### PR TITLE
[enhancement](serialize) add dcheck to ensure pb type is set

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

1. should check the pb's type is set, or the deserialize will core.
2. should not return unknown type because deserialize will core.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
