### PR TITLE
[Feature](doris compose) A tool for setup and manage doris docker cluster scaling easily

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #xxx

Add a tool to setup and manager doris compose cluster.

```
usage: doris-compose.py [-h] {up,down,ls,start,stop,restart,pause,unpause} ...

positional arguments:
  {up,down,ls,start,stop,restart,pause,unpause}
    up                  Create and upgrade doris containers. If none of --add-fe-num, --add-be-num, --fe-id, --be-id is specific, apply to all containers.
    down                Down doris containers, networks. It will also remove node from DB. If none of --fe-id, --be-id is specific, then apply to all containers.
    ls                  List running doris compose clusters.
    start               Start the doris containers. If none of --fe-id, --be-id is specific, then apply to all containers.
    stop                Stop the doris containers. If none of --fe-id, --be-id is specific, then apply to all containers.
    restart             Restart the doris containers. If none of --fe-id, --be-id is specific, then apply to all containers.
    pause               Pause the doris containers. If none of --fe-id, --be-id is specific, then apply to all containers.
    unpause             Unpause the doris containers. If none of --fe-id, --be-id is specific, then apply to all containers.

options:
  -h, --help            show this help message and exit
```

For more usage,  run 
```
python docker/runtime/doris-compose/doris-compose.py 
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by yujun777** [comment]
run builall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by gavinchou** [comment]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
