### PR TITLE
[fix](regression) create table failed in 'map_agg'

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
@xiaokang branch-2.0也需要合入

**Comment by yiguolei** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
