### PR TITLE
[Enhance](external)add prepare hive data in case

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

add support prepare hive data in suite case

like.  
hive_docker """ create database d1"""
hive_docker """ create table t1"""

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run p0

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run p0

**Review by pingchunzhang — APPROVED** [review]

**Review by pingchunzhang — APPROVED** [review]

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
