### PR TITLE
[Fix](Variant) fix element_at should return nullable if result type is nullable

### PR DESCRIPTION
**Pull request by eldenmoon**
…s nullable

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
