### PR TITLE
[Refactor](multi-catalog) Conjuncts are currently split, so refactor source code to handle split conjuncts for dict filters.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Conjuncts are currently split, so refactor source code to handle split conjuncts for dict filters.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.97 seconds
 stream load tsv:          466 seconds loaded 74807831229 Bytes, about 153 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          66.8 seconds inserted 10000000 Rows, about 149K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230703142344_clickbench_pr_171613.html

**Review by morningman — APPROVED** [review]
LGTM

**Comment by AshinGau** [comment]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
