### PR TITLE
[improvement] start|stop script files improvements

### PR DESCRIPTION
**Pull request by wolfboys**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

start|stop script files improvement

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [x] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes
    - [x] No

## Further comments

compatible with the case where the script is a soft link (reference apache tomcat)
optimize script readability
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Hi @wolfboys , please fix the checks.

**Review by jackwener — COMMENTED** [review]
ShellCheck failed, please fix it.

**Comment by adonis0147** [comment]
Hi @wolfboys , you can run `bash build-support/shell-check.sh` on your machine to help you fix the issues.

**Comment by wolfboys** [comment]
> Hi @wolfboys , you can run `bash build-support/shell-check.sh` on your machine to help you fix the issues.

ok, thx, I'll try

**Pull request closed without merging**
