### PR TITLE
[Improvement](multi-catalog)make location easier to modified, decoupling all storage with single location class

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

decoupling all storage with single location class

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run p0

**Comment by wsjz** [comment]
run p1

**Comment by wsjz** [comment]
run pipelinex_p0

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
