### PR TITLE
[Enhancement](inverted index) improve expr evaluate_inverted_index performace and remove useless code

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes
Pre-allocate vectors based on an estimated or known size in vexpr evaluated_inverted_index

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
