### PR TITLE
[BUG] fix bug for vectorized compaction

### LINKED ISSUE #9343: [Bug] Correctness check failed in vectorized compaction
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch
Introduced by PR #9280

### What's Wrong?

Correctness check failed in vectorized compaction

### What You Expected?

work well

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gabriel39**
# Proposed changes

Issue Number: close #9343

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
cc @HappenLee

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Oh, I noticed that now the compaction operation is go through `vmerge_rowsets` directly without checking if vectorized is enabled. Is it safe? @Gabriel39 @HappenLee

**Comment by Gabriel39** [comment]
> Oh, I noticed that now the compaction operation is go through `vmerge_rowsets` directly without checking if vectorized is enabled. Is it safe? @Gabriel39 @HappenLee

Config `enable_vectorized_compaction` has been added in last commit. Please review again @morningman

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
