### PR TITLE
[fix](cloud-mow) compaction may cause duplicate key if get delete bitmap from cache failed

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

To accelerate the speed of sync latest delete bitmap,  #35856 try to get the delete bitmap from `CloudTxnDeleteBitmapCache` first.
In the following situation, compaction may get empty delete bitmap and cause duplicate key:
1. compaction started
2. several load succeed during the compaction
3. compaction finished data merging and start to calculate delete bitmap generated by latest load tasks
4. compaction try to sync rowset and delete bitmap, it get delete bitmap first from `CloudTxnDeleteBitmapCache`
5. `CloudTxnDeleteBitmapCache::get_delete_bitmap()` can get txn infos from it's inner map, but cache missed when it try to get delete bitmap from LRU cache, it don't report error but returned an empty delete bitmap
6. compaction used wrong delete bitmap, duplicate key occured.

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by hust-hhb — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
