### PR TITLE
[fix](cooldown)Add ut for StoragePolicy

### LINKED ISSUE #17888: [Bug](cooldown)Add ut for StoragePolicy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

Add ut for StoragePolicy

### What You Expected?

Add ut for StoragePolicy

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #17888

## Problem summary

Add ut for StoragePolicy

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pengxiangyu** [comment]
run buildall

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run clickbench

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run feut

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run p0

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run buildall

**Comment by pengxiangyu** [comment]
run fe_ut

**Pull request closed without merging**
