### PR TITLE
[Refactor](doc)(config)(variable) use script to generate doc for FE config and session variables

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

### Background

The document of configs(FE and BE) and session variables is hard to maintain.
Because developer need to modify both code and document.
And you can see that some of config's document is missing.

So I plan to write the document of config or variables directly in code, and using
script to generate document automatically.

### How To

This CL mainly changes:

1. Add field in Config and Session Variables' annaotion

    - `description`: The description of the config or variable item. It is a String array. And first element is in Chinese, second is in English
    - `options`: the valid options if the config or variable is enum.

2. Add a scripts `docs/generate-config-and-variable-doc.sh`

    Simple run `sh docs/generate-config-and-variable-doc.sh` and it will generate docs of FE config and variables,
    And save it under `docs/admin-manual/config/fe-config.md` and `docs/advanced/variables.md`,
    both in Chinese and in English.

    And there are template markdowns for this script to read and replace with real doc content.

### TODO

1. Too many description need to be filled. I will finish them in next PR. And now the origin doc remain unchanged.
2. Find a way to check the description field of config and variables, to make sure we won't missing it.
3. Generate doc for BE config.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
