### PR TITLE
[fix](dynamic partition) data lost with very small dynamic_partition.start

### PR DESCRIPTION
**Pull request by cambyzju**
### What problem does this PR solve?

How to reproduce:
Create a table with very small `dynamic_partition.start` property, then all partitions will be dropped wrongly, and make all the data lost.

```
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.start" = "-100000",
```

Come from: https://github.com/apache/doris/pull/33712

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — DISMISSED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by yujun777** [comment]
The real root cause is the introduction of history_partition_num.  When creatting partition,  use partition_num = (-start,  history_partition_num),    but when dropping partition, use partition_num = -start.

user set a small history_partition_num and a much smaller start, then when creatting partiton, the start was skipped check.

In fact, history_partition_num and start has the same meaning (the history partition num),  only except that start = int.min means no deleting history partitions .

The introduce of history_partition_num is a bad thing.   It make the creating and dropping partition behaviour not consistent.

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
