### PR TITLE
[fix](arrow-flight-sql) Fix get Schema failed when `enable_parallel_result_sink` is false

### PR DESCRIPTION
**Pull request by xinyiZzz**
if `enable_parallel_result_sink` is true, use queryID to get Schema and fetch Result.
if `enable_parallel_result_sink` is false, use fragment 0 instance ID to get Schema and fetch Result.

```
Caused by: cfjd.org.apache.arrow.flight.FlightRuntimeException: not found arrow flight schema, maybe query has been canceled, queryid: cef21a3bd35e40c5-bd25643a1e02dbb7
	at cfjd.org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131)
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:164)
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:185)
	at cfjd.org.apache.arrow.flight.FlightStream$Observer.onError(FlightStream.java:456)
	at cfjd.org.apache.arrow.flight.FlightClient$1.onError(FlightClient.java:350)
	at cfjd.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at cfjd.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at cfjd.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at cfjd.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at cfjd.org.apache.arrow.flight.grpc.ClientInterceptorAdapter$FlightClientCallListener.onClose(ClientInterceptorAdapter.java:117)
	at cfjd.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at cfjd.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at cfjd.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at cfjd.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
```

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by xinyiZzz** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
