### PR TITLE
[enhance](catalog)Unified external partition prune interface

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

Previously, external partition cropping only supported Hive. If you want to support other types of tables, you need to understand the internal processing logic of partition pruning.

This PR abstracts the logic of partition pruning, and other tables can be implemented by simply covering a few methods of externalTable

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Unified external partition prune interface
### Release note

Unified external partition prune interface

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [x] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p0

**Review by hubgeter — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
