### PR TITLE
[fix](metrics) fix compaction_used_permits are negative numbers

### LINKED ISSUE #32437: [Bug] doris_be_compaction_used_permits 监控项为负数
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0 

### What's Wrong?

image
令牌数为负数

### What You Expected?

正常显示

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yuxuan-luo**
## Proposed changes

Issue Number: close #32437

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by yuxuan-luo** [comment]
run build all

**Review by Yulei-Yang — APPROVED** [review]
LGTM

**Comment by yuxuan-luo** [comment]
run build all

**Comment by cambyzju** [comment]
run buildall

**Pull request merged**
