### PR TITLE
[feature](merge-cloud) Refactor write path code by abstract base class

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Refactor write path code by abstract base class. Whether to use `StorageEngine` or `CloudStorageEngine` will be determined during compilation instead of runtime `config::cloud_mode` to avoid unexpected null pointer or undefined behavior issues caused by merging code.
Class that depend on `StorageEngine` but are shared by the cloud mode need to have an abstract base class. Common code should be extracted into the base class, while the code that depends on `StorageEngine` should be implemented in a `StorageEngine` mix-in class of the base class.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]
LGTM

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by platoneko** [comment]
run buildall

**Review by jackwener — APPROVED** [review]

**Pull request merged**
