### PR TITLE
[opt](test) Optimize execution time of test_s3_load case

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes
For test_s3_load, keeping the minimum set case for p0, and move all other cases to p2.

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run p0

**Comment by liaoxin01** [comment]
run external

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
