### PR TITLE
[Fix](Nereids) fix leading left outer join join constraint collect problem

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
## Proposed changes

cherry-pick pr #31387

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Pull request merged**
