### PR TITLE
[Feature-Wip](MySQL LOAD)Add trim quotes property for mysql load

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Add trim quotes property for mysql load to trim double quotes in the load files.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SaintBacchus** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.88 seconds
 stream load tsv:          470 seconds loaded 74807831229 Bytes, about 151 MB/s
 stream load json:         37 seconds loaded 2358488459 Bytes, about 60 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230314125313_clickbench_pr_114170.html

**Comment by SaintBacchus** [comment]
run p1

**Comment by SaintBacchus** [comment]
run p1

**Comment by SaintBacchus** [comment]
run p1

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run clickbench

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run arm

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run arm

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
