### PR TITLE
[refactor](move-memtable) rename proto OpenStreamSink to OpenLoadStream

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

RPC name was changed in #25883, but we forgot to change message name.
Rename proto OpenStreamSink to OpenLoadStream.

This is an incompatible change, but this feature has not been released yet.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by sollhui — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
