### PR TITLE
[optimize](function) optimize array_sort using qsort instead of bubble sort

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes
Optimize array_sort 
(1) optimize array_sort using qsort instead of bubble sort
(2) Simplifies the handling of null values, because nullable column already supports the sorting process for null value comparisons.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run builldall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.8 seconds
 stream load tsv:          440 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230327011907_clickbench_pr_120953.html

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
