### PR TITLE
[feature](merge-cloud) implement alter table property of cloud mode

### PR DESCRIPTION
**Pull request by luwei16**
Co-authored-by: Lei Zhang <1091517373@qq.com>

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
