### PR TITLE
[feature](load) enable single replica load by default

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Set session variables `enable_single_replica_load` default to true.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Pull request closed without merging**
