### PR TITLE
[log](insert-into) add log in vtablet sink

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Add log to expose potential data loss, the log will be deleted in the future.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run p0 10

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
Close for question is found.

**Pull request closed without merging**
