### PR TITLE
[Chore](planner) add error information for OnClause contain ExistsPredicates

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes
https://github.com/apache/doris/issues/18079
add error information
```sql
ERROR 1105 (HY000): errCode = 2, detailMessage = Not support OnClause contain ExistsPredicates `t`.`EMSECURITYCODE` = `t1`.`SECURITYCODE` AND `t`.`eisdel` = '0' AND `t`.`type` = '1' AND NOT EXISTS (SELECT 1 AS `1` FROM `default_cluster:test`.`index_ba_sample` s WHERE `s`.`secinnercode` = `t`.`secinnercode` AND `s`.`emsecuritycode` = `t`.`emsecuritycode` AND `s`.`type` = '0' AND `s`.`opdate` > `t`.`opdate` AND `s`.`eisdel` = '0') AND (`t`.`trademarketcode` LIKE '069001001%' OR `t`.`trademarketcode` LIKE '069001002%')
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run arm

**Comment by BiteTheDDDDt** [comment]
run arm

**Review by HappenLee — DISMISSED** [review]

**Comment by HappenLee** [comment]
Better return `Not support use subquery in ON clause`

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
