### PR TITLE
[enhancement](regression-test) cover mow and mor

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
sync to branch2.1

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by freemandealer** [comment]
run p0

**Review by gavinchou — DISMISSED** [review]

**Comment by cjj2010** [comment]
run p0

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
