### PR TITLE
[fix](load) fix nullptr in memtable limiter flush

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

`MemTableMemLimiter` may call `MemTableWriter::flush_memtable_and_wait` when it's already closed. 
In that case, memtable is `nullptr`, which causes BE core.

In #23019, the following code was removed, which causes this issue.

```cpp
        // close will reset deltawriter memtable and should deregister writer before it.
        {
            std::lock_guard<SpinLock> l(_tablets_channels_lock);
            auto tablet_channel_it = _tablets_channels.find(index_id);
            if (tablet_channel_it != _tablets_channels.end()) {
                tablet_channel_it->second->deregister_memtable_memory_limiter();
            }
        }
```

After this change, it's safe to call `flush_memtable_and_wait` even if `MemTableWriter` is closed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.26 seconds
 stream load tsv:          536 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162275284 Bytes

**Comment by kaijchen** [comment]
run clickbench

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.64 seconds
 stream load tsv:          535 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162280121 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
