### PR TITLE
[enhancement](docs) Clarify JAR file locations for JDBC catalog

### PR DESCRIPTION
**Pull request by larshelge**
This PR is clarifying some aspects of the JDBC catalog (which is really cool btw) under the lakehouse section in the docs based on the first-time experience of creating an external catalog.

* It was not very easy to understand that you need to create _two_ `jdbc_drivers` directories and put JDBC driver JAR files in each. Clarified that in the `parameter` > `driver_url` section.
* Changed `Catalog` to `catalog` starting with lower-case, as `catalog` is a concept and not a proper noun.
* In properties sections, consistently use space around equals, i.e. `"key" = "value"` instead of `"key"="value"`, as the former seems to be the convention in the docs.
* Changed "Jar" to "JAR", as it is an abbreviation.

Online page URL: https://doris.apache.org/docs/lakehouse/multi-catalog/jdbc

### CODE REVIEW

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by larshelge** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
