### PR TITLE
[Improvement](sql) support create or replace view (#20131)

### PR DESCRIPTION
**Pull request by HowardQin**
create or replace view is implemented by reusing alter view logic, 
and IF NOT EXISTS is not allowed with create or replace view.

## Proposed changes

Issue Number: #20131 

## Further comments

If the view already exists, follow alter view logic，
otherwise follow create view logic。

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Comment by HowardQin** [comment]
> run buildall

Hi, can you trigger this again?

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.36 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17160875327 Bytes

**Pull request closed without merging**
