### PR TITLE
[bugfix](hive)fix error for writing to hive

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

When the nameserver specified by defaultFS is different from the nameserver of the actual table, write failure may occur.
Moreover, when the orc writing fails, it still goes to the commit process (actually, after the writing fails, FE should be able to get the error message from BE, and should not go to the commit process)

Fix:

1. When orc writing fails, an exception is thrown. The upstream captures the exception and returns it to status for FE to obtain.
2. When creating fs in the writing process, if the writing path contains a nameserver, then use this nameserver directly to create fs. (In this way, when writing to hive, there is no need to configure defaultFS in the catalog)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
