### PR TITLE
[nereids] fix join fd computing bug

### PR DESCRIPTION
**Pull request by xzj7019**
## Proposed changes

[nereids] fix join fd computing typo bug

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xzj7019** [comment]
run buildall

**Review by keanji-x — APPROVED** [review]

**Review by starocean999 — DISMISSED** [review]

**Comment by xzj7019** [comment]
run buildall

**Comment by xzj7019** [comment]
run buildall

**Comment by xzj7019** [comment]
run buildall

**Comment by xzj7019** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
