### PR TITLE
 [fix](planner) fix orthogonal_bitmap_union_count plan : wrong PREAGGREGATION

### PR DESCRIPTION
**Pull request by lihuigang**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Execution plan display when using orthogonal_bitmap_union_count function: 

- PREAGGREGATION: OFF

- Reason: Invalid Aggregate Operator: orthogonal_bitmap_union_count

The correct plan is: PREAGGREGATION: ON

image
[](url)

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please add case in regression test.

**Comment by lihuigang** [comment]
ok~

**Comment by lihuigang** [comment]
ok~

**Comment by lihuigang** [comment]
@morningman I have added the case~

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
