### PR TITLE
[refactor](executor)Delete cpu_resource_limit

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
We want to use workload group to instead of CpuResourcelimit to manage cpu resource.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Pull request merged**
