### PR TITLE
[Feature](schema change) Support add column bitmap with default value bitmap_empty 

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run p0

**Comment by Yukang-Lian** [comment]
run cloud_p0

**Review by Hastyshell — APPROVED** [review]
LGTM

**Pull request merged**
