### PR TITLE
[enhancement](Nereids): remove LAsscom in Bushy Tree RuleSet in Branch-2.0

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

- Bushy Tree RuleSet don't need LAsscom
- fix bug: rule pattern shouldn't use same name

(cherry picked from commit 410441b5162befc690b3a4a9620762364abd59e6)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.16 seconds
 stream load tsv:          580 seconds loaded 74807831229 Bytes, about 123 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.7 seconds inserted 10000000 Rows, about 336K ops/s
 storage size: 17167533403 Bytes

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
