### PR TITLE
[fix](resource) fix can't update BE s3 resource config

### PR DESCRIPTION
**Pull request by DarvenDuan**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Doris can update resource properties in FE, but some properties of resource on BE can't be modified.

### Check List (For Committer)

- Test 

    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Review by caiconghui — DISMISSED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
cloud_p0

**Comment by DarvenDuan** [comment]
run cloud_p0

**Review by GoGoWen — DISMISSED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run buildall

**Review by caiconghui — APPROVED** [review]
LGTM

**Review by GoGoWen — APPROVED** [review]
LGTM

**Pull request merged**
