### PR TITLE
[opt](inverted index) Optimize sequential phrase query logic

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1.  Set enable_phrase_query_sequential_opt = true to optimize conjunction matching in sequential phrase queries.
2.  For example, match_phrase "赵丽颖 中国 ~20+" ensures that "赵丽颖" appears consecutively, and "中国" also appears consecutively, while maintaining the semantics of sequential phrase queries.

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
