### PR TITLE
[Fix](profile) do not send export profile when enable_profile=false.

### PR DESCRIPTION
**Pull request by dutyu**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by carlvinhust2012** [comment]
Can you add some regression test?

**Comment by dutyu** [comment]
> Can you add some regression test?

Hi, i will add some test in FE UT later.

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.87 seconds
 load time: 498 seconds
 storage size: 17123187350 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230117051201_clickbench_pr_81788.html

**Comment by dutyu** [comment]
> Can you add some regression test?

Hi, i have added some ut.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
