### PR TITLE
[FIX](array)fix array with inverted index

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
see also for branch-2.1:  https://github.com/apache/doris/pull/35837
and master: 
https://github.com/apache/doris/pull/34766
https://github.com/apache/doris/pull/35086
https://github.com/apache/doris/pull/34683
https://github.com/apache/doris/pull/34076

Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run feut

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Pull request merged**
