### PR TITLE
[Enhancement] Remove minidump

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Minidump is not useful in a real online environment, instead it introduces additional errors.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
> Does we should remove `breakpad`?

done, you are right

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by gaodayue** [comment]
> Minidump is not useful in a real online environment, instead it introduces additional errors.

@xinyiZzz What is the additional errors introduced by minidump? I think minidump is still useful in scenarios where coredump is too large to be enabled, what's the alternative to minidump in those scenarios?

**Pull request merged**
