### PR TITLE
[docs][fix][fix some confusing doc content]

### PR DESCRIPTION
**Pull request by daikon12**
# Proposed changes
1.  XXX of Doris --> Doris on XXX
2. brpc_port* --> brpc_port   http_port * -> http_port
3. (FE <--> FE，用户)  -->  (FE <--> FE，用户 <--> FE)
    
## Problem Summary:
Due to the inconsistency of the documents, there will be some doubts when reading. It is recommended to make relevant adjustments,  increase the readability of the documents

## Checklist(Required)

1. Does it affect the original behavior: (No)
4. Has unit tests been added: (No)
5. Has document been added or modified: (Yes)
6. Does it need to update dependencies: (No)
7. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by daikon12** [comment]
您好！邮件我已收到，我会尽快处理的

**Review by EmmyMiao87 — APPROVED** [review]
Thanks for your first pr ~

**Comment by daikon12** [comment]
> PR approved by anyone and no changes requested.



> Thanks for your first pr ~

thank you very much for the guide

**Pull request merged**
