### PR TITLE
[feature](pipeline) check nullable in SET operator

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

There are some issues where planning problems lead to discrepancies between the nullable attribute of the computed column and the expected output column.

```
[INTERNAL_ERROR]SET operator expects a nullalbe : true column in column 0, but the computed output is a nullable : false column
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
