### PR TITLE
[improvement](jdbc catalog) Added support for Oracle Raw type

### PR DESCRIPTION
**Pull request by zy-kkk**
In previous versions, we adopted the strategy of reading the object address for Oracle's raw type, which would lead to unstable and meaningless results. Here I changed it to read hexadecimal or UTF8

### CODE REVIEW

**Comment by zy-kkk** [comment]
run feut

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
