### PR TITLE
[Chore](MoW) remove unused code about rowset tree

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Due to refactoring, the code for the rowset tree is no longer in use.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall.

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
