### PR TITLE
[fix](regresstest) move nested case to p2 and fix cases

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
move three_level_nestedtypes_with_s3data/two_level_nestedtypes_with_s3data to p2 which is time consuming.
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
