### PR TITLE
[Fix](Variant) implement resize and set num_rows right when `subcolumns` is empty

### PR DESCRIPTION
**Pull request by eldenmoon**
## Proposed changes
Set rows correct when subcolumns is empty, and implement resize method with correct semantic
This fix the potential crash with stack bellow
```
6# doris::vectorized::ColumnObject::get(unsigned long, doris::vectorized::Field&) const at /root/doris/be/src/vec/columns/column_object.cpp:841
7# doris::vectorized::ColumnObject::operator[](unsigned long) const at /root/doris/be/src/vec/columns/column_object.cpp:838
8# doris::vectorized::ColumnObject::insert_from(doris::vectorized::IColumn const&, unsigned long) in /home/work/unlimit_teamcity/TeamCity/Agents/20240725170551agent_172.16.0.48_1/work/60183217f6ee2a9c/output/be/lib/doris_be
9# doris::vectorized::ColumnObject::insert_indices_from(doris::vectorized::IColumn const&, unsigned int const*, unsigned int const*) at /root/doris/be/src/vec/columns/column_object.cpp:1581
```
Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
Proposed changes need to be filled

**Comment by eldenmoon** [comment]
> Proposed changes need to be filled

done

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by eldenmoon** [comment]
Block the regression-test pipeline, so i merged it

**Pull request merged**
