### PR TITLE
[fix](Hive bitmap udf) NPE error when mapreduce task only has map task

### LINKED ISSUE #17539: [Bug] BitmapUnion and toBitmap UDAF throws NPE when the mapreduce job only has map task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.3-rc02

### What's Wrong?

When using the UDF in hive to get a doris bitmap representation of a column (e.g. bitmap_union, to_bitmap), an NPE occurs if the submitted mapreduce job only has map task, no reduce  task. The exception stack is as below:
img_v2_1873e203-a34a-468a-b5e5-8a4a7efd653g

This is because in BitmapUnionUDAF/ToBitmapUDAF, the `Mode` should be `Mode.COMPLETE`, so the `BinaryObjectInspector inputOI` will not be initialized here:
image

### What You Expected?

run successfully and get doris representation bitmap result.

### How to Reproduce?

e.g. creating as temporary function, query and run with only map task, no reduce task

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xiaoDjun**
# Proposed changes

Issue Number: close #17539 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
Hi @xiaoDjun , please rebase to pass the check

**Comment by morningman** [comment]
run buidall

**Comment by morningman** [comment]
run buildall

**Pull request closed without merging**
