### PR TITLE
[fix](export) fix timeout property not work for export job

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by BePPPower** [comment]
Please modify the description of `Export` on the corresponding document.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
