### PR TITLE
[enhancement](http) add fail reply for failed submitting tasks in single-replica-download

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Currently in single-replica-download, if tasks submitted to thread pool failed, the `CHECK` way may cause a crash when server is busy and is not user-friendly as well.So reply internal server error to user when tasks submitted failed.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
