### PR TITLE
[fix](inverted index) multi_match supports any, all, phrase.

### PR DESCRIPTION
**Pull request by zzzxl1993**
1. Implemented multi_match query support for 'any', 'all', and 'phrase' types as the second to last argument.
2. select * from tbl where multi_match(c1, c2, 'any | all | phrase | phrase_prefix', 'x');

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
