### PR TITLE
[enhancement](exception) pageio method should return error when allocate memory failed

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

1. pageio method should return error when allocate memory failed just for point query.
2. variant parsing logic should return error when allocate memory failed.

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
