### PR TITLE
fix bug colocate join table can't repaired

### PR DESCRIPTION
**Pull request by dh-cloud**
cluster info: 4 hosts (10.35.15.164,165,206,207), 8 bes , table with colocate_with, 3 replicas

version: 0.14

we found colocate join table replica can't repaired.   the tablet status is "COLOCATE_MISMATCH", schedule failed log is "unable to find dest path for new replica"

show can't repaired tablet info is :

703694    10008    1    0    1    0    -1    0        -1    0    0    NORMAL    false    -1    -1    http://10.35.25.165:8040/api/meta/header/703691/-1    http://10.35.25.165:8040/api/compaction/show?tablet_id=703691&schema_hash=-1
729811    10004    1    0    1    0    -1    0        -1    0    0    NORMAL    false    -1    -1    http://10.35.25.207:8040/api/meta/header/703691/-1    http://10.35.25.207:8040/api/compaction/show?tablet_id=703691&schema_hash=-1
735553    10003    1    0    1    0    -1    0        -1    0    0    NORMAL    false    -1    -1    http://10.35.25.206:8140/api/meta/header/703691/-1    http://10.35.25.206:8140/api/compaction/show?tablet_id=703691&schema_hash=-1
740612    10006    1    0    1    0    -1    0        -1    0    0    NORMAL    false    -1    -1    http://10.35.25.164:8040/api/meta/header/703691/-1    http://10.35.25.164:8040/api/compaction/show?tablet_id=703691&schema_hash=-1

repair mis_match status tablet, need clone replica to other host , but each host already have replica, so it always schedule failed.

so we set should set tablet status to COLOCATE_REDUNDANT, delete one replica, then we can repair mis_match tablet

### CODE REVIEW

**Comment by morningman** [comment]
Why you deploy 2 BEs on one host?

**Comment by dh-cloud** [comment]
> Why you deploy 2 BEs on one host?
put be on one ssd，we test 2 num be on one host, the performance is the better.
may be test case is not good，we should test again next

**Comment by dh-cloud** [comment]
> Why you deploy 2 BEs on one host?

we put one be on one disk，test 2 bes on one host, the performance is better
may be the test case is not good。 next we should put one be date on  all disks，and 1 be on one host，test the performance

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
