### PR TITLE
[Fix][Refactor](mutli-catalog) Fix 'not member call on null pointer of type doris::TextConverter' error in ubsan env and code refactoring.

### LINKED ISSUE #19848: [Bug] (ubsan) member call on null pointer of type 'doris::TextConverter *'.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

ubsan env:
runtime error： member call on null pointer 
doris/be/src/exec/text_converter.cpp:47:21: runtime error: member call on null pointer of type 'doris::TextConverter *'
doris/be/src/vec/exec/format/parquet/vparquet_group_reader.cpp:569:31: runtime error: member call on null pointer of type 'doris::TextConverter'

### What You Expected?

not throw error.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kaka11chen**
# Proposed changes

Issue Number: close #19848

## Problem summary

Fix 'not member call on null pointer of type doris::TextConverter' error in ubsan env and refactor text converter.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Review by yiguolei — COMMENTED** [review]
could you add some regression test?

**Comment by kaka11chen** [comment]
> could you add some regression test?

current emr tests already cover these cases.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
