### PR TITLE
[opt](function)avoid virtual function calls in geo functions

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

```
mysql [test10]>select count(st_distance_sphere(db, db, db, db)) from double_ranges;
+-------------------------------------------+
| count(st_distance_sphere(db, db, db, db)) |
+-------------------------------------------+
|                                         0 |
+-------------------------------------------+
1 row in set (1.46 sec)



mysql [test10]>select count(st_distance_sphere(db, db, db, db)) from double_ranges;
+-------------------------------------------+
| count(st_distance_sphere(db, db, db, db)) |
+-------------------------------------------+
|                                  50000000 |
+-------------------------------------------+
1 row in set (1.14 sec)
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
