### PR TITLE
[Fix](Parquet Reader) fix parquet read issue

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by AshinGau** [comment]
LGTM

**Review by AshinGau — DISMISSED** [review]

**Comment by GoGoWen** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
