### PR TITLE
[Chore](function) check nested function on AggregateFunctionNullBaseInline

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
check nested function on AggregateFunctionNullBaseInline

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
