### PR TITLE
[Fix](merge-on-write) throw exception when the user don't specify the insert columns in insert statement for partial update

### PR DESCRIPTION
**Pull request by bobhan1**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run clickbench

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
