### PR TITLE
[improvement](cloud)Not allowed to operate internal_schema database

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

Inherited from： https://github.com/apache/doris/pull/29790
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
