### PR TITLE
[fix](broker-load) fix error in broker-load with read_json_by_line

### PR DESCRIPTION
**Pull request by wyxxxcat**
## Proposed changes

Issue Number: close #xxx

before:
```
mysql> select * from user_info;
Empty set (0.00 sec)

mysql> LOAD LABEL local_load_label (
    ->     DATA INFILE("s3://wyxxxcardoris/test/data_by_line.json")
    ->     INTO TABLE user_info
    ->     (id, name, age)
    ->     PROPERTIES
    ->     (
    ->         "read_json_by_line" = "true"
    ->     )
    -> )
    -> WITH s3
    -> (
    ->     "AWS_ACCESS_KEY" = "xxx",
    ->     "AWS_SECRET_KEY" = "xxx",
    ->     "AWS_ENDPOINT" = "xxx",
    ->     "AWS_REGION" = "xxx"
    -> )
    -> PROPERTIES
    -> (
    ->     "timeout" = "3600"
    -> );
Query OK, 0 rows affected (0.15 sec)

mysql> select * from user_info;
+------+-------+------+
| id   | name  | age  |
+------+-------+------+
|    1 | Alice |   25 |
+------+-------+------+
1 row in set (0.04 sec)
```

now:
```
mysql> select * from user_info;
Empty set (0.01 sec)

mysql> LOAD LABEL local_load_label (
    ->     DATA INFILE("s3://wyxxxcardoris/test/data_by_line.json")
    ->     INTO TABLE user_info
    ->     (id, name, age)
    ->     PROPERTIES
    ->     (
    ->         "read_json_by_line" = "true"
    ->     )
    -> )
    -> WITH s3
    -> (
    ->     "AWS_ACCESS_KEY" = "xxx",
    ->     "AWS_SECRET_KEY" = "xxx",
    ->     "AWS_ENDPOINT" = "xxx",
    ->     "AWS_REGION" = "xxx"
    -> )
    -> PROPERTIES
    -> (
    ->     "timeout" = "3600"
    -> );
Query OK, 0 rows affected (0.62 sec)

mysql> select * from user_info;
+------+---------+------+
| id   | name    | age  |
+------+---------+------+
|    2 | Bob     |   30 |
|    4 | John    |   29 |
|    5 | Mars    |   17 |
|    1 | Alice   |   25 |
|    3 | Charlie |   35 |
+------+---------+------+
5 rows in set (0.10 sec)
```

### CODE REVIEW

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run p0

**Comment by wyxxxcat** [comment]
run p0

**Comment by wyxxxcat** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
