### PR TITLE
[fix](Nereids) tablet prune wrong when decimal value scale is nagtive

### PR DESCRIPTION
**Pull request by morrySnow**
we use unscaled value of BigDecimal in tablet prune. So we need to ensure BigDecimal's precision and scale is same with the literal contains it.

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run could_p1

**Review by starocean999 — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
