### PR TITLE
[enhancement](mysql) Add have_query_cache variable to be compatible with old mysql client

### LINKED ISSUE #20774: [BUG]  Unknow system variable 'have_query_cache'  caused by mysql-jdbc
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

mysql-java-connector: 5.1.13 
mysql: 5.7
envrionment: spring-boot、DruidDatasource
doris ： 1.1.5

### What's Wrong?

image

As you can see, when we use mysql version 5.1.13, there will be an error that the have_query_cache parameter is missing. This will disappear after upgrading to 8.x. However, in our company, the mysql version has been fixed to 5.1.13 and cannot be easily upgraded, otherwise business production problems will occur.

### What You Expected?

We hope that the community can solve this parameter problem and be compatible with the java connector of the lower version of mysql 5.1.x

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #20774

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.48 seconds
 stream load tsv:          499 seconds loaded 74807831229 Bytes, about 142 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17167291801 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711010438_clickbench_pr_176089.html

**Comment by zy-kkk** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.41 seconds
 stream load tsv:          442 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          25.7 seconds inserted 10000000 Rows, about 389K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711031734_clickbench_pr_176176.html

**Pull request merged**
