### PR TITLE
[fix](dbt) fix dbt doris bug that appeared in annotated models and table column comment bug

### PR DESCRIPTION
**Pull request by catpineapple**
## Proposed changes

Issue Number: close #xxx

fix dbt doris bug :
1. appeared in annotated models 
2.  table column comment bug

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by catpineapple** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by catpineapple** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by LemonLiTree — APPROVED** [review]

**Pull request merged**
