### PR TITLE
[Regression](Array) add more array test

### PR DESCRIPTION
**Pull request by eldenmoon**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]

**Review by kpfly — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
Rethink we really do the work now? I think should do it after we support the array literal. we can do array function test more friendly and easy.
like `selet array_min([1,2,3)`

**Comment by adonis0147** [comment]
> Rethink we really do the work now? I think should do it after we support the array literal. we can do array function test more friendly and easy. like `selet array_min([1,2,3)`


I think we should cover these two ways.
1. insert and select
2. literals

**Review by dataroaring — APPROVED** [review]

**Pull request merged**
