### PR TITLE
[fix](Nereids) null type in result set will be cast to tinyint

### PR DESCRIPTION
**Pull request by morrySnow**

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run external

**Comment by morrySnow** [comment]
run p0

**Review by starocean999 — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
