### PR TITLE
[docs](data-model):add sql statements to import data

### PR DESCRIPTION
**Pull request by vinlee19**
## Problem summary

 Add sql statements to import data

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — COMMENTED** [review]
Please modify the English document simultaneously

**Comment by vinlee19** [comment]
> Please modify the English document simultaneously

I've modified the English document. Thank you!

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
