### PR TITLE
[change](index) change enable_create_bitmap_index_as_inverted_index default to true

### PR DESCRIPTION
**Pull request by xiaokang**
When an user create a new BITMAP INDEX, an INVERTED INDEX will be created instead, since INVERTED INDEX is ready to replace BITMAP INDEX. 
The transformation is transparent to user and nothing need to be done by user. Already existed BITMAP INDEX will NOT be changed and can be used as before.

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
