### PR TITLE
[fix](load)when enable_single_replica_load = true, load not failed a…

### PR DESCRIPTION
**Pull request by xuwei0912**
…s expected

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by neuyilan — APPROVED** [review]
LGTM

**Review by dataroaring — CHANGES_REQUESTED** [review]
single replica does not work as this, you should open the config in be too.

**Comment by dataroaring** [comment]
Could you explain it more?

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
