### PR TITLE
[fix](docs) Fix delete statement in partition mode

### PR DESCRIPTION
**Pull request by echo-YK**
## Proposed changes

update the PARTITION keyword of the DELETE statement in the document

## Further comments

Change the keyword 'Partitions' to' Partitions'

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by xy720 — COMMENTED** [review]
This may be a syntax conflict bug

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request closed without merging**
