### PR TITLE
[feature](jsonb)support json_length and json_contains function

### PR DESCRIPTION
**Pull request by LemonLiTree**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by eldenmoon — DISMISSED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run p0

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
