### PR TITLE
[bug](function) fix regexp_extract_all can't handle empty str

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
regexp_extract_all need return empty result when input is empty str.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by zhangstar333** [comment]
run p0

**Pull request merged**
