### PR TITLE
[fix] the nullable info is lost in ifnull expr

### PR DESCRIPTION
**Pull request by starocean999**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

The ifnull(col_left, col_right) is converted to if(isnull(col_left), col_right, col_left). the col_left's nullable info is lost during converting.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
Do you have any case to repeat the error?

```java
            if (children.get(0).isNullable()) {
                return children.get(1).isNullable();
            }
```
The nullable here needs to be consistent with `FE`, I think we should do more change at `ifnull`.
This is the modification of get_return_type_impl, we also need to implement similar logic in execute_impl
图片

**Comment by starocean999** [comment]
> Do you have any case to repeat the error?
> 
> ```java
>             if (children.get(0).isNullable()) {
>                 return children.get(1).isNullable();
>             }
>             return false;
> ```
> 
> The nullable here needs to be consistent with `FE`, I think we should do more change at `ifnull`. This is the modification of get_return_type_impl, we also need to implement similar logic in execute_impl 图片

thx, the be is modified and consistent with fe now.

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
