### PR TITLE
[Feature](GA)Latest-Master-Code-Check

### PR DESCRIPTION
**Pull request by CalvinKirs**
A GitHub Action to check if a pull request includes the latest code of the master branch.

This GA will be triggered during review and commit.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
latest code check

**Review by CalvinKirs — COMMENTED** [review]
trigger

**Comment by CalvinKirs** [comment]
latest code check

**Review by CalvinKirs — COMMENTED** [review]
trigger

**Comment by CalvinKirs** [comment]
latest code check

**Comment by CalvinKirs** [comment]
"latest code check"

**Comment by CalvinKirs** [comment]
latest-code-check

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by yiguolei** [comment]
> It can't avoid such issue, because the merge time may be far behind the commit time. This GA can't handle that issue.

Although it could not prevent this issue. But it could prevent many useless p0 runnings, and I think we could not solve this issue completely because it need more than 1 hour to run p0 and there is some conflict. we may only merge 10 pr one day

**Review by yiguolei — APPROVED** [review]
lgtm

**Comment by CalvinKirs** [comment]
> It can't avoid such issue, because the merge time may be far behind the commit time. This GA can't handle that issue.↳

When a development branch falls behind the main branch, even if there are no conflicts, bugs may still arise when the development branch is merged into the main branch. Git can only detect conflicts, but it is powerless when our code conflicts logically.

This pull request will address this issue as much as possible, but it cannot solve it completely. However, at least when a contributor creates a pull request, the development branch will not fall too far behind the main branch.

Looking back over the past few months, we have had too many meaningless test cases. When the code falls behind the main branch, running test cases may be meaningless. In addition, test cases are a heavyweight resource and should be avoided as much as possible when the code is not yet ready. Therefore, when the development branch falls behind the main branch, we should try to avoid running test cases.

**Comment by CalvinKirs** [comment]
Or, we check whether the latest code is merged before each run of TC?

**Comment by CalvinKirs** [comment]
At present, TC will run again after merging the latest code, so this change may not be meaningful.

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
lgtm

**Comment by CalvinKirs** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
