### PR TITLE
(enhance)(InternalQuery) Support to collect profile for intenal query

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

Issue Number: close #xxx

The profile information is ignored even though enable profile for internal query. This pr adds one config to control whether collecting the profile for internal query.

image

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
