### PR TITLE
[Bug](runtime-filter) send ignored rf when hash join build closed early

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
send ignored rf when hash join build closed early to avoid runtime filter sync/merge error
Follow-up : https://github.com/apache/doris/pull/41292

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
