### PR TITLE
[enhance](cooldown) Improve cooldown logs

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Cooldown meta not found  in `_follow_cooldowned_data` is usually an expected phenomenon rather than data loss, because cooldown replica may not complete uploading yet. This PR reduces log level to `INFO` to avoid misleading users.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
