### PR TITLE
[test](case)  Remove sensitive information in k8s deploy test

### PR DESCRIPTION
**Pull request by yongjinhou**
## Proposed changes

Issue Number: close #xxx

Remove sensitive information from the k8s deployment test, otherwise the code base security check fails.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run p0

**Review by xy720 — APPROVED** [review]
LGTM

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Pull request merged**
