### PR TITLE
[Performance](json reader) optimize filling default values

### PR DESCRIPTION
**Pull request by eldenmoon**
Add a faster path for filling default values, since looking up value map is relatively slow

Benchmark:
json load 30s->20s

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
