### PR TITLE
[opt](inverted index) Add null document interface to optimize empty s…

### PR DESCRIPTION
**Pull request by qidaye**
…tring indexing

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run pipelinex

**Comment by qidaye** [comment]
run pipelinex

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
