### PR TITLE
[improvement](balance) don't balance tablet which has unfinish alter job

### PR DESCRIPTION
**Pull request by yujun777**
Improvement:   don't balance tablets that have unfished alter job.

Also fix partition rebalancer may balance colocate tablets.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
