### PR TITLE
[fix](cloud) Fix CloudTabletRebalancer npe

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

Issue Number: close #xxx

fix
```
2024-06-09 02:47:43,945 ERROR (cloud tablet rebalancer|37) [Daemon.run():118] daemon thread got exception. name: cloud tablet rebalancer
java.lang.NullPointerException: null
        at com.selectdb.cloud.catalog.CloudTabletRebalancer.checkDecommissionState(CloudTabletRebalancer.java:357) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.selectdb.cloud.catalog.CloudTabletRebalancer.runAfterCatalogReady(CloudTabletRebalancer.java:221) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
```

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by deardeng** [comment]
run buildall

**Pull request merged**
