### PR TITLE
[fix](multi-table-load) fix fe log too much when using multi table load

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Log introduce by https://github.com/apache/doris/pull/32716

There is lots of log in FE log when using multi table load:
```
2024-06-18 11:13:05,360 INFO (thrift-server-pool-3645|93075) [FrontendServiceImpl.streamLoadMultiTablePut():2042] receive stream load multi table put requ
est result: TStreamLoadMultiTablePutResult(status:TStatus(status_code:OK), pipeline_params:[TPipelineFragmentParams(protocol_version:V1, query_id:TUniqueI
d(hi:8161224298039997004, lo:3829166682228620956), fragment_id:185, per_exch_num_senders:{}, desc_tbl:TDescriptorTable(slotDescriptors:[TSlotDescriptor(id
:0, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DATEV2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullInd
icatorByte:0, nullIndicatorBit:-1, colName:l_shipdate, slotIdx:0, isMaterialized:true, col_unique_id:0, is_key:true, need_materialize:true, is_auto_increm
ent:false, primitive_type:DATEV2), TSlotDescriptor(id:2, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:BIGINT))]
, byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_orderkey, slotIdx:3, isMaterialized:true, col_unique_id:
1, is_key:true, need_materialize:true, is_auto_increment:false, primitive_type:BIGINT), TSlotDescriptor(id:4, parent:0, slotType:TTypeDesc(types:[TTypeNod
e(type:SCALAR, scalar_type:TScalarType(type:BIGINT))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_lin
enumber, slotIdx:4, isMaterialized:true, col_unique_id:2, is_key:true, need_materialize:true, is_auto_increment:false, primitive_type:BIGINT), TSlotDescri
ptor(id:6, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:BIGINT))], byte_size:-1), columnPos:-1, byteOffset:-1, 
nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_partkey, slotIdx:5, isMaterialized:true, col_unique_id:3, is_key:true, need_materialize:true, is_auto_
increment:false, primitive_type:BIGINT), TSlotDescriptor(id:8, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:BIG
INT))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_suppkey, slotIdx:6, isMaterialized:true, col_uniqu
e_id:4, is_key:true, need_materialize:true, is_auto_increment:false, primitive_type:BIGINT), TSlotDescriptor(id:10, parent:0, slotType:TTypeDesc(types:[TT
ypeNode(type:SCALAR, scalar_type:TScalarType(type:DECIMAL64, precision:15, scale:2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nu
llIndicatorBit:-1, colName:l_quantity, slotIdx:7, isMaterialized:true, col_unique_id:5, is_key:false, need_materialize:true, is_auto_increment:false, prim
itive_type:DECIMAL64), TSlotDescriptor(id:12, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DECIMAL64, precision
:15, scale:2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_extendedprice, slotIdx:8, isMaterialized:
true, col_unique_id:6, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:DECIMAL64), TSlotDescriptor(id:14, parent:0, slotType:
TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DECIMAL64, precision:15, scale:2))], byte_size:-1), columnPos:-1, byteOffset:-1, null
IndicatorByte:0, nullIndicatorBit:-1, colName:l_discount, slotIdx:9, isMaterialized:true, col_unique_id:7, is_key:false, need_materialize:true, is_auto_in
crement:false, primitive_type:DECIMAL64), TSlotDescriptor(id:16, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:D
ECIMAL64, precision:15, scale:2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_tax, slotIdx:10, isMat
erialized:true, col_unique_id:8, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:DECIMAL64), TSlotDescriptor(id:18, parent:0,
 slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:VARCHAR, len:1))], byte_size:1), columnPos:-1, byteOffset:-1, nullIndicator
Byte:0, nullIndicatorBit:-1, colName:l_returnflag, slotIdx:11, isMaterialized:true, col_unique_id:9, is_key:false, need_materialize:true, is_auto_incremen
t:false, primitive_type:VARCHAR), TSlotDescriptor(id:20, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:VARCHAR, 
len:1))], byte_size:1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_linestatus, slotIdx:12, isMaterialized:true, col_
unique_id:10, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:VARCHAR), TSlotDescriptor(id:22, parent:0, slotType:TTypeDesc(t
ypes:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DATEV2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1,
 colName:l_commitdate, slotIdx:1, isMaterialized:true, col_unique_id:11, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:DATE
V2), TSlotDescriptor(id:24, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DATEV2))], byte_size:-1), columnPos:-1
, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_receiptdate, slotIdx:2, isMaterialized:true, col_unique_id:12, is_key:false, need_mat
erialize:true, is_auto_increment:false, primitive_type:DATEV2), TSlotDescriptor(id:26, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_t
ype:TScalarType(type:VARCHAR, len:25))], byte_size:25), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_shipinstruct, slo
tIdx:13, isMaterialized:true, col_unique_id:13, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:VARCHAR), TSlotDescriptor(id:
28, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:VARCHAR, len:40))], byte_size:40), columnPos:-1, byteOffset:-1
, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_shipmode, slotIdx:14, isMaterialized:true, col_unique_id:14, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:VARCHAR), TSlotDescriptor(id:30, parent:0, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:VARCHAR, len:44))], byte_size:44), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_comment, slotIdx:15, isMaterialized:true, col_unique_id:15, is_key:false, need_materialize:true, is_auto_increment:false, primitive_type:VARCHAR), TSlotDescriptor(id:1, parent:1, slotType:TTypeDesc(types:[TTypeNode(type:SCALAR, scalar_type:TScalarType(type:DATEV2))], byte_size:-1), columnPos:-1, byteOffset:-1, nullIndicatorByte:0, nullIndicatorBit:-1, colName:l_shipdate, slotIdx:0, isMaterialized:true, col_unique_id:0, is_key:true, need_materialize:true, is_auto_increment:false, primitive_t
```
Due to the presence of a large number of such logs, the speed of the log file rolling up  is very fast.

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by CalvinKirs — DISMISSED** [review]

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
