### PR TITLE
[opt](ci) start dockers in parallel 

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
Start docker in parallel to reduce external pipeline time

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Review by shuke987 — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
