### PR TITLE
[improve](json_reader) add prompt when all fields is null

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

```
curl --location-trusted -u root:"" -T data.json  -H"format:json" http://127.0.0.1:8030/api/db/user1/_stream_load -H "jsonpaths: [\"$.NAME\", \"$.AGE\", \"$.AGENT_ID\"]"
```

before:
```
Reason: All fields is null, this is a invalid row.. src line [{"name":"Name 1","age":21,"agent_id":"1"}
]; 
```

after:
```
Reason: There is no column matching jsonpaths in the json file, columns:[name, age, agent_id, ], jsonpaths:["$.NAME", "$.AGE", "$.AGENT_ID"], please check columns and jsonpaths. src line [{"name":"Name 1","age":21,"agent_id":"1"}
]; 
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
