### PR TITLE
[improvement](paimon)Using table serialization on the jni side

### PR DESCRIPTION
**Pull request by wuwenchi**
advantage:
1. Reduce the access to HMS and HDFS on the JNI side.
2. There will be no inconsistency between the fe and be tables.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run external

**Review by morningman — COMMENTED** [review]
Need consider the upgrade compatibility

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by hubgeter — APPROVED** [review]

**Pull request merged**
