### PR TITLE
[style] clang-format all c++ code

### PR DESCRIPTION
**Pull request by chenlinzhong**
# Proposed changes

Issue Number:  

## Problem Summary:

- now all pr failed in "BE Code Formatter / Clang Formatter" check
- sh build-support/clang-format.sh  to  clang-format all c++ code 

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
@chenlinzhong please rebase because #9280 has been merged

**Comment by morningman** [comment]
And you'd better send an email to dev@doris to notice others.
Because this PR may be conflict with all other PRs.

**Comment by morningman** [comment]
hi @chenlinzhong , please also add this:
https://github.com/apache/incubator-doris/blob/c132abd2bdbbd6e86b61eedc84473a891fb69880/.asf.yaml#L37-L44

Enable this `# - Clang Formatter`

**Comment by chenlinzhong** [comment]
> 

done

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
