### PR TITLE
[fix](pipeline) Update check-pr-if-need-run-build.sh

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

fix the shell script to check if PR has added files，
bug was introduced by PR #23332

### CODE REVIEW

**Comment by hello-stephen** [comment]
run compile

**Comment by hello-stephen** [comment]
run p0

**Comment by hello-stephen** [comment]
run p1

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
