### PR TITLE
[fix](regression) add `"enable_unique_key_merge_on_write" = "false"` for cases that want to use MOR unique table

### PR DESCRIPTION
**Pull request by bobhan1**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by eldenmoon — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
https://github.com/apache/doris/pull/28105

**Pull request closed without merging**
