### PR TITLE
[fix](group commit) Fix insert_group_commit_into_unique_sync_mode

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

The `insert_group_commit_into_unique_sync_mode` is failed sometimes because of `PUBLISH_TIMEOUT`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
