### PR TITLE
[Bug][Function] pass intermediate argument list to be

### LINKED ISSUE #10641: [Bug] Core dump when aggregate function with no group by
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Some query like `select max_by(k1,k2) from test` will meet core dump. 
The aggregate function should have more than one arguments.

### What You Expected?

fix it.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #10641

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — COMMENTED** [review]
Why we need to pass all parameters for agg in both phase? I'm still confused in this. Intuitively, I think the original logics is better understood.

I tried to resolve this problem caused by `min_by` and `max_by` before. I think a better way is to support variadic arguments for aggregate functions just like the simple functions. We can obtain functions by different names by this way. What do you think?

**Comment by BiteTheDDDDt** [comment]
> 

We should get same argument at two diffrent aggregate phase, then we can create same specific function.
Even if we support variadic aggregate functions, we still need the correct parameter list.

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
