### PR TITLE
[doc](partial update) add complete doc for partial update

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

add complete doc for partial update

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Pull request merged**
