### PR TITLE
[fix](cloud) fix file cache missing when compaction and improve bvars

### PR DESCRIPTION
**Pull request by freemandealer**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [ ] No.
    - [x] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run beut

**Comment by freemandealer** [comment]
run cloud_p0

**Review by gavinchou — DISMISSED** [review]

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
run cloud_p0

**Comment by freemandealer** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
