### PR TITLE
[optimize](information_schema) optimize the data type of table information_schema.rowsets

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

Issue Number: close #xxx

The original data type of column `CREATION_TIME` and `NEWEST_WRITE_TIMESTAMP` in table `information_schema.rowsets` is bigint, which is not read friendly，change to DATETIME is more reasonable, and we can use time range to filter data more easily:
`select * from information_schema.rowsets where CREATION_TIME > '2024-05-10 00:00:00'`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run feut

**Comment by DarvenDuan** [comment]
run cloud

**Comment by DarvenDuan** [comment]
run performance

**Comment by DarvenDuan** [comment]
run cloud_p0

**Comment by DarvenDuan** [comment]
run performance

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Review by caiconghui — APPROVED** [review]
LGTM

**Review by GoGoWen — APPROVED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run performance

**Comment by DarvenDuan** [comment]
run performance

**Pull request merged**
