### PR TITLE
[Bug](join) fix nested loop join some problems

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
./run-regression-test.sh --run -d nereids_syntax_p0 -s sub_query_correlated

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]

**Pull request merged**
