### PR TITLE
[fix](group commit)fix group commit regresstion test

### PR DESCRIPTION
**Pull request by hust-hhb**
now group commit insert into regresstion test is take too much time, bacasue of loading big data source, which will lead to pipeline running time out. This pr will reduce data source size and add some exception processing.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
