### PR TITLE
[Improvement](auditlog) add column catalog for audit log and audit log table

### PR DESCRIPTION
**Pull request by Yulei-Yang**
image

If you get error when building audit loader plugin after merge this pr, build doris fe first and use below commands to update dependent jars and then build again
mvn install:install-file -DgroupId=org.apache.doris -DartifactId=fe-core -Dversion=1.2-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/doris-fe.jar
mvn install:install-file -DgroupId=org.apache.doris -DartifactId=fe-common -Dversion=1.2-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/fe-common-1.2-SNAPSHOT.jar

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run pipelinex

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run pipelinex

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run checkstyle

**Comment by Yulei-Yang** [comment]
run fecodestyle

**Comment by Yulei-Yang** [comment]
run buildall

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
@Yulei-Yang hello, could you please backport this commit to branch-2.0 and update our mvn repository https://repository.apache.org/content/repositories/snapshots/org/apache/doris/fe/2.0-SNAPSHOT/

Many users have reported that they could not compile this plugin.
Or we may need to revert this pr since this problem is in the way of our new release.

**Pull request merged**
