### PR TITLE
[bug](test) fix regression test of jdbc postgresql table core

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.96 seconds
 load time: 466 seconds
 storage size: 17172259636 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221119073704_clickbench_pr_49068.html

**Review by morningman — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
why the fix just fix the case ?

**Comment by morningman** [comment]
> why the fix just fix the case ?

I discuss it with @zhangstar333 , this is because currently, we have to make sure that the column type in Doris
 is identical to the type in source table, or it will cause BE crash.
In this case, the `delete` column is with `boolean` type in source table, so the external table in Doris has to be `boolean` too.

@zhangstar333 will find some other way to prevent BE from crash when type is different, maybe in next PR.
So I will merge it now to make regression test happy.

**Pull request merged**
