### PR TITLE
[fix](inverted index) fix multi match result error

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. multi_match result merging logic is incorrect

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
