### PR TITLE
[Fix](nereids) add checkBlockRules() check for create view and alter view

### PR DESCRIPTION
**Pull request by feiniaofeiafei**

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run performance

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Comment by feiniaofeiafei** [comment]
run p0

**Pull request merged**
