### PR TITLE
[regression](catalog)Add test case of paimon complex type

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes

Add Paimon complex nested type regression case.
Related pr:https://github.com/apache/doris/pull/25364

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by DongLiang-0** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Pull request merged**
