### PR TITLE
[Bug](CSVReader) fix null pointer coredump in CSVReader in p2

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

[[Bug](CSVReader) fix null pointer coredump in CSVReader in p2]

pr：#21514

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.6 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17169657110 Bytes

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Review by hubgeter — APPROVED** [review]
LGTM

**Pull request merged**
