### PR TITLE
[fix](auto-partition) Fix auto partition concurrent conflict

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

1. add a timer for tablets channel of incremental open
2. use fe config variable `max_auto_partition_num` to control the max partitions' number of auto-partition table.
3. for multi rpc from BE try to create partition, check not to create repetitive partition.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
