### PR TITLE
[typo](doc)Update stream-load-manual.md

### PR DESCRIPTION
**Pull request by mklzl**
Modify the sequential label

## Proposed changes

Issue Number: close #xxx

Modify the sequential label，Stream load  task has only four steps and should not be labeled 5

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xy720 — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run p0

**Pull request merged**
