### PR TITLE
[typo](docs)modify error josn format in filecache docs.

### PR DESCRIPTION
**Pull request by ixzc**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hf200012** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Pull request closed without merging**
