### PR TITLE
[fix](build index)Fix build index failed on renamed column

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Add `column_unique_ids` in `TOlapTableIndex` thrift struct, to get col_unique_id when building index.

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buiildall

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
