### PR TITLE
[regression-test](memtable)  test memtable flush is high priority for vtable writerV1

### PR DESCRIPTION
**Pull request by Ma1oneZhang**
1. enable debug points
2. get original value of the variable named `enable_memtable_on_sink_node`
3. set the variable to false
4. insert some data to trigger the debug points
5. compare with answer
6. reset the variable

### CODE REVIEW

**Comment by Ma1oneZhang** [comment]
run buildall

**Comment by hello-stephen** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
