### PR TITLE
[fix](func) fix truncate float type result error

### LINKED ISSUE #16467: [Bug] truncate function calculates float type result error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

k9 is a float type
```
mysql> select truncate(k9, 1) from test_query_db.test;
+-------------------+
| truncate(`k9`, 1) |
+-------------------+
|                 6 |
|               789 |
|              3654 |
+-------------------+
```

### What You Expected?

```
mysql> select truncate(k9, 1) from test_query_db.test;
+-------------------+
| truncate(`k9`, 1) |
+-------------------+
|               6.3 |
|             789.2 |
|              3654 |
+-------------------+
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #16467

## Problem summary

When the argument of truncate function is float type, it can match both `truncate(DECIMALV3)` and `truncate(DOUBLE)`, if the match is `truncate(DECIMALV3)`, the precision is lost when converting float to DECIMALV3(38, 0). 

Here I modify it to match `truncate(DOUBLE)` for now, maybe we still need to solve the problem of losing precision when converting float to DECIMALV3.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
Thanks. It's a mistake. I will resolve this losing precision problem later

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by Gabriel39** [comment]
Argument with Float/Double type should use the function with argument `DOUBLE`. This bug is caused by incorrect function register order and the behavior of CAST expression from float/double to DECIMAL is expected.

**Pull request merged**
