### PR TITLE
[bug](array) fix be core in array_with_constant/array_repeat function when the first argument is nullable

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

How to reproduce:

```
select array_with_constant(null, 'abc');
```

Or 

```
select array_with_constant(k1, k2) from table 
```

while k1 is a nullable column in table.

coredump:

```
*** Query id: fe5370a64260419d-804b213ce2811cf4 ***
*** Aborted at 1680708172 (unix time) try "date -d @1680708172" if you are using GNU date ***
*** Current BE git commitID: 7d6c487498 ***
*** SIGABRT unknown detail explain (@0x1fb00001377) received by PID 4983 (TID 5812 OR 0x7fc2a1ec0700) from PID 4983; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/common/signal_handler.h:413
 1# 0x00007FC4116CA7E0 in /lib64/libpthread.so.0
 2# gsignal in /lib64/libc.so.6
 3# __GI_abort in /lib64/libc.so.6
 4# 0x00007FC422E368D9 in /home/disk4/xuyang/work/be/lib/doris_be
 5# 0x00007FC422E2BEED at src/logging.cc:1650
 6# google::LogMessage::SendToLog() at src/logging.cc:1607
 7# google::LogMessage::Flush() at src/logging.cc:1477
 8# google::LogMessageFatal::~LogMessageFatal() at src/logging.cc:2227
 9# doris::vectorized::IColumn::get_int(unsigned long) const at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/columns/column.h:184
10# doris::vectorized::FunctionArrayWithConstant::execute_impl(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/array/function_array_with_constant.cpp:65
11# doris::vectorized::PreparedFunctionImpl::_execute_skipped_constant_deal(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:146
12# doris::vectorized::PreparedFunctionImpl::execute(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:270
13# doris::vectorized::IFunctionBase::execute(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/function.h:158
14# doris::vectorized::VectorizedFnCall::execute(doris::vectorized::VExprContext*, doris::vectorized::Block*, int*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exprs/vectorized_fn_call.cpp:107
15# doris::vectorized::VExprContext::execute(doris::vectorized::Block*, int*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exprs/vexpr_context.cpp:42
16# doris::vectorized::VUnionNode::get_next_const(doris::RuntimeState*, doris::vectorized::Block*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exec/vunion_node.cpp:218
17# doris::vectorized::VUnionNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exec/vunion_node.cpp:285
18# std::_Function_handler<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*), std::_Bind<doris::Status (doris::ExecNode::*(doris::ExecNode*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(doris::RuntimeState*, doris::vectorized::Block*, bool*)> >::_M_invoke(std::_Any_data const&, doris::RuntimeState*&&, doris::vectorized::Block*&&, bool*&&) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:293
19# doris::ExecNode::get_next_after_projects(doris::RuntimeState*, doris::vectorized::Block*, bool*, std::function<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*)> const&, bool) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/exec/exec_node.cpp:586
20# doris::PlanFragmentExecutor::get_vectorized_internal(doris::vectorized::Block*, bool*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:330
21# doris::PlanFragmentExecutor::open_vectorized_internal() at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:293
22# doris::PlanFragmentExecutor::open() at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:243
23# doris::FragmentExecState::execute() at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/fragment_mgr.cpp:231
24# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::RuntimeState*, doris::Status*)> const&) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/fragment_mgr.cpp:495
25# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:291
26# doris::ThreadPool::dispatch_thread() at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/util/threadpool.cpp:537
27# doris::Thread::supervise_thread(void*) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/util/thread.cpp:454
28# start_thread in /lib64/libpthread.so.0
29# __clone in /lib64/libc.so.6
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
