### PR TITLE
[vectorzied](jdbc) refactor jdbc table read array type

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes
jdbc read array type get result from Doris is string, PG is java.sql.array, CK is java.lang.object
it's difficult to maintain and read the code, 
so change all database's array result to string, then add a cast function from string to doris array type

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
> Is there any performance impact?

There should be a slight performance impact for PG array type.
firstly read PG array result object is java.lang.array, eg:[1,2,3]
so could get element use get(i) one by one.
now change the java.lang.array object to string, which have all elements.
then in BE have a cast function from string to array<>.

But this can simplify the code to reduce a lot of judgment.
so might be worth it to refactor

**Comment by zhangstar333** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.54 seconds
 stream load tsv:          445 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230331032843_clickbench_pr_123172.html

**Comment by zhangstar333** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
