### PR TITLE
[feature](function) Add nvl function

### PR DESCRIPTION
**Pull request by sumtumn**
# Proposed changes

Add nvl function support.

## Problem Summary:

Add nvl function support: just make ifnull alias.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hf200012** [comment]
Add the function documentation

**Comment by yiguolei** [comment]
Please add regression test。

**Comment by sumtumn** [comment]
@hf200012  @yiguolei   doc and regression test were added.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
