### PR TITLE
[BugFix](PG catalog) fix that pg catalog can not get all schemas that a pg user can access.

### PR DESCRIPTION
**Pull request by BePPPower**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.
In the past, pg catalog use sql `SELECT schema_name FROM information_schema.schemata where schema_owner='<UserName>';` to select schemas of an user. Howerver, this sql can not find all schemas that a user can access, that because:
1. A user may not be the owner of an schema, but may have read permission on the schema.
2. A user may inherit the permissions of its  user group and thus have read permissions on one schema.

For these reasons, we replace the sql statement with `select nspname from pg_namespace where has_schema_privilege('<UserName>', nspname, 'USAGE');`

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.9 seconds
 stream load tsv:          458 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         39 seconds loaded 2358488459 Bytes, about 57 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230307133145_clickbench_pr_110064.html

**Comment by BePPPower** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
