### PR TITLE
[fix](regression) fix regression test case failure

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by jacktengg** [comment]
run cloud_p1

**Review by yiguolei — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
