### PR TITLE
[test](case) add java-udf function meta test case

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by hello-stephen — DISMISSED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Comment by zhangstar333** [comment]
FE GSON meta not in 2.1.x

**Pull request merged**
