### PR TITLE
[enhancement](regression-test) fix data comparison error

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
