### PR TITLE
[regressiontest](unionall) Regression_test_similar_query_boolean

### LINKED ISSUE #17705: [Bug] Two similar QUERYs return different results
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

I'm trying to add Apache Doris support to SQLancer, this may be a logic bug found by @[SQLancer](https://github.com/sqlancer/sqlancer).

You can reproduce this error from the following steps.

1. `CREATE TABLE t0(c0 BOOLEAN DEFAULT 'false') DISTRIBUTED BY RANDOM PROPERTIES ("replication_num" = "1");`

2. `INSERT INTO t0 (c0) VALUES (DEFAULT), ('false'),('true'),(DEFAULT), ('true'), (DEFAULT),(DEFAULT), ('false');`
The current status of table t0 is as follows
image

3. `SELECT t0.c0 FROM t0;`

**This SQL returns 8 records**, it's correct answer
image

4. When we add the where condition to the SQL in the third step, divide it into three cases according to c0, not c0, c0 is null, and union all the results, we find that **14 records are returned, which is inconsistent with expectations**.

`SELECT t0.c0 FROM t0 WHERE t0.c0 
UNION ALL 
SELECT t0.c0 FROM t0 WHERE (NOT t0.c0) 
UNION ALL 
SELECT t0.c0 FROM t0 WHERE ((t0.c0) IS NULL);
`

image

### What You Expected?

Two similar QUERYs should return the same results

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ZI-MA**
# Proposed changes

Issue Number: close #17705

## Problem summary

Add a regression test about issue#17705

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

This issue existed in version 1.2.2, but it seems to have been resolved in master branch.

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by ZI-MA** [comment]
> so the issue is not a problem for master?

Yes, the results just tested show that there is no problem on the master branch.

**Comment by ZI-MA** [comment]
run buildall

**Comment by ZI-MA** [comment]
run buildall

**Comment by ZI-MA** [comment]
run buildall

**Comment by shuke987** [comment]
Pls rebase and run build all again

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
