### PR TITLE
branch-2.1: [Fix](ORC) Not push down fixed char type in orc reader #45484

### PR DESCRIPTION
**Pull request by suxiaogang223**
cherry-pick #45484

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by suxiaogang223** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run p0

**Comment by yiguolei** [comment]
run buildall

**Pull request merged**
