### PR TITLE
[fix](block-reader) Make rowsets union iterating work

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

issue: #41995

### Fix 5 problems to make union iterating work.

1. Fix the forever true logic when juding rowsets overlapping.

2. Fix collect iterator corruption due to not refreshing ref block resulting in nullptr.

3. Fix exception raised on row id conversion when doing union iterate due to block reader's lazy init policy. Init rowid conversion when really doing  init.

4. Fix rowid_conversion test failed because of constructing a non-empty [0-1] rowset. Just make the overlap judgement compactible with that case because it does no harm (**_PLZ review this conclusion_**).

5. Make rowid conversion test produce correct non-overlap input data and cover union reading code path.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
