### PR TITLE
[Proposal] create table like clause support copy rollup

### PR DESCRIPTION
**Pull request by qzsee**
## Proposed changes

for issue #6474

```sql
create table test.table1 like test.table with rollup r1,r2 -- copy some rollup

create table test.table1 like test.table with rollup all -- copy all rollup

create table test.table1 like test.table  -- only copy base table
```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [x] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (#6474) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by qzsee** [comment]
@morningman Why did CreateTableTest/PlannerTest fail during FE unit testing.

**Comment by morningman** [comment]
Hi @qzsee , thanks for your PR. But please rebase the master to pass the test.
```
git checkout ctl-with-rollup
git pull --rebase upstream-apache master
```

**Comment by qzsee** [comment]
> Hi @qzsee , thanks for your PR. But please rebase the master to pass the test.
> 
> ```
> git checkout ctl-with-rollup
> git pull --rebase upstream-apache master
> ```

ut passed

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
