### PR TITLE
[branch-2.1](fix) fix incorrect result of hash join with const column

### PR DESCRIPTION
**Pull request by DarvenDuan**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

### Problem Summary:
In legacy planner, if Doris executes hash join with a const join column, the rows with the same join key may get different hashes and be send to different hash join node.
#### why:
[`ColumnConst`](https://github.com/apache/doris/blob/branch-2.1/be/src/vec/columns/column_const.h) just updates the hash value of the first row in a block, so the hash value of the first row is different from the other rows even thought they have the same join key.
#### resolve:
skip update hashes of const columns.
 
### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [x] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by yiguolei** [comment]
run buildall

**Review by GoGoWen — APPROVED** [review]
LGTM

**Review by zclllyybb — COMMENTED** [review]
LGTM. please pick to master

**Comment by DarvenDuan** [comment]
> LGTM. please pick to master

master branch just supports nereids planner now, so master may have no need to fix?

**Comment by DarvenDuan** [comment]
> LGTM. please pick to master

nereids planner will not use const column to update hashes in test cases.

**Comment by zclllyybb** [comment]
> > LGTM. please pick to master
> 
> nereids planner will not use const column to update hashes in test cases.

I think it's still needed for insurance purposes. It's also good for code consistency

**Pull request merged**
