### PR TITLE
[improve](move-memtable) include and check offset when append data

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Include and check offset when append data, for data integrity.
Also enhance error checking in `LoadStreamWriter`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
