### PR TITLE
[docs](typo) Correct typos in kyuubi doc

### PR DESCRIPTION
**Pull request by bowenliang123**
# Proposed changes

as the follwup for https://github.com/apache/doris/pull/17481

## Problem summary

- fix typo typos in Kyuubi doc
- fix the wrong error path in examples

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @luzhijing

**Comment by bowenliang123** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by jackwener — APPROVED** [review]

**Comment by zhangguoqiang666** [comment]
run p0

**Pull request merged**
