### PR TITLE
分区为左闭右开区间描述修改

### PR DESCRIPTION
**Pull request by qf8505**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
lgtm

**Comment by morningman** [comment]
hi @qf8505 , please rebase to pass the check

**Comment by jackwener** [comment]
Please `git pull --rebase upstream master` rebase code to pass the CI

**Comment by jackwener** [comment]
Long time no response. 
close it.

**Pull request closed without merging**
