### PR TITLE
[Fix](multi-catalog) Fix hive incorrect result by disable string dict filter if exprs contain null expr.

### LINKED ISSUE #21960: [Bug] Hive catalog query result not right
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0-beta

### What's Wrong?

SQL of Query 1: 
```
select 
  count(*), 
  count(distinct user_no) as "no_reuse_distinct_user_total" 
from 
  (
    SELECT 
      `id` AS `id`, 
      `intf_type` AS `intf_type`, 
      `actual_intf_type` AS `actual_intf_type`, 
       ...
      `user_no` AS `user_no`, 
      `reuse_flag` AS `reuse_flag`, 
        ...
      `partitions` AS `partitions` 
    FROM 
      (
        select 
          `crs_query_cr_query_info_partition`.`id`, 
          `crs_query_cr_query_info_partition`.`actual_intf_type`, 
           ...
          `crs_query_cr_query_info_partition`.`user_no`, 
          `crs_query_cr_query_info_partition`.`reuse_flag`, 
           ...
          `crs_query_cr_query_info_partition`.`partitions` 
        from 
          `ods_safe`.`crs_query_cr_query_info_partition`
      ) `crs_query_cr_query_info_partition`
  ) t 
WHERE 
  t.partitions in (
    DATE_FORMAT(
      DATE_SUB(NOW(), INTERVAL 1 DAY), 
      'yyyy-MM-dd'
    )
  ) 
  and t.actual_intf_type = 'xxx' 
  and (
    t.reuse_flag is null 
    or t.reuse_flag <> 'Y'
  );
```

Query 1 Result: 
```
+----------+------------------------------+
| count(*) | no_reuse_distinct_user_total |
+----------+------------------------------+
|       23 |                           23 |
+----------+------------------------------+
1 row in set (1.89 sec)
```

Explain of Query 1:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                            |
|   OUTPUT EXPRS:                                                                                                                            |
|     count(*)[#32]                                                                                                                          |
|     no_reuse_distinct_user_total[#33]                                                                                                      |
|   PARTITION: UNPARTITIONED                                                                                                                 |
|                                                                                                                                            |
|   VRESULT SINK                                                                                                                             |
|                                                                                                                                            |
|   3:VAGGREGATE (merge finalize)                                                                                                            |
|   |  output: count(partial_count(*)[#30])[#32], multi_distinct_count(DISTINCT partial_multi_distinct_count(DISTINCT user_no)[#31])[#33]    |
|   |  group by:                                                                                                                             |
|   |  cardinality=1                                                                                                                         |
|   |                                                                                                                                        |
|   2:VEXCHANGE                                                                                                                              |
|      offset: 0                                                                                                                             |
|                                                                                                                                            |
| PLAN FRAGMENT 1                                                                                                                            |
|                                                                                                                                            |
|   PARTITION: RANDOM                                                                                                                        |
|                                                                                                                                            |
|   STREAM DATA SINK                                                                                                                         |
|     EXCHANGE ID: 02                                                                                                                        |
|     UNPARTITIONED                                                                                                                          |
|                                                                                                                                            |
|   1:VAGGREGATE (update serialize)                                                                                                          |
|   |  output: partial_count(*)[#30], partial_multi_distinct_count(DISTINCT user_no[#29])[#31]                                               |
|   |  group by:                                                                                                                             |
|   |  cardinality=1                                                                                                                         |
|   |                                                                                                                                        |
|   0:VHIVE_SCAN_NODE                                                                                                                        |
|      table: crs_query_cr_query_info_partition                                                                                              |
|      predicates: reuse_flag[#9] != 'Y' OR reuse_flag[#9] IS NULL, partitions[#28] = '2023-07-20', actual_intf_type[#4] = 'FuZhouPbocScore' |
|      inputSplitNum=16, totalFileSize=4294088271, scanRanges=16                                                                             |
|      partition=1/2515                                                                                                                      |
|      numNodes=22                                                                                                                           |
|      projections: user_no[#8]                                                                                                              |
|      project output tuple id: 1                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------+
```

SQL of Query 2:
```
select 
  count(*), 
  count(distinct user_no) as "no_reuse_distinct_user_total" 
from 
  (
    SELECT 
      `id` AS `id`, 
      `intf_type` AS `intf_type`, 
      `actual_intf_type` AS `actual_intf_type`, 
       ...
      `user_no` AS `user_no`, 
      `reuse_flag` AS `reuse_flag`, 
        ...
      `partitions` AS `partitions` 
    FROM 
      (
        select 
          `crs_query_cr_query_info_partition`.`id`, 
          `crs_query_cr_query_info_partition`.`actual_intf_type`, 
           ...
          `crs_query_cr_query_info_partition`.`user_no`, 
          `crs_query_cr_query_info_partition`.`reuse_flag`, 
           ...
          `crs_query_cr_query_info_partition`.`partitions` 
        from 
          `ods_safe`.`crs_query_cr_query_info_partition`
      ) `crs_query_cr_query_info_partition`
  ) t 
WHERE 
  t.partitions in (
    DATE_FORMAT(
      DATE_SUB(NOW(), INTERVAL 1 DAY), 
      'yyyy-MM-dd'
    )
  ) 
  and t.actual_intf_type = 'xxx' 
  and t.reuse_flag is null;
``` 

Explain of Query 2:
```
+-----------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                         |
|   OUTPUT EXPRS:                                                                                                                         |
|     count(*)[#32]                                                                                                                       |
|     no_reuse_distinct_user_total[#33]                                                                                                   |
|   PARTITION: UNPARTITIONED                                                                                                              |
|                                                                                                                                         |
|   VRESULT SINK                                                                                                                          |
|                                                                                                                                         |
|   3:VAGGREGATE (merge finalize)                                                                                                         |
|   |  output: count(partial_count(*)[#30])[#32], multi_distinct_count(DISTINCT partial_multi_distinct_count(DISTINCT user_no)[#31])[#33] |
|   |  group by:                                                                                                                          |
|   |  cardinality=1                                                                                                                      |
|   |                                                                                                                                     |
|   2:VEXCHANGE                                                                                                                           |
|      offset: 0                                                                                                                          |
|                                                                                                                                         |
| PLAN FRAGMENT 1                                                                                                                         |
|                                                                                                                                         |
|   PARTITION: RANDOM                                                                                                                     |
|                                                                                                                                         |
|   STREAM DATA SINK                                                                                                                      |
|     EXCHANGE ID: 02                                                                                                                     |
|     UNPARTITIONED                                                                                                                       |
|                                                                                                                                         |
|   1:VAGGREGATE (update serialize)                                                                                                       |
|   |  output: partial_count(*)[#30], partial_multi_distinct_count(DISTINCT user_no[#29])[#31]                                            |
|   |  group by:                                                                                                                          |
|   |  cardinality=1                                                                                                                      |
|   |                                                                                                                                     |
|   0:VHIVE_SCAN_NODE                                                                                                                     |
|      table: crs_query_cr_query_info_partition                                                                                           |
|      predicates: partitions[#28] = '2023-07-20', reuse_flag[#9] IS NULL, actual_intf_type[#4] = 'FuZhouPbocScore'                       |
|      inputSplitNum=16, totalFileSize=4294088271, scanRanges=16                                                                          |
|      partition=1/2515                                                                                                                   |
|      numNodes=22                                                                                                                        |
|      projections: user_no[#8]                                                                                                           |
|      project output tuple id: 1                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------+
```

Result of Query 2:
```
+----------+------------------------------+
| count(*) | no_reuse_distinct_user_total |
+----------+------------------------------+
|   123084 |                       119912 |
+----------+------------------------------+
1 row in set (2.03 sec)
```

Table ddl: 
```
CREATE TABLE `crs_query_cr_query_info_partition`(
  `id` bigint COMMENT '物理主键', 
  `actual_intf_type` string COMMENT '', 
  `user_no` string COMMENT '', 
   ...
  `reuse_flag` string COMMENT '', 
   ...
) PARTITIONED BY (`partitions` string) ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.orc.OrcSerde' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat' LOCATION 'hdfs://xxx/ods_safe.db/crs_query_cr_query_info_partition' TBLPROPERTIES (
  'last_modified_time' = '1688024841', 
  'spark.sql.sources.schema.numPartCols' = '1', 
  'spark.sql.sources.schema.part.0' = '...', 
  'spark.sql.sources.schema.partCol.0' = 'partitions', 
  'transient_lastDdlTime' = '1688025415', 
  'bucketing_version' = '2', 'last_modified_by' = 'hive', 
  'spark.sql.sources.schema.numParts' = '1', 
  'spark.sql.create.version' = '2.2 or prior'
);
```

I've use nereids or legacy parser, but the result is the same.

### What You Expected?

The result of query 1 should be equal or greater than query 2.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Issue Number: close #21960

Fix hive incorrect result by disable string dict filter if exprs contain null expr.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.76 seconds
 stream load tsv:          552 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162304530 Bytes

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.5 seconds
 stream load tsv:          542 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161894641 Bytes

**Review by zddr — APPROVED** [review]

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run external

**Pull request merged**
