### PR TITLE
[case][fix](iceberg)move rest cases from p2 to p0 and fix iceberg version issue

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

move cases from p2 to p0

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by kaka11chen — DISMISSED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
