### PR TITLE
[fix](colocate) fix colocate join fail caused by subquery when nereids disabled

### PR DESCRIPTION
**Pull request by hqx871**
## Proposed changes

this [pr](https://github.com/apache/doris/pull/15140/files) fix three tables doing colocate join, but it does not deal with subquery case as follow
```
select a.id,a.name,t1.id,t1.name,cid,cname from test_colo1 a join (select b.id,b.name,c.id as cid,c.name as cname from test_colo2 b left join test_colo3 c on b.id = c.id and b.name = c.name) t1 on a.id=t1.id and a.name= t1.name;

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — COMMENTED** [review]
please add test case.

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
> please add test case.



> please add test case.

Done. And I found if nereids is enabled, colocate work correct.

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
The master is much different from 1.2 which I used. And multi join with subquery work well  after 17035, so just close the pr. The only left problem is the follow join should be bucket join but it choose to colocate join
```
select a.id,a.name,t1.id,t1.name,cid,cname from test_colo1 a join (select b.id,b.name,c.id as cid,c.name as cname from test_colo2 b left join test_colo3 c on b.id = c.id and b.name = c.name) t1 on a.id=t1.id and a.name= t1.name;

```

**Pull request closed without merging**
