### PR TITLE
[fix](regression) fix flaky regression test `delete_mow_partial_update`

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
