### PR TITLE
[fix](nereids) forbid create table with illegal auto partition expr

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before:
```
mysql> create table illegal(
    -> k0 datetime(6) NOT null,
    -> k1 datetime(6) NOT null
    -> )
    -> auto partition by range date_trunc(k0, k1, 'hour')
    -> (
    -> )
    -> DISTRIBUTED BY HASH(`k0`) BUCKETS 2
    -> properties("replication_num" = "1");
Query OK, 0 rows affected (0.15 sec)
```

now:
```
mysql> create table illegal( k0 datetime(6) NOT null, k1 datetime(6) NOT null ) auto partition by range date_trunc(k0, k1, 'hour') ( ) DISTRIBUTED BY HASH(`k0`) BUCKETS 2 properties("replication_num" = "1");
ERROR 1105 (HY000): errCode = 2, detailMessage = errCode = 2, detailMessage = partition expr date_trunc is illegal!
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
