### PR TITLE
[docs] Update documentation configuration parameter `sink.batch.bytes…

### PR DESCRIPTION
**Pull request by bridgeDream**
# Proposed changes

## Problem Summary:

Please refer to: https://github.com/apache/incubator-doris-flink-connector/pull/18

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

**Comment by hf200012** [comment]
fix the code problem

**Review by jackwener — APPROVED** [review]
LGTM.
This PR should merge after another related PR merge

**Comment by hf200012** [comment]
> LGTM.
> This PR should merge after another related PR merge

There is a conflict in the code, and the code conflict needs to be resolved

**Comment by bridgeDream** [comment]
> There is a conflict in the code, and the code conflict needs to be resolved

Hi, I had resolved and submitted the pr again

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
