### PR TITLE
[fix](dpc) Update README.md doris website doc link

### PR DESCRIPTION
**Pull request by hf200012**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by vinlee19 — APPROVED** [review]

**Comment by dataroaring** [comment]
run p1

**Comment by dataroaring** [comment]
run external

**Pull request merged**
