### PR TITLE
[Feat](nereids) add transform rule MergePercentileToArray

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
MergePercentileToArray is to perform a transformation in this case:
select ss_item_sk, percentile(ss_quantity,0.9), percentile(ss_quantity,0.6), percentile(ss_quantity,0.3) from store_sales group by ss_item_sk;
=》
select ss_item_sk, percentile_array(ss_quantity,[0.3,0.6,0.9]) from store_sales group by ss_item_sk;

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by morrySnow** [comment]
wait for percentileArray perf opt

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run xcloud_p1

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run performance

**Review by morrySnow — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
