### PR TITLE
[fix](doc)description of unique

### PR DESCRIPTION
**Pull request by yz-jayhua**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by yz-jayhua** [comment]
run buildall

**Review by yagagagaga — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
