### PR TITLE
[fix](metrics) fix bvar memtable_input_block_allocated_size

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

We should update the bvar before clear `_input_mutable_block`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Pull request merged**
