### PR TITLE
[improvement](insert) refactor group commit insert into

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Refactor group commit insert into to remove some code

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by hust-hhb — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run  buildall

**Comment by mymeiyi** [comment]
run feut

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
