### PR TITLE
[fix](mtmv) fix failed to specify the number of buckets when bucket auto

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

- fix failed to specify the number of buckets when bucket auto
- delete unused SessionVariable
- if mtmv used external table ,check `isMaterializedViewRewriteEnableContainForeignTable`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by seawinde — APPROVED** [review]

**Comment by zddr** [comment]
run feut

**Comment by zddr** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
