### PR TITLE
[fix](compile) fix compile err in meta_tool.cpp

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes

 fix compile err in meta_tool.cpp
image

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.88 seconds
 stream load tsv:          445 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230331044101_clickbench_pr_123196.html

**Comment by ZhangYu0123** [comment]
run build

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run clickbench

**Pull request closed without merging**
