### PR TITLE
[Enhencement](Nereids) add string to length rule

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
## Proposed changes

Rewrite rule to convert EQUAL(string, "") to length(string, 0)
 For example:
 string == ""  ==>  length(string) == 0

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by Gabriel39 — CHANGES_REQUESTED** [review]
This is not always a improvement. As my test shows, only if `length(string)` need to be computed later and we use `length(string) > 0` to replace `string <> ''` will has nenefits.

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
as @Gabriel39 say, this is not always improvement. we reopen it if we need it again.

**Pull request closed without merging**
