### PR TITLE
[Fix](Nereids) change name of plan replayer

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
change plan_replayer to plan replayer and normalize lexer behavior

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Review by englefly — APPROVED** [review]

**Pull request merged**
