### PR TITLE
Add a link to Tablet Meta URL

### PR DESCRIPTION
**Pull request by yangzhg**
Add  a link of meta data  to doris web server's tablet view to access BE's HTTP interface to obtain the corresponding Tablet Meta information
Add  a link of compaction status  to doris web server's  tablet view to access BE's HTTP interface to obtain the corresponding Tablet compaction status
image

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]
+1， LGTM

**Review by morningman — COMMENTED** [review]
Better to update the doc here:
`administrator-guide/operation/tablet-repair-and-balance.md`

**Comment by yangzhg** [comment]
> Better to update the doc here:
> `administrator-guide/operation/tablet-repair-and-balance.md`

done

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
