### PR TITLE
[refactor](schema change) Using tablet schema shared ptr instead of raw ptr

### PR DESCRIPTION
**Pull request by yiguolei**
# Proposed changes

This is part of light weight schema change https://github.com/apache/doris/pull/10136

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangbo** [comment]
Have you done a stress test to see whether this is a performance drop for this pr?

**Comment by yiguolei** [comment]
> Have you done a stress test to see whether this is a performance drop for this pr? Including query and insert.

No, because tablet schema is only used in control path, it is not on data path. And there will be a nightly performance benchmark in selectdb. If we find performance drops we could revert this PR.

**Comment by Lchangliang** [comment]
LGTM

**Comment by yiguolei** [comment]
@wangbo I have done a simple performance test. 
1. set scanner thread to 48.
2. set page cache = true and cache all data into page cache.
3. run 3 concurrenty queries.

compare current branch with a47eff1e4669e877bff6ffb710b93af9492227d6 commit.
both of them the avg latency is 590-595ms.
And the cpu is about 3000%+.
I think the shared ptr does not affect performance.

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
