### PR TITLE
[typo](annotation): fix typo

### PR DESCRIPTION
**Pull request by Toms1999**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by jackwener — APPROVED** [review]
LGTM
By the way, it will be better to set title `[typo](annotation): fix typo`

**Comment by jackwener** [comment]
a part of #9126

**Comment by Toms1999** [comment]
> LGTM 对了，设置标题会更好`[typo](annotation): fix typo`

OK，it's better now

**Comment by Toms1999** [comment]
let me seesee

**Pull request merged**
