### PR TITLE
[feature](javaudf)support no input java udf

### PR DESCRIPTION
**Pull request by lsy3993**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
the feature maybe useless？ why not we directly use const expr “not input”

**Comment by zhangstar333** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
