### PR TITLE
[feature](function) support new function replace_empty

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Add new function `replace_empty()`.
It acts all like `replace()`, instead for the search string(the second param) is empty.

If the search string is empty, it will insert the third string in front of all characters
of the first string, as well as the end of the first string.

eg:

```
mysql> select replace("abc", '', 'xyz');
+---------------------------+
| replace('abc', '', 'xyz') |
+---------------------------+
| abc                       |
+---------------------------+
1 row in set (0.01 sec)

mysql> select replace_empty("abc", '', 'xyz');
+---------------------------------+
| replace_empty('abc', '', 'xyz') |
+---------------------------------+
| xyzaxyzbxyzcxyz                 |
+---------------------------------+
1 row in set (0.00 sec)
```

Doc: https://github.com/apache/doris-website/pull/749

This function is for compatibility of Presto/Trino, it behave exactly same as `replace()` function in Presto/Trino.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
