### PR TITLE
[Improvement](Segment) Use error code when disk exceed capacity limit

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Using error codes can obtain clearer error information.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run p0

**Pull request merged**
