### PR TITLE
Revert "[Feature](merge-on-write)Support ignore mode for merge-on-write unique table (#21773)"

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes
This reverts commit 3ee89aea35726197cb7e94bb4f2c36bc9d50da84.
We think ignore mode may be too complicate to support after discussion, so we disable it currently.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
