### PR TITLE
[feature](insert) Support group commit stream load

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Stream load support group_commit parameter, the related PR is https://github.com/apache/doris/pull/22829

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
We merged this pr and we will reorg group commit sink and group commit mgr after tablet sink reorg.

**Comment by DarvenDuan** [comment]
Is there a plan to support group commit for stream load 2PC?

**Pull request merged**
