### PR TITLE
[fix](multicatalog) support read from hive table with HIVE_UNION_SUBDIR in path location

### PR DESCRIPTION
**Pull request by Yulei-Yang**
If a hive table is generated by tez engine by a union all stmt, doris cannot read data from it. coz its result file are located in subdirectory, while when get splits, doris does not scan subdirectory now.
image

Now fix it.

## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Pull request merged**
