### PR TITLE
[Docs](community) Join the Community documentation

### PR DESCRIPTION
**Pull request by Cassiexiier**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Cassiexiier** [comment]
run buildall

**Review by luzhijing — DISMISSED** [review]
LGTM

**Review by luzhijing — DISMISSED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Pull request closed without merging**
