### PR TITLE
[fix](path gc) fix data dir path gc

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Data dir path gc include gc by tablet and gc by rowset,  both use the same one thread.  If notify to gc by rowset, but the gc thread is just waiting for gc by tablet, then this thread will not try to perform gc by rowset,  it's just always waiting for gc by tablet.  Vice versa.  Fix this.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
