### PR TITLE
[Fix](inverted index) fix inappropriate use of macro in inverted inde…

### PR DESCRIPTION
**Pull request by airborne12**
…x fs directory error process

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]

**Review by yiguolei — DISMISSED** [review]

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — APPROVED** [review]

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
