### PR TITLE
[Fix](parquet-reader) Fix reading fixed length byte array decimal in parquet reader introduced by #29825.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Fix] (parquet-reader) Fix reading fixed length byte array decimal in parquet reader introduced by #29825.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run external

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
