### PR TITLE
[fix](broker-load) make sequence column name case insensitive

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by wm1581066** [comment]
@morningman @dataroaring please review this pr

**Comment by dataroaring** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run clickbench

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
