### PR TITLE
[chore](unused) Remove unused const variables NUMBER, ZERO in vnumbers_tvf.cpp

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Remove unused const variables NUMBER, ZERO in vnumbers_tvf.cpp

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by JackDrogon** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
