### PR TITLE
[fix](partial update) mishandling of exceptions in the publish phase may result in data loss

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

We found in our stress test environment that when performing concurrent partial column updates, data was lost or inconsistent due to not to handle write exceptions of the newly generated segment well in publish phase:

1. when two concurrent partial column update job try to update an identical key at the same time, additional conflict handling needs to be done in the publish phase
2. and the load task with a higher version needs to generate the new rows and write them to the newly generated segmnet, while marking the corresponding key in the original segment for deletion
3. this deletion marker is updated in txn_info->delete_bitmap in real time, when writing the new segment failed, these deletion markers for the original segment are not rolled back
4. and the next time the publish task retries, it will not process these keys because they have already been marked for deletion.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
