### PR TITLE
[bug](random distribution) fix data loss and incorrect in random distribution table

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

This is a master fix for a issue found in branch-2.0: #33920

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
