### PR TITLE
[enhance][external]enhance and fix external cases 0807

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

1. Replace 127.0.0.1 with  externalEnvIp param
2.Replace the fixed object storage address with a specified function
3.Add group tags external_docker和external_remote
4.Fixed issue with test_doris_jdbc
5.Adjust test_hive_schema_evolution from P2 to P0

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run compile

**Comment by zhangguoqiang666** [comment]
run p0

**Comment by zhangguoqiang666** [comment]
run external

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
