### PR TITLE
[cherry-pick](branch-3.0) Pick "[fix](rowset meta) Fix rowset meta size relation (#41022)"

### PR DESCRIPTION
**Pull request by Yukang-Lian**
Pick #41022

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run cloud_p0

**Pull request merged**
