### PR TITLE
[enhancement](testutil)Add unit testing functionality

### PR DESCRIPTION
**Pull request by M1saka2003**
## Proposed changes

Enhance error reporting by overriding gtest virtual functions to provide more detailed information

here's an example:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from function_string_test
[ RUN      ] function_string_test.function_string_substr_test
/mnt/disk2/heshicheng/doris/be/test/vec/function/function_test_util.h:346: Failure
Expected equality of these values:
  expect_data
    Which is: "F"
  column_data
    Which is: "E"
 at row 5
arg1 arg2 arg3 
Error occurred in case5
/mnt/disk2/heshicheng/doris/be/test/vec/function/function_test_util.h:346: Failure
Expected equality of these values:
  expect_data
    Which is: "F"
  column_data
    Which is: "E"
 at row 0
const arg1 arg2 arg3 
Error occurred in case5

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by M1saka2003** [comment]
run buildall

**Comment by M1saka2003** [comment]
run buildall

**Comment by M1saka2003** [comment]
run buildall

**Comment by M1saka2003** [comment]
run buildall

**Comment by M1saka2003** [comment]
run buildall

**Comment by M1saka2003** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]

**Pull request merged**
