### PR TITLE
[chore] Rename Doris binary output format

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

As we discuss in thread: https://lists.apache.org/thread/b1cm011rqdqhbrn4h1qjlh1b3j2tqhjk
This CL mainly changes:
1. Change the BE binary file from `palo_be` to `doris_be`
    For compatibility, there will be a soft link `palo_be` link to `doris_be`, so that some supervisor program can still work with `palo_be` name.
2. Change the FE binary file from `palo-fe.jar` to `doris-fe.jar`
3. Change some names in document.
4. Not build meta_tools by default, to save some compile time.

## Checklist(Required)

1. Does it affect the original behavior: (Yes, somehow)
5. Has unit tests been added: (No Need)
6. Has document been added or modified: (Yes)
7. Does it need to update dependencies: (No)
8. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Shall we modify the file `fe/fe-core/src/main/java/org/apache/doris/PaloFe.java`?

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
> 

Maybe could not, because start_fe.sh depend on PaloFe...

**Comment by morningman** [comment]
> Shall we modify the file `fe/fe-core/src/main/java/org/apache/doris/PaloFe.java`?

This change is try to minimize the impact of the origin behavior.
So you can see I add a soft link for BE binary for compatibility.
But is not easy to do that for FE, because we can not add soft link for a jar file or class name.

Maybe we could change PaloFe's later, but not this time.

**Pull request merged**
