### PR TITLE
[fix](broker-read) refactor broker reading process to avoid null broker connection

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

issue: #26052
introduced: #16021

Move the broker related  RPC into `BrokerFileSystem` to make the client under protection, and should not expose the connection to the reader.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by platoneko — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
