### PR TITLE
[Test](cache)Add remote cache ut

### PR DESCRIPTION
**Pull request by zxealous**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by pengxiangyu — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221015010249_clickbench_pr_29479.html

**Comment by zxealous** [comment]
> https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221015010249_clickbench_pr_29479.html

@hello-stephen  What's the meaning of this?

**Comment by morningman** [comment]
> > https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221015010249_clickbench_pr_29479.html
> 
> @hello-stephen What's the meaning of this?

This is a auto-reply message of the result of `clickbench` checks, just for show the result.

**Pull request merged**
