### PR TITLE
[vectorized](bug) fix window function can't handle first row of beyond

### LINKED ISSUE #16845: [Bug] 窗口函数last_value窗口不生效
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.2

### What's Wrong?

表数据如下
image

------------------------------------------------------------------
执行sql为
select 
    u_id,
    u_city,
    u_salary,
    last_value(u_salary) over (partition by u_city order by u_id rows between unbounded preceding and 1 preceding) last_value_test
from example_window_tb;

------------------------------------------------------------------
此SQL使用SPARK的返回结果为
image
以上是我期望的结果，根据u_city 分区，在两个分区内分别计算last_value。

------------------------------------------------------------------
而在Doris中的返回结果为：
image
partition by u_city 没有生效，sz分区的第一行不是null，而是gz分区的最后一行。

### What You Expected?

image

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes

Issue Number: close #16845

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p0

**Comment by jacktengg** [comment]
LGTM

**Comment by jacktengg** [comment]
Please also add test case for first_value

**Comment by jacktengg** [comment]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
