### PR TITLE
[fix](merge-on-write) handle create rowset error to avoid null pointer exception

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

When I use merge on write table and load it, coredump happened when create rowset error in `_generate_delete_bitmap`
The purpose of this pr is to fix coredump when meet the error.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
