### PR TITLE
[enhancement][fix] update storage vault case for upgrade test

### PR DESCRIPTION
**Pull request by MoanasDaddyXu**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
To adapt for the upgrade test, split this test case into two

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [x] Confirm test cases
- [ ] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by MoanasDaddyXu** [comment]
run buildall

**Comment by MoanasDaddyXu** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by shuke987 — APPROVED** [review]
LGTM

**Pull request merged**
