### PR TITLE
[fix](memory) Remove ChunkAllocator & fix Allocator no use mmap

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Issue Number: close #xxx

1. Remove ChunkAllocator
2. When Allocator does not use mmap, its behavior is consistent with system alloc/free/realloc

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
