### PR TITLE
[chore](gutil) remove some gutil macros and solve some macro conflict with brpc

### PR DESCRIPTION
**Pull request by yiguolei**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. remove and refactor some gutil/macros since they are conflict with butil/macros.h

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
Any differences between those two?

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.55 seconds
 load time: 606 seconds
 storage size: 17180211444 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221103164951_clickbench_pr_39451.html

**Comment by yiguolei** [comment]
> Any differences between those two?

If use  std::mutex in a bthread context, then the bthread will hang up and the bthread's underlying pthread will also hang up. But there are a limit number of pthread  workers for bthread (the default cpu core num). If all pthreads are hang up then brpc could not work correctly. Sometime we will get failed to connect error or rpc timeout error.

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by yangzhg** [comment]
Pushing brpc to fix this bug or we help brpc fix this bug is a better solution

**Comment by yiguolei** [comment]
> Pushing brpc to fix this bug or we help brpc fix this bug is a better solution， I think we need more discussion, if it is determined that there is a problem with brpc, we should contact brpc to fix the problem

As we talked offline, we  need contact brpc to find if there are any other solutions.

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
