### PR TITLE
[improve](cloud) set default vaule for file_path

### PR DESCRIPTION
**Pull request by dataroaring**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — CHANGES_REQUESTED** [review]
test

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
