### PR TITLE
[typo](docs)Correct the odbc markdown comments

### PR DESCRIPTION
**Pull request by byte4tide**
## Proposed changes

fix odbc description in resource markdown

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Pull request merged**
