### PR TITLE
[refactor][be] Optimize headers

### LINKED ISSUE #9707: [refactor][be] Optimize headers
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

This issue aims to optimize headers:
1. Delete useless includes.
2. Simplify dependencies between headers.

### Solution

Using `clangd` to analyze includes.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #9707

## Problem Summary:

Please refer to #9707 

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
```cpp
[18:27:13]
[Step 1/1] FAILED: test/CMakeFiles/doris_be_test.dir/runtime/collection_value_test.cpp.o 
[18:27:13]
[Step 1/1] ccache /var/local/ldb-toolchain/bin/g++ -DBE_TEST -DBOOST_ALL_NO_LIB -DBOOST_STACKTRACE_USE_BACKTRACE -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Ddoris_be_test_EXPORTS -I/root/doris/be/src -I/root/doris/be/test -isystem /root/doris/be/../gensrc/build -isystem /var/local/thirdparty/installed/include -isystem /var/local/thirdparty/installed/gperftools/include -isystem /var/local/thirdparty/installed/include/breakpad -Wall -Wno-sign-compare -pthread -Werror -fstrict-aliasing -fno-omit-frame-pointer -std=gnu++17 -D__STDC_FORMAT_MACROS -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_SYSTEM_NO_DEPRECATED -DBRPC_ENABLE_CPU_PROFILER -Wno-array-bounds -Wno-stringop-overread -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX=1 -msse4.2  -Wno-attributes -DS2_USE_GFLAGS -DS2_USE_GLOG -faligned-new  -g -Wno-unused-local-typedefs -O0 -fsanitize=address -DADDRESS_SANITIZER -fprofile-arcs -ftest-coverage -DGTEST_USE_OWN_TR1_TUPLE=0   -D OS_LINUX -fno-access-control -Wno-stringop-overflow -fdiagnostics-color=always -MD -MT test/CMakeFiles/doris_be_test.dir/runtime/collection_value_test.cpp.o -MF test/CMakeFiles/doris_be_test.dir/runtime/collection_value_test.cpp.o.d -o test/CMakeFiles/doris_be_test.dir/runtime/collection_value_test.cpp.o -c /root/doris/be/test/runtime/collection_value_test.cpp
[18:27:13]
[Step 1/1] /root/doris/be/test/runtime/collection_value_test.cpp: In member function 'virtual void doris::CollectionValueTest_init_Test::TestBody()':
[18:27:13]
[Step 1/1] /root/doris/be/test/runtime/collection_value_test.cpp:33:20: error: aggregate 'doris::ObjectPool pool' has incomplete type and cannot be defined
[18:27:13]
[Step 1/1]    33 |         ObjectPool pool;
[18:27:13]
[Step 1/1]       |                    ^~~~
[18:27:13]
[Step 1/1] /root/doris/be/test/runtime/collection_value_test.cpp:52:20: error: aggregate 'doris::ObjectPool pool' has incomplete type and cannot be defined
[18:27:13]
[Step 1/1]    52 |         ObjectPool pool;
[18:27:13]
[Step 1/1]       |                    ^~~~
[18:27:13]
[Step 1/1] /root/doris/be/test/runtime/collection_value_test.cpp: In member function 'virtual void doris::CollectionValueTest_set_Test::TestBody()':
[18:27:13]
[Step 1/1] /root/doris/be/test/runtime/collection_value_test.cpp:59:16: error: aggregate 'doris::ObjectPool pool' has incomplete type and cannot be defined
[18:27:13]
[Step 1/1]    59 |     ObjectPool pool;
```

Hi, you should check ut build

**Comment by adonis0147** [comment]
Hi @BiteTheDDDDt , thank you for reminding me and I fixed the build.

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Hi @adonis0147 please rebase to solve the conflict

**Comment by adonis0147** [comment]
Hi @morningman , I have resolved all conflicts. PTAL

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
