### PR TITLE
[fix](nereids)lag and lead function's nullability is wrong

### PR DESCRIPTION
**Pull request by starocean999**
### What problem does this PR solve?
lag and lead function's nullability should depends on either first or third( if it has) param's nullability. 

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by starocean999** [comment]
run cloud_p0

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
