### PR TITLE
[opt](recycler) Improve robustness and observability 

### PR DESCRIPTION
**Pull request by gavinchou**
### What problem does this PR solve?

1. Fix delete non-existed object, the original impl. does not handle correctly 
2. Add recycle lag indicators: bvars for index, partition, rowset and txn
    1. `recycle_index_earlest_ts_${instance_id}` dropped table/mv 
    2. `recycle_partition_earlest_ts_${instance_id}` dropped partitions
    3. `recycle_rowset_earlest_ts_${instance_id}` compacted rowset
    4. `recycle_tmp_rowset_earlest_ts_${instance_id}` aborted transactions  tmp data
    5. `recycle_expired_txn_label_earlest_ts_${instance_id}`  expired labels and transactions
4. Add retry for scan_and_recycle() to prevent KV error like "Request future version"
6. Fix recycle delete instance may leak object data: we have to delete data first before delete KV
7. Improve code readability: remove duplicated code and add more comments

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by qidaye** [comment]
run p1

**Review by Yukang-Lian — APPROVED** [review]

**Comment by hello-stephen** [comment]
run cloud_p1

**Comment by hello-stephen** [comment]
run p1

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
