### PR TITLE
[feature](doris compose) start node wait for ready service

### PR DESCRIPTION
**Pull request by yujun777**
when SuiteCluster call  start/restart frontends and backends, it will wait nodes ready for service.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
