### PR TITLE
[Bug](function) remove datev2 signature of hour_ceil/hour_floor

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

remove datev2 signature of hour_ceil/hour_floor

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by jackwener** [comment]
Maybe need notice: old optimizer `ScalarBuiltins.java` contains the removed type SIGNATURES.

**Comment by jackwener** [comment]
#16174 is same with this PR

**Comment by BiteTheDDDDt** [comment]
> 

In this case we have wrong signature(the implementation of hour_ceil/hour_floor in `be` is inconsistent with the signature), so I remove it.

**Comment by jackwener** [comment]
> Maybe need notice: old optimizer `ScalarBuiltins.java` contains the removed type SIGNATURES.

signature in it also need to be removed

**Comment by BiteTheDDDDt** [comment]
> > Maybe need notice: old optimizer `ScalarBuiltins.java` contains the removed type SIGNATURES.
> 
> signature in it also need to be removed

When we modify py signature file, we should build fe with `--clean` to update ScalarBuiltins.java

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.3 seconds
 load time: 491 seconds
 storage size: 17122820269 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230129030256_clickbench_pr_85909.html

**Pull request merged**
