### PR TITLE
Fix](schema change) fix metadata inconsistency bug caused by enable light schema change (#28255)

### PR DESCRIPTION
**Pull request by luwei16**
branch-2.0 #28255

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
