### PR TITLE
[Config](thrift) set default timeout for thrift rpc in FE

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

otherwise if something's wrong with the other end or thrift itself, FE will hang.

docs pr: https://github.com/apache/doris-website/pull/528

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run compile

**Comment by zclllyybb** [comment]
run compile

**Comment by w41ter** [comment]
run p0

**Comment by w41ter** [comment]
run compile

**Pull request closed without merging**
