### PR TITLE
[feature](nereids) runtime filter prune when column stats are not available

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
prune rf when column stats are not available
print rf in "explain shape plan", both join side and apply side
add regression case to check plan shape/rf/rf prune for tpch_sf1000 (stats are not available)

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
