### PR TITLE
[test](mv) Fix regression test out text is wrong

### PR DESCRIPTION
**Pull request by seawinde**
### What problem does this PR solve?

When shrinking the test data set, the corresponding out file data was not refreshed. As a result, the data in the out file was refreshed again.

There are some tests that hit both materialized views as expected, modifying such corresponding cases.

Issue Number: close #xxx

Related PR: 
#40860
#41644

Problem Summary:

### Check List (For Committer)

- Test 

    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by zfr9527 — APPROVED** [review]
LGTM

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
