### PR TITLE
[fix](profile) Change the check of whether the username is admin and root to check whether the user specifically corresponds to admin permissions

### PR DESCRIPTION
**Pull request by xyfsjq**
## Proposed changes

Change the check of whether the username is admin and root to check whether the user specifically corresponds to admin permissions

### CODE REVIEW

**Review by zddr — APPROVED** [review]

**Review by morningman — COMMENTED** [review]
Need to add regression test

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by xyfsjq** [comment]
run feut

**Comment by xyfsjq** [comment]
run buildall

**Comment by xyfsjq** [comment]
run p0

**Review by zddr — APPROVED** [review]

**Pull request merged**
