### PR TITLE
[fix](delete_predicate) fix wrong data after upgrade from v2.0 version

### PR DESCRIPTION
**Pull request by cambyzju**
issue: https://github.com/apache/doris/issues/40390

related pr: https://github.com/apache/doris/pull/22442

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by hello-stephen** [comment]
hello, big bro,
could you help to add a compatibility case, please refer to https://github.com/apache/doris/blob/master/regression-test/README.md#compatibility-case

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
