### PR TITLE
[feat](fe) Add a counter metric for recording large editlog write

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by gavinchou** [comment]
pls describe what the metrics is like, list an example here.

**Review by w41ter — APPROVED** [review]

**Pull request merged**
