### PR TITLE
[Feature](hash-table) unify initialization of HashTableVariants and support set for distinct agg

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1. use init_hash_method to initialize agg/partition_sort/join/set's HashTableVariants
2. support set for distinct agg
3. support single column context of decimal256

```sql
select count(*) from (select CounterID,UserID from hits group by CounterID,UserID)t;
```
```
before:
                      58.8g   4.3g
                        DISTINCT_STREAMING_AGGREGATION_OPERATOR  (id=1  ,  nereids_id=244):(ExecTime:  3sec472ms)
                              -  BlocksProduced:  5.118K  (5118)
                              -  BuildTime:  3sec441ms
                              -  CloseTime:  1.514us
                              -  ExecTime:  3sec472ms
                              -  HashTableComputeTime:  3sec290ms
                              -  HashTableEmplaceTime:  2sec866ms
                              -  HashTableInputCount:  99.997497M  (99997497)
                              -  HashTableSize:  20.796015M  (20796015)
                              -  InitTime:  5.501us
                              -  InsertKeysToColumnTime:  142.189ms
                              -  MemoryUsage:  0.00  
                              -  MemoryUsagePeak:  0.00  
                              -  OpenTime:  7.35us
                              -  ProjectionTime:  14.908ms
                              -  RowsProduced:  20.796015M  (20796015)


after:
                      42.7g   4.1g 
                        DISTINCT_STREAMING_AGGREGATION_OPERATOR  (id=1  ,  nereids_id=244):(ExecTime:  3sec24ms)
                              -  BlocksProduced:  5.118K  (5118)
                              -  BuildTime:  2sec994ms
                              -  CloseTime:  1.333us
                              -  ExecTime:  3sec24ms
                              -  HashTableComputeTime:  2sec850ms
                              -  HashTableEmplaceTime:  2sec470ms
                              -  HashTableInputCount:  99.997497M  (99997497)
                              -  HashTableSize:  20.796015M  (20796015)
                              -  InitTime:  4.993us
                              -  InsertKeysToColumnTime:  134.734ms
                              -  MemoryUsage:  0.00  
                              -  MemoryUsagePeak:  0.00  
                              -  OpenTime:  9.822us
                              -  ProjectionTime:  14.389ms
                              -  RowsProduced:  20.796015M  (20796015)
```

```

select count() from (select murmur_hash3_32(number) from numbers("number" = "100000000") union select murmur_hash3_32(number) from numbers("number" = "100000000"))t;

peakMemoryBytes=6948914752  Time(ms)=3812
peakMemoryBytes=4035731208  Time(ms)=3128
```

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
