### PR TITLE
[fix](export) fix that export table retry with same label should succeed when first export job failed

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Review by GoGoWen — DISMISSED** [review]
LGTM

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Review by GoGoWen — APPROVED** [review]
LGTM

**Review by weizuo93 — APPROVED** [review]

**Pull request merged**
