### PR TITLE
[fix](meta) FE should delete a colocate table's replica when it is redundant

### PR DESCRIPTION
**Pull request by liutang123**
# Proposed changes

Issue Number: close #xxx

## Problem summary
If a colocate table's tablet is heathy. When a BE report a extra reaplica to FE, FE will not delete it.
But it should be deleted, otherwise it will report again and again but no one will handle it.

## Checklist(Required)

* [x] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.98 seconds
 stream load tsv:          472 seconds loaded 74807831229 Bytes, about 151 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230322025824_clickbench_pr_118339.html

**Comment by liutang123** [comment]
run p1

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by caiconghui** [comment]
colocate table will delete Replica in meta when do balance when it is redundant which means it doesn't matter when add it here.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
