### PR TITLE
[enhancement](merge-on-write) format logs about MoW and add more stats for publish

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Pull request merged**
