### PR TITLE
[feature](compaction) support vertical_compaction & ordered_data_compaction

### PR DESCRIPTION
**Pull request by yixiutt**
1. support vertical compaction, memory usage is 1/10 of horizontal compaction in ckbench.

2.ordered compaction, save min max key for segment in rowset meta, link file in compaction if rowsets are none overlapping.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.23 seconds
 load time: 423 seconds
 storage size: 17153754575 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221123122911_clickbench_pr_51592.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
Passes P2, so we can merge it quickly.

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by zhangm365** [comment]
Hello, is the param `enable_vertical_compaction`  default setting to true?

**Pull request merged**
