### PR TITLE
[enhance](regresstion case)add external group mark 0727

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

add group mark for external case, these tags will be used for pipeline testing

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run builldall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by pingchunzhang** [comment]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
