### PR TITLE
[Chore](Materialized-View) add some mv regression test case

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

1. add some mv regression test case
2. rename materialized_view_p0 to mv_p0 (avoid create database failed because long db name)

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run p1

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run clickbench

**Comment by BiteTheDDDDt** [comment]
run feut

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run clickbench

**Comment by BiteTheDDDDt** [comment]
run arm

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run arm

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
