### PR TITLE
[fix](stream_load)fix bug that csv_reader parse line in order to get column

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

fix bug that csv_reader parse line in order to get column.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Please add some regression test

**Comment by wolfboys** [comment]
This PR is very important for migrating data to Doris. Thank you for your contribution!

**Comment by hubgeter** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.76 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162260944 Bytes

**Comment by hubgeter** [comment]
run p0

**Comment by hubgeter** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.44 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          98.9 seconds inserted 10000000 Rows, about 101K ops/s
 storage size: 17162094261 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]
LGTM

**Pull request merged**
