### PR TITLE
[Enhancement] (branch-2.0) when partition column is datetime, date can work in create table command

### PR DESCRIPTION
**Pull request by xiedeyantu**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiaokang** [comment]
@xiedeyantu FE UT failed

**Comment by xiedeyantu** [comment]
> @xiedeyantu FE UT failed

I will fix it later.

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
@xiaokang review please

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
