### PR TITLE
[enhancement](exchange) not use thread pool to handle exchange block

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

1. avoid close error and the query will be canceld
2. avoid too much competition in queue offer.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
