### PR TITLE
[Docs] (maint-monitor) when config automatic-service-start, we need config JAVA_HOME in the fe.conf and be.conf firstly

### PR DESCRIPTION
**Pull request by lss1231**
## Proposed changes

Issue Number: close #xxx

## Further comments

when config automatic-service-start, we need config JAVA_HOME in the fe.conf and be.conf firstly, this is necessary, but the official document file "automatic-service-start.md" has not show the users this, so i create this PR.

### CODE REVIEW

**Comment by i78086** [comment]
run buildall

**Review by liujiwen-up — APPROVED** [review]

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
