### PR TITLE
[Improve](explode) improve explode func with array nested complex type

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
make explode with array nested complex type

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run beut

**Comment by amorynan** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Comment by amorynan** [comment]
run feut

**Pull request merged**
