### PR TITLE
[feat](Nereids): Refactor `Eliminate_Group_By_Key` by functional dependencies

### PR DESCRIPTION
**Pull request by keanji-x**
## Proposed changes

This pull request introduces an optimization for SQL query execution by eliminating unnecessary GROUP BY keys based on functional dependencies. This optimization targets scenarios where certain keys in the GROUP BY clause are functionally dependent on others, allowing for a more efficient grouping operation.

We employ a Breadth-First Search (BFS) algorithm to analyze the functional dependencies (treated as edges) between various keys (treated as nodes). This approach helps in identifying and subsequently eliminating redundant keys from the GROUP BY clause.

For example, given a GROUP BY clause like GROUP BY a, b where a -> b (i.e., a functionally determines b), it is redundant to group by both a and b. Instead, we can simplify this to GROUP BY b alone, thereby reducing the complexity of the query.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
add description please

**Review by jackwener — APPROVED** [review]

**Pull request merged**
