### PR TITLE
[enhancement](routineload) add debug conf and set broker.name.ttl = 0

### PR DESCRIPTION
**Pull request by dataroaring**
## Proposed changes

Add debug conf to analyze problem. 

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.57 seconds
 stream load tsv:          542 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162272048 Bytes

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
