### PR TITLE
[improve](postgresql catalog) support postgresql bytea type to doris  string

### PR DESCRIPTION
**Pull request by zy-kkk**
# Proposed changes

Issue Number: close #xxx

## Problem summary

in postgressql , we select bytea type ,show like
image
so ,I support it in doris
img_v2_3d4a6d82-5242-43c2-b958-d528449d2eag

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.79 seconds
 stream load tsv:          435 seconds loaded 74807831229 Bytes, about 164 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230413050618_clickbench_pr_128376.html

**Comment by zy-kkk** [comment]
run buildall

**Comment by morningman** [comment]
please add test case

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
> please add test case

done

**Review by BePPPower — COMMENTED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run arm p0 clickbench

**Comment by zy-kkk** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
