### PR TITLE
[Enhancement](routine-load) Support routine load task succeed with empty data consumed

### LINKED ISSUE #8255: [Enhancement]  Support routine load task succeed with empty data consumed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

routine load task would be marked as canceled, which would cause user confused. 
but now Doris should process this well for that Doris can commit empty data transaction after PR #7240.

### Solution

Support routine load task succeed with empty data consumed

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #8255 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jackwener — APPROVED** [review]
LGTM

**Review by weizuo93 — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
Does this affect the overall behavior of the job? Because I understand that "cancel" is only internal logic and does not affect the continuation of the routine load job?

**Comment by caiconghui** [comment]
> Does this affect the overall behavior of the job? Because I understand that "cancel" is only internal logic and does not affect the continuation of the routine load job?

we should uniform the logic for data loading, since that now we support empty data commit, so there would be always 100% succeed routine load task which indicate routine load job is stable and the cluster is normal

**Pull request merged**
