### PR TITLE
[opt](nereids)using mv's derived stats

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
for a given mv, we have 2 stats. one is generated by stats analyzer, which is accurate, another is derived stats, which is derived when optimizer runs the mv query.
If a query tree contains a mv, we will use the mv's derived stats to derive stats for the whole tree.

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run performance

**Comment by morrySnow** [comment]
add description

**Comment by englefly** [comment]
run p0

**Pull request merged**
