### PR TITLE
[bugfix](column_reader) index_page should not be pre-decoded

### PR DESCRIPTION
**Pull request by yixiutt**
# Proposed changes

pick #16605 

## Problem summary

cherry-pick #16605

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Comment by morningman** [comment]
Hi @yixiutt , better to use origin commit msg of the cherry-picked PR. So that we can easily know what it is from title.
And use `#16605` to link the origin PR.

**Comment by ZhangGuoqiang666** [comment]
build all

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
