### PR TITLE
[improve](nestedtype) support schema change for nested type

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run feut

**Review by BiteTheDDDDt — DISMISSED** [review]

**Review by eldenmoon — DISMISSED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run feut

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run feut

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run cloud_p1

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by xiaokang — COMMENTED** [review]
LGTM

**Pull request merged**
