### PR TITLE
[Chore](build) enchancement for backend build time usage

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

1. add time usage display on build
图片

2. remove some unused datetime function registe.
3. split max_by/min_by instantiation.
```shell
before:
[878/880] Building CXX object src/vec/CMakeFiles/Vec.dir/aggregate_functions/aggregate_function_min_max_by.cpp.o
TimeUsage: real=948.01s, user=938.11s, sys=9.81s
after:
[11/14] Building CXX object src/vec/CMakeFiles/Vec.dir/aggregate_functions/aggregate_function_max_by.cpp.o
TimeUsage: real=237.43s, user=234.74s, sys=2.65s
[12/14] Building CXX object src/vec/CMakeFiles/Vec.dir/aggregate_functions/aggregate_function_min_by.cpp.o
TimeUsage: real=245.10s, user=242.51s, sys=2.58s
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
