### PR TITLE
[test](docker-compose) change db2's image url and disable it temporarily

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Db2 Community Edition has moved from DockerHub to IBM Container Registry

Disable DB2 by default, and reopen it once ready

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by BePPPower** [comment]
run buildall

**Review by BePPPower — APPROVED** [review]
LGTM

**Pull request merged**
