### PR TITLE
Fix invalid to_bitmap input lead to BE core

### PR DESCRIPTION
**Pull request by kangkaisen**
For https://github.com/apache/incubator-doris/issues/2699 and https://github.com/apache/incubator-doris/issues/2678 and https://github.com/apache/incubator-doris/issues/2499

When there is a error for one row by insert into, we should ignore it, not fill in default value.

### CODE REVIEW

**Review by imay — DISMISSED** [review]
LGTM

**Review by imay — APPROVED** [review]
LGTM

**Comment by jmk1011** [comment]
select hex(to_bitmap(1));
ERROR 1064 (HY000): No matching function with signature: hex(bitmap).

after this pr，select hex will return wrong. Can't bitmap type use hex function?

**Comment by kangkaisen** [comment]
> select hex(to_bitmap(1));
> ERROR 1064 (HY000): No matching function with signature: hex(bitmap).
> 
> after this pr，select hex will return wrong. Can't bitmap type use hex function?

What's the meaning of  `hex(bitmap)`?

I think bitmap type needn't support hex function.

**Comment by jmk1011** [comment]
with commit https://github.com/apache/incubator-doris/commit/3022955f32c9764fd2634d57faa14664212d1831，select hex(to_bitmap(1)) is supported.

Now I have a problem. After inserting 222 different data, the calculated of bitmap_union_count result is 221. So I want to take a look at the results of hex(bitmap_hash(data)), and see if there are any duplicates of bitmap_hash(data)

**Comment by jmk1011** [comment]
Moreover, hex(HLL_HASH(1)) function is supported, I think hex(bitmap_hash(1)) should also support

**Comment by kangkaisen** [comment]
> Moreover, hex(HLL_HASH(1)) function is supported, I think hex(bitmap_hash(1)) should also support

Which isn't a reasonable logic.

hex(bitmap_function) could run before is because the bitmap_function return type is Varchar, After https://github.com/apache/incubator-doris/pull/2690, I change the bitmap_function return type to bitmap.

Currently,  the bitmap_function return type is bitmap is reasonable, and bitmap type don't support hex function I think is also reasonable.

If you to take a look at the results of bitmap_hash(data), you could use `bitmap_union(bitmap_hash(data))`.

**Comment by jmk1011** [comment]
image
It does n’t make sense to show results like this

**Comment by jmk1011** [comment]
> Now I have a problem. After inserting 222 different data, the calculated of bitmap_union_count result is 221.

In this case, how should I locate what went wrong?

**Comment by imay** [comment]
Hi @jmk1011 

1. bitmap's struct is an internal format, which is not useful to end user. Even if we support hex(), the result is meaningless. Because the format will be changed in next version.
2. For this case, we should support another function, which can convert a bitmap to a string who contains all intergers in the bitmap.

**Pull request merged**
