### PR TITLE
[test](statisitics)Add partition stats test for mtmv.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add partition stats test for mtmv.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Review by morrySnow — DISMISSED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p1

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
