### PR TITLE
[fix](eq_for_null) Fix eq_for_null when both column is NOT only_null

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Previous PR https://github.com/apache/doris/pull/36004 fixed eq_for_null processing at least one column is only-null, this pr fixed the problem when eq_for_null processing neither column is only-null.

1. ut on be is modified, make sure test block is valid.
2. when eq_for_null is not short circuited by property only_null, we should not discard Const properties before passing them to function eq.
3. more ut, now the test coverage percentage of `comparison_equal_for_null.cpp` is 100%.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
image

**Comment by zhiqiang-hhhh** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
