### PR TITLE
[Bug](function) fix current_date not equal to curdate

### LINKED ISSUE #11451: [Bug] CURRENT_DATE函数返回日期无法与日期常量正确比较
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0

### What's Wrong?

CURRENT_DATE函数返回日期无法与日期常量正确比较， CURRENT_DATE()与当天日期比较返回false，而用CURDATE函数比较是正确的。

### What You Expected?

CURRENT_DATE()与当天日期能够正确比较，返回True。

### How to Reproduce?

SELECT CURDATE() = DATE '2022-08-03', CURRENT_DATE() = DATE '2022-08-03', CURDATE() = CURRENT_DATE(), CURRENT_DATE(), CURDATE();

curdate() = '2022-08-03 00:00:00'|current_date() = '2022-08-03 00:00:00'|curdate() = current_date()|current_date()|curdate() |
---|---|---|---|---|
1| 0|0|2022-08-03|2022-08-03|

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #11451

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [X] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [X] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [X] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [X] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [X] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — CHANGES_REQUESTED** [review]
FEFunctions in FE has the same problem. Could you fix them together?

**Comment by BiteTheDDDDt** [comment]
> FEFunctions in FE has the same problem. Could you fix them together?

FE function only have `curdate`, the result is right. Do you means I should add `current_date` to fe?

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by stalary — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
