### PR TITLE
[enhancement](testutil) Add math function ut test case

### PR DESCRIPTION
**Pull request by M1saka2003**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by M1saka2003** [comment]
run buildadd

**Comment by M1saka2003** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]

**Pull request closed without merging**
