### PR TITLE
[fix](Stmt)pre-block create stmt with column type `ALL`

### LINKED ISSUE #16741: [Bug] create table could create column with type 'ALL'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
```

```
+-------+------+------+------+---------+-------+
| Field | Type | Null | Key  | Default | Extra |
+-------+------+------+------+---------+-------+
| c1    | ALL  | Yes  | true | NULL    |       |
+-------+------+------+------+---------+-------+
```

and then, query it will throw exception
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: Index -1 out of bounds for length 33
```

### What You Expected?

cannot create table with a ALL type column

### How to Reproduce?

```sql
create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #16741

## Problem summary

Pre-block create stmt with `ALL` column type.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
CREATE stmt with `ALL` type will be blocked.
```bash
mysql> create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
ERROR 1105 (HY000): errCode = 2, detailMessage = Disable to create table with `ALL` type columns.

**Review by Yukang-Lian — COMMENTED** [review]
could you plz add some test?

**Comment by TangSiyang2001** [comment]
> could you plz add some test?

What kind of test? My test result was like below, it did work then:
```bash
mysql> create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
ERROR 1105 (HY000): errCode = 2, detailMessage = Disable to create table with `ALL` type columns.

**Comment by Yukang-Lian** [comment]
> > could you plz add some test?
> 
> What kind of test? My manual test result was like below,and it did work then:
> 
> ```shell
> mysql> create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
> ERROR 1105 (HY000): errCode = 2, detailMessage = Disable to create table with `ALL` type columns.
> ```

you can try to add FE UT or regression test.

**Comment by TangSiyang2001** [comment]
> > > could you plz add some test?
> > 
> > 
> > What kind of test? My manual test result was like below,and it did work then:
> > ```shell
> > mysql> create table test (c1 all) distributed by hash(c1) properties('replication_num'='1');
> > ERROR 1105 (HY000): errCode = 2, detailMessage = Disable to create table with `ALL` type columns.
> > ```
> 
> you can try to add FE UT or regression test.

A FE UT might be proper, I'll add it.

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.72 seconds
 stream load tsv:          481 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         40 seconds loaded 2358488459 Bytes, about 56 MB/s
 stream load orc:          69 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230214124831_clickbench_pr_96338.html

**Review by stalary — APPROVED** [review]
LGTM

**Pull request merged**
