### PR TITLE
[Feature](materialized-view) support ignore not slot is null when count(slot) not has key in mv

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

support ignore not slot is null when count(slot) not has key in mv

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by xzj7019 — APPROVED** [review]

**Pull request merged**
