### PR TITLE
[regression-test](framework) disable defining global variable in test groovy files

### PR DESCRIPTION
**Pull request by shuke987**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
We've met some regression-test cases failure due to define global variables in different .groovy files with same name. This pr try forbids defining global variables in groovy files, and remove all global variables defined in groovy files.

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run p0

**Comment by shuke987** [comment]
run p0

**Comment by shuke987** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
