### PR TITLE
[test](regression) Reduce dependency of other database in `test_alter_table_column`

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
