### PR TITLE
[fix](status) fix function code_as_string to private

### PR DESCRIPTION
**Pull request by ZI-MA**
# Proposed changes

Issue Number: close #xxx

## Problem summary

change the function code_as_string to private.(doris/be/src/common/status.h)

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by ZI-MA** [comment]
run buildall

**Comment by ZI-MA** [comment]
run p1

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
