### PR TITLE
[fix](planner)fix multi partition support datetime column

### LINKED ISSUE #16684: Error [1105] [HY000]: Range partition with batch partition: Failed to create table using datetime partition column
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

``` SQL
create table internal.demo.test(
id int,
gmt_create datetime
) ENGINE=OLAP
UNIQUE KEY( id, gmt_create)
PARTITION BY RANGE(`gmt_create`)(
FROM ("2023-01-01 00:00:00") TO ("2024-01-01 00:00:00") INTERVAL 1 DAY
)
DISTRIBUTED BY HASH(id) BUCKETS 5
```
Error:
> [1105] [HY000]: errCode = 2, detailMessage = Invalid range value format： errCode = 2, detailMessage = date literal [2023-01-01] is invalid: errCode = 2, detailMessage = Invalid datetime value: 2023-01-01

``` SQL
create table internal.demo.test(
id int,
gmt_create datetime
) ENGINE=OLAP
UNIQUE KEY( id, gmt_create)
PARTITION BY RANGE(`gmt_create`)(
FROM ("2023-01-01") TO ("2024-01-01") INTERVAL 1 DAY
)
DISTRIBUTED BY HASH(id) BUCKETS 5;
```

Error:
> [1105] [HY000]: errCode = 2, detailMessage = Invalid range value format： errCode = 2, detailMessage = date literal [2023-01-01] is invalid: errCode = 2, detailMessage = Invalid datetime value: 2023-01-01

### What You Expected?

How to create partition table like this?

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by catpineapple**
# Proposed changes

Issue Number: close #16684 

## Problem summary

multi partition support datetime column 

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.32 seconds
 stream load tsv:          479 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         41 seconds loaded 2358488459 Bytes, about 54 MB/s
 stream load orc:          69 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230214131202_clickbench_pr_96258.html

**Comment by catpineapple** [comment]
run p0

**Comment by morrySnow** [comment]
please add UT or P0 test case, and update doc if necessary

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run  clickbench

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
