### PR TITLE
[chore](restore) reduce logged unfinished snapshoting task

### PR DESCRIPTION
**Pull request by w41ter**
reduce logged unfinished snapshoting task

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run p0

**Comment by w41ter** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
