### PR TITLE
[enhance](FS) Improve FS error code

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Normalize (local & S3) FS error code:

| std::errc | Posix errno | Aws HttpResponseCode | Doris ErrorCode |
| ------- | ------- | ------- | ------- |
| io_error | EIO | \ | IO_ERROR |
| file_exists | EEXIST | \ | ALREADY_EXIST |
| no_such_file_or_directory | ENOENT | NOT_FOUND | NOT_FOUND |
| no_space_on_device | ENOSPC | \ | DISK_REACH_CAPACITY_LIMIT |
| permission_denied | EACCES | FORBIDDEN | PERMISSION_DENIED |
| others | others | others | INTERNAL_ERROR |

Remove some useless FS functions.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
