### PR TITLE
[test](migrate) move 2 cases from p2 to p0

### PR DESCRIPTION
**Pull request by morningman**
- test_external_credit_data
- test_upper_case_column_name
    Only move the hive related cases, the iceberg related will be done in next PR

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by AshinGau — APPROVED** [review]

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
