### PR TITLE
[Fix](signal) fix signal handler

### LINKED ISSUE #24142: [Bug] Doris native signal handler is not working
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

image

### What You Expected?

We should call doris's native signal handler

### How to Reproduce?

_No response_

### Anything Else?

doris::init_signals(); 

should be call after jni initialization

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
## Proposed changes

Issue Number: close #24142 

introduced by https://github.com/apache/doris/pull/23578

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
