### PR TITLE
[Enhancement] (nereids)implement DropStoragePolicyCommand in nereids

### LINKED ISSUE #42626: [Enhancement] (nereids)implement DropStoragePolicyCommand  in nereids
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropStoragePolicyCommand is supported in the legacy planner but needs implementation in Nereids. Use the syntax definition in DorisParser.g4, and refer to DropPolicyStmt.java in the legacy planner.

```unsupportedDropStatement : DROP STORAGE POLICY (IF EXISTS)? name=identifier```

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by msridhar78**
### What problem does this PR solve?

Issue Number: close #42626 

Related PR: #xxx

Problem Summary:
[Enhancement] (nereids)implement DropStoragePolicyCommand in nereids

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by msridhar78** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
we can add some cases to make sure implement is right

**Comment by msridhar78** [comment]
> we can add some cases to make sure implement is right

done

**Comment by msridhar78** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
