### PR TITLE
[regressioncase](nereids)tpcds 10t plan shape for external table

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
tracking tpcds 10t shape for exteranl table
simulating exteranl table by olaptable, 
1. inject row count
2. tables are distributed by random

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run  buildall

**Review by starocean999 — APPROVED** [review]

**Review by xzj7019 — APPROVED** [review]

**Pull request merged**
