### PR TITLE
[fix](jdbc catalog) Fixed data conversion problem when all data is null

### LINKED ISSUE #28204: [Bug] (jdbc catalog) When the field value of some tables is null, the query will report an error.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

CAUSED BY: ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Long;
	at org.apache.doris.qe.Coordinator.getNext(Coordinator.java:1278) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.sendResult(StmtExecutor.java:1538) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1473) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.handleQueryWithRetry(StmtExecutor.java:653) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:586) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:444) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:431) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:240) ~[classes/:?]
	at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:160) ~[classes/:?]
	at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:187) ~[classes/:?]
	at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:240) ~[classes/:?]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]

### What You Expected?

Results can be obtained.

### How to Reproduce?

CREATE TABLE numeric_table (
  id bigint(32),
  tinyint_col TINYINT,
  smallint_col SMALLINT,
  int_col INT,
  bigint_col BIGINT,
  decimal_col DECIMAL(10,2),
  float_col FLOAT(8,4),
  double_col DOUBLE(15,10),
  boolean_col BOOLEAN,
  date_col DATE,
  time_col TIME,
  datetime_col DATETIME,
  timestamp_col TIMESTAMP
);

INSERT INTO numeric_table (id, tinyint_col, smallint_col, int_col, bigint_col, decimal_col, float_col, double_col, boolean_col, date_col, time_col, datetime_col, timestamp_col) VALUES
(1, 1, 100, 1000, NULL, 10.50, 3.1415, 3.1415926535, TRUE, '2023-01-01', '12:34:56', '2023-01-01 12:34:56', CURRENT_TIMESTAMP),
(2, 0, -50, -500, -NULL, -5.25, -2.7182, -2.7182818284, FALSE, '2023-02-02', '23:59:59', '2023-02-02 23:59:59', CURRENT_TIMESTAMP),
(3, -1, 0, 0,NULL, 0.00, 0.0000, 0.0000000000, TRUE, '2023-03-03', '00:00:00', '2023-03-03 00:00:00', CURRENT_TIMESTAMP);

### Anything Else?

Because the type of a certain column is null and the `ColumnValueConverter` is null. But the type is forced to change.

image

Since the column values ​​are all null, the type cannot be recognized, so null is returned directly.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #28204

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
