### PR TITLE
[Dependence](Fe)Upgrade Fe dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
### be scanner
- Upgrade avro to 1.11.2
### fe
- Upgrade quartz to 2.5.0-rc1
- Upgrade maxcompute to 0.45-2-publish
- Binding  avro-ipc  to 1.11.2

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
