### PR TITLE
[fix](planner)fix <slot id> in create view and cause exception

### PR DESCRIPTION
**Pull request by sohardforaname**
# Proposed changes

Issue Number: close #xxx

## Problem summary

when creating view and the view containing window functions, the slot id will be in analytic info after the latter created. we fix it.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sohardforaname** [comment]
run p0

**Comment by sohardforaname** [comment]
run buildall

**Comment by sohardforaname** [comment]
run fe ut

**Comment by morningman** [comment]
Please add regression test case

**Comment by sohardforaname** [comment]
master will be also failed to create view, fix it on master.

**Pull request closed without merging**
