### PR TITLE
(imporve)Improve error message

### PR DESCRIPTION
**Pull request by LemonLiTree**
before:
image
now:
image

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run bulidall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by DongLiang-0 — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
