### PR TITLE
Show tablet lists in EXPLAIN OlapScanNode

### PR DESCRIPTION
**Pull request by lingbin**
#2315

### CODE REVIEW

**Review by morningman — CHANGES_REQUESTED** [review]
I think in addition to displaying some tablets in the explain result, we should support displaying all tablets in the query profile. This guarantees that if the number of tablets is greater than 10, there is still a way to get all the tablets.

In addition, we need to know which replica of tablet, not just the tablet id.
Maybe [tablet id - backend id] pair is better.

**Comment by lingbin** [comment]
The bad news is that the replica info cannot be obtained in `EXPLAIN`, so it is impossible to obtain the backend info.  
The reason is the replica can only be determined just before generating `PlanFragment`.

On the other hand, the most commonly used scenario should be when we manually construct conditions to track a problem. In this scenario, the query conditions will ensure that the number of tablets is relatively small.

**Review by imay — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
OK, add replica info later if required.

**Review by imay — APPROVED** [review]
LGTM

**Pull request merged**
