### PR TITLE
[Enhancement] (binlog) Rebuild binlog and binlog manager

### PR DESCRIPTION
**Pull request by deadlinefen**
**[ATTENTION] Clusters in pipeline need to GC all binlogs before upgrading to this version**  
  

Add dummy into binlog manager, dbBinlog, tableBinlog.  
Rebuild GC.

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.46 seconds
 stream load tsv:          443 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          26.1 seconds inserted 10000000 Rows, about 383K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711151248_clickbench_pr_176573.html

**Review by JackDrogon — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
