### PR TITLE
[function](random_bytes)add random_bytes function 

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #xxx

SELECT random_bytes(10);

random_bytes(10)      |
----------------------+
0x9b8ea00b7d1084bc5b26|

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
#31244

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
Fix document error @morrySnow .PTAL

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by liugddx** [comment]
run feut

**Comment by liugddx** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
