### PR TITLE
[opt](autoinc) Remove some restrictions on schema change on table that has auto-increment column

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

- #37186 forbids some schema change on table with auto-increment column, one of which is to forbid schema change that involves double write on tables which has auto-increment column. However, the process of generating auto-increment column values is before the distributing data to indexes. So this restriction can be removed.

branch-2.1-pick: https://github.com/apache/doris/pull/41096

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run cloud_p0

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by zhannngchen** [comment]
run p0

**Comment by dataroaring** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
