### PR TITLE
[Profile](runtimefilter) fix merge time of runtime filter

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

 fix merge time of runtime filter

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
run buildall

**Pull request merged**
