### PR TITLE
[fix](Nereids) div priority is not right

### LINKED ISSUE #30539: [Bug] SELECT 10.5 DIV 2 * 2 AS "mynum" Why is the result 2
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.3-rc6

### What's Wrong?

I would like to ask what is the result of executing this in the terminal and whether this is a problem.

`
mysql> SELECT 10.5 DIV 2 * 2 AS "mynum";
+-------+
| mynum |
+-------+
|     2 |
+-------+
1 row in set (0.01 sec)

mysql>
`

### What You Expected?

10

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morrySnow**
## Proposed changes

Issue Number: close #30539

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run pipelinex_p0

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by jackwener — APPROVED** [review]

**Pull request merged**
