### PR TITLE
[Bug](function) fix function define of Retention inconsist and change some static_cast to assert cast

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
…t to assert cast

# Proposed changes

```cpp
doris/be/src/vec/aggregate_functions/aggregate_function_retention.h:97:25: runtime error: downcast of address 0x7fe2c36596b0 which does not point to an object of type 'doris::vectorized::ColumnUInt8' (aka 'ColumnVector<unsigned char>')
0x7fe2c36596b0: note: object is of type 'doris::vectorized::ColumnVector<signed char>'
 00 00 00 00  98 a1 9c a2 56 55 00 00  01 00 00 00 00 00 00 36  10 a3 53 6f 56 55 00 00  10 a3 53 6f
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'doris::vectorized::ColumnVector<signed char>'
```

1. fix function define of `Retention` inconsist, this function return tinyint on `FE` and return uint8 on `BE`
2. make assert_cast support cast to derived
3. change some static cast to assert cast
4. support sum(bool)/avg(bool)

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.11 seconds
 stream load tsv:          430 seconds loaded 74807831229 Bytes, about 165 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230509104922_clickbench_pr_141019.html

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
