### PR TITLE
[docs](docs) Add release note 2.0.2

### PR DESCRIPTION
**Pull request by httpshirley**
## Proposed changes

Issue Number: close #xxx

<add release note 2.0.2>

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]

**Review by luzhijing — DISMISSED** [review]

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Comment by httpshirley** [comment]
run build all

**Comment by httpshirley** [comment]
run build all

**Comment by httpshirley** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]

**Pull request merged**
