### PR TITLE
[minor](show_export) make result of file url usable

### PR DESCRIPTION
**Pull request by Yulei-Yang**
real file of export result:
image

before:
image

after:
image

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run clickbench

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
LGTM

**Review by nextdreamblue — APPROVED** [review]

**Pull request merged**
