### PR TITLE
[improvement](extension) add new features to Mysql to doris tools

### PR DESCRIPTION
**Pull request by gnehil**
# Proposed changes

Issue Number: close #xxx

new feature:
1. create olap table
2. sync data from external table to olap table
3. new unified startup shell script with options
4. create external table, olap table and sync data by specified database
5. check result after data sync finished
6. jdbc catalog support

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
7. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
8. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
9. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.31 seconds
 load time: 473 seconds
 storage size: 17171902810 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221114050937_clickbench_pr_45398.html

**Review by hf200012 — DISMISSED** [review]
LGTM

**Comment by gnehil** [comment]
cc @Toms1999

**Comment by Toms1999** [comment]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by caoliang-web — APPROVED** [review]

**Comment by JNSimba** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by StarkLiuyin** [comment]
LGTM

**Pull request merged**
