### PR TITLE
[test](doc) add table design example in doris's doc to regression test

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run p0

**Comment by yagagagaga** [comment]
run cloud_p0

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
