### PR TITLE
[Improvement](Cloud) Avoid unnecessary RPC to meta service for watershed txn id.

### PR DESCRIPTION
**Pull request by wangshuo128**
## Proposed changes
This PR proposed to reduce the number of RPC from FE to meta service for next txn ID when register watershed txn ID.
Issue Number: close #xxx

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]
LGTM

**Comment by wangshuo128** [comment]
run buildall

**Comment by wangshuo128** [comment]
run buildall

**Comment by wangshuo128** [comment]
run p0

**Comment by wangshuo128** [comment]
run buildall

**Comment by wangshuo128** [comment]
run p0

**Review by w41ter — APPROVED** [review]

**Pull request merged**
