### PR TITLE
[Fix](executor)Fix workload thread start failed when follower convert to master

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
image
When follower fe convert to master fe，a non-master daemon thread may be started duplicately. this may throw a exception.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
