### PR TITLE
[fix](nereids)let query be able to forwarded to master

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes

some times the follower's meta data is out of date. so we need forward the query to master until the meta data is sync with master

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
does test it in multi-fe cluster?

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
