### PR TITLE
[fix](multi-catalog)Es catalog needs to verify whether it is a valid configuration.

### LINKED ISSUE #24305: [Bug](multi-catalog)Es catalog needs to verify whether it is a valid configuration.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Es configuration error address can also be.

### What You Expected?

If es is unavailable, catalog creation fails.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #24305

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — COMMENTED** [review]
Add regression test

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by liugddx** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
