### PR TITLE
[fix](compile) be cannot compile on MacOS

### PR DESCRIPTION
**Pull request by morrySnow**
build on MacOS meet error: reference to 'detail' is ambiguous. Because there is a detail namespace under std

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jacktengg — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
