### PR TITLE
[FIX](cast)fix full/right out join for cast array

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
in some case, we has code
```
        if (_join_op == TJoinOp::RIGHT_OUTER_JOIN || _join_op == TJoinOp::FULL_OUTER_JOIN) {
            _probe_column_convert_to_null = _convert_block_to_null(*input_block);
        }
``` 
then do next function like cast , but in function cast we assume block column is same with from_type.which will make status error 
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xiaokang — COMMENTED** [review]
please add testcase

**Comment by amorynan** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by amorynan** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by eldenmoon** [comment]
in some case, we has code
```
        if (_join_op == TJoinOp::RIGHT_OUTER_JOIN || _join_op == TJoinOp::FULL_OUTER_JOIN) {
            _probe_column_convert_to_null = _convert_block_to_null(*input_block);
        }
```
then do next function like cast , but in function cast we assume block column is same with from_type.which will make status error

**Pull request merged**
