### PR TITLE
[regression-test](fix) fix case with invalid grammer

### PR DESCRIPTION
**Pull request by shuke987**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Defining global variables in a test suite can easily introduce errors, such as variable conflicts in concurrent scenarios. 
In #44576 , a method for detecting global variables was introduced. 

That approach conflicts with the function calling like connect(user=user, password="pwd"). Furthermore, the connect(user=user, password="pwd") method cannot specify assignments to parameters with default values; values still need to be assigned according to the order of parameters. Therefore, modifying these calling method.

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by shuke987** [comment]
#45792 branch-3.0
#45791 branch-2.1

**Pull request merged**
