### PR TITLE
[fix](Nereids) mv in select materialized_view should disable show table

### PR DESCRIPTION
**Pull request by keanji-x**
## Proposed changes

mv in select materialized_view should disable show table,
because Nereids planner can output the string such as
`slot#[0]` in `toSql()` of `SlotRef`. Note this is only a
temporary solution, will use an expression translator later

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
