### PR TITLE
[feature](branch20) support statement to show views from database

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

cherry-pick: #32358

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
