### PR TITLE
[fix](partial update) use correct tablet schema for rowset writer in publish task

### PR DESCRIPTION
**Pull request by zhannngchen**
# Proposed changes

Issue Number: close #xxx

## Problem summary

fix core dump
```
F0526 14:30:32.979687 811726 tablet_schema.cpp:879] Check failed: ordinal < _num_columns ordinal:20, _num_columns:20
*** Check failure stack trace: ***
    @     0x563d33ba3d2d  google::LogMessage::Fail()
    @     0x563d33ba6269  google::LogMessage::SendToLog()
    @     0x563d33ba3896  google::LogMessage::Flush()
    @     0x563d33ba68d9  google::LogMessageFatal::~LogMessageFatal()
    @     0x563d167152a9  doris::TabletSchema::column()
    @     0x563d16c26401  doris::segment_v2::SegmentWriter::_create_writers()
    @     0x563d16c24b8b  doris::segment_v2::SegmentWriter::init()
    @     0x563d16c23e2a  doris::segment_v2::SegmentWriter::init()
    @     0x563d16e9ec9c  doris::BetaRowsetWriter::_do_create_segment_writer()
    @     0x563d16e8e1f6  doris::BetaRowsetWriter::_create_segment_writer()
    @     0x563d16e9922c  doris::BetaRowsetWriter::flush_single_memtable()
    @     0x563d16539d8b  doris::Tablet::calc_delete_bitmap()
    @     0x563d16540e65  doris::Tablet::update_delete_bitmap()
    @     0x563d16750d4a  doris::TxnManager::publish_txn()
    @     0x563d1674fd69  doris::TxnManager::publish_txn()
    @     0x563d16e16916  doris::TabletPublishTxnTask::handle()
    @     0x563d16e17a6d  doris::EnginePublishVersionTask::finish()::$_0::operator()()
    @     0x563d16e17a45  std::__invoke_impl<>()
    @     0x563d16e179e5  _ZSt10__invoke_rIvRZN5doris24EnginePublishVersionTask6finishEvE3$_0JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES5_E4typeEOS6_DpOS7_
    @     0x563d16e1781d  std::_Function_handler<>::_M_invoke()
    @     0x563d14b11e83  std::function<>::operator()()
    @     0x563d179be2a9  doris::FunctionRunnable::run()
    @     0x563d179abaa7  doris::ThreadPool::dispatch_thread()
    @     0x563d179d1644  std::__invoke_impl<>()
    @     0x563d179d151d  std::__invoke<>()
    @     0x563d179d14a5  _ZNSt5_BindIFMN5doris10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x563d179d134e  std::_Bind<>::operator()<>()
    @     0x563d179d1265  std::__invoke_impl<>()
    @     0x563d179d1205  _ZSt10__invoke_rIvRSt5_BindIFMN5doris10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @     0x563d179d0f2d  std::_Function_handler<>::_M_invoke()
    @     0x563d14b11e83  std::function<>::operator()()
    @     0x563d17983947  doris::Thread::supervise_thread()
*** Query id: 0-0 ***
*** Aborted at 1685082633 (unix time) try "date -d @1685082633" if you are using GNU date ***
*** Current BE git commitID: 9185b202c5 ***
```

The schema in Tablet don't contains __DORIS_DELETE_SIGN__ and __DORIS_SEQUENCE_COL__, should use schema in rowset.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.03 seconds
 stream load tsv:          440 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          26.0 seconds inserted 10000000 Rows, about 384K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526134616_clickbench_pr_151389.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.75 seconds
 stream load tsv:          446 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.5 seconds inserted 10000000 Rows, about 392K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526144159_clickbench_pr_151400.html

**Comment by zhannngchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.2 seconds
 stream load tsv:          445 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.4 seconds inserted 10000000 Rows, about 393K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230527072403_clickbench_pr_151785.html

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.48 seconds
 stream load tsv:          444 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          25.8 seconds inserted 10000000 Rows, about 387K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230529030023_clickbench_pr_152423.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
