### PR TITLE
[regression-test](test) enable some cases

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Review by Thearas — COMMENTED** [review]
-

**Review by Thearas — COMMENTED** [review]
-

**Comment by shuke987** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
