### PR TITLE
[feature](ci): add scope labeler

### PR DESCRIPTION
**Pull request by jackwener**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

auto add label according to the files which are changed.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
Maybe, the CI can add more `file location` -> label

**Comment by morningman** [comment]
Maybe we need to use submodules `[.github](https://github.com/apache/incubator-doris/tree/master/.github)/actions/`
Or we have to ask Apache Infra to add permission for this Github Action.

**Comment by jackwener** [comment]
labeler is official action labeler--https://github.com/actions/labeler

We can see it's same group checkout--https://github.com/actions/checkout

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
