### PR TITLE
[opt](regression) ./run-regression.sh -d parameter accept "regression-test/suites/" as prefix

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

./run-regression.sh accept -d parameter with "./regression-test/suites/" or “regression-test/suites/" prefix
for example:
./run-regression-test.sh --run -d regression-test/suites/nereids_tpch_shape_sf1000_p0/shape -s q1
with the prefix, we could use command completion (supported by shell) to indicate with directory to run 

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run cloud_p0

**Review by zclllyybb — COMMENTED** [review]
then should also sync help-doc of `run-regression-test.sh`

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run cloud_p0

**Review by zclllyybb — APPROVED** [review]

**Comment by englefly** [comment]
run p0

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
