### PR TITLE
[Chore](Job)It is forbidden to change the status of internal JOB through PAUSE/RESUME/DROP

### PR DESCRIPTION
**Pull request by CalvinKirs**
…

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run pipelinex_p0

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run pipelinex_p0

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
