### PR TITLE
[pipeline](branch-2.0) pr to branch-2.0 also require to run regressio…

### PR DESCRIPTION
**Pull request by hello-stephen**
…n p0

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
please merge #25959 first

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run pipelinex_p0

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
