### PR TITLE
[fix](createTableLike) fix syntax error for CreateTableLikeStmt with partition properties

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

Issue Number: close #xxx
case:
create a partitioned table and set partition storage policy
`CREATE TABLE table1
    (
        k1 DATE,
        k2 INT,
        V1 VARCHAR(2048) REPLACE
    ) PARTITION BY RANGE (k1) (
        PARTITION p1 VALUES LESS THAN ("2022-01-01") ("storage_policy" = "test_policy")
    ) DISTRIBUTED BY HASH(k2) BUCKETS 1
    PROPERTIES (
        "replication_num"="1"
    );`

then create a new table table2 : `create table table2 like table1`, get a syntax error：
image

change partition sql string to match create table syntax.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run external

**Comment by DarvenDuan** [comment]
run performance

**Review by caiconghui — APPROVED** [review]
LGTM

**Comment by GoGoWen** [comment]
LGTM

**Review by GoGoWen — APPROVED** [review]
LGTM

**Pull request merged**
