### PR TITLE
[Feature](executor)Workload Group support Non-Pipeline Execution

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
Workload Group support Non-Pipeline Execution

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
