### PR TITLE
[enhancement](timeout) replace query timeout with exec timeout

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

introduce: #16343

## Problem summary

pr #16343 made an api-change, use execution_timeout to enrich the semantics of original query_timeout, and execution_timeout got a more general semantics than query_timeout. When I was working with MasterOpExecutor, I found that when forwarding to master, the timeout used for controlling the connection is still query_timeout.

Therefore, I made some updates related to this feature.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run arm

**Pull request merged**
