### PR TITLE
[fix](cast)fix variant cast 

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
some case in fe planner, we should specialize cast return type instead of defined type in table 
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run compile

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run cloud_p1

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
