### PR TITLE
[fix](inverted index) fix query fail caused by FullTextIndexReader doesn't check index file whether exists

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes
**(1)  `=` predicate should support INVERTED_INDEX_FILE_NOT_FOUND error.** 
image

the problem: 
 FullTextIndexReader doesn't check file and throws CLuceneError directly and lead to query error. 
image

**(2) refactor some java style code in C++ file**

**(3) fix MatchPredicate dose not check the error code** 

**(4) fix ARM p0 test date type error** 

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p0

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Review by Tanya-W — COMMENTED** [review]
LGTM

**Pull request closed without merging**
