### PR TITLE
[Improve](common)Optimize logging performance with LOG.isDebugEnabled()

### PR DESCRIPTION
**Pull request by CalvinKirs**
In a logging system, when the log level is configured to not output logs of a certain level, by checking LOG.isDebugEnabled() before the log output statement, the overhead of string concatenation can be avoided. When performing string concatenation, even if the log level does not meet the output condition, the string concatenation operation will still be executed, which can lead to unnecessary performance overhead.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by BitoAgent** [comment]
## PR Run Status

- **Limitations and other issues:** Failure - Unfortunately, this PR is too big for us to review. Please either conduct the review manually or break it into smaller PRs.  We are working to address this limitation in Bito.

**Pull request merged**
