### PR TITLE
[fix](memory) Fix prune all LRU Cache based on number

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

For NUMBER-based LRU Cache, if usage greater than CACHE_MIN_FREE_NUMBER allows prune all.

In the past, mem_consumption was greater than CACHE_MIN_FREE_SIZE to prune all, this will cause prune be delayed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Pull request merged**
