### PR TITLE
[Fix](doc) Fixed some errors in the documentation

### PR DESCRIPTION
**Pull request by xingyingone**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
run buildall

**Review by alexxing662 — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
