### PR TITLE
[Chore](topn) add case for topn opt

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
add case for topn opt

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
