### PR TITLE
[Refactor](load) Using OwnedSlice to replace Slice

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

This PR prepares for the forward movement of memtable. As the forward movement of memtable involves the work of rpc sending slices, OwnedSlice needs to be used instead of Slice to ensure the correctness of memory management.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.65 seconds
 stream load tsv:          457 seconds loaded 74807831229 Bytes, about 156 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          68.1 seconds inserted 10000000 Rows, about 146K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230628094416_clickbench_pr_169240.html

**Comment by HHoflittlefish777** [comment]
run p1

**Comment by HHoflittlefish777** [comment]
run p1

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @HHoflittlefish777

**Pull request closed without merging**
