### PR TITLE
[feature](tools)draw a graphic profile

### PR DESCRIPTION
**Pull request by englefly**
### how to get profile.png
1. execute a sql file, and draw its profile  
          python3 profile_viewer.py -sql [path to sql file]

2. draw a given profile
          python3 profile_viewer.py -query_id [query_id]
    
    graphviz is required(https://graphviz.org/)
    on linux: apt install graphviz
    on mac: brew install graphviz

### related changes
reimplement rest api: /profile/json/{query_id} to return profile in json format. currently, json profile only contains two counters: RowsReturned and TotalTime

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by starocean999 — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Review by hello-stephen — APPROVED** [review]

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
