### PR TITLE
[fix](jdbc_catalog) fix error datetime literal caused be core

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #34975

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run buildall

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
this PR introduce a behavior change, below case will failed after this PR
```sql
CREATE TABLE `roles` (
                role_id       INT,
                occupation    VARCHAR(32),
                camp          VARCHAR(32),
                register_time DATE
            )
            UNIQUE KEY(role_id)
            PARTITION BY RANGE (role_id)
            (
                PARTITION p1 VALUES LESS THAN ("10")
            )
            DISTRIBUTED BY HASH(role_id) BUCKETS 1
            PROPERTIES (
                "replication_allocation" = "tag.location.default: 1",
                "binlog.enable" = "true"
            );


INSERT INTO `roles` VALUES
            (0, 'who am I', NULL, NULL),
            (1, 'mage', 'alliance', '2018-12-03 16:11:28'),
            (2, 'paladin', 'alliance', '2018-11-30 16:11:28'),
            (3, 'rogue', 'horde', '2018-12-01 16:11:28'),
            (4, 'priest', 'alliance', '2018-12-02 16:11:28'),
            (5, 'shaman', 'horde', NULL),
            (6, 'warrior', 'alliance', NULL),
            (7, 'warlock', 'horde', '2018-12-04 16:11:28'),
            (8, 'hunter', 'horde', NULL); 
```

the original plan is right. the bug should be fixed on BE

**Pull request merged**
