### PR TITLE
[enhance](S3FileWriter) abort when s3 file writer abnormally quite and optimize s3 buffer pool

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes

Issue Number: close #xxx
1. reduce s3 buffer pool's ctor cost
2. before this pr, if one s3 file writer return err when calling append or close function, the caller will not call abort function which result in one confusing DCHECK failed like the following picture
img_v2_207b284f-b2f8-4e0e-8ad2-29ad0bdb6dbg

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run beut

**Comment by ByteYue** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by ByteYue** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
