### PR TITLE
[feature](function) support ngram_search function

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

```
mysql [test]>select ngram_search('123456789' , '12345' , 3);
+---------------------------------------+
| ngram_search('123456789', '12345', 3) |
+---------------------------------------+
|                                   0.6 |
+---------------------------------------+
1 row in set (0.01 sec)

mysql [test]>select ngram_search("abababab","babababa",2);
+-----------------------------------------+
| ngram_search('abababab', 'babababa', 2) |
+-----------------------------------------+
|                                       1 |
+-----------------------------------------+
1 row in set (0.01 sec)
```

doc https://github.com/apache/doris-website/pull/899

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by superdiaodiao — COMMENTED** [review]
It seems we should add the function in this file:
`gensrc/script/doris_builtins_functions.py`

**Comment by Mryange** [comment]
run feut

**Comment by Mryange** [comment]
> It seems we should add the function in this file: `gensrc/script/doris_builtins_functions.py`


The doris_builtins_functions.py is used for the original planner, but the original planner is about to be removed.

**Comment by superdiaodiao** [comment]
> The doris_builtins_functions.py is used for the original planner, but the original planner is about to be removed.

get✔

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
Add Doc please

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
