### PR TITLE
[fix](test) fix case of test_unique_table_new_sequence

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

pr #28105 and #28031 merging conflict caused this case to fail.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
