### PR TITLE
[docs](load-balancing):delete duplicate sentences and improve the documentation description

### PR DESCRIPTION
**Pull request by vinlee19**
## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
@luzhijing PTAL

**Comment by zy-kkk** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
