### PR TITLE
[fix](multicatalog) fix npe issue when alter property for a non-exist catalog

### PR DESCRIPTION
**Pull request by Yulei-Yang**
Issue:
```sql
mysql> ALTER CATALOG ctl_not_exist_not_exist SET PROPERTIES ('s3.access_key' = 'xxxx');                                    
ERROR 1105 (HY000): Unexpected exception: null 
```

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buidlall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
lgtm

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
