### PR TITLE
[Bug](aggregation) fix core dump on 2nd phase aggregate

### LINKED ISSUE #11786: [Bug] BE crash with query `select avg(distinct k1), avg(k2) from test2;`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
F0815 16:39:54.389199  8227 vaggregation_node.cpp:613] Check failed: _aggregate_evaluators[i]->input_exprs_ctxs().size() == 1 && _aggregate_evaluators[i]->input_exprs_ctx
s()[0]->root()->is_slot_ref()
```

### What You Expected?

No error

### How to Reproduce?

Build BE with ASAN

```
CREATE TABLE `test2` (
  `k0` boolean NULL,
  `k1` tinyint(4) NULL,
  `k2` smallint(6) NULL,
  `k3` int(11) NULL,
  `k4` bigint(20) NULL,
  `k5` decimal(9, 3) NULL,
  `k6` char(5) NULL,
  `k10` date NULL,
  `k11` datetime NULL,
  `k7` varchar(20) NULL,
  `k8` double MAX NULL,
  `k9` float SUM NULL,
  `k12` text REPLACE_IF_NOT_NULL NULL,
  `k13` largeint(40) REPLACE NULL
) ENGINE=OLAP
AGGREGATE KEY(`k0`, `k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);

insert into test2 values(1,2,3,4,5,6,"7",8,9,10,11,12,13,14);

select avg(distinct k1), avg(k2) from test2;
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #11786

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
Pls add regression test

**Review by mrhhsg — DISMISSED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
