### PR TITLE
[fix](map)fix upgrade behavior from 1.2 version

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
see also with https://github.com/apache/doris/pull/36635/files
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]

**Pull request merged**
