### PR TITLE
[improvement](ssb) run-ssb-queries.sh and run-ssb-flat-queries.sh add analyze database with sync and calculate total time

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run  buildall

**Comment by hello-stephen** [comment]
LGTM

**Review by hello-stephen — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
