### PR TITLE
[cherry-pick] Cherry-pick  report runtime workload statistics

### PR DESCRIPTION
**Pull request by wangbo**
[Feature](profile)Support report runtime workload statistics #29591
    [feature](auditlog)Add runtime cpu time/peak memory metric #29925
    [Fix](executor)Fix Grayscale upgrade be code dump when report statistics #29843

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by hello-stephen** [comment]
run performance

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
