### PR TITLE
Increased compatibility with mysql

### PR DESCRIPTION
**Pull request by stalary**
Add divPrecisionIncrement and utf8-superset transform

### CODE REVIEW

**Comment by kangkaisen** [comment]
@stalary Hi，Please add  a issue for this PR. Thanks.

**Review by imay — APPROVED** [review]
LGTM

**Comment by stalary** [comment]
> @stalary Hi，Please add a issue for this PR. Thanks.

okay

**Comment by stalary** [comment]
https://github.com/apache/incubator-doris/pull/3235 issue

**Pull request merged**
