### PR TITLE
[enhancement](show-frontends-disks) Add disk info corresponding to deploy dir in frontend disk info

### PR DESCRIPTION
**Pull request by yongjinhou**
## Proposed changes

Issue Number: close #xxx

Add disk information corresponding to deploy dir in frontend disk info.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luozenglin — DISMISSED** [review]
LGTM

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run external

**Review by luozenglin — APPROVED** [review]
LGTM

**Comment by yongjinhou** [comment]
run p0

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
