### PR TITLE
[feature](merge-cloud) Add drop cloud table

### PR DESCRIPTION
**Pull request by yujun777**
Co-authored-by: Luwei <[814383175@qq.com](mailto:814383175@qq.com)>
Co-authored-by: deardeng <[565620795@qq.com](mailto:565620795@qq.com)>
Co-authored-by: Gavin Chou <[gavineaglechou@gmail.com](mailto:gavineaglechou@gmail.com)>
Co-authored-by: Lightman <[31928846+Lchangliang@users.noreply.github.com](mailto:31928846+Lchangliang@users.noreply.github.com)>
Co-authored-by: zhengyu <[freeman.zhang1992@gmail.com](mailto:freeman.zhang1992@gmail.com)>
Co-authored-by: Lei Zhang <[1091517373@qq.com](mailto:1091517373@qq.com)>
Co-authored-by: AlexYue <[yj976240184@gmail.com](mailto:yj976240184@gmail.com)>
Co-authored-by: Xiaocc <[598887962@qq.com](mailto:598887962@qq.com)>
Co-authored-by: panDing19 <[56944854+panDing19@users.noreply.github.com](mailto:56944854+panDing19@users.noreply.github.com)>
Co-authored-by: plat1ko <[platonekosama@gmail.com](mailto:platonekosama@gmail.com)>
Co-authored-by: zhangdong <[493738387@qq.com](mailto:493738387@qq.com)>
Co-authored-by: walter <[w41ter.l@gmail.com](mailto:w41ter.l@gmail.com)>

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by w41ter — APPROVED** [review]

**Review by luwei16 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Pull request merged**
