### PR TITLE
[improve](routine load) ensure load balance after scaling up BE nodes

### PR DESCRIPTION
**Pull request by sollhui**
### What problem does this PR solve?

We scaling up from three BE nodes to five BE nodes, but from the monitoring perspective, only the previous three nodes have written traffic.
image

This pr aims to ensure load balance after scaling up BE nodes.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
