### PR TITLE
[BUG] fix profile not working with sql_cache enabled

### LINKED ISSUE #7104: [Bug] query profile is not working when sql cache is enabled
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

f93dae98e41752663ff12a443c5a46914c7aae7a

### What's Wrong?

When enable both `sql_cache` and `profile`, sql stmt is throw  `NullPointerException` except the first time.

```sql
mysql> show variables like '%cache%';
+------------------------+---------+
| Variable_name          | Value   |
+------------------------+---------+
| enable_partition_cache | false   |
| enable_sql_cache       | true    |
| query_cache_size       | 1048576 |
| query_cache_type       | 0       |
+------------------------+---------+
4 rows in set (0.00 sec)

mysql> show variables like '%profile%';
+----------------+-------+
| Variable_name  | Value |
+----------------+-------+
| enable_profile | true  |
+----------------+-------+
1 row in set (0.00 sec)

mysql> select c3, sum(c4) from (select c1, c2, c3, c4 from tb_test_1 where c1 = 1)a  where c2=3 group by c3;
+------+-----------+
| c3   | sum(`c4`) |
+------+-----------+
|    2 |         7 |
|    3 |         3 |
+------+-----------+
2 rows in set (0.01 sec)

mysql> select c3, sum(c4) from (select c1, c2, c3, c4 from tb_test_1 where c1 = 1)a  where c2=3 group by c3;
ERROR 1064 (HY000): NullPointerException, msg: null
```

### What You Expected?

Query successfully.

### How to Reproduce?

1. `set enable_sql_cache=true;`
2. `set enable_profile=true;`
3. execute sql stmt `select c3, sum(c4) from (select c1, c2, c3, c4 from tb_test_1 where c1 = 1)a  where c2=3 group by c3;` the first is success.
4. Execute once, error.

### Anything Else?

Error log in FE:
```log
2021-11-12 15:19:39,757 WARN (doris-mysql-nio-pool-0|179) [StmtExecutor.execute():409] execute Exception
java.lang.NullPointerException: null
        at org.apache.doris.qe.StmtExecutor.initProfile(StmtExecutor.java:230) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.writeProfile(StmtExecutor.java:475) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:346) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:288) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:217) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:353) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:554) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

fix #7104.

We can distinguish whether the cache is hit or not according to the profile.

When sql cache is hit,`Is Cached: Yes`. The profile is like this:

```
Query:
    Summary:
          -  Query  ID:  550eb34b2f5541ef-9bfe252bb4c88841
          -  Start  Time:  2021-11-12  15:58:06
          -  End  Time:  2021-11-12  15:58:06
          -  Total:  4ms
          -  Query  Type:  Query
          -  Query  State:  EOF
          -  Doris  Version:  trunk
          -  User:  root
          -  Default  Db:  default_cluster:example_db
          -  Sql  Statement:  select  c3,  sum(c4)  from  (select  c1,  c2,  c3,  c4  from  tb_test_1  where  c1  =  1)a    where  c2=3  group  by  c3
          -  Is  Cached:  Yes
        Execution  Summary:
              -  Analysis  Time:  1.344ms
              -  Plan  Time:  1.84ms
              -  Schedule  Time:  N/A
              -  Wait  and  Fetch  Result  Time:  N/A
    Execution  Profile  550eb34b2f5541ef-9bfe252bb4c88841:(Active:  4.946ms,  %  non-child:  100.00%)
        Fragment  0:
```

**Note**:  `Is Cached: Yes`.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #7104 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by pengxiangyu — DISMISSED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
You'd better to init cache profile and does not rely on coordinator

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
