### PR TITLE
[refactor](cluster)(step-2) remove cluster related to Backend 

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: #19897

## Problem summary

Remove cluster info in Backend, tablet scheduler

1. Remove the `Cluster` and `SystemDecommission` column in `show backends`, `show proc '/backends'` and `backends()` tvf.

No logic changed.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
