### PR TITLE
[fix](multi-table) fix multi table task cannot end

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

```
detailMessage = failed to send task: errCode = 2, detailMessage = failed to submit task. error code: TOO_MANY_TASKS, msg: ()[TOO_MANY_TASKS]7edb0aedafb240f4-9ae9b5cd22451ff4
```
When exec multi table task, it can not end when exec plan error, which causes other routine load task can not submit.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
