### PR TITLE
[Fix](regression) Fix flaky case in test_stream_load_2pc

### PR DESCRIPTION
**Pull request by liaoxin01**

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by sollhui — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
