### PR TITLE
[Fix](ut)(show) added UT cases for show backup stmt and code fix

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

 * Added UT for show backup
 * fixed some toSql() space and missing CLAUSE
 * Updated Doc with relevant syntax

### CODE REVIEW

**Comment by dataroaring** [comment]
Could you add a regression test?

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
