### PR TITLE
[fix](datatype) fix some bugs about data type array datetimev2 and decimalv3

### LINKED ISSUE #15855: [Bug] some agg functions return wrong results when the param type is array(datetimev2)
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?
#15813 maybe they are releated.
```sql
MySQL [test]> select array_min(array(cast ('2022-12-02 22:23:24.999999' as datetimev2(6))));
+-----------------------------------------------------------------------+
| array_min(array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(6)))) |
+-----------------------------------------------------------------------+
| 2022-12-02 22:23:24                                                   |
+-----------------------------------------------------------------------+
1 row in set (0.01 sec)

MySQL [test]> select array_max(array(cast ('2022-12-02 22:23:24.999999' as datetimev2(6))));
+-----------------------------------------------------------------------+
| array_max(array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(6)))) |
+-----------------------------------------------------------------------+
| 2022-12-02 22:23:24                                                   |
+-----------------------------------------------------------------------+
1 row in set (0.01 sec)

```

### What You Expected?

```sql
MySQL [test]> select array_min(array(cast ('2022-12-02 22:23:24.999999' as datetimev2(6))));
+-----------------------------------------------------------------------+
| array_min(array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(6)))) |
+-----------------------------------------------------------------------+
| 2022-12-02 22:23:24.999999                                            |
+-----------------------------------------------------------------------+
1 row in set (0.01 sec)

MySQL [test]> select array_max(array(cast ('2022-12-02 22:23:24.999999' as datetimev2(6))));
+-----------------------------------------------------------------------+
| array_max(array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(6)))) |
+-----------------------------------------------------------------------+
| 2022-12-02 22:23:24.999999                                            |
+-----------------------------------------------------------------------+
1 row in set (0.01 sec)

```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #15936: [Bug] array(datetimev2) return wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
MySQL [test]> select array(cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4))) from test;
+-----------------------------------------------------------------------------------------------------------------+
| array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)), CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4))) |
+-----------------------------------------------------------------------------------------------------------------+
| [2022-12-02 22:23:24.999900, 2022-12-02 22:23:23.999900]                                                        |
| [2022-12-02 22:23:24.999900, 2022-12-02 22:23:23.999900]                                                        |
+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.16 sec)
```

### What You Expected?

```sql
MySQL [test]> select array(cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4))) from test;
+-----------------------------------------------------------------------------------------------------------------+
| array(CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)), CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4))) |
+-----------------------------------------------------------------------------------------------------------------+
| [2022-12-02 22:23:24.9999, 2022-12-02 22:23:23.9999]                                                        |
| [2022-12-02 22:23:24.9999, 2022-12-02 22:23:23.9999]                                                        |
+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.16 sec)
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #15939: [Bug] array(decimalv3) return wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
MySQL [test]> select array(cast (24.99 as decimalv3(8,2)),cast (25.99 as decimalv3(8,2))) from test;
+---------------------------------------------------------------------+
| array(CAST(24.99 AS DECIMALV3(8,2)), CAST(25.99 AS DECIMALV3(8,2))) |
+---------------------------------------------------------------------+
| [-779803776, 220196224]                                             |
| [-779803776, 220196224]                                             |
+---------------------------------------------------------------------+
2 rows in set (0.02 sec)
```

### What You Expected?

```sql
MySQL [test]> select array(cast (24.99 as decimalv3(8,2)),cast (25.99 as decimalv3(8,2))) from test;
+---------------------------------------------------------------------+
| array(CAST(24.99 AS DECIMALV3(8,2)), CAST(25.99 AS DECIMALV3(8,2))) |
+---------------------------------------------------------------------+
| [24.99, 25.99]                                                      |
+---------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #16015: [Bug] some agg functions return wrong results when the param type is array(decimal)
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
mysql> select array_min(array(cast (22.99 as decimal(10,3))));
+------------------------------------------------+
| array_min(array(CAST(22.99 AS DECIMAL(10,3)))) |
+------------------------------------------------+
|                                   22.990000000 |
+------------------------------------------------+
1 row in set (0.02 sec)

mysql> select array_min(array(cast (22.99 as decimal(10,4))));
+------------------------------------------------+
| array_min(array(CAST(22.99 AS DECIMAL(10,4)))) |
+------------------------------------------------+
|                                   22.990000000 |
+------------------------------------------------+
1 row in set (0.03 sec)

mysql> select array_min(array(cast (22.99 as decimalv3(10,3))));
+--------------------------------------------------+
| array_min(array(CAST(22.99 AS DECIMALV3(10,3)))) |
+--------------------------------------------------+
|                                               22 |
+--------------------------------------------------+
```

### What You Expected?

```sql
mysql> select array_min(array(cast (22.99 as decimal(10,3))));
+------------------------------------------------+
| array_min(array(CAST(22.99 AS DECIMAL(10,3)))) |
+------------------------------------------------+
|                                   22.990 |
+------------------------------------------------+
1 row in set (0.02 sec)

mysql> select array_min(array(cast (22.99 as decimal(10,4))));
+------------------------------------------------+
| array_min(array(CAST(22.99 AS DECIMAL(10,4)))) |
+------------------------------------------------+
|                                   22.9900 |
+------------------------------------------------+
1 row in set (0.02 sec)
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #16131: [Bug] cast to datetimev2 return wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

mysql> select cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4)) from test;
+-----------------------------------------------------+-----------------------------------------------------+
| CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)) | CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4)) |
+-----------------------------------------------------+-----------------------------------------------------+
| 2022-12-02 22:23:24.999900                          | 2022-12-02 22:23:23.999900                          |
+-----------------------------------------------------+-----------------------------------------------------+
1 row in set (0.03 sec)

mysql> mysql> select cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4));
+-----------------------------------------------------+-----------------------------------------------------+
| CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)) | CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4)) |
+-----------------------------------------------------+-----------------------------------------------------+
| 2022-12-02 22:23:24.999900                          | 2022-12-02 22:23:23.999900                          |
+-----------------------------------------------------+-----------------------------------------------------+
1 row in set (0.00 sec)

### What You Expected?

```sql
mysql> select cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4)) from test;
+-----------------------------------------------------+-----------------------------------------------------+
| CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)) | CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4)) |
+-----------------------------------------------------+-----------------------------------------------------+
| 2022-12-02 22:23:24.9999                          | 2022-12-02 22:23:23.9999                          |
+-----------------------------------------------------+-----------------------------------------------------+
1 row in set (0.03 sec)

mysql> select cast ('2022-12-02 22:23:24.999999' as datetimev2(4)),cast ('2022-12-02 22:23:23.999999' as datetimev2(4));
+-----------------------------------------------------+-----------------------------------------------------+
| CAST('2022-12-02 22:23:24.999999' AS DATETIMEV2(4)) | CAST('2022-12-02 22:23:23.999999' AS DATETIMEV2(4)) |
+-----------------------------------------------------+-----------------------------------------------------+
| 2022-12-02 22:23:24.9999                          | 2022-12-02 22:23:23.9999                          |
+-----------------------------------------------------+-----------------------------------------------------+
1 row in set (0.00 sec)
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yukang-Lian**
# Proposed changes

Issue Number: close #16131 close #15936  close #15855 close #16015 close #15939

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.96 seconds
 load time: 486 seconds
 storage size: 17122433194 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230122143650_clickbench_pr_84927.html

**Comment by tang350476527** [comment]
谢谢您的来信，您的邮件已收到！

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
