### PR TITLE
[fix](round) Fix incorrect decimal scale inference in round functions

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Function execution in backend should always use the scale from planner to create result Decimal for round likes functions.

The problem is fixed in this pr, by:
1. modify scale inference rule on FE like what https://github.com/apache/doris/pull/34473 did
2. round function execution will alway make sure result decimal has exactly same scale with arguments from planner
3. add test cases for using float as scale arguments(which can not be executed correctly before)

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
https://github.com/apache/doris/pull/34391

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run cloud_p1

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Comment by zhiqiang-hhhh** [comment]
@yiguolei branch-2.0 does not need this pr, since previous pr is not picked to 2.0

**Pull request merged**
