### PR TITLE
[improvement](inverted index) skip write index on load and generate index on compaction

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

Issue Number: close #xxx

To reduce CPU and IO resource usage for writing inverted index, skip it on first time load and delay it to compaction.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by qidaye — COMMENTED** [review]
Please add usage docs.

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
> Please add usage docs.

Thanks for your remind. Docs and test cases are added.

**Comment by xiaokang** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
