### PR TITLE
[opt](bytebuffer) allocate ByteBuffer memory by Allocator and make it exception safe

### PR DESCRIPTION
**Pull request by sollhui**
At present, the memory allocation of `ByteBuffer` is done through `new char[capacity_]`. Now, it is uniformly allocated by `Allocator` for the following purposes:
1. Better memory statistics
2. Better support for memory limit check

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
