### PR TITLE
Sankarshan mishra patch 1

### LINKED ISSUE #8721: [Enhancement] Remove some unused include
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There are many redundant Header file included.

We can remove them.

### Solution

This is a good related tools--[IWYU](https://github.com/include-what-you-use/include-what-you-use)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SankarshanMishra**
## added yaml file in .github/workflows

Issue Number: close #8721

 used  Include what you use github action to remove unused headers.

## Further comments
Kindly guide me and help me out because It is my first opensource contribution.

### CODE REVIEW

**Comment by SankarshanMishra** [comment]
Dear Maintainer I am waiting for you to kindly review this pull request, and make me realize if I have made some error in it or accept the pull request kindly look into the pull request. Thank You.

**Comment by SankarshanMishra** [comment]
Dear Maintainer I am waiting for you to kindly review this pull request, and make me realize if I have made some error in it or accept the pull request kindly look into the pull request. Thank You.

**Comment by jackwener** [comment]
Sorry for the late reply. It seems that there is not much need to solve this issue at the moment; I forgot to close it earlier.

Thanks for your contribution.

**Comment by SankarshanMishra** [comment]
Hello Sir,

Thank you for your appreciation of my contributions to the repository! I'm
excited to continue contributing and am eager to explore new areas that
could be beneficial for the project.

While I currently adept with basics Docker, Java, Spring, JUnit testing,
and GitHub workflow actions, I'm open to broadening my skill set to better
align with the project's needs.

Are there specific technologies or domains outside of my current expertise
that you believe would be valuable for contributing to the repository? I'm
keen to hear your suggestions and embark on learning paths that would
enhance my contributions.

Furthermore, if there are any resources or recommended learning materials
you could share to expedite my skill development in these new areas, I
would greatly appreciate it.

Thank you once again for your support, and I look forward to your guidance
on how I can further contribute to the project's success.

Best regards,
Sankarshan Mishra
(21) Sankarshan Mishra | LinkedIn
<https://www.linkedin.com/in/sankarshanmishra/>

**Pull request closed without merging**
