### PR TITLE
[fix](paimon)fix type convert for paimon

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

fix type convert for paimon

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by AshinGau — DISMISSED** [review]

**Review by zddr — APPROVED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
