### PR TITLE
[feature](json)support explode_json_object func

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

backport: https://github.com/apache/doris/pull/36887
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
