### PR TITLE
[Vec][Opt] better memequal impl to speed up string compare

### PR DESCRIPTION
**Pull request by zbtzbtzbt**
## Problem Summary:
issue  https://github.com/apache/incubator-doris/issues/8283 record detail test data.

like https://github.com/apache/incubator-doris/pull/8214

faster string compare operator in vec engine and no-vec engine.

@HappenLee 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
do the same opt in not vec query

**Comment by morningman** [comment]
compile failed

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zbtzbtzbt** [comment]
> compile failed

now it's ok

**Review by morningman — APPROVED** [review]

**Pull request merged**
