### PR TITLE
[opt](conf) modify the default fe be config file

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Refine the default fe.conf and be.conf

1. Modify the default jvm opt, only leave jvm opt for jdk8 and jdk17, remove jdk9 and jdk11.
2. Add gc log config, the rollnum and the log size
3. Modify the config file for pipeline p0 and p1

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run p0

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
