### PR TITLE
[fix](insert) make group commit wal_manager exit elegantly

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
now be exit will hang because of wal_manager relay thread dosen't exit, this pr fix it.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
