### PR TITLE
[doc] Fix two urls at README.md

### LINKED ISSUE #11087: [DOC] README.md at least 2 url is not working
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Compile and install
See [Compilation](https://doris.apache.org/docs/install/source-install/compilation-with-ldb-toolchain.html)

Getting start
See [Basic Usage](https://doris.apache.org/docs/data-table/basic-usage.html)

The 2 url is not working. eg:
image

### What You Expected?

Fix it.

### How to Reproduce?

_No response_

### Anything Else?

1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shenxingwuying**
# Proposed changes

https://github.com/apache/doris/issues/11087
Issue Number: close #11087

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hf200012** [comment]
@shenxingwuying  rebase

**Review by jackwener — COMMENTED** [review]
Please `git rebase` the doris latest master to fix the conflict

**Comment by morningman** [comment]
The README has been changed. close this PR.
Thank you for your contribution @shenxingwuying

**Pull request closed without merging**
