### PR TITLE
[fix](array-type) fix the wrong result of array_join function

### PR DESCRIPTION
**Pull request by carlvinhust2012**
# Proposed changes
1. this pr is used to  fix the wrong result of array_join function.
2. before the change, the array_join function will return wrong result.
MySQL [example_db]> select array_join(["", "1", "2"], '_');
+--------------------------------------+
| array_join(ARRAY('', '1', '2'), '_')              |
+--------------------------------------+
| 1_2                                                            |
+--------------------------------------+
3.after the change, the array_join function will return correct result.
MySQL [example_db]> select array_join(["", "1", "2"], '_');
+--------------------------------------+
| array_join(ARRAY('', '1', '2'), '_')              |
+--------------------------------------+
| _1_2                                                           |
+--------------------------------------+

Issue Number: #7570

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
5. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
6. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
7. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
8. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 39.75 seconds
 load time: 585 seconds
 storage size: 17154768640 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020053809_clickbench_pr_31556.html

**Comment by carlvinhust2012** [comment]
> TeamCity pipeline, clickbench performance test result: the sum of best hot time: 39.75 seconds load time: 585 seconds storage size: 17154768640 Bytes https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020053809_clickbench_pr_31556.html

so what's wrong about this pr?

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.07 seconds
 load time: 565 seconds
 storage size: 17154602798 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221021002000_clickbench_pr_32081.html

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
