### PR TITLE
[enhancement](regression) use sf0.1 data in datev2 and decimalv3 cases

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes

Issue Number: close #xxx
Previously inside datev2 and decimalv3 we use one 1GB size data, now we can replace these cases with smaller size data to verify if the implementation of corresponding type is correct or not.
## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by ByteYue** [comment]
It seems that the teamcity has skipped P1 regression tests, i'll run the related cases on my own environment and paste the cases result in future comment. **Plz Don't Merge** until the result has been published.

**Comment by ByteYue** [comment]
I've tested the related cases on my own environment.
image

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
