### PR TITLE
[FIX](struct)improve struct literal and fix array() with struct creator

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
1. change struct literal from {1, 2, 3} ->  (1, 2, 3) 
2. fix array() with struct creator eg. named_struct() and struct()

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
some thing need to fix in regression test

**Comment by amorynan** [comment]
not support in parser so close!

**Pull request closed without merging**
