### PR TITLE
[Fix](BrokerLoad) fix broker load error when import mulitiple BrokerFileGroup

### LINKED ISSUE #22429: [Bug] (broker load) mulitiple BrokerFileGroupAggInfo will report error when enable_new_load_scan_node  and enable_vectorized_load is enable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master and 1.2 

### What's Wrong?

1.2  的broker load 当出现多个file group写 一个表的时候，会出现 report error status: [INTERNAL_ERROR]Unknown source slot descriptor, slot_id=xxx to coordinator的错误。
```
load label demo
 (DATA INFILE('hdfs://xxx/xxx/path1/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4), 
 DATA INFILE('hdfs://xxx/xxx/path2/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4), 
 DATA INFILE('hdfs://xxx/xxx/path3/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4)
 ,
 ) WITH BROKER hdfs_broker();
```
### What You Expected?

not report error

### How to Reproduce?
```
load label demo
 (DATA INFILE('hdfs://xxx/xxx/path1/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4), 
 DATA INFILE('hdfs://xxx/xxx/path2/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4), 
 DATA INFILE('hdfs://xxx/xxx/path3/*')
 INTO TABLE test
 PARTITION (p2023)
 FORMAT AS 'orc'
 (col1, col2, col3, col4) set (col1=col1, col2=col2, col3=col3, col4=col4)
 ,
 ) WITH BROKER hdfs_broker();
```
### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #22429

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 43.06 seconds
 stream load tsv:          547 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.9 seconds inserted 10000000 Rows, about 334K ops/s
 storage size: 17162579232 Bytes

**Comment by BePPPower** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.87 seconds
 stream load tsv:          512 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162248411 Bytes

**Comment by BePPPower** [comment]
run buildall

**Pull request closed without merging**
