### PR TITLE
[enhancement](repository) support alter s3 repo info about ak/sk/token

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

in some cases:
1. s3.session_token/AWS_TOKEN will be expired after hours, and may be upload snapshot job will failed if data is big large;
2. as same reason, repo will be expired too when RepositoryMgr exec repo ping

so it need support alter s3 repo properties about ak/sk/token and update upload snapshot job properties to continue backup.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run er

**Comment by nextdreamblue** [comment]
run External Regression

**Comment by nextdreamblue** [comment]
run External

**Comment by nextdreamblue** [comment]
run external

**Comment by nextdreamblue** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
