### PR TITLE
[bugfix]Clean the version.sh file before build, otherwise the version informa…

### PR DESCRIPTION
**Pull request by hello-stephen**
## Problem Summary:

During the testing process, it was found that the recompiled version information of the be was not updated, which made it easy to make mistakes when comparing the version performance during the development and testing process.

It has been modified simply, and there may be a better way to modify it.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

**Comment by cambyzju** [comment]
If you want to release the version, you could run 'sh build.sh --clean' at first, then run 'sh build.sh' to compile and release the version.

Most of the time, we test and debug frequently, I personally do not think it is necessary to update the version.

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
> If you want to release the version, you could run 'sh build.sh --clean' at first, then run 'sh build.sh' to compile and release the version.
> 
> Most of the time, we test and debug frequently, I personally do not think it is necessary to update the version.

We all agree that the new commit information needs to be packed into the newly compiled package in time. FE is included, but BE is not. In the way of --clean All files will be recompiled, while only 3 files will be recompiled by deleting version.h, which is much faster.

**Comment by cambyzju** [comment]
> > If you want to release the version, you could run 'sh build.sh --clean' at first, then run 'sh build.sh' to compile and release the version.
> > Most of the time, we test and debug frequently, I personally do not think it is necessary to update the version.
> 
> We all agree that the new commit information needs to be packed into the newly compiled package in time. FE is included, but BE is not. In the way of --clean All files will be recompiled, while only 3 files will be recompiled by deleting version.h, which is much faster.

If it is really needed, Does call 'gensrc/script/gen_build_version.sh' better than remove files?

for example:
if [ ${BUILD_BE} -eq 1 ] ; then
    ${DORIS_HOME}/gensrc/script/gen_build_version.sh --be
    ...
fi

**Pull request merged**
