### PR TITLE
[Bug](materialized-view) fix analyze where clause failed on mv

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
fix analyze where clause failed on mv
do not analyze slot after replaceSlot to avoid duplicate columns in desc

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by starocean999** [comment]
please add more description about this pr, such as what's the real problem and how to solve it.

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
