### PR TITLE
[Refactor](opentelemetry) Remove opentelemetry 

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Aim to remove useless thirdparty opentelemetry both from FE and BE
1. Remove  codes from FE&BE
2. Remove opentelemetry from thirdparty scripts
3. Remove opentelemetry from pom.xml

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]

**Pull request merged**
