### PR TITLE
[fix](es) ClassCastException when getting root schema

### PR DESCRIPTION
**Pull request by gnehil**
# Proposed changes

Issue Number: close #xxx

## Problem summary

When the dynamic parameter in the mapping and mapping type is set to null, getting the root schema will cause ClassCastException

example:
```json
{
  "test_index": {
    "mappings": {
      "dynamic": "false",
      "properties": {
        "time": {
          "type": "long"
        },
        "type": {
          "type": "keyword"
        },
        "userId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}
```

When the mapping structure is as above

The exception that occurs in the latest version is `java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode`,
and for elder version is `java.lang.ClassCastException: java.lang.String cannot be cast to org.json.simple.JSONObject`

Describe your changes.

## Checklist(Required)

* [x] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by stalary** [comment]
It can resolve this problem in this pr https://github.com/apache/doris/pull/18382

**Comment by gnehil** [comment]
I think we are not having the same problem.
The problem I have encountered is that when calling the `getRootSchema` method, when the `mappingType` is null and there is `dynamic` parameter in the mapping json, since the first element obtained by traversing the mapping json through the iterator is `dynamic`, and its type is `TextNode`, a `ClassCastException` will appear when running the following code：
```java
ObjectNode firstData = (ObjectNode) mappings.get(firstType);
```
All this happens before calling the `replaceFieldAlias` method.

**Comment by stalary** [comment]
> I think we are not having the same problem. The problem I have encountered is that when calling the `getRootSchema` method, when the `mappingType` is null and there is `dynamic` parameter in the mapping json, since the first element obtained by traversing the mapping json through the iterator is `dynamic`, and its type is `TextNode`, a `ClassCastException` will appear when running the following code：
> 
> ```java
> ObjectNode firstData = (ObjectNode) mappings.get(firstType);
> ```
> 
> All this happens before calling the `replaceFieldAlias` method.

Okey, I get it.

**Comment by stalary** [comment]
run buildall

**Review by stalary — APPROVED** [review]
LGTM

**Pull request merged**
