### PR TITLE
[fix](invert index) add the reader buffer as a parameter

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. The inverted index read buffer is configurable

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
