### PR TITLE
[docs](docs)Update spark_load.md

### PR DESCRIPTION
**Pull request by httpshirley**
## Proposed changes

Issue Number: close #xxx

https://doris.apache.org/zh-CN/community/design/spark_load/
https://doris.apache.org/zh-CN/community/developer-guide/regression-testing/#explain-action

<add en version to the docs>

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
