### PR TITLE
[fix](IO) Fix async close's raii and lazily load jni's jvm max heap value

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by platoneko — COMMENTED** [review]
`FileWriterState FileWriter::closed()` => `FileWriterState FileWriter::state()`
`FileWriter::_close_state` => `FileWriter::_state` 
`FileWriterState::OPEN` => `FileWriterState::OPENED`

**Comment by ByteYue** [comment]
run buildall

**Review by platoneko — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
