### PR TITLE
[chore](ut) unit test for column nullable serialization

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Unit test for column nullable serialization.
Including:
* column_nullable_column_vector
* column_nullable_column_vector_all_null
* column_nullable_column_vector_all_not_null
* column_nullable_column_string
* column_nullable_column_string_all_null
* column_nullable_column_string_all_not_null
* column_nullable_column_decimal
* column_nullable_column_decimal_all_null
* column_nullable_column_decimal_all_not_null
* multiple_columns
* multiple_columns_all_null
* multiple_columns_all_not_null

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
