### PR TITLE
[fix](jdbc catalog) fix type conversion error in MySQL JDBC Driver 5.x

### LINKED ISSUE #31868: [Bug] (JDBC) Error while querying JDBC catalog
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Creating a JDBC catalog for querying mysql，and I got err msg bellow:
`ERROR 1105 (HY000): errCode = 2, detailMessage = (11.91.162.209)[INTERNAL_ERROR]UdfRuntimeException: jdbc get block address:
CAUSED BY: SQLException: Conversion not supported for type java.lang.Byte`

mysql table:
`CREATE TABLE mysql_test_tbl (
  c_tinyint tinyint(4) DEFAULT NULL,
  c_smallint smallint(6) DEFAULT NULL,
  c_int int(11) DEFAULT NULL,
  c_bigint bigint(20) DEFAULT NULL,
  c_float float DEFAULT NULL,
  c_double double DEFAULT NULL,
  c_decimal decimal(10,0) DEFAULT NULL,
  c_char char(1) DEFAULT NULL,
  c_varchar varchar(64) DEFAULT NULL,
  c_text text,
  c_date date DEFAULT NULL,
  c_datetime datetime DEFAULT NULL,
  c_timestamp timestamp NULL DEFAULT NULL
) ENGINE=InnoDB` 

### What You Expected?

query succeed

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #31868

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by FreeOnePlus** [comment]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
