### PR TITLE
[Bug] Fix bug that tablet report always out of date

### LINKED ISSUE #4689: The thirdparty repository url is broken.
When I execute the command "./download-thirdparty.sh", the bash reported the errors:

===== Downloading thirdparty archives...
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/yiming/Squirrel/incubator-doris/thirdparty/src
--2020-09-29 17:16:37--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.44, 220.181.33.43, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 17:16:38 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/yiming/Squirrel/incubator-doris/thirdparty/src
--2020-09-29 17:16:38--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 220.181.33.44, 220.181.33.43, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 17:16:38 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/yiming/Squirrel/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

If I check the url in the web browser, it reported the massages:
{"code":"AccountOverdue","message":"Your request is denied because there is an overdue bill of your account.","requestId":"34341815-75e4-48b3-81ac-f4fe233d58aa"}

### LINKED ISSUE #4691: libevent 下载失败 403错误
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/cooper/Documents/git_codes/incubator-doris/thirdparty/src
--2020-09-29 22:44:19--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 202.106.5.21, 111.206.47.194, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|202.106.5.21|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 22:44:20 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/cooper/Documents/git_codes/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7 
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/cooper/Documents/git_codes/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Downloading libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip from https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip to /home/cooper/Documents/git_codes/incubator-doris/thirdparty/src
--2020-09-29 22:44:20--  https://doris-incubating-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Resolving doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)... 202.106.5.21, 111.206.47.194, 2409:8c00:6c21:10ad:0:ff:b00e:67d
Connecting to doris-incubating-repo.bj.bcebos.com (doris-incubating-repo.bj.bcebos.com)|202.106.5.21|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-29 22:44:20 ERROR 403: Forbidden.

Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip. attemp: 1
/home/cooper/Documents/git_codes/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip md5sum check failed!
except-md5 e8b9ba50270ba3b520aec8ff1089f9d7 
actual-md5 d41d8cd98f00b204e9800998ecf8427e  /home/cooper/Documents/git_codes/incubator-doris/thirdparty/src/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Archive libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip will be removed and download again.
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip
Failed to download libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip

### LINKED ISSUE #4694: [Bug] Tablet report from BE alway be out of date
**Describe the bug**
See a lot logs in fe.log:

```
out of date report version 16014061960000 from backend[10005]. current report version[16014061960129]
```

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

This is because the report version is not set correctly in the tablet report request.

Also modify the download url of libevent Fix #4689 Fix #4691 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have create an issue on (Fix #4694 ), and have described the bug/feature there in detail

### CODE REVIEW

**Review by yangzhg — DISMISSED** [review]
+1

**Review by yangzhg — APPROVED** [review]
+1

**Comment by Semon120** [comment]
@morningman Hello,I have download the libevent from this url:https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip.But when I run build.sh,it seems when compile this 'be/src/http/ev_http_server.cpp' file,it occurs an error: "../src/http/ev_http/ev_http_server.cpp:252:69: error: 'evhttp_request_set_on_free_cb' was not decalred in this scope".It seems like that  libevent do not have definition of  function 'evhttp_request_set_on_free_cb'.Then I read the source code of libevent,and I do not find this function definition in file 'event2/http.h'.So ,did I get wrong version of libevent(but I did download from that url above)?My Doris version is 0.13.15-release. Do you have any idea?Thanks.

**Comment by Semon120** [comment]
> @morningman Hello,I have download the libevent from this url:https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip.But when I run build.sh,it seems when compile this 'be/src/http/ev_http_server.cpp' file,it occurs an error: "../src/http/ev_http/ev_http_server.cpp:252:69: error: 'evhttp_request_set_on_free_cb' was not decalred in this scope".It seems like that libevent do not have definition of function 'evhttp_request_set_on_free_cb'.Then I read the source code of libevent,and I do not find this function definition in file 'event2/http.h'.So ,did I get wrong version of libevent(but I did download from that url above)?My Doris version is 0.13.15-release. Do you have any idea?Thanks.

It seems that evhttp free callback was added
 in this https://github.com/libevent/libevent/commit/63a61932f5906929fc83370725c83f4ea4c6e7e4 commit. But it was not merge to master.So,please make sure this source https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip contain this commit.

**Comment by morningman** [comment]
> > @morningman Hello,I have download the libevent from this url:https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip.But when I run build.sh,it seems when compile this 'be/src/http/ev_http_server.cpp' file,it occurs an error: "../src/http/ev_http/ev_http_server.cpp:252:69: error: 'evhttp_request_set_on_free_cb' was not decalred in this scope".It seems like that libevent do not have definition of function 'evhttp_request_set_on_free_cb'.Then I read the source code of libevent,and I do not find this function definition in file 'event2/http.h'.So ,did I get wrong version of libevent(but I did download from that url above)?My Doris version is 0.13.15-release. Do you have any idea?Thanks.
> 
> It seems that evhttp free callback was added
> in this [libevent/libevent@63a6193](https://github.com/libevent/libevent/commit/63a61932f5906929fc83370725c83f4ea4c6e7e4) commit. But it was not merge to master.So,please make sure this source https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip contain this commit.

We had a patch here: `thirdparty/patches/libevent_on_free_cb.patch`
When you run `sh build-thirdparty.sh`, this patch should be applied automatically.

**Comment by Semon120** [comment]
> > > @morningman Hello,I have download the libevent from this url:https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip.But when I run build.sh,it seems when compile this 'be/src/http/ev_http_server.cpp' file,it occurs an error: "../src/http/ev_http/ev_http_server.cpp:252:69: error: 'evhttp_request_set_on_free_cb' was not decalred in this scope".It seems like that libevent do not have definition of function 'evhttp_request_set_on_free_cb'.Then I read the source code of libevent,and I do not find this function definition in file 'event2/http.h'.So ,did I get wrong version of libevent(but I did download from that url above)?My Doris version is 0.13.15-release. Do you have any idea?Thanks.
> > 
> > 
> > It seems that evhttp free callback was added
> > in this [libevent/libevent@63a6193](https://github.com/libevent/libevent/commit/63a61932f5906929fc83370725c83f4ea4c6e7e4) commit. But it was not merge to master.So,please make sure this source https://doris-thirdparty-repo.bj.bcebos.com/thirdparty/libevent-20180622-24236aed01798303745470e6c498bf606e88724a.zip contain this commit.
> 
> We had a patch here: `thirdparty/patches/libevent_on_free_cb.patch`
> When you run `sh build-thirdparty.sh`, this patch should be applied automatically.

Oh!!!Thanks!

**Pull request merged**
