### PR TITLE
[optimize](planner)remove redundant conjuncts on plan node

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

This PR try to remove redundant conjuncts on plan node when generate Single Node Plan

## Problem Summary:

Currently, Doris cannot remove redundant expression on anywhere. We can reproduce follow these SQL:
```sql
-- create table
CREATE TABLE `t1` (
  `k1` int(11) NULL COMMENT "",
  `v1` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `v1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
)

-- query
explain select v1 from t1 where k1 = 1 and k1 = 1;
```

current plan like this:
```
+-----------------------------------------------------------------+
| Explain String                                                  |
+-----------------------------------------------------------------+
| PLAN FRAGMENT 0                                                 |
|  OUTPUT EXPRS:`v1`                                              |
|   PARTITION: HASH_PARTITIONED: `default_cluster:test`.`t1`.`k1` |
|                                                                 |
|   VRESULT SINK                                                  |
|                                                                 |
|   0:VOlapScanNode                                               |
|      TABLE: t1                                                  |
|      PREAGGREGATION: OFF. Reason: No AggregateInfo              |
|      PREDICATES: `k1` = 1, `k1` = 1                             |
|      partitions=0/1                                             |
|      rollup: null                                               |
|      tabletRatio=0/0                                            |
|      tabletList=                                                |
|      cardinality=0                                              |
|      avgRowSize=8.0                                             |
|      numNodes=1                                                 |
+-----------------------------------------------------------------+
```

after this PR, the plan is like this:
```
+-----------------------------------------------------------------+
| Explain String                                                  |
+-----------------------------------------------------------------+
| PLAN FRAGMENT 0                                                 |
|  OUTPUT EXPRS:`v1`                                              |
|   PARTITION: HASH_PARTITIONED: `default_cluster:test`.`t1`.`k1` |
|                                                                 |
|   VRESULT SINK                                                  |
|                                                                 |
|   0:VOlapScanNode                                               |
|      TABLE: t1                                                  |
|      PREAGGREGATION: OFF. Reason: No AggregateInfo              |
|      PREDICATES: `k1` = 1                                       |
|      partitions=0/1                                             |
|      rollup: null                                               |
|      tabletRatio=0/0                                            |
|      tabletList=                                                |
|      cardinality=0                                              |
|      avgRowSize=8.0                                             |
|      numNodes=1                                                 |
+-----------------------------------------------------------------+
```

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

Let's see could this PR broken any UT or regression test.
If no UT and  regression test be broken, i will add UT later.

### CODE REVIEW

**Review by dataroaring — COMMENTED** [review]
Could you add a case under regression_test/suites?

**Comment by morrySnow** [comment]
> Could you add a case under regression_test/suites?

done

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Comment by wangshuo128** [comment]
Why add a regression test? I think a unit test in FE could cover this case.

**Comment by morrySnow** [comment]
> Why add a regression test? I think a unit test in FE could cover this case.

some redundant conjuncts introduced by ExtractCommonFactorsRule, and we want to ensure this situation could be covered

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
