### PR TITLE
[Bug] fix use-after-poison bug in ut schema_change_test 

### PR DESCRIPTION
**Pull request by vagetablechicken**
Ref issue https://github.com/apache/incubator-doris/issues/4116
Using slice->data to create HyperLogLog, it will exec `HyperLogLog(Slice(const char*))`. Then `Slice(const char*)` will use `strlen(data)` to calc the size. But the slice in this ut isn't a C-string. Need to use `Slice`.

### CODE REVIEW

**Comment by chaoyli** [comment]
You can simplify the commit message to easy understand.

**Review by chaoyli — APPROVED** [review]

**Comment by vagetablechicken** [comment]
> You can simplify the commit message to easy understand.

How about this commit message?

**Comment by chaoyli** [comment]
> > You can simplify the commit message to easy understand.
> 
> How about this commit message?

You should make another to know what the commit's addressing problem and the solution.

**Comment by vagetablechicken** [comment]
> > > You can simplify the commit message to easy understand.
> > 
> > 
> > How about this commit message?
> 
> You should make another to know what the commit's addressing problem and the solution.

done

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
