### PR TITLE
[improve](restore) Release useless info for the finished job to reduce mem usage

### PR DESCRIPTION
**Pull request by w41ter**
## Proposed changes

Issue Number: close #xxx

The info about snapshot files is not visible in the result of `SHOW RESTORE`, but it costs a lot of memory.

image

Here is an example of a restore job about a large table, the main memory usage is in :

- jobInfo
  - backupOlapTableObjects
  - tabletBeMap
  - tabletSnapshotPathMap
- fileMapping
  - mapping
  - overwriteMap
  
This PR clear these fields when task is finished/cancelled, to reduce the memory usage.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]

**Comment by w41ter** [comment]
run buildall

**Comment by gavinchou** [comment]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
