### PR TITLE
[Enchancement](statistics) Show histogram statistics, show specified column statistics

### PR DESCRIPTION
**Pull request by weizhengte**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by weizhengte** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.07 seconds
 stream load tsv:          431 seconds loaded 74807831229 Bytes, about 165 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230413195754_clickbench_pr_128807.html

**Review by Kikyou1997 — CHANGES_REQUESTED** [review]
Add regression tests plz

**Comment by weizhengte** [comment]
> pull_request_target

Sure, later there will be a p0 of pr perfecting these statistics, which is based on the statistics specification document

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
