### PR TITLE
[Bug](ColumnArray) Fix array column replicate `replicate_offsets` not matched

### LINKED ISSUE #17618: [Bug] Fix array column replicate replicate_offsets not matched
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk1/yuejing/projects/doris/be/src/common/signal_handler.h:413
1# 0x00007F9D65DA9400 in /lib64/libc.so.6
2# __GI_raise in /lib64/libc.so.6
3# __GI_abort in /lib64/libc.so.6
4# 0x000055E99D0637A9 in /mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be
5# google::LogMessage::SendToLog() in /mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be
6# google::LogMessage::Flush() in /mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be
7# google::LogMessageFatal::~LogMessageFatal() in /mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be
8# doris::vectorized::ColumnArray::replicate_generic(doris::vectorized::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const in /mnt/disk1/yu
ejing/projects/doris/output/be/lib/doris_be
9# doris::vectorized::ColumnArray::replicate(doris::vectorized::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const in /mnt/disk1/yuejing/pr
ojects/doris/output/be/lib/doris_be
10# doris::vectorized::ColumnArray::replicate_nullable(doris::vectorized::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const at /mnt/disk1/y
uejing/projects/doris/be/src/vec/columns/column_array.cpp:966
11# doris::vectorized::ColumnArray::replicate(doris::vectorized::PODArray<unsigned int, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const at /mnt/disk1/yuejing/pr
ojects/doris/be/src/vec/columns/column_array.cpp:743
12# doris::vectorized::ColumnArray::replicate(unsigned int const*, unsigned long, doris::vectorized::IColumn&, unsigned long, int) const at /mnt/disk1/yuejing/projects/dor
is/be/src/vec/columns/column_array.cpp:767
13# doris::vectorized::ColumnNullable::replicate(unsigned int const*, unsigned long, doris::vectorized::IColumn&, unsigned long, int) const at /mnt/disk1/yuejing/projects/
doris/be/src/vec/columns/column_nullable.cpp:544
14# doris::vectorized::ProcessHashTableProbe<3>::probe_side_output_column(std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::alloca
tor<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, std::vector<bool, std::allocator<bool> > const&, int, int, unsigned long, bool, bool) at
/mnt/disk1/yuejing/projects/doris/be/src/vec/exec/join/process_hash_table_probe_impl.h:139
15# doris::Status doris::vectorized::ProcessHashTableProbe<3>::do_process<true, true, doris::vectorized::FixedKeyHashTableContext<unsigned long, true, doris::vectorized::R
owRefListWithFlag> >(doris::vectorized::FixedKeyHashTableContext<unsigned long, true, doris::vectorized::RowRefListWithFlag>&, doris::vectorized::PODArray<unsigned char, 4
096ul, Allocator<false, false>, 15ul, 16ul> const*, doris::vectorized::MutableBlock&, doris::vectorized::Block*, unsigned long, bool) at /mnt/disk1/yuejing/projects/doris/
be/src/vec/exec/join/process_hash_table_probe_impl.h:395
16# auto doris::vectorized::HashJoinNode::pull(doris::RuntimeState*, doris::vectorized::Block*, bool*)::$_1::operator()<doris::vectorized::FixedKeyHashTableContext<unsigne
d long, true, doris::vectorized::RowRefListWithFlag>&, doris::vectorized::ProcessHashTableProbe<3>&, std::integral_constant<bool, true>, std::integral_constant<bool, true>

### What You Expected?

no core

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eldenmoon**
# Proposed changes

Issue Number: close #17618

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run p0

**Comment by eldenmoon** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
