### PR TITLE
[bugfix](hive)Fix cache inconsistency issue

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

1. Concurrency issues:
a. One thread is performing a refresh catalog action.
b. One thread is performing an insert table action, and after completion, it executes a refresh table action.

The `partitionCache` will be refreshed only if the corresponding table exists in the `partitionValuesCache`. However, the `partitionValuesCache` may have been refreshed by the `refresh catalog`, resulting in the inability to find the corresponding table through the `partitionValuesCache`, resulting in the `partitionCache` not being refreshed.
Similarly, the `fileCacheRef` may not be refreshed either.
Therefore, directly search for all keys to match to prevent them from being refreshed.

2. No need to perform refreshAfterWriteSec operation on partitionCache.
3. Increase the thread pool size.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
Please add FE UT for `invalidateTableCache()`

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by suxiaogang223 — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
