### PR TITLE
[docs]Created commit-format-specification.md

### PR DESCRIPTION
**Pull request by luzhijing**
## Proposed changes

We found that many commit messages submitted at present have ambiguous information. Clear commit messages can help developers submit pull requests more readable, committers merge easilerly and Release Manager easy to release. Therefore, we have sorted out a version of the commit format specification. We hope that subsequent contributors can sort out the commit messages according to the specification when submitting Pull Request.

我们发现当前提交的很多Commit Message存在信息模糊的情况，清晰的Commit Message可以帮助开发者提交的Pull Request更加易读，便于Committer合入，也便于Release Manager进行发版。因此我们整理了一版Commit格式规范，希望后续Contributor在提交PR时可以按照规范整理Commit Message。

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Missing english doc

**Comment by luzhijing** [comment]
> Missing english doc

Thank you!  I have already updated it

**Review by morningman — COMMENTED** [review]
Add sidebar

**Review by morningman — DISMISSED** [review]
LGTM

**Pull request closed without merging**
