### PR TITLE
[enhancement](schema-change) Support light schema change on hash columns and agg key columns with varchar type to change length

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

1. Schema change should rebuild distribution info after modifying columns, especially distribution columns. Or it may cause dynamic partition failed when checking distribution columns' equality.
2. Support hash key columns to do light schema change. For unique key or dup key columns, could not be enabled temporarily due to some historical reasons. See #39798 .

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run cloud_p0

**Comment by TangSiyang2001** [comment]
run cloud_p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run cloud_p1

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please  add case for fer restarting.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
