### PR TITLE
[Feature](inverted index) add unicode parser for inverted index

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

support unicode parser like this

```
CREATE TABLE `nginx_log` ( 
 `id` varchar(18) NULL, 
 `addr` text NULL,                                                                                                                                                         
 INDEX idx_id (`id`) USING INVERTED PROPERTIES("parser" = "unicode") COMMENT '', 
 INDEX idx_addr (`addr`) USING INVERTED PROPERTIES("parser" = "unicode") COMMENT ''   
 ) ENGINE=OLAP                                                                                                                                                            
 DUPLICATE KEY(`id`)                                                                                                                                                       
COMMENT 'OLAP'                                                                                                                                                            
DISTRIBUTED BY HASH(`id`) BUCKETS 2                                                                                                                                       PROPERTIES (                                                                                                                                                              "replication_allocation" = "tag.location.default: 1",                                                                                                                     "storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
); 
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xiaokang — DISMISSED** [review]
docs also need to be changed

**Comment by zzzxl1993** [comment]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run p0

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
