### PR TITLE
[Feature](column) do not change column nullable on ColumnDef

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
do not change column nullable on ColumnDef

1. bitmap/hll/quantile_state will directly change nullable to false
    1. Currently, complex types do not support nullable in the storage layer. If it is set to null, it should be coredump.
    2. It is meaningless to set complex types to null. For example, bitmap can use bitmap_empty to represent null to avoid     nullable overhead.
    3. Users reported that if it is a not null bitmap. When inserting into, it is necessary to explicitly declare bitmap_empty, which is troublesome. However, the work of supporting the default value of bitmap_empty for complex columns has been claimed by the community. https://github.com/apache/doris/issues/34228
    4. Consider changing it here so that if null is explicitly specified when creating a table, an error will be reported. If it is not explicitly specified (the default will be null), it is not null.
2. The aggregate type REPLACE_IF_NOT_NULL will directly change nullable to true
    1. If it is a not null column, using REPLACE_IF_NOT_NULL is meaningless, which is equivalent to REPLACE.
    2. Consider changing it here so that if not nullable is encountered, an error will be reported, and a prompt to use REPLACE will be given.

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
