### PR TITLE
[doc](grant) add the grant command to general user executes fresh catalog

### PR DESCRIPTION
**Pull request by smallhibiscus**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by hf200012** [comment]
rebuild all

**Comment by smallhibiscus** [comment]
rebuild all

**Comment by hf200012** [comment]
rebuild all

**Comment by hf200012** [comment]
run buildall

**Comment by smallhibiscus** [comment]
rebuild all

**Pull request closed without merging**
