### PR TITLE
[feature-wip](resource-group) Support resource group tvf

### LINKED ISSUE #18527: [Feature](table-valued-function) Add resource_groups table-valued-function
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

implement a new Metadata TVF called resource_groups. 
The use of resource_groups TVF like:

mysql> select * from resource_groups();
+-------+--------------+-----------+-------+
| Id          | Name              | Item            | Value  |
+-------+--------------+-----------+-------+
| 10076   | group_name  | cpu_share  |     1      |
| 10077   | group_test     | cpu_share  |    10     |
+-------+--------------+-----------+-------+

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yongjinhou**
# Proposed changes

Issue Number: close #18527

related: #18098

## Problem summary

 Implement a new Metadata TVF called resource_groups().

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
Under modification.

**Comment by yongjinhou** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
1. missing sidebar
2. need to add regression test

**Comment by yongjinhou** [comment]
> [ ](/yongjinhou)

done

**Comment by yongjinhou** [comment]
> 1. missing sidebar
> 2. need to add regression test

done

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.29 seconds
 stream load tsv:          432 seconds loaded 74807831229 Bytes, about 165 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230410131910_clickbench_pr_127017.html

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run compile

**Comment by yongjinhou** [comment]
run feut

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run p1

**Comment by luozenglin** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
