### PR TITLE
[refactor](nereids) update Agg stats derive method

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
This pr has no effect on tpch queries.
Some tpcds queries are impacted.  
They are 4/11/23/24/47/51/57/65/74

image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by Kikyou1997 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
