### PR TITLE
[Feature](Variant) support variant load

### PR DESCRIPTION
**Pull request by eldenmoon**
## Proposed changes

This PR is the load part of variant column

related #26225

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
this pr is a clone of #24554 , which is reviewed but github workflow does not work.

**Pull request merged**
