### PR TITLE
[Feature] support ks3 storage in doris

### PR DESCRIPTION
**Pull request by xuzifu666**
## Proposed changes

Close related #issue (replace it with issue number if it exists).

Describe the overview of changes, and introduce why we need it.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
what is kmr?

**Comment by xuzifu666** [comment]
> what is kmr?



> 
kmr is emr cloud of xiaomi，https://www.ksyun.com/， like emr of tencent cloud or aliyun.

**Comment by morningman** [comment]
OK, i got it, thanks for your contribution.

And besides, if it is convenient, could you help us to test the compatibility of using AWS S3 sdk to access ksyun's Object Storage?

Doris currently has aws s3 sdk built in and can access s3 compatible object storage directly without "Broker".

We have tested Baidu, Ali and AWS object storage. You can see how to use it here: 
```
http://palo.baidu.com/docs/%E6%93%8D%E4%BD%9C%E6%89%8B%E5%86%8C/%E4%BD%BF%E7%94%A8S3-SDK%E8%AE%BF%E9%97%AE%E5%AF%B9% E8%B1%A1%E5%AD%98%E5%82%A8
```

and try to access ksyun's object storage by this way.
All you need to do is to get the `ak, sk, region, endpoint` of your ksyun's buckets and run a load job.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
