### PR TITLE
[refactor](nereids)remove old analyzer in OlapTableSink

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
add unit test please

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by starocean999** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Pull request merged**
