### PR TITLE
[Fix](Csv-Reader)Fix the issue of BE core dump caused by improper configuration of column_seperator and line_delimiter.

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

**Steps to reproduce:**
Set column `column_seperator` = "AA" and line_delimiter = "AAB" 。

**Explanation:**
When splitting into lines, the `line_delimiter` should be discarded and not considered as part of the data for that line. Otherwise, when splitting columns, the `line_delimiter` will also be included in the splitting process, resulting in incorrect values.
At this point, in `PlainCsvTextFieldSplitter::_split_field_single_char`, `line.size` is smaller than `value_start`, resulting in line.size - value_start < 0, causing the unsigned number to become very large, which leads to a core dump when printing `_split_values` in `append_error_msg_to_file()` method.

**Core stack:**
```
*** SIGABRT unknown detail explain (@0x3ed000af23e) received by PID 717374 (TID 724661 OR 0x7fd500495700) from PID 717374; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/common/signal_handler.h:421
 1# 0x00007FD9639CF400 in /lib64/libc.so.6
 2# raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# __gnu_cxx::__verbose_terminate_handler() [clone .cold] at ../../../../libstdc++-v3/libsupc++/vterminate.cc:75
 5# __cxxabiv1::__terminate(void (*)()) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
 6# 0x0000562847E67FE1 in /mnt/datadisk1/fangtiewei/projects/doris/output/be/lib/doris_be
 7# 0x0000562847E68134 in /mnt/datadisk1/fangtiewei/projects/doris/output/be/lib/doris_be
 8# std::__throw_length_error(char const*) at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:82
 9# std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (), doris::vectorized::CsvReader::_line_split_to_values(doris::Slice const&, bool*)::$_1>::_M_invoke(std::_Any_data const&) at /mnt/datadisk1/fangtiewei/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
10# doris::RuntimeState::append_error_msg_to_file(std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, bool*, bool) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/runtime/runtime_state.cpp:477
11# doris::vectorized::CsvReader::_line_split_to_values(doris::Slice const&, bool*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/format/csv/csv_reader.cpp:694
12# doris::vectorized::CsvReader::_fill_dest_columns(doris::Slice const&, doris::vectorized::Block*, std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, unsigned long*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/format/csv/csv_reader.cpp:607
13# doris::vectorized::CsvReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/format/csv/csv_reader.cpp:525
14# doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/scan/vfile_scanner.cpp:333
15# doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) in /mnt/datadisk1/fangtiewei/projects/doris/output/be/lib/doris_be
16# doris::vectorized::VScanner::get_block_after_projects(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/scan/vscanner.cpp:100
17# doris::vectorized::ScannerScheduler::_scanner_scan(std::shared_ptr<doris::vectorized::ScannerContext>, std::shared_ptr<doris::vectorized::ScanTask>) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/vec/exec/scan/scanner_scheduler.cpp:267
18# std::_Function_handler<void (), doris::vectorized::ScannerScheduler::submit(std::shared_ptr<doris::vectorized::ScannerContext>, std::shared_ptr<doris::vectorized::ScanTask>)::$_3>::_M_invoke(std::_Any_data const&) at /mnt/datadisk1/fangtiewei/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
19# doris::ThreadPool::dispatch_thread() in /mnt/datadisk1/fangtiewei/projects/doris/output/be/lib/doris_be
20# doris::Thread::supervise_thread(void*) at /mnt/datadisk1/fangtiewei/projects/doris/be/src/util/thread.cpp:499
21# start_thread in /lib64/libpthread.so.0
22# __clone in /lib64/libc.so.6
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
