### PR TITLE
[fix](function) Array_map compared offset rows one by one

### LINKED ISSUE #18348: [Bug] array_map function should be compared offset rows one by one
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

array_map function it's needs the input array column have same offset, 
so should be compared offset rows one by one

### What You Expected?

running ok

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by herry2038**
# Proposed changes

Issue Number: close #18348

## Problem summary

Array_map 's multi columns compare not only nested data rows to be equal,but also the offsets data must equal each other.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

**Comment by yiguolei** [comment]
regression test test_array_sortby failed.

**Comment by herry2038** [comment]
run buildall

**Comment by herry2038** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
