### PR TITLE
[fix](tablet report) fix not add replicas when a backend re join the cluster after changing its ip or port

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

If a backend wants to change its ip or port,   proceed as follows:
1.  drop this backend force  (`alter system dropp backend old_ip:old_port`);
2.  change this backend's ip in be.conf;
3.  restart this backend;
4.  add this backend back (`alter system add backend new_ip:new_port`).

After adding back,  this backend will report its existing tablets to fe,  but the fe will found the tablet status is force redunant and delete the replicas on this backend.

This PR is to fix the problem above. It will  add the replica back when the tablet is force redunant.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.54 seconds
 stream load tsv:          514 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.6 seconds inserted 10000000 Rows, about 337K ops/s
 storage size: 17162344311 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
what if adding back happens before fe detected the be is gone.

**Comment by yujun777** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.16 seconds
 stream load tsv:          515 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162424216 Bytes

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
