### PR TITLE
[Refactor][Doc]Add part of the document content for Get-Starting

### PR DESCRIPTION
**Pull request by FreeOnePlus**
1. Add the content of the Quick Start document
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hf200012** [comment]
Add English documents

**Comment by FreeOnePlus** [comment]
> 

Okay

**Comment by jackwener** [comment]
For add a new doc, you need to add it into `docs/.vuepress/sidebar/ en.js | zh-CN.js`
Thanks for contribution❤!

**Comment by jackwener** [comment]
I think it's a great job to new learner for doris, Thanks!

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
