### PR TITLE
[chore](dependencies)Remove Unnecessary Dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
**devtools**: This dependency is only needed during local development, so we should set its scope to runtime.
**canal** :  The Spring dependency for Canal is primarily used for Pulsar's Bean replication. Since binlogload does not require any MQ dependencies, we can remove the corresponding Spring jar.  https://github.com/alibaba/canal/blob/master/client/src/main/java/com/alibaba/otter/canal/client/kafka/protocol/KafkaFlatMessage.java
**kafka** :Fe does not directly interact with Kafka; only UT uses Kafka libraries, so its dependency scope should be set to 'test'.

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
