### PR TITLE
[fix](doc)description of of recover_with_skip_missing_version

### PR DESCRIPTION
**Pull request by yz-jayhua**
## Proposed changes

Issue Number: close #xxx

## Further comments

fix zh-CN/docs/admin-manual/config/fe-config.md description of of recover_with_skip_missing_version in the document

### CODE REVIEW

**Review by luzhijing — DISMISSED** [review]
Please rebase code and resolve conflicts.

**Comment by zy-kkk** [comment]
Now we have used to automatically generate FE configuration document, if you want to change, please go to `fe/fe-common/src/main/java/org/apache/doris/common/Config.java`

**Comment by JayITH** [comment]
> Now we have used to automatically generate FE configuration document, if you want to change, please go to `fe/fe-common/src/main/java/org/apache/doris/common/Config.java`

like this:

**Comment by JayITH** [comment]
> Now we have used to automatically generate FE configuration document, if you want to change, please go to `fe/fe-common/src/main/java/org/apache/doris/common/Config.java`

like this:
@ConfField(mutable = true, masterOnly = true, description = {**to fix**}) ?

**Comment by zy-kkk** [comment]
> > Now we have used to automatically generate FE configuration document, if you want to change, please go to `fe/fe-common/src/main/java/org/apache/doris/common/Config.java`
> 
> like this: @ConfField(mutable = true, masterOnly = true, description = {**to fix**}) ?

yes

**Comment by JayITH** [comment]
> > > Now we have used to automatically generate FE configuration document, if you want to change, please go to `fe/fe-common/src/main/java/org/apache/doris/common/Config.java`
> > 
> > 
> > like this: @ConfField(mutable = true, masterOnly = true, description = {**to fix**}) ?
> 
> yes

thanks,I'll try again.

**Pull request closed without merging**
