### PR TITLE
[feat](window_function) support to secondary argument to ignore null values in first_value/last_value

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

For `first_value`:
```sql
select first_value(col3, 1) over (partition by col1 order by col2) from t1 order by col1, col2;
```
The window function `first_value` will return the first non-null value.

For `last_value`
```sql
select last_value(col3, 1) over (partition by col1 order by col2) from t1 order by col1, col2;
```
The window function `last_value` will return the last non-null value.

If the secondary argument is set to false, the behavior remains consistent with the single argument version.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]
LGTM

**Pull request merged**
