### PR TITLE
[Test](regression) Temporarily disable quickTest for SHOW CREATE TABLE to adapt to enable_feature_binlog=true

### PR DESCRIPTION
**Pull request by deadlinefen**
When enable_feature_binlog=true, executing the SHOW CREATE TABLE properties statement will return the following results like:
> PROPERTIES (
  ......
  "binlog.enable" = "false",
  "binlog.ttl_seconds" = "9223372036854775807",
  "binlog.max_bytes" = "9223372036854775807",
  "binlog.max_history_nums" = "9223372036854775807",
  .....
);

When enable_feature_binlog=false, the above properties will not appear, so the state of enable_feature_binlog will interfere with the judgment of SHOW CREATE TABLE statement in regression test.   

As a compromise, temporarily use sql instead of qt_ function containing SHOW CREATE TABLE.   

If this problem is fixed later, this compromise PR will be corrected.

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by JackDrogon — APPROVED** [review]
LGTM

**Pull request merged**
