### PR TITLE
[improvement](scanner_schedule) reduce memory consumption of scanner #24199

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

backport #24199

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
convert it to draft since an bug is reported related to this pr on master.

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
