### PR TITLE
[Branch-2.0](Full compaction) Fix full compaction regressison test (#23487)

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

Cherry pick from master #23487 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Comment by shuke987** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Pull request merged**
