### PR TITLE
[enhancement](show) Move storage policy info from show create table to show partitions

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a case.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run cloud_p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run p0

**Pull request merged**
