### PR TITLE
[BUG] fix partition storage policy info lost

### PR DESCRIPTION
**Pull request by qzsee**
## Proposed changes
1. fix partition storage policy info lost
   When adding a storage policy to a table through an alter statement, the partition policy is lost when the FE is restarted because the storage policy is not set for the partition synchronously.

2. when setting policies, check the uniq table in advance to prevent metadata inconsistencies
    

3. show storage policy using for stmt support any string policy name
     
    If the policy name begins with a number, the statement cannot be parsed.

Issue Number: close #xxx

### CODE REVIEW

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
