### PR TITLE
[Improve](CI)Check PR approve status

### PR DESCRIPTION
**Pull request by CalvinKirs**
After discussion in the doris community @apache/doris-committers , we limit the PR to be merged only after at least two people approve it.↳

We can try to run it for a while first, and if everyone gives good feedback, we can use this as a mandatory check.

Since the merge must be approved by at least one committer, we only need to judge whether there are two approves, and we don't need to care about the identity of the approve.
When there is a request change, if the other party is a committer, the committer dismiss is required when merging, which is enforced by github, so we don't need to care.

### CODE REVIEW

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by caoliang-web — DISMISSED** [review]

**Review by JNSimba — DISMISSED** [review]

**Review by caoliang-web — COMMENTED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]

**Review by JNSimba — CHANGES_REQUESTED** [review]
just for test

**Review by irenesrl — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — CHANGES_REQUESTED** [review]
test

**Review by irenesrl — CHANGES_REQUESTED** [review]
lgtm

**Comment by CalvinKirs** [comment]
run buildall

**Review by gnehil — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
