### PR TITLE
[env](test) add ubsan content to the compilation options in asan

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

Currently, we have chosen to add ubsan content to asan so that both can check together. 
The known ubsan issues with p0 and p1 have already been fixed.

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p1

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
