### PR TITLE
[doc](index) fix inverted index doc typo and reorganize index related docs

### PR DESCRIPTION
**Pull request by xiaokang**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. fix type typo
2. reorganize index related docs and modify index overview introduction

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Comment by ZhangGuoqiang666** [comment]
run p1

**Review by zy-kkk — APPROVED** [review]

**Comment by xiaokang** [comment]
run compile

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
