### PR TITLE
[Fix](binlog) Fix bugs in tombstone

### PR DESCRIPTION
**Pull request by deadlinefen**
# Bug
## 1. table ref has not decreased when replay by tombstone.  
Under normal GC conditions, when a binlog is GC in a TableBinlog, it will reduce references in the binlog. When the number of references in the binlog is 0, the binlog instance will be removed from the allBinlogs in the DBBinlog, but this logic was not synchronized with the tombstone replay in the last binlog manager refactoring
## 2. table sync GC tombstone information can cause errors.
When only establishing table level synchronization, the GC ttls of each table may be different, which can result in different dummy commitSeq for each table. However, this information is not saved in tombstone, which can lead to metadata errors.
# Bug fix
1. fixed.
2. fixed, db sync can be smoothly upgraded, **but table sync requires GC of all binlogs, because the old tombstone did not contain enough commitSeq information**

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.02 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17161222749 Bytes

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.54 seconds
 stream load tsv:          507 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17163005615 Bytes

**Review by JackDrogon — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
