### PR TITLE
[Improve](start-shell)Optimize fe&be startup

### PR DESCRIPTION
**Pull request by CalvinKirs**
Added startup --console option
Modify the original default startup input stream to avoid log loss
--console is more suitable for development scenarios. When the user does not add any startup parameters, it is better to retain logs.

## Proposed changes
-  sh start_fe/start_be --console is used to instruct the program to run in console mode.
- sh start_fe/start_be --daemon is used to instruct the program to run in daemon mode.
- sh start_fe/start_be used starts as a background execution, records output and error logs to the specified file

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run p1

**Comment by CalvinKirs** [comment]
run p1

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM
please update doc in next PR

**Comment by xiaokang** [comment]
add some document @CalvinKirs

**Pull request merged**
