### PR TITLE
Remove unused client object from routine load

### PR DESCRIPTION
**Pull request by xy720**
1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Toms1999** [comment]
let me see see

**Comment by stalary** [comment]
LGTM

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
Please rebase master to fix P0 cases

**Review by xy720 — COMMENTED** [review]
Rebase master done.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
