### PR TITLE
[feat](nereids) support explain delete from clause

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
support explain like:
explain delete from T where A=1

Issue Number: close #xxx

### CODE REVIEW

**Review by morrySnow — COMMENTED** [review]
1. delete from dup/agg table still cannot explain, and will throw wrong error message, we should handle it by throw right error message.
2. add explain update case to ensure all dml is ok

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
