### PR TITLE
  [case] Load json data with enable_simdjson_reader=false

### PR DESCRIPTION
**Pull request by HowardQin**
Set enable_simdjson_reader=false 
and run some json data load tests
at last restore enable_simdjson_reader value

### CODE REVIEW

**Review by freemandealer — APPROVED** [review]
LGTM, nice job

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
