### PR TITLE
[Doc](tvf)Added tvf support for reading documents from avro files

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
trigger

**Pull request merged**
