### PR TITLE
[typo](doc) fix mistake word Update cn_doc and en_doc for elt.md

### PR DESCRIPTION
**Pull request by xiebanggui777**

### CODE REVIEW

**Comment by carlvinhust2012** [comment]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
Please rebase master

**Comment by zy-kkk** [comment]
Please rebase master to re-trigger the understream check

**Review by xiebanggui777 — COMMENTED** [review]
.

**Pull request closed without merging**
