### PR TITLE
[Fix](executor)Fix gcc compile failed

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

Fix gcc compile failed

### CODE REVIEW

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run performance

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run performance

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
