### PR TITLE
[bug](backup) Add table id into convert_rowset_ids()

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: step 1 in version 2.0 in #37076

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run fe_ut

**Comment by xy720** [comment]
run be_ut

**Review by cambyzju — APPROVED** [review]

**Comment by xy720** [comment]
run be ut

**Comment by xy720** [comment]
run fe ut

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Pull request merged**
