### PR TITLE
[improvement](config) update Be config max_runnings_transactions_per_txn_map default value

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes
The be config `max_runnings_transactions_per_txn_map` old value is 100, and increase the value to 2000 to avoid too many accumulated transactions, causing E-233 problems

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DongLiang-0** [comment]
runbuild all

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by dataroaring** [comment]
change it to 2000.

**Comment by DongLiang-0** [comment]
> change it to 2000.

Thanks for your suggestion, I will change it.

**Comment by xiaokang** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
