### PR TITLE
[improvement](executor) Add tvf and regression test for Workload Scheduler

### PR DESCRIPTION
**Pull request by wangbo**
Add tvf and regression test for Workload Scheduler.

```
select name,condition,action,priority,enabled,version from workload_schedule_policy() order by name;

```

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
