### PR TITLE
[testcase](hive)add exception test for hive txn

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Issue #31442
#32726

1. add LocalDfsFileSystem to manipulate local files.
2. add HMSCachedClientTest to analog HMS services.
3. add test for rollback commit.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Comment by wuwenchi** [comment]
run p0

**Comment by wuwenchi** [comment]
run external

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by wuwenchi** [comment]
run p0

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
