### PR TITLE
[chore](load) rm some load related redundant code

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
