### PR TITLE
Reduce conflict of sql_parser.cup

### PR DESCRIPTION
**Pull request by yangzhg**
## Proposed changes

Fix the Shift/Reduce conflict in cup file #4176

## Types of changes 

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Doris's issues](https://github.com/apache/incubator-doris/issues), and have described the bug/feature there in detail
- [x] Commit messages in my PR start with the related issues ID
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by morningman** [comment]
If we resolve the reduce conflict, I suggest to modify the `expectedConflicts` in `fe/fe-core/pom.xml` too.

**Comment by kangkaisen** [comment]
@yangzhg @morningman Hi, The sql_parser.cup file seems has conflict issue  frequently. could we put a readme file or some useful link under `fe/fe-core/src/main/cup/` directory？ which is friendly for new contributor.

**Comment by yangzhg** [comment]
> If we resolve the reduce conflict, I suggest to modify the `expectedConflicts` in `fe/fe-core/pom.xml` too.

done

**Comment by yangzhg** [comment]
> @yangzhg @morningman Hi, The sql_parser.cup file seems has conflict issue frequently. could we put a readme file or some useful link under `fe/fe-core/src/main/cup/` directory？ which is friendly for new contributor.
@kangkaisen  It is difficult to describe clearly how to write a cup file with simple sentences, but we can attach a link to the cup syntax

**Comment by kangkaisen** [comment]
> > @yangzhg @morningman Hi, The sql_parser.cup file seems has conflict issue frequently. could we put a readme file or some useful link under `fe/fe-core/src/main/cup/` directory？ which is friendly for new contributor.
> 
> @kangkaisen It is difficult to describe clearly how to write a cup file with simple sentences, but we can attach a link to the cup syntax

OK.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
