### PR TITLE
[bugfix](thirdparty) Upgrade aws s3 sdk to prevent mem leak

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

Issue Number: close #xxx
During the use of the AWS S3 SDK, we found that there is a memory leak. According to the official [issue](https://github.com/aws/aws-sdk-cpp/issues/2331), upgrading the SDK should resolve the issue.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
