### PR TITLE
[fix](stats) truncate min/max if too long

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

For some string value the max/min might be a very long string which might take too many memory of FE, so we truncate to 1024 chars if it's too long

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]

**Review by morrySnow — DISMISSED** [review]

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
