### PR TITLE
[enhancement](paimon)support predict for null and notnull

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

support predict for null and notnull

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by morningman** [comment]
Please add regression test

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Pull request merged**
