### PR TITLE
[feature](code-style)add spotless plugin

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

https://lists.apache.org/thread/x0r5lndj1b0dxypm3v2k0dnkvl416szl

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by morrySnow** [comment]
does new checker's rules TOTALLY same as original checkstyle rules? if not same, please desc what different between two of them

**Review by morrySnow — CHANGES_REQUESTED** [review]
does new checker's rules TOTALLY same as original checkstyle rules? if not same, please desc what different between two of them. there are too many check to avoid wrong code and ensure easy reading in checkstyle rules, u should impl all of them in new checker before remove checkstyle rules.
furthermore, u should explain the purpose of replacing spotless with checkstyle

**Comment by liugddx** [comment]
> does new checker's rules TOTALLY same as original checkstyle rules? if not same, please desc what different between two of them. there are too many check to avoid wrong code and ensure easy reading in checkstyle rules, u should impl all of them in new checker before remove checkstyle rules. furthermore, u should explain the purpose of replacing spotless with checkstyle

- `import-control` is done through replaceRegex https://github.com/diffplug/spotless/issues/649
- `Suppressions.xml` is not required under the spotless plugin.

Other rules can use spotless directly. If you have any other verification rules that you are interested in, please send them to me.

**Comment by morrySnow** [comment]
checkstyle is not just for code format check. it is also check some code logic check. for example,
- ensure no fall through branch in switch statement
- ensure switch statement has default branch
- name name overload method should put togather
- must have java doc for long method
- ...

does spotless do same check now?

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
@morrySnow I am compatible with checkstyle and spotless , PTAL .

**Comment by freemandealer** [comment]
run pipelinex_p0

**Review by morrySnow — DISMISSED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]

**Comment by liugddx** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
