### PR TITLE
[typo](docs) add more description of if function

### PR DESCRIPTION
**Pull request by lsy3993**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Comment by lsy3993** [comment]
run buidlall

**Review by yagagagaga — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by lsy3993** [comment]
run buildall

**Pull request closed without merging**
