### PR TITLE
[fix](smooth-upgrade) Fix function now upgrade compatible

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

https://github.com/apache/doris/pull/22321 was forgotten to pick to branch-2.0 and make upgrade safe.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Comment by hello-stephen** [comment]
run external

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
