### PR TITLE
[Enhancement](merge-on-write) optimize rowset tree and tablet header lock

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

1. tablet header lock need to be held  when update rowset tree or lookup row key. Long lock holding time can affect the performance of concurrent load.
2. The performance improvement brought by rowset tree for point lookup is not significant.

So I removed rowset tree and  tablet header lock when lookup row key, just traversal all segments. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
