### PR TITLE
optimize create tpch table statments to achieve higher performance

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
Can you provide some performance changes and conclusions before and after the table conversion?

**Comment by morningman** [comment]
> Can you provide some performance changes and conclusions before and after the table conversion?

I think this may trigger some bucket shuffle join

**Review by morningman — APPROVED** [review]
LGTM

**Comment by englefly** [comment]
> Can you provide some performance changes and conclusions before and after the table conversion?
1. Trigger bucket shuffle join for the following joins
orders join lineitem
part join partsupp

2. The distribution num of lineitem equals to that of orders, so that the buckets of both table are aligned, and good for bucket shuffle.

**Pull request merged**
