### PR TITLE
[test](Export) add `show export` regression testes

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

need merged into branch-2.0

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by BePPPower** [comment]
run buildall

**Comment by xiaokang** [comment]
The pick pr caused some testcases fail in branch-2.0 and reverted.

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
