### PR TITLE
[fix](merge-on-write) fix that delete bitmap is not calculated correctly when has sequence column

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

This problem was introduced by: #17542
`row_id` does not add 1 when there is a continue statement.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
