### PR TITLE
[minor](dependencies)binding a third-party Hadoop component to version 1.2.0

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
binding a third-party Hadoop component to version 1.2.0

hadoop-shaded-protobuf and hadoop-shaded-guava are older components, and the components such as guava they depend on have some known CVE issues, so they were upgraded to 1.2.0

remove unless hadoop yarn and htrace jars

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run p0 (timeout)

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
