### PR TITLE
[feature](properties) Erase dynamic properties when table is synced

### PR DESCRIPTION
**Pull request by deadlinefen**
# Add property "is_being_synced"
The syncer will mark the table in dest cluster as "is being synced" when establishing synchronization, so that it can be distinguished during use.
# Erase properties when table is being synced in dest cluster
- Disable dynamic partition and erase its other properties.  
- Switch auto bucket to static bucket.  (bucket nums depend on its source table)
- Erase property estimate_partition_size
- Erase storage policy
- Erase colocate with

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.42 seconds
 stream load tsv:          507 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         29 seconds loaded 2358488459 Bytes, about 77 MB/s
 stream load orc:          69 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17168354601 Bytes

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.3 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162737632 Bytes

**Pull request closed without merging**
