### PR TITLE
[BUG] Fix location url in agg_fn_evaluator

### LINKED ISSUE #3779: [BUG] Fix _hdfs_location misuse in AggFnEvaluator
The current location uses the wrong variable in AggFnEvaluator, the variable _hdfs_location in _fn should be used

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Fix #3779

### CODE REVIEW

**Review by imay — DISMISSED** [review]
LGTM

**Comment by kangkaisen** [comment]
The following code could remove.
```
    std::string _hdfs_location;
    std::string _init_fn_symbol;
    std::string _update_fn_symbol;
    std::string _merge_fn_symbol;
    std::string _serialize_fn_symbol;
    std::string _finalize_fn_symbol;
```

**Review by morningman — APPROVED** [review]
LGTM

**Review by kangkaisen — APPROVED** [review]
+1, LGTM

**Pull request merged**
