### PR TITLE
[Bug](streamload) fix inconsistent load result of be and fe

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

When enter an abnormal command like -H"Authorization:Basic    XXX",which is more than one blank space in Basic and XXX, will cause inconsistent load result of be and fe.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @HHoflittlefish777

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
