### PR TITLE
[fix](routine-load) routine load date where expression rewrite should change over time

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

when use where expr in routine load with data function, such as:
```
COLUMNS(k00,k01,k02,k03,k04,k05,k06,k07,k08,k09,k10,k11,k12,k13,k14,k15,k16,k17,k18),
COLUMNS TERMINATED BY "|",
where k12 >= date_sub(CURDATE(), INTERVAL 2 DAY)
PROPERTIES
(
     "max_batch_interval" = "5",
     "max_batch_rows" = "300000",
     "max_batch_size" = "209715200"
)
```

the where expr will be rewritten by fold constant and the result is
```
2024-X-X 00:00:00
```
which won't change after first rewrite.

As a long-term load, the rewritten constant should change over time.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
