### PR TITLE
[opt](nereids) optimze  aggregation estimation

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes
`select count(*) from T group by A, B`
suppose `ndv(A) > ndv(B)`
the estimated row count of aggregate is between `ndv(A)`  and `ndv(A) * ndv(B)`

in previous version, we choose upper bound, that is `ndv(A) * ndv(B)`. The drawback of this choice is the estimated row is often bigger that row count of T.

In this version, we choose the lower bound.
 
Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.07 seconds
 stream load tsv:          434 seconds loaded 74807831229 Bytes, about 164 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230414064424_clickbench_pr_129013.html

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
