### PR TITLE
[enhancement](log)Updated the default setting of sys_log_mode in fe.conf for better performance

### PR DESCRIPTION
**Pull request by Baymine**
## Proposed changes

Updated the default setting of `sys_log_mode` in `fe.conf` from `NORMAL` to `ASYNC` for better performance.

### CODE REVIEW

**Review by caiconghui — DISMISSED** [review]
LGTM

**Comment by caiconghui** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
Need modify Config.java too

**Comment by yiguolei** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Review by caiconghui — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
Do not pick to 2.1 now, we should check it on master.

**Pull request merged**
