### PR TITLE
[fix](group commit) Fix group commit in nereids

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Before: the insert into values in group commit use the stream load way to load data, this may cause complex data type load error.
After: use the original insert into values way(scanner node is union node), sink is group_commit_block_sink.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
