### PR TITLE
[refactor] refactor method finalize_columns of segment writer

### PR DESCRIPTION
**Pull request by zbtzbtzbt**
# Proposed changes

- seperate segment write logic of data area and index area
- more concise clear
- other small change

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.14 seconds
 load time: 476 seconds
 storage size: 17121492959 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230107144625_clickbench_pr_75425.html

**Comment by zbtzbtzbt** [comment]
@yixiutt @dataroaring  
I refactor some of your code.
cc, thanks!

**Review by zhannngchen — CHANGES_REQUESTED** [review]
pls update the title, `refactor segment writer` sounds like a big change...
I think the title should be `refactor method finalize_columns of segment writer`

**Comment by zbtzbtzbt** [comment]
> 

done

**Comment by zbtzbtzbt** [comment]
> pls update the title, `refactor segment writer` sounds like a big change... I think the title should be `refactor method finalize_columns of segment writer`

done

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Review by yixiutt — DISMISSED** [review]

**Comment by yixiutt** [comment]
LGTM

**Review by zhannngchen — DISMISSED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
