### PR TITLE
[improvement](pipeline) Use hash shuffle local exchange if no require…

### PR DESCRIPTION
**Pull request by Gabriel39**
…d data distribution

This is a follow-up for #34122 .
Currently, we use bucket shuffle local exchange to re-distribution data before a 'colocated' operator. But if no colocate/bucket-shuffle join followed, bucket-shuffle for this operator is not always suitable because the parallism will be restricted by the account of buckets.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
