### PR TITLE
[enhance](auth)modify priv of refresh catalog/db/table

### PR DESCRIPTION
**Pull request by zddr**
change priv of refresh catalog/db/table to `PrivPredicate.SHOW`

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zddr** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
