### PR TITLE
[Refact](inverted index) refact no need read data opt logic

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Refact no need read data for column where all predicates have passed the inverted index, make it clear

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by csun5285 — COMMENTED** [review]
LGTM

**Pull request merged**
