### PR TITLE
[fix](memory) Fix too many repeat cause OOM

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Limit the maximum number of repeat
```
select repeat("a", 10000);
```

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.21 seconds
 load time: 643 seconds
 storage size: 17122875466 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221220172516_clickbench_pr_65839.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by luozenglin** [comment]
This pr sets the repeat count to the smaller value of count and `repeat_max_num`, which may cause the result to be inconsistent with the user's expectations and there is no error prompt. Why not throw an exception when count is greater than `repeat_max_num`?

**Comment by xinyiZzz** [comment]
> This pr sets the repeat count to the smaller value of count and `repeat_max_num`, which may cause the result to be inconsistent with the user's expectations and there is no error prompt. Why not throw an exception when count is greater than `repeat_max_num`?

throw an exception seems to be a better solution

**Pull request merged**
