### PR TITLE
[fix](planner) collect_list and collect_set should always not null

### PR DESCRIPTION
**Pull request by morrySnow**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Review by starocean999 — DISMISSED** [review]

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by amorynan — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
