### PR TITLE
[fix](scanner) cached blocks may be empty when VFileScanner return NOT_FOUND

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Cached blocks may be empty when VFileScanner return NOT_FOUND. This feature is introduced by https://github.com/apache/doris/pull/15226. Move this function inner `VFileScanner`.

Fix core dump like:
```
 0# 0x000055D9EE0F45BE in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
 1# PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0] in /mnt/datadisk0/gaoxin/app/jdk-17.0.2/lib/server/libjvm.so
 2# JVM_handle_linux_signal in /mnt/datadisk0/gaoxin/app/jdk-17.0.2/lib/server/libjvm.so
 3# 0x00007F21F62D8400 in /lib64/libc.so.6
 4# doris::vectorized::Block::~Block() in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
 5# doris::vectorized::ScannerContext::get_block_from_queue(doris::RuntimeState*, doris::vectorized::Block*, bool*, int, bool) in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
 6# doris::vectorized::VScanNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
 7# doris::vectorized::VScanNode::get_next_after_projects(doris::RuntimeState*, doris::vectorized::Block*, bool*, std::function<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*)> const&, bool) in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
 8# doris::pipeline::SourceOperator<doris::vectorized::VScanNode>::get_block(doris::RuntimeState*, doris::vectorized::Block*, doris::pipeline::SourceState&) in /mnt/datadisk0/gaoxin/doris/output/be/lib/doris_be
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Review by zddr — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
