### PR TITLE
[Enhance](regression)enhance external  jdbc case

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes
enhance external  jdbc case

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
