### PR TITLE
[Fix](load) fix wrong replica number when loading to table with no partition

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

now in auto-partition situation it will occur. may effect the txn commit check.

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
