### PR TITLE
[Fix](parquet-reader) Fix definition level rle decode dead loop in parquet-reader.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Fix] (parquet-reader) Fix definition level rle decode dead loop in parquet-reader.

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
