### PR TITLE
[fix](planner) Empty table source should not begin a transaction to avoid infinite transaction

### LINKED ISSUE #38956: [Bug] Insert from empty source will begin an infinite transaction
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

As title.
InsertIntoTableCommand#runInternal
```java
private void runInternal(ConnectContext ctx, StmtExecutor executor) throws Exception {
        AbstractInsertExecutor insertExecutor = initPlan(ctx, executor);
        // if the insert stmt data source is empty, directly return, no need to be executed.
        if (insertExecutor.isEmptyInsert()) {
            return;
        }
        insertExecutor.executeSingleInsert(executor, jobId);
}
```
Here insert command will not be actually started when empty relation, so callback of txn commit and publish will never be called, resulting in an infinite transaction which will only finish when timeout reached.

InsertIntoTableCommand#initPlan  (transaction begins here)
```java
public AbstractInsertExecutor initPlan(ConnectContext ctx, StmtExecutor executor) throws Exception {
        // ...
        try {
           // ...
            insertExecutor.beginTransaction();
            insertExecutor.finalizeSink(planner.getFragments().get(0), sink, physicalSink);
            targetTableIf.readUnlock();
        } catch (Throwable e) {
            targetTableIf.readUnlock();
            // the abortTxn in onFail need to acquire table write lock
            if (insertExecutor != null) {
                insertExecutor.onFail(e);
            }
            throw e;
        }

        executor.setProfileType(ProfileType.LOAD);
        // We exposed @StmtExecutor#cancel as a unified entry point for statement interruption,
        // so we need to set this here
        executor.setCoord(insertExecutor.getCoordinator());
        return insertExecutor;
    }
```

### What You Expected?

Empty source optimization should commit and publish transaction.

### How to Reproduce?

Just create an empty table, insert data from itself.

### Anything Else?

introduced by #34418

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Issue Number: close #38956 

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
