### PR TITLE
[test](migrate) move 2 cases from p2 to p0

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

releated: #36787

- test_text_garbled_file
- test_hive_statistic_timeout
- test_hive_to_array
- test_hive_statistic
- test_hive_default_partition

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
