### PR TITLE
[enhancement](regression-test) schema reordering case

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
