### PR TITLE
Revert "[feature](load) enable memtable on sink node by default (#28963)"

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

This reverts commit 17917a0adb57ac337dfd41e8853b1aa87c9d5acd.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
