### PR TITLE
[feature](cloud) Support path format v1 for Storage Vault

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Support path format v1 for Storage Vault. See more detail in #35473

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
we may need some test

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
