### PR TITLE
[feature-wip](meta) create or replace to overwrite table (#21834)

### PR DESCRIPTION
**Pull request by davedwwang**
[feature-wip](meta) create or replace to overwrite table (#21834)

### CODE REVIEW

**Comment by davedwwang** [comment]
I am not yet sure if my implementation approach is correct, so I haven't developed test cases. Please review it first to ensure the approach is correct. If the approach is correct, I will add the test cases immediately.（我还不知道我的实现思路是否正确，所以测试用例还没有开发。先麻烦review下已确保思路正确，如果思路正确，我会马上补上测试用例。）

**Review by morrySnow — COMMENTED** [review]
please add ut or regression test

**Comment by davedwwang** [comment]
@morrySnow Thank you for the code review. I have added test cases and regression tests. However, I am not yet very familiar with the focus of test cases and regression testing, so my writing might not be good. I look forward to your guidance！

**Comment by davedwwang** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46 seconds
 stream load tsv:          544 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161959621 Bytes

**Comment by catpineapple** [comment]
hi, @davedwwang   you can resolve the conflicts,then add case ,thanks.

**Pull request closed without merging**
