### PR TITLE
[ut](stats) Added tests for JDBC analysis tasks

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

Added  unit tests for JDBC Analysis task.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
