### PR TITLE
[Fix](Nereids) fix case expectation error with nereids

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
## Proposed changes

Problem:
expectation error when checking bitmap int
Example:
expecting an exception of (bitmap in null or 1 = 1)
Reason:
nereids lose check of datatype
Solved:
cherry-pick parts of checks from master pr #22851 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Pull request merged**
