### PR TITLE
[fix](match_phrase) Fix the inconsistent query result for 'match_phrase' after creating index without support_phrase property

### PR DESCRIPTION
**Pull request by Tanya-W**
## Proposed changes

if create inverted index without support_phrase property, remaining the match_phrase condition to filter by match function.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Tanya-W** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Comment by Tanya-W** [comment]
run beut

**Comment by Tanya-W** [comment]
run feut

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
