### PR TITLE
Fix rowset_meta race condition for commit_txn in TxnManager

### LINKED ISSUE #3329: TxnManager::commit_txn may have race condition because of lack of txn lock
https://github.com/apache/incubator-doris/blob/b29cb9dbb3d32cf58a20036049420095011597e0/be/src/olap/txn_manager.cpp#L187-L243

### PR DESCRIPTION
**Pull request by caiconghui**
This PR is to fix rowset_meta race condition for rowset_meta modification in commit_txn

### CODE REVIEW

**Comment by caiconghui** [comment]
for #3329

**Review by chaoyli — DISMISSED** [review]

**Comment by kangkaisen** [comment]
@caiconghui Hi, Why `prepare_txn`, `rollback_txn`, `delete_txn` don't need this txn_lock?

**Comment by caiconghui** [comment]
> @caiconghui Hi, Why `prepare_txn`, `rollback_txn`, `delete_txn` don't need this txn_lock?

@kangkaisen txn_lock to protect txn itself, and txn_map_lock to protect txn_map

**Comment by morningman** [comment]
> @caiconghui Hi, Why `prepare_txn`, `rollback_txn`, `delete_txn` don't need this txn_lock?

Only `commit_txn` and `publish_txn` has rowset meta modification. So I think the txn lock is mainly to protect the rowset meta of the specified txn.

**Comment by kangkaisen** [comment]
>txn_lock to protect txn itself

what's the meaning of `protect txn itself` ?

> Only `commit_txn` and `publish_txn` has rowset meta modification. So I think the txn lock is mainly to protect the rowset meta of the specified txn.

@caiconghui  Hi. If @morningman is right. Please rename `_txn_mutex` and `_txn_shard_size`, current name is confusing.

**Comment by caiconghui** [comment]
> > txn_lock to protect txn itself
> 
> what's the meaning of `protect txn itself` ?
> 
> > Only `commit_txn` and `publish_txn` has rowset meta modification. So I think the txn lock is mainly to protect the rowset meta of the specified txn.
> 
> @caiconghui Hi. If @morningman is right. Please rename `_txn_mutex` and `_txn_shard_size`, current name is confusing.

how about _rowset_meta_mutex,  _rowset_meta_shard_size? @kangkaisen

**Comment by kangkaisen** [comment]
> how about _rowset_meta_mutex, _rowset_meta_shard_size? @kangkaisen

@caiconghui OK. I agree with you.

**Comment by chaoyli** [comment]
I think TxnManager is better to not know the RowsetMeta concept.

**Comment by kangkaisen** [comment]
> I think TxnManager is better to not know the RowsetMeta concept.
> It's only to know the Transaction concept, so I think the previous name is OK.

1.  TxnManager **has known** the RowsetMeta concept.
2. `_txn_mutex` normally means we should get this lock for most of txn operations, but we only get it when `commit_txn` and `publish_txn`
3. We really use `_txn_mutex` to protect the rowset meta.

**Comment by caiconghui** [comment]
> > I think TxnManager is better to not know the RowsetMeta concept.
> > It's only to know the Transaction concept, so I think the previous name is OK.
> 
> 1. TxnManager **has known** the RowsetMeta concept.
> 2. `_txn_mutex` normally means we should get this lock for most of txn operations, but we only get it when `commit_txn` and `publish_txn`
> 3. We really use `_txn_mutex` to protect the rowset meta.

I think the txn_lock really ensure the commit_txn and publish_txn be atomic function, which not only include rowset_meta modification, function also need to find, insert or find and then delete the txn from txn_map.
@kangkaisen @morningman @chaoyli

**Comment by chaoyli** [comment]
You can use the _txn_mutex still

**Review by chaoyli — DISMISSED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
