### PR TITLE
[Fix](hdfs-fs)The cache expiration should explicitly release the held fs

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
The RemoteFSPhantomManager class is responsible for managing phantom references of RemoteFileSystem objects, ensuring that the associated FileSystem resources are automatically cleaned up when RemoteFileSystem objects are garbage collected.

Key features:

- Phantom Reference Monitoring: The class uses a ReferenceQueue and PhantomReference to track RemoteFileSystem objects. When these objects are no longer in use and garbage collected, the class ensures the corresponding FileSystem resources are properly closed to prevent resource leaks.
- Thread-safe Cleanup: It provides a thread-safe mechanism to start a cleanup thread only once. This thread runs periodically, checking the ReferenceQueue and closing any unused FileSystem resources.
Resource Management: The class maintains a map between phantom references and their corresponding FileSystem objects, ensuring that these resources are cleaned up appropriately.
- The cleanup thread runs at regular intervals, ensuring that any RemoteFileSystem object that is no longer in use is safely removed along with its associated FileSystem resources.

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run cloud_p1

**Comment by CalvinKirs** [comment]
run External

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run p0 
run External

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run cloud_p0

**Comment by CalvinKirs** [comment]
run cloud_p0

**Comment by CalvinKirs** [comment]
run cloud_p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run cloud_p0

**Pull request merged**
