### PR TITLE
[Enhancement](auto-partition) Re-add deduplication to auto partition rpc

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

removed in https://github.com/apache/doris/pull/27817. we need it so re add it.

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
testing in internal regression environment

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Comment by hello-stephen** [comment]
skip buildall

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
