### PR TITLE
[fix](function) Fix from_second functions overflow and wrong result

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before:
```sql
mysql> select from_microsecond(253402272999999999);
+--------------------------------------+
| from_microsecond(253402272999999999) |
+--------------------------------------+
|                                      |
+--------------------------------------+

mysql> select from_millisecond(-20);
+-----------------------+
| from_millisecond(-20) |
+-----------------------+
|                       |
+-----------------------+
```
after:
```sql
mysql> select from_microsecond(253402272000000000);
+--------------------------------------+
| from_microsecond(253402272000000000) |
+--------------------------------------+
| NULL                                 |
+--------------------------------------+

mysql> select from_millisecond(-20);
+-------------------------+
| from_millisecond(-20)   |
+-------------------------+
| NULL                    |
+-------------------------+
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
