### PR TITLE
[regression](case) test routine load with enable_pipeline_load=true

### PR DESCRIPTION
**Pull request by HowardQin**
enable_pipeline_load=true and test routine load kafka data

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by sollhui — COMMENTED** [review]
Now enable_pipeline_load is true by default

**Comment by HowardQin** [comment]
> Now enable_pipeline_load is true by default

OK，I'll close this pr.

**Comment by HowardQin** [comment]
enable_pipeline_load is true by default, is test case is not necessary.

**Pull request closed without merging**
