### PR TITLE
[fix](load) fix DataSink prepared check in PlanFragmentExecutor

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

`PlanFragmentExecutor` called `DataSink::prepare()` and set `_prepared` to true.
But `AsyncWriterSink` had moved `prepare()` into `open()` (renamed to `_init()`), nothing is done (`VTabletWriter::_inited` = false).
Then `PlanFragmentExecutor` calls `DataSink::close()` and goes into the `_prepared` branch:

```cpp
void PlanFragmentExecutor::close() {
    if (_closed) {
        return;
    }

    // Prepare may not have been called, which sets _runtime_state
    if (_runtime_state != nullptr) {
        // _runtime_state init failed
        if (_plan != nullptr) {
            static_cast<void>(_plan->close(_runtime_state.get()));
        }

        if (_sink != nullptr) {
            if (_prepared) {
                Status status;
                {
                    std::lock_guard<std::mutex> l(_status_lock);
                    status = _status;
                }
                static_cast<void>(_sink->close(runtime_state(), status));
            } else {
                static_cast<void>(
                        _sink->close(runtime_state(), Status::InternalError("prepare failed")));
            }
        }
```

Causing this DCHECK to fail:

```cpp
Status VTabletWriter::close(Status exec_status) {
    if (!_inited) {
        DCHECK(!exec_status.ok());
        _cancel_all_channel(exec_status);
        _close_status = exec_status;
        return _close_status;
    }
```

So now we need to check `_opened` instead of `_prepared` in `PlanFragmentExecutor`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
