### PR TITLE
[test](regression) support ccr regression

### PR DESCRIPTION
**Pull request by zgxme**
## Proposed changes
add CI base conf to support ccr regression

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
