### PR TITLE
[bug](delete) fix delete random distributed tbl

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

Bug description:
In PR https://github.com/apache/doris/pull/33630, Doris supports auto aggregation for random distributed table, but it not only effects query statements, so if we delete from a random distributed table, will get an error because of unexpectedly rewriting.
```
CREATE TABLE `test_tbl` (
  `k` INT NULL,
  `v` BIGINT SUM NULL
) ENGINE=OLAP
AGGREGATE KEY(`k`)
DISTRIBUTED BY RANDOM BUCKETS AUTO;

mysql > delete from test_tbl where k=1;
ERROR 1105 (HY000): errCode = 2, detailMessage = Where clause only supports compound predicate, binary predicate, is_null predicate or in predicate.
```

fix:
Check whether it is a query statement before rewriting.

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
add test case please

**Comment by DarvenDuan** [comment]
> add test case please

done

**Review by morrySnow — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
