### PR TITLE
Add 'IndexKeysType' field in 'Desc all table stmt'

### PR DESCRIPTION
**Pull request by EmmyMiao87**
After doris support aggregation materialized view on duplicate table, desc stmt of metadata is confused in sometimes.
The reason is that there is no grouping information in desc stmt of metadata.

For example:
There are two materialized view as following.
    1. create materialized view k1_k2 as select k1, k2 from table;
    2. create materialzied view deduplicated_k1_k2 as select k1, k2 from table group by k1, k2;
Before this commit, the metatdata in desc stmt is the same.

   ```
    +-----------------------+-------+----------+------+-------+---------+-------+
    | IndexName             | Field | Type     | Null | Key   | Default | Extra |
    +-----------------------+-------+----------+------+-------+---------+-------+
    | k1_k2                 | k1    | TINYINT  | Yes  | true  | N/A     |       |
    |                       | k2    | SMALLINT | Yes  | true  | N/A     |       |
    | deduplicated_k1_k2    | k1    | TINYINT  | Yes  | true  | N/A     |       |
    |                       | k2    | SMALLINT | Yes  | true  | N/A     |       |
    +-----------------------+-------+----------+------+-------+---------+-------+
   ```

So, we need to show the KeysType of materialized view in desc stmt.
Now, the desc stmt of all mvs is changed as following:

    ```
    +-----------------------+---------------+-------+----------+------+-------+---------+-------+
    | IndexName             | IndexKeysType | Field | Type     | Null | Key   | Default | Extra |
    +-----------------------+---------------+-------+----------+------+-------+---------+-------+
    | k1_k2                 | DUP_KEYS      | k1    | TINYINT  | Yes  | true  | N/A     |       |
    |                       |               | k2    | SMALLINT | Yes  | true  | N/A     |       |
    | deduplicated_k1_k2    | AGG_KEYS      | k1    | TINYINT  | Yes  | true  | N/A     |       |
    |                       |               | k2    | SMALLINT | Yes  | true  | N/A     |       |
    +-----------------------+---------------+-------+----------+------+-------+---------+-------+
    ```

### CODE REVIEW

**Review by imay — DISMISSED** [review]
LGTM

**Comment by kangkaisen** [comment]
I think only show IndexKeysType isn't enough，we need also show the materialized view sql.
@EmmyMiao87 Hi, Currently, do we have a way to get the materialized view  sql?

**Comment by EmmyMiao87** [comment]
> I think only show IndexKeysType isn't enough，we need also show the materialized view sql.
> @EmmyMiao87 Hi, Currently, do we have a way to get the materialized view sql?

Actually, according to keystype, iskey, column, and Extra we could infer the sql of materialized view. But this display sql really better than desc stmt.
Until now, we do not have a way to get the materialized view sql.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
