### PR TITLE
[Cloud](Variant) support DESC merge variants's schema for cloud mode

### PR DESCRIPTION
**Pull request by eldenmoon**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]

**Review by csun5285 — APPROVED** [review]
LGTM

**Pull request merged**
