### PR TITLE
[improvement](be report) add be report http

### PR DESCRIPTION
**Pull request by yujun777**
used for regression test.  we can send be report http and no need to wait.

usage:

|type|http| regression test suites|
|---  |---  |---|
|report disk |  http://beIp:beHttpPort/api/report/disk |  be_report_disk(beIp, beHttpPort)
|report task |  http://beIp:beHttpPort/api/report/task |  be_report_task(beIp, beHttpPort)
|report tablet |  http://beIp:beHttpPort/api/report/tablet |  be_report_tablet(beIp, beHttpPort)

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
