### PR TITLE
[fix](partial update) Fix some bugs about partial update

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes
fix some bugs about partial update, related pr: 
- https://github.com/apache/doris/pull/28321
- https://github.com/apache/doris/pull/27947

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
