### PR TITLE
[opt](test) remove duplicate case and make concurrent to accelerate regression test

### PR DESCRIPTION
**Pull request by sollhui**
Remove duplicate case and make concurrent to accelerate regression test.

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
