### PR TITLE
[test](ES Catalog) Add test cases for ES 5.x

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

ES 5.x test output is same with ES 6.x.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p1

**Comment by qidaye** [comment]
run cloud p1

**Comment by qidaye** [comment]
run cloud_p1

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
