### PR TITLE
[Refactor](exec) Remove the unless header of vresult_writer

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Remove unless code of vresult_wirter;

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
