### PR TITLE
[fix](legacy-planner) fixed loss of BetweenPredicate rewrite on reana…

### LINKED ISSUE #29798: [Bug] old planner can not rewrite BetweenPredicate  in having
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table  test(a DATE,b varchar(100),c varchar (100),d varchar(100),e int,f int)  
ENGINE=OLAP
DUPLICATE KEY( a )
COMMENT "OLAP"
DISTRIBUTED BY HASH( e ) BUCKETS  auto
PROPERTIES (
    "replication_num" = "1"
);

set experimental_enable_nereids_planner = false;

select t1.a,t1.b,t1.c,t1.f,t1.d,t1.e,stddev_pop(t1.d+t1.e) std from test t1 
group by t1.f,t1.d,t1.e,t1.a,t1.b,t1.c
having t1.b between 'aa' and 'bb';

```

ERROR 1105 (HY000): IllegalStateException, msg: java.lang.IllegalStateException: BetweenPredicate needs to be rewritten into a CompoundPredicate.

### What You Expected?

can get result

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
…lyze in legacy planner (29798)

## Proposed changes

having clause rewrite is lost on expression rewrite in old planner flow.
this fix retains the rewrite of having expression in re-analyzed path.

Issue Number: close #29798 

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by xiaokang — CHANGES_REQUESTED** [review]
pls add testcases

**Comment by Nitin-Kashyap** [comment]
> pls add testcases

added regression test

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Vallishp — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
