### PR TITLE
[Enhancement](streamload) stream tvf support compress

### PR DESCRIPTION
**Pull request by zzzzzzzs**
## Proposed changes

example:
```
curl -v --location-trusted -u root: -H "sql: insert into test.t1(c1, c2) select c1,c2 from http_stream(\"format\" = \"CSV\", \"compress_type\" = \"GZ\",\"column_separator\" = \",\")" -T all_types.csv.gz http://127.0.0.1:8030/api/_http_stream

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by zzzzzzzs** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
