### PR TITLE
[bug](fix) intersect_count function query error fix

### LINKED ISSUE #27954: [Bug] intersect_count function query error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
select intersect_count(uid, `date`, '2022-10-12') as meituan_uv
from retention_test_bitmap;
– SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = (10.16.10.6)[INTERNAL_ERROR]Agg Function intersect_count(BITMAP, DATETIMEV2(0), DATETIMEV2(6)) is not implemented
```

### What You Expected?

no error

### How to Reproduce?

```sql
CREATE TABLE retention_test(
`uid` int COMMENT 'user id',
`date` datetime COMMENT 'date time'
)
DUPLICATE KEY(uid)
DISTRIBUTED BY HASH(uid) BUCKETS 3
PROPERTIES (
"replication_num" = "1"
);

 
CREATE TABLE retention_test_bitmap(
`date` datetime COMMENT 'date time' ,
`uid` bitmap BITMAP_UNION COMMENT 'user id',
)
aggregate KEY(`date`)
DISTRIBUTED BY HASH(`date`) BUCKETS 3
PROPERTIES (
"replication_num" = "1"
);

 
INSERT into retention_test (uid, date)

values (0, '2022-10-12'),
(0, '2022-10-13'),
(0, '2022-10-14'),
(1, '2022-10-12'),
(1, '2022-10-13'),
(2, '2022-10-12');
 
insert into retention_test_bitmap
select `date`,bitmap_agg(uid)
from retention_test
group by `date`
;

select intersect_count(uid, `date`, '2022-10-12') as meituan_uv
from retention_test_bitmap; 
```

### Anything Else?

new planner
image
old  planner
image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LemonLiTree**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/27954

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
add desc to describe the problem

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Pull request closed without merging**
