### PR TITLE
[fix](broker) fix no error url when broker data quality error

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

becase #30581, broker load can not get error url when DATA_QUALITY_ERROR

before 
image

after
image

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run performance

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a test which check error url.

**Comment by nextdreamblue** [comment]
> Please add a test which check error url.

have added ' result[0][13].contains("_load_error_log") '

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run p0

**Pull request merged**
