### PR TITLE
[refactor](Nereids): avoid ConnectContext.get() ASAP to improve proformance

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

`ConnectContext.get()` will invoke `ThreadLocal get()`, invoke it frequently will cost much time.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by yiguolei** [comment]
why using ConnectContext.get() affect performance?

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by keanji-x — APPROVED** [review]

**Pull request merged**
