### PR TITLE
[fix](schema change) Fix fe restart failed because of replay schema change alter job failed

### PR DESCRIPTION
**Pull request by Tanya-W**
# Proposed changes

Issue Number: close (https://github.com/apache/doris/issues/17824)

## Problem summary

Change table's state to normal after schema change job finished

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run build

**Comment by Tanya-W** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.94 seconds
 stream load tsv:          475 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         37 seconds loaded 2358488459 Bytes, about 60 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230316035713_clickbench_pr_114960.html

**Comment by Tanya-W** [comment]
run p0

**Comment by Tanya-W** [comment]
run feut

**Comment by Tanya-W** [comment]
run buildall

**Comment by Tanya-W** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
