### PR TITLE
[Doc](typo) Remove redundant symbols and Fix some misspelled words

### PR DESCRIPTION
**Pull request by liujiwen-up**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yagagagaga — DISMISSED** [review]
LGTM

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
There are some conflicts and you should rebase it

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
