### PR TITLE
[fix](function) Support more behaviors of cast time in MySQL

### PR DESCRIPTION
**Pull request by Mryange**
# Proposed changes
fix https://github.com/apache/doris/pull/18565  Some MySQL behaviors that still need to be supported.
**before**
```
mysql [(none)]>select cast('2023-02-02 19:18:17' as time);
+-------------------------------------+
| CAST('2023-02-02 19:18:17' AS TIME) |
+-------------------------------------+
| NULL                                |
+-------------------------------------+
```

**affter**

```
mysql [(none)]>select cast('2023-02-02 19:18:17' as time);
+-------------------------------------+
| CAST('2023-02-02 19:18:17' AS TIME) |
+-------------------------------------+
| 19:18:17                            |
+-------------------------------------+

```
## Problem summary

In the past, the "time" type was stored using double, but later additional date types were added. The problem is that we do not allow users to use the "time" type
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unsupported type: TIME
```
it is only used internally in the program. 
May be we need to **refactor** the code?

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run builall

**Comment by Mryange** [comment]
run builall

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.96 seconds
 stream load tsv:          424 seconds loaded 74807831229 Bytes, about 168 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230424140810_clickbench_pr_134140.html

**Comment by Mryange** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
