### PR TITLE
[typo](doc)rectify some spelling mistakes

### PR DESCRIPTION
**Pull request by Johnnyssc**
# Proposed changes
same with https://github.com/apache/doris/pull/13704
Issue Number: close #xxx

## Problem summary
rectify some spelling mistakes

Describe your changes.
string variables and docs 

## Checklist(Required)

* [ no] Does it affect the original behavior
* [ no] Has unit tests been added
* [ yes] Has document been added or modified
* [no ] Does it need to update dependencies
* [ yes] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.24 seconds
 stream load tsv:          476 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         40 seconds loaded 2358488459 Bytes, about 56 MB/s
 stream load orc:          69 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230217062438_clickbench_pr_98675.html

**Review by luzhijing — DISMISSED** [review]

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
Sorry for my wrong operation, could you rebase the code？

**Comment by Johnnyssc** [comment]
hi&nbsp;Luzhijing!
because of the wrong operation, i create a new pr, u could review the code&nbsp;
thx and wish u have a good day!






                       
Original
                       
                     

From:"Luzhijing"< ***@***.*** &gt;;

Date:2023/3/9 20:44

To:"apache/doris"< ***@***.*** &gt;;

CC:"Johnny_Sc"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

Subject:Re: [apache/doris] [typo](doc)rectify some spelling mistakes (PR#16863)




 
Sorry for my wrong operation, could you rebase the code？

**Pull request closed without merging**
