### PR TITLE
[fix](FoldConst)The length function returns incorrect results under FoldConst.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

```
mysql [(none)]>set debug_skip_fold_constant = false;
Query OK, 0 rows affected (0.00 sec)

mysql [(none)]>select length('你');
+---------------+
| length('你')  |
+---------------+
|             1 |
+---------------+
1 row in set (0.01 sec)

mysql [(none)]>set debug_skip_fold_constant = true;
Query OK, 0 rows affected (0.00 sec)

mysql [(none)]>select length('你');
+---------------+
| length('你')  |
+---------------+
|             3 |
+---------------+
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run cloud_p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run external

**Review by zhangstar333 — APPROVED** [review]

**Comment by zclllyybb** [comment]
already picked into 2.1 by https://github.com/apache/doris/pull/46523

**Pull request merged**
