### PR TITLE
[fix](doc) Update doris zh-CN doc hit-the-rollup.md  prefix index  link address open fail

### PR DESCRIPTION
**Pull request by fcb-xiaobo**
## Proposed changes

update dev version zh-CN doc hit-the-rollup.md  prefix index link address

### CODE REVIEW

**Comment by DongLiang-0** [comment]
Thank you for your contribution. Please add this link to the corresponding English document.

**Comment by fcb-xiaobo** [comment]
> Thank you for your contribution. Please add this link to the corresponding English document.

i hive modified the doris en doc open prefix index link address
https://github.com/apache/doris/pull/24962#issue-1914907140,Could you please take a look

**Comment by DongLiang-0** [comment]
> > Thank you for your contribution. Please add this link to the corresponding English document.
> 
> i have modified the doris en doc open prefix index link address,pr address [#24962 (comment)](https://github.com/apache/doris/pull/24962#issue-1914907140) you please take a look

This is the same problem. Can it be merged into one PR?

**Comment by fcb-xiaobo** [comment]
> > > Thank you for your contribution. Please add this link to the corresponding English document.
> > 
> > 
> > i have modified the doris en doc open prefix index link address,pr address [#24962 (comment)](https://github.com/apache/doris/pull/24962#issue-1914907140) you please take a look
> 
> This is the same problem. Can it be merged into one PR?

ok. i try merged

**Pull request closed without merging**
