### PR TITLE
[fix](regression) fix group commit stream load regression test

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

`test_group_commit_stream_load` is failed sometimes becase schema change:
```
W20231011 11:27:57.499117  9973 status.h:382] meet error status: [DATA_QUALITY_ERROR]schema version not match

        0#  doris::GroupCommitTable::get_first_block_load_queue(long, std::shared_ptr<doris::vectorized::FutureBlock>, std::shared_ptr<doris::LoadBlockQueue>&) at /root/dori
s/be/src/common/status.h:0
        1#  doris::GroupCommitMgr::_get_first_block_load_queue(long, long, std::shared_ptr<doris::vectorized::FutureBlock>, std::shared_ptr<doris::LoadBlockQueue>&) at /var/
local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        2#  doris::GroupCommitMgr::_group_commit_stream_load(std::shared_ptr<doris::StreamLoadContext>) at /root/doris/be/src/runtime/group_commit_mgr.cpp:593
        3#  std::_Function_handler<void (), doris::GroupCommitMgr::group_commit_stream_load(std::shared_ptr<doris::StreamLoadContext>)::$_0>::_M_invoke(std::_Any_data const&
) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:701
        4#  doris::ThreadPool::dispatch_thread() at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/move.h:206
        5#  doris::Thread::supervise_thread(void*) at /var/local/ldb-toolchain/bin/../usr/include/pthread.h:562
        6#  ?
        7#  clone
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
