### PR TITLE
[Fix](multi catalog, nereids)Fix FileQueryScanNode couldn't filter partition in nereids planner bug.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Nereids planner add conjuncts to ScanNode after call finalize, this may cause external table scan node fail to filter useless partition, because external table do the partition prune in the finalize method.
This pr is to fix this bug. In the rewrite stage, pass the conjuncts to LogicalFileScan object, and eventually pass to ScanNode while creating it. So that the ScanNode could use the conjuncts while doing finalize. Why not doing the partition prune in the LogicalFileScan like LogicalOlapScan doing? Because Iceberg api doesn't have the partition concept, it just accept a list of Conjuncts, so it's easier to pass the conjuncts to ScanNode (Hive, Icegerg, Hudi...) and doing the partition prune in there.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
Can't we unify all scan nodes?

**Comment by 924060929** [comment]
maybe you should add a rule like `PruneOlapScanPartition`

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
