### PR TITLE
[fix](regression) fix p1 test_backup_restore fail caused by http download 401 invalid token error

### PR DESCRIPTION
**Pull request by ZhangYu0123**
## Proposed changes
fix p1 test_backup_restore fail caused by http download 401 invalid token error
(1)  set fe auth token,  becouse regression cannot get the cluster token, so not auto generate it in test env.
(2)  fix remote_http_download result code problem.

# problem :
image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run p0

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 43.56 seconds
 stream load tsv:          461 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          70.2 seconds inserted 10000000 Rows, about 142K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230624081002_clickbench_pr_166774.html

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
