### PR TITLE
[chore](build) Fix compilation errors reported by GCC-13

### LINKED ISSUE #21214: [Bug] Failed to build BE by GCC-13
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```shell
ccache /devel/compiler/bin/g++ -DBOOST_STACKTRACE_USE_BACKTRACE -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DUSE_HADOOP_HDFS -I/Programs/doris/be/src/apache-orc/c++/include -I/Programs/doris/be/build_ASAN/src/apache-orc/c++/include -I/Programs/doris/be/build_ASAN/src/clucene/src/shared -I/Programs/doris/be/src/clucene/src/core -I/Programs/doris/be/src/clucene/src/shared -I/Programs/doris/be/src/clucene/src/contribs-lib -I/Programs/doris/be/src -I/Programs/doris/be/test -I/devel/opt/java/include -I/devel/opt/java/include/linux -isystem /Programs/doris/be/../gensrc/build -isystem /Programs/doris/thirdparty/installed/include -isystem /Programs/doris/thirdparty/installed/gperftools/include -O0 -fsanitize=address -DADDRESS_SANITIZER  -std=gnu++20   -D OS_LINUX -g -Wall -Wextra -Werror -pthread -fstrict-aliasing -fno-omit-frame-pointer -Wnon-virtual-dtor -Wno-unused-parameter -Wno-sign-compare -fdiagnostics-color=always -Wno-nonnull -Wno-stringop-overread -Wno-stringop-overflow -D__STDC_FORMAT_MACROS -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX=1 -DBRPC_ENABLE_CPU_PROFILER -DS2_USE_GFLAGS -DS2_USE_GLOG -msse4.2 -mavx2 -DUSE_MEM_TRACKER -DUSE_JEMALLOC -DENABLE_STACKTRACE -gdwarf-5 -MD -MT src/vec/CMakeFiles/Vec.dir/common/format_ip.cpp.o -MF src/vec/CMakeFiles/Vec.dir/common/format_ip.cpp.o.d -o src/vec/CMakeFiles/Vec.dir/common/format_ip.cpp.o -c /Programs/doris/be/src/vec/common/format_ip.cpp
In file included from /Programs/doris/be/src/vec/common/format_ip.cpp:21:
/Programs/doris/be/src/vec/common/format_ip.h:34:19: error: 'array' in namespace 'std' does not name a template type
   34 | extern const std::array<std::pair<const char*, size_t>, 256> one_byte_to_string_lookup_table;
      |                   ^~~~~
/Programs/doris/be/src/vec/common/format_ip.h:26:1: note: 'std::array' is defined in header '<array>'; did you forget to '#include <array>'?
   25 | #include <utility>
  +++ |+#include <array>
   26 |
/Programs/doris/be/src/vec/common/format_ip.h:56:24: error: 'uint8_t' has not been declared
   56 |                        uint8_t mask_tail_octets = 0, const char* mask_string = "xxx") {
      |                        ^~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h: In function 'void doris::vectorized::formatIPv4(const unsigned char*, size_t, char*&, int, const char*)':
/Programs/doris/be/src/vec/common/format_ip.h:66:9: error: 'uint8_t' was not declared in this scope
   66 |         uint8_t value = 0;
      |         ^~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h:26:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   25 | #include <utility>
  +++ |+#include <cstdint>
   26 |
/Programs/doris/be/src/vec/common/format_ip.h:68:13: error: 'value' was not declared in this scope
   68 |             value = static_cast<uint8_t>(src[IPV4_BINARY_LENGTH - octet - 1]);
      |             ^~~~~
/Programs/doris/be/src/vec/common/format_ip.h:68:33: error: 'uint8_t' does not name a type
   68 |             value = static_cast<uint8_t>(src[IPV4_BINARY_LENGTH - octet - 1]);
      |                                 ^~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h:68:33: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
/Programs/doris/be/src/vec/common/format_ip.h:70:13: error: 'value' was not declared in this scope
   70 |             value = static_cast<uint8_t>(src[octet]);
      |             ^~~~~
/Programs/doris/be/src/vec/common/format_ip.h:70:33: error: 'uint8_t' does not name a type
   70 |             value = static_cast<uint8_t>(src[octet]);
      |                                 ^~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h:70:33: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
/Programs/doris/be/src/vec/common/format_ip.h:71:15: error: 'uint8_t' does not name a type
   71 |         const uint8_t len = one_byte_to_string_lookup_table[value].second;
      |               ^~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h:71:15: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
/Programs/doris/be/src/vec/common/format_ip.h:72:27: error: 'one_byte_to_string_lookup_table' was not declared in this scope
   72 |         const char* str = one_byte_to_string_lookup_table[value].first;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Programs/doris/be/src/vec/common/format_ip.h:72:59: error: 'value' was not declared in this scope
   72 |         const char* str = one_byte_to_string_lookup_table[value].first;
      |                                                           ^~~~~
/Programs/doris/be/src/vec/common/format_ip.h:74:26: error: 'len' was not declared in this scope; did you mean 'mblen'?
   74 |         memcpy(dst, str, len);
      |                          ^~~
      |                          mblen
/Programs/doris/be/src/vec/common/format_ip.h: At global scope:
/Programs/doris/be/src/vec/common/format_ip.h:90:62: error: 'uint8_t' has not been declared
   90 | inline void formatIPv4(const unsigned char* src, char*& dst, uint8_t mask_tail_octets = 0,
      |                                                              ^~~~~~~
[4/6] Building CXX object src/vec/CMakeFiles/Vec.dir/functions/function_ip.cpp.o
ninja: build stopped: subcommand failed.
```

### What You Expected?

Build BE successfully.

### How to Reproduce?

Build the codebase by GCC-13

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Issue Number: close #21214

Add missing headers to fix the compilation errors reported by GCC-13.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.96 seconds
 stream load tsv:          462 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          68.6 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230627063523_clickbench_pr_168516.html

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
