### PR TITLE
[test]Add regression test method for agg function

### PR DESCRIPTION
**Pull request by FreeOnePlus**
This PR mainly completes the regression test case of the agg function

# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
Please update title follow [commit format spec](https://doris.apache.org/community/how-to-contribute/commit-format-specification.html) and enrich commit log

**Comment by zy-kkk** [comment]
Don't forget to put [test] in front of the title

**Comment by FreeOnePlus** [comment]
> 不要忘记在标题前加上 [test]

Title modification completed

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
