### PR TITLE
[case](regression) using load_parallelism when load csv and json from s3

### PR DESCRIPTION
**Pull request by HowardQin**
use load_parallelism = 3 when loading csv and json from S3, so file will be separated

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
