### PR TITLE
[Document]Add note for workload group when upgrade Doris

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

Add note for workload group when upgrade Doris.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]

**Pull request merged**
