### PR TITLE
[fix](parquet) fix parquet reader missing column and filter missing column

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

follow https://github.com/apache/doris/pull/35583, fix parquet reader.

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
Need to add cases

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
