### PR TITLE
[Enhance](regression) add hms catalog broker scan case

### PR DESCRIPTION
**Pull request by WinkerDu**
## Proposed changes

add regression case for #24830 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
cc @morningman @chenlinzhong @luozenglin , please take a review, thank you :)

**Review by morningman — APPROVED** [review]
LGTM

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
