### PR TITLE
[performance](load) improve memtable sort performance

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Improve cache friendliness by sorting memtable column by column.
And use `pdqsort` to replace `std::sort`.

### result

Profile of insert into 1 tablet, 3 replicas 7.5G per tablet
SQL: `INSERT INTO dup/uniq SELECT * FROM dup2`

| target table | before | after |
| --- | --- | --- |
| unique | MemTableSortTime:  13s375ms<br>MemTableSortTimes:  56<br>MemTableSortTime:  14s499ms<br>MemTableSortTimes:  56<br>MemTableSortTime:  13s404ms<br>MemTableSortTimes:  56 | MemTableSortTime:  7s79ms<br>MemTableSortTimes:  56<br>MemTableSortTime:  7s523ms<br>MemTableSortTimes:  56<br>MemTableSortTime:  7s123ms<br>MemTableSortTimes:  56 |
| duplicate | MemTableSortTime:  35s384ms<br>MemTableSortTimes:  53<br>MemTableSortTime:  34s124ms<br>MemTableSortTimes:  53<br>MemTableSortTime:  33s740ms<br>MemTableSortTimes:  53 | MemTableSortTime:  7s992ms<br>MemTableSortTimes:  53<br>MemTableSortTime:  7s923ms<br>MemTableSortTimes:  53<br>MemTableSortTime:  8s439ms<br>MemTableSortTimes:  53 |

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
