### PR TITLE
[vectorized](bug) fix some open enable_fold_constant_by_be failed cases

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes
when set enable_fold_constant_by_be = true
some cases of P0 will be failed, this pr fix some about BE, eg:
`SELECT CAST('null' AS JSONB)` 
`select cast ('2022-12-02 22:23:24.999999' as datetimev2(3))` 
`SELECT repeat(\"a\", 3)` 
`select version()` 
`select cast(19888.8999999 as decimal(12,2))` 

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
