### PR TITLE
[fix](multi-catalog) check properties when alter catalog

### LINKED ISSUE #19379: [Bug] When user change the properties of the catalog, doris doesn't do the checks
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

When I create a catalog, **doris will check my properties**, for example, the hive type will check whether the properties of dfs.ha.namenodes exist.However, when I want to modify the catalog's properties, and the properties of this dfs.ha.namenodes does not exist, **doris does not do the check**.
**The first picture** below is that I created a normal catalog, and then deliberately modified the parameters, so that `'dfs.ha.namenodes.HANN' = ''`, doris do not checks the properties.
**The second picture** below is that I created an abnormal catalog, so that` 'dfs.ha.namenodes.HANN' = ''`, but doris checks the properties
error2

error1

### What You Expected?

I think doris should also make a properties check when **modifying** properties as it did when **creating** them

### How to Reproduce?

Create a catalog first,the sql is
``` sql
CREATE CATALOG hive1 PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='nn1,nn2',
    'dfs.namenode.rpc-address.HANN.nn1'='nn1_host:rpc_port',
    'dfs.namenode.rpc-address.HANN.nn2'='nn2_host:rpc_port',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```
and update it 
``` sql
ALTER CATALOG hive1 SET PROPERTIES  (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```
------
and create a catalog again
``` sql
CREATE CATALOG hive2 PROPERTIES (
    'type'='hms',
    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',
    'dfs.nameservices'='HANN',
    'dfs.ha.namenodes.HANN'='',
    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
);
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by q763562998**
# Proposed changes

Issue Number: close #19379

## Problem summary
When we were altering the catalog, we did not verify the new parameters of the catalog, and now we have added verification
My changes：
When We are altering the catalog, I have carried out a full inspection, and if an exception occurs, the parameters will be rolled back

## Checklist(Required)
1. Does it affect the original behavior:
   -  No
2. Has unit tests been added:
   -  No
3. Has document been added or modified:
   -  No
4. Does it need to update dependencies:
   -  No
5. Are there any changes that cannot be rolled back:
   -  No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.36 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17164143331 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by wsjz — APPROVED** [review]
LGTM

**Pull request merged**
