### PR TITLE
[chore](autobucket) add autobucket test and log

### PR DESCRIPTION
**Pull request by yujun777**
We met unexpect autobucket case for online env. Add log for  investigation.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
