### PR TITLE
[fix](inverted index) Fix key column match query failed

### PR DESCRIPTION
**Pull request by Tanya-W**
# Proposed changes

Issue Number: close (https://github.com/apache/doris/issues/18435)

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Review by xiaokang — COMMENTED** [review]
add a testcase

**Comment by Tanya-W** [comment]
run buildall

**Comment by Tanya-W** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
