### PR TITLE
[security] Remove sensitive information from the code.

### PR DESCRIPTION
**Pull request by lide-reed**
## Proposed changes

Remove sensitive information from the code.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]

**Comment by lide-reed** [comment]
run buildall

**Comment by lide-reed** [comment]
run buildp0

**Comment by lide-reed** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by lide-reed** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by lide-reed** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Pull request closed without merging**
