### PR TITLE
[fix](cloud) fix chose cloud cluster order

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by deardeng** [comment]
https://github.com/selectdb/selectdb/commit/ae25f2eb00f4ed2aba54ef2a61287b8fb5df6434

choose way 建议改成和现在dev一样的方式

**Review by luwei16 — APPROVED** [review]

**Comment by luwei16** [comment]
LGTM

**Comment by yujun777** [comment]
run p0

**Pull request merged**
