### PR TITLE
[chore] Use info level in recordCreatePartitionFailedMsg() due to intersection happens all the time

### PR DESCRIPTION
**Pull request by gavinchou**
image

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
