### PR TITLE
[Enhancement] (nereids)implement RecoverCommand in nereids

### LINKED ISSUE #42550: [Enhancement] (nereids)implement RecoverCommand in nereids
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

recover command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following use command in nereids:
- [x] https://github.com/apache/doris/issues/42544
- [x] https://github.com/apache/doris/issues/42545
- [x] https://github.com/apache/doris/issues/42547

This pr https://github.com/apache/doris/pull/41913 implemented Set Command in nereids. Although it's a little complex than this one, it can be a reference

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #42550 

Support recover table and recover partition  command in nereids.
https://github.com/apache/doris/issues/42550
https://github.com/apache/doris/issues/42545
https://github.com/apache/doris/issues/42547

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ *] Regression test //added
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
