### PR TITLE
[Fix](Variant) casting to decimal type may lost precision and scale when _normalize_predicate

### PR DESCRIPTION
**Pull request by eldenmoon**
use TypeDescriptor to prevent from info lost

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
