### PR TITLE
[refactor](datatype)delete useless code in datatype and fix push_number func

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
1. delete useless code
2. change push_bumber to push_number
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run p0

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
