### PR TITLE
[Opt](pipeline) disable coloagg when the para instance num >= tablet_num * 2

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

opt pipeline exec performance in 1 tablet ckbench:

before:
```
mysql> set enable_pipeline_engine = false;                                                                                                                                                    Query OK, 0 rows affected (0.00 sec)

mysql> SELECT UserID, COUNT(*) FROM hits GROUP BY UserID ORDER BY COUNT(*) DESC LIMIT 10;
+---------------------+----------+
| UserID              | count(*) |
+---------------------+----------+
| 1313338681122956954 |    29097 |
| 1907779576417363396 |    25333 |
| 2305303682471783379 |    10597 |
| 7982623143712728547 |     7584 |
| 6018350421959114808 |     6678 |
| 7280399273658728997 |     6411 |
| 1090981537032625727 |     6197 |
| 5730251990344211405 |     6019 |
|  835157184735512989 |     5211 |
|  770542365400669095 |     4906 |
+---------------------+----------+
10 rows in set (3.40 sec)
```

after:
```
mysql> SELECT UserID, COUNT(*) FROM hits GROUP BY UserID ORDER BY COUNT(*) DESC LIMIT 10;
+---------------------+----------+
| UserID              | count(*) |
+---------------------+----------+
| 1313338681122956954 |    29097 |
| 1907779576417363396 |    25333 |
| 2305303682471783379 |    10597 |
| 7982623143712728547 |     7584 |
| 6018350421959114808 |     6678 |
| 7280399273658728997 |     6411 |
| 1090981537032625727 |     6197 |
| 5730251990344211405 |     6019 |
|  835157184735512989 |     5211 |
|  770542365400669095 |     4906 |
+---------------------+----------+
10 rows in set (0.58 sec)

```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.91 seconds
 stream load tsv:          473 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          75 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          33 seconds loaded 861443392 Bytes, about 24 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230322221734_clickbench_pr_118974.html

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
