### PR TITLE
[ci](perf) print running pipeline tasks to debug

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

1. print running pipeline tasks to debug
2. fix the bug of deploy when the previous meta changed PR has run build on the same machine

### CODE REVIEW

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
