### PR TITLE
[fix](move-memtable) fix bvar g_load_stream_file_writer_cnt

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Previously the bvar `g_load_stream_file_writer_cnt` is not accurate when error happens.
Some `FileWriters` are not supposed to be closed manually.

All `FileWriter` in `LoadStreamWriter` is managed by `std::unique_ptr`.
A `FileWriter` should be able to close itself and cleanup storage state on its deconstructor.

This PR changes the bvar `g_load_stream_file_writer_cnt` to track deconstruction of `FileWriter`,
instead of tracking `FileWriter` close.

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
