### PR TITLE
[Bugfix](CCR) BinlogTombstone tableId is null when db disable binlog

### PR DESCRIPTION
**Pull request by deadlinefen**
Bug:  
BinlogTombstone tableId is null when db disable binlog.  
  
Bugfix:  
Added a new constructor for BinlogTombstome, which sets BinlogTombstome.tableId to an ArrayList that only contains the current tableId when db binlog is disabled.

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Review by JackDrogon — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
