### PR TITLE
[fix](followup) Stop tasks if waken by downstream tasks

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Follow-up : #41292

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Review by Mryange — APPROVED** [review]

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
