### PR TITLE
[fix](index) bitmap and bloomfilter index should not do light index change

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

cherry pick https://github.com/apache/doris/pull/35214 to branch-2.1

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
