### PR TITLE
[log](statistics)Add result row count log for statistics internal query.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add result row count log for statistics internal query.
Change some log level to debug to reduce log size.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run feut

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
