### PR TITLE
[chore](macOS) Fix SSL errors while building documents

### LINKED ISSUE #23126: [Bug] ERR_OSSL_EVP_UNSUPPORTED errors occur while building documents
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris: master
OS: macOS 13.5
nodejs: 20.5.1

### What's Wrong?

```shell
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Programs/doris/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Programs/doris/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Programs/doris/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Programs/doris/ui/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Programs/doris/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /Programs/doris/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/Programs/doris/ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Programs/doris/ui/node_modules/cache-loader/dist/index.js:240:7
    at /Programs/doris/ui/node_modules/neo-async/async.js:2830:7
    at done (/Programs/doris/ui/node_modules/neo-async/async.js:2865:11)
    at /Programs/doris/ui/node_modules/neo-async/async.js:2818:7
    at /Programs/doris/ui/node_modules/cache-loader/dist/index.js:229:9
    at /Programs/doris/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.1
```

### What You Expected?

Build documents successfully.

### How to Reproduce?

```
./build.sh --fe --clean
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Issue Number: close #23126

Add `NODE_OPTIONS` to fix this issue.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.08 seconds
 stream load tsv:          543 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162244380 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.99 seconds
 stream load tsv:          543 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162381881 Bytes

**Comment by adonis0147** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.89 seconds
 stream load tsv:          540 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.6 seconds inserted 10000000 Rows, about 337K ops/s
 storage size: 17162261071 Bytes

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by HonestManXin — APPROVED** [review]

**Pull request merged**
