### PR TITLE
[fix](local shuffle) Not channel_id causes a local merge infinite loop.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

```
LOCAL_EXCHANGE_OPERATOR (LOCAL_MERGE_SORT): id=-4, parallel_tasks=24, _channel_id: 0, _num_partitions: 24, _num_senders: 24, _num_sources: 24, _running_sink_operators: 24, _running_source_operators: 1, mem_usage: 0, data queue info: Data Queue 0: [size approx = 1656, eos = false], MemTrackers: 0: 135659520, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 
  DATA_STREAM_SINK_OPERATOR: id=3, Sink Buffer: (_should_stop = false, _busy_channels = 0, _is_finishing = false), _reach_limit: false
0.   this=0x7f9100dbca10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=false, _always_ready=false
0.   this=0x7f9100dbf910, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dc1910, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dc6c10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dc8810, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dc9d10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dd5e10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de0310, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de3210, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de3910, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de3b10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de3d10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de3f10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de5910, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100de9b10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100dea910, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
0.   this=0x7f9100debf10, LOCAL_MERGE_EXCHANGE_OPERATOR_DEPENDENCY: id=-4, block task = 0, ready=true, _always_ready=false
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — COMMENTED** [review]
remove default param to prevent the problem and check p2 case to prevent the bug

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run cloud_p1

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
