### PR TITLE
[feature](nereids) judge if the join is at bottom of join cluster

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
set width property in stats to indicate how many relations are joined under a plan node

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run feut

**Review by starocean999 — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
