### PR TITLE
[fix](hudi)Add hudi catalog read partition table partition prune

### PR DESCRIPTION
**Pull request by hubgeter**
### What problem does this PR solve?
Problem Summary:
In the previous PR #41218, some partition pruning logic was changed, which caused the hudi partition pruning to fail. This PR is to fix this problem.

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Comment by hubgeter** [comment]
wait me test `use_hive_sync_partition = false` in hudi 0.15

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
> wait me test `use_hive_sync_partition = false` in hudi 0.15

done. append test : `use_hive_sync_partition = false/true`

**Review by morningman — APPROVED** [review]

**Review by suxiaogang223 — APPROVED** [review]
+1

**Pull request merged**
