### PR TITLE
[Chore](build) adjust build script about pch setting

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

try to make be-ut workflow stable

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
