### PR TITLE
[fix](insert)fix conversion of doris type to hive type

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

#31442

create table
fix doris to hive type, use primitiveType to check doris type.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run p0

**Review by morningman — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
