### PR TITLE
[improvement](pipeline)Avoid duplicate trigger teamcity build

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
# Proposed changes

Describe your changes.
1 . simplify auto trigger code
2.  avoid repeated triggers

## Checklist(Required)

* [ no ] Does it affect the original behavior
* [ no ] Has unit tests been added
* [ no ] Has document been added or modified
* [ no ] Does it need to update dependencies
* [ yes ] Is this PR support rollback (If NO, please explain WHY)

## Further comments
There are a lot of changes, and although it has been well tested locally, there is still a risk of rollback。

### CODE REVIEW

**Review by zhangguoqiang666 — COMMENTED** [review]
it is checked

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run compile

**Pull request merged**
