### PR TITLE
[fix](clone) fix calculate merge missing version

### PR DESCRIPTION
**Pull request by yujun777**
BUG:  when calculate missing version,  the snapshot need single versions.  For example,  if missing version 4 ~ 6,  the missing version should be [4, 4], [5, 5], [6, 6]. But pr #30128 merge missing versions,  it will give [4, 6],  then clone will be fail.

FIX:  don't merge missing versions.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
