### PR TITLE
[improvement](shutdown) not print thread pool error stack trace when shutdown

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

1. when thread pool shutdown, should not print error stack trace, it is very confuse.
2. arrow flight server should not call shutdown, if it is not enabled, because it will print error stack.
3. remove service unavailable from thrift because it is useless.

Part of this PR need to pick to 2.0 branch.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
