### PR TITLE
[Bug](iceberg)fix read partitioned iceberg without partition path

### LINKED ISSUE #23014: Do not use columnsFromPath for Iceberg
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0 trunk 

### What's Wrong?

The code is attempting to parse partition column values from the filepath but in Iceberg there is no requirement for anything to be present in the path and it should instead be retrieved from the Iceberg scan.

### What You Expected?

Query a partitioned iceberg table e.g. partitioned by hour transform on ts column.

Doris will look for a ts_hour= in the path. If the path does not contain it, it will throw an error. 

Failed to parse columnFromPath ...

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Issue Number: close #23014

Iceberg does not require partition values to exist on file paths, so we should get the partition value from `PartitionScanTask.partition`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run external

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
