### PR TITLE
[Optimize](function) Optimize locate function by compare across strings

### PR DESCRIPTION
**Pull request by ZhangYu0123**
## Proposed changes
Optimize locate function by compare across strings.   about 90% speed up test by sum()

before:
image

after:
image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
