### PR TITLE
[Bug](join) corner case cause the mark join + null aware left join core dump in regression test in pipeline query engine

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Issue Number: close #24804 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
run buildall

**Pull request merged**
