### PR TITLE
[fix](udf)java udf does not support overloaded evaluate method

### PR DESCRIPTION
**Pull request by whutpencil**
## Proposed changes

Issue Number: https://github.com/apache/doris/issues/22680

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please add a regression test for this case

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
cc @Gabriel39 PTAL

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.61 seconds
 stream load tsv:          549 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162007268 Bytes

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by whutpencil** [comment]
@morningman @Gabriel39 Sorry, there was a problem with the test case I wrote earlier, and I have fixed it. Could you please review it again

**Review by morningman — DISMISSED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run  buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.56 seconds
 stream load tsv:          514 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162412359 Bytes

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.6 seconds
 stream load tsv:          535 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162068299 Bytes

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by wm1581066** [comment]
run buildall

**Comment by morningman** [comment]
run buidall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
