### PR TITLE
[fix](schemachange) Avoid drop index in checking compatibility mode and checkpoint thread

### PR DESCRIPTION
**Pull request by w41ter**
`dropIndex` is an RPC request in the cloud mode.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
