### PR TITLE
[feature](restore) Add thrift RestoreSnapshotRequest support table alias

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add thrift RestoreSnapshotRequest support table alias

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Review by deadlinefen — COMMENTED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Pull request merged**
