### PR TITLE
[docs](doc) Add docs for Apache Kyuubi

### PR DESCRIPTION
**Pull request by bowenliang123**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Add documents for Apache Kyuubi in the ecosystem catalog.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by bowenliang123** [comment]
cc @zhaomin1423

**Comment by bowenliang123** [comment]
run buildall

**Review by zhaomin1423 — APPROVED** [review]
LGTM， thanks bowen.

**Comment by bowenliang123** [comment]
> LGTM， thanks bowen.

Thanks for the review. The credit comes to @zhaomin1423 as most parts of these docs for Kyuubi are from [his article](https://mp.weixin.qq.com/s/bvPolsDRlZiKeoB2OT7siQ) on Apache Kyuubi's Wechat site.

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run build all

**Review by luzhijing — APPROVED** [review]

**Comment by luzhijing** [comment]
run P0

**Comment by bowenliang123** [comment]
It seems the new-added kyuubi page is shown on the website at all, neither on the sidebar nor in search results. Is there any other steps or modification required to do?

**Pull request merged**
