### PR TITLE
[Fix](Nereids) TopN should forbid two-phase topN if child is DistributionSpecGather

### PR DESCRIPTION
**Pull request by xiedeyantu**
## Proposed changes

TopN should forbid two-phase topN if child is DistributionSpecGather.

### CODE REVIEW

**Review by keanji-x — DISMISSED** [review]

**Review by morrySnow — COMMENTED** [review]
add case please

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run p0

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run p0

**Review by morrySnow — DISMISSED** [review]

**Comment by xiedeyantu** [comment]
run buildall

**Comment by xiedeyantu** [comment]
run buildall

**Review by keanji-x — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
