### PR TITLE
[fix](memory) Modified low water mark=min(6.4G, MemTotal * 5%)

### PR DESCRIPTION
**Pull request by xinyiZzz**
On 64G machine, warning water mark is 12.8G. when system available memory reaches the warning water mark, load memtable will flush, this is not a good idea.

`mem_limit` default 10%, except for the memory used by the Linux kernel , buffer may be around 5%, so low water mark=min(6.4G, MemTotal * 5%) looks better.

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
