### PR TITLE
[Only-Test-P0](fold_constant) add defer in fold constant to close

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes
`when set this.enableFoldConstantByBe = true; 
and doing prepare work will return error for some reason, eg: can't find function in BE.
    so will return directly without call close function.`
Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.93 seconds
 stream load tsv:          484 seconds loaded 74807831229 Bytes, about 147 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          68 seconds loaded 1101869774 Bytes, about 15 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230209115555_clickbench_pr_93058.html

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run P0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Pull request closed without merging**
