### PR TITLE
[opt](nereids) add dphyper limit configuration

### PR DESCRIPTION
**Pull request by xzj7019**
## Proposed changes

Issue Number: close #xxx

Make dphyper limit configurable.

### CODE REVIEW

**Comment by xzj7019** [comment]
run buildall

**Comment by xzj7019** [comment]
run p0

**Comment by xzj7019** [comment]
run feut

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Comment by englefly** [comment]
run cloud_p1

**Pull request merged**
