### PR TITLE
[feature](function)support bit_test function

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
support bit_test function
doc: https://github.com/apache/doris-website/pull/1214

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Pull request merged**
