### PR TITLE
[doc](fix)Fix table typo in star schema benchmark documentation and join optimization

### PR DESCRIPTION
**Pull request by neuyilan**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by neuyilan** [comment]
@xinyiZzz Could you please review it

**Comment by neuyilan** [comment]
@luzhijing Could you please review it

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
> @luzhijing Could you please review it

So sorry for late review and thank you for your contribution.

**Comment by luzhijing** [comment]
Please rebase the code.

**Comment by neuyilan** [comment]
> Please rebase the code.

Thanks for reviewing the code, and I have been rebasing the latest master codes.

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Comment by neuyilan** [comment]
@luzhijing @morrySnow Thanks for reviewing it, maybe we can merge this PR now.

**Pull request merged**
