### PR TITLE
[enhancement](err-msg) Output column info when size invalid in block data convertor

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
