### PR TITLE
[docs] (DebugPoints) Update docs about Debug Points

### PR DESCRIPTION
**Pull request by HowardQin**
Update docs about Debug Points

### CODE REVIEW

**Comment by freemandealer** [comment]
well done @HowardQin    would you please also add dbg point usage for regression tests?

**Comment by HowardQin** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HowardQin** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
Lgtm

**Pull request merged**
