### PR TITLE
[fix](auth)fix show routine load db is null

### PR DESCRIPTION
**Pull request by zddr**
fix 

- when label contains dbName, will loss
cause by: #27861

- `show routine load for xxx.yyy` can export authentication error
cause #33347

Note: Cases will be added uniformly in other PRs

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a regression test.

**Comment by zddr** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by morrySnow — DISMISSED** [review]

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
