### PR TITLE
[typo](docs)optimize docker image building script and document

### PR DESCRIPTION
**Pull request by figurant**
1. print init_be.log in entry_point.sh
2.optimize document of docker image build

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
Please modify your PR title, which should follow the format of the following link~
https://doris.apache.org/community/how-to-contribute/commit-format-specification

**Comment by FreeOnePlus** [comment]
Please modify your PR title, which should follow the format of the following link~
https://doris.apache.org/community/how-to-contribute/commit-format-specification

**Review by hf200012 — DISMISSED** [review]
LGTM

**Comment by figurant** [comment]
@FreeOnePlus modified the log path，used ${doris_home}

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by zy-kkk** [comment]
please rebase your branch to master

**Pull request closed without merging**
