### PR TITLE
[optimize](desc) display the correct data type of aggStateType

### PR DESCRIPTION
**Pull request by DarvenDuan**
If a table column is AGG_STATE type, we can't get the clear defined data type if we use `desc tbl` statement.

```sql
create table a_table(
    k1 int null,
    k2 agg_state<max_by(int not null,int)> generic,
    k3 agg_state<group_concat(string)> generic
)
aggregate key (k1)
distributed BY hash(k1) buckets 3
properties("replication_num" = "1");
```

before optimize:
```
mysql> desc a_table;
+-------+------------------------------------------------+------+-------+---------+---------+
| Field | Type                                           | Null | Key   | Default | Extra   |
+-------+------------------------------------------------+------+-------+---------+---------+
| k1    | INT                                            | Yes  | true  | NULL    |         |
| k2    | org.apache.doris.catalog.AggStateType@239f771c | No   | false | NULL    | GENERIC |
| k3    | org.apache.doris.catalog.AggStateType@2e535f50 | No   | false | NULL    | GENERIC |
+-------+------------------------------------------------+------+-------+---------+---------+
3 rows in set (0.00 sec)
```

after optimize:
```
mysql> desc a_table;
+-------+------------------------------------+------+-------+---------+---------+
| Field | Type                               | Null | Key   | Default | Extra   |
+-------+------------------------------------+------+-------+---------+---------+
| k1    | INT                                | Yes  | true  | NULL    |         |
| k2    | AGG_STATE<max_by(INT, INT NULL)>   | No   | false | NULL    | GENERIC |
| k3    | AGG_STATE<group_concat(TEXT NULL)> | No   | false | NULL    | GENERIC |
+-------+------------------------------------+------+-------+---------+---------+
```

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run buildall

**Review by caiconghui — APPROVED** [review]
LGTM

**Review by GoGoWen — APPROVED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
could u replace screenshot by code block? screeshot is hard to put into git message and not firendly for search engine

**Comment by DarvenDuan** [comment]
> could u replace screenshot by code block? screeshot is hard to put into git message and not firendly for search engine

OK, I modified my comment.

**Pull request merged**
