### PR TITLE
[pipeline](opt) Opt fragment instance prepare performance by thread pool

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

SSB Q4.1 empty set only test prepare performance：16 instance

before：
img_v2_21cbeaa9-5ecb-41a0-b450-cfa01026b1ag

after：
img_v2_0fb4cb01-26f9-41fe-b729-c2bb32c0c72g

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Comment by Gabriel39** [comment]
This is a temporary solution. We plan to do the overall refactor in future to reduce the overhead by preparation

**Pull request merged**
