### PR TITLE
[fix](polixy)support drop policy for user or role

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

support `DROP ROW POLICY test_row_policy_1 on table1 [FOR user| ROLE role]`

`row policy name`,`tableName` and `user or role` as a whole unique identifiers

change `KW_SHOW KW_ROW KW_POLICY KW_FOR KW_ROLE STRING_LITERAL:role` to `KW_SHOW KW_ROW KW_POLICY KW_FOR KW_ROLE ident:role`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run pipelinex_p0

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
