### PR TITLE
[fix](insert) fix txn error reason clearly

### LINKED ISSUE #16503: [Bug] [daily] insert transaction commit failed, error msg should be more friendly
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master: doris-0.0.0-trunk-cf18de1

### What's Wrong?

jenkins failed case:
https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/201/testReport/(root)/test_sys_insert_txn/test_txn_drop_tb/

image

### What You Expected?

error msg should not be: [ok]

### How to Reproduce?

1. connection a:  begin and insert data
2. connection b:  drop table
3. connection a: commit,  commit failed 

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #16503

## Problem summary

will get txn reason like "ERROR 1105 (HY000): errCode = 2, detailMessage = errCode = 2, detailMessage = [ANALYSIS_ERROR]errCode = 7, detailMessage = unknown table, tableName=A"

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
./run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.66 seconds
 stream load tsv:          467 seconds loaded 74807831229 Bytes, about 152 MB/s
 stream load json:         39 seconds loaded 2358488459 Bytes, about 57 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          27 seconds loaded 861443392 Bytes, about 30 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230223075010_clickbench_pr_102435.html

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run P0

**Review by xy720 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
