### PR TITLE
[chore](fe) Add some important information in fe log for debug

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
* Add git commit info in fe.log/fe.out when fe start
* Add `metadata recovery mode` log in fe.log/fe.out
* Add bdb journal info in fe.log when size over `1M`

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — CHANGES_REQUESTED** [review]
-v does not work any more.

**Comment by SWJTU-ZhangLei** [comment]
> -v does not work any more.
```
 // pid file
 if (!cmdLineOpts.isVersion() && !createAndLockPidFile(pidDir + "/fe.pid")) {
     throw new IOException("pid file is already locked.");
 }
```
-v option still work

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
