### PR TITLE
[fix](profile) Fix print profile in be log

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
1. Fix stream load does not set enabel_profile correctly.
2. Fix pipeline X print profile in be.INFO failed.

Original: https://github.com/apache/doris/pull/31198

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Comment by liaoxin01** [comment]
run p0

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
