### PR TITLE
[fix](nereids)support group_concat with distinct and order by

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes

This pr support group_concat with distinct and order by. So we can support sql like bellow:
```
select group_concat(distinct x order by y) from t;
select multi_distinct_group_concat(x order by y) from t;
```

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
