### PR TITLE
[feature-wip][multi-catalog]Support caseSensitive field name in file scan node

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:
Spark support upper case column name and the column name will persist in parquet and orc.
But the hms table only record the lower case column name, so it need to support read the  upper case column in file.
In file scan node, it's not caseSensitive, col_a and Col_a is the same column.
In broker scan node, it's caseSensitive, col_a and Col_a is not the same column.

Create table in spark 
```sql
CREATE TABLE `default`.`emp3` (
  `Name` STRING,
  `AGE` INT,
  `provice` STRING,
  `City` STRING)
USING parquet
PARTITIONED BY (City)
TBLPROPERTIES (
  'transient_lastDdlTime' = '1658550652')
```

doris result
```sql
MySQL [default]> select * from emp3;
+------+------+---------+------+
| name | age  | provice | city |
+------+------+---------+------+
| a    |    1 | zj      | hz   |
+------+------+---------+------+
1 row in set (1.492 sec)
```

## Checklist(Required)

1. Type of your changes:
    - [ ] Improvement
    - [ ] Fix
    - [x] Feature-WIP
    - [ ] Feature
    - [ ] Doc
    - [ ] Refator
    - [ ] Others: 
2. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by stalary — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by SaintBacchus** [comment]
@morningman @stalary I had rebase this pr

**Review by stalary — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
