### PR TITLE
[improve](cloud) make tablet sync_rowsets async to reduce calculating delete bitmap time

### PR DESCRIPTION
**Pull request by hust-hhb**
sync_rowsets may cost too much time, make  sync_rowsets async can reduce more than 90% times on calculating delete bitmap time in publish phase.

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by hust-hhb** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
