### PR TITLE
[feat](nereids)set actual row count in physical plan according to merged profile

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
physical plan is already printed in profile.
however, it is hard to compare the estimated rows of sql operator and the actual rows.
In this pr, we get actual rows from merged profile, and set it to corresponding physical node in physical plan.
here is an example:
"PhysicalHashJoin[13890]@115  (  stats=17,964.27  actualRows=20499,  type=INNER_JOIN,  hashCondition=[(l_suppkey#19  =  s_suppkey#33)]"
the estmated rows is 17,964, the actual rows is 20499
Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Comment by zhiqiang-hhhh** [comment]
Can we pick this pr to branch-3.0 ?

**Comment by englefly** [comment]
based on ##35144

**Comment by englefly** [comment]
> Can we pick this pr to branch-3.0 ?

YES

**Pull request merged**
