### PR TITLE
[Feature][MultiTableMV](Step1)Scheduler framework

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem summary
Metadata define for the job shcedule framework
image

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Hi @SaintBacchus , is this a common job-task scheduling framework? Or a specific framework for multi table mv?
If it is a common framework, better create an issue or DSIP to describe how it works can what it can do.
If it just for multi table mv, I think class name like `JobManager` and `Job` need to be more specific, eg: `MVJobManager`.

**Comment by SaintBacchus** [comment]
@morningman this job-task scheduling framework is almost for mv but it may also for asyn insert

**Comment by SaintBacchus** [comment]
JobManager -> MvJobManager and package name scheduler -> mv

**Comment by SaintBacchus** [comment]
元数据的对象前缀都加MV

**Comment by SaintBacchus** [comment]
JobManager -> MvJobManager

**Comment by SaintBacchus** [comment]
Close this and new impl in https://github.com/apache/doris/issues/13146

**Pull request closed without merging**
