### PR TITLE
[improvement](group commit) refector replay wal function

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
now be replaying wal by sending a http request, which is not reliable, change it to use stream load internal infector is a better way.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Pull request closed without merging**
