### PR TITLE
[Enhancement] (nereids)implement showGrantsCommand in nereids

### LINKED ISSUE #42766: [Enhancement] (nereids)implement showGrantsCommand in nereids
showGrants command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showGrants command in nereids:
unsupportedshowGrantsStatement
``` SHOW ALL? GRANTS                                                              ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #42766
#42767

Related PR: #xxx

Problem Summary:
implement showGrantsCommand and showGrantsForUserCommand in nereids
### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test // added
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run p0

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
