### PR TITLE
[improvement](statistics)Support external table show table stats, modify column stats and drop stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Issue Number: close #xxx

Support external table show table stats, modify column stats and drop stats.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Need to add some regression tests

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]
LGTM

**Pull request merged**
