### PR TITLE
[chore](cloud) Reflect the current working mode (cloud) in the `version_comment` session variable

### PR DESCRIPTION
**Pull request by yagagagaga**
Before：
```
mysql> show variables like '%version_comment%';
+-----------------+-------------------------------------------+-------------------------------------------+---------+
| Variable_name   | Value                                     | Default_Value                             | Changed |
+-----------------+-------------------------------------------+-------------------------------------------+---------+
| version_comment | Doris version doris-0.0.0-rc09-afb2dcca62 | Doris version doris-0.0.0-rc09-afb2dcca62 | 0       |
+-----------------+-------------------------------------------+-------------------------------------------+---------+
1 row in set (0.04 sec)
```

After：
```
mysql> show variables like '%version_comment%';
+-----------------+--------------------------------------------------------+-------------------------------------------------------+---------+
| Variable_name   | Value                                                  | Default_Value                                         | Changed |
+-----------------+--------------------------------------------------------+-------------------------------------------------------+---------+
| version_comment | Doris version doris-0.0.0-rc09-afb2dcca62 (Cloud mode) | Doris version doris-0.0.0-rc09-afb2dcca62 (Cloud Mode)| 0       |
+-----------------+--------------------------------------------------------+-------------------------------------------------------+---------+
1 row in set (0.04 sec)
```

### CODE REVIEW

**Comment by gavinchou** [comment]
run buidlall

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Comment by yagagagaga** [comment]
run p1

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run cloud_p1

**Comment by yagagagaga** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
