### PR TITLE
[typo](docs) Add a demo of export minio

### PR DESCRIPTION
**Pull request by yuanyuan8983**
## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run p0

**Pull request merged**
