### PR TITLE
[chore](compile) Improves PCH cache hit ratio

### PR DESCRIPTION
**Pull request by deadlinefen**
## Problem summary

1. Supplement the documentation of be-clion-dev, avoid the problem of undefined `DORIS_JAVA_HOME` and inability to find jni.h when using clion development without directly compiling through build.sh
2. Complete the classification of header files in pch.h and introduce some header files that are not frequently modified in doris.
3. Separate the declaration and definition in common/config.h. **If you need to modify the default configuration now, please modify it in common/config.cpp.**
4. gen_cpp/version.h is regenerated every time it is recompiled, which may cause PCH to fail, so now you need to get the version information indirectly rather than directly.

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.7 seconds
 stream load tsv:          427 seconds loaded 74807831229 Bytes, about 167 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230509142034_clickbench_pr_141156.html

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
