### PR TITLE
[fix](planner) Output is wrong when select from an inline view with constant expressions

### PR DESCRIPTION
**Pull request by adonis0147**
Co-authored-by: AKIRA <33112463+Kikyou1997@users.noreply.github.com>
Co-authored-by: xueweizhang <zxw520blue1@163.com>

# Proposed changes

Backport #16370 #16556 #16579 to branch-1.1-lts .

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
