### PR TITLE
[feature](function) support ip functions named to_ipv4[or_default, or_null](string) and to_ipv6[or_default, or_null](string)

### LINKED ISSUE #20584: [Enhancement] Add IP address process function for SQL like ClickHouse
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

ClickHouse support some [IP address process function](https://clickhouse.com/docs/zh/sql-reference/functions/ip-address-functions) for SQL. These are very useful for some network service cases.
Hope to add these function ASAP.Thanks.

### Solution

Add IP address process function for SQL like ClickHouse

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sjyango**
## Proposed changes

Issue Number: close #20584

- `to_ipv4`:  A function like `ipv4_string_to_num` that takes a string form of IPv4 address and returns value of IPv4 type, which is binary equal to value returned by `ipv4_string_to_num`. If the IPv4 address has an invalid format, throw an exception. 
- `to_ipv4_or_default`: Same as `to_ipv4`, but if the IPv4 address has an invalid format, it returns 0.0.0.0 (0 IPv4).
- `to_ipv4_or_null`: Same as `to_ipv4`, but if the IPv4 address has an invalid format, it returns null.
- `to_ipv6`: Converts a string form of IPv6 address to IPv6 type. If the IPv6 address has an invalid format, throw an exception. Similar to `ipv6_string_to_num` function, which converts IPv6 address to binary format.
- `to_ipv6_or_default`: Same as `to_ipv6`, but if the IPv6 address has an invalid format, it returns :: (0 IPv6).
- `to_ipv6_or_null`: Same as `to_ipv6`, but if the IPv6 address has an invalid format, it returns null.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run p0

**Comment by sjyango** [comment]
run p0

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by sjyango** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by sjyango** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
run buildall

**Comment by sjyango** [comment]
run feut

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
