### PR TITLE
[ci](test) support run sql convertor cases

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run cloud_p0

**Review by liujiwen-up — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
