### PR TITLE
[test](routine load) add routine load doc case

### PR DESCRIPTION
**Pull request by sollhui**
Add routine load doc case.

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Review by XuJianxu — APPROVED** [review]
LGTM

**Pull request merged**
