### PR TITLE
[test](regression) add cases for data quality error url

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Add regression tests to check url is returned when filtered rows in strict mode (data quality error).
Also fix some small bugs:
1. Error type returned when partition is not found (`END_OF_FILE` -> `DATA_QUALITY_ERROR`).
2. Unify status string format (`"[ERROR] message"` -> `"[ERROR]message"`)  

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
