### PR TITLE
[feature](invert index) add tokenizer CharFilter preprocessing

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

USING INVERTED PROPERTIES("parser" = "unicode", "char_filter_type" = "char_replace", "char_filter_pattern" = "._", 
 "char_filter_replacement" = " ")
 
char_replace: replace only char
char_filter_pattern: char array to replace
char_filter_replacement: need to replace the char

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run be

**Comment by zzzxl1993** [comment]
run ut

**Comment by zzzxl1993** [comment]
run beut

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by xiaokang — COMMENTED** [review]
add some testcase

**Comment by zzzxl1993** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
