### PR TITLE
[FIX](explode) fix explode with array<decimal> has specific precision at old planner

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by yiguolei — COMMENTED** [review]
please add regression test

**Comment by amorynan** [comment]
> please add regression test

done!

**Comment by amorynan** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
LGTM

**Comment by amorynan** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run pipelinex_p0

**Comment by amorynan** [comment]
run pipelinex_p0

**Comment by amorynan** [comment]
run pipelinex_p0

**Review by morrySnow — APPROVED** [review]

**Pull request closed without merging**
