### PR TITLE
[fix](schema change)support schema change operation between IPv4/IPv6 and VARCHAR/STRING/TEXT

### PR DESCRIPTION
**Pull request by sjyango**
## Proposed changes

Issue Number: close #xxx

Support schema change operations for IP and string types.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run compile

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run external

**Comment by dataroaring** [comment]
Is it a heavy schema change? Please add some cases after sc. e.g. ip related fuction.

**Pull request closed without merging**
