### PR TITLE
[fix](log) fix and clarify error msg for tablet writer write failure …

### PR DESCRIPTION
**Pull request by freemandealer**
…(#14078)

fmt::format dosen't support non-template object as args, even if it implements
`to_string()` or `operator<<`. so orignal code may cause `false` to be printed
instead of real cause of the failure. So to_string() need to be manually invoked.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
After apply this pr, the error output would be like:
```
"Message": "[INTERNAL_ERROR]cancelled: [INTERNAL_ERROR]tablet error: tablet writer write failed, tablet_id=10083, txn_id=2, err=[E-238], host: 127.0.0.1",
```

**Comment by freemandealer** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by freemandealer** [comment]
run beut p0 arm

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run p0

**Comment by ZhangGuoqiang666** [comment]
run p0

**Review by zhannngchen — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
TODO: merge this to 1.2lts after PR #14744  be merged

**Pull request merged**
