### PR TITLE
[test](nereids) Add some tests for PushFilterInsideJoin and FindHashC…

### PR DESCRIPTION
**Pull request by JingDas**
## Proposed changes

Add some test Instances for rewrite rule.

### CODE REVIEW

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by JingDas** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by xzj7019 — APPROVED** [review]

**Pull request merged**
