### PR TITLE
[Fix](inverted index) fix wrong opt for pk no need read data

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

The optimization to avoid reading data for primary keys (PK) in segment_iterator can lead to incorrect results when there are function expressions involving the same PK column in the predicate.

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
