### PR TITLE
[Shell] Add build parallel option

### PR DESCRIPTION
**Pull request by acelyc111**
## Proposed changes

Add build parallel option then we can build project with a user specified parallel not a fixed value.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by stdpain** [comment]
run-be-ut.sh also need this modify

**Comment by acelyc111** [comment]
> run-be-ut.sh also need this modify

Yes, I've modified it too.

**Comment by stdpain** [comment]
may be thirdparty/build-thirdparty.sh also parallel options

**Comment by acelyc111** [comment]
> may be thirdparty/build-thirdparty.sh also parallel options

Good idea, done.

**Review by morningman — COMMENTED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
