### PR TITLE
[bugfix](mergeprofile) ignore null profile to avoid bug

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Pull request merged**
