### PR TITLE
[HTTP][API] add backend by rest api

### PR DESCRIPTION
**Pull request by JNSimba**
## Proposed changes

At present, add backend can only be done through `alter system add backend "host:port"`, but when the cluster does not have Be, an error will be reported when executed through jdbc: **errCode = 2, detailMessage = candidate backends is empty**.
Therefore, I hope to add a way to add backend through restapi

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Is this new API for Doris manager?
Or just to resolve the problem "errCode = 2, detailMessage = candidate backends is empty."?

**Comment by hf200012** [comment]
> Is this new API for Doris manager?
> 
> Or just to resolve the problem "errCode = 2, detailMessage = candidate backends is empty."?

This is a new API for Doris manager. Because there is no be, there is no way to add be through the jdbc connection

**Comment by morningman** [comment]
> Because there is no be, there is no way to add be through the jdbc connection

I think this should be resolved by this PR #6150 ?

**Comment by hf200012** [comment]
> > Because there is no be, there is no way to add be through the jdbc connection
> 
> 
> 
> I think this should be resolved by this PR #6150 ?

In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?

**Comment by morningman** [comment]
> > > Because there is no be, there is no way to add be through the jdbc connection
> > 
> > 
> > I think this should be resolved by this PR #6150 ?
> 
> In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?

#6150 is included in 0.15, you can try it.

**Comment by hf200012** [comment]
> > > > Because there is no be, there is no way to add be through the jdbc connection
> 
> > > 
> 
> > > 
> 
> > > I think this should be resolved by this PR #6150 ?
> 
> > 
> 
> > In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?
> 
> 
> 
> #6150 is included in 0.15, you can try it.

Ok, then we also set it to 0.15 with the lowest version supported by doris manager

**Comment by JNSimba** [comment]
> > > > Because there is no be, there is no way to add be through the jdbc connection
> > > 
> > > 
> > > I think this should be resolved by this PR #6150 ?
> > 
> > 
> > In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?
> 
> #6150 is included in 0.15, you can try it.

Thank you very much, I  test with version 0.15.1-rc03 just now,  it's works to use jdbc to execute alter system add backend.

**Comment by morningman** [comment]
> > > > > Because there is no be, there is no way to add be through the jdbc connection
> > > > 
> > > > 
> > > > I think this should be resolved by this PR #6150 ?
> > > 
> > > 
> > > In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?
> > 
> > 
> > #6150 is included in 0.15, you can try it.
> 
> Thank you very much, I test with version 0.15.1-rc03 just now, it's works to use jdbc to execute alter system add backend.

So is this new API still necessary? If not, you can close it.

**Comment by JNSimba** [comment]
> > > > > > Because there is no be, there is no way to add be through the jdbc connection
> > > > > 
> > > > > 
> > > > > I think this should be resolved by this PR #6150 ?
> > > > 
> > > > 
> > > > In which version is this pr? Does that mean that this previous version was not available for doris manager? Or do we qualify the supported version?
> > > 
> > > 
> > > #6150 is included in 0.15, you can try it.
> > 
> > 
> > Thank you very much, I test with version 0.15.1-rc03 just now, it's works to use jdbc to execute alter system add backend.
> 
> So is this new API still necessary? If not, you can close it.

ok，i will close this

**Pull request closed without merging**
