### PR TITLE
[pipeline](load) Not blocking in execution threads

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

In group-commit loading tasks, we will wait for a condition variables in execution threads before finishing. This is harmful for pipeline engine.

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
