### PR TITLE
[bug](ColumnDecimal)call set_decimalv2_type when cloning ColumnDecimal

### LINKED ISSUE #14060: [Bug] is_decimalv2_type is lost after clone ColumnDecimal
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

is_decimalv2_type is lost after clone ColumnDecimal

### What You Expected?

is_decimalv2_type of the cloned ColumnDecimal is the same as its ancestor

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xiaokang**
# Proposed changes

Issue Number: close #14060

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — COMMENTED** [review]
Could you also set `is_date` and `is_date_time` in `ColumnVector<T>::clone_resized` ?

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.68 seconds
 load time: 454 seconds
 storage size: 17182819778 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221108064429_clickbench_pr_41759.html

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
Thanks for your comment @Gabriel39

**Pull request merged**
