### PR TITLE
[fix](Nereids): fix ColumnPruningPostProcessor

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

ColumnPruningPostProcessor use visitor wrong, we need call `super.visit`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
Update description and explain the reasons for the errors.

**Comment by jackwener** [comment]
run p1

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run p1

**Comment by jackwener** [comment]
run p1

**Comment by jackwener** [comment]
run p1

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run p0

**Comment by jackwener** [comment]
run buildall

**Pull request closed without merging**
