### PR TITLE
[fix](statistics) fix updated rows incorrect due to typo in code

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
Added case should be modified, I'll add modification later.

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
