### PR TITLE
[typo](docs) Refix sidebar and docs of DEV version

### PR DESCRIPTION
**Pull request by KassieZ**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — DISMISSED** [review]

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run buildall

**Comment by KassieZ** [comment]
run buildall

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run p0

**Review by luzhijing — APPROVED** [review]

**Comment by KassieZ** [comment]
run buildall

**Pull request closed without merging**
