### PR TITLE
[Improvement](function) enable ipv6_num_to_string function to support handling of IPv6 type

### PR DESCRIPTION
**Pull request by sjyango**
## Proposed changes

Enable ipv6_num_to_string function to handle `IPv6` type normally in addition to handling 16 byte string types

### before this PR:
error

### after this PR:
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run pipelinex_p0

**Comment by sjyango** [comment]
run arm

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
