### PR TITLE
[refactor](streamload) refactor stream load executor

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

There are many duplicate logic in the stream load executor, which should be extracted to avoid repetition.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
