### PR TITLE
[fix](tablet schedule) disable schedule need clear running tasks

### PR DESCRIPTION
**Pull request by yujun777**
BUG:  when disable tablet schedule, the running task still remain until timeout.  Need set them fail when disable schedule.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run cloud_p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
