### PR TITLE
[improvement](statistics)Support drop cached stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Support drop cached stats. Usage:
`drop cached stats table_name`

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run performance

**Comment by Jibing-Li** [comment]
run cloud_p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
