### PR TITLE
[Bug](parser) fix cannot delete from partitions

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

```sql
mysql>  delete from dwd_pay partitions (p202310) where pay_time = '20231002';
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
...e from dwd_pay partitions (p202310) where pay_time = '...
                             ^
Encountered: (
Expected: COMMA 
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
