### PR TITLE
[fix](ccr) Add tableName in DropInfo && BatchDropInfo

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add tableName in DropInfo && BatchDropInfo

### CODE REVIEW

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.46 seconds
 stream load tsv:          498 seconds loaded 74807831229 Bytes, about 143 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.4 seconds inserted 10000000 Rows, about 352K ops/s
 storage size: 17162644226 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711233135_clickbench_pr_176672.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 49.98 seconds
 stream load tsv:          438 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          56 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          25.8 seconds inserted 10000000 Rows, about 387K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230711170955_clickbench_pr_176671.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Pull request merged**
