### PR TITLE
[fix](parse_url) fix `parse_url` is not working in some case to extract the HOST 

### LINKED ISSUE #24452: [Bug] parse_url is not working in some case to extract the HOST
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache-doris-2.0-beta-bin-x64

### What's Wrong?

Generaet the correct HOST using parse_url

url = https://www.lottoland.at/meinlottoland/einzahlung?returnpage=https://www.lottoland.at/spiele/wolffangvolcano/spielen

with parse_url ( url, 'HOST') , we get  www.lottoland.at/meinlottoland/einzahlung?returnpage=https

### What You Expected?

I expected www.lotttoland.at

### How to Reproduce?

Yes, you can reproduce

with 

select url_path(' https://www.lottoland.at/meinlottoland/einzahlungreturnpage=https://www.lottoland.at/spiele/wolffangvolcano/spielen','HOST')

### Anything Else?

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #24452

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
