### PR TITLE
[Enhancement](array) reserve nested column to improve read array column

### PR DESCRIPTION
**Pull request by hqx871**
## Proposed changes

The old way reading array column one range by one range can not reserve nested column and may cause nested column resize many times. Add an option to read column by range batch.  But this change makes the block seek metric lost. No idea how to solve this problem.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hqx871** [comment]
runbuild all

**Comment by hqx871** [comment]
run buildall

**Comment by amorynan** [comment]
hey, Is there any data show for ur enhancement ?

**Comment by hqx871** [comment]
we are still doing bench

**Pull request closed without merging**
