### PR TITLE
[optimize](string) optimize concat function by SIMD memcpy

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes
Optimize concat function 29% up by memcpy_small_allow_read_write_overflow15.
Optimize string functions list: concat, convert_to, mask, initcap, lower, upper.

concat function has 29% up:
(1) after
image

(2) before
image

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by jacktengg** [comment]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
