### PR TITLE
[chore](workflow) Fix security issues in Code Checks

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

~~Issue Number: close #xxx~~

The workflow `Code Checks` needs write permissions granted by the event `pull_request_target` to comment on pull requests. However, if the workflow ran users' code, the malicious code would do some dangerous actions on our repository.

The following changes are made in this PR:
1. Instead of applying patches, we use `sed` to modify the `entrypoint.sh` in action-sh-checker explicitly in the workflow.
2. Revoke the write permissions when generating `compile_commands.json` which is produced by executing the build script `build.sh`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]
well done

**Pull request merged**
