### PR TITLE
[Test](orc-reader) Add orc submodule's unit tests.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Add orc submodule's unit tests.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by AshinGau** [comment]
LGTM

**Review by AshinGau — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
