### PR TITLE
[feature](fs) add fs benchmark tool framework

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Add an optional executable binary `fs_benchmark_tool`, for test the performance of file system such as hdfs, s3.
Usage:
```
./fs_benchmark_tool --conf my.conf --fs_type=s3 --operation=read --iterations=5
```

in `my.conf`, you can add any config key value with following format:

```
key1=value1
key2=value2
```

By default, this binary will not be built. Only build it when setting `BUILD_FS_BENCHMARK=ON`.
The binary will be installed in `output/be/lib`.

For developer, you can add new subclass of `BaseBenchmark` to add your own benchmark.
See `be/src/io/fs/benchmark/s3_benchmark.hpp` for an example

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by AshinGau — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by kaka11chen** [comment]
LGTM

**Review by AshinGau — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
