### PR TITLE
[enhancement](commands) Clarify user feedback messages

### PR DESCRIPTION
**Pull request by larshelge**
This PR attempts to enhance user feedback messages in the `start_be`, `stop_be.sh`, `start_fe.sh`, `stop_be.sh` commands.

* Removes period at the end of some feedback messages for consistency.
* Removes the use of "please", good to be polite but better to be clear and concise.
* Uses consistent uppercase for PID.
* Improves English wording in a few places.

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run buildall

**Comment by larshelge** [comment]
I can see there are some actions failing. Probably some failing tests. I tried to look into it but TeamCity requires a login.

**Comment by larshelge** [comment]
I can see there are some actions failing. Probably some failing tests. I tried to look into it but TeamCity requires a login.

**Comment by LemonLiTree** [comment]
run buildall

**Review by LemonLiTree — APPROVED** [review]

**Pull request merged**
