### PR TITLE
[fix](restore) fix restore odbc resource bug

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

if some odbc tables use the same resource, and restore not all odbc tables, it will not retain the resource. 
and check some conf for backup/restore

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run feut

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
