### PR TITLE
[chore](proto) modify the order of `store_row_column` and `is_dynamic_schema` to be compatible with branch-1.2-lts

### PR DESCRIPTION
**Pull request by eldenmoon**
This PR will change olap file proto, so that all data in master should be deleted and reload again!!!

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by yiguolei** [comment]
Not merge it in these days because many performance env will re-import data, I will merge it in April.

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
