### PR TITLE
[fix](core) fix multi_match_any maybe core down

### LINKED ISSUE #19050: [Bug] compare multi_match_any result with 1 cause be coredump
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4, master

### What's Wrong?

coredump with the following bt

```
*** SIGSEGV address not mapped to object (@0x5598b265fc) received by PID 3224331 (TID 0x7fbd6a3bf700) from PID 18446744071976412668; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/doris/doris/be/src/common/signal_handler.h:420
 1# os::Linux::chained_handler(int, siginfo*, void*) in /mnt/disk1/liuhong/caol/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /mnt/disk1/liuhong/caol/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /mnt/disk1/liuhong/caol/jdk1.8.0_331/jre/lib/amd64/server/libjvm.so
 4# 0x00007FBE6DE12400 in /lib64/libc.so.6
 5# doris::vectorized::ColumnNullable::compare_at(unsigned long, unsigned long, doris::vectorized::IColumn const&, int) const at /root/doris/doris/be/
src/vec/columns/column_nullable.cpp:340
 6# doris::vectorized::GenericComparisonImpl<doris::vectorized::EqualsOp<int, int> >::vector_constant(doris::vectorized::IColumn const&, doris::vectorized::IC
olumn const&, doris::vectorized::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) at /root/doris/doris/be/src/vec/functions/func
tions_comparison.h:117
 7# doris::vectorized::FunctionComparison<doris::vectorized::EqualsOp, doris::vectorized::NameEquals>::execute_impl(doris_udf::FunctionContext*, doris::vector
ized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) at /root/doris/doris/be/src/vec/functio
ns/functions_comparison.h:423
 8# doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsig
ned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /root/doris/doris/be/src/vec/functions/function.cpp:244
 9# doris::vectorized::PreparedFunctionImpl::execute(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigne
d long> > const&, unsigned long, unsigned long, bool) at /root/doris/doris/be/src/vec/functions/function.cpp:267
10# doris::vectorized::IFunctionBase::execute(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long>
 > const&, unsigned long, unsigned long, bool) at /root/doris/doris/be/src/vec/functions/function.h:154
11# doris::vectorized::VectorizedFnCall::execute(doris::vectorized::VExprContext*, doris::vectorized::Block*, int*) at /root/doris/doris/be/src/vec/ex
prs/vectorized_fn_call.cpp:109
12# doris::vectorized::VExprContext::filter_block(doris::vectorized::VExprContext*, doris::vectorized::Block*, int) at /root/doris/doris/be/src/vec/ex
prs/vexpr_context.cpp:126
13# doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/doris/doris/be/src/vec/exec/scan/vscanner.
cpp:68
14# doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, doris::vectorized::VScanner*)
 at /root/doris/doris/be/src/vec/exec/scan/scanner_scheduler.cpp:247
15# doris::PriorityWorkStealingThreadPool::work_thread(int) at /root/doris/doris/be/src/util/priority_work_stealing_thread_pool.hpp:136
16# execute_native_thread_routine in /mnt/disk1/liuhong/doris/1.2.4/doris-1.2.4.0-x86_64-noavx2/be/lib/doris_be
17# start_thread in /lib64/libpthread.so.0
18# __GI___clone in /lib64/libc.so.6
```

### What You Expected?

get right result without coredump

### How to Reproduce?

```
CREATE TABLE `test_jsonb_2` (
  `id` int(11) NULL,
  `rank` jsonb NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS AUTO
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);

insert into test_jsonb_2 values (1,'{"question12":{"answer":["1","2","4"],"content":"自己输入的内容"}}'); 

select * from test_jsonb_2 where 1 = multi_match_any(jsonb_extract_string(rank, '$.question12.answer'),['3']);
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #19050

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.03 seconds
 stream load tsv:          420 seconds loaded 74807831229 Bytes, about 169 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230426061512_clickbench_pr_135457.html

**Comment by nextdreamblue** [comment]
run p1

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
close by https://github.com/apache/doris/pull/19498

**Pull request closed without merging**
