### PR TITLE
[feat](docker)Modify the init_be and start_be scripts to meet the requirements for rapid Docker startup.

### PR DESCRIPTION
**Pull request by FreeOnePlus**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #45267

Problem Summary:

To meet the needs of rapid Docker startup, I have made adjustments to two related scripts in the Docker startup process. First, I added a env `SKIP_CHECK_ULIMIT` to the `start_be.sh` script, which will skip the size checks for `swap`, `ulimit`, and `max_map_count`. At the same time, I used `--console` to start the process and print logs. The reason why I did not use the `--daemon` daemon command to execute is that starting with a foreground log printing method in a Docker container is the correct and reliable approach.

At the same time, I added a check logic for a `be.conf` configuration item in the `init_be.sh` script: if it is the first time starting, append the export `SKIP_CHECK_ULIMIT=true` to skip the `ulimit` value check in the BE process. In summary, these adjustments can meet the basic requirements for rapid Docker startup usage.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [x] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

1. Set the `ulimit`, `swap`, and `max_map_count` check values on the host machine to values that do not meet the requirements.
2. Run `export SKIP_CHECK_ULIMIT=true` and `sh start_be.sh --console` to start the BE process, which starts up normally.
3. Run `export SKIP_CHECK_ULIMIT=false`，then using the `--daemon` or `--console` option to start, the BE process fails to start normally.

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
run buildall

**Comment by FreeOnePlus** [comment]
run buildall

**Review by catpineapple — DISMISSED** [review]

**Comment by FreeOnePlus** [comment]
run buildall

**Review by catpineapple — DISMISSED** [review]

**Comment by FreeOnePlus** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by catpineapple — APPROVED** [review]

**Pull request merged**
