### PR TITLE
[Feature](proc) Support proc dir for showing tablet health status

### LINKED ISSUE #8323: [Feature] Support proc dir for showing tablet health status
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now，We need more detail statistic for tablet unhealthy info monitor to do more improvement

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #8323 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (Yes)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Why don't just add new columns to `show proc "/statistic"`?

**Comment by caiconghui** [comment]
> Why don't just add new columns to `show proc "/statistic"`?

cannot find a suitable place to append this, which may cause /statistic info verbose and not easy to display

**Comment by morningman** [comment]
> 

So maybe it is better to move some column from `/statistic` to `/cluster_health`? such as `UnhealthyTabletNum` and `InconsistentTabletNum`? Otherwise we need to check them here and there.

**Comment by caiconghui** [comment]
> > 
> 
> So maybe it is better to move some column from `/statistic` to `/cluster_health`? such as `UnhealthyTabletNum` and `InconsistentTabletNum`? Otherwise we need to check them here and there.

move UnhealthyTabletNum | InconsistentTabletNum | CloningTabletNum | BadTabletNum |  to /cluster_health is more reasonable. BadTabletNum is uncoverableTabletNum

**Review by weizuo93 — APPROVED** [review]

**Pull request merged**
