### PR TITLE
[Fix](be log)Support BE log 'sys_log_level' modify to take effect dynamically #26060

### LINKED ISSUE #26060: [Bug] Support BE log 'sys_log_level' modify to take effect dynamically
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Execution does not take effect, update be sysLog:
curl -X POST http://{be_ip}:{be_http_port}/api/update_config?sys_log_level=ERROR&persist=true

### What You Expected?

which to repair it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
https://github.com/apache/doris/pull/26061

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
https://github.com/apache/doris/pull/26061

### PR DESCRIPTION
**Pull request by LuGuangming**
## Proposed changes

Issue Number: close #26060

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
lgtm

**Comment by LuGuangming** [comment]
All clean, LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by JNSimba — DISMISSED** [review]
LGTM

**Comment by JNSimba** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Pull request closed without merging**
