### PR TITLE
[Bugfix] Fix runtimefilter access violation when stub is nullptr

### PR DESCRIPTION
**Pull request by awakeljw**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

when stub is nullptr, rpc_contexts will pop_back, so next access rpc_contexts will be violation.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
@Gabriel39

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by awakeljw** [comment]
@Gabriel39 Please Review Again.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
