### PR TITLE
[Test](multi-catalog) Add tpcds sf100 hive shapes.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Add tpcds sf100 hive shapes.

Disable query64 temporarily because it is not same with emr cluster after collecting metadata by `analyze table xxx`.
And the root cause need to analyze, will enable in future PR.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Comment by kaka11chen** [comment]
run external

**Comment by kaka11chen** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Comment by zhangguoqiang666** [comment]
run clickbench

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run p0

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
