### PR TITLE
[Fix](RoutineLoad) Delete duplicate attribute in job property

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

There is duplicate attribute execMemLimit in job properties
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
