### PR TITLE
[fix](memory) Fix Allocator check mem tracker limit

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

img_v2_a8d4789c-6694-4624-ba97-d2065fa6f20g

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
