### PR TITLE
[Fix](regression-test) fix es regression test

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx
Because nereids do not support `Es external table` and complex data type，
we comment on some case first temporarily.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run external

**Comment by BePPPower** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run external

**Comment by BePPPower** [comment]
run buildall external

**Comment by zhangguoqiang666** [comment]
run external

**Comment by BePPPower** [comment]
run external

**Comment by BePPPower** [comment]
run buildall external

**Comment by wsjz** [comment]
run external

**Comment by BePPPower** [comment]
run buildall external

**Comment by BePPPower** [comment]
run external

**Comment by BePPPower** [comment]
run external

**Comment by BePPPower** [comment]
run p0

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
