### PR TITLE
[docs] add function substring document

### PR DESCRIPTION
**Pull request by obobj**
# Proposed changes

1. add function substring document

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hf200012** [comment]
add sidebar
docs/.vuepress/sidebar/en.js and docs/.vuepress/sidebar/zh-CN.js

**Comment by obobj** [comment]
> add sidebar docs/.vuepress/sidebar/en.js and docs/.vuepress/sidebar/zh-CN.js

done

**Comment by hf200012** [comment]
> > add sidebar docs/.vuepress/sidebar/en.js and docs/.vuepress/sidebar/zh-CN.js
> 
> done
Please see what I have commented in the file

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
