### PR TITLE
[Feature](remote)Remote Storage support single file when Cooldown.(FE)

### LINKED ISSUE #14389: [Feature](remote)Remote Storage support single file when Cooldown.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Remote Storage support single file when Cooldown.
In old cooldown, one replica will create one remote file, it will create too many replicas in remote storage, because remote storage already support replicas.
In this case, several replicas in local files will upload to one file in remote storage.

### Use case

Remote Storage support single file when Cooldown.

### Related issues

1.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #14389

## Problem summary

Remote Storage support single file when Cooldown.
In old cooldown, one replica will create one remote file, it will create too many replicas in remote storage, because remote storage already support replicas.
In this case, several replicas in local files will upload to one file in remote storage.

## Description
In old case, 1 tablet has 3 replicas,  they are on BE1, BE2, BE3, when cooldowning, each replica will be uploaded as one replica on remote storage. As result, 1 tablet will create 3 replicas on remote storage.
But, remote storage has its own replica controller, 1 replica is enought.
So, this pr will create a policy, cooldown will create only 1 replica instead of 3 replicas.

This pr realize FE, FE will get replica cooldownType in tabletReport which is used to dicide which BE will used to upload file, others will only get meta from remote, but not upload file.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.14 seconds
 load time: 424 seconds
 storage size: 17154741777 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221118080934_clickbench_pr_48558.html

**Comment by pengxiangyu** [comment]
> What is `single file` means? And could you please add more details about this policy? And is it a WIP feature or fully implemented?

It is a WIP feature, BE will be append later.

**Comment by yiguolei** [comment]
Please add some regression test for cool down.

**Review by yiguolei — CHANGES_REQUESTED** [review]
As we discussed offline, we should resolve the problem that two replica write to S3 concurrently.

**Pull request closed without merging**
