### PR TITLE
[Enhance](regression)enhance case test_broker_load_func

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

Issue Number: close #xxx

enhance case test_broker_load_func

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by pingchunzhang — APPROVED** [review]

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by pingchunzhang — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Review by zgxme — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
