### PR TITLE
[Fix](Nereids) fix hint tests with different be instances

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
Problem:
When using multiple be to test hint with distribute hint, the result would be unstable
Solved:
Add ordered hint to every distribute hint and move some leading hint cases to check containing of hint infomation

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by englefly** [comment]
it is beter to 'set be_number_for_test=3' to avoid choosing different join type

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
