### PR TITLE
[Fix][Opt](parquet_reader) Fix dict filtering doesn't work with plain dict encoding in parquet reader.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Fix][Opt] (parquet_reader) Fix dict filtering doesn't work with plain dict encoding in parquet reader.

- Fix dict filtering doesn't work with plain dict encoding in parquet reader.
- Fix `test_hive_parquet_alter_column.out` decimal display format.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
