### PR TITLE
[Fix](doc) Fix doris english doc data-model.md table name spell error

### PR DESCRIPTION
**Pull request by fcb-xiaobo**
## Proposed changes

fix doris  english doc  data-model.md table name(example_db.example_tbl_agg) spell error

### CODE REVIEW

**Review by liugddx — APPROVED** [review]
LGTM

**Review by hf200012 — COMMENTED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Comment by liugddx** [comment]
I have refactor data-model.md ,fix some doc error and fixed some formatting issues #24941

**Comment by liugddx** [comment]
> I have refactor data-model.md ,fix some doc error and fixed some formatting issues #24941

@hf200012 @zy-kkk

**Pull request closed without merging**
