### PR TITLE
[Enhancement](function) fix compatibility issues of sum/count during upgrade process

### PR DESCRIPTION
**Pull request by zhangstar333**
* in order to solve agg of sum/count is not compatibility during the upgrade process.
 * in PR #20370 have changed the serialize type and serialize column of sum/count
 * before is ColumnVector, now sum/count change to use ColumnFixedLengthObject
 * so during the upgrade process, will be not compatible if exist Old BE and Newer BE

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
