### PR TITLE
[enhancement](export)export job for olap table will  only hit the base index, so skip other tablets of  rollup index when do splitTablets

### PR DESCRIPTION
**Pull request by caiconghui**

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run performance

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run fe-ut

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run p0

**Comment by caiconghui** [comment]
run p0

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Review by GoGoWen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Comment by caiconghui** [comment]
run p0

**Comment by caiconghui** [comment]
run p0

**Review by weizuo93 — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
