### PR TITLE
[fix](compaction) remove check rowset overlapping in base compaction

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
when a version publish late, cmululative compaction won't pick corresponding rowset to do compaction, because the version won't be in tablet _rs_version_map. After this round cmululative compaction, the cmululative point will update and the late publish version will never have chance to do cmululative compaction unless restar be to recalculate cmululative point. However now base compaction will check rowset overlapping first, and it will fail in this situation. After checking the code, i think check overlapping can remove in base compaction, and check version continuity is enough. The diffrent between base compaction and cmululative compaction is that base compaction will filter deleted row, and block reader they are used is same, so no need to worry about data aggregation in agg type.
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.4 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162078916 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.44 seconds
 stream load tsv:          514 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162194298 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run p0

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
