### PR TITLE
[chore](Nereids) forbid some commands fallback when parse failed

### PR DESCRIPTION
**Pull request by morrySnow**
1. CreateTableLikeCommand
2. CreateViewCommand
3. AlterViewCommand

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Review by feiniaofeiafei — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
