### PR TITLE
[BugFix](MultiCatalog)fix iceberg table get split fail when with date type conjuct

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

issue found in 2.0.4-rc05

1, have iceberg table with partitioned by date type column "day"
2 execute select * from test_table where day = "2022-01-01" will get nothing while the data exist in iceberg table, just we transfer the DateLiteral("2022-01-01") to datetime, cause we can not get the split correctly.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
