### PR TITLE
[fix](index compaction)support compact multi segments in one index

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

pick from branch-2.0-var #28545 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
add testcase

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
