### PR TITLE
[ci](perf) 1. add perf check of tpcds, 2. adjust clickbench and tpch check

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
<details>
<summary>ClickBench test result on machine: 'aliyun_ecs.c7a.8xlarge_32C64G'</summary>

```
ClickBench test result on commit 5f5c4c80564c76ff4267fc4ce6a5408498ed1ab5, data reload: false

run clickbench query with default conf and session variables
query1,0.01,0.01,0.01
query2,0.01,0.01,0.01
query3,0.01,0.01,0.01
query4,0.01,0.01,0.01
query5,0.02,0.01,0.01
query6,0.02,0.01,0.01
query7,0.01,0.00,0.01
query8,0.02,0.01,0.01
query9,0.02,0.01,0.01
query10,0.02,0.02,0.01
query11,0.01,0.01,0.01
query12,0.01,0.01,0.00
query13,0.01,0.00,0.01
query14,0.01,0.00,0.01
query15,0.01,0.01,0.00
query16,0.01,0.00,0.01
query17,0.01,0.00,0.01
query18,0.01,0.01,0.01
query19,0.01,0.01,0.01
query20,0.01,0.01,0.00
query21,0.01,0.01,0.01
query22,0.01,0.01,0.02
query23,0.02,0.01,0.00
query24,0.02,0.01,0.02
query25,0.01,0.01,0.01
query26,0.01,0.01,0.01
query27,0.01,0.01,0.00
query28,0.02,0.01,0.01
query29,0.01,0.00,0.01
query30,0.03,0.03,0.04
query31,0.01,0.01,0.01
query32,0.02,0.02,0.01
query33,0.01,0.01,0.01
query34,0.01,0.01,0.00
query35,0.00,0.01,0.01
query36,0.00,0.01,0.01
query37,0.01,0.01,0.01
query38,0.01,0.01,0.00
query39,0.02,0.01,0.01
query40,0.02,0.01,0.01
query41,0.02,0.01,0.01
query42,0.00,0.00,0.01
query43,0.01,0.01,0.01
Total cold run time: 0.54 s
Total hot run time: 0.31 s
```
</details>

**Comment by dataroaring** [comment]
<details>
<summary>TPC-DS test result on machine: 'aliyun_ecs.c7a.8xlarge_32C64G'</summary>

```
TPC-DS sf1 test result on commit 5f5c4c80564c76ff4267fc4ce6a5408498ed1ab5, data reload: false

run tpcds-sf1 query with default conf and session variables
query78	188	198	177	177
query79	58	62	55	55
query80	167	175	171	171
query81	42	39	39	39
query82	24	24	25	24
query83	76	69	68	68
query84	37	37	36	36
query85	173	170	170	170
query86	38	37	38	37
query87	83	80	78	78
query88	181	193	180	180
query89	45	43	46	43
query90	41	39	40	39
query91	61	59	59	59
query92	26	27	26	26
query93	17	17	17	17
query94	70	71	69	69
query95	75	68	67	67
query96	35	32	31	31
query97	92	96	96	96
query98	40	39	41	39
query99	48	54	49	49
Total cold run time: 11081 ms
Total hot run time: 9824 ms
```
</details>

**Comment by hello-stephen** [comment]
run buildall

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by Gabriel39 — DISMISSED** [review]

**Comment by hello-stephen** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
