### PR TITLE
[fix](Export) Fix an export error when lower_case_table_names=1

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

if `lower_case_table_names=1` and using old optimizer, when the table we want to export belongs to a database containing a capital letter, we will get an error.
For example, if the db named XXX, and the table we want to export is named yyy, then when we execute `export` job, we will get the error:
Unknown table 'yyy' in default_cluster:XXX

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
