### PR TITLE
[2.0-pick-26525](workflow) Fix security issues with pull_request_target #26525

### PR DESCRIPTION
**Pull request by CalvinKirs**
…

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by xiaokang** [comment]
#26525

**Review by adonis0147 — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Pull request merged**
