### PR TITLE
[feature](planner) allow `HLL` and `QUANTILE_STATE` types on duplicate and unique table

### PR DESCRIPTION
**Pull request by bobhan1**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by zhannngchen — CHANGES_REQUESTED** [review]
need to update the doc as well? in duplicate and unique key mode, it will not work as expect.

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
