### PR TITLE
[fix](multi-catalog)filter impala generated path

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

file impala generated dir `_imapala_insert_staging`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
have created the impala dir in p2 case

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
