### PR TITLE
[fix](auth)Fix the compatibility issue with show_view_priv when replaying editLog

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

The previous version showed an index of 9 for show_view_priv, while the new version has an index of 14
The previous logic was only compatible with the playback logic of images, not with the playback logic of editLog

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Fix the compatibility issue with show_view_priv when replaying editLog
### Release note
Fix the compatibility issue with show_view_priv when replaying editLog

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [x] Manual test (add detailed scripts or steps below)
           - use doris2.1 create user and grant show_view_priv on xx.xx to userxxx;
           - use doris master revoke show_view_priv on xx.xx from userxxx;
           - show grants for userxxx; show_view_priv has been disappear
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run p0

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
