### PR TITLE
[chore](olap) Unify the parameters into SegmentWriterOptions

### PR DESCRIPTION
**Pull request by w41ter**

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
