### PR TITLE
[enhance](catalog)show partitions support iceberg

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

support `show partitions from iceberg_table`
Field Explanation Reference: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/PartitionsTable.java
```
mysql> show partitions from sample_cow_parquet\G
*************************** 1. row ***************************
                partition: col_timestamp_day=1970-01-04/city=Hefei/id_bucket=1
                   specId: 0
              recordCount: 36
                fileCount: 1
 totalDataFileSizeInBytes: 7717
positionDeleteRecordCount: 0
  positionDeleteFileCount: 0
equalityDeleteRecordCount: 0
  equalityDeleteFileCount: 0
            lastUpdatedAt: 1697163408768000
    lastUpdatedSnapshotId: 1704258583567025327
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
add use case in description

**Comment by zddr** [comment]
run buildall

**Comment by Samrose-Ahmed** [comment]
Nice. btw should we follow the iceberg semi-convention and support metadata table as well (e.g. trino `select * from table$partitions` or spark `select * from prod.db.table.partitions` https://iceberg.apache.org/docs/1.5.1/spark-queries/#partitions) in a separate pr

**Review by morningman — COMMENTED** [review]
Need to add more test
1. unpartitioned table
2. partition with exprs

**Pull request closed without merging**
