### PR TITLE
[fix](env)fix feut failed by mockit error

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

```
mockit.internal.expectations.invocation.MissingInvocation: Missing 1 invocation to:
org.apache.doris.catalog.Env#isCheckpointThread()
mockit.internal.expectations.invocation.MissingInvocation: 
Missing 1 invocation to:
org.apache.doris.catalog.Env#isCheckpointThread()
Caused by: mockit.internal.expectations.invocation.ExpectationError
```

resolve http://43.132.222.7:8111/viewLog.html?buildId=213066&buildTypeId=Doris_Doris_FeUt

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
