### PR TITLE
[fix](regression-test) use correct dataset for unique_with_mow_p2

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

cases in `unique_with_mow_p2` should use sf100 dataset, rather than sf0.1 dataset
sf100 dataset have 10 data files for lineorder table, which is not easy to load through stream load, so I use s3 load instead.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
