### PR TITLE
[Improvement](function) optimization for substr with ascii string

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
optimization for substr with ascii string
```sql
select count(substr(l_comment, 1, 10)) from lineitem;
```

before:
图片

after:
图片

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by yanyxin** [comment]
@BiteTheDDDDt Will the modifications be synchronized to 2.1.5

**Comment by BiteTheDDDDt** [comment]
> @BiteTheDDDDt Will the modifications be synchronized to 2.1.5

Already included

**Comment by yanyxin** [comment]
> > @BiteTheDDDDt Will the modifications be synchronized to 2.1.5
> 
> Already included

The position of line 235 in the function_string. h file in 2.1.5 is inconsistent with the current modification, lacking the judgment of fixed_pos>index.size(), resulting in incorrect results in 2.1.5

**Comment by BiteTheDDDDt** [comment]
> > > @BiteTheDDDDt Will the modifications be synchronized to 2.1.5
> > 
> > 
> > Already included
> 
> The position of line 235 in the function_string. h file in 2.1.5 is inconsistent with the current modification, lacking the judgment of fixed_pos>index.size(), resulting in incorrect results in 2.1.5

The code 2.1.5 and master in this regard should be the same. Can you provide a specific example to illustrate the problem of wrong results?

**Comment by yanyxin** [comment]
> The code 2.1.5 and master in this regard should be the same. Can you provide a specific example to illustrate the problem of wrong results?

select substr('老人年轻并不等于动的金币第七十二',17);  The result of executing 2.0.13 is null，2.1.5 The result is '老人年轻并不等于动的金币第七十二'，Due to the presence of fixed_pos>index.size() in line 247 of the function_string. h file in 2.0.13, but not in branch 2.1.5, 2.0.13 is consistent with master

**Comment by BiteTheDDDDt** [comment]
> > The code 2.1.5 and master in this regard should be the same. Can you provide a specific example to illustrate the problem of wrong results?
> 
> select substr('老人年轻并不等于动的金币第七十二',17); The result of executing 2.0.13 is null，2.1.5 The result is '老人年轻并不等于动的金币第七十二'，Due to the presence of fixed_pos>index.size() in line 247 of the function_string. h file in 2.0.13, but not in branch 2.1.5, 2.0.13 is consistent with master

this behavior is changed by #28352, so I think 2.1 is same with master, and 2.0 still remained old behavior

**Comment by yanyxin** [comment]
> > > The code 2.1.5 and master in this regard should be the same. Can you provide a specific example to illustrate the problem of wrong results?
> > 
> > 
> > select substr('老人年轻并不等于动的金币第七十二',17); The result of executing 2.0.13 is null，2.1.5 The result is '老人年轻并不等于动的金币第七十二'，Due to the presence of fixed_pos>index.size() in line 247 of the function_string. h file in 2.0.13, but not in branch 2.1.5, 2.0.13 is consistent with master
> 
> this behavior is changed by #28352, so I think 2.1 is same with master, and 2.0 still remained old behavior

Substring (VARCHAR str, INT pos, [INT len]), so when pos exceeds the length of str, is the correct result null? However, 2.1.5 is currently not available；

**Comment by yanyxin** [comment]
> > > The code 2.1.5 and master in this regard should be the same. Can you provide a specific example to illustrate the problem of wrong results?
> > 
> > 
> > select substr('老人年轻并不等于动的金币第七十二',17); The result of executing 2.0.13 is null，2.1.5 The result is '老人年轻并不等于动的金币第七十二'，Due to the presence of fixed_pos>index.size() in line 247 of the function_string. h file in 2.0.13, but not in branch 2.1.5, 2.0.13 is consistent with master
> 
> this behavior is changed by #28352, so I think 2.1 is same with master, and 2.0 still remained old behavior

In line 243 of function_string. h in 2.1.5, if we do not check whether fixed_pos is greater than index.size(), will there be index access errors

**Comment by BiteTheDDDDt** [comment]
@koarz hi, could you help me answer the question? I'm not very get familiar with new logic

**Comment by koarz** [comment]
> > > @BiteTheDDDDt Will the modifications be synchronized to 2.1.5
> > 
> > 
> > Already included
> 
> The position of line 235 in the function_string. h file in 2.1.5 is inconsistent with the current modification, lacking the judgment of fixed_pos>index.size(), resulting in incorrect results in 2.1.5

sorry, when I changed the logic of this part of the code, ignored this part, the return of the empty result is correct, I did not test the Chinese case led to the error was not found, i'll fix it soon

**Pull request merged**
