### PR TITLE
[fix](inverted index) fix check failed for block erase temp column

### PR DESCRIPTION
**Pull request by Tanya-W**
## Proposed changes

fix check failed like:
```
F0615 22:51:33.920902 631399 block.cpp:240] No such name in Block::erase(): '__TEMP__payload.commits.message_match_fix'
*** Check failure stack trace: ***
    @     0x5610d87169fd  google::LogMessage::Fail()
    @     0x5610d8718f39  google::LogMessage::SendToLog()
    @     0x5610d8716566  google::LogMessage::Flush()
    @     0x5610d87195a9  google::LogMessageFatal::~LogMessageFatal()
    @     0x5610d3ab6993  doris::vectorized::Block::erase()
    @     0x5610d4eb987e  doris::Defer<>::~Defer()
    @     0x5610d4eb955c  doris::vectorized::VScanNode::get_next()
    @     0x5610d1c0682f  doris::ExecNode::pull()
    @     0x5610d83a7741  std::_Function_handler<>::_M_invoke()
    @     0x5610d1c02878  doris::ExecNode::get_next_after_projects()
    @     0x5610d83a757c  doris::pipeline::SourceOperator<>::get_block()
    @     0x5610d83d5463  doris::pipeline::PipelineTask::execute()
    @     0x5610d83dcf93  doris::pipeline::TaskScheduler::_do_work()
    @     0x5610d1dac94f  doris::ThreadPool::dispatch_thread()
    @     0x5610d1da27ec  doris::Thread::supervise_thread()
    @     0x7fd4698c0609  start_thread
    @     0x7fd469b4f133  clone
    @              (nil)  (unknown)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Tanya-W** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
