### PR TITLE
[feature](nereids) deal the slots that appear both in agg func and grouping sets

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
## Proposed changes

select sum(a) from t group by grouping sets ((a)); The slot a  appearing both in agg func and grouping sets. 
Report an error: col_int_undef_signed cannot both in select list and aggregate functions when using GROUPING SETS/CUBE/ROLLUP, please use union instead.
 This PR removes the restriction and supports this situation.

### CODE REVIEW

**Comment by 924060929** [comment]
please add regression test case

**Comment by starocean999** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Pull request closed without merging**
