### PR TITLE
[fix](nereids) fix bug for A>n, where A.max is infinity

### PR DESCRIPTION
**Pull request by englefly**

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by starocean999 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
