### PR TITLE
[Enhancement](docs) fix document typo

### PR DESCRIPTION
**Pull request by geniusjoe**
# Proposed changes

Issue Number: close #xxx

## Problem summary

When visit english [kafka load](https://doris.apache.org/docs/data-operate/import/import-scenes/kafka-load) document, click [ROUTINE LOAD](https://doris.apache.org/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.html) will lead to NOT FOUND exception.
image

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments
It is because an markdown link error.Someone use .html link file instead of .md link file.

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jackwener — APPROVED** [review]
LGTM

**Comment by geniusjoe** [comment]
@jackwener Would you mind merge this pr to the main stream? As a first-time commiter workflow needs to trigger manually. 😂

**Comment by jackwener** [comment]
I'm not Committer😂, so I haven't this permission.

**Comment by geniusjoe** [comment]
> I'm not Committer😂, so I haven't this permission.

okay. whatever thanks a lot for your help. lol

**Comment by geniusjoe** [comment]
@hf200012 
Would you mind merge this little fix into the main stream ? My jacwener fellow doesn't have this project write access. 😁

**Comment by geniusjoe** [comment]
@hf200012 
Hello, do you have free time now？

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by geniusjoe** [comment]
@yiguolei 
Would you mind merge this little fix into the main stream ? 😁

**Comment by geniusjoe** [comment]
Thanks indeed!

**Pull request merged**
