### PR TITLE
[enhancement](Tablet) rename pathHashToDishInfoRef to pathHashToDiskInfoRef

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

1、use Set.containsAll instead of List.containsAll because the Set.containsAll is faster.
2、rename `pathHashToDishInfoRef` to `pathHashToDiskInfoRef`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
