### PR TITLE
[Doris On ES] [1/3] Add ES QueryBuilders for debug mode

### PR DESCRIPTION
**Pull request by wuyunfeng**
https://github.com/apache/incubator-doris/issues/3759
First step for debug mode for other user easily reading. function `esquery` will be processed at last.

reorganize some elasticsearch-related file into `elasticsearch` folder

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]
+1, LGTM

**Comment by morningman** [comment]
hi @wuyunfeng Plz resolve the conflict.

**Review by kangkaisen — DISMISSED** [review]

**Comment by wuyunfeng** [comment]
Sorry for leave some file which use elasticsearch related still reference the before source file path

**Comment by wuyunfeng** [comment]
`EsStateStoreTest` do some test based on `cluster state`, `Doris On ES` will not request `_cluster/state` in the future

**Comment by kangkaisen** [comment]
@wuyunfeng Hi，This PR is ready to merge?

**Comment by wuyunfeng** [comment]
@kangkaisen  Yes,  can you help me to merge this?

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
