### PR TITLE
[fix](set) fix coredump caused by intersect of nullable and not nullable children

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx

Bug of block reuse of set operator.

```
*** tablet id: 0 ***
*** Aborted at 1719221462 (unix time) try "date -d @1719221462" if you are using GNU date ***
*** Current BE git commitID: fe750497af ***
*** SIGSEGV address not mapped to object (@0x4000000108) received by PID 560 (TID 1133 OR 0x7f6371eff640) from PID 264; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/selectdb-core/be/src/common/signal_handler.h:435
 1# 0x00007F64A638042F in /lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 3# 0x00007F64A63790FC in /lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 4# 0x00007F64AB726520 in /lib/x86_64-linux-gnu/libc.so.6
 5# doris::vectorized::ColumnNullable::insert_range_from_not_nullable(doris::vectorized::IColumn const&, unsigned long, unsigned long) at /root/selectdb-core/be/src/vec/columns/column_nullable.cpp:348
 6# doris::ExecNode::do_projections(doris::vectorized::Block*, doris::vectorized::Block*) at /root/selectdb-core/be/src/exec/exec_node.cpp:572
 7# doris::ExecNode::get_next_after_projects(doris::RuntimeState*, doris::vectorized::Block*, bool*, std::function<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*)> const&, bool) at /root/selectdb-core/be/src/exec/exec_node.cpp:594
 8# doris::vectorized::VSetOperationNode<true>::open(doris::RuntimeState*) at /root/selectdb-core/be/src/vec/exec/vset_operation_node.cpp:248
 9# doris::vectorized::VSortNode::open(doris::RuntimeState*) at /root/selectdb-core/be/src/vec/exec/vsort_node.cpp:172
10# doris::PlanFragmentExecutor::open_vectorized_internal() at /root/selectdb-core/be/src/runtime/plan_fragment_executor.cpp:308
11# doris::PlanFragmentExecutor::open() at /root/selectdb-core/be/src/runtime/plan_fragment_executor.cpp:265
12# doris::FragmentExecState::execute() at /root/selectdb-core/be/src/runtime/fragment_mgr.cpp:281
13# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::RuntimeState*, doris::Status*)> const&) at /root/selectdb-core/be/src/runtime/fragment_mgr.cpp:554
14# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0>::_M_invoke(std::_Any_data const&) at /root/tools/ldb-16/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
15# doris::ThreadPool::dispatch_thread() in /opt/selectdb/be/lib/doris_be
16# doris::Thread::supervise_thread(void*) at /root/selectdb-core/be/src/util/thread.cpp:499
17# 0x00007F64AB778AC3 in /lib/x86_64-linux-gnu/libc.so.6
18# __clone in /lib/x86_64-linux-gnu/libc.so.6 
```

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run p0

**Comment by jacktengg** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
