### PR TITLE
[doc](flink-connector) Update the flink connector docs to the latest version

### PR DESCRIPTION
**Pull request by Myasuka**
# Proposed changes

Issue Number: no issues yet

## Problem summary

Update the flink-doris connector docs to the latest version, this PR should be merged after https://github.com/apache/doris-flink-connector/pull/91

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

### CODE REVIEW

**Review by hf200012 — COMMENTED** [review]
Please modify the Chinese version together

**Comment by Myasuka** [comment]
@hf200012 could you make another round of review?

**Comment by hf200012** [comment]
@Myasuka Modified, thanks for your submission

**Comment by luzhijing** [comment]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
