### PR TITLE
[fix](arrow-flight) Fix arrow flight sql compatible with JDK 17 and upgrade arrow 15.0.2

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

1. `--add-opens=java.base/java.nio=ALL-UNNAMED`, see: https://arrow.apache.org/docs/java/install.html#java-compatibility
2. groovy use flight sql connection to execute query `SUM(MAX(c1) OVER (PARTITION BY))` report error: `AGGREGATE clause must not contain analytic expressions`, but no problem in Java execute it with `jdbc::arrow-flight-sql`.
3. groovy not support print arrow array type, throw IndexOutOfBoundsException.
4. "arrow_flight_sql" not support two phase read

./run-regression-test.sh --run --clean -g arrow_flight_sql

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
