### PR TITLE
[fix](doc)Added english translation for monitoring Metric description…

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
… page

## Proposed changes

added english translation for metrics description page.

ref: #28435

### CODE REVIEW

**Review by httpshirley — APPROVED** [review]

**Comment by httpshirley** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by KassieZ** [comment]
Hi @Nitin-Kashyap ,

Thank you for contributing to Document revisions. 

The pr seems to be failing to build because of the error. May be you can use code format , such as ```<GarbageCollector>```or  \<GarbageCollector\> , to solve it.


img_v3_026i_c510f130-ee91-44b3-8850-166e29bd12ag

**Comment by morningman** [comment]
run buildall

**Pull request merged**
