### PR TITLE
[fix](arrow-flight-sql) Fix arrow flight result sink

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

1. get arrow flight result schema use query id instead of instance id.
2. get arrow flight result is a sync method, need wait for data ready and return result, introduced by https://github.com/apache/doris/pull/36667.
    TODO, waiting for data will block pipeline, so use a request pool to save requests waiting for data.

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
