### PR TITLE
 [fix](stream_load) fix stream load may failed caused by column name with keyword

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Comment by caiconghui** [comment]
run buildall

**Comment by zclllyybb** [comment]
please add pr descreption

**Comment by caiconghui** [comment]
> please add pr descreption

@zclllyybb reopen it in #35822 and add pr descreption

**Pull request closed without merging**
