### PR TITLE
[Feature][external catalog/lakesoul] support lakesoul catalog

### LINKED ISSUE #32163: [Feature] (LakeSoul) Support LakeSoul catalog
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support reading [LakeSoul](https://lakesoul-io.github.io/) Data by using [JNI Scanner](https://github.com/apache/doris/pull/17960)

### Use case

_No response_

### Related issues

You can refer to this PR https://github.com/apache/doris/pull/17960 and following classes:

be/src/vec/exec/jni_connector.h
be/src/vec/exec/format/jni_reader.h
fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/MockJniScanner.java

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Ceng23333**
## Proposed changes

Issue Number: close #32163 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run  buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
