### PR TITLE
[fix](csv_reader)Fixed bug when parsing multi-character delimiters.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

Fixed bug when parsing multi-character delimiters.

example:
column_separator : "xx"
data.csv :  data1xxxxdata2

Parse incorrectly:
      data1[xx]xxdata2
      data1x[xx]xdata2
      data1xx[xx]data2
The string "xxxx" is parsed into three "xx" delimiters.

Parse correctly:
      data1[xx]xxdata2
      data1xx[xx]data2

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Pull request merged**
