### PR TITLE
[Fix](Variant) fix variant partial update with row store enabled

### PR DESCRIPTION
**Pull request by eldenmoon**
## Proposed changes

1. Variant use serialize_one_row_to_string to string and then parse to jsonb as row store.Since we could not get the original string after #34925
2. Remove redundant code
Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
