### PR TITLE
Document Update compilation.md(en)

### PR DESCRIPTION
**Pull request by emerkfu**
# Proposed changes
Added solutions to the "fatal error: Killed signal terminated program ..." problem encountered when compiling with Docker to the FAQ.

### CODE REVIEW

**Review by zbtzbtzbt — COMMENTED** [review]
thanks your pr, please add it in chinese  documents also.

**Review by hf200012 — COMMENTED** [review]
LGTM

**Comment by emerkfu** [comment]
https://github.com/apache/incubator-doris/pull/8638

**Comment by emerkfu** [comment]
https://github.com/apache/incubator-doris/pull/8638

**Pull request closed without merging**
