### PR TITLE
[FIX](array)fix index writer with add_array_values with first empty array for a batch

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
if first is empty array in coming batch data
fieldDataArray.values would not be initialized in ThreadState.init method,
then next array which to be inverted index will not be reset in Field because of this condition. 
so we have to create a field into _doc to make thread init fieldDataArray 
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
