### PR TITLE
[feature](view) support create or replace view stmt

### PR DESCRIPTION
**Pull request by cambyzju**
Support `CREATE OR REPLACE VIEW` stmt.

Usage example:
```
mysql>  CREATE VIEW IF NOT EXISTS view_test_create_or_replace_view
    ->         AS SELECT * FROM test_create_or_replace_view_tbl1;
Query OK, 0 rows affected (0.02 sec)

mysql> select * from view_test_create_or_replace_view;
+------+------+------+
| k1   | k2   | v    |
+------+------+------+
|    1 |    1 |    1 |
+------+------+------+
1 row in set (0.03 sec)

mysql> 
mysql>  CREATE OR REPLACE VIEW view_test_create_or_replace_view
    ->         AS SELECT * FROM test_create_or_replace_view_tbl2;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from view_test_create_or_replace_view;
+------+------+------+
| k1   | k2   | v    |
+------+------+------+
|    2 |    2 |    2 |
+------+------+------+
1 row in set (0.03 sec)
```

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by feiniaofeiafei — APPROVED** [review]

**Comment by cambyzju** [comment]
run feut

**Comment by cambyzju** [comment]
run feut

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
