### PR TITLE
[fix](index) should not use light index change for bloom filter index

### PR DESCRIPTION
**Pull request by cambyzju**
cherry-pick https://github.com/apache/doris/pull/35214 to branch2.0

Problem:
1. add or drop Bitmap Index;
2. add or drop Bloom Filter Index;
Both do not work correctly for history data.

related pr: https://github.com/apache/doris/pull/28135 https://github.com/apache/doris/pull/32839 https://github.com/apache/doris/pull/10136

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add regression cases.

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
