### PR TITLE
[improvement](regression-test)  add more group commit regression-test

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes

These regression test will be divided into three type: insert into , stream load, http stream.
And each type hase four scenario: long time load, load with schema change, load with multiple client, load with multiple tabel.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
