### PR TITLE
[Fix](outfile) Add a configuration for exporting data in Parquet format using `select into outfile`

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

backport: #36142

When exporting data to Parquet, you can specify the minimum row group size. Add the configuration min_row_group_size in be.conf.

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Pull request merged**
