### PR TITLE
[fix](datetime) fix unstable str_to_date function result

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

**must merge into other branch with https://github.com/apache/doris/pull/24932 together**

```sql
select str_to_date("2014-12-21 12:34:56.789 PM", '%Y-%m-%d %h:%i:%s.%f %p');
```
has different result in Old/Nereids Planner before.
now they are all:
```sql
2014-12-21T12:34:56.789
```

the whole function relys on some specific judge on FE and fully tested in regression-test. so deleted some inconvenient be-ut

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
