### PR TITLE
[fix](auth)Fix no auth,but can select count(*)

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

when `select count(*)`,cols is empty, should check table priv

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
