### PR TITLE
[chore] Separate debugging information from BE binaries

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Currently, the compiled output of BE mainly consists of two binaries:
palo_be and meta_tool, which are both around 1.6G in size.
However, the debug information is only needed for debugging purposes.

So I separate the debug info from binaries.
After BE is built, the debug info file will be saved in `be/lib/debug_info/` dir.
`palo_be` and `meta_tool`'s size decrease to about 100MB

This is optional, and default is disabled.
To enable it, use:

`STRIP_DEBUG_INFO=ON sh build.sh`

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
If we strip debug info to another file, BE could not print stack trace line number during Core. And if we use exception as error handling mechanism the line number is also lost.
Even though strip debug info to another file will reduce the binary size, I think maybe we could implement it in the future because more debug info will help us fix bugs more quickly. 
What about save debug info just in palo_be and move debug info from meta tool?

**Comment by morningman** [comment]
> If we strip debug info to another file, BE could not print stack trace line number during Core. And if we use exception as error handling mechanism the line number is also lost.
> Even though strip debug info to another file will reduce the binary size, I think maybe we could implement it in the future because more debug info will help us fix bugs more quickly.
> What about save debug info just in palo_be and move debug info from meta tool?

It is ok that we can still see the error stack in `be.out`, just like before:
```
PC: @     0x7fa8c35fe14e doris::OlapScanNode::get_next()
*** SIGSEGV (@0x0) received by PID 79516 (TID 0x7fa85e564700) from PID 0; stack trace: ***
    @     0x7fa8c4bb7a92 (unknown)
    @     0x7fa8c08c0570 (unknown)
    @     0x7fa8c35fe14e doris::OlapScanNode::get_next()
    @     0x7fa8c36c2381 doris::PartitionedAggregationNode::open()
    @     0x7fa8c2fc14ad doris::PlanFragmentExecutor::open_internal()
    @     0x7fa8c2fc2a4d doris::PlanFragmentExecutor::open()
    @     0x7fa8c2f335e5 doris::FragmentExecState::execute()
    @     0x7fa8c2f37eaa doris::FragmentMgr::_exec_actual()
    @     0x7fa8c2f413bc std::_Function_handler<>::_M_invoke()
    @     0x7fa8c30e93b9 doris::ThreadPool::dispatch_thread()
    @     0x7fa8c30e29af doris::Thread::supervise_thread()
    @     0x7fa8c0678aa1 start_thread
    @     0x7fa8c0976c4d clone
    @                0x0 (unknown)
```

I am not sure about the exception mechanism. And because when we do binary release, it is hard to push a large file to
Apache SVN.

**Comment by yiguolei** [comment]
Both exception stack and signal core stack will lost line number info. For example I have rewrite glog's signal handler and could print more detail info during core.
For example, we could add a error code to tabelt.cpp, like this:
`
--- a/be/src/olap/tablet.cpp
+++ b/be/src/olap/tablet.cpp
@@ -82,6 +82,8 @@ Tablet::Tablet(TabletMetaSharedPtr tablet_meta, DataDir* data_dir,

     INT_COUNTER_METRIC_REGISTER(_metric_entity, flush_bytes);
     INT_COUNTER_METRIC_REGISTER(_metric_entity, flush_count);
+    std::vector<int>* a = nullptr;
+    a->push_back(1);
 }
`
It will cause segment fault like this:

`
  *** Aborted at 1647785336 (unix time) try "date -d @1647785336" if you are using GNU date ***
  *** SIGSEGV address not mapped to object (@0x8) received by PID 8750 (TID 0x7fe2423da700) from PID 8; stack trace: ***
  0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /data/ygl/code/github/incubator-doris/be/src/common/signal_handler.h:423
 1# 0x00007FE255D23270 in /lib64/libc.so.6
 2# doris::Tablet::Tablet(std::shared_ptr<doris::TabletMeta>, doris::DataDir*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /data/ygl/code/github/incubato    r-doris/be/src/olap/tablet.cpp:86
 3# doris::Tablet::create_tablet_from_meta(std::shared_ptr<doris::TabletMeta>, doris::DataDir*) at /data/ygl/code/github/incubator-doris/be/src/olap/tablet.cpp:61
 4# doris::TabletManager::load_tablet_from_meta(doris::DataDir*, long, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, bool) at /data/ygl    /code/github/incubator-doris/toolchain/include/c++/11/bits/shared_ptr.h:122
 5# std::_Function_handler<bool (long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), doris::DataDir::load()::{lambda(long, int, std::__cxx11::basic_str    ing<char, std::char_traits<char>, std::allocator<char> > const&)#2}>::_M_invoke(std::_Any_data const&, long&&, long&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > c    onst&) at /data/ygl/code/github/incubator-doris/toolchain/include/c++/11/bits/std_function.h:291
 6# std::_Function_handler<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >     const&), doris::TabletMetaManager::traverse_headers(doris::OlapMeta*, std::function<bool (long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&,     std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::b    asic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, s    td::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /data/ygl/code/github/incubator-doris/toolchain/include/c++/11/bits/std_function.h:291
 7# doris::OlapMeta::iterate(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, s    td::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&) at /data/ygl/code/github/incubator-doris/be/src/olap/olap_meta.cpp:183
 8# doris::TabletMetaManager::traverse_headers(doris::OlapMeta*, std::function<bool (long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, std::_    _cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /data/ygl/code/github/incubator-doris/be/src/olap/tablet_meta_manager.cpp:134
 9# doris::DataDir::load() at /data/ygl/code/github/incubator-doris/be/src/olap/data_dir.cpp:453
10# std::thread::_State_impl<std::thread::_Invoker<std::tuple<doris::StorageEngine::load_data_dirs(std::vector<doris::DataDir*, std::allocator<doris::DataDir*> > const&)::{lambda()#1}> > >::_M_run() a    t /data/ygl/code/github/incubator-doris/toolchain/include/c++/11/bits/std_thread.h:211
 11# execute_native_thread_routine in /data/ygl/code/github/incubator-doris/test_output/be/lib/palo_be
 12# start_thread in /lib64/libpthread.so.0
 13# clone in /lib64/libc.so.6
`

We could add it as an option, but not the default option. We could build a very small release binary for apache svn but not for 
 all developers.

**Comment by yiguolei** [comment]
#8545

**Comment by morningman** [comment]
Convert this PR to draft and rethink it later

**Review by yangzhg — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
merge for quick test

**Pull request merged**
