### PR TITLE
[fix](multi-catalog)add exception for unsupported hive input format

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

add exception for unsupported hive input format

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
Need to add test cases

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run feut

**Comment by wsjz** [comment]
run p0

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
