### PR TITLE
[refactor](group commit) refactor group commit wal code

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

This pr refactor wal code of group commit, and add some TODO to be fixed in later pr.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Comment by mymeiyi** [comment]
run clickbench

**Comment by mymeiyi** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
