### PR TITLE
[fix](docs) Fix 'DATE' type to 'DATEV2' type in Geting-Started

### LINKED ISSUE #19388: [Bug] Cannot create table with 'DATE' type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch: until e5a6b00

### What's Wrong?

- Error occurs when using the example provided by the official doc to create table.

image
image

- After searching the [official doc](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-reference/Data-Types/DATE/), doris recommends using 'DATEV2' after version 1.2.
- So is that suitable to change this in the offcicial doc?

### What You Expected?

Fix this little bug.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Centurybbx**
# Proposed changes

Issue Number: close #19388

## Problem summary

Change 'DATE' type to 'DATEV2' to avoid bug.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LemonLiTree** [comment]
Please modify the title format as [docs](fix)Fix 'DATE' type to 'DATEV2' type in Geting-Started

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
Do not change it.

**Comment by morningman** [comment]
I will close this PR.
DATEV2 is a temp name and we should use it explicitly.
cc @LemonLiTree @luzhijing

**Pull request closed without merging**
