### PR TITLE
[test](tvf) move p2 tvf tests from p2 to p0

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

Move test `test_tvf_p2`, `test_path_partition_keys` and `test_hdfs_tvf_compression` from external_table_p2 to external_table_p0,
so that developer can run it locally with docker env.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run p0 external

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run cloud_p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
