### PR TITLE
[Feature] (json)add json_contains function

### LINKED ISSUE #17216: [Feature] add some new json function
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

`json_contains` : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains)

`json_extract` : support return array, like : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-extract)

`json_unqoute` : [https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-unquote](https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-unquote)

`json_valid` : [https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-valid](https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-valid)

`-> operator` : [https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-column-path](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-column-path)

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yuxuan-luo**
## Proposed changes

Issue Number: close #17216

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by yuxuan-luo** [comment]
run buildall

**Comment by yuxuan-luo** [comment]
run buildall

**Comment by yuxuan-luo** [comment]
run buildall

**Review by nextdreamblue — APPROVED** [review]

**Review by Yulei-Yang — APPROVED** [review]
LGTM

**Pull request merged**
