### PR TITLE
[improvment](group_commit) Refector scan wal function

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
Refector scan wal function and change wal file name format.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
