### PR TITLE
[fix](s3-load) refactor s3 parallelism case and remove it to p2

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
