### PR TITLE
[opt](nereids) get table row count according to BE reported num and analyze result

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
we have 2 sources to get table rowCount
1. row count reported by BE
2. row count set by analyzer
when the reported row count is no more than zero, we use the row count set by analyzer.
for olap table, TableStatsMeta.getRowCount(indexId) returns the row count set by analzyer
for external table, TableStatsMeta.getRowCount(indexId) is not exists, and  we use the max of ColumnStatistics.count

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run performance

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run cloud_p0

**Comment by englefly** [comment]
run external

**Comment by englefly** [comment]
run performance

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
