### PR TITLE
[fix](tpcds-tool) Fix the echo in create-tpcds-tables.sh

### PR DESCRIPTION
**Pull request by dongsilun**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dongsilun** [comment]
run buildall

**Comment by dongsilun** [comment]
@xiaokang Is this pr still needed?

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
@AcKing-Sam I have picked this pr to branch-2.0 #33143

**Pull request merged**
