### PR TITLE
[improve](cloud txn insert) Add more ut; Remove duplicated table_id to reduce fdb value length

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

1. add more meta_service ut;
2. remove duplicated table_id to reduce fdb value length

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run cloud_ut

**Comment by mymeiyi** [comment]
run fe_ut

**Comment by mymeiyi** [comment]
run feut cloudut

**Comment by mymeiyi** [comment]
run cloudut

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run cloudut

**Comment by mymeiyi** [comment]
run cloudp1

**Comment by mymeiyi** [comment]
run cloud_p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
