### PR TITLE
[refactor](nereids)unify outputTupleDesc and projection be part

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

Because compatibility needs to be considered, we are merging the backend code here first.
In the past, the join node had its own set of project code, which has now been unified into the plan node.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by englefly** [comment]
run external

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Review by englefly — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
