### PR TITLE
[fix](load data) decommission replica don't load data when it misses versions

### PR DESCRIPTION
**Pull request by yujun777**
BUG:  when a decommission replica misses versions (last failed version > 0),   it will cause a bug:
1. It cann't do compaction due to it has miss versions;
2. It cann't  cloning the missing rowsets because it's decommissioned.

So if it continue to load data, its rowset will increase  util it cause error -235(TOO MANY VERSION).

Fix:  don't write data to the decommission replica if it miss rowsets.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run cloud_p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
