### PR TITLE
[fix](bitmap) fix wrong result of bitmap count functions for null values

### PR DESCRIPTION
**Pull request by jacktengg**
# Proposed changes

Issue Number: close #xxx

## Problem summary

bitmap count functions result is null when there are null values, which is not right:
```
mysql [(none)]>select bitmap_and_count(to_bitmap(1), null);
+----------------------------------------+
| bitmap_and_count(to_bitmap('1'), NULL) |
+----------------------------------------+
|                                   NULL |
+----------------------------------------+
1 row in set (0.04 sec)

mysql [(none)]>select bitmap_xor_count(to_bitmap(1), null);
+----------------------------------------+
| bitmap_xor_count(to_bitmap('1'), NULL) |
+----------------------------------------+
|                                   NULL |
+----------------------------------------+
1 row in set (0.03 sec)

mysql [(none)]>select bitmap_and_not_count(to_bitmap(1), null);
+--------------------------------------------+
| bitmap_and_not_count(to_bitmap('1'), NULL) |
+--------------------------------------------+
|                                       NULL |
+--------------------------------------------+
```
Theare should be consistent with `bitmap_count(bitmap_xxx())`:
```
mysql [(none)]>select bitmap_count(bitmap_and(to_bitmap(1), null));
+------------------------------------------------+
| bitmap_count(bitmap_and(to_bitmap('1'), NULL)) |
+------------------------------------------------+
|                                              0 |
+------------------------------------------------+
mysql [(none)]>select bitmap_count(bitmap_xor(to_bitmap(1), null));
+------------------------------------------------+
| bitmap_count(bitmap_xor(to_bitmap('1'), NULL)) |
+------------------------------------------------+
|                                              0 |
+------------------------------------------------+
mysql [(none)]>select bitmap_count(bitmap_and_not(to_bitmap(1), null));
+----------------------------------------------------+
| bitmap_count(bitmap_and_not(to_bitmap('1'), NULL)) |
+----------------------------------------------------+
|                                                  0 |
+----------------------------------------------------+
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run p0

**Comment by jacktengg** [comment]
run p0

**Comment by jacktengg** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.56 seconds
 stream load tsv:          458 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230317174815_clickbench_pr_116209.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
