### PR TITLE
[enhencement](binlog) Update table binlog config disable failure when db binlog is enable && modify table binlog more than one property.

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed change

Update table binlog config disable failure when db binlog is enable && modify table binlog more than one property.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.83 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.7 seconds inserted 10000000 Rows, about 336K ops/s
 storage size: 17169769084 Bytes

**Review by deadlinefen — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
