### PR TITLE
[fix](Nereids) string literal coercion of in predicate

### PR DESCRIPTION
**Pull request by mongo360**
## Proposed changes
pick from master https://github.com/apache/doris/pull/35200

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by mongo360** [comment]
run buildall

**Comment by xiaokang** [comment]
@mongo360 The testcase max_msg_size_of_result_receiver is failed after retry

**Pull request merged**
