### PR TITLE
[performance](executor) remove repeated call within the loop in validate_column

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

before
image

after
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run clickbench

**Comment by Mryange** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
