### PR TITLE
[BUG] If new group name is the same as old group name when mod table colocate group name, the group has been in an unstable state

### LINKED ISSUE #6694: [Bug]  If new group name is the same as old group name when mod table colocate group name, the group has been in an unstable state
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.13.11

### What's Wrong?

```shell
mysql> alter table test set("colocate_with"="test01");
Query OK, 0 rows affected (0.02 sec)

mysql> show proc "/colocation_group";
+---------------+---------------+----------+------------+----------------+------------------------+----------+
| GroupId       | GroupName     | TableIds | BucketsNum | ReplicationNum | DistCols               | IsStable |
+---------------+---------------+----------+------------+----------------+------------------------+----------+
| 191766.193070 | 191766_test01 | 191770   | 10         | 1              | bigint(20), bigint(20) | true     |
+---------------+---------------+----------+------------+----------------+------------------------+----------+
1 row in set (0.02 sec)

mysql> show proc "/colocation_group/191766.193070";
+-------------+------------+
| BucketIndex | BackendIds |
+-------------+------------+
| 0           | 10003      |
| 1           | 11001      |
| 2           | 10003      |
| 3           | 11001      |
| 4           | 10003      |
| 5           | 11001      |
| 6           | 10003      |
| 7           | 11001      |
| 8           | 10003      |
| 9           | 11001      |
+-------------+------------+
10 rows in set (0.02 sec)

# 相同的SQL在执行一次
mysql> alter table test set("colocate_with"="test01");
Query OK, 0 rows affected (0.02 sec)

mysql> show proc "/colocation_group";
+---------------+---------------+----------+------------+----------------+------------------------+----------+
| GroupId       | GroupName     | TableIds | BucketsNum | ReplicationNum | DistCols               | IsStable |
+---------------+---------------+----------+------------+----------------+------------------------+----------+
| 191766.193071 | 191766_test01 | 191770   | 10         | 1              | bigint(20), bigint(20) | false    |
+---------------+---------------+----------+------------+----------------+------------------------+----------+
1 row in set (0.01 sec)

mysql> show proc "/colocation_group/191766.193071"; # BucketIndex | BackendIds 信息却没了.....
Empty set (0.01 sec)
```

In this case, a bug is triggered.

Obviously, in the variable `group2BackendsPerBucketSeq` without this information.

```in master branch```

the group has been in an unstable state

```before 0.14.13 version```

When the master does ckpt, this bug will throw npe and ckpt will not work. The number of databases in BDB continues to rise

### What You Expected?

fix this bug

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
fix #6694

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6694) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liutang123** [comment]
LGTM

**Comment by liutang123** [comment]
If possible, please add an UT.

**Review by morningman — COMMENTED** [review]
Please add UT

**Comment by qzsee** [comment]
> Please add UT

UT have been added

**Comment by morningman** [comment]
> > Please add UT
> 
> UT have been added

Call ` UtFrameUtils.createDorisCluster(runningDir);` in UT will takes about 20 seconds to startup a mocked cluster.
So it is better not to `createDorisCluster` for every single unit test, it will takes longer time to run it.

That is my bad to not mention it before.
Could you please move your unit test to `ColocateTableTest.java`?

**Comment by qzsee** [comment]
> > > Please add UT
> > 
> > 
> > UT have been added
> 
> Call ` UtFrameUtils.createDorisCluster(runningDir);` in UT will takes about 20 seconds to startup a mocked cluster.
> So it is better not to `createDorisCluster` for every single unit test, it will takes longer time to run it.
> 
> That is my bad to not mention it before.
> Could you please move your unit test to `ColocateTableTest.java`?

That has been done

**Comment by morningman** [comment]
Sorry that you forget this:
```
LOG.warn("modify table[{}] group name same as old group name,skilled modify.", table.getName());
 LOG.warn("modify table[{}] group name same as old group name, skip.", table.getName());

```
image

**Comment by qzsee** [comment]
> Sorry that you forget this:
> 
> ```
> LOG.warn("modify table[{}] group name same as old group name,skilled modify.", table.getName());
>  LOG.warn("modify table[{}] group name same as old group name, skip.", table.getName());
> ```
> 
> image

Sorry, it has been corrected

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
