### PR TITLE
[fix](nestedtypes) fix nested type with is_exclusive

### PR DESCRIPTION
**Pull request by amorynan**
is_exclusive in column_array/map/struct has wrong semantic , we should make sure it's nested column is also is_exclusive which can make behavior right in some operator like join.

## Proposed changes
backport: https://github.com/apache/doris/pull/40398
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run beut

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Pull request merged**
