### PR TITLE
[fix](jdbc scan) `1=1` does not translate to `TRUE`

### LINKED ISSUE #19745: [Bug] sqlserver catalog/external table hit JDBC executor sql error when filter 1 = 1
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1

### What's Wrong?

[INTERNAL_ERROR]UdfRuntimeException: JDBC executor sql has error: 
CAUSED BY: SQLServerException: An expression of non-boolean type specified in a context where a condition is expected, near ')'.

### What You Expected?

should be no error

### How to Reproduce?

CREATE CATALOG sqlserver_catalog PROPERTIES (
    "type"="jdbc",
    "user"="abcd",
    "password"="abcd",
    "jdbc_url" = "jdbc:sqlserver://ip:port;database=abc;encrypt=true;trustServerCertificate=true;",
    "driver_url" = "mssql-jdbc-11.2.3.jre8.jar",
    "driver_class" = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
);

switch sqlserver_catalog ;

select * from Countries
where 1 = 1;

SQL Error [1105] [HY000]: errCode = 2, detailMessage = [INTERNAL_ERROR]UdfRuntimeException: JDBC executor sql has error: 
CAUSED BY: SQLServerException: An expression of non-boolean type specified in a context where a condition is expected, near ')'.

### Anything Else?

1.2.3 also have this problem

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #19745

For most database systems, they recognize where 1=1 but not where true, so we should send the original 1=1 to the database

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
