### PR TITLE
[fix](inverted index change) make mutex for ALTER_INVERTED_INDEX task and STORAGE_MEDIUM_MIGRATE task

### PR DESCRIPTION
**Pull request by Tanya-W**
## Proposed changes

make mutex for ALTER_INVERTED_INDEX task and STORAGE_MEDIUM_MIGRATE task

branch-2.0 pr https://github.com/apache/doris/pull/23033

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Tanya-W** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by Tanya-W** [comment]
run buildall

**Comment by Tanya-W** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.76 seconds
 stream load tsv:          536 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17162120544 Bytes

**Review by xiaokang — APPROVED** [review]

**Pull request merged**
