### PR TITLE
[chore](nereids) Added compatibility with mysql alias filter

### PR DESCRIPTION
**Pull request by Toms1999**
qt_filter_select4 """
       select * from filter_alias_test.test b where filter_alias_test.b.id = 1;
    """

    qt_filter_select5 """
         select * from internal.filter_alias_test.test b where internal.filter_alias_test.b.id = 1;
    """

### CODE REVIEW

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildadd

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
