### PR TITLE
[BugFix](TabletInvertedIndex) fix replica not found in TabletInvertedIndex

### PR DESCRIPTION
**Pull request by Johnnyssc**
## Proposed changes

adding and dropping backend in cluster may lead to the different replica in different backend have the same replica id, 

at that time, 'delete from table partition xxx' operation will be failed with exception:'Failed to commit txn 862, cause tablet 11653 succ replica num 1 < quorum replica num 2. ...'

and also, with the above delete operation, drop replica operation(class:TabletInvertedIndex) will be failed with WARN log:
' could not find tablet id for replica xxx, the tablet maybe dropped'

fix in master branch already merged: #34117

### CODE REVIEW

**Comment by Johnnyssc** [comment]
run buildall

**Comment by Johnnyssc** [comment]
run buildall

**Comment by Johnnyssc** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run buildall

**Comment by Johnnyssc** [comment]
run p0

**Review by GoGoWen — APPROVED** [review]
LGTM

**Pull request merged**
