### PR TITLE
[fix](audit) duplicate audit log for multi-statements at the same query

### PR DESCRIPTION
**Pull request by cambyzju**
Only v2.0 have this problem.

The key point is we should call `auditEventBuilder.reset()` to make deep copy for each statement.

Reproduce steps:
1. Make sure send these stmts in one query:
```
truncate table xxx.b;
truncate table xxx.c;
truncate table xxx.d;
truncate table xxx.e;
truncate table xxx.f;
```

2. Then we find the audit log is wrong, always print the last statement:
```
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
2024-07-16 16:03:43,221 [query] |Client=11.139.106.206:41702|User=xxx|Catalog=internal|Db=xxx|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=2|ScanBytes=0|ScanRows=0|ReturnRows=0|StmtId=946576|QueryId=1e82df5048f04c5b-8f2b86d66c7f72a4|IsQuery=false|isNereids=false|feIp=xxx|Stmt= truncate table xxx.f|CpuTimeMS=0|SqlHash=4f0d9bd6286943e5acd661e8bd8b2f72|peakMemoryBytes=0|SqlDigest=|TraceId=|WorkloadGroup=|FuzzyVariables=
```

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
