### PR TITLE
[pick2.0](Planner): don't push down isNull predicate into view (#26288)

### PR DESCRIPTION
**Pull request by keanji-x**
We can't push down `isNull` predicate into view

[#26288](https://github.com/apache/doris/pull/26012)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by XieJiann** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Pull request merged**
