### PR TITLE
[Enhancement] replace table options to keep original dropped table in recycle bin

### LINKED ISSUE #43537: [Enhancement] replace table options to keep original dropped table in recycle bin
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

replace table need to keep the original table in recycle bin if swap="false".
and also use should have option to force fully replace table without keeping original table in recycle bin.

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #43537

Related PR: #xxx

Problem Summary:

### Release note
Replace table options to keep original dropped table in recycle bin

### Check List (For Author)

- Test 
    - [ *] Regression test //added
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 
    Yes. older version will directly drop the original table when swap=false. After this PR, it will be kept in recycle bin.
user can use Force option in replace table to directly drop table without keeping in recycle bin.

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. //updated

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by dataroaring** [comment]
Please  add document in doris-website.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
