### PR TITLE
[fix](fe) Support set hive version when create hive external table

### LINKED ISSUE #20588: [Bug] Doris does not support specifying the hive version when creating hive external table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris version 2.0.0
hive version  2.1.2

### What's Wrong?

Doris does not support specifying the hive version when creating hive tables. Because a large amount of data needs to be imported by spark load, the hive version cannot be specified when creating a hive table, and the hive 2.3 version is used by default, which leads to an incompatibility error of the hive metastore version. 
exception:
`Invalid method name：'get_table_req'`

### What You Expected?

Doris already supports configuring hive version when registering catalog, so I think it should also support configuring hive version when creating hive external table.

### How to Reproduce?

use hive 2.1 version, create hive EXTERNAL TABLE as this:
create EXTERNAL TABLE `feature_metric_extend_aggregation_external`(
  `team_id` bigint ,
  `user_id` string ,
  `metric_code` string,
  `metric_value` string ,
  `version` string 
)
ENGINE=hive
properties
(
"database" = "dm_cdp",
"table" = "feature_metric_extend_aggregation",
"hive.metastore.uris" = "****"
);

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CodeCooker17**
## Proposed changes

Issue Number: close #20588 

support set hive version when create external table.

## Further comments
support set hive version when create external table.

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CodeCooker17** [comment]
run buildall

**Comment by CodeCooker17** [comment]
run buildall

**Comment by CodeCooker17** [comment]
create EXTERNAL TABLE `auto_user_gender_tag_v2_external`(
  `case_id` bigint,
  `tag_id` string,
  `tag_value` string
)
ENGINE=hive
properties
(
"database" = "dm_dmp",
"table" = "auto_user_gender_tag_v2",
"hive.metastore.uris" = "****",
"hive.version" = "2.1.2"
);

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.96 seconds
 stream load tsv:          538 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162095195 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Review by HonestManXin — APPROVED** [review]

**Comment by tarepanda1024** [comment]
LGTM

**Review by tarepanda1024 — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.83 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162239785 Bytes

**Comment by CodeCooker17** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.16 seconds
 stream load tsv:          547 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162173008 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
