### PR TITLE
[opt](Nereids) add switch / unset / kill / desc statement syntax

### PR DESCRIPTION
**Pull request by morrySnow**

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p0

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run cloud_p1

**Review by starocean999 — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
