### PR TITLE
[bug](function) fix count equal function return incorrect value

### LINKED ISSUE #18191: [Bug] countEqual function return incorrect value
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch：master
commit id：d7cb5cf3db2662d1a2e5adf52ab0b920cb4b1387

### What's Wrong?

The array function `countEqual` returns an incorrect value `1`, instead of the actual occurrence times `3` of the given element `5` in the array.
```
mysql> select countEqual([1,2,3,4,5,5,5], 5);
+-------------------------------------------+
| countequal(ARRAY(1, 2, 3, 4, 5, 5, 5), 5) |
+-------------------------------------------+
|                                         1 |
+-------------------------------------------+
1 row in set (0.03 sec)
```

### What You Expected?

Returns a number of the `value` in the given array. In `[1,2,3,4,5,5,5]`, it should return 3.
```
mysql> select countEqual([1,2,3,4,5,5,5], 5);
+-------------------------------------------+
| countequal(ARRAY(1, 2, 3, 4, 5, 5, 5), 5) |
+-------------------------------------------+
|                                         3 |
+-------------------------------------------+
```

### How to Reproduce?

_No response_

### Anything Else?

I am working on the `array_count` function and I am willing to submit this PR for `countEqual`, but it may take some time.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes

Issue Number: close #18191 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by zhangstar333** [comment]
run beut feut

**Pull request merged**
