### PR TITLE
[fix](cast) wrong result while cast const to double then to string

### LINKED ISSUE #31514: [Bug] cast constant to string get wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.4 && 2.0.5

### What's Wrong?

case:
 set experimental_enable_nereids_planner = true;
select cast(cast(10000.00001 as double) as string)

master  has right result:
```
MySQL [(none)]> select cast(cast(10000.00001 as double) as string);
+-------------------------------------------+
| cast(cast(10000.00001 as DOUBLE) as TEXT) |
+-------------------------------------------+
| 10000.00001                               |
+-------------------------------------------+
1 row in set (0.010 sec)
```

2.0.4 && 2.0.5 :
```
MySQL [(none)]> select cast(cast(10000.00001 as double) as string);
+---------------------------------------------+
| cast(cast(10000.00001 as DOUBLE) as STRING) |
+---------------------------------------------+
| 10000                                       |
+---------------------------------------------+
1 row in set (0.017 sec)
```

### What You Expected?

work well

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/31514

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Comment by cambyzju** [comment]
run p1

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by lide-reed** [comment]
what about float?

**Comment by cambyzju** [comment]
> what about float?

this pr only fix `float/double --> string`, later prs will try to fix `const literal --> double/float`,  and `string --> double/float`

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Pull request merged**
