### PR TITLE
Support AnalyticExpr in View

### PR DESCRIPTION
**Pull request by kangkaisen**
Doris view should support AnalyticExpr like normal table.

### CODE REVIEW

**Comment by kangkaisen** [comment]
Update this commit to apply the latest version code.

**Review by imay — APPROVED** [review]
LGTM

**Review by imay — CHANGES_REQUESTED** [review]
Can you change your commit message?

**Comment by kangkaisen** [comment]
Update the commit message.

**Review by imay — APPROVED** [review]

**Pull request merged**
