### PR TITLE
[Fix](Core) Fix core caused by null MowContext ptr

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

Query id: 0-0 ***
Aborted at 1688614857 (unix time) try "date -d @1688614857" if you are using GNU date ***
Current BE git commitID: b3db904847 ***
SIGSEGV address not mapped to object (@0x10) received by PID 1580278 (TID 1581464 OR 0x7efa1ede9700) from PID 16; stack trace: ***
0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/doris_master/doris/be/src/common/signal_handler.h:413

1# 0x00007F0BDD7800A7 in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

2# JVM_handle_linux_signal in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

3# 0x00007F0BDD77902C in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

4# 0x00007F0BFF89D090 in /lib/x86_64-linux-gnu/libc.so.6

5# doris::BetaRowsetWriter::_generate_delete_bitmap(int) at /home/zcp/repo_center/doris_master/doris/be/src/olap/rowset/beta_rowset_writer.cpp:158

6# doris::BetaRowsetWriter::flush_single_memtable(doris::vectorized::Block const*, long*, doris::FlushContext const*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/rowset/beta_rowset_writer.cpp:535

7# doris::Tablet::calc_segment_delete_bitmap(std::shared_ptr<doris::Rowset>, std::shared_ptr<doris::segment_v2::Segment> const&, std::vector<std::shared_ptr<doris::Rowset>, std::allocator<std::shared_ptr<doris::Rowset> > > const&, std::shared_ptr<doris::DeleteBitmap>, long, doris::RowsetWriter*) in /mnt/ssd01/doris-master/VEC_ASAN/be/lib/doris_be

8# doris::Tablet::calc_delete_bitmap(std::shared_ptr<doris::Rowset>, std::vector<std::shared_ptr<doris::segment_v2::Segment>, std::allocator<std::shared_ptr<doris::segment_v2::Segment> > > const&, std::vector<std::shared_ptr<doris::Rowset>, std::allocator<std::shared_ptr<doris::Rowset> > > const&, std::shared_ptr<doris::DeleteBitmap>, long, doris::RowsetWriter*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/tablet.cpp:3003

9# doris::Tablet::update_delete_bitmap(std::shared_ptr<doris::Rowset> const&, std::unordered_set<doris::RowsetId, doris::HashOfRowsetId, std::equal_to<doris::RowsetId>, std::allocator<doris::RowsetId> > const&, std::shared_ptr<doris::DeleteBitmap>, long, doris::RowsetWriter*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/tablet.cpp:3284

10# doris::TxnManager::publish_txn(doris::OlapMeta*, long, long, long, int, doris::UniqueId, doris::Version const&, doris::TabletPublishStatistics*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:378

11# doris::TxnManager::publish_txn(long, std::shared_ptr<doris::Tablet> const&, long, doris::Version const&, doris::TabletPublishStatistics*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:171

12# doris::TabletPublishTxnTask::handle() at /home/zcp/repo_center/doris_master/doris/be/src/olap/task/engine_publish_version_task.cpp:248

13# doris::ThreadPool::dispatch_thread() in /mnt/ssd01/doris-master/VEC_ASAN/be/lib/doris_be

14# doris::Thread::supervise_thread(void*) at /home/zcp/repo_center/doris_master/doris/be/src/util/thread.cpp:466

15# start_thread at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:478

16# __clone at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.62 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          87.9 seconds inserted 10000000 Rows, about 113K ops/s
 storage size: 17170239080 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706173134_clickbench_pr_173619.html

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.83 seconds
 stream load tsv:          502 seconds loaded 74807831229 Bytes, about 142 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17160775742 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230710174610_clickbench_pr_175867.html

**Comment by zhannngchen** [comment]
it's fixed by #21619, we can close this PR

**Pull request closed without merging**
