### PR TITLE
[fix](case) fix struct format out files

### PR DESCRIPTION
**Pull request by morningman**
follow up #37039
1. Some of constants are calculated in FE, it should output same format as in BE.
    Add `FormatOptions` to control the output format of complex types.

3. Modify some of result files of test cases.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
