### PR TITLE
[docs](docs) Update invalid pics of release note 1.1.0 and 2.0-beta 

### PR DESCRIPTION
**Pull request by KassieZ**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KassieZ** [comment]
run buildall

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by KassieZ** [comment]
run buildall

**Comment by KassieZ** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
