### PR TITLE
[fix](stream_load) can abort 2pc stream load when table dropped

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #xxx

## Problem summary

when stream load with 2pc, the table was droped before commit, it will get error commit or abort, trasaction can not finish.
if commit or abort ,will get error:
{
    "status": "ANALYSIS_ERROR",
    "msg": "errCode = 7, detailMessage = unknown table, tableId=52579"
}
after this pr, i can abort success.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run P0

**Comment by nextdreamblue** [comment]
run p0

**Comment by yiguolei** [comment]
buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
