### PR TITLE
[feature-WIP](query cache) cache tablets aggregate result, BE part

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

support cache tablets aggregate result

for example

SQL 1:
```sql
select key, sum(value)
from tbl
where dt between '2024-08-01' and '2024-08-10'
group by key
```

SQL 2:
```sql
select key, sum(value)
from tbl
where dt between '2024-08-5' and '2024-08-15'
group by key
```

SQL 1 will update the tablets aggregate result which partition between '2024-08-01' and '2024-08-10'.
Then SQL 2 will reuse the tablets aggregate which partition between '2024-08-05' and '2024-08-10', and compute aggregate which partition between '2024-08-11' and '2024-08-15'

We only support simple aggregate which not contains join with runtime filter, at present.

# How to use

```sql
set enable_query_cache=true;
```

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
