### PR TITLE
[fix](fe) fix MetricRepo.THRIFT_COUNTER_RPC_ALL NullPointException

### LINKED ISSUE #17550: [Bug] (Fe) FeServer.lambda$start NullPointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.2.1

### What's Wrong?

023-03-07 15:21:48,999 ERROR (thrift-server-pool-0|91) [ProcessFunction.process():47] Internal error processing ping
java.lang.NullPointerException: null
        at org.apache.doris.service.FeServer.lambda$start$0(FeServer.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at com.sun.proxy.$Proxy23.ping(Unknown Source) ~[?:?]
        at org.apache.doris.thrift.FrontendService$Processor$ping.getResult(FrontendService.java:2197) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
        at org.apache.doris.thrift.FrontendService$Processor$ping.getResult(FrontendService.java:2177) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313) ~[libthrift-0.13.0.jar:0.13.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
2023-03-07 15:21:49,017 INFO (replayer|81) [Env.replayJournal():2498] replayed journal id is 1617, replay to journal id is 1618 

### What You Expected?

without NullPointerException

### How to Reproduce?

1.  create 3 fe cluster with starting the 3 fe at the same time, the master fe may occur this problem

### Anything Else?

the problem is  caused by https://github.com/apache/doris/pull/11693

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
# Proposed changes

Issue Number: close #17550 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.46 seconds
 stream load tsv:          460 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230319033007_clickbench_pr_116552.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
