### PR TITLE
[fix][refactor] refactor schema init of externa table and some parquet issue

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Skip parquet file which has only 4 bytes length: PAR1
2. Refactor the schema init method of iceberg/hudi/hive table in hms catalog
    1. Remove some redundant methods of `getIcebergTable`
    2. Fix issue described in #23771
3. Support HoodieParquetInputFormatBase, treat it as normal hive table format
4. When listing file, skip all hidden dirs and files

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
