### PR TITLE
Revert "[fix](merge-on-write) add check for segment num (#14032)"

### PR DESCRIPTION
**Pull request by zhannngchen**
This reverts commit b7d2bec8ea3baaf8e4d52da5264f148ae827467b.  #14032

# Proposed changes

some old case may cause this check failed, revert it first, and will add it back after the case fixed.

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run p0

**Comment by ZhangGuoqiang666** [comment]
run p0

**Pull request merged**
