### PR TITLE
[fix](regression) Parameterize the S3 info for segcompaction regressi…

### PR DESCRIPTION
**Pull request by freemandealer**
…on (#16731)

Use regression conf instead hard-coded S3 info.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [x] Does it affect the original behavior
* [x] Has unit tests been added
* [x] Has document been added or modified
* [x] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by pingchunzhang** [comment]
LGMT

**Comment by freemandealer** [comment]
run p0

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by zhannngchen** [comment]
run p0

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
