### PR TITLE
[fix](schema-change) fix the bug of alter column nullable when double writing

### PR DESCRIPTION
**Pull request by luwei16**
## problem 

CREATE TABLE t (
    `k1` VARCHAR(30) NOT NULL,
    `v1` INT NOT NULL
)

alter table t modify column `v1` INT NULL

insert into value ('1', 2), ('1', 3);

core dump

## reason

Schema change leads to double writing, during double writing, the two schemas and slots are as follows
 
```
old tablet schema 
k1 varchar not null
v1 int not null
```
 
```
new tablet scheam
k1 varchar not null
v1 int null
```

```
slot
k1 varchar not null
v1 int not null
v1 int null
```

During the double writing process, when selecting slots through the schema, only the column names and types were compared, without comparing the nullable attributes, which led to the selection of the wrong slot. Since the slot determines the nullable attribute of the block, the nullable attribute of the columns in the block is different from that of the columns in the schema, resulting in a core dump.

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run p0

**Comment by luwei16** [comment]
run cloud_p0

**Comment by luwei16** [comment]
run cloud_p0

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by Hastyshell — APPROVED** [review]
LGTM

**Pull request merged**
