### PR TITLE
[fix](meta_scanner) fix meta_scanner process ColumnNullable

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
meta_scanner can not process ColumnNullable since FE dont know how to transmit a NULL value to BE.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
https://github.com/apache/doris/pull/25052

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]

**Pull request merged**
