### PR TITLE
[Fix](multi catalog)Change all partition names to lower case.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Iceberg table partition name may contain upper case characters, for example: City=xxx, Nation=xxx. But in Doris, all column names are in lower case. Here we transfer the partition name to lower case to keep consist with column name.

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
