### PR TITLE
[fix](join) Disable scan sharing for NAAJ

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by yiguolei — COMMENTED** [review]
Please add some regression test

**Review by yiguolei — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
