### PR TITLE
[doc] Update be-vscode-dev.md

### PR DESCRIPTION
**Pull request by EvanTheBoy**
Modified some syntax errors, making it more comfortable for developers to read.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by EvanTheBoy — COMMENTED** [review]
I think the modifications were reasonable.

**Comment by Yukang-Lian** [comment]
> I think the modifications were reasonable.

Of course, it is reasonable and remarkable! LGTM means 'looks good to me', you just need to wait for someone who have write access to merge this modification into Doris. By the way, thanks for your contribution!

**Comment by adonis0147** [comment]
Hi @EvanTheBoy , thanks for your contribution, it is a nice job.

**Comment by EvanTheBoy** [comment]
Thanks!




⊙Copy↗＆that!
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/doris"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/doris] [doc] Update be-vscode-dev.md (PR #15800)





 
Hi @EvanTheBoy , thanks for your contribution, it is a nice job.

**Comment by EvanTheBoy** [comment]
> > I think the modifications were reasonable.
> 
> Of course, it is reasonable and remarkable! LGTM means 'looks good to me', you just need to wait for someone who have write access to merge this modification into Doris. By the way, thanks for your contribution!

Thank you! This is the first time for me to do a "pull request", so there are probably something about how it works that I do not understand yet. Again, thank you for your patience and meticulous reply!

**Comment by Yukang-Lian** [comment]
> > > I think the modifications were reasonable.
> > 
> > 
> > Of course, it is reasonable and remarkable! LGTM means 'looks good to me', you just need to wait for someone who have write access to merge this modification into Doris. By the way, thanks for your contribution!
> 
> Thank you! This is the first time for me to do a "pull request", so there are probably something about how it works that I do not understand yet. Again, thank you for your patience and meticulous reply!

😄haha, You're welcome. If you any question, we are willing to help! Looking forward to your next contribution. Have a great day!

**Pull request merged**
