### PR TITLE
[Feature](vec)(quantile_state): support  quantile state in vectorized engine

### LINKED ISSUE #15868: [Feature] support QuantileState in vectorized engine
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

From  #8234  pre-aggregation for quantile type is supported in non-vectorized engine.

### Use case

Already added in #8234

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by spaces-X**
# Proposed changes

Issue Number: close #15868  
## Problem summary

1. support related quantile_state function in vectorized engine
2. add up some regression test cases for the quantile_state type.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by spaces-X** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by spaces-X** [comment]
run buildall

**Comment by spaces-X** [comment]
run buildall

**Comment by spaces-X** [comment]
run P0 Regression

**Comment by spaces-X** [comment]
run compile

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
