### PR TITLE
[enhancement](docs) Clarify requirement for JDK exact version 8

### PR DESCRIPTION
**Pull request by larshelge**
Backport to `branch-2.0` of `master` branch commit https://github.com/apache/doris/commit/a346408717ad9e1da6d4f304742c9f85fd84ace3

### CODE REVIEW

**Comment by larshelge** [comment]
run buildall

**Comment by larshelge** [comment]
run buildall

**Comment by larshelge** [comment]
`run buildall`

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by httpshirley — APPROVED** [review]

**Comment by httpshirley** [comment]
run buildall

**Comment by larshelge** [comment]
run buildall

**Pull request merged**
