### PR TITLE
[fix](regression) Fix flaky test test_partial_update_2pc_schema_change

### PR DESCRIPTION
**Pull request by bobhan1**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
