### PR TITLE
[feature](merge-cloud) Add init CloudEnv and CloudInternalCatalog

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by w41ter — APPROVED** [review]

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
