### PR TITLE
[Fix](RoutineLoad)MultiTable Filter tables that are not OlapTable

### PR DESCRIPTION
**Pull request by CalvinKirs**
### Description
multi-table will take all tables and then convert them into OlapTable, thus causing View type conversion errors.
### Error log
```
while process request for streamLoadMultiTablePut
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.apache.doris.service.FeServer.lambda$start$0(FeServer.java:59) ~[doris-fe.jar:1.2-SNAPSHOT]
	at com.sun.proxy.$Proxy37.streamLoadMultiTablePut(Unknown Source) ~[?:?]
	at org.apache.doris.thrift.FrontendService$Processor$streamLoadMultiTablePut.getResult(FrontendService.java:3392) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.thrift.FrontendService$Processor$streamLoadMultiTablePut.getResult(FrontendService.java:3372) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250) ~[libthrift-0.16.0.jar:0.16.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
Caused by: java.lang.ClassCastException: Cannot cast org.apache.doris.catalog.View to org.apache.doris.catalog.OlapTable
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_131]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_131]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_131]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_131]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_131]
	at org.apache.doris.service.FrontendServiceImpl.streamLoadMultiTablePut(FrontendServiceImpl.java:1889) ~[doris-fe.jar:1.2-SNAPSHOT]
	... 13 more
```
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run 
FE UT (Doris FE UT) —

**Comment by CalvinKirs** [comment]
run feut

**Comment by CalvinKirs** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run p1

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run p0 
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
