### PR TITLE
[fix](planner) remove and retain input slot for aggregate slot which is not materialized

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

fix bug introduced by #32092。do not remove input slot which need retain

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by starocean999** [comment]
LGTM

**Pull request merged**
