### PR TITLE
[fix](fe) variable enable_odbc_tanscation is misspelled

### PR DESCRIPTION
**Pull request by Tech-Circle-48**
## Proposed changes

Issue Number: close #xxx

Variable enable_odbc_tanscation is misspelled, change to enable_odbc_tansaction

### CODE REVIEW

**Comment by Tech-Circle-48** [comment]
run rebuildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Comment by Tech-Circle-48** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request closed without merging**
