### PR TITLE
[performance](move-memtable) async close tablet streams

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Asynchronously close tablet streams to speed up load stream close.

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by liaoxin01** [comment]
All tablet close operations should be handled by a single thread to avoid saturating the heavy_work thread pool when there are many tablets.

**Comment by kaijchen** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
