### PR TITLE
[regression](insert)add hive DDL and CTAS regression case

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

Issue Number: https://github.com/apache/doris/issues/31442

dependent on https://github.com/apache/doris/pull/32824

1. add ddl(create and drop) test
2. add ctas test
3. add complex type test

TODO:
bucketed table test
truncate test
add/drop partition test

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by zddr — APPROVED** [review]

**Pull request merged**
