### PR TITLE
[fix](compaction) disable cumu delete rowset from performing ordered data compaction

### PR DESCRIPTION
**Pull request by luwei16**
## problem

When enable_delete_when_cumu_compaction = true, multiple delete rowsets may be merged into an empty data rowset through ordered data compaction, causing the delete predicate to be lost.

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by luwei16** [comment]
run ShellCheck

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
