### PR TITLE
[fix](memory) Avoid modify memory tracker when Allocator alloc memory

### PR DESCRIPTION
**Pull request by xinyiZzz**
fix:
img_v3_02e7_e9847bd3-89ad-4e9e-8fa1-76109a5386fg

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Pull request closed without merging**
