### PR TITLE
[cases](regresstests) update regress test for array/map nested insert into negetive cases

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
update regress test for array/map nested insert into negetive cases

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p1

**Comment by amorynan** [comment]
run p1

**Comment by amorynan** [comment]
@shuke987

**Review by shuke987 — APPROVED** [review]

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
