### PR TITLE
[feature](clucene) coverage compilation option added

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run p0

**Comment by zzzxl1993** [comment]
run PipelineX

**Comment by zzzxl1993** [comment]
run p0

**Review by qidaye — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run p0

**Comment by zzzxl1993** [comment]
run pipelinex_p0

**Comment by zzzxl1993** [comment]
run be-ut

**Comment by zzzxl1993** [comment]
run be_ut

**Comment by zzzxl1993** [comment]
run fe_ut

**Comment by zzzxl1993** [comment]
run ut

**Comment by zzzxl1993** [comment]
run buildall

**Pull request merged**
