### PR TITLE
[fix](paimon)fix `like` predicate

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

fix `like` predict

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by morningman — DISMISSED** [review]
LGTM, please add test cases

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
