### PR TITLE
[Improve](regresscases)fix function array index with null param and add regress cases for ar…

### PR DESCRIPTION
**Pull request by amorynan**
1. fix array index with null param
2. add create inverted index regress cases for array nested all type in dup/mor/mow table
3. add query case for array all type with inverted index

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run external

**Comment by amorynan** [comment]
run external

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
