### PR TITLE
[fix](typo) fix typo "partiton" to "partition"

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Fix typo "partiton" to "partition".

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Pull request closed without merging**
