### PR TITLE
[fix](regression) fix auth case for move-memtable streamload test

### PR DESCRIPTION
**Pull request by freemandealer**
## Proposed changes

fix regression complain:
```
Access denied for user 'default_cluster:common_user@127.0.0.1' (using password: YES)","count":0}
java.lang.IllegalArgumentException: Text must not be null or empty
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by shuke987 — APPROVED** [review]

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run external

**Comment by dataroaring** [comment]
run buildall

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run p0

**Review by kaijchen — APPROVED** [review]
LGTM

**Pull request merged**
