### PR TITLE
[Enhencement](test) enhencement regression test of java udf

### PR DESCRIPTION
**Pull request by zhangstar333**
# Proposed changes

when run regression test of java udf many times.
if failed in some reason, the next time will meet error like: **function already exist**

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run build all

**Review by yiguolei — APPROVED** [review]
lgtm

**Review by yiguolei — COMMENTED** [review]
run buildall

**Comment by yiguolei** [comment]
./run buildall

**Pull request merged**
