### PR TITLE
[fix](array_range) fix array_range func for large param which should return error

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
if array_range with large size , which will make be oom , so we should avoid this with max_array_size_as_field  
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]

**Comment by amorynan** [comment]
run beut

**Pull request merged**
