### PR TITLE
[fix](memory) Fix hash table buf initialize null pointer

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Issue Number: close #xxx

When compiling `FunctionArrayEnumerateUniq::_execute_by_hash`, `AllocatorWithStackMemory::free(buf)`
will be called when `delete HashMapContainer`. the gcc compiler will think that `size > N` and `buf` is not heap memory,
and report an error `' void free(void*)' called on unallocated object 'hash_map'`

This only fails on doris docker + gcc 11.1, no problem on doris docker + clang 16.0.1,
no problem on ldb_toolchanin gcc 11.1 and clang 16.0.1.

But for this compilation problem, I still don’t understand why gcc in docker will report an error. If the hash map is not initialized and buf is not alloc, it should not go to allocator::free. If you are familiar with the principle of compilation, hope you can guide me, thxs!~

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run arm

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run arm

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run arm

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run arm

**Comment by xinyiZzz** [comment]
run clickbench

**Comment by xinyiZzz** [comment]
run arm

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.8 seconds
 stream load tsv:          460 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          61 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          68.9 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230629192813_clickbench_pr_170111.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.43 seconds
 stream load tsv:          455 seconds loaded 74807831229 Bytes, about 156 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          67.6 seconds inserted 10000000 Rows, about 147K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230630031302_clickbench_pr_170195.html

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
