### PR TITLE
 [Fix](multi-catalog) Filter invisible files for hive table.

### PR DESCRIPTION
**Pull request by dutyu**
## Proposed changes

image

```java
errCode = 2, detailMessage = (xxx)[INTERNAL_ERROR]failed to init reader for file /user/hive/warehouse/xxx.db/xxx/pday=20230717/rule_set_no=xxx/.part-11a8fa15-9c2d-4860-994e-f47f23c2563e-5-829310.inprogress.c0dc4be1-1073-47f3-a3ac-02cdbb262db5, err: [INTERNAL_ERROR]Init OrcReader failed. reason = File size too small
```

In fact, hive can not read files which startswith "." or "_", so we need filter these files.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dutyu** [comment]
run buildall

**Comment by dutyu** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.31 seconds
 stream load tsv:          503 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          30.1 seconds inserted 10000000 Rows, about 332K ops/s
 storage size: 17162282951 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
