### PR TITLE
[refractor](regression-test) sort out test cases of external tables

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

sort out the test cases of external table.
After modify, there are 2 directories:

1. `external_table_p0`: all p0 cases of external tables: hive, es, jdbc and tvf
2. `external_table_p2`: all p2 cases of external tables: hive, es, mysql, pg, iceberg and tvf

So that we can run it with one line command like:

```
sh run-regression-test.sh --run -d external_table_p0,external_table_p2
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by zhangguoqiang666 — APPROVED** [review]
good job

**Comment by zhangguoqiang666** [comment]
run p1

**Review by zhangguoqiang666 — COMMENTED** [review]
checked

**Review by BePPPower — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
