### PR TITLE
[Enhancement] (nereids)implement showDataTypesCommand in nereids

### LINKED ISSUE #42743: [Enhancement] (nereids)implement showDataTypesCommand in nereids
showDataTypes command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showDataTypes command in nereids:
unsupportedshowDataTypesStatement
``` SHOW DATA TYPES                                                               ```

### PR DESCRIPTION
**Pull request by msridhar78**
### What problem does this PR solve?

Issue Number: close #42743 

[Enhancement] (nereids)implement showDataTypesCommand in nereids

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by msridhar78** [comment]
run buildall

**Comment by msridhar78** [comment]
run buildall

**Comment by msridhar78** [comment]
run p0

**Comment by msridhar78** [comment]
run buildall

**Review by LiBinfeng-01 — APPROVED** [review]

**Comment by msridhar78** [comment]
run buildall

**Comment by msridhar78** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by msridhar78** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
