### PR TITLE
[nereids] bucket shuffle downgrade expansion

### PR DESCRIPTION
**Pull request by xzj7019**
## Proposed changes

Expand bucket shuffle downgrade condition, which originally requiring a single partition after pruning, basic table and bucket number < para number. Currently, we expect this option can be used for disabling bucket shuffle more efficiently, without above restrictions.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xzj7019** [comment]
run buildall

**Comment by xzj7019** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
run cloud_p1

**Pull request merged**
