### PR TITLE
[fix](arrow-flight) Modify regression test Arrow version to 14.0.1

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Same as #28093

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by hello-stephen** [comment]
run compile

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]

**Pull request merged**
