### PR TITLE
[fix](recycler) Implement missing delete_prefix() of hdfs accessor

### PR DESCRIPTION
**Pull request by gavinchou**
To test it,
1. enable commit_rowset fail with injection point
2. issue a streamload
3. check the recycler log or storage vault the uncommitted rowset recycled
```
curl 'be_ip:http_port/api/injection_point/enable'
curl 'be_ip:http_port/api/injection_point/clear'
curl "be_ip:http_port/api/injection_point/set?name=CloudMetaMgr::commit_rowset&behavior=return_error"
curl -XPUT --location-trusted -vv -T tmp/1.csv -H'format:csv' -H 'column_separator:,' -H'timeout:60' -uroot: be_ip:http_port/api/db1/t2/_stream_load

curl 'be_ip:http_port/api/injection_point/clear'
curl 'be_ip:http_port/api/injection_point/disable'
```

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Review by bobhan1 — APPROVED** [review]

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
