### PR TITLE
[refactor](standard)BE:Initialize pointer variables in the class to nullptr by default

### PR DESCRIPTION
**Pull request by hongkun-Shao**
…r by default

## Proposed changes

In the source code of the Doris be module, the default initialization of pointer member variables in the class is not uniform, and there is no default initialization, {nullptr},=nullptr. So in this large-scale unification, use=nullptr to set it.
1. Use = nullptr
   - T *
   - const T *
   - T **
   - const T **
   - shared_ptr<T>
   - unique_ptr<T>
2. Don't set default initialization
   - T * const
3. Set {nullptr} to = nullptr
4. Unchanged parts
   - extern
   - null/NULL
   - Customized pointers through using, typedef, and other methods
  
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
> 4. Unchanged parts
>    
>    * extern
>    * null/NULL
for traditional usages like `NULL`, could you change them to `nullptr` by the way?

**Comment by hongkun-Shao** [comment]
> > 4. Unchanged parts
> >    
> >    * extern
> >    * null/NULL
> 
> for traditional usages like `NULL`, could you change them to `nullptr` by the way?

of course, It's my pleasure。

**Comment by zclllyybb** [comment]
run buildall

**Comment by hongkun-Shao** [comment]
run buildall

**Comment by hongkun-Shao** [comment]
run buildall

**Comment by hongkun-Shao** [comment]
run buidlBE UT

**Comment by yiguolei** [comment]
run beut

**Comment by yiguolei** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
