### PR TITLE
[enhancement][docker]update kafka docker file for branch-2.0"

### PR DESCRIPTION
**Pull request by XuJianxu**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Fix the routine load test case on branch-2.0 by changing the Kafka topic data producer method. In the new approach, the routine load test case will produce Kafka topic data in the regression-test script instead of using run-thirdparties-docker.sh.

### Check List (For Committer)

- Test 

    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run p0

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run p0

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
