### PR TITLE
[bug](json)Fix the problem of be down caused by json path ending with \

### PR DESCRIPTION
**Pull request by LemonLiTree**
## Proposed changes

before:
```sql
mysql> select json_extract( '{"k1\": "v1"}', "$.k1\\");
ERROR 1105 (HY000): RpcException, msg: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```
now
```sql
mysql> select json_extract( '{"k1\\": "v1"}', "$.k1.");
+----------------------------------------+
| json_extract('{"k1\": "v1"}', '$.k1.') |
+----------------------------------------+
| NULL                                   |
+----------------------------------------+
1 row in set (0.02 sec)

mysql> select jsonb_extract( '{"k1\\": "v1"}', "$.k1\\");
ERROR 1105 (HY000): errCode = 2, detailMessage = (127.0.0.1)[CANCELLED]Json path error: Invalid Json Path for value: $.k1\
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
