### PR TITLE
Revert "[fix](memory safe) Fix block-reader memory alloc failed make …

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
…be core dump. (#36299)"

This reverts commit 4bb46a8d580cbcd35200af5e4f23830ceb9c3ef2.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run p0

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Review by zhangstar333 — DISMISSED** [review]

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
