### PR TITLE
[fix](cast) wrong result while cast const to double then to string #31657

### PR DESCRIPTION
**Pull request by xiaokang**
cherry pick from #31657

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by cambyzju** [comment]
duplicate with https://github.com/apache/doris/pull/31686

**Comment by xiaokang** [comment]
@cambyzju Sorry, I just notice your comment after merged this PR. And I merged yours too. Do I need to revert this one?

**Comment by cambyzju** [comment]
> @cambyzju Sorry, I just notice your comment after merged this PR. And I merged yours too. Do I need to revert this one?

I think we should revert one, revert any one is OK to me.

**Pull request merged**
