### PR TITLE
[fix](config) change segment_cache_fd_percentage and inverted_index_fd_number_limit_percent default value

### PR DESCRIPTION
**Pull request by xiaokang**
change segment_cache_fd_percentage and inverted_index_fd_number_limit_percent default value from 40% to 20% to avoid too many open files.

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
