### PR TITLE
[fix](fe ut) fix unstable ut DecommissionTest

### PR DESCRIPTION
**Pull request by yujun777**
After decommission a be, its 600 tablets will relocate to other three backends.

tolerate a tiny unbalance between the tablet num of the three  backends;

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LTGM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
