### PR TITLE
[Fix](doc)Fix word spelling errors

### PR DESCRIPTION
**Pull request by xingyingone**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
run  buildall

**Comment by xingyingone** [comment]
run feut

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Review by alexxing662 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
