### PR TITLE
[enhancement](index compaction) Enable index compaction by default

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
