### PR TITLE
[refactor](delete) refactor FE DeleteHandler related logic

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

1. move lifecycle of delete job and DeleteJob creation logic into DeleteJob class, to split the coupling logic.
2. remove some redundant logic, like checkV2 in DeleteHandler
3. move the execution entry point of delete stmt from DdlExecutor to StmtExecutor, to make it easier to expose the status.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
