### PR TITLE
[enhancement](profilev2) add some fields for profile v2

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

Add 3 counters for ExecNode:
1. ExecTime - Total execution time(excluding the execution time of children).
2. OutputBytes - The total number of bytes output to parent.
3. BlockCount - The total count of blocks output to parent.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
