### PR TITLE
[improvement](backup) Add BackupJobInfo with tableCommitSeqMap

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add BackupJobInfo with tableCommitSeqMap

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by deadlinefen** [comment]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 40.98 seconds
 stream load tsv:          459 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          68.9 seconds inserted 10000000 Rows, about 145K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230627170622_clickbench_pr_168987.html

**Pull request merged**
