### PR TITLE
[BUG] Key is 'True',Extra is 'NONE' when add rollup for DUP table

### LINKED ISSUE #6762: [Bug] Key is 'True',Extra is 'NONE' when add rollup for DUP table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
mysql> desc test2 all;
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+
| IndexName | IndexKeysType | Field | Type          | Null | Key   | Default | Extra | Visible |
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+
| test2     | DUP_KEYS      | a     | BIGINT        | Yes  | true  | NULL    |       | true    |
|           |               | b     | BIGINT        | Yes  | true  | NULL    |       | true    |
|           |               | c     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
|           |               | d     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
|           |               | e     | VARCHAR(1024) | Yes  | false | NULL    | NONE  | true    |
|           |               | f     | VARCHAR(1024) | Yes  | false | NULL    | NONE  | true    |
|           |               |       |               |      |       |         |       |         |
| r1        | DUP_KEYS      | c     | BIGINT        | Yes  | true  | NULL    | NONE  | true    |
|           |               | e     | VARCHAR(1024) | Yes  | true  | NULL    | NONE  | true    |
|           |               | a     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+

```
column `a,b` are `key`.  others are `value` .  I added rollup r1.  `c,e` become `key`, `Key` is true but `Extra` is `NONE`. `Extra` should be empty

### What You Expected?

Show the correct

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
## Proposed changes

fix #6762

The result is displayed after the repair

```
mysql> desc test2 all;
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+
| IndexName | IndexKeysType | Field | Type          | Null | Key   | Default | Extra | Visible |
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+
| test2     | DUP_KEYS      | a     | BIGINT        | Yes  | true  | NULL    |       | true    |
|           |               | b     | BIGINT        | Yes  | true  | NULL    |       | true    |
|           |               | c     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
|           |               | d     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
|           |               | e     | VARCHAR(1024) | Yes  | false | NULL    | NONE  | true    |
|           |               | f     | VARCHAR(1024) | Yes  | false | NULL    | NONE  | true    |
|           |               |       |               |      |       |         |       |         |
| r1        | DUP_KEYS      | c     | BIGINT        | Yes  | true  | NULL    |       | true    |
|           |               | e     | VARCHAR(1024) | Yes  | true  | NULL    |       | true    |
|           |               | a     | BIGINT        | Yes  | false | NULL    | NONE  | true    |
+-----------+---------------+-------+---------------+------+-------+---------+-------+---------+

```

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6762) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Could you please add UT for this?
Can be in RollupJobV2Test.java

**Comment by qzsee** [comment]
> Could you please add UT for this?
> Can be in RollupJobV2Test.java

I tried to add ut in `RollupJobV2Test.java`

**Review by morningman — COMMENTED** [review]
Seems that if we call `column.setIsKey(true);`, there is alway following `column.setAggregationType(null, false);`.
So how about set aggregation type to `null false` in `setIsKey()` method when key is true?
Otherwise, it is error prone.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
