### PR TITLE
[improvement](processlist) Add more information for `show processlist`

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Here is the result of `show processlist`
```
mysql> show processlist;
+------+------+--------------------+-----------------+-------+---------+------+-------+------+
| Id   | User | Host               | Cluster         | Db    | Command | Time | State | Info |
+------+------+--------------------+-----------------+-------+---------+------+-------+------+
|   84 | root | 127.0.0.1:48794    | default_cluster | demo  | Query   |    0 |       |      |
|   88 | root | 192.168.1.90:56191 | default_cluster |       | Sleep   |  752 |       |      |
|   89 | root | 192.168.1.90:56194 | default_cluster |       | Sleep   |  198 |       |      |
|   90 | root | 192.168.1.90:56196 | default_cluster | tpcds | Sleep   |   31 |       |      |
|   91 | root | 192.168.1.90:56197 | default_cluster | demo  | Sleep   |  749 |       |      |
+------+------+--------------------+-----------------+-------+---------+------+-------+------+
```

In previous versions, the `State` and `Info` columns did not display any content, which was not expected. So I fix this problem and remove the unused `Cluster` column.

As the same time, I added some additional columns. The final changes are as follows.

```
mysql> show processlist;
+------------------+------+------+-----------------+---------------------+------------+-------+---------+------+-------+-----------------------------------+------------------+
| CurrentConnected | Id   | User | Host            | LoginTime           | Catalog    | Db    | Command | Time | State | QueryId                           | Info             |
+------------------+------+------+-----------------+---------------------+------------+-------+---------+------+-------+-----------------------------------+------------------+
| Yes              |    0 | root | 127.0.0.1:54318 | 2023-09-07 15:18:53 | internal   |       | Query   |    0 | OK    | 915e90179c434adf-9af2eedb03fd19bd | show processlist |
|                  |    1 | root | 127.0.0.1:54834 | 2023-09-07 15:19:10 | jdbc_mysql | mysql | Sleep   |    3 | EOF   | 3255a97e7e04c69-a4f0b837ce742ff9  | select 1         |
+------------------+------+------+-----------------+---------------------+------------+-------+---------+------+-------+-----------------------------------+------------------+
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buidlall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Comment by yagagagaga** [comment]
run p0

**Pull request merged**
