### PR TITLE
[fix](session) fix select * from variables system table

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

after #23017, information_schema.session_variables and information_schema.global_variables had 2 new columns, but SchemaVariablesScanner just 2 columns. when select * from *_variables,will get 'no match column for this column' error

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
I have tried to do similar fix in https://github.com/apache/doris/pull/30998, but not merged.

**Review by morningman — COMMENTED** [review]
need test case

**Comment by zhiqiang-hhhh** [comment]
> > I have tried to do similar fix in #30998, but not merged.
> 
> ... why not

We want to use something like a general table value function to handle all similar situation. For example, it could be used like `select * from system_tables("information_schema.session_variables")`

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run cloud_p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yulei-Yang — APPROVED** [review]

**Pull request merged**
