### PR TITLE
[Enhancement] partition name of partitions should be same

### LINKED ISSUE #32319: [Enhancement] partition name of partitions should be same
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

https://github.com/apache/doris/discussions/32183

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #32319

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Review by gavinchou — COMMENTED** [review]
How does this PR relate to CLOUD (AKA separation of storage and compute")?

**Comment by cjj2010** [comment]
> How does this PR relate to CLOUD (AKA separation of storage and compute")?

I'm not sure if it's related to cloud yet, it's just a temporary association

**Review by zclllyybb — COMMENTED** [review]
Thanks for your contribution. Please don't merge this PR until I reviewed it completely.

**Review by HappenLee — CHANGES_REQUESTED** [review]
behavier change @zclllyybb please check

**Review by zclllyybb — COMMENTED** [review]
The design of this behaviour is deliberate, and many behaviours in our code rely on this piece. so I prefer not to merge this pr. sorry for that

**Pull request closed without merging**
