### PR TITLE
[fix]fix be core when migration tablet to other disk

### LINKED ISSUE #36809: [Bug] be core when migration tablet to other disk
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.11

### What's Wrong?

The be will core when send tablet migration request, i.e. `http://beIP:8040/api/tablet_migration?goal=run&tablet_id=7003921&schema_hash=1433840853&disk=/mnt/dfs/5/doris_be_storage`.

The `be.out` log is: 
image

### What You Expected?

It should return the error message and do not make be core.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by z404289981**
image
The asynchronous task reference captures a local variable

## Proposed changes

Issue Number: close #36809

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Comment by bobhan1** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by z404289981** [comment]
@bobhan1 @gavinchou @dataroaring Hi, Some regression cases failed and have nothing to do with modifications. Could you please tell me if this is a known issue in the master branch? thank you

**Comment by bobhan1** [comment]
run buildall

**Comment by z404289981** [comment]
run external

**Comment by z404289981** [comment]
run buildall

**Comment by z404289981** [comment]
run cloud_p0

**Comment by z404289981** [comment]
run arm_p0

**Comment by z404289981** [comment]
run cloud_p0

**Comment by z404289981** [comment]
run cloud_p0

**Comment by z404289981** [comment]
run cloud_p0

**Comment by z404289981** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
