### PR TITLE
[deps](benchmark) bump benchmakr from 1.5.6 -> 1.8.0

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

To support some new methods used in #21074

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 43.85 seconds
 stream load tsv:          454 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          70.3 seconds inserted 10000000 Rows, about 142K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230625031621_clickbench_pr_166935.html

**Comment by xxiao2018** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]

**Comment by kaka11chen** [comment]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
