### PR TITLE
[Bug](auto-partition) should check the expr of auto range partition

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

```

AUTO PARTITION BY RANGE (FUNC_CALL_EXPR)
(
)

FUNC_CALL_EXPR ::= date_trunc ( <partition_column>, '<interval>' )

should check the expr, now auto range partition only support date_trunc

```

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by starocean999** [comment]
please check convertToLegacyAutoPartitionExprs method in PartitionTableInfo.java. I think it needs to be updated for nereids too

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
