### PR TITLE
[chore](test) Add testing util sync point

### PR DESCRIPTION
**Pull request by gavinchou**
Add sync point testing util for future use: tests for file cache, s3 related operation and file system related operations.

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
