### PR TITLE
[test] Add scalable regression testing framework

### PR DESCRIPTION
**Pull request by 924060929**
# Proposed changes

Add scalable regression testing framework(#7584)
contains
- Test framework making by groovy, and support built-in **readable DSL** named as `Action`
- Demo exists in `${DORIS_HOME}/regression-test/data/demo`
- Chinese doc exist in `${DORIS_HOME}/docs/zh-CN/developer-guide/regression-testing.md`

English document coming soon

## Problem Summary:

Add regression test framework

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No
3. Has document been added or modified: Yes
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

### CODE REVIEW

**Comment by yiguolei** [comment]
Great~~~~~~~~~~

**Comment by caiconghui** [comment]
wonderful!

**Comment by yiguolei** [comment]
Maybe we could just merge this PR and improve it later?

**Review by morningman — APPROVED** [review]
> Maybe we could just merge this PR and improve it later?

Yes, this is a relatively independent module. I think we can quickly merge it first, so that everyone can participate in and iterate quickly.

So it LGTM.

And @924060929 , Could you please send a email to dev@doris.
The main content is to briefly introduce the motivation and purpose of this testing framework.
so that we can discuss the follow-up in the mailing list?

**Comment by 924060929** [comment]
> > Maybe we could just merge this PR and improve it later?
> 
> Yes, this is a relatively independent module. I think we can quickly merge it first, so that everyone can participate in and iterate quickly.
> 
> So it LGTM.
> 
> And @924060929 , Could you please send a email to dev@doris. The main content is to briefly introduce the motivation and purpose of this testing framework. so that we can discuss the follow-up in the mailing list?

okey

**Pull request merged**
