### PR TITLE
[fix](meta) fix bug for using full name in show_full_columns stmt

### PR DESCRIPTION
**Pull request by Yulei-Yang**
Issue:
image

show_full_columns stmt only support internal catalog.
企业微信截图_8c918d1c-962b-49b8-acad-ae00ac8e1cf3

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Review by morningman — COMMENTED** [review]
Could you please add test cases?

**Review by nextdreamblue — DISMISSED** [review]

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
> Could you please add test cases?
done

**Comment by nextdreamblue** [comment]
LGTM

**Review by nextdreamblue — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
