### PR TITLE
[fix](move-memtable) abstract multi-streams to one logical stream

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes
Currently, an upstream BE (sink_v2) will open multiple streams to a downstream BE (load_stream).
If any of the streams fails, the use_cnt on the downstream BE will be messed up.
The load_stream will not report any success tablets to the sink_v2 since in its view there are still unfinished streams.

So fault tolerance when open streams is not meaningful in practical, and may cause data lost.
i.e. Upstream think there is still working streams to transfer data, but downstream does not report any commit info.

This PR removes fault tolerance when open multiple streams to the same backend.
If any of the open fails, the upstream sink_v2 should mark the downstream BE as failed replicas.

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
