### PR TITLE
[fix](schema) fix show create table get wrong random distribution info

### LINKED ISSUE #18881: [Bug]  use show create table xxxx, then give me a error distribution_desc
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version doris-1.2.2-rc01(AVX2) RELEASE (build file://be0ca7388ef3@Unknown)
Built on Fri, 10 Feb 2023 16:46:09 UTC by be0ca7388ef3

### What's Wrong?

I created a table `test` with `DISTRIBUTED BY RANDOM BUCKETS 10`, and then executed `show create table test`. The returned DDL statement could not be executed, and upon investigation, it was found that there was round brackets after `RANDOM`.

1. create table `test`
```sql
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
distributed by random buckets 10
PROPERTIES (
"replication_num" = "1"
);
```
2. show create table test
```
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY RANDOM() BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

### What You Expected?

```
CREATE TABLE `test` (
  `id` int(11) NULL,
  `col1` text NULL,
  `col2` text NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY RANDOM BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #18881

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 32.76 seconds
 stream load tsv:          429 seconds loaded 74807831229 Bytes, about 166 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230421082511_clickbench_pr_132380.html

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
