### PR TITLE
[enhancement](exception) enble exception logic in pipeline execute thread

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

Pipeline engine's code is exception safe, we could enable exception now.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
