### PR TITLE
[test](fix) replace hardcode s3BucketName

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run external

**Comment by hello-stephen** [comment]
run p0

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Review by w41ter — APPROVED** [review]

**Pull request merged**
