### PR TITLE
[typo](docs) update documentation

### PR DESCRIPTION
**Pull request by Yankee24**
issue: #8756

## Problem Summary:

Update the field name for viewing be status in the install-deploy documentation.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

**Review by EmmyMiao87 — DISMISSED** [review]
Please change the Chinese document together ~

**Comment by EmmyMiao87** [comment]
The PR title must refer to ：https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83

**Comment by Yankee24** [comment]
I have synchronously modified the Chinese document

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
The CI/CD failed maybe you should rebase the code ~

**Comment by luzhijing** [comment]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
