### PR TITLE
[Test](Orc) Add tests for exception orc files

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by CalvinKirs — DISMISSED** [review]

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
