### PR TITLE
[feature](statistics)Support get row count for pg and sql server.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Support get row count for pg and sql server. Get the row count value through the databases' statistics info.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run feut

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run p0

**Review by englefly — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
