### PR TITLE
[fix](serde)fix string deserialize with unescaped char

### PR DESCRIPTION
**Pull request by amorynan**
before this pr : if we use streamload with unescaped char in json format , we will not deal with it in nested type.
like this :
image
after we will deal with it in output:

```
|   27 | "双引号"    | [""双引号"", "反斜\线"]       |
```
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
