### PR TITLE
[minor](load) Improve error message for string type in loading process

### PR DESCRIPTION
**Pull request by Yulei-Yang**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.77 seconds
 load time: 627 seconds
 storage size: 17154810754 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221027051241_clickbench_pr_34579.html

**Review by Gabriel39 — DISMISSED** [review]
LGTM. Thanks for your contribution!

**Comment by Yulei-Yang** [comment]
@Gabriel39 please review, thx

**Comment by Gabriel39** [comment]
> @Gabriel39 please review, thx

@Yulei-Yang Still some format problems.

**Comment by Yulei-Yang** [comment]
@Gabriel39 please review in your convenience, thx

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
@Gabriel39 please merge, thx

**Pull request merged**
