### PR TITLE
[Improvement](date) shortcut for str to date parse

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1. shortcut for str to date parse
2. remove some unused code
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Pull request merged**
