### PR TITLE
[fix](Tools) Fix the escape character '\' error in sql  generated by tpcds tools scripts

### PR DESCRIPTION
**Pull request by TimCoder**
## Proposed changes

Update tpcds tools:

Fix the escape character '\' error in sql  generated  by tpcds tools scripts gen-tpcds-queries.sh

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TimCoder** [comment]
run buildall

**Comment by TimCoder** [comment]
BD5462BC415ED34ACB90BE7C70DFB351
when execute the query generated by gen-tpcds-queries.sh， the query with '\' failed. @englefly

**Comment by morrySnow** [comment]
could u add a example to explain the behavior before and after this PR, thanks.

**Comment by TimCoder** [comment]
it seems different linux shell handle with '\' results different sql. the sql with '\' in left linux, doris ran will return error. @morrySnow

**Comment by hello-stephen** [comment]
这可能是系统兼容性原因吧，在我环境上ok

**Comment by TimCoder** [comment]
> 这可能是系统兼容性原因吧，在我环境上ok

按这个commit中的代码修改后，是可以解决兼容性问题的，这个PR麻烦处理一下。

**Comment by adonis0147** [comment]
> #### `sh-checker report`
> To get the full details, please check in the job output.
> 
> shellcheck errors
> ```
> 
> 'shellcheck ' returned error 1 finding the following syntactical issues:
> 
> ----------
> 
> In tools/tpcds-tools/bin/gen-tpcds-queries.sh line 151:
>             q="${q//${origin}/concat(concat('${smc1}', ','), '${smc2}')}" && echo "${q};" >>"${of}"
>                                             ^-------^ SC2016 (info): Expressions don't expand in single quotes, use double quotes for that.
>                                                              ^-------^ SC2016 (info): Expressions don't expand in single quotes, use double quotes for that.
> 
> For more information:
>   https://www.shellcheck.net/wiki/SC2016 -- Expressions don't expand in singl...
> ----------
> 
> You can address the above issues in one of three ways:
> 1. Manually correct the issue in the offending shell script;
> 2. Disable specific issues by adding the comment:
>   # shellcheck disable=NNNN
> above the line that contains the issue, where NNNN is the error code;
> 3. Add '-e NNNN' to the SHELLCHECK_OPTS setting in your .yml action file.
> ```
> 
> shfmt errors
> ```
> 'shfmt ' found no issues.
> ```

Hi @TimCoder , you should fix the errors reported by the workflow.

By the way, did you run the script by `sh` (e.g. sh gen-tpcds-queries.sh) ?

**Pull request closed without merging**
