### PR TITLE
[branch-3.0][feat](lock)add deadlock detection tool and monitored lock implementations (#39015)

### PR DESCRIPTION
**Pull request by CalvinKirs**
bp #39015

### CODE REVIEW

**Comment by CalvinKirs** [comment]
#39015

**Comment by CalvinKirs** [comment]
run buildall

**Comment by morningman** [comment]
@gavinchou , this is a new feature.
Maybe we should not merge it ino 3.0.2

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Pull request merged**
