### PR TITLE
Create table with nullable column for default

### PR DESCRIPTION
**Pull request by caiconghui**
on production enviroment, create table usually with so many nullable columns,so default nullable for column will be better

### CODE REVIEW

**Comment by caiconghui** [comment]
#2242

**Review by imay — DISMISSED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
I don't agree with this. More discuss should be made in issue #2242

**Comment by morningman** [comment]
> I don't agree with this. More discuss should be made in issue #2242

You convince me. Plz modify the CREATE TABLE doc to explicitly tell the user what is default behavior.

**Review by imay — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
@caiconghui Hi, you need to fix the unit test failure. (May be just rebase the master)

**Review by morningman — APPROVED** [review]

**Comment by gaodayue** [comment]
This PR contains too much irrelevant code changes. People may want to cherry-pick a patch for the specific purpose described by the PR title, such giant PR makes it difficult though.

**Comment by imay** [comment]
Oh, something is wrong, we will revert this PR.
@caiconghui Please provide another clean PR. I'm not sure why there are too much code in this PR. Do you use merge other than rebase?

**Comment by gaodayue** [comment]
@imay Thanks for the information

**Comment by caiconghui** [comment]
@imay is there still a need for me to push a clean PR?

**Comment by imay** [comment]
> @imay is there still a need for me to push a clean PR?

No new PR, this PR is OK.

**Pull request merged**
