### PR TITLE
[Feature](group commit) move group_commit_interval_ms from be.conf to table property

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

Current batch commit interval is configured in be.conf with the property "group_commit_interval_ms". It has the following drawbacks:

1. The interval is the same for all tables, and cannot be configured differently.
2. If the configuration is modified, all BEs need to be modified and restarted.

Considering that the commit interval is a table-level configuration, it is possible to move this configuration from be.conf to table properties. If not explicitly set, the default value is 10000ms. Users can modify it as follows:

```SQL
ALTER TABLE my_table SET ("group_commit_interval_ms"="1000");
```

Each time BE requests a plan from FE, it can be passed over.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run ppipelinex_p0

**Comment by Yukang-Lian** [comment]
run pipelinex_p0

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by mymeiyi — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run p0

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
