### PR TITLE
[fix](move-memtable) temporary disable load stream profile

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Temporary disable load stream profile, because:

1. It's not being processed by the upstream for now
2. There are some problems in `_profile->to_thrift()`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
