### PR TITLE
[FE Code Style] Include test sources

### PR DESCRIPTION
**Pull request by xleoken**
## Problem Summary:

 Include test sources, we also need to check them.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]
Great. FE Code Style Checker failed. Looks like there's still some fix to be done

**Comment by leo65535** [comment]
> Great. FE Code Style Checker failed. Looks like there's still some fix to be done

👍, blocked for https://github.com/apache/incubator-doris/pull/9370

**Comment by leo65535** [comment]
cc @EmmyMiao87, take a review when free, thanks.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
