### PR TITLE
[refactor](move-memtable) simplify LoadStreamStub::open

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Extend `std::enable_shared_from_this` to simplify `LoadStreamStub::open`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
