### PR TITLE
[fix](multi-catalog)compatible with hdfs HA empty prefix

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

compatible with hdfs HA empty prefix
for example: ’hdfs:///‘ will be replaced to ’hdfs://ha-nameservice/‘

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.98 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          30.2 seconds inserted 10000000 Rows, about 331K ops/s
 storage size: 17168658071 Bytes

**Comment by wsjz** [comment]
do not merge before user verify.... wait for 3-5 days from now on.

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Review by zddr — APPROVED** [review]

**Pull request merged**
