### PR TITLE
[fix](column_array)fix filter_generic in column_array func

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
filter_generic in column_array is wrong calculate in nested_result_hint_size which may cause heap_buffer_overflow 
image

Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run cloud_p0

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
