### PR TITLE
[fix] fix ltrim result may incorrect in some case

### PR DESCRIPTION
**Pull request by yangzhg**
## Problem Summary:

fix ltrim result may incorrect in some case
according to https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
Built-in Function: int __builtin_cl/tz (unsigned int x)
If x is 0, the result is undefined.
So we handle the case of 0 separately

this function return different between gcc and clang when x is 0

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinghuayu007** [comment]
please add some unit tests for case:  __builtin_cl/tz (0)

**Comment by amosbird** [comment]
Similar fixes has been done in https://github.com/apache/incubator-doris/pull/7712 , which was caught by current unit tests. It's an indication that test coverage should be improved.

**Comment by yangzhg** [comment]
> please add some unit tests for case: __builtin_cl/tz (0)

Unit test has already contained this situation

**Comment by yangzhg** [comment]
> Similar fixes has been done in #7712 , which was caught by current unit tests. It's an indication that test coverage should be improved.

I see, this is in another function, we may merge the those implements together

**Comment by yangzhg** [comment]
> Similar fixes has been done in #7712 , which was caught by current unit tests. It's an indication that test coverage should be improved.

Fix in #7712 will add an offset of 128 when mask is 0, but offset is 32 when mask is 0 in this pr, I not sure 128 is a correct value @amosbird ?

**Comment by xinghuayu007** [comment]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
