### PR TITLE
[improvement](regression) improve p1 test time by moving spill cases to p2

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by jacktengg** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
