### PR TITLE
[Enhancement](status) Refactor Slice move/copy ctor && assignment to default

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Refactor Slice move/copy ctor && assignment to default

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
