### PR TITLE
[enhancement](Nereids) Refactor EliminateLimitTest and EliminateFilterTest by match-pattern

### PR DESCRIPTION
**Pull request by reswqa**
# Proposed changes

Issue Number: #17625

## Problem summary

- Remove useless public modifier and fix typo in EliminateFilterTest and EliminateLimistTest.
- Refactor EliminateLimitTest and EliminateFilterTest by match-pattern.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by reswqa** [comment]
@jackwener Would you mind taking a look at this? thanks!

**Review by jackwener — APPROVED** [review]

**Comment by jackwener** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.86 seconds
 stream load tsv:          461 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230310024509_clickbench_pr_111815.html

**Comment by reswqa** [comment]
Thanks @jackwener for the review. It seems that `P0 Regression (Doris Regression)` is failed, but I'm not familiar with Doris's CI pipeline. Could you help confirm the reason for the failure? thanks.

**Review by jackwener — APPROVED** [review]

**Comment by jackwener** [comment]
Thanks

**Pull request merged**
