### PR TITLE
[improvement][config] change be 2pc config  enbale  defalut

### PR DESCRIPTION
**Pull request by JNSimba**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

default disable_stream_load_2pc=false

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by yiguolei — CHANGES_REQUESTED** [review]
Why enable this by default? I think it has not been fully tested.

**Comment by JNSimba** [comment]
> Why enable this by default? I think it has not been fully tested.

At present, the latest version of flink doris connector is submitted in 2pc mode to ensure the exactly once semantics of doris storage. We have done a lot of tests based on this, and there is no problem at present, so we hope that from the 1.1 version of doris, this configuration will be turned on by default.
On the other hand, even if this configuration is enabled by default, it has no effect on the normal streamload, because the 2pc streamload also needs to be displayed in the header to declare that 2pc is enabled

**Comment by morningman** [comment]
If it has been tested, I think we can merge this into 1.1. So that we can match the new version of flink-connector in next release.
@yiguolei please add dev-1.0.1 label if it looks good to you.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
