### PR TITLE
[fix](memory) Add cache manager check for exist

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Debug CacheManager::_caches unordered_map multithreaded visibility.

```
#0  0x0000557d141fede4 in std::__shared_ptr<doris::MemTracker::MemCounter, (__gnu_cxx::_Lock_policy)2>::get (this=0x28) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1291
1291          { return _M_ptr; }
[Current thread is 1 (Thread 0x7fcd139bd700 (LWP 3807666))]
(gdb)
(gdb) bt
#0  0x0000557d141fede4 in std::__shared_ptr<doris::MemTracker::MemCounter, (__gnu_cxx::_Lock_policy)2>::get (this=0x28) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1291
#1  0x0000557d141fed97 in std::__shared_ptr_access<doris::MemTracker::MemCounter, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get (this=0x28) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:990
#2  0x0000557d141fe607 in std::__shared_ptr_access<doris::MemTracker::MemCounter, (__gnu_cxx::_Lock_policy)2, false, false>::operator-> (this=0x28) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:984
#3  0x0000557d141fd857 in doris::MemTracker::consume (this=0x0, bytes=106) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/runtime/memory/mem_tracker.h:141
#4  0x0000557d146a4331 in doris::LRUCachePolicy::insert (this=0x60c00036a600, key=..., value=0x60300151a890, charge=1, tracking_bytes=4, priority=doris::CachePriority::NORMAL) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/runtime/memory/lru_cache_policy.h:100
#5  0x0000557d1466387d in doris::CreateTabletIdxCache::set_index (this=0x60c00036a600, key=..., next_idx=3) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:1500
#6  0x0000557d14662c8d in doris::StorageEngine::_get_and_set_next_disk_index (this=0x61d000102280, partition_id=10112, storage_medium=doris::TStorageMedium::HDD) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:460
#7  0x0000557d14664da8 in doris::StorageEngine::get_stores_for_create_tablet (this=0x61d000102280, partition_id=10112, storage_medium=doris::TStorageMedium::HDD) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:529
#8  0x0000557d1467246f in doris::StorageEngine::create_tablet (this=0x61d000102280, request=..., profile=0x7fcd119a6020) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:1151
#9  0x0000557d16edfbbc in doris::create_tablet_callback (engine=..., req=...) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/agent/task_worker_pool.cpp:1361
#10 0x0000557d181b72f4 in doris::AgentServer::start_workers(doris::ExecEnv*)::$_10::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const (this=0x606000dd4638, task=...)
    at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/agent/agent_server.cpp:123
#11 0x0000557d181b728f in std::__invoke_impl<void, doris::AgentServer::start_workers(doris::ExecEnv*)::$_10&, doris::TAgentTaskRequest const&>(std::__invoke_other, doris::AgentServer::start_workers(doris::ExecEnv*)::$_10&, doris::TAgentTaskRequest const&) (__f=...,
    __args=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#12 0x0000557d181b7201 in std::__invoke_r<void, doris::AgentServer::start_workers(doris::ExecEnv*)::$_10&, doris::TAgentTaskRequest const&>(doris::AgentServer::start_workers(doris::ExecEnv*)::$_10&, doris::TAgentTaskRequest const&) (__fn=..., __args=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#13 0x0000557d181b7037 in std::_Function_handler<void (doris::TAgentTaskRequest const&), doris::AgentServer::start_workers(doris::ExecEnv*)::$_10>::_M_invoke(std::_Any_data const&, doris::TAgentTaskRequest const&) (__functor=..., __args=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
#14 0x0000557d16f02cff in std::function<void (doris::TAgentTaskRequest const&)>::operator()(doris::TAgentTaskRequest const&) const (this=0x606000dd4638, __args=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#15 0x0000557d16ef17b4 in doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}::operator()() const (this=0x62000001a080)
    at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/agent/task_worker_pool.cpp:437
#16 0x0000557d16ef1757 in std::__invoke_impl<void, doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}&>(std::__invoke_other, doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}&) (__f=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#17 0x0000557d16ef16c9 in std::__invoke_r<void, doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}&>(doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}&) (__fn=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#18 0x0000557d16ef13ef in std::_Function_handler<void (), doris::TaskWorkerPool::submit_task(doris::TAgentTaskRequest const&)::$_0::operator()<doris::TAgentTaskRequest const&>(doris::TAgentTaskRequest const&) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (
    __functor=...) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
#19 0x0000557d1442dfb7 in std::function<void ()>::operator()() const (this=0x606000ebb6f8) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#20 0x0000557d187c61db in doris::FunctionRunnable::run (this=0x606000ebb6f0) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/util/threadpool.cpp:48
#21 0x0000557d187af5ff in doris::ThreadPool::dispatch_thread (this=0x6150006cc300) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/util/threadpool.cpp:543
#22 0x0000557d187db496 in std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&> (__f=@0x6030015178c0: (void (doris::ThreadPool::*)(doris::ThreadPool * const)) 0x557d187ad620 <doris::ThreadPool::dispatch_thread()>,
    __t=@0x6030015178d0: 0x6150006cc300) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
#23 0x0000557d187db33f in std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&> (__fn=@0x6030015178c0: (void (doris::ThreadPool::*)(doris::ThreadPool * const)) 0x557d187ad620 <doris::ThreadPool::dispatch_thread()>, __args=@0x6030015178d0: 0x6150006cc300)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#24 0x0000557d187db2b7 in std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x6030015178c0, __args=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:420
#25 0x0000557d187db150 in std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() (this=0x6030015178c0) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:503
#26 0x0000557d187db057 in std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) (__f=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#27 0x0000557d187dafc9 in std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) (__fn=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#28 0x0000557d187dab8f in std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
#29 0x0000557d1442dfb7 in std::function<void ()>::operator()() const (this=0x6110014c6ed8) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#30 0x0000557d18773ea4 in doris::Thread::supervise_thread (arg=0x6110014c6ec0) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/util/thread.cpp:498
#31 0x00007fd3a3c32609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#32 0x00007fd3a3edf133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 5
#5  0x0000557d1466387d in doris::CreateTabletIdxCache::set_index (this=0x60c00036a600, key=..., next_idx=3) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:1500
1500    /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp: No such file or directory.
(gdb) p value
$1 = (doris::CreateTabletIdxCache::CacheValue *) 0x60300151a890
(gdb) p (LRUCacheValueBase*)value
$2 = (doris::LRUCacheValueBase *) 0x60300151a890
(gdb) p *(LRUCacheValueBase*)value
$3 = {_vptr$LRUCacheValueBase = 0x557d4a8eb440 <vtable for doris::CreateTabletIdxCache::CacheValue+16>, _tracking_bytes = 0, _mem_tracker = 0x0}
#5  0x0000557d1466387d in doris::CreateTabletIdxCache::set_index (this=0x60c00036a600, key=..., next_idx=3) at /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp:1500
1500	in /home/zcp/repo_center/doris_branch-2.1/doris/be/src/olap/storage_engine.cpp
(gdb) p *this
$4 = {<doris::LRUCachePolicy> = {<doris::CachePolicy> = {_vptr$CachePolicy = 0x557d4a8eb310 <vtable for doris::CreateTabletIdxCache+16>, _type = doris::CachePolicy::CacheType::CREATE_TABLET_RR_IDX_CACHE, _mem_tracker = {
        _M_t = {<std::__uniq_ptr_impl<doris::MemTracker, std::default_delete<doris::MemTracker> >> = {
            _M_t = {<std::_Tuple_impl<0ul, doris::MemTracker*, std::default_delete<doris::MemTracker> >> = {<std::_Tuple_impl<1ul, std::default_delete<doris::MemTracker> >> = {<std::_Head_base<1ul, std::default_delete<doris::MemTracker>, true>> = {
                    _M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0ul, doris::MemTracker*, false>> = {_M_head_impl = 0x60c0003697c0}, <No data fields>}, <No data fields>}}, <No data fields>}},
      _mem_tracker_by_allocator = {<std::__shared_ptr<doris::MemTrackerLimiter, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<doris::MemTrackerLimiter, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x0, _M_refcount = {
            _M_pi = 0x0}}, <No data fields>}, _profile = {_M_t = {<std::__uniq_ptr_impl<doris::RuntimeProfile, std::default_delete<doris::RuntimeProfile> >> = {
            _M_t = {<std::_Tuple_impl<0ul, doris::RuntimeProfile*, std::default_delete<doris::RuntimeProfile> >> = {<std::_Tuple_impl<1ul, std::default_delete<doris::RuntimeProfile> >> = {<std::_Head_base<1ul, std::default_delete<doris::RuntimeProfile>, true>> = {
                    _M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0ul, doris::RuntimeProfile*, false>> = {_M_head_impl = 0x617000127900}, <No data fields>}, <No data fields>}}, <No data fields>}}, _prune_stale_number_counter = 0x6030008fdc70,
      _prune_all_number_counter = 0x6030008fdd00, _freed_memory_counter = 0x6030008fdd60, _freed_entrys_counter = 0x6030008fdd90, _cost_timer = 0x6030008fddc0, _stale_sweep_time_s = 1800, _enable_prune = true},
    _cache = {<std::__shared_ptr<doris::Cache, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<doris::Cache, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x60f000078220, _M_refcount = {_M_pi = 0x6030008fe150}}, <No data fields>},
    _lru_cache_type = doris::NUMBER}, <No data fields>}
```

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
