### PR TITLE
[refactor](metrics) Complete metrics for some operators

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by Gabriel39** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Comment by 0xderek** [comment]
HI,

I am working on a patch  to fix #42406. Initially I came across the issue on Doris 2.1.6 so I based my work on branch-2.1. I added some tests in be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp but I can't find the file on master branch.

It turns out the file was removed in this pull request. It seems odd to me as the test file is irrelevant to this pr. Is there a particular reason to remove it? Thanks.

**Comment by Gabriel39** [comment]
> Hi,
> 
> I am working on a patch to fix #42406. Initially I came across the issue on Doris 2.1.6 so I based my work on branch-2.1. I added some tests in be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp but I can't find the file on master branch.
> 
> It turns out the file was removed in this pull request. It seems odd to me as the test file is irrelevant to this pr. Is there a particular reason to remove it?
> 
> Thanks.

Hi @0xderek , sorry for this late reply.

I removed this file because I found a function `convert_to_arrow_schema` which is never unused is tested multiple times by this test file. In this PR, I deleted this unused function and also removed this file. And after discussing with @xinyiZzz , we think this file needs to be refactored to do some necessary tests. This job is expected to be done in this month.

**Comment by 0xderek** [comment]
> > Hi,
> > I am working on a patch to fix #42406. Initially I came across the issue on Doris 2.1.6 so I based my work on branch-2.1. I added some tests in be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp but I can't find the file on master branch.
> > It turns out the file was removed in this pull request. It seems odd to me as the test file is irrelevant to this pr. Is there a particular reason to remove it?
> > Thanks.
> 
> Hi @0xderek , sorry for this late reply.
> 
> I removed this file because I found a function `convert_to_arrow_schema` which is never unused is tested multiple times by this test file. In this PR, I deleted this unused function and also removed this file. And after discussing with @xinyiZzz , we think this file needs to be refactored to do some necessary tests. This job is expected to be done in this month.

Hi @Gabriel39 

Glad to hear from you.

I think the function `convert_to_arrow_schema ` was used as a utility function in tests. It helps to construct arrow structures from doris row descriptors. The arrow structures are later used to test serialization and deserialization of data in arrow format. If the situation of the function not being used is really an issue for you, moving it to a test file (for example serde_utils.h) seems like a better option.

The reason I care so much about the test is that I have a use case which heavily depends on stream loading in arrow format. Without this test file, serialization / deserialization for data in arrow format was left completely untested. Not to mention the coverage was rather low at the first place.

With that being said, I am glad to know that test refactoring is in progress. Thank you for your effort.

**Pull request merged**
