### PR TITLE
[FIX](complextype)fix information schema for complex type

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
when we select in information schema , here do not show complex type information 
ea5111e3-d872-4441-8d0f-3bc2b708af14

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run feut

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
