### PR TITLE
[Enhancement] (nereids)implement showFrontendsCommand in nereids

### LINKED ISSUE #42764: [Enhancement] (nereids)implement showFrontendsCommand in nereids
showFrontends command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showFrontends command in nereids:
unsupportedshowFrontendsStatement
``` SHOW FRONTENDS name=identifier?                                               ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

support showFrontendsCommand in nereids

Issue Number: close #42764 

Related PR: #xxx

Problem Summary:

### Check List (For Committer)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 
test_frontend.groovy cover this test case.

mysql> show frontends;
+-----------------------------------------+-------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+-------------------------+------------------+
| Name                                    | Host        | EditLogPort | HttpPort | QueryPort | RpcPort | ArrowFlightSqlPort | Role     | IsMaster | ClusterId | Join | Alive | ReplayedJournalId | LastStartTime       | LastHeartbeat       | IsHelper | ErrMsg | Version                 | CurrentConnected |
+-----------------------------------------+-------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+-------------------------+------------------+
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | 9010        | 8030     | 9030      | 9020    | -1                 | FOLLOWER | true     | 453869832 | true | true  | 3425              | 2024-11-01 19:16:13 | 2024-11-01 19:31:54 | true     |        | doris-0.0.0--f56e46721e | Yes              |
+-----------------------------------------+-------------+-------------+----------+-----------+---------+--------------------+----------+----------+-----------+------+-------+-------------------+---------------------+---------------------+----------+--------+-------------------------+------------------+
1 row in set (5.21 sec)

mysql> show frontends disks;
+-----------------------------------------+-------------+-----------+-------------------------------------+----------------+----------+------+-----------+---------+-------------+
| Name                                    | Host        | DirType   | Dir                                 | Filesystem     | Capacity | Used | Available | UseRate | MountOn     |
+-----------------------------------------+-------------+-----------+-------------------------------------+----------------+----------+------+-----------+---------+-------------+
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | meta      | /root/doris/doris_run/fe/doris-meta | /dev/nvme0n1p6 | 295G     | 246G | 34G       | 88%     | /root/doris |
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | log       | /root/doris/doris_run/fe/log        | /dev/nvme0n1p6 | 295G     | 246G | 34G       | 88%     | /root/doris |
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | audit-log | /test                               | overlay        | 295G     | 246G | 34G       | 88%     | /           |
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | temp      | /root/doris/doris_run/fe/temp_dir   | /dev/nvme0n1p6 | 295G     | 246G | 34G       | 88%     | /root/doris |
| fe_73d1d34b_7ec5_444a_9266_0299c34183e7 | 172.20.80.1 | deploy    | /root/doris/doris_run/fe            | /dev/nvme0n1p6 | 295G     | 246G | 34G       | 88%     | /root/doris |
+-----------------------------------------+-------------+-----------+-------------------------------------+----------------+----------+------+-----------+---------+-------------+
5 rows in set (0.00 sec)

- Behavior changed:

    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?

    - [ ] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by starocean999** [comment]
please resolve conflict

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run p0

**Review by starocean999 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
