### PR TITLE
[Doris Manager][Doc]Add space list documents

### PR DESCRIPTION
**Pull request by JusticeGong**
Add space list and access control document. Remove some pictures to reduce the size of source code.

# Proposed changes

Issue Number: close #8609 

## Problem Summary:

Add space list and access control document. Remove some pictures to reduce the size of source code.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (Yes)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
The picture is too big and seem to be changed very frequently.
This will significantly increase the size of this code repo.

**Comment by JusticeGong** [comment]
> The picture is too big and seem to be changed very frequently. This will significantly increase the size of this code repo.

Already compress the size of all pics to 20%

**Comment by luzhijing** [comment]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
