### PR TITLE
[FIX](regresscases) fix regress exception for test_array_element_at_and_slice

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Comment by amorynan** [comment]
2.0 不用合入 这是nereids 的case

**Pull request merged**
