### PR TITLE
[Enhance](BE) Add -Wshadow-field compile option to avoid unexpected shadowing behavior

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Shadow fields usually make mistakes, add `-Wshadow-field` compile option to avoid unexpected shadowing behavior.

It is a refactor, not need merge to 2.0 and there maybe many conflict.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
