### PR TITLE
[Fix](ccr) Wrong result of tosql for add column with comment

### PR DESCRIPTION
**Pull request by wyxxxcat**
### What problem does this PR solve?

ccr increment sync problem, ccr-syncer also will be fixed and add test case
```
alter table t add column col1 varchar(20) NULL COMMENT "xxx\"xx\""
```
```
[2024-12-11 17:48:30.737]  WARN job sync failed, job: test, err: [normal] Error 1105 (HY000): errCode = 2, detailMessage = 
mismatched input 'xx' expecting {<EOF>, ';'}(line 1, pos 64)
exec sql ALTER TABLE `t` ADD COLUMN `col1` varchar(20) NULL COMMENT "xxx"xx"" failed
github.com/selectdb/ccr_syncer/pkg/ccr/base.(*Spec).DbExec
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/base/spec.go:1166
github.com/selectdb/ccr_syncer/pkg/ccr/base.(*Spec).LightningSchemaChange
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/base/spec.go:1242
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleLightningSchemaChange
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2107
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleBinlog
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2725
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleBinlogs
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2662
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).incrementalSync
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2839
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).dbSync
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2900
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).sync
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2917
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).run
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:2975
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).Run
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job.go:3096
github.com/selectdb/ccr_syncer/pkg/ccr.(*JobManager).runJob.func1
    /mnt/disk2/wangyixuan/ccr-syncer/pkg/ccr/job_manager.go:166
runtime.goexit
    /mnt/disk2/wangyixuan/go_1_23/go/src/runtime/asm_amd64.s:1700 job=test line=ccr/job.go:2980
```

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by wyxxxcat** [comment]
run buildall

**Review by w41ter — DISMISSED** [review]

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by wyxxxcat** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
