### PR TITLE
[feature](cloud) support get load state by HTTP API in cloud mode

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

use label 125 load data
```
{
    "TxnId": 163088604293120,
    "Label": "125",
    "Comment": "",
    "TwoPhaseCommit": "false",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 1,
    "NumberLoadedRows": 1,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 4,
    "LoadTimeMs": 441,
    "BeginTxnTimeMs": 60,
    "StreamLoadPutTimeMs": 246,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 126,
    "CommitAndPublishTimeMs": 6
}
```

curl --location-trusted -u root:"" http://127.0.0.1:8239/api/db/get_load_state?label=125
```
{
    "msg": "success",
    "code": 0,
    "data": "VISIBLE",
    "count": 0
}
```

curl --location-trusted -u root:"" http://127.0.0.1:8239/api/db/get_load_state?label=126
```
{
    "msg": "success",
    "code": 0,
    "data": "UNKNOWN",
    "count": 0
}
```

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a regression test.

**Review by gavinchou — APPROVED** [review]

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
