### PR TITLE
[Fix](invert index)fix s3 Failed to check the directory

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

Issue Number: close #xxx

1. s3 does not support checking directories

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run p0

**Pull request merged**
