### PR TITLE
[regression] add regression-test for s3 tvf

### PR DESCRIPTION
**Pull request by 133tosakarin**
I had added some regression test for s3 tvf,  all requirse of test cases  refer to https://github.com/apache/doris/issues/32576

### CODE REVIEW

**Comment by 133tosakarin** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by 133tosakarin** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
