### PR TITLE
[fix]Optimize debug logging

### PR DESCRIPTION
**Pull request by ixzc**
## Proposed changes

Issue Number: close #xxx

A conditional check is added to determine if debug level logging is required

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by ixzc** [comment]
run buildall

**Pull request closed without merging**
