### PR TITLE
[enhancement]use awaitility.await() replace thread.sleep()

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
@dataroaring

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
