### PR TITLE
[regression-test](load) add something like $.tag.[a.b] key's json case

### PR DESCRIPTION
**Pull request by felixwluo**
## Proposed changes

1、json 
```
{
        "tags": {
                "a.b": "test",
                "k2": "k2_value"
        }
}
```
`add a regression test to parse a key like a.b`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by felixwluo** [comment]
run buildall

**Review by cambyzju — DISMISSED** [review]
LGTM

**Comment by felixwluo** [comment]
run buildall

**Comment by felixwluo** [comment]
run p0

**Comment by cambyzju** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]

**Pull request merged**
