### PR TITLE
[fix](cloud) fix create tablet miss cluster key index

### PR DESCRIPTION
**Pull request by yujun777**
only base tablet +  schema change tablet use cluster key index,  other tablet don't.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Comment by yujun777** [comment]
run cloud_p0

**Comment by yujun777** [comment]
run cloud_p0

**Review by gavinchou — APPROVED** [review]

**Pull request closed without merging**
