### PR TITLE
[opt](array) optimize array_sortby using qsort instead of bubble sort

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes

Now in array_sortby function, elements are sorted by bubble sort. 
This PR is to use qsort instead of bubble sort.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.08 seconds
 stream load tsv:          440 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230402003741_clickbench_pr_123714.html

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run clickbench

**Review by zhangstar333 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
