### PR TITLE
[case](regression) Test duplicated load id

### PR DESCRIPTION
**Pull request by HowardQin**
[[runtime/stream_load/new_load_stream_mgr.h](https://doris-build-1308700295.cos.ap-beijing.myqcloud.com/daily_regression_coverage/daily/doris/branch_2.0_df82f8bd080d676aff88bca6b38a05b98fb2525f/report/coverage/home/zcp/repo_center/doris_branch-2.0/doris/be/src/runtime/stream_load/new_load_stream_mgr.h.html)](case: load id 已经存在)

### CODE REVIEW

**Comment by HowardQin** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
