### PR TITLE
[Fix]add set thread num config for wg flush pool

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
calculate workload group's mem table flush pool 's thread num by cpu and disk num,  other wise it may cause mem table flush cost more memory than not enable workload group.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
@liaoxin01  please add merge branch label for this pr.

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
