### PR TITLE
[Enhancement] (nereids)implement showWhitelistCommand in nereids

### LINKED ISSUE #42725: [Enhancement] (nereids)implement showWhitelistCommand in nereids
showWhitelist command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showWhitelist command in nereids:
unsupportedshowWhitelistStatement
``` SHOW WHITELIST                                                                ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #42725 

Related PR: #xxx

Problem Summary:
implement showWhitelistCommand in nereids
### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test // added
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run fe_ut

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
