### PR TITLE
[Imporve](UNIX_TIMESTAMP) UNIX_TIMESTAMP func support  'yyyy-MM-dd HH:mm:ss' format

### PR DESCRIPTION
**Pull request by LemonLiTree**
UNIX_TIMESTAMP function data format parameter supports 'yyyy-MM-dd HH:mm:ss'
The implementation is the same as the date_format function
before:
```sql
mysql> select UNIX_TIMESTAMP('2023-09-18 00:00:00','yyyy-MM-dd HH:mm:ss');
+--------------------------------------------------------------+
| unix_timestamp('2023-09-18 00:00:00', 'yyyy-MM-dd HH:mm:ss') |
+--------------------------------------------------------------+
|                                                         NULL |
+--------------------------------------------------------------+
1 row in set (0.04 sec)
```
now:
```sql
mysql> select UNIX_TIMESTAMP('2023-09-18 00:00:00','yyyy-MM-dd HH:mm:ss');
+------------+
| 1694966400 |
+------------+
| 1694966400 |
+------------+
1 row in set (0.01 sec)
```

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by LemonLiTree** [comment]
run buildall

**Review by jackwener — APPROVED** [review]

**Comment by LemonLiTree** [comment]
run buildall

**Pull request merged**
