### PR TITLE
[feature](replica) support force set replicate allocation for olap tables

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

We try to deploy a high available doris cluster between three zones.
Firstly we need set tag.location to `zone1|zone2|zone3` for each BE;
Secondly we need set `replication_allocation` properly while create table;

But it is not very convenient, so we add a config to force set replication allocation for all OLAP tables and partitions.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Pull request merged**
