### PR TITLE
[fix](move-memtable) ensure segment is flushed before add segment

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Currently segment flush is async, and ADD_SEGMENT is handled immediately.
When ADD_SEGMENT arrives, segment flush may not been finished, causing corruption.
Fix this issue by execute ADD_SEGMENT asyncly in the same FIFO threadpool of segment flush.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
