### PR TITLE
[Fix] Coredump in column dictionary insert data from DefaultValueColumnIterator

### LINKED ISSUE #11216: [Bug] [ColumnDictionary] Coredump in column dictionary insert data from DefaultValueColumnIterator
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

#0  0x00007f52487938a5 in raise () from /lib64/libc.so.6
#1  0x00007f5248795085 in abort () from /lib64/libc.so.6
#2  0x00007f524abf4f0c in google::DumpStackTraceAndExit () at src/utilities.cc:160
#3  0x00007f524d06dd6d in google::LogMessage::Fail () at src/logging.cc:1650
#4  0x00007f524d0702a9 in google::LogMessage::SendToLog (this=0x7f52181abd10) at src/logging.cc:1607
#5  0x00007f524d06d8d6 in google::LogMessage::Flush (this=0x7f52181abd10) at src/logging.cc:1476
#6  0x00007f524d070919 in google::LogMessageFatal::~LogMessageFatal (this=this@entry=0x7f52181abd10, __in_chrg=<optimized out>) at src/logging.cc:2226
#7  0x00007f524b15b560 in doris::vectorized::ColumnDictionary<int>::insert_data (this=<optimized out>, pos=<optimized out>)
    at /home/disk6/palo/release/baidu/bdg/doris/palo-1.1/be/src/vec/columns/column_dictionary.h:100
#8  0x00007f524b8f144e in doris::vectorized::ColumnNullable::insert_data (this=0x7f55413354c0, pos=<optimized out>, length=<optimized out>)

### What You Expected?

run normally

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #11216

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by wangbo — DISMISSED** [review]
LGTM

**Comment by 924060929** [comment]
could you add a regression test case?

**Comment by yiguolei** [comment]
@924060929  I will quick merge this PR because it is very serious.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
