### PR TITLE
[queryretry](errormsg) should not send retry request to BE again if the query is timeout

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

If retry, then FE will send fragments to BE, but there is a timeout checker and will cancel the timeout query. But BE will run the fragment, it is useless and will cost CPU.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
