### PR TITLE
[regression-test](connector) Add a case for the response of streamload that the connector depends

### PR DESCRIPTION
**Pull request by JNSimba**
## Proposed changes

Issue Number: close #xxx

Add a case for the response of streamload that the connector depends

### CODE REVIEW

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run p0

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run p0

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run p0

**Comment by JNSimba** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
