### PR TITLE
[Docs](docs) Organize http documents

### LINKED ISSUE #15658: [Enhancement] add http interface authentication and support https
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently, doris supports access to fe / be only through http protocol, not https protocol. In addition, http does not perform interface authentication, which may cause security problems.

### Solution

Add http interface authentication and support https for doris, eliminate potential security risks and strengthen enterprise-level security support.
[Support https protocol and interface authentication](https://cwiki.apache.org/confluence/display/DORIS/DSIP-029%3A+Support+https+protocol+and+interface+authentication)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)]

### PR DESCRIPTION
**Pull request by yongjinhou**
# Proposed changes

Issue Number: close #15658

## Problem summary

1. **Organize http documents**
2. Add http interface authentication for FE
3. Support https interface for FE
4. Provide authentication interface
5. Add http interface authentication for BE
6. Support https interface for BE

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run compile

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run compile

**Review by yangzhg — DISMISSED** [review]
LGTM

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run p0

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
