### PR TITLE
[Bugfix](multi-catalog)If es hosts ends with "/", the index cannot be obtained.

### LINKED ISSUE #24271: [Bug](multi-catalog) If es hosts ends with "/", the index cannot be obtained.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

mysql> show tables;

ERROR 1105 (HY000): DorisEsException, msg: org.apache.doris.external.elasticsearch.DorisEsException: get es indexes error

### What You Expected?

Get the index

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #24271

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Review by qidaye — COMMENTED** [review]
Please add some regression tests.

**Comment by liugddx** [comment]
> Please add some regression tests.

This test requires a real es server, I'm not sure if regression testing can provide such a service?

**Comment by qidaye** [comment]
> > Please add some regression tests.
> 
> This test requires a real es server, I'm not sure if regression testing can provide such a service?

We can add external regression by docker, you can refer to this pr: https://github.com/apache/doris/pull/24318

**Comment by qidaye** [comment]
There is the developer guide: https://doris.apache.org/community/developer-guide/regression-testing/#e2e-test-with-external-data-sources

**Comment by liugddx** [comment]
> There is the developer guide: https://doris.apache.org/community/developer-guide/regression-testing/#e2e-test-with-external-data-sources

Thanks, I'll try it

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
@liugddx please take a look , external regression cases is failed.

**Comment by liugddx** [comment]
> @liugddx please take a look , external regression cases is failed.

Let me take a look.

**Comment by liugddx** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
