### PR TITLE
[fix](http stream) http stream support memtable_on_sink_node header

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Make `memtable_on_sink_node` header work for `http_stream`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run p0

**Pull request merged**
