### PR TITLE
[branch-2.0-fix](partial update) Don't use delete bitmap to mark delete for rows with delete sign when sequence column doesn't exist

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes
reverts the optimization for delete sign on MOW table
pick from master: https://github.com/apache/doris/pull/26721

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run clickbench

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
