### PR TITLE
[Fix](nereids) change char(0) to char(1), varchar(0) to varchar(65533) when create table (#38427)

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
cherry-pick #38427 to branch-2.1

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Pull request merged**
