### PR TITLE
[regression_test](flink) add await for commit phase

### PR DESCRIPTION
**Pull request by JNSimba**
## Proposed changes

Issue Number: close #xxx

The publish in the commit phase of streamload is asynchronous, so the data may not be visible.

### CODE REVIEW

**Comment by JNSimba** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run p0

**Comment by JNSimba** [comment]
run external

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
