### PR TITLE
[fix](insert) txn insert and group commit should write \N string corr…

### PR DESCRIPTION
**Pull request by mymeiyi**
…ectly

## Proposed changes

For insert into values, we can write `\N` string to a column.
```
insert into t2 values(1, '"b"', 100);
insert into t2 values(2, '\N', 100);
insert into t2 values(3, '\\N', 100);

mysql> select * from t2 where name is null;
Empty set (0.03 sec)
```

But txn insert and group commit insert use stream load as the inner implementation, the `\N` means `null`, so the write result is not correct.
```
begin;
insert into t2 values(1, '"b"', 100);
insert into t2 values(2, '\N', 100);
insert into t2 values(3, '\\N', 100);
commit;

mysql> select * from t2 where name is null;
+------+------+-------+
| id   | name | score |
+------+------+-------+
|    3 | NULL |   100 |
+------+------+-------+
1 row in set (0.02 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zzzzzzzs — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
