### PR TITLE
[fix](catalog)fix when modifying comments in property, it will modify the comments in the catalog

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

- fix when modifying comments in property, it will modify the comments in the catalog
- add `alter catalog modify comment` to modify comment for catalog
- abstract some logic of `alter catalog` to parent class 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by morningman — COMMENTED** [review]
please add regression test case, so that we can test edit log replay logic

**Comment by zddr** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
The Test_paimon_catalog regression test case should be tagged external_docker, otherwise it will not run on the external access pipeline

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
