### PR TITLE
[fix](cloud) Support cloud multi cluster run in docker

### PR DESCRIPTION
**Pull request by deardeng**

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by gavinchou — DISMISSED** [review]

**Comment by deardeng** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
