### PR TITLE
[opt](assert_num_rows) support filter in AssertNumRows operator and fix some explain

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
1. support filter in AssertNumRows on BE
2. explain of AssertNumRows prints predicates
3. explain of DataGenScanNode prints predicates

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run build all

**Comment by zhiqiang-hhhh** [comment]
run build all

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
