### PR TITLE
[enhancement](testutil) add string funciton ut test case

### PR DESCRIPTION
**Pull request by M1saka2003**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by M1saka2003** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by M1saka2003** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Pull request closed without merging**
