### PR TITLE
[fix](move-memtable) fix initial use count of streams for auto partition

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

In auto partition, new streams may be created after some sinks closed.
But the initial `use_cnt` of those streams are still `num_local_sinks`,
which causes `use_cnt` cannot reach 0 and `CLOSE_LOAD` will never be sent. 

This PR fixes this problem by removing `use_cnt` from individual streams.
Sinks will now rely on the `use_cnt` in each `LoadStreamMap` to determine whether this is the last sink.
Only the last sink will handle the close_load, close_wait and commit_info.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
