### PR TITLE
[case](udf) support run java udf case on cluster with multiple BEs

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Comment by hello-stephen** [comment]
2.1 https://github.com/apache/doris/pull/36742
2.0 https://github.com/apache/doris/pull/36741

**Pull request merged**
