### PR TITLE
[Fix](ut) Fix BE UT macOS compile

### PR DESCRIPTION
**Pull request by platoneko**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
