### PR TITLE
[Improvement](decimal) print decimal according to the real precision and scale

### PR DESCRIPTION
**Pull request by Gabriel39**
# Proposed changes

before:
image

after:
image

image

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by LOVEGISER** [comment]
i have test，this is great

`
CREATE TABLE `test` (
  `id` varchar(32) NULL DEFAULT "",
  `user_name` varchar(32) NULL DEFAULT "",
  `member_list` DECIMAL(10,3)
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);


INSERT INTO test VALUES ('2','sim',1.000);
INSERT INTO test VALUES ('2','sim',1.001);
INSERT INTO test VALUES ('2','sim',1.002);

mysql> select  * from test;
+------+-----------+-------------+
| id   | user_name | member_list |
+------+-----------+-------------+
| 2    | sim       |       1.002 |
| 2    | sim       |       1.001 |
| 2    | sim       |       1.000 |


mysql> select  cast(avg(member_list) as DECIMAL(10,3)) from test;
+-------------------------------------------+
| CAST(avg(`member_list`) AS DECIMAL(10,3)) |
+-------------------------------------------+
|                                     1.000 |
+-------------------------------------------+
1 row in set (0.02 sec)

`

**Comment by dataroaring** [comment]
We should update result for p2 cases too.

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 40.88 seconds
 load time: 570 seconds
 storage size: 17154602757 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020205802_clickbench_pr_32113.html

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
