### PR TITLE
[docs](auth): forbid 127.0.0.1 passwd free login

### PR DESCRIPTION
**Pull request by haochengxia**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Handle description inconsistency in password-free login 

PR #18816 omitted a necessary change.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by haochengxia** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by haochengxia** [comment]
run buildall

**Comment by haochengxia** [comment]
run buildall

**Comment by zy-kkk** [comment]
please rebase your branch to master

**Comment by zy-kkk** [comment]
run buildall

**Comment by haochengxia** [comment]
Used `rebase` (force push) to avoid `merge` commit.

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run p0

**Pull request merged**
