### PR TITLE
[Chore] remove unused code

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #xxx

remove unused class

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run build all

**Review by yiguolei — COMMENTED** [review]
This class is useless, you could remove it directly.

**Comment by Vallishp** [comment]
> This class is useless, you could remove it directly.

done

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run build all

**Comment by Vallishp** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
