### PR TITLE
[fix] (docs) Fix wrong path in /docs folder

### PR DESCRIPTION
**Pull request by gogim1**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by GoGim1** [comment]
I found that if this PR was merged, images on [Doris's website](https://doris.apache.org/docs/summary/basic-summary) would get the wrong path since the website only copies the docs/images directory to the static/ instead of the docs/. Even though some images cannot be found when reading md files [directly on the github](https://github.com/apache/doris/tree/master/docs/zh-CN/docs) , I think it's better to close this PR. Any ideas?
@morningma

**Comment by Yukang-LIAN** [comment]
> Even though some images cannot be found when reading md files [directly on the github](https://github.com/apache/doris/tree/master/docs/zh-CN/docs) , I think it's better to close this PR. Any ideas?
> @MorningMa

Maybe you @ the wrong guy. :joy: I think this is the right one. @morningman

**Comment by morningman** [comment]
@hf200012 PTAL

**Comment by hf200012** [comment]
Here is the official website, the official website of the picture path is all /images beginning

**Pull request closed without merging**
