### PR TITLE
[fix](json) change int to bigint for json function

### LINKED ISSUE #17607: [Bug] The length is lost after converting the long value using json_object
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

- 1.1.3
- 1.2.2

### What's Wrong?

**The length is lost after converting the long value using json_object.**

Such as：

image

### What You Expected?

```
SELECT json_object('ts', unix_timestamp() * 1000) AS ts;
```
```
The correct value is: {"ts":1678351570000}
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #17607

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.6 seconds
 stream load tsv:          463 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         37 seconds loaded 2358488459 Bytes, about 60 MB/s
 stream load orc:          74 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230314073351_clickbench_pr_113945.html

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run DORIS_COMPILE

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p1

**Comment by nextdreamblue** [comment]
run p1

**Comment by nextdreamblue** [comment]
run p1

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by xiaokang** [comment]
@nextdreamblue can you add a get_json_bigint instead of change the behavior of get_json_int

**Comment by xiaokang** [comment]
BTW, binary json type JSONB is much faster than json text, have you try it?

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
