### PR TITLE
[typo](doc)Add Broker installation and upgrade to 1.2.2

### PR DESCRIPTION
**Pull request by davidshtian**
Add Broker [installation in docker-compose](https://doris.apache.org/docs/dev/install/construct-docker/run-docker-cluster) and upgrade docker image to 1.2.2 version.

# Proposed changes

Issue Number: N/A

## Problem summary

Add Broker [installation in docker-compose](https://doris.apache.org/docs/dev/install/construct-docker/run-docker-cluster) and upgrade docker image to 1.2.2 version.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
@FreeOnePlus PTAL

**Comment by FreeOnePlus** [comment]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
