### PR TITLE
[Bug](function) catch error state in function cast to avoid core dump

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

catch error state in function cast to avoid core dump

```cpp
java.lang.IllegalStateException: exceptions : exception : errCode = 2, detailMessage = (172.21.0.22)[E-123][E-123] std::bad_typeid
    @     0x561088ee86e5  doris::Exception::Exception()
    @     0x561088fb9cec  typeid_cast<>()
    @     0x561088fb8305  doris::vectorized::check_and_get_column<>()
    @     0x56109f622d1c  doris::vectorized::wrap_in_nullable()
    @     0x5610a06b319a  _ZZNK5doris10vectorized12FunctionCast23prepare_remove_nullableEPNS_15FunctionContextERKSt10shared_ptrIKNS0_9IDataTypeEES9_bENKUlS3_RNS0_5BlockERKSt6vectorImSaImEEmmE_clES3_SB_SG_mm
    @     0x5610a06b2064  _ZSt13__invoke_implIN5doris6StatusERZNKS0_10vectorized12FunctionCast23prepare_remove_nullableEPNS0_15FunctionContextERKSt10shared_ptrIKNS2_9IDataTypeEESB_bEUlS5_RNS2_5BlockERKSt6vectorImSaImEEmmE_JS5_SD_SI_mmEET_St14__invoke_otherOT0_DpOT1_
    @     0x5610a06b1f1c  _ZSt10__invoke_rIN5doris6StatusERZNKS0_10vectorized12FunctionCast23prepare_remove_nullableEPNS0_15FunctionContextERKSt10shared_ptrIKNS2_9IDataTypeEESB_bEUlS5_RNS2_5BlockERKSt6vectorImSaImEEmmE_JS5_SD_SI_mmEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESM_E4typeEOSN_DpOSO_
    @     0x5610a06b1c8c  _ZNSt17_Function_handlerIFN5doris6StatusEPNS0_15FunctionContextERNS0_10vectorized5BlockERKSt6vectorImSaImEEmmEZNKS4_12FunctionCast23prepare_remove_nullableES3_RKSt10shared_ptrIKNS4_9IDataTypeEESJ_bEUlS3_S6_SB_mmE_E9_M_invokeERKSt9_Any_dataOS3_S6_SB_OmSQ_
    @     0x5610a008dd9f  std::function<>::operator()()
    @     0x5610a036bf69  doris::vectorized::PreparedFunctionCast::execute_impl()
    @     0x56109f62f4d3  doris::vectorized::PreparedFunctionImpl::_execute_skipped_constant_deal()
    @     0x56109f627201  doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns()
    @     0x56109f627320  doris::vectorized::PreparedFunctionImpl::execute()
    @     0x56109c74307b  doris::vectorized::IFunctionBase::execute()
    @     0x56109c7b283f  doris::vectorized::VCastExpr::execute()
    @     0x56109c7c0642  doris::vectorized::VExprContext::execute()
    @     0x56109c34587a  doris::vectorized::Sorter::partial_sort()
    @     0x56109c348133  doris::vectorized::FullSorter::_do_sort()
    @     0x56109c348baf  doris::vectorized::FullSorter::prepare_for_read()
    @     0x56109c617baf  doris::vectorized::VSortNode::sink()
    @     0x56109c618769  doris::vectorized::VSortNode::open()
    @     0x56109c287f8f  doris::vectorized::VAnalyticEvalNode::open()
    @     0x56109c40a9ec  doris::vectorized::VSelectNode::open()
    @     0x56109b9a370f  doris::vectorized::VJoinNodeBase::_probe_side_open_thread()
    @     0x56109b9a3ba0  doris::vectorized::VJoinNodeBase::open()::$_0::operator()()
    @     0x56109b9a3af5  std::__invoke_impl<>()
    @     0x56109b9a3a95  _ZSt10__invoke_rIvRZN5doris10vectorized13VJoinNodeBase4openEPNS0_12RuntimeStateEE3$_0JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @     0x56109b9a38fd  std::_Function_handler<>::_M_invoke()
    @     0x561088c17f13  std::function<>::operator()()
    @     0x56108bba7c09  doris::FunctionRunnable::run()
    @     0x56108bb951a7  doris::ThreadPool::dispatch_thread()
    @     0x56108bbbafa4  std::__invoke_impl<>()
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
