### PR TITLE
[fix](routine-load) update partition offset cache timely to avoid negative lag

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Lag is negative when we use routine load, it is need check all partitions, for some partitions offset may be out of time.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run build

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
