### PR TITLE
[enhancement](regression-test) sync unique case to 2.1

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Pull request merged**
