### PR TITLE
[Doris On ES] Pushdown some  castexpr predicate to ES

### PR DESCRIPTION
**Pull request by wuyunfeng**
Process castexpr, such as: k (float) > 2.0, k(int) > 3.2, Doris On Es should ignore this doris native cast transformation for every row's col value, we push down this `cast semantic` to Elasticsearch.  

I believe in this `predicate` situation, would decrease the mount of data for transmission。

k1 is float:

````
k1 >= 5
````

push-down filter:

```
{"range":{"k1":{"gte":"5.000000"}}}
```
k2 is int :

```
k2 > 3.2
```

push-down filter:

```
{"range":{"k2":{"gte":"3.2"}}}
```

### CODE REVIEW

**Comment by wuyunfeng** [comment]
for https://github.com/apache/incubator-doris/issues/3306

**Comment by kangkaisen** [comment]
@wuyunfeng Hi, please add a UT to cover this case in `EsPredicateTest`.

**Comment by wuyunfeng** [comment]
@kangkaisen For now, it is difficult to construct the `ExprContext`, the previous `EsPredicateTest ` is meaningfulless

**Review by kangkaisen — APPROVED** [review]
+1， LGTM

**Review by imay — APPROVED** [review]
LGTM

**Pull request merged**
