### PR TITLE
[fix](compile) fix mac compile

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by JackDrogon — CHANGES_REQUESTED** [review]
LGTM

**Review by JackDrogon — APPROVED** [review]
LGTM

**Comment by jacktengg** [comment]
duplicate with #26155

**Comment by zy-kkk** [comment]
same as #26155 , close this

**Pull request closed without merging**
