### PR TITLE
[fix](multi-catalog)fix max compute array and map type read offset

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

fix for https://github.com/apache/doris/pull/39259

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
