### PR TITLE
[fix](migrate disk) fix migrate disk lost data during publish version

### PR DESCRIPTION
**Pull request by yujun777**
Tablet migrate disk may cause lost data. For example,   suppose the old tablet's version is 10,   it's just publish txn on version 11.  At then comes a migrate disk task. After the old tablet just finish publish txn 11, but before it add rowset( version = 11).  For the migrating task,  the old tablet had no txn now,   so the new tablet will copy the old tablet's data(old tablet's version is still 10).   After copying,  it will delete the old tablet,  and replace it with the new tablet.
So data whose version is 11  will be lost.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run beut

**Comment by yiguolei** [comment]
run feut

**Comment by dataroaring** [comment]
run clickbench

**Comment by dataroaring** [comment]
run clickbench-new

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
