### PR TITLE
[Bug](agg) percentile_approx_weighted function should sure the input value is valid

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

the weight should be positive num, as have check the value valid use DCHECK_GT(c._weight, 0) in Centroid;
```
    void add(const Centroid& c) {
        DCHECK_GT(c._weight, 0);
        if (_weight != 0.0) {
            _weight += c._weight;
            _mean += c._weight * (c._mean - _mean) / _weight;
        } else {
            _weight = c._weight;
            _mean = c._mean;
        }
    }
```

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
Should also change the Doc Plz

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
> Should also change the Doc Plz

doc: https://github.com/apache/doris-website/pull/1053

**Review by Mryange — APPROVED** [review]

**Review by zclllyybb — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
