### PR TITLE
[Fix](inverted index) fix fast execute for not_in expr

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

not_in predicate is not processed correctly in vin_predicate fast_execute

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — COMMENTED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
