### PR TITLE
[enhancement](streamload) allow table in url when do two-phase commit (#15246)

### LINKED ISSUE #15246: [Enhancement] allow table in url when do two-phase commit
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

when doing two-phase load, user need to do following two steps:

1) precommit
curl --location-trusted -u user:passwd -H "two_phase_commit:true" -T test.txt  http://fe_host:http_port/api/{db}/{table}/_stream_load

2) actual commit
curl -X PUT --location-trusted -u user:passwd -H "txn_id:18036" -H "txn_operation:commit" http://fe_host:http_port/api/{db}/_stream_load_2pc

the url in step 2) has two difference against step 1):
1. _stream_load -> _stream_load_2pc, which is obvious
2. {table} is omitted, which is not very obvious

Is is reasonable to remove {table} because Txn id is provided so {table} is no longer needed. But user can be confused if they failed to omit it -- usually one may just copy&paste the url.

### Solution

let us make it works even if user provide us with (unnecessary) table info in url. i.e., `curl -X PUT --location-trusted -u user:passwd -H "txn_id:18036" -H "txn_operation:commit" http://fe_host:http_port/api/{db}/{table}/_stream_load_2pc` can still works!

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by freemandealer**
Make it works even if user provide us with (unnecessary) table info in url. i.e. `curl -X PUT --location-trusted -u user:passwd -H "txn_id:18036" -H \ "txn_operation:commit" http://fe_host:http_port/api/{db}/{table}/_stream_load_2pc` can still works!

Signed-off-by: freemandealer <freeman.zhang1992@gmail.com>

# Proposed changes

Issue Number: close #15246

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [X] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [X] No Need
3. Has document been added or modified:
    - [X] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [X] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [X] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — COMMENTED** [review]
What if user specify a different table?

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.75 seconds
 load time: 633 seconds
 storage size: 17122838244 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221221134229_clickbench_pr_66415.html

**Comment by morningman** [comment]
Why should we support this url? Since {table} is meaningless?

**Comment by freemandealer** [comment]
> What if user specify a different table?

It would commit the transaction based on specific txnid, table name only works as a placeholder and is ignored by the service.

**Comment by freemandealer** [comment]
> Why should we support this url? Since {table} is meaningless?

Yes, {table} is unnecessary. I just try to make the url more consistant with the one in precommit command. I saw users copied&pasted the url from precommit command and confused why it won't works in commit.

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
