### PR TITLE
[fix](mtmv)Fix that the storage medium specified for the mtmv is SSD, but the partition storage medium for the mtmv is still HDD

### PR DESCRIPTION
**Pull request by zddr**
fix when create mtmv use property `'storage_medium' = 'SSD'`,after refresh mtmv, partition's `storage_medium` is HDD

Not only is there a problem with mtmv, but essentially, when creating partitions, there is no inheritance of the table

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run performance

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Review by shuke987 — APPROVED** [review]
LGTM

**Pull request merged**
