### PR TITLE
[fix](schema change) fix bug of query failure after rename column

### PR DESCRIPTION
**Pull request by luwei16**
### Fix the following issue
```
CREATE TABLE IF NOT EXISTS t1 (
                k1 INT NOT NULL,
                value1 varchar(16) NOT NULL,
                value2 int NOT NULL
)
DUPLICATE KEY (k1)
DISTRIBUTED BY HASH(k1) BUCKETS 1 properties("replication_num" = "1");

select * from t1

ALTER TABLE t1 RENAME COLUMN value2 new_col

select * from t1 where new_col = xxx  // failed，The old schema in the be scheam cache was used in the query. The 
                                                                // new_col column could not be found and an error was reported.

```

### fix

When rename the column, the schema version+1 is added in FE, and the BE schema cache key encoding uses the schema version. Since the BE schema cache key has changed, the old schema cache is no longer used in the query. 

### compatibility
Since the old version does not have a persistent schemaVersion field in TableRenameColumnInfo, when the rename edit log of the old version is replayed in the new version of FE, the schema version will not be modified, so the metadata of the FE master and observer will not be inconsistent.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
lgtm

**Review by dataroaring — COMMENTED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by swjtu-zhanglei — APPROVED** [review]

**Pull request merged**
