### PR TITLE
[opt](session var) throw exception when setting query time out to zero

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
1. make query timeout of SessionVariable private;
2. throw exception if `set query_timeout = 0` like below:
```
mysql [(none)]>set query_timeout=0;
--------------
set query_timeout=0
--------------

ERROR 1228 (HY000): errCode = 2, detailMessage = Query timeout must be greater than 0
```
3. add warning log when setting query timeout of Userproperty to zero

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
