### PR TITLE
[feature](storage)support delete condition

### PR DESCRIPTION
**Pull request by wangbo**
# Proposed changes

[Vectorization]Support delete condition in Storage layer 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangbo** [comment]
I'll add some UT tests later

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
hi @wangbo , please resolve the conflict

**Comment by wangbo** [comment]
@morningman conflicts has been resolved

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
