### PR TITLE
[fix](case)fix PolicyTest testMergeFilterNereidsPlanner failed

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

The results of explain may have some order that is not fixed
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Review by AshinGau — APPROVED** [review]

**Comment by morningman** [comment]
run performance

**Pull request merged**
