### PR TITLE
[fix](statistics)Fix auto analyze bugs.

### PR DESCRIPTION
**Pull request by Jibing-Li**
1. Fix auto analyze doesn't filter unsupported type bug.
 2. Catch throwable in auto analyze thread for each database, otherwise the thread will quit when one database failed to create jobs and all other databases will not get analyzed.
 3. change FE config item full_auto_analyze_simultaneously_running_task_num to auto_analyze_simultaneously_running_task_num

backport https://github.com/apache/doris/pull/27559

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by Kikyou1997 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
