### PR TITLE
[fix](operation_node)Replace structure to ensure same colRef can be save

### LINKED ISSUE #28438: [Bug] when use Minus or Except ，single node output column result incorrect, multiple nodes experience crash phenomenon
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

multiple node 
image
single node 
image

### What You Expected?

fix it

### How to Reproduce?

Reproducing statements as below:

```sql
CREATE TABLE test_varchar(c1 varchar) DISTRIBUTED BY hash(c1) PROPERTIES ("replication_num" = "1");
CREATE TABLE test_date(c2 date) DISTRIBUTED BY hash(c2) PROPERTIES  ("replication_num" = "1");
insert into test_varchar values('+06-00');
insert into test_date values('1990-11-11');
SELECT c1, c1 FROM test_varchar MINUS SELECT c2, c2 FROM test_date;

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TomaYoko**
## Proposed changes

Issue Number: close #28438 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TomaYoko** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Comment by hello-stephen** [comment]
run pipelinex_p0

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
image

I explained the query plan, do you mean the c1 is the slot ref and the result column id is the same?

And could you try if SELECT expr(c1),expr(c1) FROM test_varchar1 MINUS select c2,c2 from test_date;? 
If we add an expression to c1 column, is there still any problem?
@TomaYoko

**Comment by yiguolei** [comment]
@TomaYoko And please add comment on multi_map to explain why we need multimap here, so that other developers will notice that when do some refactor work.

**Review by mrhhsg — COMMENTED** [review]
Maybe we can swap the 'first' and the 'second' to avoid this issue?

**Comment by TomaYoko** [comment]
> @TomaYoko And please add comment on multi_map to explain why we need multimap here, so that other developers will notice that when do some refactor work.

@yiguolei What I have tried  before is that when  string type such as CHAR/VARCHAR/STRING type(other type are not this phenomenon) used as original column in a minus/except statement, same column will use the same ColRef id which will cause the order_map only saves only one col ，thus ,will cause the result is incorrect. this similar pr is mentioned in #28440, which I have discussed with @zhiqiang-hhhh

**Comment by TomaYoko** [comment]
> Maybe we can swap the 'first' and the 'second' to avoid this issue?

@mrhhsg This modification may involve more changes than simply  adjusting the code structure.

**Comment by TomaYoko** [comment]
> image
> I explained the query plan, do you mean the c1 is the slot ref and the result column id is the same?
> 
> And could you try if SELECT expr(c1),expr(c1) FROM test_varchar1 MINUS select c2,c2 from test_date;? If we add an expression to c1 column, is there still any problem? @TomaYoko

https://github.com/apache/doris/blob/b06f3edcab2ac1ce5271c03280c906d150bd8eeb/be/src/vec/exec/vset_operation_node.cpp#L453C1-L454C51

**Review by Gabriel39 — DISMISSED** [review]

**Comment by TomaYoko** [comment]
https://github.com/apache/doris/blob/b06f3edcab2ac1ce5271c03280c906d150bd8eeb/be/src/vec/exec/vset_operation_node.cpp#L453-L454

**Comment by zhiqiang-hhhh** [comment]
@TomaYoko hello, we are fixing the result format problem. 
I just tried similar pattern on join to make sure we don't have same problem on join node, unfortunately I met some problem which is described in https://github.com/apache/doris/issues/28540.
Maybe problem is different from this PR, but still wondering if you have interest to help us fix a new problem?

**Comment by TomaYoko** [comment]
> @TomaYoko hello, we are fixing the result format problem. I just tried similar pattern on join to make sure we don't have same problem on join node, unfortunately I met some problem which is described in #28540. Maybe problem is different from this PR, but still wondering if you have interest to help us fix a new problem?

ok, maybe I'll try

**Comment by yiguolei** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
@TomaYoko the problem of result format is still addressing, will let you know if any progress

**Comment by TomaYoko** [comment]
> @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> 
> PS: Could you please add some comments on why we need to modify the data structure?



> @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> 
> PS: Could you please add some comments on why we need to modify the data structure?

https://github.com/apache/doris/blob/b06f3edcab2ac1ce5271c03280c906d150bd8eeb/be/src/vec/exec/vset_operation_node.cpp#L453-L454
@zhiqiang-hhhh  I've mentioned before,the phenomenon is when string type such as CHAR/VARCHAR/STRING type(other type are not this phenomenon) used as original column in a minus/except statement, same column will use the same ColRef id which will cause the order_map only saves only one col ，thus ,will cause the result incorrect.

**Comment by zhiqiang-hhhh** [comment]
> > @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> > PS: Could you please add some comments on why we need to modify the data structure?
> 
> > @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> > PS: Could you please add some comments on why we need to modify the data structure?
> 
> https://github.com/apache/doris/blob/b06f3edcab2ac1ce5271c03280c906d150bd8eeb/be/src/vec/exec/vset_operation_node.cpp#L453-L454
> 
> 
> @zhiqiang-hhhh I've mentioned before,the phenomenon is when string type such as CHAR/VARCHAR/STRING type(other type are not this phenomenon) used as original column in a minus/except statement, same column will use the same ColRef id as key which will cause the order_map only save one col(normally, two columns should be saved) ，thus ,will cause the result incorrect,

I've seen this. 
I mean to add some Code Comment on cpp files(be/src/vec/exec/vset_operation_node.h:111 and pipelineX), so that others can figure out what happened when they reading the code instead of open this PR.

**Comment by TomaYoko** [comment]
> > > @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> > > PS: Could you please add some comments on why we need to modify the data structure?
> > 
> > 
> > > @TomaYoko the problem of result format is still addressing, will let you know if any progress.
> > > PS: Could you please add some comments on why we need to modify the data structure?
> > 
> > 
> > https://github.com/apache/doris/blob/b06f3edcab2ac1ce5271c03280c906d150bd8eeb/be/src/vec/exec/vset_operation_node.cpp#L453-L454
> > 
> > @zhiqiang-hhhh I've mentioned before,the phenomenon is when string type such as CHAR/VARCHAR/STRING type(other type are not this phenomenon) used as original column in a minus/except statement, same column will use the same ColRef id as key which will cause the order_map only save one col(normally, two columns should be saved) ，thus ,will cause the result incorrect,
> 
> I've seen this. I mean to add some Code Comment on cpp files(be/src/vec/exec/vset_operation_node.h:111 and pipelineX), so that others can figure out what happened when they reading the code instead of open this PR.

ok,I've done.

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by TomaYoko** [comment]
run buildall

**Pull request closed without merging**
