### PR TITLE
[ut](filecache) fix try_any_cast error in UTs

### PR DESCRIPTION
**Pull request by freemandealer**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
blocked by UTs (not related to this PR)

**Review by yiguolei — APPROVED** [review]

**Comment by freemandealer** [comment]
remove the dev/2.1.x FFS coz the tests in 2.1 require no fix at all

**Pull request merged**
