### PR TITLE
[fix](hdfs)read 'fs.defaultFS' from core-site.xml for hdfs load which has no default fs

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

read 'fs.defaultFS' from hdfs-site.xml for hdfs load which has no default fs 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please add test cases for it

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run feut

**Comment by wsjz** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Comment by morningman** [comment]
run beut

**Pull request merged**
