### PR TITLE
[compile]( fix ) fix compile in gcc

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes
when compile 
`
template <class Lock>
concept IsXLock = requires {
    std::same_as<Lock, std::lock_guard<std::mutex>> || 
    std::same_as<Lock, std::unique_lock<std::mutex>>; };
`
with gcc 13.1.0 on linux, it will reports 
`
warning: testing if a concept-id is a valid expression; add 'requires' to check satisfaction [-Wmissing-requires]
    9 | concept IsXLock = requires { std::same_as<Lock, std::lock_guard<std::mutex>> ||
      |                               ^
      |                               requires 
`

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shuke987** [comment]
run performance

**Comment by cambyzju** [comment]
please add some desc in pr, such as: which os, which gcc version, and the error message.

**Comment by shuke987** [comment]
run performance

**Review by adonis0147 — DISMISSED** [review]

**Comment by shuke987** [comment]
run buildall

**Review by Lchangliang — APPROVED** [review]

**Comment by shuke987** [comment]
run performance

**Comment by shuke987** [comment]
run performance

**Comment by shuke987** [comment]
run performance

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run performance

**Comment by shuke987** [comment]
run performance

**Pull request closed without merging**
