### PR TITLE
[fix](statistics)Refresh follower FE cache after alter column stats. Support alter index column stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
1. Refresh follower FE cache after alter column stats. So that follower could update the cached stats too.
2. Support alter index column stats.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by Jibing-Li** [comment]
run buildall

**Comment by hello-stephen** [comment]
run feut

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
