### PR TITLE
[Bug](delete) Fix bug of delete partition prune error

### LINKED ISSUE #18056: [Bug] delete from do not get right result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

CREATE TABLE `test`.`tb_test1` (
  `dt` date NULL COMMENT '统计日期',
  `code` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`dt`, `code`)
COMMENT 'OLAP'
PARTITION BY RANGE(`dt`)
(PARTITION m202206 VALUES [('2022-06-01'), ('2022-07-01')),
PARTITION m202207 VALUES [('2022-07-01'), ('2022-08-01')),
PARTITION m202208 VALUES [('2022-08-01'), ('2022-09-01')),
PARTITION m202209 VALUES [('2022-09-01'), ('2022-10-01')),
PARTITION m202210 VALUES [('2022-10-01'), ('2022-11-01')),
PARTITION m202211 VALUES [('2022-11-01'), ('2022-12-01')),
PARTITION m202212 VALUES [('2022-12-01'), ('2023-01-01')),
PARTITION m202301 VALUES [('2023-01-01'), ('2023-02-01')),
PARTITION m202302 VALUES [('2023-02-01'), ('2023-03-01')),
PARTITION m202303 VALUES [('2023-03-01'), ('2023-04-01')),
PARTITION m202304 VALUES [('2023-04-01'), ('2023-05-01')))
DISTRIBUTED BY HASH(`dt`, `code`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "m",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "10",
"dynamic_partition.create_history_partition" = "false",
"dynamic_partition.history_partition_num" = "-1",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"dynamic_partition.start_day_of_month" = "1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);

insert into test.tb_test1 values ('2022-10-01', 123);

mysql> select * from tb_test1 where dt = '2022-10-01';
+------------+------+
| dt         | code |
+------------+------+
| 2022-10-01 |  123 |
+------------+------+

mysql> select * from tb_test1 where dt = '20221001';
+------------+------+
| dt         | code |
+------------+------+
| 2022-10-01 |  123 |
+------------+------+

mysql> delete from tb_test1 where dt = '20221001';
Query OK, 0 rows affected (0.04 sec)

mysql> select * from tb_test1 where dt = '20221001';
+------------+------+
| dt         | code |
+------------+------+
| 2022-10-01 |  123 |
+------------+------+

### What You Expected?

delete successful

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #18056 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.76 seconds
 stream load tsv:          469 seconds loaded 74807831229 Bytes, about 152 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          75 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          33 seconds loaded 861443392 Bytes, about 24 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230323102749_clickbench_pr_119569.html

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
