### PR TITLE
[fix](nereids)update regression case for eager-agg

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

the new plans are better than original plans.

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by starocean999 — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
