### PR TITLE
[Fix](Job)Job repaly logic error

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
revert this one
img_v3_02ag_d2b78ab8-b5f6-47ae-a402-7950f9eeb32g

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by NANJIDONG — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run external

**Comment by CalvinKirs** [comment]
run external

**Comment by CalvinKirs** [comment]
run buildall

**Pull request merged**
