### PR TITLE
[docker](trino) add Trino docker compose and hive catalog

### PR DESCRIPTION
**Pull request by bingquanzhao**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
