### PR TITLE
[Feature](rpc) support set brpc_idle_timeout_sec and enable thrift socket keep alive

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
In some special circumstances (such as network instability), the brpc server will always retain many tcp connections.

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by w41ter — APPROVED** [review]

**Pull request merged**
