### PR TITLE
[fix](orc)fix orc reader missing column and filter missing column.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

Fixed the problem that filtering with non-existent columns failed when reading orc tables

example : 
```
mysql> select * from sc_test;
+------+------+-------+----------------------+----------+
| id   | type | state | sensitive_query_flag | dt       |
+------+------+-------+----------------------+----------+
|    5 |    6 | bac   |                 NULL | 20240226 |
|    3 |    4 | bac   |                 NULL | 20240227 |
|    1 |    2 | bac   |                    1 | 20240228 |
+------+------+-------+----------------------+----------+
3 rows in set (0.03 sec)

mysql> select * from sc_test where sensitive_query_flag is null;
0 rows in set (0.03 sec)
```
after : 
```
mysql> select * from sc_test where sensitive_query_flag is null;
+------+------+-------+----------------------+----------+
| id   | type | state | sensitive_query_flag | dt       |
+------+------+-------+----------------------+----------+
|    3 |    4 | bac   |                 NULL | 20240227 |
|    5 |    6 | bac   |                 NULL | 20240226 |
+------+------+-------+----------------------+----------+
2 rows in set (0.03 sec)

```

Issue Number: close #xxx

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Review by AshinGau — DISMISSED** [review]

**Comment by AshinGau** [comment]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
