### PR TITLE
[fix](olap) dictionary cannot be sorted after inserting some null values

### PR DESCRIPTION
**Pull request by mrhhsg**
# Proposed changes

Issue Number: close #xxx

## Problem summary

coredump:
```bash
#0  0x000055cf7bf6a1b8 in doris::vectorized::ColumnDictionary<int>::Dictionary::convert_code (code=@0x7f92ea19e098: 0, this=0x7f92ea117220) at /root/doris-1.2.1-rc01/be/src/vec/columns/column_dictionary.h:442
#1  doris::vectorized::ColumnDictionary<int>::convert_dict_codes_if_necessary (this=<optimized out>) at /root/doris-1.2.1-rc01/be/src/vec/columns/column_dictionary.h:250
#2  doris::vectorized::ColumnDictionary<int>::convert_dict_codes_if_necessary (this=0x7f92ea117200) at /root/doris-1.2.1-rc01/be/src/vec/columns/column_dictionary.h:242
#3  0x000055cf7c433a20 in doris::segment_v2::SegmentIterator::_convert_dict_code_for_predicate_if_necessary (this=this@entry=0x7f92ea11fc00) at /root/doris-1.2.1-rc01/be/src/olap/rowset/segment_v2/segment_iterator.cpp:1249
#4  0x000055cf7c43edca in doris::segment_v2::SegmentIterator::next_batch (this=0x7f92ea11fc00, block=<optimized out>) at /root/doris-1.2.1-rc01/be/src/olap/rowset/segment_v2/segment_iterator.cpp:1164
#5  0x000055cf7c7271da in doris::BetaRowsetReader::next_block (this=0x7f9178a83c00, block=0x7f91780da800) at /root/doris-1.2.1-rc01/be/src/olap/rowset/beta_rowset_reader.cpp:277
#6  0x000055cf8004af81 in doris::vectorized::VCollectIterator::Level0Iterator::next (this=0x7f92ea1001c0, block=0x7f91780da800) at /root/doris-1.2.1-rc01/be/src/vec/olap/vcollect_iterator.cpp:267
#7  0x000055cf8004a749 in doris::vectorized::VCollectIterator::Level1Iterator::_normal_next (this=0x7f92ea100260, block=0x7f91780da800) at /root/doris-1.2.1-rc01/be/src/vec/olap/vcollect_iterator.cpp:533
#8  0x000055cf8004ca6e in doris::vectorized::VCollectIterator::Level1Iterator::next (this=<optimized out>, block=<optimized out>) at /root/doris-1.2.1-rc01/be/src/vec/olap/vcollect_iterator.cpp:359
#9  0x000055cf80049d5a in doris::vectorized::VCollectIterator::next (this=this@entry=0x7f9178a7f1b8, block=<optimized out>) at /root/doris-1.2.1-rc01/be/src/vec/olap/vcollect_iterator.cpp:187
#10 0x000055cf80041395 in doris::vectorized::BlockReader::_direct_next_block (this=0x7f9178a7ee00, block=<optimized out>, mem_pool=<optimized out>, agg_pool=<optimized out>, eof=0x7f92f5ff65b6) at /root/doris-1.2.1-rc01/be/src/vec/olap/block_reader.cpp:167
#11 0x000055cf80047279 in doris::vectorized::BlockReader::next_block_with_aggregation (this=<optimized out>, block=<optimized out>, mem_pool=<optimized out>, agg_pool=<optimized out>, eof=<optimized out>) at /root/doris-1.2.1-rc01/be/src/vec/olap/block_reader.h:45
#12 0x000055cf8024302d in doris::vectorized::NewOlapScanner::_get_block_impl (this=0x7f9178a74c00, state=<optimized out>, block=0x7f91780da800, eof=0x7f92f5ff65b6) at /var/local/ldb-toolchain/include/c++/11/bits/unique_ptr.h:173
#13 0x000055cf80224f13 in doris::vectorized::VScanner::get_block (this=this@entry=0x7f9178a74c00, state=state@entry=0x7f93393fe300, block=block@entry=0x7f91780da800, eof=eof@entry=0x7f92f5ff65b6) at /root/doris-1.2.1-rc01/be/src/vec/exec/scan/vscanner.cpp:53
#14 0x000055cf8022239f in doris::vectorized::ScannerScheduler::_scanner_scan (this=<optimized out>, scheduler=<optimized out>, ctx=0x7f9178bb6800, scanner=0x7f9178a74c00) at /root/doris-1.2.1-rc01/be/src/vec/exec/scan/scanner_scheduler.cpp:234
#15 0x000055cf7ca75805 in std::function<void ()>::operator()() const (this=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:560
#16 doris::FunctionRunnable::run (this=<optimized out>) at /root/doris-1.2.1-rc01/be/src/util/threadpool.cpp:45
#17 doris::ThreadPool::dispatch_thread (this=0x7f9338457400) at /root/doris-1.2.1-rc01/be/src/util/threadpool.cpp:534
#18 0x000055cf7ca6bbef in std::function<void ()>::operator()() const (this=0x7f9337edd478) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:560
#19 doris::Thread::supervise_thread (arg=0x7f9337edd460) at /root/doris-1.2.1-rc01/be/src/util/thread.cpp:454
#20 0x00007f93543d6ea5 in __pthread_mutex_unlock_full () from /lib64/libpthread.so.0
#21 0x0000000000000000 in ?? ()
```

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.96 seconds
 load time: 494 seconds
 storage size: 17122022977 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230111131433_clickbench_pr_77790.html

**Review by dataroaring — CHANGES_REQUESTED** [review]
Could you add a regression test?

**Comment by mrhhsg** [comment]
> Could you add a regression test?

Hi @dataroaring , I have added a case.

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
