### PR TITLE
[Improvement](hive-udf)(doc) minimize hive-udf and add some docs.

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Doris has provided hive-bitmap-udf to convert data into bitmap on HIVE, but the udf jar package is too large, which exceeding 100MB, and there may be dependencies conflicts for different versions of Hadoop.  
企业微信截图_16946762807862

Therefore, I will remove unnecessary dependencies and greatly reduce the size of the package.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run p0

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Comment by wm1581066** [comment]
ZJCF

**Pull request merged**
