### PR TITLE
[chore](ut)add one option to skip build be when running ut

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes

Issue Number: close #xxx
Previously when we run be ut, it would always run building the whole binary. But sometimes I just change one conf in be.conf to test the UT, I think it would help when we just wanna run one UT without building it.
## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
If we didn't modify the source code, the build for BE should be skipped by running the command `./run-be-ut.sh --run`. Would you like to provide some steps to describe the scenario you mentioned.

**Comment by ByteYue** [comment]
>  Would you like to provide some steps to describe the scenario you mentioned.

Hi there, I was trying to deploy the ut binary from compile machine to another machine in another region in another cloud vendor to test some feature like downloading object storage file from the corresponding cloud platform using different threads nums which is configured by be.conf. 
And i ran into such scenario where the logic would try to find related CMake build files each time I type `bash run-be-ut.sh --run --filter=MyTest.*`. And unfortunately it failed cause there is no such thing. I think maybe it would help if we can manually choose to skip the related build steps when i just need to deploy only the binary to another machine to test the effects brought by another environment.

**Comment by BiteTheDDDDt** [comment]
> > Would you like to provide some steps to describe the scenario you mentioned.
> 
> Hi there, I was trying to deploy the ut binary from compile machine to another machine in another region in another cloud vendor to test some feature like downloading object storage file from the corresponding cloud platform using different threads nums which is configured by be.conf. And i ran into such scenario where the logic would try to find related CMake build files each time I type `bash run-be-ut.sh --run --filter=MyTest.*`. And unfortunately it failed cause there is no such thing. I think maybe it would help if we can manually choose to skip the related build steps when i just need to deploy only the binary to another machine to test the effects brought by another environment.

Maybe you can run binary ut directly, there is a exaple:
```sh
/be/ut_build_RELEASE/test/doris_be_test
--gtest_filter=GeoFunctionsTest.st_polygon 
--gtest_output=xml:/mnt/disk1/xx/incubator-doris/be/ut_build_ASAN/gtest_output/doris_be_test.xml 
--gtest_print_time=true
```

**Comment by ByteYue** [comment]
> > > Would you like to provide some steps to describe the scenario you mentioned.
> > 
> > 
> > Hi there, I was trying to deploy the ut binary from compile machine to another machine in another region in another cloud vendor to test some feature like downloading object storage file from the corresponding cloud platform using different threads nums which is configured by be.conf. And i ran into such scenario where the logic would try to find related CMake build files each time I type `bash run-be-ut.sh --run --filter=MyTest.*`. And unfortunately it failed cause there is no such thing. I think maybe it would help if we can manually choose to skip the related build steps when i just need to deploy only the binary to another machine to test the effects brought by another environment.
> 
> Maybe you can run binary ut directly, there is a example:
> 
> ```shell
> /be/ut_build_RELEASE/test/doris_be_test
> --gtest_filter=GeoFunctionsTest.st_polygon 
> --gtest_output=xml:/mnt/disk1/xx/incubator-doris/be/ut_build_ASAN/gtest_output/doris_be_test.xml 
> --gtest_print_time=true
> ```

It works well, i'll close this pr soon.

**Pull request closed without merging**
