### PR TITLE
[improvement][test] (log)Add more error message on connect to hdfs failure, and corresponding ut

### PR DESCRIPTION
**Pull request by zhannngchen**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

I met a failure of reading hdfs files in broker load, the error message is unclear and I spent a lot of time to locate the problem.
```
W0330 11:08:01.093812 2755268 broker_scan_node.cpp:364] Scanner[0] process failed. status=connect failed.
W0330 11:08:01.097682 2018787 fragment_mgr.cpp:234] Got error while opening fragment 712ae2b848324cb6-94a83d646173c1e9: Internal error: connect failed.
W0330 11:08:01.097702 2018787 tablet_sink.cpp:148] connect failed.
```
We should add more information when connect to hdfs failed.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
Please refer to : https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83

**Comment by zhannngchen** [comment]
> Please refer to : https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83

Do you mean the title or description not follow the guideline? Could you please provide more details?
Thanks

**Comment by EmmyMiao87** [comment]
> > Please refer to : https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83
> 
> Do you mean the title or description not follow the guideline? Could you please provide more details? Thanks

Yes, I mean the title of PR ~

**Comment by zhannngchen** [comment]
updated the title

**Pull request merged**
