### PR TITLE
[test](regression) add some regression cases on constant evaluation

### LINKED ISSUE #16505: [Bug] [daily] UNION ALL query return wrong
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master: doris-0.0.0-trunk-cf18de1

### What's Wrong?

jenkins failed case: https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/201/testReport/(root)/test_execute/test_issue_4772/

image

https://github.com/apache/doris/issues/4772

### What You Expected?

return 2 rows

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #16505

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.52 seconds
 stream load tsv:          482 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         36 seconds loaded 2358488459 Bytes, about 62 MB/s
 stream load orc:          68 seconds loaded 1101869774 Bytes, about 15 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230210113108_clickbench_pr_93762.html

**Comment by luozenglin** [comment]
run buildall

**Comment by luozenglin** [comment]
run compile

**Comment by luozenglin** [comment]
run buildall

**Review by yinzhijian — APPROVED** [review]
LGTM

**Pull request merged**
