### PR TITLE
[Feat](json) Support json_search function in 2.0

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes
pick #40948
Issue Number: close #xxx

### CODE REVIEW

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run external

**Review by cambyzju — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
