### PR TITLE
[fix](forward) fix MissingFormatArgumentException when failed to forward stmt to Master

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

The call of `String.format()` contains orphan `%s` that will cause following error.
Introduced from #21205

```
2023-07-24 12:46:33,059 WARN (mysql-nio-pool-5|1393) [StmtExecutor.executeByLegacy():762] execute Exception. stmt[2032, 896ff544d0b049f2-856be29f0f7744e5]
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519) ~[?:1.8.0_192]
        at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_192]
        at java.lang.String.format(String.java:2940) ~[?:1.8.0_192]
        at org.apache.doris.qe.MasterOpExecutor.forward(MasterOpExecutor.java:134) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MasterOpExecutor.execute(MasterOpExecutor.java:84) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:829) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:671) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:443) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:414) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:441) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:589) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:827) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192]
        at java.util.concurrent.ThreadPoo
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
PTAL @TangSiyang2001

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.35 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17169297859 Bytes

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
