### PR TITLE
[fix](regresion-test) Fix the problem of occasional failure of test_outfile_exception regression-test case

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

`test_outfile_exception` case may be failed because of timeout when accessing to S3 endpoint.

This is because P0 pipeline machine access `https://cos.ap-beijing.myqcloud.com` is unstable.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run p0

**Comment by BePPPower** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
