### PR TITLE
[fix](memory) fix memory GC details and join probe catch bad_alloc

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. Fix Redhat 4.x OS `/proc/meminfo` has no `MemAvailable`, disable `MemAvailable` to control memory.
2. `vm_rss_str` and `mem_available_str` recorded when gc is triggered, to avoid memory changes during gc and cause inaccurate logs.
3. join probe catch bad_alloc, this may alloc 64G memory at a time, avoid OOM.
4. Modify document `doris_be_all_segments_num` and `doris_be_all_rowsets_num` names.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.73 seconds
 stream load tsv:          469 seconds loaded 74807831229 Bytes, about 152 MB/s
 stream load json:         36 seconds loaded 2358488459 Bytes, about 62 MB/s
 stream load orc:          68 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230221113952_clickbench_pr_101050.html

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
