### PR TITLE
[fix](mtmv)fix MTMVTask log has null pointer

### PR DESCRIPTION
**Pull request by zddr**
`LOG.info("finish create mtmv task, task: {}", task);`
==> finish create mtmv task, task: [!!!org.apache.doris.job.extensions.mtmv.MTMVTask@xxx=>java.lang.NullPointerException:null!!!]

Suspected to be a problem with lombok, therefore displaying the implementation of a toString method

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
