### PR TITLE
[behavior change](fe) Change `ShowProcessStmt` output column format

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
* Show fe host info in output columns by default
* Add a new column `CloudCluster` for cloud cluster info

## Proposed changes
In the previous
```
set show_all_fe_connection = true;

    mysql [(none)]>show processlist;
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+------------+
| CurrentConnected | Id   | User | Host             | LoginTime           | Catalog  | Db   | Command | Time | State | QueryId                           | Info             | FE         |
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+------------+
| Yes              |    0 | root | 127.0.0.1:52494 | 2024-02-07 12:08:01 | internal |      | Query   |    0 | OK    | 2fa7a4724ccc4090-b794ff24504ad20f | show processlist | 127.0.0.1|
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+------------+
1 row in set (1.75 sec)

set show_all_fe_connection = false;
mysql [(none)]>show processlist;
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+
| CurrentConnected | Id   | User | Host             | LoginTime           | Catalog  | Db   | Command | Time | State | QueryId                           | Info             |
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+
| Yes              |    0 | root | 127.0.0.1:52494 | 2024-02-07 12:08:01 | internal |      | Query   |    0 | OK    | a84ce3be2c464042-80cfced4936bb8b2 | show processlist |
+------------------+------+------+------------------+---------------------+----------+------+---------+------+-------+-----------------------------------+------------------+
1 row in set (0.00 sec)

```

after the pr

```
mysql> show processlist;
+------------------+------+------+-----------------+---------------------+----------+------+---------+------+-------+-----------------------------------+-----------------------+-----------+--------------+
| CurrentConnected | Id   | User | Host            | LoginTime           | Catalog  | Db   | Command | Time | State | QueryId                           | Info                  | FE        | CloudCluster |
+------------------+------+------+-----------------+---------------------+----------+------+---------+------+-------+-----------------------------------+-----------------------+-----------+--------------+
|                  |    0 | root | 127.0.0.1:49720 | 2024-04-22 16:34:03 | internal |      | Sleep   | 2556 | EOF   | ec83ebb2835b45d3-9d0c654a6631f26e | show full processlist | 127.0.0.1 | NULL         |
| Yes              |   16 | root | 127.0.0.1:45900 | 2024-04-22 17:18:01 | internal |      | Query   |    0 | OK    | f8bdf77109894fea-9a879f5665020624 | show processlist      | 127.0.0.1 | NULL         |
+------------------+------+------+-----------------+---------------------+----------+------+---------+------+-------+-----------------------------------+-----------------------+-----------+--------------+
2 rows in set (0.00 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
