### PR TITLE
fix lineDelimiter Multi-separator wiriter failed

### PR DESCRIPTION
**Pull request by JackFzy**
## Proposed changes

Close related #7513  (replace it with issue number if it exists).

Describe the overview of changes, and introduce why we need it.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by JackFzy** [comment]
Thanks

**Review by morningman — CHANGES_REQUESTED** [review]
Hi @JackFzy Thanks for your contribution. But the code quality need to be improved.
We will subsequently refactor this piece of code

**Comment by JackFzy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thanks ， I will try to improve the code quality
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 12/31/2021 17:09，Mingyu ***@***.***> wrote： 



@morningman requested changes on this pull request.

Hi @JackFzy Thanks for your contribution. But the code quality need to be improved.
We will subsequently refactor this piece of code

**Comment by morningman** [comment]
Hi @JackFzy #7568 do the refactor of DataX writer, and use json to avoid line delimiter problem.
So I think this PR can be closed.
Thanks for you contribution again.

**Pull request closed without merging**
