### PR TITLE
[Improve](dynamic schema) support filtering invalid data

### PR DESCRIPTION
**Pull request by eldenmoon**
- Support dynamic schema to filter illegal data.
- Expand the regular expression for ColumnName to support more column names.
- Be compatible with PropertyAnalyzer and support legacy tables.
- Default disable parse multi dimenssion array, since some bug unresolved

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
