### PR TITLE
[Feat](Job)After a job is paused, it can be manually triggered to execute.

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
- After a job is paused, it can be manually triggered to execute.
- Update the return fields of the Insert task query to include a new start time field.

### CODE REVIEW

**Review by zddr — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run  cloud_p1

**Comment by CalvinKirs** [comment]
run performance

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
