### PR TITLE
[Feature]Support external table sample stats collection.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Support hive table sample stats collection. Gramma is like

`analyze table with sample percent 10`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Kikyou1997 — APPROVED** [review]

**Pull request merged**
