### PR TITLE
[fix](analyze) correct duplicated counting of updated rows for mv in cloud mode

### PR DESCRIPTION
**Pull request by freemandealer**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run feut

**Comment by freemandealer** [comment]
run feut

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
