### PR TITLE
[bugfix](topn) fix key topn merge block conflict with index predicate result columns

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

Issue Number: close #xxx

If some the blocks output by rowset reader have different columns, due to w/o optimization of inverted index, key topn will crash when it try to call MutableBlock::add_rows on block with different columns. 

This PR remove the different __TEMP__ columns, generated by optimization of inverted index, after filter_block. And filter_block will not be called in scanner.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Review by Tanya-W — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
