### PR TITLE
[fix] Fix potential unhandled exception cause data inconsistency

### LINKED ISSUE #11018: [Bug] Unhandled exception may cause data inconsistency
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.14

### What's Wrong?

During a broker load job, after the txn is COMMITTED, there was something going wrong in BrokerLoadJob.writeProfile() and it threw an exception. And the thrown exception causing the broker load job's txn is COMMITTED in the coordinator FE, but VISIBLE in other FE. 
The problem is caused by in DatabaseTransactionMgr.finishTransaction(): transactionState.afterStateTransform() threw an exception on coordinator FE. Before that happened, DatabaseTransactionMgr.unprotectUpsertTransactionState() add VISIBLE state log to editLog making other FE mark the txn VISIBLE. However, after the exception happened, the coordinator FE's txn state still remains COMMITTED.

### What You Expected?

the broker load job txn should be either VISIBLE or otherwise at the same time in all FE.

### How to Reproduce?

throw an exception in BrokerLoadJob.writeProfile()。

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TsukiokaKogane**
# Proposed changes

Issue Number: close #11018

## Problem Summary:

catch unhandled exception to prevent potential data inconsistency behavior.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
@morningman-cmy

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
@TsukiokaKogane please rebase to pass the check

**Comment by TsukiokaKogane** [comment]
> @TsukiokaKogane please rebase to pass the check

done

**Review by morningman — APPROVED** [review]

**Pull request merged**
