### PR TITLE
[fix](load) avoid using protobuf set_allocated_id in VDataStreamSender

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

`id` is very lightweight, we should just copy it instead of using `set_allocated_id`.

Fix the following compile error:

```
In file included from /home/runner/work/doris/doris/be/src/pipeline/exec/multi_cast_data_streamer.h:20:
/home/runner/work/doris/doris/be/src/vec/sink/vdata_stream_sender.h:268:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
        _brpc_request.release_finst_id();
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/doris/doris/be/src/vec/sink/vdata_stream_sender.h:269:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
        _brpc_request.release_query_id();
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.73 seconds
 stream load tsv:          543 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17161947184 Bytes

**Comment by kaijchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.15 seconds
 stream load tsv:          544 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162069940 Bytes

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
