### PR TITLE
[fix](fe) Inconsistent behavior for string comparison in FE and BE

### LINKED ISSUE #13573: [Bug] Inconsistent behavior for string comparison in FE and BE
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

In FE, when constant folding rule is applied, '汇总' is always less than '2022-01-01'.
image

But when I send a sorting sql which runs a sorting in BE, the result is contrary.
image

### What You Expected?

FE should keep the same logic as BE.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
Signed-off-by: nextdreamblue <zxw520blue1@163.com>

# Proposed changes

Issue Number: close #13573

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Please add test case.

**Comment by nextdreamblue** [comment]
> Please add test case.

done

**Comment by nextdreamblue** [comment]
@morningman please review, thanks

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
