### PR TITLE
[Enhancement]use awaitility.await() replace thread.sleep() #37817

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #xxx
#37817
replace thread.sleep with awaitility util in some of compaction testcases.

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by Vallishp** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Vallishp** [comment]
run buildall

**Pull request merged**
