### PR TITLE
[fix](cloud) Fix cloud auto start and add a regression case

### PR DESCRIPTION
**Pull request by deardeng**
1. Fix the cluster being suspended and select not waking up the cluster. The reason is that all be nodes in the cluster are inactive, the cluster is skipped, and the cluster that needs to be woken up cannot be found, and the wake-up logic will not be reached. And delete the redundant function getAuthorizedCloudCluster
2. Add check after resume cluster, there must be at least one alive be in the cluster.
3. add auto start regression case

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by gavinchou — COMMENTED** [review]
This PR, describe below, what is the bug and how was it fixed, and then the removed segment of code, as well as changing the return type from void to string, does it involve a behavior change?

**Review by gavinchou — DISMISSED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by deardeng** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
