### PR TITLE
[fix](restore) Ignore base tablet if it is migrated

### PR DESCRIPTION
**Pull request by w41ter**
In atomic restore, if the base tablet exists, the base tablet is directly linked to the rowset files. Sometimes the base tablet is migrated to other disks and direct linking fails. In this case, the base tablet data is ignored and downloaded directly from the upstream.

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
