### PR TITLE
[enhance](mtmv)change mysql table type of mtmv to table

### PR DESCRIPTION
**Pull request by zddr**
mv1 is MTMV
```
mysql> SHOW FULL TABLES WHERE Table_type =  'BASE TABLE';
+--------------+------------+
| Tables_in_zd | Table_type |
+--------------+------------+
| mv1          | BASE TABLE |
| com3         | BASE TABLE |
+--------------+------------+
```

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run feut

**Comment by zddr** [comment]
run cloud_p1

**Review by morrySnow — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
