### PR TITLE
[Bug](lateral-view) make lateral view function's nullable mode work

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1.
```sql
select e1 from (select 1 k1) as t lateral view explode_numbers(5) tmp1 as e1;
```
Here e1 is nullable now and needs to be set to not nullable according to depend on argument.

2. remove some unused code about NullIndicator.
3. fix insert wrong data due to serialize_without_key_to_column not append data to column
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by shuke987 — APPROVED** [review]

**Comment by shuke987** [comment]
LGTM

**Pull request merged**
