### PR TITLE
[test](shuffle) test insert row count when rows filtered by ExchangeNode

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

This PR adds a regression test for #34605.

Before #34605, the `rows affected` returned is not correct when ExchangeNode has filtered some rows. 

```
2024-05-10 16:45:06.763 INFO [suite-thread-1] (Suite.groovy:340) - Execute sql:  SET enable_strict_consistency_dml = true; 
2024-05-10 16:45:06.765 INFO [suite-thread-1] (Suite.groovy:995) - Execute tag: insert2, sql: 
        INSERT INTO regression_test_insert_p0.test_insert_row_count_dst SELECT `id`, `type`, `score` FROM regression_test_insert_p0.test_insert_row_count_src;
    
2024-05-10 16:45:15.990 WARN [suite-thread-1] (Suite.groovy:988) - expect results in file: insert_p0/test_insert_row_count.out, line: 6
realResults:
2
2024-05-10 16:45:15.995 ERROR [suite-thread-1] (ScriptContext.groovy:122) - Run test_insert_row_count in /mnt/disk1/chenkaijie/doris/regression-test/suites/insert_p0/test_insert_row_count.groovy failed
java.lang.IllegalStateException: Check tag 'insert2' failed:
Check tag 'insert2' failed, line 1 mismatch.
Expect line is: 4
But real is   : 2
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
