### PR TITLE
[fix](schemachange) Fixed the issue of incorrect log information when distribution columns are compared inconsistently

### PR DESCRIPTION
**Pull request by gnehil**
## Proposed changes

Issue Number: close #xxx

When the new distribution column is inconsistent with the default distribution column, the new distribution column is output twice in the log information, but the default distribution column is not output.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]
LGTM

**Comment by JNSimba** [comment]
run p0

**Comment by gnehil** [comment]
run buildall

**Comment by gnehil** [comment]
run buildall

**Comment by gnehil** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
