### PR TITLE
[tests](inverted index)Add and improve add/drop index cases

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

1. Adding a debug point for FE light schema change
2. Reorganising the case directory structure
3. Add some cases: 
    - test_build_index_with_direct_schema_change_fault_injection,
    - test_build_index_with_light_schema_change_fault_injection
    - test_add_drop_index_repeatly
    - test_index_change_on_renamed_column
    - test_index_change_with_full_compaction
5. Improve some cases: 
    - test_index_change_on_new_column
    - test_index_change_on_new_column

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by airborne12 — COMMENTED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
