### PR TITLE
[feature](cast) remove some unused in functioncast  and support some function in nereids

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

1 ConvertImplGenericFromString do not need a template StringColumnType
2 remove timev1 in function cast 
3 support time_to_sec , sec_to_time in nereids

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.69 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17161959351 Bytes

**Comment by Mryange** [comment]
run feut

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
2.0上也有这个问题，需要合入

**Pull request merged**
