### PR TITLE
Fix Windows function lag()/lead() function throw AnalysisException.

### PR DESCRIPTION
**Pull request by HappenLee**
Decimal should have high match priority than varcher.

issue: #4665

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kangkaisen** [comment]
I think a more simple way to fix this issue is:

```
     @Override
     protected Expr uncheckedCastTo(Type targetType) throws AnalysisException {
-        if (targetType.isFloatingPointType()) {
+        if (targetType.isDecimal() || targetType.isDecimalV2()) {
+            return this;
+        } else if (targetType.isFloatingPointType()) {

@@ -769,7 +749,9 @@ public class FunctionSet {
         final Type[] candicateArgTypes = candicate.getArgs();
         if (functionName.equalsIgnoreCase("hex")
                 || functionName.equalsIgnoreCase("greast")
-                || functionName.equalsIgnoreCase("least")) {
+                || functionName.equalsIgnoreCase("least")
+                || functionName.equalsIgnoreCase("lead")
+                || functionName.equalsIgnoreCase("lag")) {
```
My fixed way has been passed a lot of tests.

**Comment by kangkaisen** [comment]
Besides，you should add a UT for this bug.

**Comment by HappenLee** [comment]
> I think a more simple way to fix this issue is:
> 
> ```
>      @Override
>      protected Expr uncheckedCastTo(Type targetType) throws AnalysisException {
> -        if (targetType.isFloatingPointType()) {
> +        if (targetType.isDecimal() || targetType.isDecimalV2()) {
> +            return this;
> +        } else if (targetType.isFloatingPointType()) {
> 
> @@ -769,7 +749,9 @@ public class FunctionSet {
>          final Type[] candicateArgTypes = candicate.getArgs();
>          if (functionName.equalsIgnoreCase("hex")
>                  || functionName.equalsIgnoreCase("greast")
> -                || functionName.equalsIgnoreCase("least")) {
> +                || functionName.equalsIgnoreCase("least")
> +                || functionName.equalsIgnoreCase("lead")
> +                || functionName.equalsIgnoreCase("lag")) {
> ```
> 
> My fixed way has been passed a lot of tests.

Thanks，I will check again the repair way again.

**Review by kangkaisen — APPROVED** [review]
+1

**Pull request merged**
