### PR TITLE
[fix](memory) Fix ExecEnv destroy memory tracking

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

1. disable memory tracking when ExecEnv destroy.
2. fix memory tracker label convert to query id

fix:
```
20:52:43    2# raise at ../sysdeps/unix/sysv/linux/raise.c:51
20:52:43    3# abort at /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81
20:52:43    4# 0x000055DFC6DA2ABD in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43    5# 0x000055DFC6D9515A in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43    6# google::LogMessage::SendToLog() in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43    7# google::LogMessage::Flush() in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43    8# google::LogMessageFatal::~LogMessageFatal() in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43    9# doris::ThreadContext::consume_memory(long) const in /mnt/hdd01/ci/doris_cloud/master/NEREIDS_ASAN/cluster0/be/lib/doris_be
20:52:43   10# Allocator<false, false, false>::release_memory(unsigned long) const at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/allocator.cpp:177
20:52:43   11# Allocator<false, false, false>::free(void*, unsigned long) at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/allocator.h:154
20:52:43   12# doris::vectorized::PODArrayBase<1ul, 4096ul, Allocator<false, false, false>, 15ul, 16ul>::dealloc() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/pod_array.h:156
20:52:43   13# doris::vectorized::PODArrayBase<1ul, 4096ul, Allocator<false, false, false>, 15ul, 16ul>::~PODArrayBase() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/pod_array.h:272
20:52:43   14# doris::vectorized::PODArray<unsigned char, 4096ul, Allocator<false, false, false>, 15ul, 16ul>::~PODArray() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/pod_array_fwd.h:37
20:52:43   15# doris::vectorized::ColumnVector<unsigned char>::~ColumnVector() at /home/zcp/repo_center/doris_master/doris/be/src/vec/columns/column_vector.h:131
20:52:43   16# doris::vectorized::ColumnVector<unsigned char>::~ColumnVector() at /home/zcp/repo_center/doris_master/doris/be/src/vec/columns/column_vector.h:131
20:52:43   17# COW<doris::vectorized::IColumn>::release_ref() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:100
20:52:43   18# COW<doris::vectorized::IColumn>::intrusive_ptr<doris::vectorized::IColumn const>::~intrusive_ptr() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:135
20:52:43   19# COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn>::~immutable_ptr() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:245
20:52:43   20# COW<doris::vectorized::IColumn>::chameleon_ptr<doris::vectorized::IColumn>::~chameleon_ptr() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:321
20:52:43   21# doris::vectorized::ColumnNullable::~ColumnNullable() at /home/zcp/repo_center/doris_master/doris/be/src/vec/columns/column_nullable.h:62
20:52:43   22# doris::vectorized::ColumnNullable::~ColumnNullable() at /home/zcp/repo_center/doris_master/doris/be/src/vec/columns/column_nullable.h:62
20:52:43   23# COW<doris::vectorized::IColumn>::release_ref() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:100
20:52:43   24# COW<doris::vectorized::IColumn>::intrusive_ptr<doris::vectorized::IColumn const>::~intrusive_ptr() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:135
20:52:43   25# COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn>::~immutable_ptr() at /home/zcp/repo_center/doris_master/doris/be/src/vec/common/cow.h:245
20:52:43   26# doris::vectorized::ColumnWithTypeAndName::~ColumnWithTypeAndName() at /home/zcp/repo_center/doris_master/doris/be/src/vec/core/column_with_type_and_name.h:46
20:52:43   27# void std::destroy_at<doris::vectorized::ColumnWithTypeAndName>(doris::vectorized::ColumnWithTypeAndName*) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:89
20:52:43   28# void std::_Destroy<doris::vectorized::ColumnWithTypeAndName>(doris::vectorized::ColumnWithTypeAndName*) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:142
20:52:43   29# void std::_Destroy_aux<false>::__destroy<doris::vectorized::ColumnWithTypeAndName*>(doris::vectorized::ColumnWithTypeAndName*, doris::vectorized::ColumnWithTypeAndName*) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:151
20:52:43   30# void std::_Destroy<doris::vectorized::ColumnWithTypeAndName*>(doris::vectorized::ColumnWithTypeAndName*, doris::vectorized::ColumnWithTypeAndName*) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:186
20:52:43   31# void std::_Destroy<doris::vectorized::ColumnWithTypeAndName*, doris::vectorized::ColumnWithTypeAndName>(doris::vectorized::ColumnWithTypeAndName*, doris::vectorized::ColumnWithTypeAndName*, std::allocator<doris::vectorized::ColumnWithTypeAndName>&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:747
20:52:43   32# std::vector<doris::vectorized::ColumnWithTypeAndName, std::allocator<doris::vectorized::ColumnWithTypeAndName> >::~vector() at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:680
20:52:43   33# doris::vectorized::Block::~Block() at /home/zcp/repo_center/doris_master/doris/be/src/vec/core/block.h:92
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
