### PR TITLE
[fix](Config): Remove unused config max_connection_scheduler_threads_num

### PR DESCRIPTION
**Pull request by xutaoustc**
[fix](Config): Remove unused config max_connection_scheduler_threads_num

### CODE REVIEW

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
