### PR TITLE
[feat](nereids) Add name of catalog/db/table to column stats tbl

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

After this PR, schema of `coumn_statistics` and `histogram_statistics` would like

```
mysql> desc column_statistics;
+--------------------+----------------+------+-------+---------+---------+
| Field              | Type           | Null | Key   | Default | Extra   |
+--------------------+----------------+------+-------+---------+---------+
| id                 | VARCHAR(4096)  | No   | true  | NULL    |         |
| catalog_id         | VARCHAR(64)    | No   | true  | NULL    |         |
| db_id              | VARCHAR(64)    | No   | true  | NULL    |         |
| tbl_id             | VARCHAR(64)    | No   | true  | NULL    |         |
| idx_id             | VARCHAR(64)    | No   | true  | NULL    |         |
| col_id             | VARCHAR(64)    | No   | true  | NULL    |         |
| part_id            | VARCHAR(64)    | Yes  | true  | NULL    |         |
| count              | BIGINT         | Yes  | false | NULL    | REPLACE |
| ndv                | BIGINT         | Yes  | false | NULL    | REPLACE |
| null_count         | BIGINT         | Yes  | false | NULL    | REPLACE |
| min                | VARCHAR(65533) | Yes  | false | NULL    | REPLACE |
| max                | VARCHAR(65533) | Yes  | false | NULL    | REPLACE |
| data_size_in_bytes | BIGINT         | Yes  | false | NULL    | REPLACE |
| update_time        | DATETIME       | No   | false | NULL    | REPLACE |
| catalog_name       | VARCHAR(256)   | Yes  | false | NULL    | REPLACE |
| db_name            | VARCHAR(256)   | Yes  | false | NULL    | REPLACE |
| tbl_name           | VARCHAR(65533) | Yes  | false | NULL    | REPLACE |
+--------------------+----------------+------+-------+---------+---------+
17 rows in set (0.03 sec)

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.27 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          35.2 seconds inserted 10000000 Rows, about 284K ops/s
 storage size: 17162228832 Bytes

**Comment by Kikyou1997** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.5 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162204718 Bytes

**Comment by Kikyou1997** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.31 seconds
 stream load tsv:          534 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          30.2 seconds inserted 10000000 Rows, about 331K ops/s
 storage size: 17161968386 Bytes

**Pull request closed without merging**
