### PR TITLE
[improve](group commit) set internal group commit timeout

### PR DESCRIPTION
**Pull request by mymeiyi**
The internal group commit timeout now use the default value of load, which is 14400 second, 4 hour.
It should not use it, because the group commit interval is generally a small value.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run external

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
