### PR TITLE
[Feature](multi-catalog) support query hive views.

### PR DESCRIPTION
**Pull request by dutyu**
# Proposed changes

## Problem summary

A very simple implementation to query hive views, **it is an EXPERIMENTAL feature**.  We can try to parse the ddl of hive views and try to execute the query relies on the fact that  HiveQL is very similar to Doris SQL. But if the ddl of hive views use some complicated or incompatible grammar, the query might fail.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
> But if the ddl of hive views use some complicated or incompatible grammar, the query might fail.
Could you list the specific area of influence?

**Comment by dutyu** [comment]
> > But if the ddl of hive views use some complicated or incompatible grammar, the query might fail.
> 
> Could you list the specific area of influence?
Sorry i can not enumerate all fail scenes but i can give an example, if the hive view's definition like this 
```CREATE VIEW `test.tbl_test_v` AS select sha(`lh_test`.`number`), `lh_test`.`k1`, `lh_test`.`k2`, `lh_test`.`k3`, `lh_test`.`k4` from `test`.`lh_test`
```, when we create a hive catalog named `hive_ctl` and submit a query like this ```select * from hive_ctl.test.tbl_test_v```,  this query will fail and you can see some message like this: ```
MySQL [test_d]> select * from hive_ctl.test.tbl_test_v;
ERROR 1105 (HY000): errCode = 2, detailMessage = No matching function with signature: sha(decimal(18, 7)).
```.
Above all, a query with hive view will be failed including but not limited to these scenes, **but other queries are not affected.** :
- ddl of hive view use some functions that doris dose not contain
- ddl of hive view use some grammer that doris does not support

**Review by morningman — COMMENTED** [review]
Please add some test case.
You can refer to `https://doris.apache.org/zh-CN/community/developer-guide/regression-testing#%E5%A4%96%E9%83%A8%E6%95%B0%E6%8D%AE%E6%BA%90-e2e-%E6%B5%8B%E8%AF%95`

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by dutyu** [comment]
> Please add some test case. You can refer to `https://doris.apache.org/zh-CN/community/developer-guide/regression-testing#%E5%A4%96%E9%83%A8%E6%95%B0%E6%8D%AE%E6%BA%90-e2e-%E6%B5%8B%E8%AF%95`

Sorry, i meet some problems when executing the regression test in my local env, i will submit a pr to add some regression test later if the problem be solved.

**Pull request merged**
