### PR TITLE
[typo](docs) change the URI to lowercase

### PR DESCRIPTION
**Pull request by vinlee19**
## Proposed changes

Issue Number: close #xxx

We found the following error when using Table Value Function in 2.0-alpha:

image

image

When we change the URI to uri：
image

Thus,we change the URI to ower case.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — DISMISSED** [review]

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by vinlee19** [comment]
run buildall

**Pull request closed without merging**
