### PR TITLE
[fix](rest catalog)support set region for s3

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Use REST Catalog to access S3 and support setting up regions：
```
CREATE CATALOG iceberg_rest_s3 PROPERTIES (
    "type"="iceberg",
    "iceberg.catalog.type"="rest",
    "uri" = "http://127.0.0.1:8181",
    "s3.endpoint" = "http://127.0.0.1:8010",
    "s3.access_key" = "admin",
    "s3.secret_key" = "password",
    "s3.region" = "us-east-1"
);
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by wsjz — APPROVED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
