### PR TITLE
[Fix](functions) Fix bug in makedate and str_to_date functions

### LINKED ISSUE #34582: [Bug] The results of makedate and str_to_date functions do not meet expectations
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.9&master

### What's Wrong?

select str_to_date('11.09.2011 11:09:30', '%m.%d.%Y %h:%i:%s');
# 期望值: 2011-11-09 11:09:30
# 实际值: 2011-11-09 00:09:30

select makedate(2021, 0);
# 期望值: NULL（与mysql保持一致）
# 实际值: datetime.date(2020, 12, 31)

### What You Expected?

函数执行结果与期望值保持一致

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yongjinhou**
## Proposed changes

Issue Number: close #34582

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run build all

**Comment by yongjinhou** [comment]
run buildall

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Review by LompleZ — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
