### PR TITLE
[opt](binlog) Support modify comment binlog

### PR DESCRIPTION
**Pull request by smallx**
## Proposed changes

Support modify comment binlog.

### CODE REVIEW

**Comment by smallx** [comment]
run buildall

**Comment by smallx** [comment]
@w41ter please help to review code, thank you.

**Review by w41ter — DISMISSED** [review]

**Comment by w41ter** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Comment by w41ter** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
