### PR TITLE
[feature](function)add search functions: multi_search_all_positions & multi_match_any

### PR DESCRIPTION
**Pull request by yiliangyl**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Add search functions: `multi_search_all_positions` and `multi_match_any`

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.37 seconds
 load time: 597 seconds
 storage size: 17154821227 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028182119_clickbench_pr_35293.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.38 seconds
 load time: 561 seconds
 storage size: 17154644898 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028130052_clickbench_pr_35413.html

**Comment by xiaokang** [comment]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
