### PR TITLE
[improvement](exception-safe) create and prepare node/sink support exception safe

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Issue Number: close #xxx

motivation is to fix create_data_type exception safety
```
*** Query id: 54ff960ef5cb477c-b4c16aae769a03ce ***
*** Aborted at 1686127430 (unix time) try "date -d @1686127430" if you are using GNU date ***
*** Current BE git commitID: c910e9b78b ***
*** SIGSEGV address not mapped to object (@0x0) received by PID 1889933 (TID 1891124 OR 0x7fb77adc6700) from PID 0; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /doris/core/be/src/common/signal_handler.h:413
 1# 0x00007FB9E08D1400 in /lib64/libc.so.6
 2# doris::vectorized::IDataType::get_name[abi:cxx11]() const at /doris/core/be/src/vec/data_types/data_type.cpp:49
 3# doris::vectorized::VExpr::create_expr(doris::TExprNode const&, std::shared_ptr<doris::vectorized::VExpr>&) at /doris/core/be/src/vec/exprs/vexpr.cpp:143
 4# doris::vectorized::VExpr::create_tree_from_thrift(std::vector<doris::TExprNode, std::allocator<doris::TExprNode> > const&, int*, std::shared_ptr<doris::vectorized::VExpr>&, std::shared_ptr<doris::vectorized::VExprContext>&) at /doris/core/be/src/v
ec/exprs/vexpr.cpp:238
 5# doris::vectorized::VExpr::create_expr_tree(doris::TExpr const&, std::shared_ptr<doris::vectorized::VExprContext>&) at /doris/core/be/src/vec/exprs/vexpr.cpp:281
 6# doris::vectorized::VExpr::create_expr_trees(std::vector<doris::TExpr, std::allocator<doris::TExpr> > const&, std::vector<std::shared_ptr<doris::vectorized::VExprContext>, std::allocator<std::shared_ptr<doris::vectorized::VExprContext> > >&) at /do
ris/core/be/src/vec/exprs/vexpr.cpp:298
 7# doris::vectorized::VResultSink::prepare_exprs(doris::RuntimeState*) at /doris/core/be/src/vec/sink/vresult_sink.cpp:67
 8# doris::vectorized::VResultSink::prepare(doris::RuntimeState*) at /doris/core/be/src/vec/sink/vresult_sink.cpp:87
 9# doris::PlanFragmentExecutor::prepare(doris::TExecPlanFragmentParams const&, doris::QueryContext*) at /doris/core/be/src/runtime/plan_fragment_executor.cpp:217
10# doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&) at /doris/core/be/src/runtime/fragment_mgr.cpp:804
11# doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&) at /doris/core/be/src/runtime/fragment_mgr.cpp:585
12# doris::PInternalServiceImpl::_exec_plan_fragment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, doris::PFragmentRequestVersion, bool) at /doris/core/be/src/service/internal_service.cpp:449
13# doris::PInternalServiceImpl::exec_plan_fragment(google::protobuf::RpcController*, doris::PExecPlanFragmentRequest const*, doris::PExecPlanFragmentResult*, google::protobuf::Closure*) at /doris/core/be/src/service/internal_service.cpp:285
14# brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) in /doris/core/output_run/be/lib/doris_be
15# brpc::ProcessInputMessage(void*) in /doris/core/output_run/be/lib/doris_be
ux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
15# doris::PriorityWorkStealingThreadPool::work_thread(int) at /doris/core/be/src/util/priority_work_stealing_thread_pool.hpp:137
16# execute_native_thread_routine at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
17# start_thread in /lib64/libpthread.so.0
18# __GI___clone in /lib64/libc.so.6
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
