### PR TITLE
[fix](cloud) fix core dump in CloudWarmUpManager::handle_jobs

### PR DESCRIPTION
**Pull request by freemandealer**
use smart pointer to control the lifespan of JobMeta to avoid nullptr

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
