### PR TITLE
[fix](dockerfile) Switch repos to point to to vault.centos.org because CentOS 7 is EOL

### PR DESCRIPTION
**Pull request by morningman**
Fix `Could not resolve host: mirrorlist.centos.org; Unknown error`

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
