### PR TITLE
remove explicit memtracker from scannode

### PR DESCRIPTION
**Pull request by dataroaring**
memory is tracked by implicit tracker via hook.

# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
What is the reason for removing `_buffered_bytes` and `_block_mem_tracker`?

`_block_mem_tracker` also exists elsewhere, reusing the previous memory track logic,
If we don't need to track more fine-grained block memory, I would consider removing both. @dataroaring @morningman

**Comment by dataroaring** [comment]
> `_block_mem_tracker` also exists in other places. I intentionally kept the previous memory track logic and tracked the more detailed block memory. If we don't need track block memory, or it will bring performance or other issues, then I will consider removing both. @dataroaring @morningman

I removed it because its counterpart in olap_scan_node.cpp is removed.

**Comment by xinyiZzz** [comment]
> _block_mem_tracker

So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.

**Comment by dataroaring** [comment]
> > _block_mem_tracker
> 
> So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.

It seems that _block_mem_tracker tracks memory for vectorized block?  If so, we should track them via ExecNode::_mem_tracker， and  it should be tracked via hook, right?  btw, we should track mmap allocated memory.

**Comment by xinyiZzz** [comment]
> > > _block_mem_tracker
> > 
> > 
> > So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.
> 
> It seems that _block_mem_tracker tracks memory for vectorized block? If so, we should track them via ExecNode::_mem_tracker， and it should be tracked via hook, right? btw, we should track mmap allocated memory.

mmap has been tracked and introduced in pr: https://github.com/apache/incubator-doris/pull/9145

`_block_mem_tracker` only tracks memory for vectorized block, `ExecNode::_mem_tracker` includes other memory in ExecNode in addition to memory for vectorized block. This is the purpose of my previous design, so my reply above is whether it is necessary.

**Comment by dataroaring** [comment]
> > > > _block_mem_tracker
> > > 
> > > 
> > > So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.
> > 
> > 
> > It seems that _block_mem_tracker tracks memory for vectorized block? If so, we should track them via ExecNode::_mem_tracker， and it should be tracked via hook, right? btw, we should track mmap allocated memory.
> 
> mmap has been tracked and introduced in pr: #9145
> 
> `_block_mem_tracker` only tracks memory for vectorized block, `ExecNode::_mem_tracker` includes other memory in ExecNode in addition to memory for vectorized block. This is the purpose of my previous design, so my reply above is whether it is necessary.

Yep. I understand what you mean. IMHO, It should be case by case, e.g. for the OlapScanNode, the majority memory should be contributed by blocks, so value of block_mem_tracker is about equal value of ExecNode::_mem_tracker？ But for the AggregateNode, may be the majority memory should be contributed by hash table, so we should track memory usage of hash table.

**Comment by xinyiZzz** [comment]
> > > > > _block_mem_tracker
> > > > 
> > > > 
> > > > So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.
> > > 
> > > 
> > > It seems that _block_mem_tracker tracks memory for vectorized block? If so, we should track them via ExecNode::_mem_tracker， and it should be tracked via hook, right? btw, we should track mmap allocated memory.
> > 
> > 
> > mmap has been tracked and introduced in pr: #9145
> > `_block_mem_tracker` only tracks memory for vectorized block, `ExecNode::_mem_tracker` includes other memory in ExecNode in addition to memory for vectorized block. This is the purpose of my previous design, so my reply above is whether it is necessary.
> 
> Yep. I understand what you mean. IMHO, It should be case by case, e.g. for the OlapScanNode, the majority memory should be contributed by blocks, so value of block_mem_tracker is about equal value of ExecNode::_mem_tracker？ But for the AggregateNode, may be the majority memory should be contributed by hash table, so we should track memory usage of hash table.

I agree with you that the `_block_mem_tracker` of `scan node` is really unnecessary. After the new MemTracker is used for a period of time, the more detailed tracker and the existing virtual tracker can be modified.

A little leak in the code:
volap_scan_node.h:67 - remove `_block_mem_tracker` definition.
volap_scan_node.cpp:323 - remove `_block_mem_tracker` create.

**Comment by dataroaring** [comment]
> > > > > > _block_mem_tracker
> > > > > 
> > > > > 
> > > > > So why remove `counterpart`, `counterpart` is just for `_block_mem_tracker`.
> > > > 
> > > > 
> > > > It seems that _block_mem_tracker tracks memory for vectorized block? If so, we should track them via ExecNode::_mem_tracker， and it should be tracked via hook, right? btw, we should track mmap allocated memory.
> > > 
> > > 
> > > mmap has been tracked and introduced in pr: #9145
> > > `_block_mem_tracker` only tracks memory for vectorized block, `ExecNode::_mem_tracker` includes other memory in ExecNode in addition to memory for vectorized block. This is the purpose of my previous design, so my reply above is whether it is necessary.
> > 
> > 
> > Yep. I understand what you mean. IMHO, It should be case by case, e.g. for the OlapScanNode, the majority memory should be contributed by blocks, so value of block_mem_tracker is about equal value of ExecNode::_mem_tracker？ But for the AggregateNode, may be the majority memory should be contributed by hash table, so we should track memory usage of hash table.
> 
> I agree with you that the `_block_mem_tracker` of `scan node` is really unnecessary. After the new MemTracker is used for a period of time, the more detailed tracker and the existing virtual tracker are expected to be modified.
> 
> A little leak in the code: volap_scan_node.h:67 - remove `_block_mem_tracker` definition. volap_scan_node.cpp:323 - remove `_block_mem_tracker` create.

done

**Comment by xinyiZzz** [comment]
LGTM

**Pull request closed without merging**
