### PR TITLE
[feature](doris compose) Support generate code coverage data

### PR DESCRIPTION
**Pull request by yujun777**
Need two steps: 
1.  Build  using `sh build.sh --fe --be --coverage`;
2. Create cluster,  use --coverage-dir to spec the output directory.  Default not generate them.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
