### PR TITLE
[opt](plugin) improve filebeat doris output plugin

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

1. read doris stream load response and retry
2. add a config to log doris stream load request header and response
3. add a config to log progress for better observability

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
