### PR TITLE
[fix](load) fix unified load redirect status delegate error

### PR DESCRIPTION
**Pull request by lvshaokang**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by lvshaokang** [comment]
run buildall

**Review by Hastyshell — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
maybe better to show the fix result?

**Comment by lvshaokang** [comment]
> maybe better to show the fix result?

good sug, done

**Comment by lvshaokang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
