### PR TITLE
[fix](regression-test) fix test_hive_serde_prop

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
fellow https://github.com/apache/doris/pull/42200

Null values ​​in text tables are now correctly recognized now.

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
be same with hive result：
```text
hive> select * from test_open_csv_default_prop;
OK
1       John Doe        28      50000.75        TRUE    2022-01-15      2023-10-21 14:30:00     4.5     Senior Developer
2       Jane,Smith                              2020-05-20                      "Project Manager"
Time taken: 0.053 seconds, Fetched: 2 row(s)
hive> select * from serde_test7;
OK
1       NULL
2       |||
3       aaa
4       "null"
Time taken: 0.05 seconds, Fetched: 4 row(s)
```

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
