### PR TITLE
[fix](build index) Fix inverted index hardlink leak and missing problem

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

Issue Number: close #xxx

1. delete partial success hard link on exception
2. skip hard link to not exist index file

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
