### PR TITLE
[fix](partial update) only unique table with MOW insert with target columns can consider be a partial update

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #28321

when enable_unique_key_partial_update = true,
only unique table with MOW insert with target columns can consider be a partial update,
and unique table with MOW insert without target columns will be like a normal insert,
and unique table without MOW, insert will be like a normal insert.

when enable_unique_key_partial_update = false,
unique table with MOW, insert will be a normal insert, and column that not set will insert default value.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by zhannngchen** [comment]
@nextdreamblue  We do have plans to support partial column updates on Unique Key MoR, specifically, using replace_if_not_null as an agg function, but it requires additional handling of sequence columns and delete sign columns compared to Aggregate Key. Would you be interested in supporting this function?

**Comment by nextdreamblue** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
