### PR TITLE
[Bug] Grouping set clause act wrong for fucntion expr in view (#7410)

### LINKED ISSUE #7410: [Bug] Grouping set clause act wrong for fucntion expr in view
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0499b2211b7ad685a6aae17508b3120b3490bcec

### What's Wrong?

When we create a materialization view with function like `concat`, and use `WITH ROLLUP` clause, we can get wrong answer that not identical to ROLLUP defination.
```
CREATE TABLE `table1` (
  `siteid` int(11) NULL DEFAULT "10" COMMENT "",
  `citycode` int(11) NULL COMMENT "",
  `username` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`siteid`, `citycode`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`siteid`) BUCKETS 1
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "V2"
);

create view view_test1 as select siteid, citycode, concat(username, pv) as concat from 

select siteid, citycode, concat from view_test1 group by rollup(siteid, citycode, concat);
```

### What You Expected?

It should return multi-level result like below.
image

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MorningLight5**
## Proposed changes

Fix #7410 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please add ut for this case

**Comment by morningman** [comment]
You can write `Fix #7410` in your PR comment. So the the issue 7410 will be closed automatically when the PR is merged.

**Comment by tianhui5** [comment]
> Please add ut for this case

Done, is there any other problems?

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
