### PR TITLE
[Bug](fold-constant) fix result error with fold constant on BE

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
```
CREATE TABLE IF NOT EXISTS str_tb (k1 VARCHAR(10) NULL, v1 STRING NULL) 
UNIQUE KEY(k1) DISTRIBUTED BY HASH(k1) BUCKETS 5 properties("replication_num" = "1")
        
mysql [test_query_qa]>set enable_fold_constant_by_be = true;
Query OK, 0 rows affected (0.00 sec)

mysql [test_query_qa]>INSERT INTO str_tb VALUES (2, repeat("test1111", 10000));
Query OK, 1 row affected (0.26 sec)
{'label':'label_687238ef637b4929_9675dd5b4f31d5bf', 'status':'VISIBLE', 'txnId':'16017'}

mysql [test_query_qa]>select length(v1) from str_tb;
+------------+
| length(v1) |
+------------+
|      65533 | // the repeat("test1111", 10000) length should be 80000, but varchar have max length 65533
+------------+
1 row in set (0.07 sec)
```

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Comment by yiguolei** [comment]
run feut

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
