### PR TITLE
[feature](binlog) Add AddPartitionRecord && DropPartition

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add AddPartitionRecord && DropPartition

### CODE REVIEW

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
