### PR TITLE
[revert](function) fix AES/SM3/SM4 encrypt/ decrypt algorithm initialization vector bug

### PR DESCRIPTION
**Pull request by xinyiZzz**
This reverts commit 397cc011c4f1ba5a25c770258c13f1cd3f28b47d.

# Proposed changes

Issue Number: close #xxx

## Problem summary

revert #17420
There are compatibility issues, I will resubmit the pr later

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.41 seconds
 stream load tsv:          477 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          74 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230318013017_clickbench_pr_116265.html

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run p0

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
