### PR TITLE
[optimize](string) optimize char_length function by SIMD

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes

Optimize char_length function by SIMD
(1) optimize utf8_len compute
(2) 840% up

after: 0.54s
image

before: 5.1s
image

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.83 seconds
 stream load tsv:          425 seconds loaded 74807831229 Bytes, about 167 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230422033513_clickbench_pr_132743.html

**Comment by ZhangYu0123** [comment]
run p0

**Comment by ZhangYu0123** [comment]
run p0

**Comment by yiguolei** [comment]
Could also speed up other string related method like strlen ?

**Comment by ZhangYu0123** [comment]
> Could also speed up other string related method like strlen ?

strlen function has three implements length、bit_length、char_length. 
The difference is that char_length computes char length by finding utf8-length-table. eg: '中国' the length is 2 not 6. This pr use simd to optimize the process of finding utf8-length-table.
Related methods like InStr, locate_pos is also optimized and bit_length、char_length are not optimized.

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run p1

**Comment by zclllyybb** [comment]
LGTM

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p0

**Comment by ZhangYu0123** [comment]
run p1

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p1

**Review by zclllyybb — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
