### PR TITLE
[enhancment](quantile_union): support quantile_union on nullable columns

### PR DESCRIPTION
**Pull request by spaces-X**
# Proposed changes
In the last pr #15868, the quantile_union function can not handle nullable columns.
In this pr
- make it to handle nullable columns correctly 
- change the related table schema to nullable in regression tests

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by spaces-X** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.78 seconds
 stream load tsv:          463 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         40 seconds loaded 2358488459 Bytes, about 56 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230314150032_clickbench_pr_114263.html

**Comment by spaces-X** [comment]
run p0

**Comment by spaces-X** [comment]
run buildall

**Comment by spaces-X** [comment]
run p0

**Comment by spaces-X** [comment]
run buildall

**Pull request closed without merging**
