### PR TITLE
Revert "[Test](multi-catalog) Add tpcds sf100 hive shapes."

### PR DESCRIPTION
**Pull request by zy-kkk**
Reverts apache/doris#25639

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run external

**Pull request merged**
