### PR TITLE
[test](cloud_p0) prepare java udf for some cases

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by hello-stephen** [comment]
run compile

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run cloud_p0

**Comment by hello-stephen** [comment]
run compile

**Comment by hello-stephen** [comment]
run cloud_p0

**Comment by hello-stephen** [comment]
run cloud_p0

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
