### PR TITLE
[typo](docs) Fix some ambiguous descriptions

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yagagagaga** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Review by mklzl — COMMENTED** [review]
lgbt

**Review by mklzl — APPROVED** [review]

**Review by mklzl — APPROVED** [review]

**Comment by yagagagaga** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
