### PR TITLE
[improvement](jdbc mysql) support auto calculate the precision of timestamp/datetime

### LINKED ISSUE #20791: MySQL

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #20791

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
