### PR TITLE
[typo](doc) illustrate storage policy is not supported on merge-on-write table

### PR DESCRIPTION
**Pull request by gnehil**
## Proposed changes

illustrate storage policy is not supported on merge-on-write table

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
