### PR TITLE
[Bug](pipeline) add DCHECK for _instance_to_sending_by_pipeline = false on _send_rpc

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
```cpp
Core was generated by `/mnt/ssd01/doris-master/VEC_UBSAN/be/lib/doris_be'.

Program terminated with signal SIGSEGV, Segmentation fault.

#0  0x0000556fc48ebbb1 in std::__atomic_base<bool>::load (this=0x7d8, __m=std::memory_order::seq_cst)

    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:481

481 return __atomic_load_n(&_M_i, int(__m));

[Current thread is 1 (Thread 0x7f6255064700 (LWP 1216124))]

(gdb) bt

#0  0x0000556fc48ebbb1 in std::__atomic_base<bool>::load (this=0x7d8, __m=std::memory_order::seq_cst)

    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/atomic_base.h:481

#1  std::atomic<bool>::load (this=0x7d8, __m=std::memory_order::seq_cst)

    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/atomic:112

#2  0x0000556fc7e9d486 in doris::RuntimeState::is_cancelled (this=0x0)

    at /home/zcp/repo_center/doris_master/doris/be/src/runtime/runtime_state.h:158

#3  0x0000556fefca3e26 in doris::pipeline::PipelineFragmentContext::cancel (this=0x7f6007042410, 

    reason=@0x7f796ebfea24: doris::INTERNAL_ERROR, 

    msg="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0.0.0:0, client: 172.21.0.38, latency = 300000110")

    at /home/zcp/repo_center/doris_master/doris/be/src/pipeline/pipeline_fragment_context.cpp:149

#4  0x0000556fefc9ae65 in doris::pipeline::ExchangeSinkBuffer::_failed (this=0x7f6006f67c00, id=-4840408317930866523, 

    err="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0.0.0:0, client: 172.21.0.38, latency = 300000110")

    at /home/zcp/repo_center/doris_master/doris/be/src/pipeline/exec/exchange_sink_buffer.cpp:283

#5  0x0000556fefc560df in doris::pipeline::ExchangeSinkBuffer::_send_rpc(long)::$_0::operator()(long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x7f7b519e28c0, 

    id=@0x7f7b519e2900: -4840408317930866523, 

    err="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0.0.0:0, client: 172.21.0.38, latency = 300000110")

    at /home/zcp/repo_center/doris_master/doris/be/src/pipeline/exec/exchange_sink_buffer.cpp:182

#6  0x0000556fefc56039 in std::__invoke_impl<void, doris::pipeline::ExchangeSinkBuffer::_send_rpc(long)::$_0&, long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__invoke_other, doris::pipeline::ExchangeSinkBuffer::_send_rpc(long)::$_0&, long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__f=..., 

    __args="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0.0.0:0, client: 172.21.0.38, latency = 300000110", 

    __args="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0.0.0:0, client: 172.21.0.38, latency = 300000110")

    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61

#7  0x0000556fefc55ed9 in std::__invoke_r<void, doris::pipeline::ExchangeSinkBuffer::_send_rpc(long)::$_0&, long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(doris::pipeline::ExchangeSinkBuffer::_send_rpc(long)::$_0&, long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__fn=..., 

    __args="failed to send brpc when exchange, error=RPC call is timed out, error_text=[E1008]Reached timeout=300000ms @0.0
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 42.02 seconds
 stream load tsv:          462 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          66.4 seconds inserted 10000000 Rows, about 150K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230626053943_clickbench_pr_167684.html

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 42.03 seconds
 stream load tsv:          455 seconds loaded 74807831229 Bytes, about 156 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          69.2 seconds inserted 10000000 Rows, about 144K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230626100441_clickbench_pr_167883.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
