### PR TITLE
[fix](memory) Fix LRU Cache of type `NUMBER` charge

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

 LRU Cache of type `LRUCacheType::NUMBER` cache capacity means the number of entries, so the `charge` of insert is always `1` instead of `sizeof(CacheValue)`, which is easier to understand.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
