### PR TITLE
fix disk size more than long type range

### PR DESCRIPTION
**Pull request by mklzl**
## Proposed changes

Issue Number: close #xxx

## If the sum of the size of the be disk exceeds the range of the LONG data type,it causes the checkAvailableCapacity method to determine an exception

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by ixzc — APPROVED** [review]

**Review by deardeng — CHANGES_REQUESTED** [review]
请配置下代码编辑器，不要轻易修改代码缩进。后面merge代码会带来很多冲突的

**Comment by yujun777** [comment]
64 bit long capacity = 8EB,   that's a quite large capacity, suppose  a disk is 1T,   a machine cabinet = 1PB (1000 disk) ,   8EB = 1.6w cabinet.  Maybe a doris cluster cann't hold such a lot of data.

**Review by yujun777 — COMMENTED** [review]
Long type range is 8EB, that's a very large capacity.  A doris cluster couldn't hold such a lot.

**Review by yujun777 — CHANGES_REQUESTED** [review]
64 bit long capacity = 8EB, that's a quite large capacity, suppose a disk is 1T, a machine cabinet = 1PB (1000 disk) , 8EB = 8k cabinet. A doris cluster cann't hold such a lot of data.

**Comment by mklzl** [comment]
> 64 bit long capacity = 8EB, that's a quite large capacity, suppose a disk is 1T, a machine cabinet = 1PB (1000 disk) , 8EB = 8k cabinet. A doris cluster cann't hold such a lot of data.

In Doris On k8s deployment mode, the configured pv may have this problem。such as :
image

**Comment by yujun777** [comment]
Good case.


8388607 TB = (int64_t) = -1


Maybe be’s totoal capacity is not initialized or has bug calculating the capacity.


BE’s capacity is in class DataDir::_disk_capacity_bytes
Do you want to fix this bug ? 


在 2023年10月23日 ***@***.***> 写道：


64 bit long capacity = 8EB, that's a quite large capacity, suppose a disk is 1T, a machine cabinet = 1PB (1000 disk) , 8EB = 8k cabinet. A doris cluster cann't hold such a lot of data.
In Doris On k8s deployment mode, the configured pv may have this problem。such as :

**Comment by mklzl** [comment]
> Good case. [8388608](https://github.com/apache/doris/commit/8388608462dcb67709150f915a039c9456eb6124) TB = (int64_t) = -1 Maybe be’s totoal capacity is not initialized or has bug calculating the capacity. BE’s capacity is in class DataDir::_disk_capacity_bytes Do you want to fix this bug ? 在 2023年10月23日 ***@***.***> 写道： 64 bit long capacity = 8EB, that's a quite large capacity, suppose a disk is 1T, a machine cabinet = 1PB (1000 disk) , 8EB = 8k cabinet. A doris cluster cann't hold such a lot of data. In Doris On k8s deployment mode, the configured pv may have this problem。such as : — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I will try to solve this problem，tks !

**Pull request closed without merging**
