### PR TITLE
[Fix](orc-reader) Fix the issue when string col has mixed plain and dict encoding in different stripes.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Issue 

```
bbadf33823ed1aeb instance_id=0-0, error message: 
(10.10.11.192)[CANCELLED][E-1721] Size of filter doesn't match size of column: 
size=8128, filter.size=4064

0#  doris::Exception::Exception(int, std::basic_string_view<char, std::char_traits<char> > const&) 
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:173	
1#  doris::Exception::Exception<unsigned long&, unsigned long&>(int, 
    std::basic_string_view<char, std::char_traits<char> > const&, unsigned long&, unsigned long&) 
    at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:187	
2#  doris::vectorized::ColumnVector<unsigned long>::filter(doris::vectorized::PODArray<unsigned char, 4096ul, 
    Allocator
3#  doris::vectorized::ColumnNullable::filter(doris::vectorized::PODArray<unsigned char, 4096ul, Allocator
4# doris::vectorized::Block::filter_block_internal(doris::vectorized::Block*, std::vector<unsigned int, std::allocator<unsigned int> > const&, doris::vectorized::PODArray<unsigned char, 4096ul, Allocator

5# doris::vectorized::OrcReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*)
at /home/zcp/repo_center/doris_release/doris/be/src/vec/exec/format/orc/vorc_reader.cpp:1511
6# doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*)
```

The root cause there is something wrong when string col has mixed plain and dict encoding in different stripes.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run p0

**Review by AshinGau — DISMISSED** [review]

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
