### PR TITLE
support binlog for rename operator

### PR DESCRIPTION
**Pull request by lsy3993**
Related to #37031 and #38034.
Support binlog for rename operator

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
run buildall

**Comment by lsy3993** [comment]
Because the reason of version compatibility, adding new field in TableInfo is not permitted. Just close the PR

**Pull request closed without merging**
