### PR TITLE
[Fix](function) fix overflow of date_add function

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before:
```sql
select date_add("1900-01-01 12:00:00.123456", interval 10000000000 month);
------
r838-09-01 12:00:00.123456
```
now:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = (xxx)[E-218][E-218] Operation months_add 133705200962757184 1410065408 out of range
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by zhangstar333 — DISMISSED** [review]

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
