### PR TITLE
[feature](merge-cloud) Rewrite FS interface

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

To merge cloud filesystem implementation to Doris community, should do such things:
Image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Kikyou1997 — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
