### PR TITLE
[regression-test](fix)add ctas test cases.

### PR DESCRIPTION
**Pull request by ixzc**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ixzc** [comment]
run buildall

**Comment by zy-kkk** [comment]
You may have forgotten to commit the out file,cc @shuke987

**Review by shuke987 — APPROVED** [review]

**Review by shuke987 — APPROVED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
