### PR TITLE
[Enhancement](partition) Forbid create table with null partition item which relative column is not null

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before:
```sql
CREATE TABLE `test_null` (
`k0` BIGINT NOT NULL,
`k1` BIGINT NOT NULL
)
partition by list (k0, k1) (
PARTITION `pX` values in ((NULL, 1))
)
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
);
```
may core in local exchange for inserting.

now:
```sql
mysql [test]>CREATE TABLE `test_null` (
    -> `k0` BIGINT NOT NULL,
    -> `k1` BIGINT NOT NULL
    -> )
    -> partition by list (k0, k1) (
    -> PARTITION `pX` values in ((NULL, 1))
    -> )
    -> PROPERTIES (
    -> "replication_allocation" = "tag.location.default: 1"
    -> );
ERROR 1105 (HY000): errCode = 2, detailMessage = errCode = 2, detailMessage = Can't have null partition is for NOT NULL partition column in partition expr's index 0
```

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
