### PR TITLE
[refactor](catalog) catalog interface refactor

### PR DESCRIPTION
**Pull request by morningman**
## Catalog Code Structure

Most of the code is located under the `org.apache.doris.datasource` package.

Relevant classes previously stored under `catalog.external` and `planner.external` have been moved to `datasource` package.
**No logic is changed**

Take JDBC Catalog as an example:

- `org.apache.doris.datasource.jdbc`
	- Store the implementation class of Catalog/Database/Table
	- Store classes related to metadata access, such as MetaCache
	- Store some public methods
- `org.apache.doris.datasource.jdbc.source`
	- Store classes related to data reading, such as JdbcScanNode
- `org.apache.doris.datasource.jdbc.sink`
	- Store classes related to data writing, such as JdbcTableSink

## How to implement a new Catalog（Read Only）

Let's say you have a new Catalog named "Foo".

### FE side

1. Implement `FooExternalCatalog` inherited from `ExternalCatalog` and implement the following methods:

	- `listDatabaseNames()`: Get a list of all Database names.
	- `listTableNames()`: Get a list of all Table names under the specified Database.
	- `tableExist()`: Determine whether the specified Table exists.
	- `initLocalObjectsImpl()`: used to initialize some necessary objects when creating Catalog, such as `JdbcClient`.

2. Implement `FooExternalDatabase`, which inherits from `ExternalDatabase`, and implements the following methods:

	- `getExternalTable()`: Construct `FooExternalTable` instance.

3. Implement `FooExternalTable` integrated from `ExternalTable` and implement the following methods:

	- `makeSureInitialized()`: Initialize some necessary objects, such as `JdbcTable`.
	- `initSchema()` returns the schema of the Table.

4. Implement `FooScanNode` inherited from `FileQueryScanNode` and implement the following methods:

	- `getSplits()`: Get the data `Split` that need to be scanned.
	- `doInitialize()`: Initialize some necessary objects.
	- `setScanParams()`: For each `Split` object, generate a `TTableFormatFileDesc` object passed to the BE side.
	- `getLocationType()`: Get the location type of the `Split` that needs to be scanned, such as S3/HDFS.
	- `getFileFormatType()`: Get the format type of `Split` to be scanned, such as Parquet/ORC.
	- `getFileCompressType()`: Get the compression type of `Split` to be scanned, such as LZ4/SNAPPY.
	- `getFileAttributes()`: Get the description attributes of the file, such as the row and column separators of Text format files, etc.
	- `getPathPartitionKeys()`: Get the column name of the partition column on the file path.
	- `getLocationProperties()`: Obtain the connection information necessary to access the data source, such as HDFS namenode address, authentication information, etc.

### BE side

See various implementations inherited from `GenericReader` under `be/src/vec/exec/format/`.

## TODO

This is the first step to ensure that most of the External Catalog-related code is under a unified package. The interface implementation will be further refined in the future.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
