### PR TITLE
[Fix](Status) Disable printing stacktrace for `InvalidArgument` in `BitShufflePageDecoder::seek_to_position_in_page`

### PR DESCRIPTION
**Pull request by bobhan1**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
