### PR TITLE
[fix](test) fix unstable external p0 cases

### PR DESCRIPTION
**Pull request by morningman**
try fixing:
- test_clickhouse_jdbc_catalog
- test_hive_parquet_alter_column
- test_wide_table

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by shuke987 — APPROVED** [review]

**Pull request merged**
