### PR TITLE
[improvement](vectorized) Improve count distinct performance by using fastunion

### PR DESCRIPTION
**Pull request by zenoyang**
# Proposed changes

Issue Number: close #xxx
Improve count distinct performance by using fastunion.
Testing our user real data has a 10-40% performance improvement.

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
wow

**Comment by zhangstar333** [comment]
hi, I see this improvement also speed up agg function of bitmap_union, why not add it?

**Comment by zhangstar333** [comment]
LGTM, it's a great work! , And I could speed up to bitmap union using this way later

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
