### PR TITLE
[fix](cluster by) Fix cluster_by used-after-moved in compaction

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

The linter report a used-after-moved

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run p0

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by py023 — APPROVED** [review]
LGTM

**Pull request merged**
