### PR TITLE
[improvement](JDBC Catalog)Added Presto connection to Presto/Trino

### LINKED ISSUE #19726: [Bug] Can't create Presto Catalog
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4.1

### What's Wrong?

CREATE CATALOG presto PROPERTIES (
    "type"="jdbc",
    "user"="test",
    "password"="",
    "jdbc_url" = "jdbc:presto://192.168.231.248:7520/hive/test",
    "driver_url" = "presto-jdbc-0.218.jar",
    "driver_class" = "com.facebook.presto.jdbc.PrestoDriver"
);

[1105] [HY000]: errCode = 2, detailMessage = Unsupported jdbc database type, please check jdbcUrl: jdbc:presto://192.168.231.248:7520/hive/test

### What You Expected?

Can create Presto Catalog

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
# Proposed changes

Issue Number: close #19726

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.49 seconds
 stream load tsv:          429 seconds loaded 74807831229 Bytes, about 166 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230506074323_clickbench_pr_139234.html

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
