### PR TITLE
[chore](ci) adjust ckb expect result

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run performance

**Review by jacktengg — DISMISSED** [review]

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run performance

**Review by Gabriel39 — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
