### PR TITLE
[fix](fragment mgr) check duplicated pipeline fragment instance correctly

### PR DESCRIPTION
**Pull request by levy5307**
# Proposed changes

Issue Number: close #xxx

## Problem summary

`_fragment_map` has no bussiness with the pipeline version of `exec_plan_fragment` function. So we can't use it to check whether a duplicated fragment instance is coming. 

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run p0

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run p0

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.03 seconds
 stream load tsv:          473 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          33 seconds loaded 861443392 Bytes, about 24 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230322102219_clickbench_pr_118583.html

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run p0

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Pull request closed without merging**
