### PR TITLE
[Fix](planner) fix create view star except and modify cast to sql

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
fix old planner create view bug when the select has star except and cast(sth to time)

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run feet

**Comment by feiniaofeiafei** [comment]
run feut

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
