### PR TITLE
[Feature](ES): Support es get alias field type.

### LINKED ISSUE #17723: [Enhancement] (DOE) Supports alias field queries
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When creating a field in an alias in es, the field cannot be recognized.

image

image

image

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by stalary**
# Proposed changes

Issue Number: close https://github.com/apache/doris/issues/17723

## Problem summary

Support es get alias field type.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by stalary** [comment]
run buildall

**Comment by stalary** [comment]
run buildall

**Comment by stalary** [comment]
run p0

**Comment by stalary** [comment]
run buildall

**Comment by stalary** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
