### PR TITLE
[improvement](chore) remove unused code of RuntimeState

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by jacktengg** [comment]
run p1

**Comment by jacktengg** [comment]
run external

**Comment by yiguolei** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run performance

**Review by zhiqiang-hhhh — APPROVED** [review]

**Pull request merged**
