### PR TITLE
[regressiontest](statistics) Collate and supplement statistics regression test

### PR DESCRIPTION
**Pull request by weizhengte**
# Proposed changes

This pr is mainly supplement statistics regression test. include the following：

analyze stats p0 tests:

1. Universal analysis

analyze stats p1 tests:

1. Universal analysis
2. Sampled analysis
3. Incremental analysis
4. Automatic analysis
5. Periodic analysis

manage stats p0 tests:

1. Alter table stats
2. Show table stats
3. Alter column stats
4. Show column stats and histogram
5. Drop column stats
6. Drop expired stats

TODO：

1. Supplement related documents
2. Optimize for unstable cases encountered during testing
3. Add other cases

For pr related to statistics, should ensure that all of these cases pass！

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run compile

**Comment by weizhengte** [comment]
run p0

**Comment by Kikyou1997** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run compile

**Comment by weizhengte** [comment]
run p0

**Review by Kikyou1997 — APPROVED** [review]

**Review by Kikyou1997 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
