### PR TITLE
[docs](MoveRepo) Delete Docs in apache/doris 

### PR DESCRIPTION
**Pull request by luzhijing**
## Proposed changes

Move all docs to apache/doris-website repo and delete old docs

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by KassieZ — APPROVED** [review]

**Pull request merged**
