### PR TITLE
[fix](group_commit) Fix group_commit ut

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by hust-hhb** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
