### PR TITLE
[fix](Azure) Enhance the glob list's logic for azure file system in FE

### PR DESCRIPTION
**Pull request by ByteYue**
Previously in fe, for files like `s3://qa-build/regression/tpcds/sf100_split/catalog_sales.dat.*.gz` it can not work.

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by ByteYue** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
