### PR TITLE
[Bug](pipeline) fix pipeline task execute without wait second start rpc

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
task execute should wait the second start rpc.
if task execute without wait rpc and meet some error in node open function.
the query will be canceled, and remove query_id from query_map.
so when the second start rpc arrival will not found query_id.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
