### PR TITLE
[chore](ga) add large file checker

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Add a action to check if the PR contains large file.
To avoid merge large file in to code base

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
https://github.com/morningman/doris/actions/runs/10060661416/job/27808817591 status success

run buildall

**Review by CalvinKirs — APPROVED** [review]
For security reasons, I used a specific commit version.

**Comment by CalvinKirs** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
