### PR TITLE
[fix] need materialize condition conlumn in if function

### PR DESCRIPTION
**Pull request by starocean999**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:
if( condition, then, else ) the condition may be a const column. Before evaluate this function, condition column need to be materialized first.

## Checklist(Required)

1. Type of your changes:
    - [ ] Improvement
    - [*] Fix
    - [ ] Feature-WIP
    - [ ] Feature
    - [ ] Doc
    - [ ] Refator
    - [ ] Others: 
2. Does it affect the original behavior: 
    - [ ] Yes
    - [ *] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [*] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [*] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [*] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes
    - [*] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by kpfly — DISMISSED** [review]
LGTM

**Comment by stalary** [comment]
Need rebase to fix fe ut.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
