### PR TITLE
[improvement](jdbc catalog) remove useless jdbc catalog code

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #xxx

Since JdbcExecutor splitting for different data sources has been completed, I deleted the old JdbcExecutor code in this PR, and since the current reading of different data types is processed by each data source, we do not need to continue in BE Internal inspection is performed, so this part of the code is also deleted.In addition, since support for the nebula database Jdbc appearance is no longer needed, this part of the code has also been removed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
