### PR TITLE
[branch-2.0](prepared statement) Handle unsigned numeric type in prepared statement in legacy planner

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: bp #36133 #36426

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
