### PR TITLE
[Improvement](pipeline) Improve shared scan performance

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Use ConcurrentQueue to replace global queue and lock for scanners.

Test on SSB.
SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue FROM lineorder_flat WHERE     LO_ORDERDATE >= 19930101     AND LO_ORDERDATE <= 19931231     AND LO_DISCOUNT BETWEEN 1 AND 3     AND LO_QUANTITY < 25;

Before: 0.08s
After: 0.04s

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Comment by Gabriel39** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
