### PR TITLE
[fix](fe)reduce memory usage in alter

### LINKED ISSUE #32786: [Bug] ALTER TABLE COLUMN cause continuous  Full GC on fe
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.6,2.0.6

### What's Wrong?

Execute an alter table modify  command , fe memory usage usage is rapidly increasing and continuously undergoing Full GC operations. This makes the FE master unable to provide services.

the table has 1000+ partitions ,and the command has 500+ columns.

### What You Expected?

Optimize memory usage of the ALTER TABLE COLUMN command.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kylinmac**
Issue Number: close #32786 

Extract the creation of some objects from the loop

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Comment by luwei16** [comment]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
