### PR TITLE
[fix](test) change some names in regression test to avoid conflict name running in parallel

### PR DESCRIPTION
**Pull request by morningman**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]

**Review by wsjz — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Pull request merged**
