### PR TITLE
[enhance](ccr-test) Add downstream* for regression test to support downstream cluster

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add downstream* for regression test to support downstream cluster

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by XuJianxu — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Pull request closed without merging**
