### PR TITLE
[fix][chore](thrift) Fix warning when generate cpp code by thrift IDL file and use strict mode

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by yangzhg** [comment]
After this pr is merged, will the thrift data of different versions cannot be parsed during the upgrade or in the mixed distribution scenario?

**Comment by caiconghui** [comment]
> After this pr is merged, will the thrift data of different versions cannot be parsed during the upgrade or in the mixed version cluster?

The only thing I'm not sure about is if List<byte> and binary are compatible
but according to https://stackoverflow.com/questions/40886279/apache-thrift-difference-between-byte-and-binary-types
It seems that it is ok

**Comment by yangzhg** [comment]
Have you test this in a cluster that have new and old nodes ?

**Comment by caiconghui** [comment]
> Have you test this in a cluster that have new and old nodes ?



> Have you test this in a cluster that have new and old nodes ?

follower with new version，master with older version，I test forward function, but not test list<byte>

**Pull request merged**
