### PR TITLE
[chore](FE)add license header check in fe's checkstyle

### PR DESCRIPTION
**Pull request by morrySnow**
## Problem Summary:

Add license header check in fe's checkstyle

### CODE REVIEW

**Comment by morrySnow** [comment]
@924060929 PTAL

**Comment by wangshuo128** [comment]
LGTM
I thought this already exists...

**Comment by wangshuo128** [comment]
BTW, do we have any guidance to let developers get a license header template and config generating license header when creating new files automaticly in IntelliJ IDEA?

**Review by 924060929 — APPROVED** [review]
LGTM

**Pull request merged**
