### PR TITLE
[feature](backup) ignore table that not support type when backup, and…

### PR DESCRIPTION
**Pull request by nextdreamblue**
… not report exception

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buidlall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Review by w41ter — APPROVED** [review]

**Pull request merged**
