### PR TITLE
[fix](regression)Fix test_agg_complex_type fail case. Improve analyze_stats time consumption.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Reduce time consumption of analyze_stats case. Fix cloud version failed case test_agg_complex_type, set force_sample_analyze to false.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p1

**Comment by Jibing-Li** [comment]
run cloud_p1

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Review by zfr9527 — APPROVED** [review]
LGTM

**Pull request merged**
