### PR TITLE
[opt](routine load) support routine load perceived schema change

### PR DESCRIPTION
**Pull request by sollhui**
At present, if the table structure changes, the routine load cannot perceive it. As a long-running load, it should be able to perceive the changes in the table structure.

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Pull request merged**
