### PR TITLE
[enhance](auto-partition) forbid null column for auto partition

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

1. 
```sql
mysql> create table test_null1( k0 datetime(6) null ) auto partition by range date_trunc(k0, 'hour') ( ) DISTRIBUTED BY HASH(`k0`) BUCKETS 2 properties("replication_num" = "1");
ERROR 1105 (HY000): errCode = 2, detailMessage = The auto partition column must be NOT NULL
mysql> create table test_null2( k0 int null ) auto partition by list (k0) ( ) DISTRIBUTED BY HASH(`k0`) BUCKETS 2 properties("replication_num" = "1");
ERROR 1105 (HY000): errCode = 2, detailMessage = The auto partition column must be NOT NULL
```
2. add docs of `allowPartitionColumnNullable`

need pick 2.1, no 2.0

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Pull request merged**
