### PR TITLE
[Enhancement]use awaitility.await() add in variant and schema testcase

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #xxx
#37817
use awaitility in  variant  schema_change testcases.

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
