### PR TITLE
[FIX](compile)fix for gcc compile

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run external

**Comment by hello-stephen** [comment]
run performance

**Comment by amorynan** [comment]
run performance

**Comment by amorynan** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Review by shuke987 — APPROVED** [review]
LGTM

**Pull request merged**
