### PR TITLE
[opt](Nereids) polish aggregate function signature matching

### PR DESCRIPTION
**Pull request by morrySnow**
use double to match string
- corr
- covar
- covar_samp
- stddev
- stddev_samp

use largeint to match string
- group_bit_and
- group_bit_or
- group_git_xor

use double to match decimalv3
- topn_weighted

optimize error message
- multi_distinct_sum
- multi_distinct_sum0

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p0

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run feut

**Review by starocean999 — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
