### PR TITLE
[feature](sql-block-rule) sql block rule support external table

### PR DESCRIPTION
**Pull request by morningman**
Let SQL Block rule feature support external table:
```
create sql_block_rule r1 properties("partition_num" = "100", "global" = "true");
create sql_block_rule r2 properties("tablet_num" = "100", "global" = "true");
create sql_block_rule r3 properties("cardinality" = "100", "global" = "true");
```

For external table, `tablet_num` equals to `splitNum`

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by zddr — APPROVED** [review]

**Pull request merged**
