### PR TITLE
[fix](multicatalog) fix error reading data on tencent ofs after jdk17

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #xxx
error msg:
```sql
Exception in thread "TThreadPoolServer WorkerProcess-218" java.lang.NoClassDefFoundError: Could not initialize class chdfs.
1.1.6.com.qcloud.chdfs.cache.Platform
        at chdfs.1.1.6.com.qcloud.chdfs.fs.CHDFSInputStream.<init>(CHDFSInputStream.java:35)
        at chdfs.1.1.6.com.qcloud.chdfs.fs.CHDFSHadoopFileSystem.open(CHDFSHadoopFileSystem.java:1287)
        at com.qcloud.chdfs.fs.CHDFSHadoopFileSystemAdapter.open(CHDFSHadoopFileSystemAdapter.java:247)
        at org.apache.doris.broker.hdfs.FileSystemManager.openReader(FileSystemManager.java:1211)
        at org.apache.doris.broker.hdfs.HDFSBrokerServiceImpl.openReader(HDFSBrokerServiceImpl.java:188)
        at org.apache.doris.thrift.TPaloBrokerService$Processor$openReader.getResult(TPaloBrokerService.java:1145)
        at org.apache.doris.thrift.TPaloBrokerService$Processor$openReader.getResult(TPaloBrokerService.java:1125)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run buildall

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Pull request merged**
