### PR TITLE
[branch-2.1](arrow-flight-sql) Open regression-test/pipeline/p0/arrow_flight_sql

### PR DESCRIPTION
**Pull request by xinyiZzz**
pick #36854

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Pull request merged**
