### PR TITLE
[fix](mini-load) Remove mini load in LOADING and PENDING state

### LINKED ISSUE #8648: [Bug] There are more than xxx unfinished load jobs, please retry later.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

When submitting a load job, error returns:
```
There are more than 100 unfinished load jobs, please retry later. You can use `SHOW LOAD` to view submitted jobs
```

But `show load` return no job's running.

### What You Expected?

Can submit load job

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #8648 

## Problem Summary:

1. Remove some unused code.
2. handle mini load with wrong state
    1. For some historical reasons, some mini load jobs in LOADING state have not been cleared.
        As a result, new load jobs cannot be committed.
    2. If a mini load job is created right before FE restart, the mini load job will be in PENDING state forever.
        But it should be removed finally.

## Checklist(Required)

1. Does it affect the original behavior: (No)
4. Has unit tests been added: (No Need)
5. Has document been added or modified: (No Need)
6. Does it need to update dependencies: (No)
7. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luozenglin** [comment]
LGTM

**Comment by yiguolei** [comment]
Could we reimplement the miniload api by using stream load? And remove all these mini load code?

**Comment by morningman** [comment]
> Could we reimplement the miniload api by using stream load? And remove all these mini load code?

Actually, when using mini load in current version, it is same as stream load. The only difference it that the mini load will
create a MiniLoadJob in FE so that user can view the job with `show load` stmt.

I plan to disable the `/_load` api in Doris v1.1

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
