### PR TITLE
[fix](load) fix load null value(not '\N') from file

### LINKED ISSUE #17903: [Bug] routine load strict mode error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

CREATE TABLE `test9999` (
  `k1` datetime NOT NULL COMMENT "",
  `v1` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `v2` varchar(8) NOT NULL COMMENT "",
  `v3` largeint(40) NOT NULL COMMENT "",
  `v4` varchar(18) NULL COMMENT "",
  `v5` varchar(20) NULL COMMENT "",
  `v6` int NULL COMMENT "",
  `v7` varchar(8) NOT NULL COMMENT "",
  `v8` varchar(8) NOT NULL COMMENT "",
  `v9` varchar(320) NOT NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`)
COMMENT "OLAP" 
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1"
);

CREATE ROUTINE LOAD test123123 ON test9999
COLUMNS TERMINATED BY "|",
COLUMNS(k1, v2, v3, v4, v5, v6, v7, v8, v9)
PROPERTIES
(
    "max_batch_interval" = "30",
    "max_batch_rows" = "300000",
    "max_batch_size" = "111000000",
    "strict_mode" = "true"
)
FROM KAFKA
(
    "kafka_broker_list" = "********",
    "kafka_topic" = "****",
    "kafka_partitions" = "*****,
    "property.group.id" = "******"
);

数据内容如下：
```
2023-03-02|test|345634235887||132213123||AF|af|XXXX@gmail.com
```

报错：
```
Reason: column(v6) value is incorrect while strict mode is true, src value is af. src line [2023-03-02 test 345634235887 1111111111 132213123  AF af XXXX@gmail.com];
```

相同的数据和表使用stream load导入就可以正确导入，routine load就会失败

### What You Expected?

正确导入

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #17903

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.56 seconds
 stream load tsv:          461 seconds loaded 74807831229 Bytes, about 154 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          74 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230320162650_clickbench_pr_117522.html

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
目前只通过 \N 表示NULL，空值会按空字符串来对待，建议业务明确通过  \N 来在数据或文件或数据流中来表示NULL，防止写入失败

**Pull request closed without merging**
