### PR TITLE
[fix](log) avoid redundent log printing

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx
Avoid redundent log printing in `PInternalServiceImpl::_transmit_block` when get `Status::END_OF_FILE`
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
