### PR TITLE
[Bug](ScanNode) Fix potential incorrect query result caused by concurrent NewOlapScanNode initialization and Compaction

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

1. Optimize fetching delete predicates code:
  - Avoid traversing rowsets of tablet to  get specified version schema.
  - Get delete predicates directly from captured consistent rowsets instead of tablet to get rid of holding meta lock.

2. Fix incorrect query result when compaction eliminate delete predicates between `NewOlapScanNode::_init_scanners` and `NewOlapScanner::init`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Pull request merged**
