### PR TITLE
[feature](nereids) support common table expression

### LINKED ISSUE #13616: support CTE in Nereids
This issue is used to record the progress of the implementation of CTE functions and subtasks in nereids. Currently, the CTE syntax is implemented by fully inlining it(in #12742), without cost-based optimization. Based on approaches and algorithms in paper [Optimization of Common Table Expressions in MPP Database Systems](http://www.vldb.org/pvldb/vol8/p1704-elhelw.pdf), there are still a few more subtasks to be done, which may refactor the current CTE implementation.

Subtasks for this issue:

- [x] the completed CTE-related syntax, except keyword RECURSIVE, which is not supported in existing implementation; https://github.com/apache/doris/pull/12742
- [x] #16718
- [x] #16719
- [x] #16720
- [x] #16721
- [x] #16722
- [x] #16723

### PR DESCRIPTION
**Pull request by YangShaw**
# Proposed changes

Issue Number: subtask 1 of #13616 

## Problem summary

Support common table expression(CTE) in Nereids：
- Just implemented inline CTE, which means we will copy the logicalPlan of CTE everywhere it is referenced;
- If the name of CTE is the same as an existing table or view, we will choose CTE first;

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.19 seconds
 load time: 620 seconds
 storage size: 17108741844 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221019193901_clickbench_pr_31408.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 40.83 seconds
 load time: 565 seconds
 storage size: 17154657433 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020215940_clickbench_pr_32184.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.79 seconds
 load time: 593 seconds
 storage size: 17154864983 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028091355_clickbench_pr_35242.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 39.27 seconds
 load time: 556 seconds
 storage size: 17154644571 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028100130_clickbench_pr_35305.html

**Review by 924060929 — APPROVED** [review]

**Review by 924060929 — DISMISSED** [review]

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
