### PR TITLE
[opt](inverted index) Optimize the compression of inverted index position information

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Unalian** [comment]
Has Doris's inverted index been compressed before? Why is it smaller than the inverted index of Lucene/Clucene? Thank you for your ideas.

**Comment by zzzxl1993** [comment]
@Unalian 
1.  Earlier versions of Doris only applied the PFOR compression algorithm to the inverted lists of the inverted index.  We plan to use the PFOR algorithm for position information and Zstd compression for dictionary information, which will further reduce the space usage of Doris indexes.
2.  Doris only utilizes column storage and inverted indexes, resulting in less space usage compared to Elasticsearch.

**Comment by Unalian** [comment]
> @Unalian
> 
> 1. Earlier versions of Doris only applied the PFOR compression algorithm to the inverted lists of the inverted index.  We plan to use the PFOR algorithm for position information and Zstd compression for dictionary information, which will further reduce the space usage of Doris indexes.
> 2. Doris only utilizes column storage and inverted indexes, resulting in less space usage compared to Elasticsearch.

Thank you for answering! 
1. I see PFOR compression on .frq files from codes. However, .frq (and as your plan, .prx file )files are always tiny compared with .tis(see from clucene).  Does PFOR compression algorithm on .frq/.prx have a big impact on the inverted index size? 
image
Or is there a big difference between the inverted index files' sizes generated by Clucene and that generated by Doris?

2. If we ignore all the data and only consider the size of the inverted index, I use Lucene to build an inverted index for the same data, and Doris uses less space. This makes me curious.

**Comment by zzzxl1993** [comment]
@Unalian 
1. Did you use the official Clucene for your tests? 
2. Doris has implemented some optimizations and modifications to Clucene. You can refer to this codebase: https://github.com/apache/doris-thirdparty/tree/clucene and the related pull request: https://github.com/apache/doris-thirdparty/pull/238.

**Comment by Unalian** [comment]
> @Unalian
> 
> 1. Did you use the official Clucene for your tests?
> 2. Doris has implemented some optimizations and modifications to Clucene. You can refer to this codebase: https://github.com/apache/doris-thirdparty/tree/clucene and the related pull request: [[opt](inverted index) optimize the space usage of the inverted index dictionary file and position information doris-thirdparty#238](https://github.com/apache/doris-thirdparty/pull/238).

1. I used this version: git://clucene.git.sourceforge.net/gitroot/clucene/clucene; And I set simple analyzer; Set writer config: SOTRE_NO; INDEX_NONORMS; INDEX_TOKENIZED; Add I set the config to make sure there is only one segment.
2. Thank you! I am reading the code here.

**Pull request closed without merging**
