### PR TITLE
[opt](split) add max wait time of getting splits

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Add session variable `fetch_splits_max_wait_time` to control the max wait time of getting splits to prevent long waiting time.

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by wsjz — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
