### PR TITLE
[improvement](compaction) start 1 cumu compaction thread each disk by default

### PR DESCRIPTION
**Pull request by dataroaring**
We start 1 cumu and base compaction thread each disk.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by luwei16 — APPROVED** [review]

**Comment by luwei16** [comment]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
