### PR TITLE
[improve](transaction) extend abort transaction time

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Transaction may be aborted when can not receive be heartbeat one minute, it may be unstable in some network isolation or abnormal situations, so the default time for aborting transaction has been extended and can be configurable.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
