### PR TITLE
[fix](create table) create table fail not write drop table editlog

### PR DESCRIPTION
**Pull request by yujun777**
Fix:  for creating table,  if create dynamic partition throw exception (pr #35778),  then create table will fail,  then drop table,  but it forget to write an editlog.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
