### PR TITLE
[FE](dependency) Add azure sdk dependency to FE

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

This is one prior pr for FE's Azure support. Introduce the Azure Java SDK in this PR. This way, the PR supporting S3 load and Copy into can be developed in parallel.

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
