### PR TITLE
Restructure storage type to support complex types expending

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes

This CL includes:
* Change the column metadata to a tree structure.
* Refactor the segment_v2.ColumnReader and sgment_v2.ColumnWriter to support complex type.
* Implements the reading and writing of array type.

## Types of changes

- [] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

- [x] I have create an issue on (#2885 ), and have described the feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

### CODE REVIEW

**Comment by liutang123** [comment]
@morningman @wangbo @kangkaisen Hi, this PR is the replacement PR of #3025. Look forward to reviewing.

**Review by kangkaisen — APPROVED** [review]
+1

**Review by morningman — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
LGTM

**Review by wangbo — APPROVED** [review]
+1

**Pull request merged**
