### PR TITLE
[chore](thirdparty) update bitshuffle from 0.3.5 to 0.5.1

### PR DESCRIPTION
**Pull request by HackToday**
Signed-off-by: Wu, Kaiqiang <kaiqiang.wu@intel.com>

# Proposed changes

Issue Number: close #xxx

## Problem summary

Update bitshuffle version

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Why upgrade this?

**Comment by HackToday** [comment]
@morningman This PR need such split(as reviewers comment), you can check the details here.
https://github.com/apache/doris/pull/15972

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.68 seconds
 load time: 490 seconds
 storage size: 17122982861 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230117013519_clickbench_pr_81666.html

**Comment by adonis0147** [comment]
Hi @HackToday , this PR should include the file `thirdparty/build-thirdparty.sh`

**Comment by HackToday** [comment]
> Hi @HackToday , this PR should include the file `thirdparty/build-thirdparty.sh`.

Have updated, but seems workflows blocks

**Comment by HackToday** [comment]
@adonis0147  “P0 Regression (ARM pipeline) ” details need login information for TeamCity, so I can not figure it out why it fails.
And other two pending for that.

**Comment by adonis0147** [comment]
> @adonis0147 “P0 Regression (ARM pipeline) ” details need login information for TeamCity, so I can not figure it out why it fails. And other two pending for that.
> 
> I check logs as guest, "+ grep -i 'virtual memory exhausted: Cannot allocate memory' /root/teamcity/teamcity-agent-1/work/e0bc234628561cad/build-doris.log [12:11:10]+ echo 'retry compile...' [12:11:10]++ nproc"
> 
> it not related with PR change.

Hi @HackToday , this check can be ignored because it isn't marked as a required workflow.

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by spaces-X — APPROVED** [review]
LGTM

**Pull request merged**
