### PR TITLE
Rewrite count(distinct if(bool, bitmap, null)) to bitmap_union_count

### LINKED ISSUE #4200: Rewrite count(distinct if(bool, bitmap, null)) to bitmap_union_count
Some time, users want to execute a sql like follows:
```
select count(distinct if(id = 1, id2, null)) , count(distinct id2) from test.bitmap_table
```
Now, `IF` Expr will return decimal type and the result is meaningless.

### PR DESCRIPTION
**Pull request by liutang123**
Fix #4200

Add IF(BOOL, BITMAP, BITMAP) function.
Add UT.

### CODE REVIEW

**Comment by kangkaisen** [comment]
nullif, ifnull, coalesce function should also update.

**Comment by liutang123** [comment]
> nullif, ifnull, coalesce function should also update.

Add ifnull(bitmap, bitmap) and coalesce(bitmap,...).

For `nullif(bitmap, bitmap)`, I can not think of comparing two bitmaps.

**Comment by kangkaisen** [comment]
> > nullif, ifnull, coalesce function should also update.
> 
> Add ifnull(bitmap, bitmap) and coalesce(bitmap,...).
> 
> For `nullif(bitmap, bitmap)`, I can not think of comparing two bitmaps.

OK. But PR not update.

**Review by kangkaisen — APPROVED** [review]
+1, LGTM

**Pull request merged**
