### PR TITLE
[fix](function) fix error result in auto partition name

### PR DESCRIPTION
**Pull request by wyxxxcat**
## Proposed changes

Issue Number: close #xxx

list partitions support NULL columns as partition columns

Before:
```
mysql> select auto_partition_name('list','wyx','null');
+-------------------------------------------------------------+
| auto_partition_name('list','wyx','null')                    |
+-------------------------------------------------------------+
| NULL                                                        |
+-------------------------------------------------------------+
```
Now:
```
mysql> select auto_partition_name('list','wyx','null');
+-------------------------------------------------------------+
| auto_partition_name('list','wyx','null')                    |
+-------------------------------------------------------------+
| pwyx3X                                                      |
+-------------------------------------------------------------+
```

### CODE REVIEW

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run buildall

**Comment by wyxxxcat** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
