### PR TITLE
[opt](MultiCast) Avoid copying while holding a lock

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

pick https://github.com/apache/doris/pull/37462
The difference is quite large, so it can't be directly picked.

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
