### PR TITLE
[fix](auth)Fix the need for low-level table permissions when querying views in certain situations

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?
fix when `create view v1 as select * from table1 union select * from table2` and user has select_priv of v1,but he can not `select * from v1`

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Fix the need for low-level table permissions when querying views in certain situations
### Release note

Fix the need for low-level table permissions when querying views in certain situations

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Comment by zddr** [comment]
run p0

**Pull request merged**
