### PR TITLE
[Fix](cloud) Fix cluster status inconsistent with bes and add config disable auto

### PR DESCRIPTION
**Pull request by deardeng**
1. add switch for auto start in cloud
2. fix inconsistent with cluster status  in be tag when add be node
3. fix docker compose， `[INVALID_ARGUMENT]cloud_instance_id in fe.conf and be.conf are not same, fe: , be: reg_cloud_instance`

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by deardeng** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
