### PR TITLE
[fix] (mac compile) Fix mac compile error & fe start time related

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Fix of PR #23582 

1. Some Fe codes are deleted by #23582  , need to be added back;
2. Fix mac build failed caused by wrong thrift declaration order.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.89 seconds
 stream load tsv:          550 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17161940622 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
not merge this fix in 2.0

**Pull request merged**
