### PR TITLE
[enhancement](schema) dynamic_partition.time_unit support year

### LINKED ISSUE #17013: [Feature] Support range partition by year, support range partition by season
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Support range partition by year with properties `"dynamic_partition.time_unit" = "YEAR"`.
Support range partition by season with properties `"dynamic_partition.time_unit" = "SEASON"`.

### Use case

Looks like below.

```SQL
-- DROP TABLE IF EXISTS foobar;
CREATE TABLE IF NOT EXISTS `foobar` (
  `id` bigint NOT NULL COMMENT '主键',
  `name` varchar(255) DEFAULT '' COMMENT '名称',
  `payment_date` date DEFAULT NULL COMMENT '支付时间',
  `payment_amount` varchar(255) DEFAULT '' COMMENT '支付金额',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `created_by` varchar(50) NOT NULL DEFAULT '' COMMENT '创建者',
  `updated_by` varchar(50) DEFAULT '' COMMENT '更新者',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int DEFAULT '1' COMMENT '版本号，用于乐观锁更新',
  `deleted` int DEFAULT '0' COMMENT '是否删除，1 是，0 否，作为软删除标记'
)
ENGINE=OLAP
DUPLICATE KEY(id)
COMMENT "测试表"
PARTITION BY RANGE(payment_date)
(
    PARTITION p2016 VALUES LESS THAN ("2017-01-01"),
    PARTITION p2017 VALUES LESS THAN ("2018-01-01"),
    PARTITION p2018 VALUES LESS THAN ("2019-01-01"),
    PARTITION p2019 VALUES LESS THAN ("2020-01-01"),
    PARTITION p2020 VALUES LESS THAN ("2021-01-01"),
    PARTITION p2021 VALUES LESS THAN ("2022-01-01"),
    PARTITION p2022 VALUES LESS THAN ("2023-01-01")
    , PARTITION p2023 VALUES LESS THAN ("2024-01-01")
)
DISTRIBUTED BY HASH(id) BUCKETS 32
PROPERTIES (
    "replication_num" = "3"
    ,"dynamic_partition.enable" = "true"
    ,"dynamic_partition.time_unit" = "YEAR"
    ,"dynamic_partition.start" = "-10"
    ,"dynamic_partition.end" = "1"
    ,"dynamic_partition.prefix" = "p"
    ,"dynamic_partition.buckets" = "16"
);
```

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #17013

dynamic_partition.time_unit support year

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.83 seconds
 stream load tsv:          425 seconds loaded 74807831229 Bytes, about 167 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230511105332_clickbench_pr_142325.html

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
