### PR TITLE
[chore](build) Fix the compilation errors on macOS (arm64)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

~~Issue Number: close #xxx~~

## Problem summary

Some errors raise when building the codebase on macOS (arm64).

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run be_ut

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
