### PR TITLE
[fix](remote) fix be crash while write data to s3 in debug mode

### LINKED ISSUE #15046: [Bug] BE crash while write data to s3 in debug mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master，1.2

### What's Wrong?
It is unreasonable to use DCHECK to check whether etag is empty, it is also need check in release mode. 
And etag is not empty under normal conditions.

9dc572c1b9e63b3d33f71efc7ea1a078

### What You Expected?

write data to s3 well in debug mode

### How to Reproduce?

use if judgment instead of DCHECK(), if etag is empty will return error.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zxealous**
# Proposed changes

Issue Number: close #15046

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.86 seconds
 load time: 432 seconds
 storage size: 17123356931 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221213143220_clickbench_pr_62789.html

**Review by pengxiangyu — COMMENTED** [review]
LGTM

**Review by pengxiangyu — DISMISSED** [review]
LGTM

**Review by pengxiangyu — APPROVED** [review]
LGTM

**Pull request merged**
