### PR TITLE
[Improvement](test) compute be full coverage

### PR DESCRIPTION
**Pull request by pingchunzhang**
compute be full coverage, which report will be like 
image

### CODE REVIEW

**Comment by pingchunzhang** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.65 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17162394067 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
