### PR TITLE
Catalog suport gaussdb

### PR DESCRIPTION
**Pull request by xulovemin**
## Proposed changes

[feat](catalog)  jdbccatalog support gaussdb

## Further comments

JdbcCatalog Support gaussdb

### CODE REVIEW

**Comment by morningman** [comment]
Hi @xulovemin Thanks for your contributor.
But we need more details about this new catalog, such as column type mapping, docs and test cases.

**Comment by xulovemin** [comment]
> Hi @xulovemin Thanks for your contributor. But we need more details about this new catalog, such as column type mapping, docs and test cases.

gaussdb is based on PostgreSQL and has undergone modifications. The calling methods and syntax are the same, similar to the example of MySQL and MariaDB. Therefore, I directly made the changes.

**Comment by morningman** [comment]
> > Hi @xulovemin Thanks for your contributor. But we need more details about this new catalog, such as column type mapping, docs and test cases.
> 
> @morningman GaussDb is based on PostgreSQL and has undergone modifications. The calling methods and syntax are the same, including DML, DDL, and column mapping. It's similar to the example of MySQL and MariaDB, so I directly made the changes. The following is an example of my actual usage:
> 
> CREATE CATALOG `gaussdb` PROPERTIES ( "password" = "passowrd", "driver_class" = "com.huawei.gauss200.jdbc.Driver", "only_specified_database" = "false", "driver_url" = "gsjdbc-200.jar", "lower_case_table_names" = "true", "type" = "jdbc", "user" = "user", "jdbc_url" = "jdbc:gaussdb://ip:port/db?useCursorFetch=true" );
> 
> show tables from gaussdb.public;
> 
> I just made some modifications in the project and used it. I am only providing some suggestions. The implementation can be further investigated by experts. I hope to see more catalogs added with more powerful features.

Can you provide a docker compose for GaussDb so that we can add regression test case for it?

**Comment by xulovemin** [comment]
> > > Hi @xulovemin Thanks for your contributor. But we need more details about this new catalog, such as column type mapping, docs and test cases.
> > 
> > 
> > @morningman GaussDb is based on PostgreSQL and has undergone modifications. The calling methods and syntax are the same, including DML, DDL, and column mapping. It's similar to the example of MySQL and MariaDB, so I directly made the changes. The following is an example of my actual usage:
> > CREATE CATALOG `gaussdb` PROPERTIES ( "password" = "passowrd", "driver_class" = "com.huawei.gauss200.jdbc.Driver", "only_specified_database" = "false", "driver_url" = "gsjdbc-200.jar", "lower_case_table_names" = "true", "type" = "jdbc", "user" = "user", "jdbc_url" = "jdbc:gaussdb://ip:port/db?useCursorFetch=true" );
> > show tables from gaussdb.public;
> > I just made some modifications in the project and used it. I am only providing some suggestions. The implementation can be further investigated by experts. I hope to see more catalogs added with more powerful features.
> 
> Can you provide a docker compose for GaussDb so that we can add regression test case for it?

Hi @morningman 
`version: '3'
services:
  gaussdb:
    container_name: gaussdb
    image: enmotech/opengauss:3.0.3
    environment:
      GS_PASSWORD: Enmo@123
      TZ: Asia/Shanghai
    volumes:
      - /gaussdb:/var/lib/opengauss
    ports:
      - 5432:5432
    networks:
      - my_network
networks:
  my_network:
    external: true`
username is gaussdb

**Pull request closed without merging**
