### PR TITLE
[regression](memtable) add case for memtable flush error status handle

### PR DESCRIPTION
**Pull request by Ma1oneZhang**
1. Enable debug points
2. Trigger the debug points and change the _flush_status varible
3. Catch the execption
4. Disable all debug points

### CODE REVIEW

**Comment by Ma1oneZhang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Ma1oneZhang** [comment]
run buildall

**Comment by Ma1oneZhang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
