### PR TITLE
[Improvement](shuffle) Use a knob to decide whether a serial exchange should be used

### PR DESCRIPTION
**Pull request by Gabriel39**
### What problem does this PR solve?
A new knob to control a exchange node should be serial or not.
For example, a partitioned hash join should be executed like below:
```
┌────────────────────────────┐                  ┌────────────────────────────┐
│                            │                  │                            │
│Exchange(HASH PARTITIONED N)│                  │Exchange(HASH PARTITIONED N)│
│                            │                  │                            │
└────────────────────────────┴─────────┬────────┴────────────────────────────┘
                                       │                                      
                                       │                                      
                                       │                                      
                                       │                                      
                                       │                                      
                                       │                                      
                                ┌──────▼──────┐                               
                                │             │                               
                                │ HASH  JOIN  │                               
                                │             │                               
                                └─────────────┘                               
```          

After turning on this knob, the real plan should be:
```
  ┌──────────────────────────────┐                        ┌──────────────────────────────┐    
  │                              │                        │                              │    
  │ Exchange (HASH PARTITIONED 1)│                        │ Exchange (HASH PARTITIONED 1)│    
  │                              │                        │                              │    
  └────────────┬─────────────────┘                        └────────────┬─────────────────┘    
               │                                                       │                      
               │                                                       │                      
               │                                                       │                      
               │                                                       │                      
               │                                                       │                      
┌──────────────▼─────────────────────┐                  ┌──────────────▼─────────────────────┐
│                                    │                  │                                    │
│ Local  Exchange(HASH PARTITIONED N)│                  │ Local  Exchange(HASH PARTITIONED N)│
│              1 -> N                │                  │              1 -> N                │
└────────────────────────────────────┴─────────┬────────┴────────────────────────────────────┴
                                               │                                              
                                               │                                              
                                               │                                              
                                               │                                              
                                               │                                              
                                               │                                              
                                        ┌──────▼──────┐                                       
                                        │             │                                       
                                        │ HASH  JOIN  │                                       
                                        │             │                                       
                                        └─────────────┘                                       
```

For large cluster, X (mappers) * Y (reducers) rpc channels can be reduced to X (mappers) * Z (BEs).

### Check List (For Committer)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
