### PR TITLE
[bug](map-type)fix some bugs in map and map element function

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

fix some bugs in map and map element function:

1、error occur when map constructor's parameter is empty:

Before:

```
mysql> select map();
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: 0
```

After:

```
mysql> SELECT map();
+-------+
| MAP{} |
+-------+
| MAP{} |
+-------+
1 row in set (0.01 sec)
```

2、be core in map constructor when the parameter number is odd:

Before

```
mysql> select map(1,'a',3,'c',5);
ERROR 1105 (HY000): RpcException, msg: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

After

```
mysql> select map(1,'a',3,'c',5);
ERROR 1105 (HY000): errCode = 2, detailMessage = map can't be odd parameters, need even parameters: map(1, 2, 3, 4, 5)
```

3、be core in map element function

Before

```
mysql> select {1:"a", 3:"b", 5:"c"}[1];
ERROR 1105 (HY000): RpcException, msg: org.apache.doris.rpc.RpcException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

After

```
mysql> select {1:"a", 3:"b", 5:"c"}[1];
+------------------------------------------------+
| %element_extract%(MAP{1:'a', 3:'b', 5:'c'}, 1) |
+------------------------------------------------+
| a                                              |
+------------------------------------------------+
1 row in set (0.02 sec)
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run clickbench

**Comment by xy720** [comment]
run clickbench

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.66 seconds
 stream load tsv:          432 seconds loaded 74807831229 Bytes, about 165 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230423120942_clickbench_pr_133414.html

**Comment by xy720** [comment]
run p0

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
