### PR TITLE
[case](sql_block_rule)fix case return list should order

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #44302 

Problem Summary:

fix case return list should order

### Release note

fix case return list should order

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p0

**Review by seawinde — APPROVED** [review]

**Pull request merged**
