### PR TITLE
[docs](releasenote) 2.0 beta release note

### PR DESCRIPTION
**Pull request by luzhijing**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luzhijing** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]

**Comment by luzhijing** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
