### PR TITLE
[improvement](statistics)Write audit log while doing drop stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add delete sql to audit log while doing drop stats and truncate table.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM
But we should call `logAuditLog` inside the `stmtExecutor.execute();`.
Better refactor in future

**Review by morrySnow — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run buildall

**Pull request merged**
