### PR TITLE
[fix](jdbc catalog) fix gbase catalog time type mapping and scan && limit pushdown

### PR DESCRIPTION
**Pull request by zy-kkk**
followup #41027
We should map time to String and support reading time outside of 24 hours.
and add limit pushdown

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
