### PR TITLE
[branch-2.0](test-framework) Support operator performance test for branch2.0

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

cherry-pick https://github.com/apache/doris/pull/27582, https://github.com/apache/doris/pull/27848, https://github.com/apache/doris/pull/23762 and https://github.com/apache/doris/pull/28051

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Pull request merged**
