### PR TITLE
[Fix](clean trash) Fix clean trash use agent task

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

clean trash 使用be的 rpc 线程干活，影响到了create tablet agent task执行，导致建表超时

```
本地复现：

在be代码void BackendService::clean_trash() 函数中sleep 100s
create database db1;
建表 如回归case中的
DROP database if EXISTS db1 force;
ADMIN CLEAN TRASH
create database db2; use db2;
CREATE TABLE IF NOT EXISTS `customer` (
  `c_custkey` int(11) NOT NULL COMMENT "",
  `c_name` varchar(26) NOT NULL COMMENT "",
  `c_address` varchar(41) NOT NULL COMMENT "",
  `c_city` varchar(11) NOT NULL COMMENT "",
  `c_nation` varchar(16) NOT NULL COMMENT "",
  `c_region` varchar(13) NOT NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "groupa2",
"in_memory" = "false",
"storage_format" = "DEFAULT"
）
```

clean trash 改成使用agent task形式，下发任务

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xy720 — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by deardeng** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
