### PR TITLE
[fix](alter) support alter table ENABLE FEATURE SEQUENCE_LOAD WITH PROPERTIES ( function_column.sequence_col = col_name)

### LINKED ISSUE #16899: [Bug] unique table can not alter table ENABLE FEATURE "SEQUENCE_LOAD" WITH PROPERTIES (   "function_column.sequence_col" = "col_name")
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

MySQL [test]> CREATE TABLE test (
    -> c1 int(11) NULL,
    -> v1 int(11) NULL COMMENT "",
    -> v2 datetime NULL COMMENT ""
    -> ) ENGINE=OLAP
    -> unique KEY(c1)
    -> COMMENT "OLAP"
    -> DISTRIBUTED BY HASH(c1) BUCKETS 3
    -> PROPERTIES (
    -> "replication_allocation" = "tag.location.default: 1",
    -> "in_memory" = "false",
    -> "storage_format" = "V2"
    -> );
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> ALTER TABLE test ENABLE FEATURE "SEQUENCE_LOAD" WITH PROPERTIES (   "function_column.sequence_col" = "v2" );
ERROR 1105 (HY000): errCode = 2, detailMessage = errCode = 2, detailMessage = unknown sequence column type

it can not alter table ENABLE FEATURE "SEQUENCE_LOAD" WITH PROPERTIES (   "function_column.sequence_col" = "col_name")

### What You Expected?

it can alter table ENABLE FEATURE "SEQUENCE_LOAD" WITH PROPERTIES (   "function_column.sequence_col" = "col_name") like WITH PROPERTIES (   "function_column.sequence_type" = "type").

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
…OPERTIES ( function_column.sequence_col = col_name)

# Proposed changes

Issue Number: close #16899

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run clickbench

**Comment by nextdreamblue** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.45 seconds
 stream load tsv:          459 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         39 seconds loaded 2358488459 Bytes, about 57 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230221040034_clickbench_pr_100713.html

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run beut

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by zhannngchen** [comment]
This property should not support schema change. We have a hidden sequence column, it's value is copied from specified column. If we want the new added sequence column works correctly, we should rewrite the value of hidden sequence column of all old data.

**Comment by nextdreamblue** [comment]
> This property should not support schema change. We have a hidden sequence column, it's value is copied from specified column. If we want the new added sequence column works correctly, we should rewrite the value of hidden sequence column of all old data.

ok, this pr will close

**Pull request closed without merging**
