### PR TITLE
[improvement] (storage) Dict decoder optimization

### PR DESCRIPTION
**Pull request by zuochunwei**
# Proposed changes
1. using StringValue _dict_word_info[] replace _start_offset_array + _len_array, two separate uint32_t array are not cache-friendly
2. to store String-pointer + String-len together is better, before changing,  reading String word must use the expression '_data + offset', after changing, we visit String word by _dict_word_info[subscript] directly
3. designing a new interface get_dict_word_info() to build _dict_word_info, one loop for String-ptr, another loop for calculating String-len, simper loop is good for SIMD, this benifit is wait for proving
4. multi-table ssb test result for SQL 2.1:
- before: 9 seconds
- after: 8.87 seconds

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangbo** [comment]
I want to make a test for this pr, so review may take some time.

**Comment by wangbo** [comment]
I think the abstraction for StringValue instead of offset and char_ptr is OK.
I want to do some testing to check whether performance is degraded

**Comment by wangbo** [comment]
No performance degradation after I test this pr;
Please fix the conflicts.

**Comment by zuochunwei** [comment]
too much conflicts, so i new a PR instead, this PR will be deleted later

**Comment by zuochunwei** [comment]
i have created a new PR, so close this PR

**Pull request closed without merging**
