### PR TITLE
[enhance](mtmv)Enable the MTMVRelatedTableIf interface to support mvcc 2

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

Add snapshotId as a parameter to the `getPartitionType`, `getPartitionColumnNames`, and `getPartitionColumns `methods of `MTMVRelatedTableIf`, as the partition information for different snapshotId may vary

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Continuing to optimize on the basis of https://github.com/apache/doris/pull/44419
### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [x] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run p0

**Review by Jibing-Li — DISMISSED** [review]

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run performance

**Comment by zddr** [comment]
run beut

**Comment by zddr** [comment]
run cloudut

**Review by Jibing-Li — APPROVED** [review]

**Pull request closed without merging**
