### PR TITLE
[improvement](function) improve date_trunc function performance when timeunit is const

### PR DESCRIPTION
**Pull request by zhangstar333**
this PR https://github.com/apache/doris/pull/22602 have check function.
only support date_trunc(column, const), so the second must be const literal
and no need to check time unit every row.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Review by HappenLee — COMMENTED** [review]
better use function call ptr to replace strncmp? like "re"

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
