### PR TITLE
[improvement](regression)Use createMV to create materialized view.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Sometimes, the regression case of create mv will fail because table is not NORMAL. Do not allow doing ALTER.
This pr use createMV method to create mv, it include the waiting time of doing mv jobs.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p0

**Pull request merged**
