### PR TITLE
[fix](auth)fix row policy use alias error

### LINKED ISSUE #19975: [Bug] row policy use alis error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

ERROR 1054 (42S22): errCode = 2, detailMessage = Unknown column 'id' in 'a'

repro steps：

use idx_db;

CREATE TABLE `userinfo` (
  `id` varchar(200) NULL,
  `username` varchar(500) NULL,
  `userprofession` varchar(500) NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);

insert into userinfo values ('1','wxx','教师');
insert into userinfo values ('5','sl','医生');
insert into userinfo values ('2','wcc','厨师');
insert into userinfo values ('4','zw','司机');
insert into userinfo values ('3','ls','程序员');

CREATE USER  'demo1' IDENTIFIED BY '123456';

GRANT SELECT_PRIV,ALTER_PRIV,LOAD_PRIV ON ..* TO 'demo1'@'%';

CREATE ROW POLICY test_userinfo_1 ON idx_db.userinfo
AS RESTRICTIVE TO demo1 USING (id in ('1','2','3'));

use demo1 login

select * from idx_db.userinfo a;
select * from idx_db.userinfo;

### What You Expected?

fix bug

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zddr**
# Proposed changes

Issue Number: close #19975 

## Problem summary

Describe your changes.

should not change object in cache

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
Please also check if it works with new optimizer

**Comment by zddr** [comment]
> [fix](auth)fix row policy use alias error

Verification completed, running normally

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
