### PR TITLE
[Fix](Variant) variant fallthrough with inverted index

### PR DESCRIPTION
**Pull request by eldenmoon**
When reading from segment, the schema type is variant, if we check type valid in `get_inverted_index`, the result should always return nullptr(since variant type it self does not support inverted index), but the actual storage could be `string` or etc.So we should ignore the type check and return the correct inverted index iterators

introduced by #36163
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — APPROVED** [review]

**Pull request merged**
