### PR TITLE
[chore] Fix compilation errors reported by clang

### LINKED ISSUE #9585: [Bug] Failed to compile by clang
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

When compiling by clang, some errors occur.
Snipaste_2022-05-16_11-11-20

### What You Expected?

Compile the project by clang successfully.

### How to Reproduce?

```shell
export DORIS_TOOLCHAIN=clang
./build.sh --be --clean
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #9585

## Problem Summary:

Please refer to #9585 .

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
CC @carlvinhust2012

**Comment by BiteTheDDDDt** [comment]
Maybe we can avoid `using function` like https://github.com/apache/incubator-doris/pull/9323

**Comment by BiteTheDDDDt** [comment]
LGTM

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
