### PR TITLE
[fix](mysql-channel) initialize mysql serializer by default

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Mysql serializer is used by all sub classes. Make it initialized by default to avoid NPE.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
