### PR TITLE
[doc](fix) a new docs for k8s deploy by operator to 2.0

### PR DESCRIPTION
**Pull request by catpineapple**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
