### PR TITLE
[fix](test) fix s3 load test failed

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Fix s3 load test failed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by pingchunzhang — APPROVED** [review]
LMGT

**Review by gavinchou — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
