### PR TITLE
[fix](grouping sets) fix grouping sets have multiple empty sets (#32317)

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by xiaokang** [comment]
#32317

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
#[32112](https://github.com/apache/doris/pull/32112)

**Pull request merged**
