### PR TITLE
[profile](name) add table rollup name in profile

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
add select rollup name in profile, eg:
```
  VNewOlapScanNode(baseall(test_rollup_name))  (id=0):(Active:  179.574us,  %  non-child:  0.00%)
        -  RuntimeFilters:  :  
        -  PushDownPredicates:  []
```

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
