### PR TITLE
[Improvement](load) Do no block in group commit sink

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Group commit sink operator will create an internal loading task before starting. This is a blocking stop now to create task by RPC which is not allowed on pipeline engine.
This PR makes this blocking step a dependency.

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by zclllyybb — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
