### PR TITLE
[fix](broker) not print broker request detail default

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

if broker detail contails ak/sk or some sensitive information, not print these info default in log 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xy720 — COMMENTED** [review]
The other information printed here may be valuable for operation and maintenance？

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
> The other information printed here may be valuable for operation and maintenance？

done, left some request infos

**Review by xy720 — APPROVED** [review]
LGTM

**Review by Yulei-Yang — APPROVED** [review]
LGTM

**Pull request merged**
