### PR TITLE
[fix](auth)remove the key when priv is empty

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

- remove the key when priv is empty
- check priv when create mv

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zddr** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
