### PR TITLE
[feature-wip](array-type) Add array functions size and cardinality

### PR DESCRIPTION
**Pull request by cambyzju**
# Proposed changes

Issue Number: close #7570

## Problem Summary:
1. Change static config enable_complex_type_support to dynamic config enable_complex_type for array columns;

2. Array function size and cardinality usage examples:

> 2.1. open vectorized engine

`mysql> set enable_vectorized_engine=true;`

> 2.2. size of array

```
mysql> select k1,k2,size(k2) from array_test;
+------+-----------+------------+
| k1   | k2        | size(`k2`) |
+------+-----------+------------+
|    1 | [1, 2, 3] |          3 |
|    2 | []        |          0 |
|    3 | NULL      |       NULL |
+------+-----------+------------+
```

> 2.3. cardinality of array

```
mysql> select k1,k2,cardinality(k2) from array_test;
+------+-----------+-------------------+
| k1   | k2        | cardinality(`k2`) |
+------+-----------+-------------------+
|    1 | [1, 2, 3] |                 3 |
|    2 | []        |                 0 |
|    3 | NULL      |              NULL |
+------+-----------+-------------------+
```

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
4. Has document been added or modified: (Yes/No/No Need)
5. Does it need to update dependencies: (Yes/No)
6. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
I think the `cardinality` is different from `size`. Cardinality return the "distinct" value number, while Size return total number?

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by adonis0147** [comment]
Why not just use single function (either `size` or `cardinality`), do we actually need the alias function?

**Comment by cambyzju** [comment]
> Why not just use single function (either `size` or `cardinality`), do we actually need the alias function?

Lots of users come from Hive or Spark, they have both size and cardinality functions.

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by cambyzju** [comment]
rebase to fix conflicts with master branch

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
