### PR TITLE
[fix](es catalog) only es_query function can push down to ES

### LINKED ISSUE #29318: [Bug] es catalog not_null_or_empty not working
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

`not_null_or_empty` not working

### What You Expected?

Working.

### How to Reproduce?

1. curl -sXPUT localhost:29200/test?pretty -H 'Content-Type:application/json' -d'{"settings":{"number_of_shards":1, "number_of_replicas":0},"mappings":{"properties":{"message":{"type":"text"}}}}'
2. curl -sXPUT localhost:9200/test/_doc/1?pretty -H'Content-Type:application/json' -d'{"id":1}'
3. curl -sXPUT localhost:9200/test/_doc/1?pretty -H'Content-Type:application/json' -d'{"id":2, "message":""}'
4. curl -sXPUT localhost:9200/test/_doc/1?pretty -H'Content-Type:application/json' -d'{"id":3, "message":"not null or empty"}'
5. CREATE CATALOG es PROPERTIES ( "type"="es", "hosts"="http://127.0.0.1:9200/" );
6. select message from test_v1 where message != '';
7. select message from test_v1 where message is not null;
8. select message from test_v1 where not_null_or_empty(message);

not_null_or_empty can not filter null or empty.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #29318 
1. Only push down `es_query` function to ES
2. Add null check where ES query result not have `_source` or `fields` fields.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
