### PR TITLE
[fix](plan) fix wrong result for random distributed agg table with all keys not null

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

cherry-pick https://github.com/apache/doris/pull/36270 to branch-2.1

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Review by lide-reed — COMMENTED** [review]
LGTM

**Pull request merged**
