### PR TITLE
[improvement](mysql) merge connect context and mysql channel and reduce send buffer memory

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem summary

This PR refactor the MysqlChannel and ConnectionContext,
and fix memory consumption issue.

1. Merge NMysqlChannel and MysqlChannel
   NMysqlChannel is implemented by nio, and it is now the default and the only MysqlChannel implementation.
   So we don't need it to be extended from `MysqlChannel`.
   I merged all methods from `NMysqlChannel` to `MysqlChannel`, and removed the `NMysqlChannel`.

2. Merge NConnectionContext and ConnectionContext
    Same as `MysqlChannel`, no need two implementation, merge them into one: `ConnectionContext`.

3. Fix double send buffer issue
    In previous, we incorrectly allocate 2 send buffer for each mysql connection, one is in `ConnectionContext`,
    and one is in `MysqlChannel`. This results in memory waste.
    After merging (N)ConnectionContext and (N)MysqlChannel, this is only one send buffer

4. Introduce `DummyMysqlChannel`
    The real mysql channel is only needed when the connection context is a real mysql connection context.
    For other senario, such as http connection, we also create a `ConnectionContext`, but should without a
    real mysql channel. And because for each mysql channel, this is a 2MB send buffer, which is memory waste.
    So I introduce `DummyMysqlChannel`, not only to save memory, but can also make unit test happy because
    it doesn't need to check if something got from `MysqlChannel` may be NULL. 

5. Fix potential memory leak bug
    It seems that in previous implementation of `NConnectionContext`, the `cleanup()` method doesn't call
    `threadlocal.remove()`.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.57 seconds
 stream load tsv:          481 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         41 seconds loaded 2358488459 Bytes, about 54 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230224165627_clickbench_pr_104215.html

**Comment by morningman** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
