### PR TITLE
[refactor] remove `atomic.h/cpp` use std::atomic instead

### PR DESCRIPTION
**Pull request by yangzhg**
# Proposed changes

remove atomic.h/cpp use c++ standard std::atomic instead

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
LGTM

**Comment by zbtzbtzbt** [comment]
I have a small question: why some variables are initialized to 0 and some not

**Comment by yangzhg** [comment]
> I have a small question: why some variables are initialized to 0 and some not

Previous `AtomicInt` will  initialize value as `0`， but `std::atomic` not, the variables not initialize as 0 will be initialized at ctor

**Comment by zbtzbtzbt** [comment]
> the variables not initialize as 0 will be initialized at ctor

i get it, thanks

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by yangzhg** [comment]
Merge for next remove mutex pr

**Pull request merged**
