### PR TITLE
[Enhancement](Expr) Opt In Set by small size fixed container to improve performance.

### PR DESCRIPTION
**Pull request by kaka11chen**
# Proposed changes

**Test Result**: (single-machine, single-thread)
|catalog.database|Query No|SQL|before opt|after opt|
| ------------- |:-------------:| ---------:| ---------:| ---------:|
|internal.clickbench|Q1|select CodeVersion, count(URLHash) from hits where CodeVersion in (0, 1, 30) group by CodeVersion;|0.48|0.40|
|internal.clickbench|Q2|select CodeVersion, count(URLHash) from hits where CodeVersion in (0, 1, 30, 514, 633, 644) group by CodeVersion;|0.49|0.47|
|hive.ssb100|Q5|SELECT  LO_ORDERDATE,     SUM(LO_REVENUE) AS revenue FROM lineorder_flat WHERE    LO_ORDERDATE IN (19920101, 19920102, 19920103) group by LO_ORDERDATE;|14.51|11.93|
|hive.ssb100|Q6|SELECT  LO_ORDERDATE,     SUM(LO_REVENUE) AS revenue FROM lineorder_flat WHERE    LO_ORDERDATE IN (19920101, 19920102, 19920103, 19920104, 19920105, 19920106, 19920107, 19920108, 19920109, 19920110, 19920111, 19920112) group by LO_ORDERDATE;|15.20|12.51|
|hive.ssb100|Q7|SELECT  LO_ORDERDATE,     SUM(LO_REVENUE) AS revenue FROM lineorder_flat WHERE    LO_ORDERDATE IN (19920101, 19920102, 19920103, 19920104, 19920105, 19920106, 19920107, 19920108, 19920109, 19920110, 19920111, 19920112, 19920113) group by LO_ORDERDATE;|15.25|14.27|
|hive.ssb100|Q8|SELECT     C_CITY,     S_CITY, (LO_ORDERDATE DIV 10000) AS YEAR,     SUM(LO_REVENUE) AS revenue FROM lineorder_flat WHERE     C_CITY IN ('UNITED KI1', 'UNITED KI5')     AND S_CITY IN ('UNITED KI1', 'UNITED KI5')     AND LO_ORDERDATE >= 19920101     AND LO_ORDERDATE <= 19971231 GROUP BY C_CITY, S_CITY, YEAR ORDER BY YEAR ASC, revenue DESC;|17.40|13.74|
|hive.ssb100|Q9|SELECT     C_CITY,     S_CITY, (LO_ORDERDATE DIV 10000) AS YEAR,     SUM(LO_REVENUE) AS revenue FROM lineorder_flat WHERE     C_CITY IN ('UNITED KI1', 'UNITED KI5')     AND S_CITY IN ('UNITED KI1', 'UNITED KI5')     AND LO_ORDERDATE >= 19971201     AND LO_ORDERDATE <= 19971231 GROUP BY C_CITY, S_CITY, YEAR ORDER BY YEAR ASC, revenue DESC;|13.40|10.11|

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.94 seconds
 stream load tsv:          458 seconds loaded 74807831229 Bytes, about 155 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230320200945_clickbench_pr_117618.html

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
