### PR TITLE
[fix](dynamic partition) fix dynamic partition storage medium not working

### PR DESCRIPTION
**Pull request by yujun777**
fix dynamic_partition.storage_medium not working if hot_partition_num <= 0

for example: 

```
Config.default_storage_medium = ssd
dynamic_partition.storage_medium = hdd
```

will create dynamic partition on ssd, but it should on hdd;

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run clickbench

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
