### PR TITLE
[feature](partitions)support batch delete partition

### PR DESCRIPTION
**Pull request by LemonLiTree**
```sql
ALTER TABLE example_db.my_table
DROP PARTITION p1,
DROP PARTITION p2,
DROP PARTITION p3;
``

### CODE REVIEW

**Review by zy-kkk — DISMISSED** [review]

**Comment by zy-kkk** [comment]
please add regression test

**Review by morningman — COMMENTED** [review]
Please add test case

**Comment by LemonLiTree** [comment]
> Please add test case

done

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
