### PR TITLE
[improvement](statistics)Remove collect external table row count task.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Before, we would create an analyze task for external table to collect the row count of the table. But this is resource consuming and unnecessary. Because the planner doesn't use table row count, it fetch the row count from column row count. This pr is to remove this row count task for external table. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
