### PR TITLE
[fix](load) fix MemTableWriter::active_memtable_mem_consumption

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Active memtable should be the memtable currently being writing.
Fix active_memtable_mem_consumption for use in memtable memory limiter.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
