### PR TITLE
[Fix](schema_hash) Fix bug that introduced by removing schema_hash

### LINKED ISSUE #9441: [Bug] All Export job exec error now
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

98bfeaf560f7ac04f2324499e4dc7cc3bbf0a437

## All  Export  job  exec  error now 

2022-05-07 16:48:38,626 INFO (export checker pending|91) [ExportChecker.runPendingJobs():115] run pending export job. job: ExportJob [jobId=19010, label=clzlabel, dbId=10005, tableId=14005, state=PENDING, path=hdfs://szwg-palo-be04.szwg01.baidu.com:9000/user/palo/clz/output/xixi, partitions=(null), progress=0, createTimeMs=2022-05-07 16:48:31, exportStartTimeMs=\N, exportFinishTimeMs=\N, failMsg=ExportFailMsg [cancelType=UNKNOWN, msg=], files=()]
2022-05-07 16:48:38,626 ERROR (export_pending_job_pool-2|217) [MasterTask.run():33] task exec error
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_91]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_91]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_91]
	at org.apache.doris.task.ExportPendingTask.makeSnapshots(ExportPendingTask.java:114) ~[palo-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.task.ExportPendingTask.exec(ExportPendingTask.java:76) ~[palo-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[palo-fe.jar:1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_91]

## Caused by   

#9005 

image

image

@caiconghui  @yiguolei   

### What You Expected?

no error

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #9441 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
cc @chenlinzhong @yiguolei

**Comment by chenlinzhong** [comment]
strongly recommended  formatter the code first  by running:

 > sh build-support/clang-format.sh

The master branch has been formatted

**Comment by caiconghui** [comment]
> strongly recommended formatter the code first by running:
> 
> > sh build-support/clang-format.sh
> 
> The master branch has been formatted

run it, but it seems not as expected

**Comment by morningman** [comment]
> > strongly recommended formatter the code first by running:
> > > sh build-support/clang-format.sh
> > 
> > 
> > The master branch has been formatted
> 
> run it, but it seems not as expected

You need to use clang format v11, see http://doris.incubator.apache.org/zh-CN/developer-guide/cpp-format-code.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

**Comment by chenlinzhong** [comment]
> > strongly recommended formatter the code first by running:
> > > sh build-support/clang-format.sh
> > 
> > 
> > The master branch has been formatted
> 
> run it, but it seems not as expected

what's error ?   maybe clang-format version is too lower ?

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
