### PR TITLE
[ci](perf) adjust performance pipeline

### PR DESCRIPTION
**Pull request by hello-stephen**
1. remove old tpch trigger
2. branch-2.0 also run performance

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run performance

**Comment by hello-stephen** [comment]
run performance

**Comment by dataroaring** [comment]
<details>
<summary>TPC-DS: <b>Total hot run time: 182867 ms</b></summary>

```
machine: 'aliyun_ecs.c7a.8xlarge_32C64G'
scripts: https://github.com/apache/doris/tree/master/tools/tpcds-tools
TPC-DS sf100 test result on commit b82c8d37c46a746dae07eb2c6f2918aec8a1e012, data reload: false

run tpcds-sf100 query with default conf and session variables
query1	574	343	342	342
query2	2233	2111	2147	2111
query3	450	217	223	217
query4	23213	22610	22307	22307
query5	907	587	589	587
query6	234	199	189	189
query7	469	291	295	291
query8	242	216	215	215
query9	3158	2979	2783	2783
query10	637	352	357	352
query11	15620	15671	15609	15609
query12	143	108	94	94
query13	492	335	341	335
query14	7997	7623	7550	7550
query15	247	221	205	205
query16	584	328	323	323
query17	693	508	514	508
query18	409	298	301	298
query19	201	152	169	152
query20	110	107	111	107
query21	120	99	96	96
query22	5037	4733	4953	4733
query23	31562	31278	31062	31062
query24	3359	2953	2991	2953
query25	486	381	369	369
query26	599	168	178	168
query27	484	312	322	312
query28	2328	2187	2151	2151
query29	676	407	425	407
query30	216	139	149	139
query31	929	822	792	792
query32	95	73	80	73
query33	407	356	311	311
query34	799	462	494	462
query35	957	900	863	863
query36	1339	1220	1238	1220
query37	115	96	82	82
query38	3549	3365	3344	3344
query39	1340	1278	1294	1278
query40	120	92	87	87
query41	39	39	36	36
query42	109	106	105	105
query43	547	523	524	523
query44	1126	796	805	796
query45	227	207	202	202
query46	1069	701	665	665
query47	1772	1629	1660	1629
query48	387	293	281	281
query49	588	313	336	313
query50	735	313	333	313
query51	5455	5282	5331	5282
query52	110	100	97	97
query53	234	166	171	166
query54	1010	628	672	628
query55	106	97	94	94
query56	286	286	248	248
query57	1026	966	976	966
query58	303	256	266	256
query59	3015	2929	2767	2767
query60	346	303	312	303
query61	151	137	155	137
query62	552	468	465	465
query63	195	192	185	185
query64	2547	1712	1669	1669
query65	3445	3331	3365	3331
query66	535	389	392	389
query67	15676	14755	15326	14755
query68	19322	535	547	535
query69	659	327	320	320
query70	1708	1500	1539	1500
query71	632	303	297	297
query72	6354	3504	3490	3490
query73	5142	359	344	344
query74	6993	6582	6586	6582
query75	6941	2246	2222	2222
query76	8873	1190	1129	1129
query77	734	332	336	332
query78	9021	8562	8626	8562
query79	4118	527	515	515
query80	631	332	356	332
query81	412	213	213	213
query82	194	111	103	103
query83	215	146	139	139
query84	259	57	58	57
query85	789	279	267	267
query86	422	435	435	435
query87	3696	3463	3462	3462
query88	2939	2506	2521	2506
query89	397	275	308	275
query90	1735	265	233	233
query91	123	94	95	94
query92	81	67	78	67
query93	1975	488	481	481
query94	738	246	248	246
query95	559	503	487	487
query96	650	339	341	339
query97	4323	4198	4200	4198
query98	238	217	203	203
query99	1007	824	891	824
Total cold run time: 246601 ms
Total hot run time: 182867 ms
```
</details>

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by englefly — APPROVED** [review]

**Pull request merged**
