### PR TITLE
[Bug](materialized-view) fix failed insert into mv meet default null

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

fix failed insert into mv meet default null

```sql
mysql [test]>INSERT INTO `test` (`date`)  
    -> VALUES ('2023-07-19');
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: Failed analysis after expr substitution: errCode = 2, detailMessage = can not cast from origin type NULL_TYPE to target type=HLL
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
