### PR TITLE
[fix](datatype) fixed decimal type implicit cast handling in BinaryPredicate

### LINKED ISSUE #30103: [Bug] old planner and Nereids Planner can not return same result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

old planner and Nereids Planner can not return same result.

### What You Expected?

old planner and Nereids Planner return same result.

### How to Reproduce?

```sql
create table z1(a DECIMAL(2, 1), b DECIMAL(3, 2)) ENGINE=OLAP DUPLICATE KEY(a) COMMENT "OLAP" 
DISTRIBUTED BY HASH(a) BUCKETS  auto PROPERTIES (     "replication_num" = "1" );

create table z2(c DECIMAL(3, 2)) ENGINE=OLAP DUPLICATE KEY(c) COMMENT "OLAP" DISTRIBUTED BY HASH(c) BUCKETS  auto
 PROPERTIES (     "replication_num" = "1" );
 
 insert into z1 values(5.7, 5.70);
insert into z2 values(5.70);

select a, b from z1, z2 where a=c;

```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

Implicit type cast for binary predicate was not handled for decimal types correctly in **OriginalPlanner** (Neredis planner already handles this case as part of BindExpression),
It only compared primitive type without specialization on the scale and precision. leading to wrong result.

Issue Number: close #30103 

Added full Type compare instead of PreimitiveType compare to apply cast.

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by Vallishp — COMMENTED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
@morrySnow PTAL

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]
LGTM

**Pull request merged**
