### PR TITLE
[Fix](regression) fix regression sql which has schema change

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
This pr change the WaitForAction in regression test, making it able to wait for "ALTER TABLE ROLLUP" stmt.
And change the use of waitSchemaChangeJob to waitForSchemaChangeDone in 2 case.

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run external

**Comment by feiniaofeiafei** [comment]
run p1

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run xcloud_p0

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
