### PR TITLE
[regression](kerberos)add hive kerberos docker regression env

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

add kerberos docker regression environment
add cases for two different hive kerberos

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
