### PR TITLE
[enhancement](memory) Add PODArray UT and pick some patch

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

1. Add PODArray ut
2. pick https://github.com/ClickHouse/ClickHouse/pull/21533
3. pick https://github.com/ClickHouse/ClickHouse/pull/21678
4. pick https://github.com/ClickHouse/ClickHouse/pull/9498
5. pick https://github.com/ClickHouse/ClickHouse/pull/7791
6. pick https://github.com/ClickHouse/ClickHouse/pull/24271
7. if c_end_of_storage == null, allocated_bytes return 0.
8. Add some checks for DEBUG.
9. TODO: Adapt internal data structures to 512-bit era https://github.com/ClickHouse/ClickHouse/pull/42564

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
