### PR TITLE
[Improvement](multi catalog)Add comment to external hms table show create table output.

### PR DESCRIPTION
**Pull request by Jibing-Li**
# Proposed changes

Issue Number: close #xxx

## Problem summary

The output of `show create table` comment for hms external table doesn't contain comment section. This pr is to add the comment to the output.

Create table sql
```
create table `abc` (
`id` int,
`name` string comment 'name comment',
`department` string comment 'department comment')
COMMENT 'this is table comment'
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
WITH SERDEPROPERTIES (
'field.delim'=',',
'serialization.format'=',')
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
tblproperties (
'bucketing_version'='2',
'transactional_properties'='default');
```

Show create table result
```
mysql> show create table abc;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| abc   | CREATE TABLE `abc`(
  `id` int,
  `name` string COMMENT 'name comment',
  `department` string COMMENT 'department comment')
COMMENT 'this is table comment'
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs://172.21.16.47:4007/usr/hive/warehouse/test.db/abc'
TBLPROPERTIES (
  'totalSize'='0',
  'numRows'='0',
  'rawDataSize'='0',
  'transactional_properties'='default',
  'COLUMN_STATS_ACCURATE'='{"BASIC_STATS":"true"}',
  'numFiles'='0',
  'bucketing_version'='2') |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.13 sec)
```

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.59 seconds
 load time: 448 seconds
 storage size: 17123356277 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221206135100_clickbench_pr_58764.html

**Comment by morningman** [comment]
Also need to support comment in `desc table` stmt

**Comment by Jibing-Li** [comment]
> Also need to support comment in `desc table` stmt. So we need to save `comment` in `Column`

As discussed, this is not necessary.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
