### PR TITLE
[fix](es catalog)Unexpected result with query on text field of ES

### LINKED ISSUE #24443: [Bug] Unexpected result with query on text field of ES
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master 

### What's Wrong?

image

### What You Expected?

Get correct result.

### How to Reproduce?

``` 
docker run  --name your_container_name -p 80:80 -e "discovery.type=single-node"  --net=host  -e "ES_JAVA_OPTS=-Xms512m -Xmx512m"  -d elasticsearch:7.8.0 
```
创建index：
```
curl "http://127.0.0.1:9200/test_index" -H "Content-Type:application/json" -X PUT -d '{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      "device_id": {
        "type": "text"
      },
      "report_time": {
        "type": "long"
      },
      "company_id": {
        "type": "text"
      },
      "status": {
        "type": "text"
      },
      "user_name": {
        "type": "text"
      }
    }
  }
}'
```
导入数据到es：
```
curl "http://127.0.0.1:9200/test_index/_doc/1" -H "Content-Type:application/json" -X POST -d '{
    "company_id": 0,
    "device_id": "abc",
    "report_time": 1692892810,
    "status": "LOGIN",
    "user_name": "A52C86027FCF3E44719C62E1EB4E30CDDC403464"
}' 
```
在doris中创建catalog：
```
CREATE CATALOG es PROPERTIES (    "type"="es",    "hosts"="http://127.0.0.1:9200"); 
```
在doris中建表：
```
CREATE TABLE `test_es` ( device_id varchar(50), report_time bigint, company_id varchar(10), user_name varchar(50))
ENGINE=OLAP duplicate KEY (device_id)
DISTRIBUTED BY HASH(device_id) BUCKETS 1
PROPERTIES ( "replication_allocation" = "tag.location.default: 1"); 
```
查询es catalog，并将数据写入doris：
```
select device_id, report_time, company_id, user_name from es.default_db.test_index where report_time >= unix_timestamp('2023-07-01') and status = 'LOGIN'; 
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #24443
Do not pushdown ES text field, term query on text field may return unexpected results. Further read: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html#term-query-notes

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
It will cause performance problem if do not pushdown ES text field. Hold for more discussion.

**Pull request closed without merging**
