### PR TITLE
[Enhancement](meta) Show remote data usage via SHOW DATA #19533

### LINKED ISSUE #19533: [Enhancement] Show remote data usage via `SHOW DATA`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

After using hot and cold separation, `SHOW DATA` only shows local data usage of the table, but no remote cold data usage info. Expect to show both local and remote data usage via `SHOW DATA`.

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liangjiawei1110**
# Proposed changes

Issue Number: close #19533 

## Problem summary

Describe your changes.

SHOW DATA can show both local data usage of the table and remote cold data usage info. 
before 
image

----------------------------------------------------------------------------------------------------------------------------------------------

after
c48b72bc85f132b193345becd35685a
afebd237ee1c46d687e21a69537d07a

## Checklist(Required)

* [x] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liangjiawei1110** [comment]
run buildall

**Comment by liangjiawei1110** [comment]
run p1

**Review by platoneko — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
