### PR TITLE
[fix](load) fix new_load_scan_node load finished but no data actually caused by wrong file size

### LINKED ISSUE #15210: [Bug] load finished but no data actually
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

daily:https://ci-builds.apache.org/job/Doris/job/doris_daily_enable_vectorized/lastCompletedBuild/testReport/(root)/test_sys_pull_load_hdfs/test_all_types_parquet/

### What You Expected?

load Successfully

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #15210

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.85 seconds
 load time: 629 seconds
 storage size: 17123683872 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221220132053_clickbench_pr_65703.html

**Comment by morningman** [comment]
I saw the error in case is: ` [INTERNAL_ERROR]Open file failed. path=all_type_none.parquet, error=No such file or directory'`? The load job is not finished?

**Comment by luozenglin** [comment]
> I saw the error in case is: ` [INTERNAL_ERROR]Open file failed. path=all_type_none.parquet, error=No such file or directory'`? The load job is not finished?

Sorry, the daily test in the issue is not the latest result, and the latest case has not been opened yet. I will update the daily link later.

**Review by morningman — APPROVED** [review]
LGTM

**Comment by luozenglin** [comment]
> > I saw the error in case is: ` [INTERNAL_ERROR]Open file failed. path=all_type_none.parquet, error=No such file or directory'`? The load job is not finished?
> 
> Sorry, the daily test in the issue is not the latest result, and the latest case has not been opened yet. I will update the daily link later.

I have updated the failed daily case link in issuse

**Pull request merged**
