### PR TITLE
[fix][refactor](backend-policy)(compute) refactor the hierarchy of external scan node and fix compute node bug

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

There should be 2 kinds of ScanNode:

- OlapScanNode
- ExternalScanNode

The Backends used for ExternalScanNode should be controlled by FederationBackendPolicy.
But currently, only FileScanNode is controlled by FederationBackendPolicy, other scan node such as MysqlScanNode,
JdbcScanNode will use Mix Backend even if we enable and prefer to use Compute Backend.

In this PR, I modified the hierarchy of ExternalScanNode, the new hierarchy is:

```
ScanNode
    OlapScanNode
    SchemaScanNode
    ExternalScanNode
        MetadataScanNode
        DataGenScanNode
        EsScanNode
        OdbcScanNode
        MysqlScanNode
        JdbcScanNode
        FileScanNode
            FileLoadScanNode
            FileQueryScanNode
                MaxComputeScanNode
                IcebergScanNode
                TVFScanNode
                HiveScanNode
                    HudiScanNode
```

And previously, the `BackendPolicy` is the member of `FileScanNode`, now I moved it to the `ExternalScanNode`.
So that all subtype ExternalScanNode can use `BackendPolicy` to choose Compute Backend to execute the query.

All all ExternalScanNode should implement the abstract method `createScanRangeLocations()`.

For scan node like jdbc scan node/mysql scan node, the scan range locations will be selected randomly from
compute node(if preferred).

And for compute node selection. If all scan nodes are external scan nodes, and `prefer_compute_node_for_external_table`
is set to true, the BE for this query will only select compute nodes.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by Jibing-Li** [comment]
Reviewed. LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
