### PR TITLE
[fix](crash) be crash because of duplicate __PARTIAL_UPDATE_AUTO_INC_COLUMN__ (#41172)

### PR DESCRIPTION
**Pull request by cambyzju**
pick #41172 to branch-2.1

### CODE REVIEW

**Comment by cambyzju** [comment]
run buidlall

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
