### PR TITLE
[enhancement](Nereids) boost characterLiteralTypeCoercion

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

Boost characterLiteralTypeCoercion by check the string format and skip throw Throwable when can not parse string to integer/float/date/datetime.

This logical usually appear when search `If`  function signature, because the If has lots of signature, we need cast argument to the signature type to matches the best signature, for example:

```
select if(column_1, 'xxx', 'yyy')
```
we will check whether the 'xxx' and 'yyy' can be parsed to int/datetime and so on.

In some scenarios, this optimize can provide 16% QPS

before: optimize:
image

image

after optimize:
image

image

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
