### PR TITLE
[fix](test)fix auto partition date file not exists

### PR DESCRIPTION
**Pull request by zfr9527**
## Proposed changes

[fix](test)fix auto partition date file not exists

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zfr9527** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Comment by zfr9527** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
