### PR TITLE
[improvement](show snapshot) show iceberg snapshot print summary info

### PR DESCRIPTION
**Pull request by whutpencil**
add doc

## Proposed changes

Iceberg's snapshot has summary information, but Doris did not display it. This patch fixes this issue.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by whutpencil** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by wuwenchi** [comment]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
