### PR TITLE
[feature](table-value-functions)add catalogs table-value-function

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes
add catalogs table value function

```
mysql> select * from catalogs() order by CatalogId;
+-----------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------+
| CatalogId | CatalogName | CatalogType | Property                                       | Value                                                                     |
+-----------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------+
|         0 | internal    | internal    | NULL                                           | NULL                                                                      |
|     11471 | hive        | hms         | dfs.ha.namenodes.HDFS8000871                   | nn1,nn2                                                                   |
|     11471 | hive        | hms         | create_time                                    | 2023-07-13 11:28:53.667                                                   |
|     11471 | hive        | hms         | ipc.client.fallback-to-simple-auth-allowed     | true                                                                      |
|     11471 | hive        | hms         | enable.self.splitter                           | true                                                                      |
|     11471 | hive        | hms         | hive.metastore.uris                            | thrift://127.0.0.1:7004                                                 |
|     11471 | hive        | hms         | type                                           | hms                                                                       |
|     11471 | hive        | hms         | dfs.nameservices                               | HDFS8000871                                                               |
|     11471 | hive        | hms         | hadoop.username                                | hadoop                                                                    |
|     11471 | hive        | hms         | dfs.namenode.rpc-address.HDFS8000871.nn1       | 127.0.0.1:4007                                                          |
|     11471 | hive        | hms         | dfs.namenode.rpc-address.HDFS8000871.nn2       | 127.0.0.1:4007                                                          |
|     11471 | hive        | hms         | dfs.client.failover.proxy.provider.HDFS8000871 | org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider |
|     12002 | hive2       | hms         | dfs.ha.namenodes.HDFS8000871                   | nn1,nn2                                                                   |
|     12002 | hive2       | hms         | create_time                                    | 2023-07-13 11:59:23.249                                                   |
|     12002 | hive2       | hms         | ipc.client.fallback-to-simple-auth-allowed     | true                                                                      |
|     12002 | hive2       | hms         | enable.self.splitter                           | true                                                                      |
|     12002 | hive2       | hms         | hive.metastore.uris                            | thrift://127.0.0.1:7004                                                 |
|     12002 | hive2       | hms         | type                                           | hms                                                                       |
|     12002 | hive2       | hms         | dfs.nameservices                               | HDFS8000871                                                               |
|     12002 | hive2       | hms         | hadoop.username                                | hadoop                                                                    |
|     12002 | hive2       | hms         | dfs.namenode.rpc-address.HDFS8000871.nn1       | 127.0.0.1:4007                                                          |
|     12002 | hive2       | hms         | dfs.namenode.rpc-address.HDFS8000871.nn2       | 127.0.0.1:4007                                                          |
|     12002 | hive2       | hms         | dfs.client.failover.proxy.provider.HDFS8000871 | org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider |
+-----------+-------------+-------------+------------------------------------------------+---------------------------------------------------------------------------+
23 rows in set (0.04 sec)

mysql> desc function catalogs();
+-------------+--------+------+-------+---------+-------+
| Field       | Type   | Null | Key   | Default | Extra |
+-------------+--------+------+-------+---------+-------+
| CatalogId   | BIGINT | No   | false | NULL    | NONE  |
| CatalogName | TEXT   | No   | false | NULL    | NONE  |
| CatalogType | TEXT   | No   | false | NULL    | NONE  |
| Property    | TEXT   | No   | false | NULL    | NONE  |
| Value       | TEXT   | No   | false | NULL    | NONE  |
+-------------+--------+------+-------+---------+-------+
5 rows in set (0.04 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.23 seconds
 stream load tsv:          502 seconds loaded 74807831229 Bytes, about 142 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17169213505 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230714011300_clickbench_pr_178198.html

**Pull request merged**
