### PR TITLE
[fix](typo) typo fix for 'delete bimap' changing to 'delete bitmap'

### PR DESCRIPTION
**Pull request by WinkerDu**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WinkerDu** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Comment by WinkerDu** [comment]
@yiguolei maybe we can merge this pr?

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
@morningman maybe we can merge it?

**Comment by WinkerDu** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
