### PR TITLE
[improve](routine-load) optimize routine load task schedule to make consume real-time and balanced

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

If be slot is full, the task will be put in the end, causing the partition corresponding to this task will be delayed in consumption and consumption not balanced.

Therefore, the PR keeps the task still in the head of the queue to avoid it.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
