### PR TITLE
[Docs](docs) Rename Release Note Title and File name of CN & EN Version

### PR DESCRIPTION
**Pull request by KassieZ**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KassieZ** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
build all

**Comment by zy-kkk** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
