### PR TITLE
[fix](Nereids) fix some bugs in Subquery to window rule

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. fix window function generation method, replace inner slot with equivalent outer slot
2. forbid below scenes
  a. inner has a mapping project
  b. inner has an unexpected filter
  c. outer has a mapping project
  d. outer has an unexpected filter
  e. outer has additional table
  f. outer has same table
  g. outer and inner with different join condition
  h. outer and inner has same table with different join condition

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.33 seconds
 stream load tsv:          448 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230330023415_clickbench_pr_122590.html

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
