### PR TITLE
[Fix](jdbcCatalog) fix typo of some variable

### LINKED ISSUE #22198: [Bug] typo maxIdelTime
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

there's a typo `maxIdelTime` in java files and be.conf :

https://github.com/apache/doris/blob/master/fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcExecutor.java#L91

`private int maxIdelTime;`

https://github.com/apache/doris/blob/master/conf/be.conf#L22

`-DJDBC_MAX_IDEL_TIME=300000`

### What You Expected?

it should be maxIdleTime.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #22198 

There are some typo in jdbcExectuor.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
