### PR TITLE
[opt](error msg) Make data codec error clearly when load csv data can't display

### PR DESCRIPTION
**Pull request by Tanya-W**
## Proposed changes

Issue Number: close #xxx

Current no detailed error information when load csv file failed due to non-utf-8 encoding data.
This pr add more error information to help user find which data in large file is problematic of encoding.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Tanya-W** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
