### PR TITLE
[fix](clone) fix stale tablet report miss the new cloning replica

### PR DESCRIPTION
**Pull request by yujun777**
BUG:
1. BE begin collect tablet report;
2. BE clone a new replica A;
3. FE handle this BE's tablet report from step 1. But it's stale, it don't include the replica A,  then FE mark replica A as bad;

only after 1min later, BE report tablets again, then the new report contains replica A, only after that, FE will change replica A from bad to good.

Fix:
If BE clone a new replica,   it should increase its report version and tell FE to update it.   Then if FE handle the stale tablet report,  it will compare BE's report version, then found the tablet report is stale and discard it.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run external

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
