### PR TITLE
[Improvement](fe)Simplified type system initialization Array List

### PR DESCRIPTION
**Pull request by darionyaphet**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
lgtm

**Comment by yiguolei** [comment]
@darionyaphet  pls fix fe code style check failed problem

**Comment by darionyaphet** [comment]
> @darionyaphet pls fix fe code style check failed problem

thanks ~  fix java code style and please review

**Comment by yiguolei** [comment]
run buildall

**Comment by darionyaphet** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.54 seconds
 stream load tsv:          531 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162153587 Bytes

**Pull request closed without merging**
