### PR TITLE
[Feature](compatibility) make some agg function restrict

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
make some agg function restrict

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]
Need more discussion

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
