### PR TITLE
[Improve]Profile logging is enabled by default

### PR DESCRIPTION
**Pull request by hf200012**
Many community users do not know how to set this, they are confused, it is recommended to enable it by default

# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
The default value of enableProfile should be false, this only be used for trace query performance, not used on line for better query performance

**Review by yangzhg — COMMENTED** [review]
Why set this variables to true?  it may be cause performance problem when  qps  is very high

**Review by yangzhg — CHANGES_REQUESTED** [review]
we may need more discuss

**Comment by hf200012** [comment]
Mainly when many users in the community use it, they do not set this, and the web interface cannot see the information, and this problem is raised

**Comment by hf200012** [comment]
> > > information
> 
> > 
> 
> > Maybe should prompt that user should set the variable when entered the web interface.
> 
> 
> 
> Agree, I think we can just add a hint on UI.

good idea

**Pull request closed without merging**
