### PR TITLE
[feature](profile) add DORIS_BUILD_SHORT_HASH in profile 

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
```
show frontends
         IsHelper: true
           ErrMsg: 
          Version: doris-2.0.0-trunk-2b9a95f74f
```
```
profile
    Summary:
          -  Profile  ID:  7ae9974d8f0c417a-8c493b70a94023a9
          -  Doris  Version:  doris-2.0.0-trunk-2b9a95f74f
          -  Task  Type:  QUERY
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run clickbench

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.68 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162108006 Bytes

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
