### PR TITLE
[fix](DECIMAL) error DECIMAL cat to BOOLEAN

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
before
```
mysql []>select 3.14 and 3.0;
+--------------------------------------------------+
| (cast(3.14 as BOOLEAN) AND cast(3.0 as BOOLEAN)) |
+--------------------------------------------------+
|                                                3 |
+--------------------------------------------------+
mysql [test]>select cast(3.000 as boolean) ;
+------------------------+
| cast(3.000 as BOOLEAN) |
+------------------------+
|                      3 |
+------------------------+

```
now
```
mysql [test]>select cast(3.000 as boolean) ;
+------------------------+
| cast(3.000 as BOOLEAN) |
+------------------------+
|                      1 |
+------------------------+
```

In the past, casting DECIMAL to BOOLEAN directly converted it to an integer.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast

cast function of mysql do not support using bool as type argument.

**Comment by Mryange** [comment]
> https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
> 
> cast function of mysql do not support using bool as type argument.

But there is implicit conversion to boolean.
https://dbfiddle.uk/FGUsvxTk

**Comment by Mryange** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
> > https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
> > cast function of mysql do not support using bool as type argument.
> 
> But there is implicit conversion to boolean. https://dbfiddle.uk/FGUsvxTk

why do you think there is an implicit conversion?

https://dev.mysql.com/doc/refman/8.3/en/logical-operators.html#operator_and

oprator_and checks whether operands are zero or NULL, it has nothing to do with type convert.

**Comment by Mryange** [comment]
> > > https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
> > > cast function of mysql do not support using bool as type argument.
> > 
> > 
> > But there is implicit conversion to boolean. https://dbfiddle.uk/FGUsvxTk
> 
> why do you think there is an implicit conversion?
> 
> https://dev.mysql.com/doc/refman/8.3/en/logical-operators.html#operator_and
> 
> oprator_and checks whether operands are zero or NULL, it has nothing to do with type convert.

My mistake, as doris implementation involves implicit conversion.
But such results in doris
```
mysql []>set enable_fold_constant_by_be = false;
Query OK, 0 rows affected (0.00 sec)

mysql []>select 3.14 and 3.0;
+--------------------------------------------------+
| (cast(3.14 as BOOLEAN) AND cast(3.0 as BOOLEAN)) |
+--------------------------------------------------+
|                                                3 |
+--------------------------------------------------+
1 row in set (0.03 sec)

mysql []>desc select 3.14 and 3.0;
+----------------------------------------------------------+
| Explain String(Nereids Planner)                          |
+----------------------------------------------------------+
| PLAN FRAGMENT 0                                          |
|   OUTPUT EXPRS:                                          |
|     (cast(3.14 as BOOLEAN) AND cast(3.0 as BOOLEAN))[#0] |
|   PARTITION: UNPARTITIONED                               |
|                                                          |
|   HAS_COLO_PLAN_NODE: false                              |
|                                                          |
|   VRESULT SINK                                           |
|      MYSQL_PROTOCAL                                      |
|                                                          |
|   0:VUNION(30)                                           |
|      constant exprs:                                     |
|          CAST(3.14 AS BOOLEAN) AND CAST(3.0 AS BOOLEAN)  |
+----------------------------------------------------------+
13 rows in set (0.01 sec)

mysql []>select 3.14 and 2.0;
+--------------------------------------------------+
| (cast(3.14 as BOOLEAN) AND cast(2.0 as BOOLEAN)) |
+--------------------------------------------------+
|                                                2 |
+--------------------------------------------------+
```

**Comment by zhiqiang-hhhh** [comment]
> > > > https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
> > > > cast function of mysql do not support using bool as type argument.
> > > 
> > > 
> > > But there is implicit conversion to boolean. https://dbfiddle.uk/FGUsvxTk
> > 
> > 
> > why do you think there is an implicit conversion?
> > https://dev.mysql.com/doc/refman/8.3/en/logical-operators.html#operator_and
> > oprator_and checks whether operands are zero or NULL, it has nothing to do with type convert.
> 
> My mistake, as doris implementation involves implicit conversion. But such results in doris
> 
> ```
> mysql []>set enable_fold_constant_by_be = false;
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql []>select 3.14 and 3.0;
> +--------------------------------------------------+
> | (cast(3.14 as BOOLEAN) AND cast(3.0 as BOOLEAN)) |
> +--------------------------------------------------+
> |                                                3 |
> +--------------------------------------------------+
> 1 row in set (0.03 sec)
> 
> mysql []>desc select 3.14 and 3.0;
> +----------------------------------------------------------+
> | Explain String(Nereids Planner)                          |
> +----------------------------------------------------------+
> | PLAN FRAGMENT 0                                          |
> |   OUTPUT EXPRS:                                          |
> |     (cast(3.14 as BOOLEAN) AND cast(3.0 as BOOLEAN))[#0] |
> |   PARTITION: UNPARTITIONED                               |
> |                                                          |
> |   HAS_COLO_PLAN_NODE: false                              |
> |                                                          |
> |   VRESULT SINK                                           |
> |      MYSQL_PROTOCAL                                      |
> |                                                          |
> |   0:VUNION(30)                                           |
> |      constant exprs:                                     |
> |          CAST(3.14 AS BOOLEAN) AND CAST(3.0 AS BOOLEAN)  |
> +----------------------------------------------------------+
> 13 rows in set (0.01 sec)
> 
> mysql []>select 3.14 and 2.0;
> +--------------------------------------------------+
> | (cast(3.14 as BOOLEAN) AND cast(2.0 as BOOLEAN)) |
> +--------------------------------------------------+
> |                                                2 |
> +--------------------------------------------------+
> ```

I think the problem here may be signature of and operator is not correnct ,it should not use boolean as operator.

**Pull request closed without merging**
