### PR TITLE
[feature](merge-cloud) Support delete statement in cloud mode

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Support delete statement in cloud mode

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by cwang9208** [comment]
@platoneko Hello, are there any detailed design docs about the DELETE write path for the Doris cloud mode?

**Pull request merged**
