### PR TITLE
[imrovement](iterators) reduce memory for union iterators

### PR DESCRIPTION
**Pull request by dataroaring**
## Proposed changes

After the patch, doris opens iterators for union on demand and free it if it is not used any more. e.g. if there are 1000 rowsets for a tablet, before the patch, doris allocates a block for each rowset and segments of them is loaded while after the patch, doris allocates a block for the only one rowset being read and its segments is loaded, others is not loaded any more.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
