### PR TITLE
[branch-2.0][enhancement](regression) fault injection for segcompaction test (#25709)

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

1. generalized debug point facilities from docker suites for fault-injection/stubbing cases
2. add segcompaction fault-injection cases for demonstration
3. add -238 TOO_MANY_SEGMENTS fault-injection case for good

#25709 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run build

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run p0

**Comment by HHoflittlefish777** [comment]
run arm

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
