### PR TITLE
[fix](commit) Fix does not skip commit if txn state is committed or visible

### PR DESCRIPTION
**Pull request by mymeiyi**
introduced in #32980
if a txn is committed twice, the check txn state is committed or visible and skip commit logic does not work

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by yujun777 — CHANGES_REQUESTED** [review]
```
void   XXXTransaction() {
        readlock()
         txn = getTransaction()
         checkTransactionStateBeforeXXX() 
        readunlock()

         do something no need lock()

         writeLock()
         checkTransactionStateBeforeXXX() 
          ...
         writeUnlock()
}
```


maybe in write lock scope,  check transaction status again is better ?

here XXXTransaction  XXX should include PreCommit/Commit/Abort

**Comment by mymeiyi** [comment]
run fe_ut

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
Please add a description of what scenario triggers the issue.

**Review by dataroaring — CHANGES_REQUESTED** [review]
There should be a lock hold when check and commit. Otherwise, two parallel thread may check ok and commit together.  It seems that lock on trasaction state is enough.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
