### PR TITLE
[fix](chore) fix session var memtable on sink for bulk load

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

The added line had been there, but was deleted somehow.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run external

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
