### PR TITLE
[docs] Correct ssb data validation sql error

### PR DESCRIPTION
**Pull request by zenoyang**
# Proposed changes

Correct ssb data validation sql error: 
`select count(*) from date;` to `select count(*) from dates;`

## Problem Summary:

Describe the overview of changes.

## Checklist(Requried)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luzhijing** [comment]
the table name is 'date' , you can refer the following create-table.sql
 
[](https://github.com/apache/incubator-doris/blob/master/tools/ssb-tools/create-tables.sql)

**Review by hf200012 — APPROVED** [review]
Documentation yes

**Review by hf200012 — COMMENTED** [review]
Documentation yes

**Comment by zenoyang** [comment]
ok，my mistake！

**Pull request closed without merging**
