### PR TITLE
[fix]be地址重复提交时，不报异常

### PR DESCRIPTION
**Pull request by Hanchers**
查看了相关的代码，似乎没啥影响。

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Hanchers** [comment]
[issue](https://github.com/apache/doris/issues/29880)

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Pull request closed without merging**
