### PR TITLE
[Chore](thrift) add some check on client cache && remove some unused code && catch st…

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
…d::exception on MasterServerClient rpc

# Proposed changes

1. add some check on client cache
2. remove some unused code
3. catch std::exception on MasterServerClient rpc

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 32.7 seconds
 stream load tsv:          432 seconds loaded 74807831229 Bytes, about 165 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230414121909_clickbench_pr_129207.html

**Comment by BiteTheDDDDt** [comment]
run p1

**Comment by BiteTheDDDDt** [comment]
run arm

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
