### PR TITLE
[Fix](Iceberg)Fix HDFS FileSystem Leak Caused by Frequent Refresh of Iceberg Catalog

### PR DESCRIPTION
**Pull request by CalvinKirs**
### Background
When using an HMS-based Iceberg Catalog, refreshing the Catalog frequently creates new HadoopAuthenticator instances. This leads to the following issues:

#### Frequent FileSystem Creation:
Iceberg uses Path.getFileSystem(Configuration) to obtain a FileSystem instance. Even though the Configuration remains unchanged, changes in the UserGroupInformation (UGI) cause new FileSystem instances to be created.

#### Resource Leakage:
```
Newly created FileSystem instances are not released, leading to increased resource consumption over time.

 198:          1978          72712  [Ljava.security.Principal;
 244:          2202          52848  javax.security.auth.kerberos.KerberosPrincipal
 418:           753          24096  sun.security.krb5.PrincipalName
 717:           391           9384  com.sun.security.auth.UnixNumericGroupPrincipal
 940:           382           6112  com.sun.security.auth.UnixNumericUserPrincipal
  64:          1158         240864  org.apache.hadoop.hdfs.client.impl.DfsClientConf
  99:          1155         147840  org.apache.hadoop.hdfs.DFSClient
 113:          1158         120432  org.apache.hadoop.hdfs.client.impl.DfsClientConf$ShortCircuitConf
 127:          3465         110880  org.apache.hadoop.hdfs.server.namenode.ha.AbstractNNFailoverProxyProvider$NNProxyInfo
 189:          1155          64680  org.apache.hadoop.hdfs.DistributedFileSystem
 204:           294          58800  org.apache.hadoop.hdfs.protocol.DatanodeInfoWithStorage
 215:          2310          55440  org.apache.hadoop.hdfs.server.datanode.CachingStrategy
```

#### Root Cause
Each Catalog refresh creates a new HadoopAuthenticator instance. Changes in the UGI contained in HadoopAuthenticator lead to the creation of new FileSystem instances, even when the Configuration is the same.

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Pull request closed without merging**
