### PR TITLE
[Bug](function) fix week function get wrong result

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

before:
```
select week(cast('0000-01-01' as DATEV2), cast(2 as INT));
+----------------------------------------------------+
| week(cast('0000-01-01' as DATEV2), cast(2 as INT)) |
+----------------------------------------------------+
|                                                 52 |
+----------------------------------------------------+
1 row in set (0.00 sec)
```
 but it's should return 1 as result,
 mode 2 is start with a Sunday day as first week in this year.
 and special case for 0000-01-01, as it's SATURDAY, calculate result of 52 is
 last year, so it's meaningless.

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by zclllyybb — COMMENTED** [review]
lgtm for the fix. but we should add both fe-ut and be-ut for them. maybe cover the first 7 days and last 7 days for year 0000

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
