### PR TITLE
[fix](Planner): branch-2.0 pick (#28432) (#28434)

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

branch-2.0 pick (#28432) (#28434)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
