### PR TITLE
update docker run command

### PR DESCRIPTION
**Pull request by andotorg**
update docker run -v source code in /var/local dir

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Why changing it to `/var/local`?

**Comment by andotorg** [comment]
> 为什么将其更改为`/var/local`？

in /var/local/thirdparty not download third application script

**Comment by morningman** [comment]
> > 为什么将其更改为`/var/local`？
> 
> in /var/local/thirdparty not download third application script

This docker image already contains all pre-compiled thirdparties, no need to download them again.

**Comment by jackwener** [comment]
Long time passed. And I find this PR isn't essential. 
Close it.
If you have some question, feel free to contact me by @jackwener / reopen this PR.

**Pull request closed without merging**
