### PR TITLE
[comm](github) add submodule create-or-update-comment

### PR DESCRIPTION
**Pull request by morningman**
Follow #27219
the action should be added as a submodule of Doris repo,
otherwise it is not allowed to run

also remove the message to https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
Please pay attention to similar security issues. We'd better check the corresponding commitid to verify the integrity of the package.  like thishttps://github.com/apache/doris/pull/26525

**Comment by CalvinKirs** [comment]
> Please pay attention to similar security issues. We'd better check the corresponding commitid to verify the integrity of the package. like thishttps://github.com/[/pull/26525](https://github.com/apache/doris/pull/26525)

I checked the permissions and this only requires read permission, so it's ok

**Pull request merged**
