### PR TITLE
[fix](move-memtable) fix load timeout caused by lost wakeup

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

introduced by：#31689

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
