### PR TITLE
[fix](docs) fix wrong link

### PR DESCRIPTION
**Pull request by gitccl**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
20000

**Comment by gitccl** [comment]
run buildall

**Comment by lexluo09** [comment]
20000
 take a look

**Comment by dutyu** [comment]
+1

**Comment by Yukang-Lian** [comment]
+1

**Comment by stalary** [comment]
+1

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Review by stalary — DISMISSED** [review]
LGTM

**Comment by wsjz** [comment]
666

**Comment by wsjz** [comment]
LGTM

**Comment by lsy3993** [comment]
LGTM

**Review by fuchanghai — DISMISSED** [review]
LGTM

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by zddr** [comment]
LGTM

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by SleepyBear96** [comment]
take a look

**Comment by zhangyuchi** [comment]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by caiconghui — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
MTGL

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by catpineapple** [comment]
LGTM

**Comment by luozenglin** [comment]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Pull request merged**
