### PR TITLE
[test](pipline) adjust mem limit to 90 & exclude some cases

### PR DESCRIPTION
**Pull request by zgxme**
## Proposed changes
1. Adjust `mem_limit` to 90% to prevent cases from failing due to query cancle.
2. Exclude some known case issues.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run p0

**Comment by zgxme** [comment]
run p1

**Comment by zgxme** [comment]
run p0

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run p1

**Comment by zgxme** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]

**Comment by hello-stephen** [comment]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
