### PR TITLE
[Bug](exchange) fix dcheck fail when VDataStreamRecvr input empty block

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

图片

0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/doris/be/src/common/signal_handler.h:413
12:56:30    1# 0x00007FE9D4797090 in /lib/x86_64-linux-gnu/libc.so.6
12:56:30    2# raise at ../sysdeps/unix/sysv/linux/raise.c:51
12:56:30    3# abort at /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81
12:56:30    4# 0x0000564104666E49 in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30    5# google::LogMessage::SendToLog() in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30    6# google::LogMessage::Flush() in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30    7# google::LogMessageFatal::~LogMessageFatal() in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30    8# doris::vectorized::VDataStreamRecvr::PipSenderQueue::get_batch(doris::vectorized::Block*, bool*) in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30    9# std::_Function_handler<doris::Status (doris::vectorized::Block*, bool*), std::_Bind<std::_Mem_fn<doris::Status (doris::vectorized::VDataStreamRecvr::SenderQueue::*)(doris::vectorized::Block*, bool*)> (doris::vectorized::VDataStreamRecvr::SenderQueue*, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, doris::vectorized::Block*&&, bool*&&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
12:56:30   10# doris::vectorized::BlockSupplierSortCursorImpl::has_next_block() at /root/doris/be/src/vec/core/sort_cursor.h:234
12:56:30   11# doris::vectorized::BlockSupplierSortCursorImpl::BlockSupplierSortCursorImpl(std::function<doris::Status (doris::vectorized::Block*, bool*)> const&, std::vector<std::shared_ptr<doris::vectorized::VExprContext>, std::allocator<std::shared_ptr<doris::vectorized::VExprContext> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&) at /root/doris/be/src/vec/core/sort_cursor.h:222
12:56:30   12# void std::vector<doris::vectorized::BlockSupplierSortCursorImpl, std::allocator<doris::vectorized::BlockSupplierSortCursorImpl> >::_M_realloc_insert<std::function<doris::Status (doris::vectorized::Block*, bool*)> const&, std::vector<std::shared_ptr<doris::vectorized::VExprContext>, std::allocator<std::shared_ptr<doris::vectorized::VExprContext> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&>(__gnu_cxx::__normal_iterator<doris::vectorized::BlockSupplierSortCursorImpl*, std::vector<doris::vectorized::BlockSupplierSortCursorImpl, std::allocator<doris::vectorized::BlockSupplierSortCursorImpl> > >, std::function<doris::Status (doris::vectorized::Block*, bool*)> const&, std::vector<std::shared_ptr<doris::vectorized::VExprContext>, std::allocator<std::shared_ptr<doris::vectorized::VExprContext> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&) in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30   13# doris::vectorized::VSortedRunMerger::prepare(std::vector<std::function<doris::Status (doris::vectorized::Block*, bool*)>, std::allocator<std::function<doris::Status (doris::vectorized::Block*, bool*)> > > const&) at /root/doris/be/src/vec/runtime/vsorted_run_merger.cpp:74
12:56:30   14# doris::vectorized::VDataStreamRecvr::create_merger(std::vector<std::shared_ptr<doris::vectorized::VExprContext>, std::allocator<std::shared_ptr<doris::vectorized::VExprContext> > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&, unsigned long, long, unsigned long) in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30   15# doris::vectorized::VExchangeNode::get_next(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/doris/be/src/vec/exec/vexchange_node.cpp:101
12:56:30   16# doris::ExecNode::pull(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /root/doris/be/src/exec/exec_node.h:127
12:56:30   17# std::_Function_handler<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*), std::_Bind<doris::Status (doris::ExecNode::*(doris::vectorized::VExchangeNode*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>))(doris::RuntimeState*, doris::vectorized::Block*, bool*)> >::_M_invoke(std::_Any_data const&, doris::RuntimeState*&&, doris::vectorized::Block*&&, bool*&&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
12:56:30   18# doris::ExecNode::get_next_after_projects(doris::RuntimeState*, doris::vectorized::Block*, bool*, std::function<doris::Status (doris::RuntimeState*, doris::vectorized::Block*, bool*)> const&, bool) at /root/doris/be/src/exec/exec_node.cpp:584
12:56:30   19# doris::pipeline::SourceOperator<doris::pipeline::ExchangeSourceOperatorBuilder>::get_block(doris::RuntimeState*, doris::vectorized::Block*, doris::pipeline::SourceState&) at /root/doris/be/src/pipeline/exec/operator.h:390
12:56:30   20# doris::pipeline::PipelineTask::execute(bool*) in /mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be
12:56:30   21# doris::pipeline::TaskScheduler::_do_work(unsigned long) at /root/doris/be/src/pipeline/task_scheduler.cpp:275
12:56:30   22# doris::ThreadPool::dispatch_thread() at /root/doris/be/src/util/threadpool.cpp:539
12:56:30   23# doris::Thread::supervise_thread(void*) at /root/doris/be/src/util/thread.cpp:466
12:56:30   24# start_thread at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:478
12:56:30   25# __clone at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.7 seconds
 stream load tsv:          542 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162136496 Bytes

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run ckbench

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
