### PR TITLE
[enhancement][diagnostics] Add a diagnostic: detect unused includes

### LINKED ISSUE #9116: [Enhancement] [diagnostics] Use clangd to detect unused includes.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

The latest version of clangd (14.0.0) has a feature to detect unused includes. We can optimize includes by using it.

### Solution

Add the config file `.clangd` and turn on diagnostics.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #9116 

## Problem Summary:

Please refer to #9116 

## Checklist(Required)

1. Does it affect the original behavior: No
3. Has unit tests been added: No Need
4. Has document been added or modified: No Need
5. Does it need to update dependencies: No
6. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
License Check / License Check (pull_request) Failing.

Maybe solution.
- New file need header.
- Rebase

**Comment by adonis0147** [comment]
License was added.

**Comment by adonis0147** [comment]
@morningman PTAL, when you are free.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
