### PR TITLE
[fix](load) fix cancel load failed because Job could not be cancelled…

### PR DESCRIPTION
**Pull request by mymeiyi**
… when job is finished or cancelled

# Proposed changes

Issue Number: close #xxx

## Problem summary

Label can be reused if the previous load is failed. But when cancel a retry load, I got the following error:

```
mysql> cancel load where label = 'load_l2';
ERROR 1105 (HY000): errCode = 2, detailMessage = Cancel load job [49114] fail, label=[load_l2] failed msg=errCode = 2, detailMessage = Job could not be cancelled when job is finished or cancelled
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by morningman** [comment]
Why change this behavior?

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.5 seconds
 stream load tsv:          532 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17161910421 Bytes

**Pull request merged**
