### PR TITLE
[improvement](regression-test)improve workload group regression stress test script

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

Improve workload group regression stress test script

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]
lgtm

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
