### PR TITLE
[chore](cloud) Add show hotspot tablet API on BE

### PR DESCRIPTION
**Pull request by gavinchou**
Usage:
* Get all tablets {metrics} with descending order `curl beip:http_port/api/hotspot/tablet?metrics={metrics}`
* Get top n tablets  {metrics} with descending order `curl beip:http_port/api/hotspot/tablet?metrics={metrics}&topn={n}`

"metrics" must be specified, which is one of
* read_block
* write
* compaction
* num_rowsets
* num_cumu_rowsets
* num_base_rowsets

Co-authored-by: plat1ko <platonekosama@gmail.com>

TODO: Add support for local mode.

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
It is better to add this API output example in the description.

**Review by Yukang-Lian — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
