### PR TITLE
[feature](statistics)Support collect external partition stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
This is the following pr of https://github.com/apache/doris/pull/34552. To support collect partition level stats for HMSExternalTable.
Also refactor analysis task code.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
