### PR TITLE
[refactor](exprcontext) move close to expr context's dector method

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes
The close method does nothing. But I am not sure we could remove it. So that I add it to dector method and remove many many calls.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
