### PR TITLE
[fix](inverted index)Remove the strong check for `parser` when creating a table with inverted index

### PR DESCRIPTION
**Pull request by qidaye**
…ng a table with inverted index

## Proposed changes

When creating a table with inverted index, the `parser` property is `none` in default.
But the index without a `parser` can also have other properties, such as `ignore_above`.
This strong check will cause table creation failure with inverted index, which `parser` is omit and have other properties.
So we remove the check here to create a table successfully.
 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run feut

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
