### PR TITLE
[bug](meta) exit when get RollbackException in observer.

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes

Issue Number: close #xxx

image
After #6582 and #17475 , fe will just resart ReplicatedEnvironment after catch RollbackException. But it may read an old edit log and ignore the new edit log from new master.
Some key logs:
**Old master**
```
2024-02-26 12:02:07,350 ERROR (stateListener|89) [Catalog$4.runOneCycle():2433] transfer FE type from MASTER to UNKNOWN. exit
2024-02-26 12:02:11,879 ERROR (timePrinter|795) [BDBJEJournal.write():157] catch an exception when writing to database. sleep and retry. journal id 195250935
```
**New master**
```
2024-02-26 12:01:47,213 INFO (stateListener|89) [Catalog$4.runOneCycle():2356] begin to transfer FE type from UNKNOWN to MASTER
2024-02-26 12:01:56,239 INFO (stateListener|89) [BDBJEJournal.rollJournal():106] roll edit log. new db name is 195250935
2024-02-26 12:01:56,275 INFO (stateListener|89) [BDBJEJournal.write():140] Write OP_MASTER_INFO_CHANGE to BDB, JournalId: 195250935
```
**Normal Follower**
```
2024-02-26 12:01:56,275 INFO (replayer|91) [Catalog.replayJournal():2460] replayed journal id is 195250934, replay to journal id is 195250935
2024-02-26 12:01:56,328 INFO (replayer|91) [EditLog.loadJournal():457] Receive OP_MASTER_INFO_CHANGE: ip: xx.xxx.xx.xx, httpPort: 8410, rpcPort: 9020
```
**Error Observer**
```
2024-02-26 12:01:57,420 INFO (replayer|91) [Catalog.replayJournal():2460] replayed journal id is 195250934, replay to journal id is 195250935
2024-02-26 12:02:07,530 WARN (replayer|91) [BDBJEJournal.getDatabaseNames():445] catch rollback log exception. will reopen the ReplicatedEnvironment.
com.sleepycat.je.rep.RollbackException: (JE 18.3.12) Environment must be closed, caused by: com.sleepycat.je.rep.RollbackException: Environment invalid because of
 previous exception: (JE 18.3.12) xx.xxx.xx.xx_9010_1696755145914(2147483647):/opt/meituan/doris-meta/bdb Node xx.xxx.xx.xx_9010_1696755145914(2147483647):/opt/me
ituan/doris-meta/bdb must rollback 2 total commits(1 of which were durable) to the earliest point indicated by transaction id=-200831693 time=2024-02-26 12:01:58.
012 vlsn=396,112,938 lsn=0x7d35/0x3b473b durable=false in order to rejoin the replication group. All existing ReplicatedEnvironment handles must be closed and rei
nstantiated.  Log files were truncated to file 0x32053, offset 0x3884641, vlsn 396,112,936 HARD_RECOVERY: Rolled back past transaction commit or abort. Must run r
ecovery by re-opening Environment handles Environment is invalid and must be closed. Environment invalid because of previous exception: (JE 18.3.12) xx.xxx.xx.xx_
9010_1696755145914(2147483647):/opt/meituan/doris-meta/bdb Node 10.221.76.23_9010_1696755145914(2147483647):/opt/meituan/doris-meta/bdb must rollback 2 total comm
its(1 of which were durable) to the earliest point indicated by transaction id=-200831693 time=2024-02-26 12:01:58.012 vlsn=396,112,938 lsn=0x7d35/0x3b473b durabl
e=false in order to rejoin the replication group. All existing ReplicatedEnvironment handles must be closed and reinstantiated.  Log files were truncated to file
0x32053, offset 0x3884641, vlsn 396,112,936 HARD_RECOVERY: Rolled back past transaction commit or abort. Must run recovery by re-opening Environment handles Envir
onment is invalid and must be closed.
        at com.sleepycat.je.rep.RollbackException.wrapSelf(RollbackException.java:146) ~[je-18.3.13-doris-SNAPSHOT.jar:18.3.13-doris-SNAPSHOT]
2024-02-26 12:02:11,897 INFO (UNKNOWN 10.221.76.23_9010_1696755145914(-1)|91) [Catalog.replayJournal():2460] replayed journal id is 195250935, replay to journal id is 195250942
```
And now, the observer will send ddl to the old master. In old master, some error logs ocurred:
```
2024-02-26 12:16:37,660 WARN (thrift-server-pool-1|241) [StmtExecutor.execute():504] execute Exception. stmt[2769, 72c0ae6e55764b5e-aa343c513756bebd], errCode = 2, detailMessage = The statement has been forwarded to master FE(xx.xxx.xx.xx) and failed to execute because Master FE is not ready. You may need to check FE's status
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liutang123** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
@liutang123 https://github.com/apache/doris/pull/28192
Can you check your version which met this problem has container this pr?

**Comment by liutang123** [comment]
> @liutang123 #28192 Can you check your version which met this problem has container this pr? the pr 28192 is for solving the problem

I took a look at #28192 and I am not sure can it resolve this case.
`isReplicaTxnAreMatched` will check the first log in a database, but the last log may not be committed to the majority.
As follows:
Old master has a databases: 1000 (1000, 1001, 1002,1003, 1004, 1005)
The old master try to commit log 1005, but only commit it to the observer.
The new master will create a database 1005(1005, ... ) and the log 1005 in this database is `OP_MASTER_INFO_CHANGE `.
In observer, log 1000 in database 1000 has been commited in majority but log 1005 may just persisted in local dist and may be read and replay?

**Review by w41ter — APPROVED** [review]

**Comment by liutang123** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
@liutang123 Can you check all RollbackException and InsufficientException and fix it?

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
