### PR TITLE
[fix](hdfs) Correct Storage Vault's key layout && Add basic multi vault case for regression-test && Meta Service's UT

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

Issue Number: close #xxx
1. correct the layout of the storage vault's key
2. add multi storage vault case
3. adjust the order of create instance to correctly add vault into instance pb
4. add multi vault ut
5. add one http action to the encoded key of storage vault

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — CHANGES_REQUESTED** [review]
missing files

**Comment by ByteYue** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
