### PR TITLE
[feature](api) add BE HTTP /api/load_streams

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Add BE HTTP API `/api/load_streams` to get all load_id for existing load_streams.

Example:

```console
$ curl http://localhost:8040/api/load_streams
{"msg":"OK","code":0,"data":{"host":"10.16.10.7","load_streams":[]},"count":0}
$ curl http://localhost:8040/api/load_streams
{"msg":"OK","code":0,"data":{"host":"10.16.10.7","load_streams":[{"load_id":"43fc5dd321f04407-96b7b2cd38323c3a"}]},"count":1}
$ curl http://localhost:8040/api/load_streams
{"msg":"OK","code":0,"data":{"host":"10.16.10.7","load_streams":[{"load_id":"02b91d709808469b-8a43d591df446353"}]},"count":1}
$ curl http://localhost:8040/api/load_streams
{"msg":"OK","code":0,"data":{"host":"10.16.10.7","load_streams":[]},"count":0}
```

```console
$ curl -s http://localhost:8040/api/load_streams | jq
{
  "msg": "OK",
  "code": 0,
  "data": {
    "host": "10.16.10.7",
    "load_streams": [
      {
        "load_id": "acdfeb53e3c34037-91fd829d1f2fe0de"
      },
      {
        "load_id": "e03742da4e5a4862-a7b0f36ad3b294c2"
      }
    ]
  },
  "count": 2
}
```

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run builldall

**Comment by morningman** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
