### PR TITLE
[Fix](auto-increment) Fix duplicate auto-increment column value problem

### PR DESCRIPTION
**Pull request by bobhan1**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
```cpp
Result<int64_t> AutoIncIDBuffer::_fetch_ids_from_fe(size_t length) {
    // ...
    return _rpc_status;
}
```
should be
```cpp
Result<int64_t> AutoIncIDBuffer::_fetch_ids_from_fe(size_t length) {
    // ...
    return ResultError(_rpc_status);
}
```
Otherwise, the returned `Result<int64_t>`'s `m_has_val` will be `true`, then `AutoIncIDBuffer::_launch_async_fetch_task()` will wrongly add an auto-increment range [0, length) to `_buffers` which will cause duplicate value problem.

### Release note

Fix duplicate auto-increment column value problem in some situations.

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by bobhan1** [comment]
run beut

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
