### PR TITLE
[fix](binlog) Fix linking binlog failure due to existing files

### PR DESCRIPTION
**Pull request by w41ter**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

If the binlog files already exist, the link file will be failed:

```
W20241212 15:56:51.084318 601741 status.h:424] meet error status: [E-242]fail to create hard link. from=/mnt/disk2/VEC_ASAN/doris.HDD/data/60/367148/684012786/020000000001570ce04a2e65a3a57b99d083b08558dfcf81_0.dat, to=/mnt/disk2/VEC_ASAN/doris.HDD/data/60/367148/684012786/_binlog/020000000001570ce04a2e65a3a57b99d083b08558dfcf81_0.dat, errno=17

        0#  doris::BetaRowset::add_to_binlog() at /home/zcp/repo_center/doris_master/doris/be/src/common/status.h:389
        1#  doris::TxnManager::publish_txn(doris::OlapMeta*, long, long, long, doris::UniqueId, doris::Version const&, doris::TabletPublishStatistics*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:0
        2#  doris::TxnManager::publish_txn(long, std::shared_ptr<doris::Tablet> const&, long, doris::Version const&, doris::TabletPublishStatistics*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:197
        3#  doris::TabletPublishTxnTask::handle() at /home/zcp/repo_center/doris_master/doris/be/src/olap/task/engine_publish_version_task.cpp:411
        4#  doris::ThreadPool::dispatch_thread() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:0
        5#  doris::Thread::supervise_thread(void*) at /var/local/ldb-toolchain/bin/../usr/include/pthread.h:562
        6#  ?
        7#  ?
```

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [x] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
