### PR TITLE
[Improvement](iceberg-catalog) Add iceberg metadata cache

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run clickbench

**Comment by Yulei-Yang** [comment]
run feut

**Pull request merged**
