### PR TITLE
[Fix](MemtableMemoryLimiter) Fix memtable memory limiter tigger flush log

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Fix memtable memory limiter tigger flush log, "reached the load hard limit" is error.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
