### PR TITLE
[Bug](function) fix explode_json_array_int can't handle min/max values

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
the json str get value maybe beyond max/min of Int64,
so add some check to limit the value, and return the max/min of Int64

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
better also add some hint in docs.

**Comment by zhangstar333** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
