### PR TITLE
[fix](test-case) fix unstable test case about table_options sys table

### PR DESCRIPTION
**Pull request by morningman**
Some regression test env use 3 replicas, some use 1 replicas.
So do not query "default.replication_allocation", because the result is uncertain

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by Vallishp — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
