### PR TITLE
[Improvement](multi catalog)Support Iceberg, Paimon and MaxCompute table in nereids.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add Iceberg external table, Paimon external table and Max compute external table support in Nereids getLogicalPlan function to support these tables in nereids planner.

Paimon:
```
mysql> select * from ads_mk_grouping_friend limit 10;
+------------+------+------+------+------+------+----------+------------+
| company_id | dr   | cid  | uid  | op   | ts   | flink_ts | flink_time |
+------------+------+------+------+------+------+----------+------------+
| a          |    1 | b    | c    | d    |    2 |        3 | e          |
+------------+------+------+------+------+------+----------+------------+
1 row in set (9.35 sec)

mysql> explain select * from ads_mk_grouping_friend limit 10;
+-----------------------------------------------------+
| Explain String                                      |
+-----------------------------------------------------+
| PLAN FRAGMENT 0                                     |
|   OUTPUT EXPRS:                                     |
|     company_id[#0]                                  |
|     dr[#1]                                          |
|     cid[#2]                                         |
|     uid[#3]                                         |
|     op[#4]                                          |
|     ts[#5]                                          |
|     flink_ts[#6]                                    |
|     flink_time[#7]                                  |
|   PARTITION: UNPARTITIONED                          |
|                                                     |
|   VRESULT SINK                                      |
|                                                     |
|   1:VEXCHANGE                                       |
|      offset: 0                                      |
|      limit: 10                                      |
|                                                     |
| PLAN FRAGMENT 1                                     |
|                                                     |
|   PARTITION: RANDOM                                 |
|                                                     |
|   STREAM DATA SINK                                  |
|     EXCHANGE ID: 01                                 |
|     UNPARTITIONED                                   |
|                                                     |
|   0:VPAIMON_SCAN_NODE                               |
|      table: ads_mk_grouping_friend                  |
|      inputSplitNum=1, totalFileSize=0, scanRanges=1 |
|      partition=0/0                                  |
|      numNodes=1                                     |
|      limit: 10                                      |
+-----------------------------------------------------+
```

Max compute:
```
mysql> select * from web_site limit 2;
+-------------+------------------+--------------------+------------------+----------+------------------+-------------------+-----------+----------------+------------+---------------------------------------------------+------------------------------------------------------------------------------------------------+--------------------+----------------+----------------------------------------------------+-------------------+-----------------+-----------------+------------------+----------+-------------------+-----------+------------+---------------+----------------+--------------------+
| web_site_sk | web_site_id      | web_rec_start_date | web_rec_end_date | web_name | web_open_date_sk | web_close_date_sk | web_class | web_manager    | web_mkt_id | web_mkt_class                                     | web_mkt_desc                                                                                   | web_market_manager | web_company_id | web_company_name                                   | web_street_number | web_street_name | web_street_type | web_suite_number | web_city | web_county        | web_state | web_zip    | web_country   | web_gmt_offset | web_tax_percentage |
+-------------+------------------+--------------------+------------------+----------+------------------+-------------------+-----------+----------------+------------+---------------------------------------------------+------------------------------------------------------------------------------------------------+--------------------+----------------+----------------------------------------------------+-------------------+-----------------+-----------------+------------------+----------+-------------------+-----------+------------+---------------+----------------+--------------------+
|          26 | AAAAAAAAKBAAAAAA | 1997-08-16         | 2000-08-15       | site_4   |          2450594 |           2446944 | Unknown   | William Carter |          2 | Also difficult women relax. Raw solutions exclude | Often well-known police can hand acres. Healthy, sensible problems make more silent recordings | Keith Williams     |              2 | able                                               | 892               | Cedar North     | Drive           | Suite 280        | Midway   | Williamson County | TN        | 31904      | United States |           NULL |               NULL |
|          27 | AAAAAAAAKBAAAAAA | 2000-08-16         | NULL             | site_4   |          2450594 |           2446944 | Unknown   | William Carter |          2 | Also difficult women relax. Raw solutions exclude | Often well-known police can hand acres. Healthy, sensible problems make more silent recordings | John Isaacs        |              5 | able                                               | 892               | Spruce          | Wy              | Suite 200        | Fairview | Williamson County | TN        | 35709      | United States |           NULL |               NULL |
+-------------+------------------+--------------------+------------------+----------+------------------+-------------------+-----------+----------------+------------+---------------------------------------------------+------------------------------------------------------------------------------------------------+--------------------+----------------+----------------------------------------------------+-------------------+-----------------+-----------------+------------------+----------+-------------------+-----------+------------+---------------+----------------+--------------------+
2 rows in set (2.83 sec)

mysql> explain select * from web_site limit 2;
+------------------------------------------------------+
| Explain String                                       |
+------------------------------------------------------+
| PLAN FRAGMENT 0                                      |
|   OUTPUT EXPRS:                                      |
|     web_site_sk[#0]                                  |
|     web_site_id[#1]                                  |
|     web_rec_start_date[#2]                           |
|     web_rec_end_date[#3]                             |
|     web_name[#4]                                     |
|     web_open_date_sk[#5]                             |
|     web_close_date_sk[#6]                            |
|     web_class[#7]                                    |
|     web_manager[#8]                                  |
|     web_mkt_id[#9]                                   |
|     web_mkt_class[#10]                               |
|     web_mkt_desc[#11]                                |
|     web_market_manager[#12]                          |
|     web_company_id[#13]                              |
|     web_company_name[#14]                            |
|     web_street_number[#15]                           |
|     web_street_name[#16]                             |
|     web_street_type[#17]                             |
|     web_suite_number[#18]                            |
|     web_city[#19]                                    |
|     web_county[#20]                                  |
|     web_state[#21]                                   |
|     web_zip[#22]                                     |
|     web_country[#23]                                 |
|     web_gmt_offset[#24]                              |
|     web_tax_percentage[#25]                          |
|   PARTITION: UNPARTITIONED                           |
|                                                      |
|   VRESULT SINK                                       |
|                                                      |
|   1:VEXCHANGE                                        |
|      offset: 0                                       |
|      limit: 2                                        |
|                                                      |
| PLAN FRAGMENT 1                                      |
|                                                      |
|   PARTITION: RANDOM                                  |
|                                                      |
|   STREAM DATA SINK                                   |
|     EXCHANGE ID: 01                                  |
|     UNPARTITIONED                                    |
|                                                      |
|   0:VMCScanNode                                      |
|      table: web_site                                 |
|      inputSplitNum=1, totalFileSize=32, scanRanges=1 |
|      partition=0/0                                   |
|      numNodes=1                                      |
|      limit: 2                                        |
+------------------------------------------------------+
50 rows in set (1.16 sec)
```

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by wsjz — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.05 seconds
 stream load tsv:          504 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17167706507 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
