### PR TITLE
[fix](Nereids) Fixed a bug where the execution plan was incorrect aft…

### LINKED ISSUE #29987: [Bug] Aggregation functions may have bugs
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.3-rc06-37d31a5

### What's Wrong?

The result of the aggregation function is incorrect

image

### What You Expected?

The first ten rows in the result should be aggregated into one row

### How to Reproduce?

table shema
[select.txt](https://github.com/apache/doris/files/13936825/select.txt)

### Anything Else?

Is it related to inserting some data, such as "7'/**/and(select'1'from/**/pg_sl"?

or The reason for the special character ?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xingyingone**
Fixed a bug where the execution plan was incorrect after ddl

## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/29987

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run P0 Regression

**Review by morrySnow — COMMENTED** [review]
add regression test or ut please

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
