### PR TITLE
[Improvement](set) enable admin_set_frontend_config can apply to all fe

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

bp: #34685 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
rerun p0

**Comment by Yulei-Yang** [comment]
rerun p0

**Comment by Yulei-Yang** [comment]
rerun p0

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
