### PR TITLE
[fix](profile) Fix regresstion s3_load_profile_test case.

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
