### PR TITLE
[feature](Nereids) graphSimplifier should compare `edge1BeforeEdge2` and `edge2BeforeEdge1`

### PR DESCRIPTION
**Pull request by keanji-x**
## Proposed changes

graphSimplifier should compare edge1BeforeEdge2 and edge2BeforeEdge1

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by jackwener — APPROVED** [review]

**Pull request merged**
