### PR TITLE
[fix](query-cache) fix query cache with empty set

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

If the query result set is empty, the query cache will not cache the result.
This PR fix it.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by dutyu — APPROVED** [review]
LGTM

**Pull request merged**
