### PR TITLE
[branch-2.0](pick) support HTTP request with chunked transfer (#26520)

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
hold.

**Comment by xiaokang** [comment]
#26520

**Pull request merged**
