### PR TITLE
[feature](load) add test property 'dry_run_load' for olap table

### LINKED ISSUE #19259: [Enhancement] support creating a table with 0 replicas
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We need a table without data in two scenarios.

1. when investigating performance issues of loads. e.g. I want to know performance except sink.
2. keep materialized views while do not keep data in a duplicate table.

### Solution

- [ ] supporting a table with 0 replica in FE.
- [ ] do not sink to a table with 0 replica in vtablet_sink, e.g. just returns OK in VtabletSink::send
- [ ] add regression test case for 2 cases in description above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
add table property 'dry_run_load', and this table will not save data really, and will return ok when sink table.

for some test case.

Issue Number: close #19259

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by morningman** [comment]
The name `return_load_in_sink` is related to internal implementation, not suitable for a user-oriented config' name.

There are 2 issues you want to solve in #19259

1. Test load performance
    I think it is better to use a session variable or load properties for this case. You can see there a session variable `dry_run_query`, when set to true, it will run the query without return the result. It resolve the similar issue as you want to resolve.

2. For materialized view.
    This is indeed a table property. I suggest to think about new property name instead of exposing the internal implements.
    Eg: `"storage_policy" = "no_storage"`. (There is already a "storage_policy" used for cold-hot data separation, maybe we can expend it)

All in all, my opinion is that the 2 things you want to resolve are 2 different cases. Better design it carefully to avoid adding confusing properties.

**Comment by nextdreamblue** [comment]
> The name `return_load_in_sink` is related to internal implementation, not suitable for a user-oriented config' name.
> 
> There are 2 issues you want to solve in #19259
> 
> 1. Test load performance
>    I think it is better to use a session variable or load properties for this case. You can see there a session variable `dry_run_query`, when set to true, it will run the query without return the result. It resolve the similar issue as you want to resolve.
> 2. For materialized view.
>    This is indeed a table property. I suggest to think about new property name instead of exposing the internal implements.
>    Eg: `"storage_policy" = "no_storage"`. (There is already a "storage_policy" used for cold-hot data separation, maybe we can expend it)
> 
> All in all, my opinion is that the 2 things you want to resolve are 2 different cases. Better design it carefully to avoid adding confusing properties.

1. I discussed with dataroaring before that session variable may affect all users and tables, and users may not be aware of the data not being loaded in a timely manner, which may result in unexpected data loss and high risks. It is recommended to use table properties, and I will modify a user-friendly name.

2. For materialized view, i will implement it in another branch and may introduce students from Doris-future to participate. and will follow your suggestion that add a table property

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Pull request closed without merging**
