### PR TITLE
[LOG](exec) Add timer for hostname_to_ip

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

RT

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buidall

**Comment by HappenLee** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
