### PR TITLE
[fix](cloud) Disable stream load and http stream 2PC for MoW table

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run p0

**Comment by Yukang-Lian** [comment]
run external

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
