### PR TITLE
[docs](kerberos)add FAQ cases and enable krb5 debug

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

add FAQ cases
enable krb5 debug

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
Wait for docs ready

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
