### PR TITLE
[Bug](mutil-catalog) PaimonColumnValue always null

### PR DESCRIPTION
**Pull request by yuxuan-luo**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by yuxuan-luo** [comment]
run buildall

**Review by hf200012 — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Comment by yuxuan-luo** [comment]
run buildall

**Comment by yuxuan-luo** [comment]
run buildall

**Pull request merged**
