### PR TITLE
[fix](profile) task type not the same in observer and master

### PR DESCRIPTION
**Pull request by cambyzju**
Insert will forward to master.

But if we open: `enable_profile`, then we could found the task type in observer is `QUERY`
image

But in master, the task type is `LOAD`, which is very confused:
image

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run cloud_p0

**Comment by cambyzju** [comment]
run cloud_p1

**Comment by cambyzju** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run cloud_p1

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run cloud_p1

**Comment by cambyzju** [comment]
run performance

**Review by xy720 — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run performance

**Pull request merged**
