### PR TITLE
[fix](oracle scan) Fix performance issues caused by version judgment

### PR DESCRIPTION
**Pull request by zy-kkk**

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — DISMISSED** [review]

**Review by wuwenchi — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Pull request merged**
