### PR TITLE
[fix](audit) fix duplicate audit log.

### LINKED ISSUE #14245: [Bug] Some duplicated audit logs occur when submit multiple statements at a time.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.2rc05

### What's Wrong?

When i use mysql-connector-java to submit multiple statements, i found that some audit logs are dumplicated.
image

### What You Expected?

When use submit multiple statements at a time, we should split these stmt and audit them one by one.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dutyu**
[fix](audit) fix duplicate audit log.

# Proposed changes

Issue Number: close #14245

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
Hi, this PR is try to fix a problem in audit with multiple statements. however, u change the parser of nereids, the new optimizer of Doris. so u use 1.1.2 with Nereids switch on and found this problem?

**Comment by dutyu** [comment]
> Hi, this PR is try to fix a problem in audit with multiple statements. however, u change the parser of nereids, the new optimizer of Doris. so u use 1.1.2 with Nereids switch on and found this problem?

I found the problem in doris 1.1.2 (without Nereids), but i've read the source code on master, 1.1.2rc05 and 1.1.3rc02, this problem must occurs on all of the versions. Maybe i need to recurrence this problem by using master branch. I will give you a feedback when i've test this scene on master branch.

**Comment by dutyu** [comment]
> if DorisSqlSeparator.g4 is not apart of Nereids, i suggest to move this file to `fe/fe-core/src/main/antlr4/org/apache/doris/parser` and move code about parser from `NereidsParser.java` to new file in `org.apache.doris.parser`. btw, maybe the better way to do this, is to save the origin stmt string in `StatementBase` when we parse sql using `sql_parser.cup`.

Thanks for you suggestion, i will move it. Maybe community plans to use antlr4 to replace cup ( i am not sure ), it is a appropriate way to fix this issue by using antlr4, i've considered using the `text` field of `singleStatementContext`( in DorisParser.g4 ), but it does't contains any whitespace.

**Comment by dutyu** [comment]
> if DorisSqlSeparator.g4 is not apart of Nereids, i suggest to move this file to `fe/fe-core/src/main/antlr4/org/apache/doris/parser` and move code about parser from `NereidsParser.java` to new file in `org.apache.doris.parser`. btw, maybe the better way to do this, is to save the origin stmt string in `StatementBase` when we parse sql using `sql_parser.cup`.

I've moved relevant code, would be grateful if you spend some time to review it.

**Review by morrySnow — DISMISSED** [review]

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
