### PR TITLE
[only test] "[refactor](nereids)unify outputTupleDesc and projection "

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

This [PR](https://github.com/apache/doris/pull/32128) involves refactoring the projection in the join node. It is used for testing the compatibility between higher version BE and lower version FE.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Pull request closed without merging**
