### PR TITLE
[fix](cluster key) some data type is not supported for cluster key

### PR DESCRIPTION
**Pull request by mymeiyi**
1. some data type is not supported for key column, it's the same for cluster key column
2. modify some cluster key cases as the mow cases

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run cloud_p1

**Comment by mymeiyi** [comment]
run performance

**Comment by mymeiyi** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
