### PR TITLE
[improvement](statistics)User admin instead of root to run stats sql.

### PR DESCRIPTION
**Pull request by Jibing-Li**
User admin instead of root to run stats sql.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
