### PR TITLE
[opt](partial update) Allow to only specify key columns in partial update

### PR DESCRIPTION
**Pull request by bobhan1**
branch-2.1-pick: https://github.com/apache/doris/pull/40863
branch-2.0-pick: https://github.com/apache/doris/pull/40864

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
