### PR TITLE
[enhancement] Optimize the log content to make the meaning clearer

### PR DESCRIPTION
**Pull request by chenlinzhong**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:
log conent message is wrong  not report to master ,but refresh storage policy from master FE 

before
image

after 

image

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by kpfly — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
hi @chenlinzhong , it has been fixed in #11123.
And it also fixed some other problem.

**Comment by chenlinzhong** [comment]
> hi @chenlinzhong , it has been fixed in #11123. And it also fixed some other problem.

log content is wrong, the action is "refresh the storage policy" not  "report to master"

**Review by morningman — APPROVED** [review]
lgtm

**Pull request merged**
