### PR TITLE
[bug](expr)fix operator do_projections should use local_state intermediate_projections

### PR DESCRIPTION
**Pull request by zhangstar333**
should use local_state->_intermediate_projections, this is clone from parent intermediate_projections.
So it can run independently between different instance operators without affecting each other。
It needs to run in some extreme multi-threaded environments, so it's not easy to add test cases.

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by HappenLee** [comment]
Add TEST and DESC of the PR

**Comment by zhangstar333** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
