### PR TITLE
[env](compile) enable the -Wshadow compiler option.

### PR DESCRIPTION
**Pull request by Mryange**
### What problem does this PR solve?

In the past, Doris had enabled -Wshadow-field, which is a subset of -Wshadow.
Therefore, we added -Wshadow in common/compile_check_begin.h and will gradually enable it.

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [x] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by Mryange** [comment]
run p0

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
