### PR TITLE
[Fix](inverted index) fix memory leak for index compaction

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

Need to delete source directory and dest directory when doing index compaction

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Comment by qidaye** [comment]
run p0

**Pull request merged**
