### PR TITLE
[fix](txn insert) Fix txn insert connect to observer fe in cloud mode

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

For txn insert, if connect to observer fe, the sql is forward to master fe, but the txn context is lost. This pr fix it.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run performance

**Comment by mymeiyi** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
