### PR TITLE
[fix](inverted index) fix match_phrase_edge query result error

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. The result of match_phrase_ edge query for a single word is incorrect

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Review by xiaokang — COMMENTED** [review]
add testcase

**Review by xiaokang — COMMENTED** [review]
pls add testcase

**Comment by zzzxl1993** [comment]
run buildall

**Review by qidaye — APPROVED** [review]

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
