### PR TITLE
[feature](Nereids) support agg state type in create table

### PR DESCRIPTION
**Pull request by morrySnow**
this PR introduce a behavior change, syntax of create table with agg_state type is changed.

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
