### PR TITLE
[Feature](docker) implementation Doris on K8S

### LINKED ISSUE #7587: [Roadmap] Doris on K8S
root issue

### PR DESCRIPTION
**Pull request by Kyofin**
# Proposed changes

Issue Number: close  #7587

## Problem summary

implementation Doris on K8S

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
hi @huzk8 , thanks for your contribution.
Could you please add a document to explain more details about this feature?
Like how it work, how to use it, how to scale up, etc?

**Comment by haydenflinner** [comment]
any news on this?

**Comment by Raven888888** [comment]
Any news?

**Comment by taptao** [comment]
@Kyofin Are you having any problems? What can I do, I'm very interested in this

**Comment by SuperEdison** [comment]
any wrong? let doris support be deployed by Helm,plssssssss

**Comment by Raven888888** [comment]
Closed?

**Pull request closed without merging**
