### PR TITLE
[enhance](privilege)Grant check name

### PR DESCRIPTION
**Pull request by zddr**
grant stmt check ctl/db/table if exist

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
