### PR TITLE
[fix](is_exclusive) fix is_exlusive func for nested types 

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
backport: https://github.com/apache/doris/pull/40398
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p0

**Review by xiaokang — CHANGES_REQUESTED** [review]
please add testcase

**Comment by amorynan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
