### PR TITLE
[fix](regression)Fix external table cardinality case.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Fix external table cardinality case.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by englefly** [comment]
this case alwasy success

**Review by englefly — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Review by morningman — APPROVED** [review]

**Pull request merged**
