### PR TITLE
[Enhancement](binlog) Add create/drop table, add/drop paritition && alter job, modify columns binlog support

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add create/drop table, add/drop paritition && alter job, modify columns binlog support

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deadlinefen — APPROVED** [review]
LGTM

**Pull request merged**
