### PR TITLE
[typo](docs) fix insert load doc error

### LINKED ISSUE #18770: [Bug] 中文文档有一处小语病
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

版本1.2.3-rc2

查看"使用 Insert 方式同步数据" 时 https://doris.apache.org/zh-CN/docs/dev/data-operate/import/import-scenes/jdbc-load?_highlight=jdbc#jdbc-%E7%A4%BA%E4%BE%8B

### What's Wrong?

,发现这个句子有语病
image

### What You Expected?

请改正

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liujiwen-up**
# Proposed changes

Issue Number: close #18770

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — COMMENTED** [review]
Whether to modify the English document at the same time. And change the PR title,like : `[typo](docs)` fix insert load doc error

**Comment by liujiwen-up** [comment]
> Whether to modify the English document at the same time. And change the PR title,like : [typo](docs) fix insert load doc error



> Whether to modify the English document at the same time. And change the PR title,like : [typo](docs) fix insert load doc error

English without error

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
