### PR TITLE
[Fix](Column) refactor ColumnNullable to provide flags safety

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

In this pr we move null_map and relative flags to an individual base class to constrain its visibility. 
please reed the comment carefully

test in master:
```
xxx/column_nullable_test.cpp:187: Failure
Value of: null_dst->has_null()
  Actual: false
Expected: true

Error occurred in case0
[  FAILED  ] ColumnNullableTest.PredicateTest (0 ms)
[ RUN      ] ColumnNullableTest.HashTest
[       OK ] ColumnNullableTest.HashTest (0 ms)
[----------] 3 tests from ColumnNullableTest (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ColumnNullableTest.PredicateTest
```

and success after this pr

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Comment by zclllyybb** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
