### PR TITLE
[fix](pipelineX) add table sink and some fix in pipelineX

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

do pipelineX = true in this pr 
https://github.com/apache/doris/pull/25303

and 

https://github.com/apache/doris/pull/25315

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run p0

**Comment by Mryange** [comment]
run p0

**Pull request merged**
