### PR TITLE
[enhance](boot) Limit the concurrency of load data dirs

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Limit the concurrency of load data dirs, which can reduce memory usage during BE boot up.

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
