### PR TITLE
[fix](timeout) unify query_timeout, use setting from user property first

### PR DESCRIPTION
**Pull request by Yulei-Yang**

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]

**Comment by liutang123** [comment]
run compile

**Review by liutang123 — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run compile

**Pull request merged**
