### PR TITLE
[fix](jni) fix jni_reader function name get_nex_block to get_next_block

### PR DESCRIPTION
**Pull request by nanfeng1999**
## Proposed changes

Issue Number: close #xxx

fix jni_reader function name get_nex_block to get_next_block

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nanfeng1999** [comment]
run buildadd

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
