### PR TITLE
[Opt] Hyperloglog _registers use chunk allocator for better memory usage

### PR DESCRIPTION
**Pull request by zbtzbtzbt**
# Proposed changes

Issue Number: https://github.com/apache/incubator-doris/issues/9194

## Problem Summary:
after pr https://github.com/apache/incubator-doris/pull/8829 , Hyperloglog still have some room for improvement
via perf, I find this `init` function cost so much CPU time
https://github.com/apache/incubator-doris/blob/4e1b75f5e79b90593b2a29e9918ed5bbfffdf117/be/src/olap/aggregate_func.h#L490-L510

hll

After discussion with @xinyiZzz @wangbo
**we can use chunk alloctor rather than `new` to require memory**, which is a better memory usage way

@xinyiZzz cc thanks

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangshuo128** [comment]
Do we have any numbers with memory usage before and after the PR?
In addition, any performance effects with the optimization?

**Comment by zbtzbtzbt** [comment]
> Do we have any numbers with memory usage before and after the PR? In addition, any performance effects with the optimization?

I'll add a test report in a few days

**Comment by xinyiZzz** [comment]
LGTM, looking forward to your test report.

**Comment by zbtzbtzbt** [comment]
> Do we have any numbers with memory usage before and after the PR? In addition, any performance effects with the optimization?

added one, there dose some improvement

**Review by jackwener — COMMENTED** [review]
Please rebase the master for fixing UT/.. CI

**Pull request closed without merging**
