### PR TITLE
[test](mtmv) Auto calc the value of sync_cbo_rewrite variable to makesure the same test code in different version

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes

Auto calc the value of sync_cbo_rewrite variable to make sure the same test code in different version.
Because the query rewrite by mv code is a little different from 2.1 to 3.0 and master.
But should keep same regression test code in different version. 
So add the methoed `enable_sync_mv_cost_based_rewrite` to  get `enable_sync_mv_cost_based_rewrite`  session variable, then decide to regression test logic by the  variable auto.

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by zfr9527 — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
