### PR TITLE
[Regression test]Add some partition test for streamload 2pc regression test

### PR DESCRIPTION
**Pull request by 133tosakarin**
this pr covers some test cases for range, list, dynamic partition, and some test for agg, mow, uniq, and dup tables

### CODE REVIEW

**Comment by 133tosakarin** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by 133tosakarin** [comment]
run buildall

**Comment by 133tosakarin** [comment]
run buildall

**Comment by 133tosakarin** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
