### PR TITLE
[enhance](auth)Abstract authentication interface

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Optimize authentication logic to facilitate the expansion of new authentication methods

Adding a new authentication method only requires implementing a new class inheriting the Authenticator and adding a new enumeration value in AuthenticateType

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
