### PR TITLE
[fix](hive) support null_format and escape_char for hive text

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
related pr: https://github.com/apache/doris/pull/39700
support escape.delim and serialization.null.format for hive text

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
