### PR TITLE
[feature](docker) regression test support run suite in docker

### PR DESCRIPTION
**Pull request by yujun777**
Support run regress test suites in docker.  Each suite can setup multiple docker clusters and execute sql commands inside the docker. Each docker is a independent env,  it will not affect other suites. Then we can add complicated test suites,  like  add/remove/start/stop/restart backends.

example usage:

```
suite("test_chaos_example") {
    // This is a docker
    docker {
        sql """create table tb1 (k int) DISTRIBUTED BY HASH(k) BUCKETS 10"""
        sql """insert into tb1 values (1),(2),(3)"""

        cluster.checkBeIsAlive(2, true)

        // stop backend 2, 3
        cluster.stopBackends(2, 3)
        // wait be lost heartbeat
        Thread.sleep(6000)

        cluster.checkBeIsAlive(2, false)

        test {
            sql """insert into tb1 values (4),(5),(6)"""

            // REPLICA_FEW_ERR
            exception "errCode = 3,"
        }
    }

    // run another docker
    def options = new ClusterOptions()
    // add fe config items
    options.feConfigs = ["example_conf_k1=v1", "example_conf_k2=v2"]
    // contains 5 backends
    options.beNum = 5
    // each backend has 3 disks
    options.beDiskNum = 3
    // This is an another docker
    docker (options) {
        sql """create table tb1 (k int) DISTRIBUTED BY HASH(k) BUCKETS 10 properties ("replication_num"="5")"""
    }
}
```

To  use `docker` function in regression test,  need three steps:
1. Build doris fe and be;
2. Build a image using docker file `docker/runtime/doris-compose/Dockerfile`;
3. Special docker image  item `image` in file `regression-conf.groovy` or `regression-conf-custom.groovy`. The image is generated by step 2.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
