### PR TITLE
[regresstion][external]fix jdbc cases fail external 0809

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

Issue Number: close #xxx

fix jdbc cases fail external, mysql,pg,clickhouse,doris,oracle,sqlserver

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run  p0

**Comment by zhangguoqiang666** [comment]
run compile

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run compile

**Comment by zhangguoqiang666** [comment]
run compile

**Comment by zhangguoqiang666** [comment]
run p0

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run compile

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
