### PR TITLE
[opt](routine-load) do not schedule task when there is no data

### LINKED ISSUE #33494: [Bug] Routine Load with kafka. No Consume when default_offset is OFFSET_END
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris: 2.0.7
kafka: 2.3.0

### What's Wrong?

1. I create a new topic with 5 partitions in kafka . At the begining, there is no data in the queue.
2. Then i create  a table and a routine load to consume the topic data. 
3. Show routine load, which shows the state is running, and the Progress is {"0":"OFFSET_END","1":"OFFSET_END","2":"OFFSET_END","3":"OFFSET_END","4":"OFFSET_END"}.
4. Push 3 msg to kafka topic, and show routine load again. The Process does't change, but the the lag of some partitions is increasing. Also clearly there isn't new data in the table. (if the default_offset is offset-end, it's normal.)
5. below is my routine load config

`            sql = "CREATE ROUTINE LOAD {} ON {} " \
                  "COLUMNS(`{}`, event_date=from_unixtime({}/1000 , '%Y%m%d')) " \
                  "PROPERTIES ( " \
                  "\"desired_concurrent_number\" = \"2\",  " \
                  "\"max_batch_interval\" = \"1\",  " \
                  "\"max_batch_rows\" = \"200000\",  " \
                  "\"max_batch_size\" = \"209715200\", " \
                  "\"max_error_number\" = \"3\", " \
                  "\"format\" = \"json\", " \
                  "\"strict_mode\" = \"false\", " \
                  "\"jsonpaths\" = \"{}\") " \
                  "FROM KAFKA (  " \
                  "\"kafka_broker_list\" = \"{}\",  " \
                  "\"kafka_topic\" = \"{}\",  " \
                  "\"property.client.id\" = \"{}\",  " \
                  "\"property.group.id\" = \"{}\")  "\`
6. what's more, when i increase the partition of an existing topic, the routine can find the new one, but the Process is also 'OFFSET_END',  and the lag is increasing when i push new msg to new partition.

### What You Expected?

the routine load can consume the data normally

### How to Reproduce?

1. I create a new topic with 5 partitions in kafka . At the begining, there is no data in the queue.
2. Then i create  a table and a routine load to consume the topic data. 
3. Show routine load, which shows the state is running, and the Progress is {"0":"OFFSET_END","1":"OFFSET_END","2":"OFFSET_END","3":"OFFSET_END","4":"OFFSET_END"}.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sollhui**
Routine load often have a large amount of concurrency executing simultaneously, do not schedule task when there is no data, allowing resources to be released in a timely manner when resources are tight.

Also fix https://github.com/apache/doris/issues/33494.

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
