### PR TITLE
[chore](dependencies)upgrade some dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run p0

**Review by morningman — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
