### PR TITLE
[test](doc) add cancel-warm-up example in doris's doc to regression test

### PR DESCRIPTION
**Pull request by freemandealer**

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Review by gavinchou — DISMISSED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
