### PR TITLE
[fix](move-memtable) close wait on all sinks

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Some per-instance data structures are now shared among all sinks due to sharing delta writers and load stream stubs.
We should let every sink to wait for the last sink, equivalent to call `close_wait` on every sinks.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
