### PR TITLE
[fix](function)revert function REPEAT nullable mode

### PR DESCRIPTION
**Pull request by koarz**
## Proposed changes

Issue Number: close #xxx

Previously, due to a mistake on my part, I changed the behaviour of the repeat function, but I didn't realise the problem
```cpp
            int repeat = 0;
            repeat = std::min<int>(repeats[i], repeat_max_num);

            if (repeat <= 0) {
                StringOP::push_empty_string(i, res_data, res_offsets);
            } else if (repeat * size > DEFAULT_MAX_STRING_SIZE) {
                StringOP::push_null_string(i, res_data, res_offsets, null_map);
            } else {
                for (int j = 0; j < repeat; ++j) {
                    buffer.append(raw_str, raw_str + size);
                }
                StringOP::push_value_string(std::string_view(buffer.data(), buffer.size()), i,
                                            res_data, res_offsets);
            }
```
You can see that in the case of repeat * size > DEFAULT_MAX_STRING_SIZE we need to output null, but due to an oversight on my part I had defaulted to repeat being less than or equal to repeat_max_num, so I removed this judgement resulting in a change in behaviour
So we need the revert function
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by koarz** [comment]
run buildall

**Comment by morrySnow** [comment]
please add some description to explain why need revert

**Comment by koarz** [comment]
> please add some description to explain why need revert

Description has been added

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — COMMENTED** [review]
Add a regression-test for > max repeat num, to make sure the behavior is stable.

**Comment by zhangstar333** [comment]
in PR https://github.com/apache/doris/pull/32219, will report error if greater than max repeat num.
could merge this pr firstly.

**Review by zhangstar333 — APPROVED** [review]

**Comment by zclllyybb** [comment]
> Add a regression-test for > max repeat num, to make sure the behavior is stable.

added in https://github.com/apache/doris/pull/32219/files. we merge both two prs

**Comment by zclllyybb** [comment]
run buildall

**Pull request merged**
