### PR TITLE
[opt](jdbc catalog) set jdbc test_connection default true

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run p0

**Review by zddr — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
