### PR TITLE
[refine](profile) format pipeline WaitForDependencyTime

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

before
```
                          EXCHANGE_OPERATOR  (id=41):
                                -  WaitForDependencyTime:  avg  0ns,  max  0ns,  min  0ns
                                    -  WaitForData0:  avg  12s120ms,  max  12s120ms,  min  12s120ms
                          AGGREGATION_OPERATOR  (id=36):
                                -  WaitForDependency[AGGREGATION_OPERATOR_DEPENDENCY]Time:  avg  12s117ms,  max  12s118ms,  min  12s117ms
```

now

```
                          EXCHANGE_OPERATOR  (id=5):
                                -  WaitForDependencyTime:  
                                    -  WaitForData0:  avg  996.715ms,  max  996.715ms,  min  996.715ms
                          AGGREGATION_OPERATOR  (id=6):
                                -  WaitForDependencyTime:  
                                    -  AGGREGATION_OPERATOR_DEPENDENCY:  avg  996.569ms,  max  996.569ms,  min  996.569ms
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run cloud_p1

**Review by Gabriel39 — APPROVED** [review]

**Pull request closed without merging**
