### PR TITLE
[fix](nereids) fix wrong resut of function ifnull/coalesce caused by mixed use multiple columns with type of datetime/datetimev2/date/datev2 of function coalesce when enable nereids

### PR DESCRIPTION
**Pull request by Yulei-Yang**
similar issue with #36640, under config:
```
admin set frontend config ("enable_date_conversion"="true");
SET enable_nereids_planner=true;
```

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by cambyzju — APPROVED** [review]

**Comment by morrySnow** [comment]
This PR modification is fine, but I don't think it can solve your problem. You need to overload the computeSignature function and use the type of the first parameter as the function signature. You can test the following case
```sql
select coalesce(dt, string, string, string, string)
```

**Comment by Yulei-Yang** [comment]
> This PR modification is fine, but I don't think it can solve your problem. You need to overload the computeSignature function and use the type of the first parameter as the function signature. You can test the following case
> 
> ```sql
> select coalesce(dt, string, string, string, string)
> ```
> 
> btw, u should fix master first, and then pick to branch-2.0 and branch-2.1

Thank you for your advice. As discussed offline, will do it later.
btw: this issue is found on a production cluster which is using v2.0, so I fix it on this version first for a immediately fix.

**Pull request merged**
