### PR TITLE
[fix](partial-update) fix update core for merge-on-write table

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

After alter table, update table will coredump.

 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/code/doris/be/src/common/signal_handler.h:413
 1# 0x00007FFA87761400 in /lib64/libc.so.6
 2# doris::TabletSchema::column(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const at /root/code/doris/be/src/olap/tablet_schema.cpp:938
 3# doris::Tablet::fetch_value_by_rowids(std::shared_ptr<doris::Rowset>, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&) in /root/code/doris/output/be/lib/doris_be
 4# doris::segment_v2::SegmentWriter::fill_missing_columns(std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, std::vector<bool, std::allocator<bool> > const&, bool) at /root/code/doris/be/src/olap/rowset/segment_v2/segment_writer.cpp:467
 5# doris::segment_v2::SegmentWriter::append_block_with_partial_content(doris::vectorized::Block const*, unsigned long, unsigned long) at /root/code/doris/be/src/olap/rowset/segment_v2/segment_writer.cpp:409
 6# doris::segment_v2::SegmentWriter::append_block(doris::vectorized::Block const*, unsigned long, unsigned long) at /root/code/doris/be/src/olap/rowset/segment_v2/segment_writer.cpp:526
 7# doris::BetaRowsetWriter::_add_rows(doris::vectorized::Block const*, std::unique_ptr<doris::segment_v2::SegmentWriter, std::default_delete<doris::segment_v2::SegmentWriter> >&, unsigned long, unsigned long) at /root/code/doris/be/src/olap/rowset/beta_rowset_writer.cpp:446
 8# doris::BetaRowsetWriter::_flush_single_block(doris::vectorized::Block const*, int, long*, std::shared_ptr<doris::TabletSchema>) at /root/code/doris/be/src/olap/rowset/beta_rowset_writer.cpp:540
 9# doris::BetaRowsetWriter::flush_memtable(doris::vectorized::Block*, int, long*) at /root/code/doris/be/src/olap/rowset/beta_rowset_writer.cpp:521

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.25 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          30.2 seconds inserted 10000000 Rows, about 331K ops/s
 storage size: 17162420930 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
