### PR TITLE
[Optimize] Remove deserialize check for meta serialization serialization to improve performance

### PR DESCRIPTION
**Pull request by xinghuayu007**
## Proposed changes

Tablet meta checkpoint is a operation to serialize tablet meta data and stores it into RocksDB. It is a cpu-exhausted and memory-exhausted operation. The data size of some tablet is high as 2G. In `serialize` function, the data has been deserialize to check the result, therefore it is no need to deserialize again to check  the result in function `save`. In reality, checkpoint often causes OOM.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by weizuo93** [comment]
`Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb. 
I think it may be not a good practice to remove this part of the code.

**Comment by xinghuayu007** [comment]
> `Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb.
> I think it may be not a good practice to remove this part of the code.

Yes, it is important. But it is no need to deserialize twice. In serialize() Function, it has been deserialized to check the result.

**Comment by acelyc111** [comment]
> `Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb.
> I think it may be not a good practice to remove this part of the code.

I'm confused if it is possible that `SerializeToString` successfully but `ParseFromString` failed, maybe there are some historical reason?

**Comment by caiconghui** [comment]
> > `Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb.
> > I think it may be not a good practice to remove this part of the code.
> 
> I'm confused if it is possible that `SerializeToString` successfully but `ParseFromString` failed, maybe there are some historical reason?

I think it make no sense to check that SerializeToString successfully but ParseFromString failed, because the next step is fatal error.  the result is the same as we store it to rocksdb and get it  then ParseFromString, finally fatal error.  what's more, until now, I could not see any fatal error like 'SerializeToString successfully but ParseFromString failed'， may it is a bug in older version?

I think  SerializeToString performance is very important ,which may affect many operations on tablet, like publish version etc.
So，just need to do the simple thing to SerializeToString instead of  adding ParseFromString check which would may cause poor performance

**Comment by xinghuayu007** [comment]
> > > `Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb.
> > > I think it may be not a good practice to remove this part of the code.
> > 
> > 
> > I'm confused if it is possible that `SerializeToString` successfully but `ParseFromString` failed, maybe there are some historical reason?
> 
> I think it makes no sense to check that SerializeToString successfully but ParseFromString failed, because the next step is fatal error. the result is the same as we store it to rocksdb and get it then ParseFromString, finally fatal error. what's more, until now, I could not see any fatal error like 'SerializeToString successfully but ParseFromString failed'， may it is a bug in older version?
> 
> I think SerializeToString performance is very important ,which may affect many operations on tablet, like publish version etc.
> So，just need to do the simple thing to SerializeToString instead of adding ParseFromString check which would may cause poor performance

agree!

**Comment by weizuo93** [comment]
> > `Deserialization` here may be necessary. To ensure the tablet meta that will be stored in rocksdb is no problem and can be deserialized successfully, so deserializing the `meta_binary` here before saving it into rocksdb.
> > I think it may be not a good practice to remove this part of the code.
> 
> Yes, it is important. But it is no need to deserialize twice. In serialize() Function, it has been deserialized to check the result.

Sorry, I ignored that deserialization has been verified in `serialize()`. It is OK for me.

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
