### PR TITLE
[feature](array_zip) Support array_zip function

### LINKED ISSUE #17487: [Feature] [array function] Support array_zip function
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Combines multiple arrays into a single array.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mellorsssss**
# Proposed changes

Issue Number: close #17487

## Problem summary

Implement array_zip.

<pre>
mysql> select array_zip(array('a', 'b'), array('c', 'd'));
+---------------------------------------------+
| array_zip(array('a', 'b'), array('c', 'd')) |
+---------------------------------------------+
| [{'a', 'c'}, {'b', 'd'}]                    |
+---------------------------------------------+
1 row in set (0.00 sec)
</pre>
## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

As the support for structs in Doris is not complete, some functions have been added to compensate. Furthermore, the output scale of DateTimeV2 within the struct is incorrect and requires correction.

For example:
<pre>
mysql> select array_zip(array(cast ('2023-03-05 12:23:24.999' as datetimev2(1)),cast ('2023-03-05 15:23:23.997' as datetimev2(3))));
+----------------------------------------------------------------------------------------------------------------------+
| array_zip(array(CAST('2023-03-05 12:23:24.999' AS DATETIMEV2(1)), CAST('2023-03-05 15:23:23.997' AS DATETIMEV2(3)))) |
+----------------------------------------------------------------------------------------------------------------------+
| [{2023-03-05 12:23:24.999000}, {2023-03-05 15:23:23.997000}]                                                         |
+----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select array_zip(array(cast ('2023-03-05 12:23:24.999' as datetimev2(1)),cast ('2023-03-05 15:23:23.997' as datetimev2(2))));
+----------------------------------------------------------------------------------------------------------------------+
| array_zip(array(CAST('2023-03-05 12:23:24.999' AS DATETIMEV2(1)), CAST('2023-03-05 15:23:23.997' AS DATETIMEV2(2)))) |
+----------------------------------------------------------------------------------------------------------------------+
| [{2023-03-05 12:23:24.990000}, {2023-03-05 15:23:23.990000}]                                                         |
+----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
</pre>

### CODE REVIEW

**Comment by Mellorsssss** [comment]
run buildall

**Review by Yukang-Lian — DISMISSED** [review]
Good job! LGTM

**Comment by carlvinhust2012** [comment]
LGTM

**Comment by eldenmoon** [comment]
rebase please

**Review by eldenmoon — DISMISSED** [review]
LGTM

**Comment by Mellorsssss** [comment]
I've resolved the conflicts.

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by Mellorsssss** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.4 seconds
 stream load tsv:          468 seconds loaded 74807831229 Bytes, about 152 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230320034019_clickbench_pr_117075.html

**Comment by eldenmoon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
