### PR TITLE
[feature](merge-cloud) Rewrite code related to IOContext

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Add some cache related contexts for incoming cloud features.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
