### PR TITLE
[improve](regression case) Add more inverted index regression case

### PR DESCRIPTION
**Pull request by Tanya-W**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. add more inverted index regression case for unique mow
2. add inverted index case with different data types

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
