### PR TITLE
[fix](Nereids) support check authorization for view but skip check in the view

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

move UserAuthentication in BindRelation, support check authorization view but skip check in the view

relate pr: #23295

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Comment by 924060929** [comment]
run build all

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
