### PR TITLE
[enhancement](delete) Using insert timeout session var to control delete job timeout

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run external

**Comment by TangSiyang2001** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
