### PR TITLE
[feature](Nereids): fold Cast(s as date/datetime) on FE

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

cast("20210101" as Date) -> DateLiteral(2021, 1, 1)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by keanji-x — APPROVED** [review]

**Pull request merged**
