### PR TITLE
[fix](test) fix some some cases in cloud mode and unify waiting for

### PR DESCRIPTION
**Pull request by dataroaring**

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
