### PR TITLE
[enhance](regression-test) test alter table partition

### PR DESCRIPTION
**Pull request by cjj2010**
## Proposed changes
test_alter_table_partition
Issue Number: close #xxx

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
