### PR TITLE
secure singleton mode

### PR DESCRIPTION
**Pull request by xinghuayu007**
## Proposed changes

The class org.apache.doris.service.ExecuteEnv is not safe in multiple thread environment. This PR is to implement a secure singleton mode.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] I have create an issue on #ISSUE, and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WingsGo** [comment]
Maybe you can reference the implement in `Catalog.SingletonHoder` to get a thread-safe singleton without lock it.

**Comment by xinghuayu007** [comment]
> Maybe you can reference the implement in `Catalog.SingletonHoder` to get a thread-safe singleton instread of use double check lock to implement.

good ideal!

**Review by imay — APPROVED** [review]
LGTM

**Comment by WingsGo** [comment]
Hi, @imay The code has no problem in logic, but I think sychornized will have poor performance than static method, why we keep the double check lock? Is there anything i didn't consider into account?thx~~

**Comment by caiconghui** [comment]
> Hi, @imay The code has no problem in logic, but I think sychornized will have poor performance than static method, why we keep the double check lock? Is there anything i didn't consider into account?thx~~

@WingsGo The performance is not poor, only double check in initial operation

**Comment by imay** [comment]
> Hi, @imay The code has no problem in logic, but I think sychornized will have poor performance than static method, why we keep the double check lock? Is there anything i didn't consider into account?thx~~

My opinion is the same with conghui's.

**Comment by WingsGo** [comment]
@caiconghui , @imay The PR look good to me, but I still think the static method's implement is more elegant and less error-prone

**Comment by morningman** [comment]
I have not tested the efficiency issue, but I think that it is better to keep the singleton implementation consistent in a system.
Both should be OK, but should choose one and only use one.

**Pull request merged**
