### PR TITLE
[fix](regression test) fix test_decommission_with_replica_num_fail due to set force_olap_table_replication_num

### PR DESCRIPTION
**Pull request by yujun777**
BUG: The test pipeline set force_olap_table_replication_num  = 3,  but has 4 backends. Then decommission will not throw exception.  So we need to modify partition's replication num to 4.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
