### PR TITLE
[Bug](DECIMALV3) Fix wrong precision for plus/minus

### PR DESCRIPTION
**Pull request by Gabriel39**
# Proposed changes

Result type for DECIMAL(x, y) plus/minus DECIMAL(m, n) should be  DECIMAL(max(x - y, m - n) + max(y + n) + 1, max(y + n))

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by HappenLee** [comment]
Revise the doc of the precision change

**Comment by Gabriel39** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
