### PR TITLE
[improvement](query) prefer to chose tablet on alive disk

### PR DESCRIPTION
**Pull request by yujun777**
improvement:
1.  when query, prefer to chose tablets on alive disks;
2.  when be report tablets,  if report version fall behind, try report again;
3.  when be restart,  it report its tablets and disks immedidately, no wait 1min;
4.  when fe handle tablet report, even if this report is stale, but if there exists other health tablets and this tablet is on bad disk,  still process this tablet;

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run performance

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run performance

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
