### PR TITLE
[fix](metadata)Add FE metadata-related file checks

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
need more test

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run cloud_p0

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
