### PR TITLE
[Chore](cmake) Refactor thirdparty.cmake by add_thirdparty function

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Refactor thirdparty.cmake by add_thirdparty function

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Review by zy-kkk — DISMISSED** [review]

**Comment by JackDrogon** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.88 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         32 seconds loaded 2358488459 Bytes, about 70 MB/s
 stream load orc:          69 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162094878 Bytes

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
