### PR TITLE
[improvement](statistics)Improve statisitcs insert into audit log.

### PR DESCRIPTION
**Pull request by Jibing-Li**
The audit log for statistics insert sql was like:
Stmt=OriginStatement{originStmt='INSERT INTO internal.__internal_schema.column_statistics VALUES...}

Remove the "OriginStatement{originStmt" part, and change it to:
Stmt=INSERT INTO internal.__internal_schema.column_statistics VALUES..

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Pull request merged**
