### PR TITLE
Finish schema change after try three times

### PR DESCRIPTION
**Pull request by WingsGo**
#2410

### CODE REVIEW

**Review by morningman — CHANGES_REQUESTED** [review]
You'd better not deal with AlterJob's error logic here, as this will lead to a messy code structure.
Here is my advise:
1. In `MasterImpl.java`
    You will find a comment `// We start to let FE perceive the task's error msg`. And you should add
    "&& taskType != TTaskType.ALTER" in the following `if` clause. So that even this is a failure task
    report, it can still be passed to `finishAlterTask()`.

2. In `finishAlterTask()`
     We are currently only dealing with successful tasks here, and you need to modify this method to 
    also deal with the failed task. And you can just set some error msgs of failure counter into the 
    agent task. And no need to get the AlterJob.

3. In `RollupJobV2` and `SchemaChangeJobV2`

    Both `RollupJobV2` and `SchemaChangeJobV2` have method `runRunningJob()`. In this method,
    you can check the tasks' status in `rollupBatchTask` or `schemaChangeBatchTask`. The tasks here 
    are same as you got in `finishAlterTask()`. And if you find that some of tasks are failed more than 3
    times. you can just throw an `AlterCancelException`, so that the job will be cancelled automatically.

**Comment by WingsGo** [comment]
> You'd better not deal with AlterJob's error logic here, as this will lead to a messy code structure.
> Here is my advise:
> 
> 1. In `MasterImpl.java`
>    You will find a comment `// We start to let FE perceive the task's error msg`. And you should add
>    "&& taskType != TTaskType.ALTER" in the following `if` clause. So that even this is a failure task
>    report, it can still be passed to `finishAlterTask()`.
> 2. In `finishAlterTask()`
>    We are currently only dealing with successful tasks here, and you need to modify this method to
>    also deal with the failed task. And you can just set some error msgs of failure counter into the
>    agent task. And no need to get the AlterJob.
> 3. In `RollupJobV2` and `SchemaChangeJobV2`
>    Both `RollupJobV2` and `SchemaChangeJobV2` have method `runRunningJob()`. In this method,
>    you can check the tasks' status in `rollupBatchTask` or `schemaChangeBatchTask`. The tasks here
>    are same as you got in `finishAlterTask()`. And if you find that some of tasks are failed more than 3
>    times. you can just throw an `AlterCancelException`, so that the job will be cancelled automatically.

I think the error msgs of failure counter have been record in following, so I think I only need to change SchemaChangeJobV2 and RollupJobV2.
```
if (taskStatus.getStatus_code() != TStatusCode.OK) {
                task.failed();
                // We start to let FE perceive the task's error msg
}
```

**Comment by morningman** [comment]
> > You'd better not deal with AlterJob's error logic here, as this will lead to a messy code structure.
> > Here is my advise:
> > 
> > 1. In `MasterImpl.java`
> >    You will find a comment `// We start to let FE perceive the task's error msg`. And you should add
> >    "&& taskType != TTaskType.ALTER" in the following `if` clause. So that even this is a failure task
> >    report, it can still be passed to `finishAlterTask()`.
> > 2. In `finishAlterTask()`
> >    We are currently only dealing with successful tasks here, and you need to modify this method to
> >    also deal with the failed task. And you can just set some error msgs of failure counter into the
> >    agent task. And no need to get the AlterJob.
> > 3. In `RollupJobV2` and `SchemaChangeJobV2`
> >    Both `RollupJobV2` and `SchemaChangeJobV2` have method `runRunningJob()`. In this method,
> >    you can check the tasks' status in `rollupBatchTask` or `schemaChangeBatchTask`. The tasks here
> >    are same as you got in `finishAlterTask()`. And if you find that some of tasks are failed more than 3
> >    times. you can just throw an `AlterCancelException`, so that the job will be cancelled automatically.
> 
> I think the error msgs of failure counter have been record in following, so I think I only need to change SchemaChangeJobV2 and RollupJobV2.
> 
> ```
> if (taskStatus.getStatus_code() != TStatusCode.OK) {
>                 task.failed();
>                 // We start to let FE perceive the task's error msg
> }
> ```

Yes you are right. But this only count the error, no error msg left. Maybe you can optimize it.

**Comment by WingsGo** [comment]
> > > You'd better not deal with AlterJob's error logic here, as this will lead to a messy code structure.
> > > Here is my advise:
> > > 
> > > 1. In `MasterImpl.java`
> > >    You will find a comment `// We start to let FE perceive the task's error msg`. And you should add
> > >    "&& taskType != TTaskType.ALTER" in the following `if` clause. So that even this is a failure task
> > >    report, it can still be passed to `finishAlterTask()`.
> > > 2. In `finishAlterTask()`
> > >    We are currently only dealing with successful tasks here, and you need to modify this method to
> > >    also deal with the failed task. And you can just set some error msgs of failure counter into the
> > >    agent task. And no need to get the AlterJob.
> > > 3. In `RollupJobV2` and `SchemaChangeJobV2`
> > >    Both `RollupJobV2` and `SchemaChangeJobV2` have method `runRunningJob()`. In this method,
> > >    you can check the tasks' status in `rollupBatchTask` or `schemaChangeBatchTask`. The tasks here
> > >    are same as you got in `finishAlterTask()`. And if you find that some of tasks are failed more than 3
> > >    times. you can just throw an `AlterCancelException`, so that the job will be cancelled automatically.
> > 
> > 
> > I think the error msgs of failure counter have been record in following, so I think I only need to change SchemaChangeJobV2 and RollupJobV2.
> > ```
> > if (taskStatus.getStatus_code() != TStatusCode.OK) {
> >                 task.failed();
> >                 // We start to let FE perceive the task's error msg
> > }
> > ```
> 
> Yes you are right. But this only count the error, no error msg left. Maybe you can optimize it.

Done

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
