### PR TITLE
[fix](tablet invert index) fix tablet invert index leaky caused by auto partition

### PR DESCRIPTION
**Pull request by yujun777**
BUG:

When creating a partition,   it will call InternalCatalog.createPartitionWithIndices  and the partition's tablet will add to tablet invert index.  And drop or discard a partition, need to clean its tablet in tablet invert index.

We found a issue oneline: user create a table with auto partition, they concurrent insert data, and then  concurrent create partitions with the same partition name.  Then the later created partition will raise exists partition eror.  But it forget to clear the related tablets in tablet invert index.  

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by yujun777** [comment]
run external

**Comment by yujun777** [comment]
run external

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
