### PR TITLE
[Config]Allower use to config different thrift server model

### PR DESCRIPTION
**Pull request by WingsGo**
Doris only support TThreadPoolServer model in thrift server, but the
server model is not effective in some high concurrency scenario, so this
PR introduced new config to allower use to choose different server model
by their scenario.

### CODE REVIEW

**Comment by WingsGo** [comment]
For #3987

**Review by morningman — COMMENTED** [review]
Better to use a `string` instead of `int` type of this config.
And  TSimpleServer seems unnecessary.

**Comment by WingsGo** [comment]
> Better to use a `string` instead of `int` type of this config.
> And TSimpleServer seems unnecessary.

use string is better, but Config have no check logic, we can only set default server model when use have typo error like `Threadd`,In this case, user may think they use a `Threaded` server model, but it is not what he think, use int type is to avoid situation like this.

**Comment by morningman** [comment]
> > Better to use a `string` instead of `int` type of this config.
> > And TSimpleServer seems unnecessary.
> 
> use string is better and easy to understand, but Config have no check logic, we can only set default server model when use have typo error like `Threadd`,In this case, user may think they use a `Threaded` server model, but it is not what he think, use int type is to avoid situation like this.

Actually, the config SHOULD has a validation logic. We may add it later.
So I suggest to keep the config in a friendly way, and we can add the checking later.

**Comment by WingsGo** [comment]
> > > Better to use a `string` instead of `int` type of this config.
> > > And TSimpleServer seems unnecessary.
> > 
> > 
> > use string is better and easy to understand, but Config have no check logic, we can only set default server model when use have typo error like `Threadd`,In this case, user may think they use a `Threaded` server model, but it is not what he think, use int type is to avoid situation like this.
> 
> Actually, the config SHOULD has a validation logic. We may add it later.
> So I suggest to keep the config in a friendly way, and we can add the checking later.

It look like the best solution, done.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
