### PR TITLE
[optimization](array-type) optimize the export precision of floating point numbers

### PR DESCRIPTION
**Pull request by carlvinhust2012**
# Proposed changes
1. this pr is used to optimize the export precision of floating point numbers.
2. before the change, it will return the result that lost of precision when we import floating point numbers and use array function to query.
MySQL> select a8[1], a9[1] from array_test_table where k1 = 1;
+----------------------------+----------------------------+
| %element_extract%(`a8`, 1) | %element_extract%(`a9`, 1) |
+----------------------------+----------------------------+
|                   0.000247 |                   0.014173 |
+----------------------------+----------------------------+

3. after the change, it could return the precise result when we import floating point numbers and use array function to query.
MySQL> select a8[1], a9[1] from array_test_problem85 where k1 = 1;
+----------------------------+----------------------------+
| %element_extract%(`a8`, 1) | %element_extract%(`a9`, 1) |
+----------------------------+----------------------------+
|              0.00024716643 |            0.0141731607687 |
+----------------------------+----------------------------+

Issue Number: #7570

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
5. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
6. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
7. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
8. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.65 seconds
 load time: 435 seconds
 storage size: 17152175316 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221114151850_clickbench_pr_45804.html

**Review by morningman — COMMENTED** [review]
please add regression test for this

**Comment by carlvinhust2012** [comment]
> please add regression test for this

done

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
