### PR TITLE
[fix](action) Update pr-approve-status.yml

### PR DESCRIPTION
**Pull request by hello-stephen**
According to https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-reviews-for-a-pull-request
the number of results per page default is 30 (max 100).
review of  APPROVED after 30 will not be listed, 
#24554 met this error,
https://github.com/apache/doris/actions/runs/6794404835/job/18470763493?pr=24554
so, change to 100 to fix it.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Comment by hello-stephen** [comment]
run p0 10

**Comment by hello-stephen** [comment]
run p0 10

**Comment by hello-stephen** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
