### PR TITLE
[fix](date) fix the value may be changed during the parsing of date and datetime types

### LINKED ISSUE #11572: [Bug] the value may be changed of date and datetime types
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

mysql> select dayofweek("2022-02-30");
+----------------------------------+
| dayofweek('2022-02-28 00:00:00') |
+----------------------------------+
|                                2 |
+----------------------------------+

### What You Expected?

mysql> select dayofyear("2022-02-30");
+-------------------------+
| dayofyear('2022-02-30') |
+-------------------------+
|                    NULL |
+-------------------------+

### How to Reproduce?

mysql> select dayofweek("2022-02-30");
+----------------------------------+
| dayofweek('2022-02-28 00:00:00') |
+----------------------------------+
|                                2 |
+----------------------------------+
1 row in set (0.06 sec)

mysql> select dayofyear("2022-02-30");
+----------------------------------+
| dayofyear('2022-02-28 00:00:00') |
+----------------------------------+
|                               59 |
+----------------------------------+
1 row in set (0.06 sec)

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #11572 

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by Gabriel39** [comment]
Could you add a case in FE UT?

**Comment by luozenglin** [comment]
> Could you add a case in FE UT?

done

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
