### PR TITLE
[chore](log) fix error log not aligned

### LINKED ISSUE #24217: [Bug] The output table is not aligned
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

image

### What You Expected?

0

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
## Proposed changes

Issue Number: close #24217

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
run Check PR title

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
