### PR TITLE
[improvement](nereids) Support `* EXCEPT`, `* REPLACE` and other expressions to appear in select statement at the same time

### PR DESCRIPTION
**Pull request by liutang123**
Follow #36777

Sometimes, users want to use * EXCEPT and other expressions in select clause.
For example:
SELECT * EXCEPT (value), sum(value) FROM tbl GROUP BY 1

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
Will add ut and rt later.

**Comment by liutang123** [comment]
run buildall

**Comment by 924060929** [comment]
add test for
```sql
SELECT * EXCEPT (value), sum(value) FROM tbl GROUP BY 1
```

**Review by morrySnow — DISMISSED** [review]

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
