### PR TITLE
[BUG] fix scan range boundary handling is incorrect

### PR DESCRIPTION
**Pull request by qzsee**
## Proposed changes

sql:

``` sql

      CREATE TABLE `s1` (
        `k1` INT NULL,
        `k2` INT NULL
      ) ENGINE=OLAP
      DUPLICATE KEY(`k1`, `k2`)
      DISTRIBUTED BY HASH(`k1`) BUCKETS 1


     insert into s1 values(1,1)

```

query sql :

```sql
 
  select k1 from s1 where k1 > -2147483648  

  select k1 from s1 where k1 < 2147483647

```

The above sql query results are empty

This is caused by a problem with the processing of boundary conditions in scan range

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qzsee** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
