### PR TITLE
[Bug][Fix] pipeline exec engine get wrong result when run regression test

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Fix regression p1：regression-test/suites/datev2/tpcds_sf1_p1/sql/pipeline case

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.59 seconds
 stream load tsv:          479 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          75 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          33 seconds loaded 861443392 Bytes, about 24 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230318051342_clickbench_pr_116347.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
