### PR TITLE
[fix](regression-test) fix non stable case test_unique_table_like

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

test_unique_table.groovy and test_unique_table_like.groovy both use database test_unique_db.
If they run at the same time, we may got the following errors:
`java.sql.SQLException: errCode = 2, detailMessage = There are still some transactions in the COMMITTED state waiting to be completed. The database [default_cluster:test_unique_db] cannot be dropped. If you want to forcibly drop(cannot be recovered), please use "DROP database FORCE".`

Both **Master & Branch2.0** have this problem.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
