### PR TITLE
[opt](docs) opt doc to avoid users using port 8030 everywhere

### PR DESCRIPTION
**Pull request by zxealous**
## Proposed changes

Issue Number: close #xxx

Avoid users using port 8030 everywhere

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Comment by zxealous** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Comment by zxealous** [comment]
run external

**Comment by zxealous** [comment]
run buildall

**Comment by zxealous** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
