### PR TITLE
[fix](multi-catalog)add the FAQ for Aliyun DLF and add the fs.xx.impl check

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

1. add the FAQ for Aliyun DLF，include the DLF configuration and Jindo SDK locations
2. add the fs.xx.impl check when load cache files

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
