### PR TITLE
[Refactor](inverted index) refact tokenize function for inverted index

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx
refactor tokenize function, it is used like this
```
mysql> select tokenize("i love china","'parser'='english'");
+----------------------------------------------------+
| tokenize('i love china', '''parser''=''english''') |
+----------------------------------------------------+
| ["i", "love", "china"]                             |
+----------------------------------------------------+
1 row in set (0.02 sec)

mysql> select tokenize("我爱北京天安门","'parser'='unicode'");
+-------------------------------------------------------------+
| tokenize('我爱北京天安门', '''parser''=''unicode''')        |
+-------------------------------------------------------------+| ["我", "爱", "北", "京", "天", "安", "门"]                  |+-------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select tokenize("我爱北京天安门","'parser'='chinese'");
+-------------------------------------------------------------+
| tokenize('我爱北京天安门', '''parser''=''chinese''')        |
+-------------------------------------------------------------+
| ["爱", "北京", "天安门"]                                    |
+-------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select tokenize("我爱北京天安门","'parser'='chinese',parser_mode='fine_grained'");
+------------------------------------------------------------------------------------------+
| tokenize('我爱北京天安门', '''parser''=''chinese'',parser_mode=''fine_grained''')        |
+------------------------------------------------------------------------------------------+
| ["爱", "北京", "天安", "天安门"]                                                         |
+------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by vinlee19 — APPROVED** [review]

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.05 seconds
 stream load tsv:          512 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17166681017 Bytes

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
