### PR TITLE
[test](case) add some test case for encrypt/decrypt functions

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

add some test case for encrypt/decrypt functions

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
