### PR TITLE
[Enhancement](Show Transaction) fix show transaction issue

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

1, when use "show transaction where label="anything not exist"  in doris, we will get "ERROR 1105 (HY000): errCode = 2, detailMessage = transaction with label delete does not exist".  seems we just throw the exception.

we expect:
Empty set (0.01 sec), and log the exception with warn log.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a regression test.

**Comment by GoGoWen** [comment]
> Please add a regression test.

Done

**Comment by GoGoWen** [comment]
run buildall

**Pull request closed without merging**
