### PR TITLE
[Improvement](profile) add catalog info in profile

### PR DESCRIPTION
**Pull request by Yulei-Yang**
add catalog in load/query profile
image

        "column_names": [
            "Profile ID",
            "Task Type",
            "Start Time",
            "End Time",
            "Total",
            "Task State",
            "User",
            "Default Catalog",
            "Default Db",
            "Sql Statement"
        ],
        "rows": [
            {
                "Task Type": "QUERY",
                "User": "root",
                "Default Catalog": "internal",
                "Total": "14ms",
                "__hrefPaths": [
                    "/query_profile/727f38676ca442bb-b33a77ea8dca569d"
                ],
                "Default Db": "regression_test_query_profile",
                "Profile ID": "727f38676ca442bb-b33a77ea8dca569d",
                "Task State": "EOF",
                "Sql Statement": "select count(*) from test_profile",
                "Start Time": "2024-07-24 03:19:39",
                "End Time": "2024-07-24 03:19:39"
            },

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run cloud_p0

**Comment by Yulei-Yang** [comment]
run cloud_p0

**Comment by Yulei-Yang** [comment]
run cloud_p0

**Comment by Yulei-Yang** [comment]
run cloud_p0

**Comment by Yulei-Yang** [comment]
run cloud_p0

**Review by liutang123 — APPROVED** [review]
LGTM

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Pull request merged**
