### PR TITLE
[fix](memory) Fix PredicateColumn wrong usage after arena expansion 

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #xxx

## Problem summary

==1742140==ERROR: AddressSanitizer: use-after-poison on address 0x7f4468db9000 at pc 0x5649e97c7faa bp 0x7e48a3b59410 sp 0x7e48a3b58be0
WRITE of size 3768 at 0x7f4468db9000 thread T485 (_scanner_scan)
    #0 0x5649e97c7fa9 in __asan_memcpy (doris-master/output/be/lib/doris_be+0x131f3fa9) (BuildId: 6d58337d9dbd17ce)
    #1 0x5649ea171fec in doris::vectorized::PredicateColumnType<(doris::PrimitiveType)23>::insert_many_continuous_binary_data(char const*, unsigned int const*, unsigned long) doris-master/be/src/vec/columns/predicate_column.h:281:13
    #2 0x5649f1b20b55 in doris::vectorized::ColumnNullable::insert_many_continuous_binary_data(char const*, unsigned int const*, unsigned long) doris-master/be/src/vec/columns/column_nullable.h:135:29
    #3 0x5649eace26a7 in doris::segment_v2::BinaryPlainPageDecoder<(doris::FieldType)5>::next_batch(unsigned long*, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&) doris-master/be/src/olap/rowset/segment_v2/binary_plain_page.h:237:14
    #4 0x5649eaccbd3a in doris::segment_v2::BinaryDictPageDecoder::next_batch(unsigned long*, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&) doris-master/be/src/olap/rowset/segment_v2/binary_dict_page.cpp:239:36
    #5 0x5649eaadd64f in doris::segment_v2::FileColumnIterator::next_batch(unsigned long*, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&, bool*) doris-master/be/src/olap/rowset/segment_v2/column_reader.cpp:982:13
    #6 0x5649ead764db in doris::segment_v2::ColumnIterator::next_batch(unsigned long*, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&) doris-master/be/src/olap/rowset/segment_v2/column_reader.h:267:16

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request closed without merging**
