### PR TITLE
[fix](profile) Fix duplicated execution profile

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
When there are multiple pipelines, execution profile will have duplicated pipelines. This is because of wrong pipeline profile naming rules. 

Root reason is this pr https://github.com/apache/doris/pull/35073 did not report fragment level profile through new profile reporting channel, makes profile naming on FE in chaos

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Review by HappenLee — CHANGES_REQUESTED** [review]
Please add more desc

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
