### PR TITLE
[typo](docs) Update profile screenshot.

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Issue Number: close #xxx

I found that the screenshot in the document is still an old version, so I decided to update a new screenshot.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run p0

**Comment by luzhijing** [comment]
please rebase the code @yagagagaga

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
