### PR TITLE
[Feat](Nereids) support show authors command

### LINKED ISSUE #42735: [Enhancement] (nereids)implement showAuthorsCommand in nereids
showAuthors command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showAuthors command in nereids:
unsupportedshowAuthorsStatement
``` SHOW AUTHORS                                                                  ```

### PR DESCRIPTION
**Pull request by GentleCold**
### What problem does this PR solve?

Issue Number: close #42735

Problem Summary:

### Check List (For Committer)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by GentleCold** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]
LGTM

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
