### PR TITLE
[Impl](Nereids) add nereids gc cost time and be fold const cost time to profile (#42007)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
pick:#42007
add Nereids GarbageCollect Time and Nereids BeFoldConst Time to profile

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run feut

**Comment by LiBinfeng-01** [comment]
run external

**Review by englefly — APPROVED** [review]

**Pull request merged**
