### PR TITLE
[fix](parquet) disable parquet page index by default

### PR DESCRIPTION
**Pull request by morningman**
there are some issue with page index parsing.
disable it temporarily

### CODE REVIEW

**Review by suxiaogang223 — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
