### PR TITLE
[Fix](Job)cancel task is not cleared from running task

### PR DESCRIPTION
**Pull request by CalvinKirs**
- When canceling a task, you should also clear the task from the running task.
- When performing gson deserialization, some parameters lose their initialized values, causing inserttask to report an error.

```error.log
2023-12-26 15:41:34,318 WARN (dispatch-task-1-thread-2|136) [DispatchTaskHandler.onEvent():75] dispatch timer job error, task id is 1285139975597
java.lang.NullPointerException: null
	at org.apache.doris.job.extensions.insert.InsertJob.createTasks(InsertJob.java:224) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.job.extensions.insert.InsertJob.createTasks(InsertJob.java:84) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.job.base.AbstractJob.commonCreateTasks(AbstractJob.java:201) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.job.executor.DispatchTaskHandler.onEvent(DispatchTaskHandler.java:60) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.job.executor.DispatchTaskHandler.onEvent(DispatchTaskHandler.java:40) ~[doris-fe.jar:1.2-SNAPSHOT]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.4.jar:?]
```
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
