### PR TITLE
[fix](pipeline) no alloc_resource projections in VSetOperationNode

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

This PR https://github.com/apache/doris/pull/26673 fixed the issue where the VEXCEPT operator would improperly execute the expr if open was not correct in the past. This PR includes relevant checks and fixes the errors. It has been merged into version 2.1 but has not yet been merged into version 2.0.

Issue Number: 
https://github.com/apache/doris/issues/32848

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
