### PR TITLE
[Bug](cast) fix cast string to int return wrong result

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
cast '+','-' as int should be return NULL like other char
```
mysql [ssb]>select cast('a' as int);
+------------------+
| cast('a' as INT) |
+------------------+
|             NULL |
+------------------+
1 row in set (0.02 sec)

mysql [ssb]>select cast('/' as int);
+------------------+
| cast('/' as INT) |
+------------------+
|             NULL |
+------------------+
1 row in set (0.02 sec)

mysql [ssb]>select cast('+' as int);
+------------------+
| cast('+' as INT) |
+------------------+
|                0 |
+------------------+
1 row in set (0.02 sec)

mysql [ssb]>select cast('-' as int);
+------------------+
| cast('-' as INT) |
+------------------+
|                0 |
+------------------+
1 row in set (0.02 sec)

```

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
