### PR TITLE
[fix](regression)Disable auto analyze for related cases, do not need to enable it for pipeline test cases.

### PR DESCRIPTION
**Pull request by Jibing-Li**
For regression test, it doesn't need to enable auto analyze. Disable it in some test cases.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run cloud_p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
