### PR TITLE
[test](hive)revert hive container to host mode

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes

Revert hive container to host mode to fix pipeline problem

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run build all

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
