### PR TITLE
[feature](metacache) add system table catalog_meta_cache_statistics

### PR DESCRIPTION
**Pull request by morningman**
Add new system table `catalog_meta_cache_statistics`

```
mysql> select * from information_schema.catalog_meta_cache_statistics;
+--------------+-----------------------------+----------------------+---------------------+
| CATALOG_NAME | CACHE_NAME                  | METRIC_NAME          | METRIC_VALUE        |
+--------------+-----------------------------+----------------------+---------------------+
| hms          | hive_file_cache             | eviction_count       | 0                   |
| hms          | hive_file_cache             | hit_ratio            | 0.6                 |
| hms          | hive_file_cache             | average_load_penalty | 7.60805755E7        |
| hms          | hive_file_cache             | estimated_size       | 2                   |
| hms          | hive_file_cache             | hit_count            | 3                   |
| hms          | hive_file_cache             | read_count           | 5                   |
| hms          | hive_partition_cache        | eviction_count       | 0                   |
| hms          | hive_partition_cache        | hit_ratio            | 1.0                 |
| hms          | hive_partition_cache        | average_load_penalty | 0.0                 |
| hms          | hive_partition_cache        | estimated_size       | 0                   |
| hms          | hive_partition_cache        | hit_count            | 0                   |
| hms          | hive_partition_cache        | read_count           | 0                   |
| hms          | hive_partition_values_cache | eviction_count       | 0                   |
| hms          | hive_partition_values_cache | hit_ratio            | 1.0                 |
| hms          | hive_partition_values_cache | average_load_penalty | 0.0                 |
| hms          | hive_partition_values_cache | estimated_size       | 0                   |
| hms          | hive_partition_values_cache | hit_count            | 0                   |
| hms          | hive_partition_values_cache | read_count           | 0                   |
| hms          | hudi_partition_cache        | eviction_count       | 0                   |
| hms          | hudi_partition_cache        | hit_ratio            | 1.0                 |
| hms          | hudi_partition_cache        | average_load_penalty | 0.0                 |
| hms          | hudi_partition_cache        | estimated_size       | 0                   |
| hms          | hudi_partition_cache        | hit_count            | 0                   |
| hms          | hudi_partition_cache        | read_count           | 0                   |
| iceberg      | iceberg_table_cache         | eviction_count       | 0                   |
| iceberg      | iceberg_table_cache         | hit_ratio            | 0.07407407407407407 |
| iceberg      | iceberg_table_cache         | average_load_penalty | 1.7263263424E8      |
| iceberg      | iceberg_table_cache         | estimated_size       | 25                  |
| iceberg      | iceberg_table_cache         | hit_count            | 2                   |
| iceberg      | iceberg_table_cache         | read_count           | 27                  |
| iceberg      | iceberg_snapshot_cache      | eviction_count       | 0                   |
| iceberg      | iceberg_snapshot_cache      | hit_ratio            | 1.0                 |
| iceberg      | iceberg_snapshot_cache      | average_load_penalty | 0.0                 |
| iceberg      | iceberg_snapshot_cache      | estimated_size       | 0                   |
| iceberg      | iceberg_snapshot_cache      | hit_count            | 0                   |
| iceberg      | iceberg_snapshot_cache      | read_count           | 0                   |
+--------------+-----------------------------+----------------------+---------------------+
```

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
