### PR TITLE
[Fix]Fix cgroup v2 init

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
1 Add a step to write pid to query path's cgroup.procs, otherwrise write thread id may failed.
2 Move some cgroup v2's public file to parent class to init init them once.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
