### PR TITLE
[fix](regression) mv segcompaction_p1 to segcompaction_p2

### PR DESCRIPTION
**Pull request by freemandealer**
segcompaction_p1 contains fairly large load jobs, which will exceed memlimit or timeout in pipeline under such heavy loads. We disable this test temporarily before we figure out better method to test it.

Note that we only disable it for community pipeline -- private pipeline can still run the tests. Plus, segcompaction specific unit tests also remain enabled.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pingchunzhang** [comment]
LGTM

**Comment by freemandealer** [comment]
run buildall

**Comment by morningman** [comment]
How about move it to p2, not disable it

**Comment by dataroaring** [comment]
please move to p2.

**Comment by freemandealer** [comment]
@morningman @dataroaring  done moving to p2

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run p0, plz

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Pull request merged**
