### PR TITLE
[feature](doris compose) run docker as host user

### PR DESCRIPTION
**Pull request by yujun777**
Our workmates run doris compose on the same dev machine.  Sometimes some docker doris_be consume high cpu. We want to find out it belongs to who. But if show processes with command 'ps -elf'  on host machine,   we only find out that  its owner is root.
What a pitty. So we let doris compose docker run as host user. Then use command 'ps -elf' can known who it belongs to.

To achive this goal,  we pass host user and uid into docker container, and let container add a new user the same with it, then run command with this new account.

If user still want to run as root in container,  they need to pass options  '--root'  when creating a new doris compose cluster.

```
# run as root in container
python doris-compose.py  up   --root ...

#run as host user in container
python doris-compose.py up ...
```

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Pull request merged**
