### PR TITLE
[fix](load) Fix potential data loss during disk migration

### PR DESCRIPTION
**Pull request by liaoxin01**
The following operations may trigger this issue.
1. migration start
2. load start using old tablet，but wait migration lock in `RowsetBuilder::prepare_txn`.
3. migration finish, old tablet -> new tablet
4. obtained migration lock and commit successfully using old tablet.
5. publish failed using old tablet, because old tablet has been dropped. It cause the data loss.

Therefore, after acquiring the migration lock, check if the tablet has already been shut down. If it has, it indicates that it is an old tablet, and data should not be imported into the old tablet.

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
