### PR TITLE
[refactor](chore) replace HashMapWithStackMemory with std::unordered_map

### PR DESCRIPTION
**Pull request by eldenmoon**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by cambyzju** [comment]
Why we need this change?

**Comment by yiguolei** [comment]
@cambyzju we want to calculate the memory using memtracker, but the hash table is used in segment cache, we could not using an allocator to calculate memory.

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
