### PR TITLE
[fix](replica) do not delete the only one replica

### PR DESCRIPTION
**Pull request by dataroaring**
## Proposed changes

  We can not delete the only one replica of a tablet internally.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
