### PR TITLE
[bug](bitmap) should return error status when execute failed

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
because it's not return error status, it's will be coredump in follow steps.
```
mysql [(none)]>select bitmap_from_base64("aGVsbG9fd29ybGQ=");
ERROR 1105 (HY000): RpcException, msg: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

if return error status, the query could be cancelled rather than code dump
```
mysql [(none)]>select bitmap_from_base64("aGVsbG9fd29ybGQ=");
ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[CANCELLED]bitmap_from_base64 decode failed: base64: aGVsbG9fd29ybGQ=
```

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
