### PR TITLE
[improvement](statistics)Add log while deserialize column statistics failed.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add log while deserialize column statistics failed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Pull request merged**
