### PR TITLE
[feature](docker)Add new example MySQL-Flink-Doris Demo

### PR DESCRIPTION
**Pull request by FreeOnePlus**
## Proposed changes

Add new example MySQL-Flink-Doris Demo

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
