### PR TITLE
[feature-wip](auto-inc)(step-1) add syntax support for duplicate table

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

Issue Number: #18501 , based on #19016 

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
