### PR TITLE
[regression-test](framework) support run a case named "check_before_quit.groovy" after all other cases running.

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes
Support run a case named "check_before_quit.groovy" after all other cases running.
If we want to check whether there are some pending tasks which is abnormal, we need this function.

Issue Number: close #xxx

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Review by wangbo — DISMISSED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by wangbo** [comment]
run p0

**Pull request closed without merging**
