### PR TITLE
[feature](array-type) Unique table support array value (#17024)

### PR DESCRIPTION
**Pull request by hqx871**
Pick from master and remove struct/map support
- #17024
- #19751

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by hqx871** [comment]
run build all

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
run buildall

**Comment by hqx871** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
check buildlog

**Comment by amorynan** [comment]
please and some regress tests

**Review by morningman — CHANGES_REQUESTED** [review]
Hi @hqx871 , this feature is not tested and missing document.
We need first add them on master, and merge it to branch 1.2 only if it pass the test.

**Comment by hqx871** [comment]
> please and some regress tests

I will add tests later

**Comment by hqx871** [comment]
run p0

**Comment by hqx871** [comment]
> Hi @hqx871 , this feature is not tested and missing document. We need first add them on master, and merge it to branch 1.2 only if it pass the test.

Sorry so late for your question. The pr is picked from master.  And there is some difference
- The 1.2 seams not support struct/map,  and master does.
- The pr [17024](https://github.com/apache/doris/pull/17024) does lack of regression tests. Thanks to @amorynan, she did it for me. And  I just pick it here.

**Comment by hqx871** [comment]
run buildall

**Pull request merged**
