### PR TITLE
[fix](char) fix char column type not check lenght

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

or can create table `c2` CHAR(2147483643) NULL

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by morrySnow — DISMISSED** [review]

**Review by amorynan — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
