### PR TITLE
[fix]fix a BE coredump bug that add new vals after reset rle page

### LINKED ISSUE #9300: [fix]fix a BE coredump bug that add new vals after reset rle page
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris master

### What's Wrong?

Load bool type may core in debug mode.
```
coredump stack:
*** Aborted at 1651050223 (unix time) try "date -d @1651050223" if you are using GNU date ***
*** SIGABRT unkown detail explain (@0x1ff000026d0) received by PID 9936 (TID 0x7f90a13d8700) from PID 9936; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at core/be/src/comm
on/signal_handler.h:419
 1# 0x00007F90BB236920 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# google::ReadFromOffset(int, void*, unsigned long, long) [clone .cold] at src/symbolize.cc:146
 5# 0x00007F90C1F69EDD at src/logging.cc:1650
 6# google::LogMessage::SendToLog() at src/logging.cc:1607
 7# google::LogMessage::Flush() at src/logging.cc:1477
 8# google::LogMessageFatal::~LogMessageFatal() at src/logging.cc:2227
 9# doris::segment_v2::RlePageBuilder<(doris::FieldType)24>::add(unsigned char const*, unsigned long*) at be/src/olap/rowset/segment_v2/rle_page.h:79
10# doris::segment_v2::ScalarColumnWriter::append_data_in_current_page(unsigned char const**, unsigned long*) at be/src/olap/rowset/segment_v2/column_writer.cpp:320
11# doris::segment_v2::ScalarColumnWriter::append_data(unsigned char const**, unsigned long) at core/be/sr
c/olap/rowset/segment_v2/column_writer.cpp:308
12# doris::segment_v2::ColumnWriter::append_nullable(unsigned char const*, void const*, unsigned long) at be/src/olap/rowset/segment_v2/column_writer.cpp:188
13# doris::segment_v2::ColumnWriter::append(unsigned char const*, void const*, unsigned long) at core/be/s
rc/olap/rowset/segment_v2/column_writer.cpp:209
14# doris::segment_v2::SegmentWriter::append_block(doris::vectorized::Block const*, unsigned long, unsigned long) at be/src/olap/rowset/segment_v2/segment_writer.cpp:141
15# doris::BetaRowsetWriter::add_block(doris::vectorized::Block const*) at core/be/src/olap/rowset/beta_ro
wset_writer.cpp:161
16# doris::MemTable::_vflush() at core/be/src/olap/memtable.cpp:329
17# doris::MemTable::flush() at core/be/src/olap/memtable.cpp:343
18# doris::FlushToken::_flush_memtable(std::shared_ptr<doris::MemTable>, long) at core/be/src/olap/memtabl
e_flush_executor.cpp:70
19# void std::__invoke_impl<void, void (doris::FlushToken::*&)(std::shared_ptr<doris::MemTable>, long), doris::FlushToken*&, std::shared_ptr<do
ris::MemTable>&, long&>(std::__invoke_memfun_deref, void (doris::FlushToken::*&)(std::shared_ptr<doris::MemTable>, long), doris::FlushToken*&,
std::shared_ptr<doris::MemTable>&, long&) in doris/be/lib/palo_be
```
### What You Expected?

not core.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yinzhijian**
# Proposed changes

Issue Number: close #9300

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by pengxiangyu — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
Could you please provide the core or exception stack?

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by wangbo — DISMISSED** [review]
+1

**Pull request closed without merging**
