### PR TITLE
[Fix](RoutineLoad)Fix when Unique (MoW) RoutineLoad imports unspecified Sequence column

### PR DESCRIPTION
**Pull request by CalvinKirs**
**effect version 2.0**
- How to reproduce：
```
CREATE TABLE `user` (
  `id` bigint(20) NOT NULL COMMENT '用户ID',
  `user_name` text NULL,
  `password` text NULL,
   ...
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT 'OLAP'
PARTITION BY RANGE(`id`)
(PARTITION i1 VALUES [("-9223372036854775808"), ("5000000")),
PARTITION i2 VALUES [("5000000"), ("10000000")),
DISTRIBUTED BY HASH(`id`) BUCKETS 16
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"is_being_synced" = "false",
"storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"function_column.sequence_col" = "order_id",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);
```

Routine Load Sql

```
CREATE ROUTINE LOAD test_load ON user
WITH MERGE
COLUMNS TERMINATED BY ",",
DELETE ON `y_n` = -1,
ORDER BY order_id
PROPERTIES
(
"desired_concurrent_number" = "1",
"max_error_number" = "0",
"max_batch_interval" = "5",
"max_batch_rows" = "300000",
"max_batch_size" = "209715200",
"format" = "json",
"strip_outer_array" = "false",
"num_as_string" = "false",
"fuzzy_parse" = "false",
"strict_mode" = "false",
"timezone" = "Asia/Shanghai",
"exec_mem_limit" = "2147483648"
)
FROM kafka(
...
)
```

error log

``` fe.log
org.apache.doris.common.UserException: errCode = 2, detailMessage = Table t_user has sequence column, need to specify the sequence column
	at org.apache.doris.planner.external.LoadScanProvider.initColumns(LoadScanProvider.java:197) ~[classes/:?]
	at org.apache.doris.planner.external.LoadScanProvider.createContext(LoadScanProvider.java:104) ~[classes/:?]
	at org.apache.doris.planner.FileLoadScanNode.initParamCreateContexts(FileLoadScanNode.java:131) ~[classes/:?]
	at org.apache.doris.planner.FileLoadScanNode.init(FileLoadScanNode.java:125) ~[classes/:?]
	at org.apache.doris.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:254) ~[classes/:?]
	at org.apache.doris.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:115) ~[classes/:?]
	at org.apache.doris.load.routineload.RoutineLoadJob.plan(RoutineLoadJob.java:872) ~[classes/:?]
	at org.apache.doris.load.routineload.KafkaTaskInfo.rePlan(KafkaTaskInfo.java:129) ~[classes/:?]
	at org.apache.doris.load.routineload.KafkaTaskInfo.createRoutineLoadTask(KafkaTaskInfo.java:98) ~[classes/:?]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.scheduleOneTask(RoutineLoadTaskScheduler.java:184) ~[classes/:?]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.process(RoutineLoadTaskScheduler.java:111) ~[classes/:?]
	at org.apache.doris.load.routineload.RoutineLoadTaskScheduler.runAfterCatalogReady(RoutineLoadTaskScheduler.java:84) ~[classes/:?]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[classes/:?]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[classes/:?]
```

- Fix
When the column is not set, the sequence column is automatically added to it

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.64 seconds
 stream load tsv:          545 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162206104 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.11 seconds
 stream load tsv:          545 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162066403 Bytes

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
lgtm

**Pull request merged**
