### PR TITLE
[Fix](Load) fix bug that last line of data lost for stream load

### LINKED ISSUE #13064: [Bug] Last line of data lost for stream load
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master (commit id: a7b42a702917ddc1b919c841b001c5b3602188f9)

### What's Wrong?

Last line of data lost for stream load when line delimiter is more than one character.

### What You Expected?

All legitimate data can be load into doris.

### How to Reproduce?

Table:
```
CREATE TABLE `table_test` (
  `id` int(11) NULL,
  `value` varchar(64) NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

Stream Load:
```
echo "1|aaweizuo2|bbweizuo3|cc" | curl --location-trusted -u xxx:xxx -H "label:test43" -H "line_delimiter:weizuo" -H "column_separator:|" -T - http://xxx:8030/api/test_db/table_test/_stream_load;
{
    "TxnId": 4014,
    "Label": "test43",
    "TwoPhaseCommit": "false",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 2,
    "NumberLoadedRows": 2,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 25,
    "LoadTimeMs": 30,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 1,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 9,
    "CommitAndPublishTimeMs": 19
}
```

Result of query:
```
mysql> select * from table_test;
+------+-------+
| id   | value |
+------+-------+
|    1 | aa    |
|    2 | bb    |
+------+-------+
2 rows in set (0.01 sec)
```

Expected:
```
mysql> select * from table_test;
+------+-------+
| id   | value |
+------+-------+
|    1 | aa    |
|    2 | bb    |
|    3 | cc    |
+------+-------+
3 rows in set (0.01 sec)
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by weizuo93**
# Proposed changes

Issue Number: close #13064 

## Problem summary

Last line of data lost for stream load when line delimiter is more than one character.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

### CODE REVIEW

**Comment by stalary** [comment]
Can you add some regression test?

**Comment by weizuo93** [comment]
> Can you add some regression test?

OK, thanks for your review. I will add some test cases.

**Comment by hf200012** [comment]
Please improve the documentation, line separators and examples to make it clearer for users to use

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
