### PR TITLE
[Feature](binlog) Add getBinlogLag

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add getBinlogLag

### CODE REVIEW

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.04 seconds
 stream load tsv:          444 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          67.9 seconds inserted 10000000 Rows, about 147K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707140941_clickbench_pr_174677.html

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 54.66 seconds
 stream load tsv:          496 seconds loaded 74807831229 Bytes, about 143 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          87.0 seconds inserted 10000000 Rows, about 114K ops/s
 storage size: 17168768394 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230707221421_clickbench_pr_174679.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
