### PR TITLE
[fix](window_func) fix bug of agg function used in window function and add many test cases

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Support usage in window function for many agg functions by adding `reset` method.
Fix bug of `window_funnel` used in window funciton;
Fix bug of wrong result of `orthogonal_bitmap_intersect`.

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
