### PR TITLE
[fix](inverted index) base compaction failed after restore indexes

### PR DESCRIPTION
**Pull request by cambyzju**
### What problem does this PR solve?
**Problem:**
after restore from other cluster, then rowsets got different index_id, and make index compaction in base compaction always failed.

**Fix:**
On master branch, this pr: https://github.com/apache/doris/pull/41625 already fix it.
Here pick it to branch-2.1

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by csun5285 — APPROVED** [review]
LGTM

**Pull request merged**
