### PR TITLE
[Regression](external)disable test_hdfs_tvf regression test case

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

disable two external case

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run p0

**Comment by zhangguoqiang666** [comment]
run p0

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by pingchunzhang — APPROVED** [review]

**Review by zgxme — APPROVED** [review]
LGTM

**Pull request merged**
