### PR TITLE
[Enhancement] (nereids)implement showDatabaseIdCommand in nereids

### LINKED ISSUE #42742: [Enhancement] (nereids)implement showDatabaseIdCommand in nereids
showDatabaseId command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showDatabaseId command in nereids:
unsupportedshowDatabaseIdStatement
``` SHOW DATABASE databaseId=INTEGER_VALUE                                        ```

### PR DESCRIPTION
**Pull request by koarz**
### What problem does this PR solve?

Issue Number: close #42742 

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run p0

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
pls resolve conflicts

**Comment by koarz** [comment]
run buildall

**Review by LiBinfeng-01 — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
