### PR TITLE
[improvement](replica) donot care last failed version in publish

### PR DESCRIPTION
**Pull request by dataroaring**
We just care 2 things:
1. If the replica acks right
2. If the replica catches up

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
