### PR TITLE
[fix](MTMV) Tasks leak when dropping job

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem summary
Fix the `test_create_mtmv.groovy` regression fail:
1. Devide mtmv regresstion into 4 suites
2. Try to remove task which was killed by drop job action in running map.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run compile

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
