### PR TITLE
[doc](readme)Enhancement in some Hyperlinks

### PR DESCRIPTION
**Pull request by nikam14**
Modified the hyperlink in the section of Users and Links.

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run P0

**Comment by luzhijing** [comment]
run P0

**Comment by nikam14** [comment]
Will you please show me how to run P0.
I am new to github workflows.

**Comment by luzhijing** [comment]
> Will you please show me how to run P0.
> I am new to github workflows.

That is an automatic workflow, which can be triggered by keyword comments 'run buildall' or 'run P0'

**Pull request merged**
