### PR TITLE
[typo](storage)Fixed wrong description about Storage_root_path parameter

### PR DESCRIPTION
**Pull request by FreeOnePlus**
## Proposed changes

Removed the invalid disk limit description, corrected the description of Storage parameters, such as the description of HDD and SSD, and changed the physical media description to the data storage directory type description (hot data directory and cold data directory).

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by FreeOnePlus** [comment]
run buildall

**Comment by FreeOnePlus** [comment]
run buildP0

**Comment by zy-kkk** [comment]
run buildall

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.9 seconds
 stream load tsv:          454 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         27 seconds loaded 2358488459 Bytes, about 83 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          69.6 seconds inserted 10000000 Rows, about 143K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230628032152_clickbench_pr_169079.html

**Pull request merged**
