### PR TITLE
[improvement](decimalv2) support check overflow for decimalv2 arithmetics

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run pipelinex_p0

**Comment by jacktengg** [comment]
run pipelinex_p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by jacktengg** [comment]
run pipelinex_p0

**Comment by jacktengg** [comment]
run compile

**Comment by jacktengg** [comment]
run pipelinex_p0

**Comment by jacktengg** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
