### PR TITLE
[Feature]Use table buckets as dynamic partition buckets default value

### PR DESCRIPTION
**Pull request by shaorui-dev**
## Proposed changes

In most scenarios, the number of buckets for dynamic partitions will be the same as the table buckets, so default value should be set.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Hi @srikker , please rebase the master to resolve the conflict

**Comment by srikker** [comment]
> 嗨@srikker，请重新设置主节点以解决冲突

done

> Hi @srikker , please rebase the master to resolve the conflict

done

**Comment by morningman** [comment]
Hi @srikker the FE unit test compile failed. 
You can run `mvn clean install -DskipTests` to see, or just running `sh run-fe-ut.sh`

**Comment by srikker** [comment]
> Hi @srikker the FE unit test compile failed.
> You can run `mvn clean install -DskipTests` to see, or just running `sh run-fe-ut.sh`

**Comment by srikker** [comment]
> > Hi @srikker the FE unit test compile failed.
> > You can run `mvn clean install -DskipTests` to see, or just running `sh run-fe-ut.sh`

ut error has fixed, local test succeeded using the command `mvn clean install -DskipTests`

**Comment by srikker** [comment]
> Hi @srikker the FE unit test compile failed.
> You can run `mvn clean install -DskipTests` to see, or just running `sh run-fe-ut.sh`

ut error has fixed, local test succeeded using the command `mvn clean install -DskipTests`

**Comment by srikker** [comment]
existed implementations

**Pull request closed without merging**
