### PR TITLE
[opt](mow) opt mow lookup with sequence column

### PR DESCRIPTION
**Pull request by cambyzju**
Compare primary key without sequence column is expensive,
if full key is exact_match, the primary key without sequence column should also the same,
do not need to compare again.

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Comment by cambyzju** [comment]
run buildall

**Comment by bobhan1** [comment]
run external

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
