### PR TITLE
[feature](ES Catalog) map nested/object type in ES to JSON type in Doris

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

1. `nested`/`object` can map to `json` type in Doris, and can be analyzed with json functions.
2. Add some cases for `json_extract`.

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
