### PR TITLE
[chore](third-party) Speed the download up for aws-crt-cpp (#22997)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Cherry pick #22997 

The package aws-sdk-cpp was upgraded in #20252. We can speed the download up for aws-crt-cpp.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
