### PR TITLE
[feature](test)Add column date type boundary of auto partition

### PR DESCRIPTION
**Pull request by zfr9527**
## Proposed changes

[feature](test)Add column date type boundary of auto partition

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zfr9527** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by zfr9527** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by zfr9527** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
