### PR TITLE
[DOC](sparkload)add spark load faq

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

add spark load FAQ

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caoliang-web — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
