### PR TITLE
[style]format fe code with some check rules

### LINKED ISSUE #9403: [Enhancement] [FE Code Style]step 1: turn on whitespace and no impact and white space check
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

fix fe code style in multi steps.
this is step 1.
Open no impact checks and fix whitespace errors

### Solution

1. Add Spotless plugin and do some simple format(1198 files changed, 3205 insertions(+), 4350 deletions(-))
	a. end with new line
	b. trim trailing whitespace
	c. replace tab indent with 4 spaces indent
	d. license header check
	e. adjust the order of import to "static, org.apache.doris, third party, java"
	f. remove unused imports
	g. make sure all files are encoding by utf-8
	h. make sure all files line ending by LF

2. Add checkstyle rules but set default severity to warning to avoid compile failed.

3. set some rules' severity to error in Checkstyle since no lines in doris break these rules(0 files, 0 lines)
	a. Merge conflicts unresolved
	b. Avoid using corresponding octal or Unicode escape
	c. Avoid Escaped Unicode Characters
	d. No Line Wrap
	e. Package Name
	f. Type Name
	g. Annotation Location
	h. Interface Type Parameter 
	i. CatchParameterName
	j. Pattern Variable Name
	k. Record Component Name
	l. Record Type Parameter Name
	m. Method Type Parameter Name

4. Set below rules severity to error in Checkstyle since these had done by splotless(12 files, 177 lines)
	a. Redundant Import
	b. Custom Import Order
	c. Unused Imports
	d. Avoid Star Import
	e. tab character in file
	f. Newline At End Of File
	g. Trailing whitespace found

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #9403 

set below rules' severity to error and format code according check info.
a. Merge conflicts unresolved
b. Avoid using corresponding octal or Unicode escape
c. Avoid Escaped Unicode Characters
d. No Line Wrap
e. Package Name
f. Type Name
g. Annotation Location
h. Interface Type Parameter
i. CatchParameterName
j. Pattern Variable Name
k. Record Component Name
l. Record Type Parameter Name
m. Method Type Parameter Name
n. Redundant Import
o. Custom Import Order
p. Unused Imports
q. Avoid Star Import
r. tab character in file
s. Newline At End Of File
t. Trailing whitespace found

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

**Comment by morrySnow** [comment]
all fe check style error is not related to the rules this patch care about

**Comment by leo65535** [comment]
👍

**Comment by leo65535** [comment]
hi @morrySnow, the `FE Code Formatter` still failed, how about use `mvn checkstyle:check` directly?

https://github.com/apache/incubator-seatunnel/tree/dev/.github/workflows/backend.yml#L104

**Comment by morrySnow** [comment]
> hi @morrySnow, the `FE Code Formatter` still failed, how about use `mvn checkstyle:check` directly?
> 
> https://github.com/apache/incubator-seatunnel/tree/dev/.github/workflows/backend.yml#L104
> 
> ```
> Raw Output:
> /github/workspace/./fe/fe-core/src/test/java/org/apache/doris/planner/OlapScanNodeTest.java:40:1: warning: Missing a Javadoc comment. (com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocTypeCheck)
> Error: reviewdog: Too many results (annotations) in diff.
> You may miss some annotations due to GitHub limitation for annotation created by logging command.
> Please check GitHub Actions log console to see all results.
> ```

Just like i comment above. I has do `mvn checkstyle:check` locally before commit pr. I checked the error list. Currently, Checker failed caused by some rules that patch do not care about.

**Review by xleoken — DISMISSED** [review]

**Comment by leo65535** [comment]
hi @morrySnow, i think we can improve the check action by using `mvn checkstyle:check` directly like apache seatunnel.

**Comment by morrySnow** [comment]
> hi @morrySnow, i think we can improve the check action by using `mvn checkstyle:check` directly like apache seatunnel.
> 
> it seems the following action still has probem which will cause the ut fail. https://github.com/apache/incubator-doris/blob/master/.github/workflows/checkstyle.yaml

could `mvn checkstyle:check` can combined with reviewdog?
what do you mean about `ut  fail`?

**Comment by leo65535** [comment]
In fact, the following configuration is enough. `reviewdog` is not a necessity. Because when met wrong checkstyle, `mvn checkstyle:check` also can cause the ut failed.

```
---
name: FE Code Style Checker
on:
  pull_request:
jobs:
  java-checkstyle:
    name: "CheckStyle"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: "Run java checkstyle"
        run:
          cd fe && mvn checkstyle:check
        
```

**Comment by morrySnow** [comment]
> In fact, the following configuration is enough. `reviewdog` is not a necessity. Because when met wrong checkstyle, `mvn checkstyle:check` also can cause the ut failed.
> 
> ```
> ---
> name: FE Code Style Checker
> on:
>   pull_request:
> jobs:
>   java-checkstyle:
>     name: "CheckStyle"
>     runs-on: ubuntu-latest
>     steps:
>       - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
>         uses: actions/checkout@v2
>         with:
>           persist-credentials: false
>           submodules: recursive
>       - name: "Run java checkstyle"
>         run:
>           cd fe && mvn checkstyle:check
>         
> ```

The final status is setting all check style rules' severity to 'error'. Currently, we have too many original code that violate check style rules. We need to fix all warnings caused by original codes and set Checker's severity to 'error' before we use `mvn checkstyle:check` instead of review dog.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
