### PR TITLE
[improvement](jdbc catalog) Modify the maximum number of connections in the connection pool to 30 by default

### PR DESCRIPTION
**Pull request by zy-kkk**
In many cases, we found that users would use JDBC Catalog to perform a large number of queries, which resulted in the maximum of 10 connections being insufficient, so I adjusted it to 30, which covered most needs.

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run external

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
