### PR TITLE
[bug](rf) fix only min/max rf return error when has remote target

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
in nested loop join the bitmap rf have non remote target
but only min/max rf maybe have remote target

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
