### PR TITLE
[Enchancement](compatible) show decimalv3 to decimal

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

now

```
mysql [test]>CREATE TABLE IF NOT EXISTS db (
    ->    `id` int(11)  ,
    ->    `dd` DECIMAL
    -> )
    -> UNIQUE KEY(`id`)
    -> DISTRIBUTED BY HASH(`id`) BUCKETS 10
    -> PROPERTIES (
    -> "enable_unique_key_merge_on_write" = "true",
    -> "replication_num" = "1"
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql [test]>desc db;
+-------+---------+------+-------+---------+-------+
| Field | Type    | Null | Key   | Default | Extra |
+-------+---------+------+-------+---------+-------+
| id    | INT     | Yes  | true  | NULL    |       |
| dd    | DECIMAL | Yes  | false | NULL    | NONE  |
+-------+---------+------+-------+---------+-------+
2 rows in set (0.00 sec)

mysql [test]>desc db all;
+-----------+---------------+-------+---------+-----------------+------+-------+---------+-------+---------+------------+-------------+
| IndexName | IndexKeysType | Field | Type    | InternalType    | Null | Key   | Default | Extra | Visible | DefineExpr | WhereClause |
+-----------+---------------+-------+---------+-----------------+------+-------+---------+-------+---------+------------+-------------+
| db        | UNIQUE_KEYS   | id    | INT     | INT             | Yes  | true  | NULL    |       | true    |            |             |
|           |               | dd    | DECIMAL | DECIMALV3(9 ,0) | Yes  | false | NULL    | NONE  | true    |            |             |
+-----------+---------------+-------+---------+-----------------+------+-------+---------+-------+---------+------------+-------------+
2 rows in set (0.00 sec)

mysql [test]>show create table db;
| db    | CREATE TABLE `db` (
  `id` int(11) NULL,
  `dd` DECIMAL NULL
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);


mysql [test]>CREATE TABLE IF NOT EXISTS db (
    ->    `id` int(11) NOT NULL ,
    ->    `str` string ,
    ->    `dd` decimal(15,6)
    -> )
    -> UNIQUE KEY(`id`)
    -> DISTRIBUTED BY HASH(`id`) BUCKETS 10
    -> PROPERTIES (
    -> "enable_unique_key_merge_on_write" = "true",
    -> "replication_num" = "1"
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql [test]>desc db;
+-------+----------------+------+-------+---------+-------+
| Field | Type           | Null | Key   | Default | Extra |
+-------+----------------+------+-------+---------+-------+
| id    | INT            | No   | true  | NULL    |       |
| str   | TEXT           | Yes  | false | NULL    | NONE  |
| dd    | DECIMAL(15, 6) | Yes  | false | NULL    | NONE  |
+-------+----------------+------+-------+---------+-------+
3 rows in set (0.00 sec)

mysql [test]>desc db all;
+-----------+---------------+-------+----------------+------------------+------+-------+---------+-------+---------+------------+-------------+
| IndexName | IndexKeysType | Field | Type           | InternalType     | Null | Key   | Default | Extra | Visible | DefineExpr | WhereClause |
+-----------+---------------+-------+----------------+------------------+------+-------+---------+-------+---------+------------+-------------+
| db        | UNIQUE_KEYS   | id    | INT            | INT              | No   | true  | NULL    |       | true    |            |             |
|           |               | str   | TEXT           | TEXT             | Yes  | false | NULL    | NONE  | true    |            |             |
|           |               | dd    | DECIMAL(15, 6) | DECIMALV3(15, 6) | Yes  | false | NULL    | NONE  | true    |            |             |
+-----------+---------------+-------+----------------+------------------+------+-------+---------+-------+---------+------------+-------------+
3 rows in set (0.00 sec)

mysql [test]>show create table db;
| db    | CREATE TABLE `db` (
  `id` int(11) NOT NULL,
  `str` text NULL,
  `dd` DECIMAL(15, 6) NULL
) ENGINE=OLAP
UNIQUE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"storage_format" = "V2",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
); |

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by yiguolei** [comment]
please add these description into regression test

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.88 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17160527682 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230713143330_clickbench_pr_177875.html

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.9 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17170371720 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230713172415_clickbench_pr_178034.html

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.73 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17163437921 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230713224848_clickbench_pr_178127.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Pull request merged**
