### PR TITLE
[feat](pipelinex) support parallel scan on pipeline x engine

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

Following of #28967

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
