### PR TITLE
fix kafka consumer reuse

### LINKED ISSUE #5981: kafka consumer复用导致位点不提交
**Describe the bug**
使用routine load时，be复用consumer会导致kafka侧位点不提交

**To Reproduce**
1 创建两个routine load任务，使用同一个topic，但是clientID和groupId不一样，其它参数一样
2 使用只有一个fe和一个be的集群，提交两个任务
3 在消费一段时间后，kafka侧显示其中某一个clientID的位点长时间不提交，但是在doris里面的数据消费是正常的。

**Expected behavior**
1 上面的情况由于groupId和clientID不一样，不应该进行复用，否则会引发混乱

**Desktop (please complete the following information):**
 - Version: 0.12.21

### PR DESCRIPTION
**Pull request by crazyleeyang**
## Proposed changes
When judging whether consumer can be reused, it is necessary to judge whether the parameter content is equal.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5981) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

Hi @crazyleeyang , thanks for your PR. but there are conflicts. Please rebase the code

**Comment by crazyleeyang** [comment]
> LGTM
> 
> Hi @crazyleeyang , thanks for your PR. but there are conflicts. Please rebase the code

done

**Review by crazyleeyang — COMMENTED** [review]
check

**Review by crazyleeyang — COMMENTED** [review]
Conflict resolution

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
