### PR TITLE
[improvement](execute) Eliminate virtual function calls when serializing and deserializing aggregate functions

### PR DESCRIPTION
**Pull request by zenoyang**
## Proposed changes

Issue Number: close #xxx
Eliminate virtual function calls when serializing and deserializing aggregate functions.

For example, in `AggregateFunctionUniq::deserialize_and_merge` method, calling `read_pod_binary(ref, buf)` in the for loop generates a large number of virtual function calls.
```c++
void deserialize_and_merge(AggregateDataPtr __restrict place, BufferReadable& buf,
                           Arena* arena) const override {
    auto& set = this->data(place).set;
    UInt64 size;
    read_var_uint(size, buf);
    set.rehash(size + set.size());
    for (size_t i = 0; i < size; ++i) {
        KeyType ref;
        read_pod_binary(ref, buf);
        set.insert(ref);
    }
}

template <typename Type>
void read_pod_binary(Type& x, BufferReadable& buf) {
    buf.read(reinterpret_cast<char*>(&x), sizeof(x));
}
```

`BufferReadable` has only one subclass, VectorBufferReader, so it is better to implement the `BufferReadable` class directly.

The following sql was tested on SSB-flat dataset:
```sql
SELECT COUNT (DISTINCT lo_partkey), COUNT (DISTINCT lo_suppkey) FROM lineorder_flat;
```
before: `MergeTime: 415.398ms`
after opt: `MergeTime: 174.660ms` 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zenoyang** [comment]
run buildall

**Review by amorynan — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.48 seconds
 stream load tsv:          448 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          63.0 seconds inserted 10000000 Rows, about 158K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230703065207_clickbench_pr_171227.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
