### PR TITLE
[fix](query cancel) Fix query is cancelled when it comes from follower FE

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
In some rear cases, the rpc port of follower FE is not updated in time, the value of rpc port of this follower in heartbeat will be 0, but actually it is still running. Query from the follower FE will be cancelled by be until rpc port is updated correctly on BE. 

This pr fixes the problem on BE by detecting above situation, and avoid cancel query in this situation.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run external

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
