### PR TITLE
[pick](nereids)do not check invisible column stats

### PR DESCRIPTION
**Pull request by englefly**
pick from master #27201

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run pipelinex_p0

**Comment by hello-stephen** [comment]
run performance

**Comment by englefly** [comment]
run buildall

**Pull request merged**
