### PR TITLE
[Fix](comments) Fix wrong comments in regression-conf.groovy

### PR DESCRIPTION
**Pull request by zhangbutao**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by morningman** [comment]
Hi @zhangbutao , sorry that I may did some wrong operation to close your PR, and I can't reopen it(don't know why).
Could you please reopen it or submit another PR?

**Comment by zhangbutao** [comment]
@morningman This change was fixed by https://github.com/apache/doris/pull/35089/files#diff-20eacd83d54c77003157839fae2a5da13bd3bae6373a516737f1db03e7bc1919 . So no need it any more. :)

**Pull request closed without merging**
