### PR TITLE
[fix](regression-test) Fix s3 load profile test failed due to css schema change

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
s3_load_profile_test failed due to FE is adding space entity, and this makes test failed.

https://github.com/apache/doris/pull/35308

image

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
