### PR TITLE
[branch-2.0][fix](outfile) Fix parquet writer wrong result issue

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

1. fix a regression test
2. Fixed a problem with parquet writer: null values in a parquet column do not have a corresponding value space, but null values in a doris column do have a reserved space. 【There is no such problem on the master branch, because master branch switched to use `ARROW` to write parquet file format】

fix a bug that fileSize is not correct, introduced by this pr: #25920

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run p0

**Comment by hello-stephen** [comment]
run p0

**Pull request merged**
