### PR TITLE
[refactor](jni) unified jni framework for java udf

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Use the unified jni framework to refactor java udf.
The unified jni framework takes `VectorTable` as the container to transform data between c++ and java, and hide the details of data format conversion.
In addition, the unified framework supports complex and nested types. 
The performance of basic types remains consistent, with a 30% improvement in string types and an order of magnitude improvement in complex types.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
