### PR TITLE
[Fix](regression) fix unstable case `test_schema_change_unique_mow`

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

branch-2.1-pick: https://github.com/apache/doris/pull/40034

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Review by zhannngchen — APPROVED** [review]

**Pull request merged**
