### PR TITLE
[docker](k8s)Determine the adjustment of the jdk version in the image through the doris version

### PR DESCRIPTION
**Pull request by catpineapple**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Review by intelligentfu — APPROVED** [review]

**Review by feifeifeimoon — APPROVED** [review]

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
