### PR TITLE
[fix](restore) Set the storage medium of the bind replicas

### PR DESCRIPTION
**Pull request by w41ter**
Since the replicas are bound to the same disk, the storage medium must be the same to avoid media migration.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Comment by w41ter** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
