### PR TITLE
[fix](regression-test) fix compile test_vertical_compaction_agg_keys failed

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #xxx

fix compile test_vertical_compaction_agg_keys failed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Pull request merged**
