### PR TITLE
[fix](string function) fix wrong usage of iconv_open

### PR DESCRIPTION
**Pull request by jacktengg**
Also add test case for function convert

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
./run buildall

**Comment by yiguolei** [comment]
buildall

**Comment by jacktengg** [comment]
run p0

**Comment by jacktengg** [comment]
run beut

**Comment by jacktengg** [comment]
run feut

**Comment by jacktengg** [comment]
run p0

**Comment by jacktengg** [comment]
run beut

**Comment by jacktengg** [comment]
run feut

**Comment by jacktengg** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
