### PR TITLE
[test](be-ut) fix load stream test after segment num check

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

fix load stream test after #36753

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
