### PR TITLE
[fix](function) fix error result in time_to_sec and timediff

### LINKED ISSUE #30229: [Bug] Inconsistent time_to_sec return value with timediff
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

When using `time_to_sec` on a value of type `TIME` returned by `timediff`, the result is always 0 if the `timediff` has been made between two date-like strings, and the result is the good one when the `timediff` has been made between 2 date objects.

### What You Expected?

We would expect `time_to_sec` to always return the amount of seconds in the `TIME` object returned by `timediff`

### How to Reproduce?

`select time_to_sec(timediff('2024-01-22', '2024-01-15')) as seconds;` returns 0 (wrong)
`select time_to_sec(timediff(to_date('2024-01-22'), to_date('2024-01-15'))) as seconds;` returns 604 800 (right)
while both `timediff('2024-01-22', '2024-01-15')` and `timediff(to_date('2024-01-22'), to_date('2024-01-15'))` return `168:00:00` which is the right value

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

[Issue Number: close #30229]

Error Reason:
In the expression, time_to_sec(timediff('2024-01-22', '2024-01-15')), the two strings '2024-01-22' and '2024-01-15' are first cast to datetime types. Due to the absence of the timev2 type in the input parameters of the new optimizer for the time_to_sec function, it falls back to the old optimizer. At this point, the signature of timediff is name = "timediff", argTypes = { "DATETIME", "DATETIME" }, returnType = "TIMEV2"). This signature triggers constant folding, but the constant folding mechanism is outdated and hasn't been updated in subsequent releases. As a result, an error occurs.

In contrast, time_to_sec(timediff(to_date('2024-01-22'), to_date('2024-01-15'))), due to the presence of an additional function, does not trigger the constant folding error.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run pipelinex_p0

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run pipelinex_p0

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
