### PR TITLE
Revert "[feature-wip](catalog) support deltalake catalog step1-metadata (#22493)"

### PR DESCRIPTION
**Pull request by zy-kkk**
This reverts commit 5b641ebd40fff71e632ee9be4ede58b744b602b9.

## Proposed changes

Currently, Deltalake Catalog is not a usable feature. We will continue to implement it in the datalake plug-in system in the future, so we will delete it from the FE code for now.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
