### PR TITLE
[improve](config) print value in error message

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

It took us quite a lot time to troubleshoot a config problem in regression environment.
It turns out that `be.conf` is missing EOL (`\n`) in the end, and the test script appended some lines.

Current:

```
start time: Thu 28 Dec 2023 12:05:06 PM CST
INFO: java_cmd /usr/local/software/jdk1.8.0_131/bin/java
INFO: jdk_version 8
config field error: sys_log_verbose_flags_v
```

After this change:

```
start time: Thu 28 Dec 2023 12:09:05 PM CST
INFO: java_cmd /usr/local/software/jdk1.8.0_131/bin/java
INFO: jdk_version 8
config field error: sys_log_verbose_flags_v = "100# priority_networks = 10.10.10.0/24;192.168.0.0/16"
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
