### PR TITLE
[fix](csv_reader) fix trim_double_quotes behavior change

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

This pr https://github.com/apache/doris/pull/23352 Introduced behavior change of trim_double_quotes behavior change, which need fix it.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
