### PR TITLE
[test](regression-test) fix case, compatible with 3 replicas.

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
