### PR TITLE
[improvement](replica) set replica drop write editlog

### PR DESCRIPTION
**Pull request by yujun777**
Set replica drop write an editlog.  Othewise if user connect to follow fe and execute this cmd,  then he show replica will still found replica's IsUserDrop = false, he may confused.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run pipelinex_p0

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
