### PR TITLE
[improvement](statistics)Reduce partition column sample BE memory consumption. (#41203)

### PR DESCRIPTION
**Pull request by Jibing-Li**
backport: https://github.com/apache/doris/pull/41203

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Comment by morrySnow** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Pull request merged**
