### PR TITLE
[improve](profile) Add close file interaction time and profile indicators

### PR DESCRIPTION
**Pull request by Sjwhello**
## Proposed changes
- Profile add hdfs file close time indicator
- Hdfs file close time add metric monitoring

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

**Comment by gavinchou** [comment]
run buildall

**Comment by Sjwhello** [comment]
run buildall

**Comment by Sjwhello** [comment]
run buildall

**Comment by Sjwhello** [comment]
run buildall

**Comment by Sjwhello** [comment]
run buildall

**Comment by Sjwhello** [comment]
run buildall

**Pull request closed without merging**
