### PR TITLE
Revert "[opt](stats) Recycle expired table stats"

### PR DESCRIPTION
**Pull request by zy-kkk**
Reverts apache/doris#23803

Used for testing the external table regression test

### CODE REVIEW

**Comment by zy-kkk** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run external

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run clickbench

**Pull request merged**
