### PR TITLE
[fix](cluster key) fix cluster key schema change

### PR DESCRIPTION
**Pull request by mymeiyi**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
for schema change: add a key in the tail of all keys, may get:

```
F20241209 14:52:09.513403 3166619 segment_writer.cpp:1309] Check failed: key.compare(last_key) >= 0 key is not sorted! current key: ^A^B06olTqiL2rEn48nTpmP8, last key: ^B^@^OЭ^BxsmIHehvUnv
*** Check failure stack trace: ***
    @     0x563674f2dcc6  google::LogMessage::SendToLog()
    @     0x563674f2a710  google::LogMessage::Flush()
    @     0x563674f2e509  google::LogMessageFatal::~LogMessageFatal()
    @     0x56366a8a72c0  doris::segment_v2::SegmentWriter::_generate_short_key_index()
    @     0x56366a8a6032  doris::segment_v2::SegmentWriter::append_block()
    @     0x56366a7624c9  doris::SegmentCreator::add_block()
    @     0x56366a731d35  doris::BaseBetaRowsetWriter::add_block()
    @     0x56366a94a233  doris::VSchemaChangeDirectly::_inner_process()
    @     0x56366a95d558  doris::SchemaChange::process()
    @     0x56366a9511e5  doris::SchemaChangeJob::_convert_historical_rowsets()
    @     0x56366a94e5e2  doris::SchemaChangeJob::_do_process_alter_tablet()
    @     0x56366a94cf22  doris::SchemaChangeJob::process_alter_tablet()
    @     0x563669e9e857  doris::alter_tablet_callback()
```

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
