### PR TITLE
[fix](load) avoid inserting too large string with type of agg_state

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

When exceeds the limit, the insert should fail with an error like this:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Insert has filtered data in strict mode. url: http://10.16.10.8:18042/api/_load_error_log?file=__shard_1/error_log_insert_stmt_4cd3aff651284c8b-b1ecc6f774d3df1b_4cd3aff651284c8b_b1ecc6f774d3df1b
```

```
curl http://10.16.10.8:18042/api/_load_error_log?file=__shard_1/error_log_insert_stmt_4cd3aff651284c8b-b1ecc6f774d3df1b_4cd3aff651284c8b_b1ecc6f774d3df1b
Reason: column_name[k2], the length of input string is too long than vec schema. first 32 bytes of input str: [��Gccc,bb,a,ccc,bb,a,ccc,bb,a,] schema length: -1; limit length: 1048576; actual length: 1179656; . src line []; 
```

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
add test case to p1

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
