### PR TITLE
[Feat](Nereids) support show create repository command

### LINKED ISSUE #42724: [Enhancement] (nereids)implement showCreateRepositoryCommand in nereids
showCreateRepository command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showCreateRepository command in nereids:
unsupportedshowCreateRepositoryStatement
``` SHOW CREATE REPOSITORY FOR identifier                                         ```

### PR DESCRIPTION
**Pull request by GentleCold**
### What problem does this PR solve?

Issue Number: close #42724

Problem Summary:

migrate show create repository command to nereids

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run p0

**Review by starocean999 — DISMISSED** [review]
LGTM

**Review by LiBinfeng-01 — APPROVED** [review]

**Comment by starocean999** [comment]
please rebase the latest master to resolve the conflicts

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
> please rebase the latest master to resolve the conflicts

done

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Comment by GentleCold** [comment]
run buildall

**Review by Vallishp — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
