### PR TITLE
[Chore](dependencies)Upgrade Fe dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
### What problem does this PR solve?

upgrade guava to 32.2.1-jre
upgrade zookeeper to 3.9.3
upgrade azure to 1.2.29
exclusion ini4j and lucene

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [x] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by hubgeter — APPROVED** [review]

**Pull request merged**
