### PR TITLE
[enhancement](log) Changed log of waiting previous transactions to info level for debug convenience

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run performance

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
