### PR TITLE
[Fix](executor)Fix backend_active_tasks only scan one be

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
Fix select * from backend_active_tasks but only return one random be info.

Before, only return one random be.
```

    mysql [information_schema]>select * from backend_active_tasks;
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
| BE_ID | FE_HOST    | QUERY_ID                          | TASK_TIME_MS | TASK_CPU_TIME_MS | SCAN_ROWS | SCAN_BYTES | BE_PEAK_MEMORY_BYTES | CURRENT_USED_MEMORY_BYTES | SHUFFLE_SEND_BYTES | SHUFFLE_SEND_ROWS |
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
| 10025 | 127.0.0.1 | cc95f1db96c0411c-bdc9f663c0053e6a |            3 |                0 |         0 |          0 |                95520 |                         0 |                254 |                 1 |
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
3 rows in set (0.02 sec)
```

After, could return all be INFO.
```
mysql [information_schema]>select * from backend_active_tasks;
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
| BE_ID | FE_HOST    | QUERY_ID                          | TASK_TIME_MS | TASK_CPU_TIME_MS | SCAN_ROWS | SCAN_BYTES | BE_PEAK_MEMORY_BYTES | CURRENT_USED_MEMORY_BYTES | SHUFFLE_SEND_BYTES | SHUFFLE_SEND_ROWS |
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
| 10025 | 127.0.0.1 | 41eb5302f1c243e9-addee8bc1692ce2f |            2 |                0 |         0 |          0 |                 4096 |                      4096 |                  0 |                 0 |
| 10025 | 127.0.0.1 | cc95f1db96c0411c-bdc9f663c0053e6a |            3 |                0 |         0 |          0 |                95520 |                         0 |                254 |                 1 |
| 10006 | 127.0.0.1 | 41eb5302f1c243e9-addee8bc1692ce2f |            2 |                0 |         0 |          0 |                 4096 |                      4096 |                  0 |                 0 |
+-------+------------+-----------------------------------+--------------+------------------+-----------+------------+----------------------+---------------------------+--------------------+-------------------+
3 rows in set (0.02 sec)
```

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by wangbo** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
