### PR TITLE
Revert "[ci](perf) add required (#30155)"

### PR DESCRIPTION
**Pull request by shuke987**
This reverts commit f9c274c338afbe14f97cc16d1327e9a548e524b3.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shuke987** [comment]
run buidlall

**Comment by xiaokang** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
