### PR TITLE
[opt](memory) Process profile add metadata profile

### PR DESCRIPTION
**Pull request by xinyiZzz**
### What problem does this PR solve?

Problem Summary:

http://127.0.0.1:8040/profile
```
ObjectHeapDump:
   - AllRowsetsMemBytes: 16.33 MB
   - AllRowsetsNum: 76.45K
   - AllSegmentsMemBytes: 4.16 KB
   - AllSegmentsNum: 1
   - BitmapIndexReaderMemBytes: 0
   - BitmapIndexReaderNum: 0
   - BloomFilterIndexReaderMemBytes: 0
   - BloomFilterIndexReaderNum: 0
   - ColumnReaderMemBytes: 0
   - ColumnReaderNum: 0
   - IndexPageReaderMemBytes: 0
   - IndexPageReaderNum: 0
   - IndexedColumnReaderMemBytes: 0
   - IndexedColumnReaderNum: 0
   - InvertedIndexReaderMemBytes: 0
   - InvertedIndexReaderNum: 0
   - OrdinalIndexReaderMemBytes: 0
   - OrdinalIndexReaderNum: 0
   - RowsetMetaMemBytes: 45.47 MB
   - RowsetMetaNum: 76.45K
   - TabletColumnMemBytes: 253.28 MB
   - TabletColumnNum: 922.18K
   - TabletIndexMemBytes: 16.78 MB
   - TabletIndexNum: 104.74K
   - TabletMetaMemBytes: 17.50 MB
   - TabletMetaNum: 45.89K
   - TabletSchemaMemBytes: 60.15 MB
   - TabletSchemaNum: 49.19K
   - ZoneMapIndexReaderMemBytes: 0
   - ZoneMapIndexReaderNum: 0
 ```

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
