### PR TITLE
[bugfix](iceberg)add prefix for endpoint with s3 client

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

add prefix for endpoint with s3 client.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Comment by morningman** [comment]
run p0

**Comment by morningman** [comment]
run cloudp0

**Comment by morningman** [comment]
run cloud_p0

**Pull request merged**
