### PR TITLE
[enhance](mtmv)Optimize the speed of obtaining the last update time of Hive

### PR DESCRIPTION
**Pull request by zddr**
Previously, to obtain the last update time of a hive table, it was necessary to obtain the last update time of all partitions under the table, which required generating a large map.

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zddr** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
