### PR TITLE
[fix](inverted index)Support rename column with inverted index

### LINKED ISSUE #38078: [Bug] rename column with inverted index throw error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.ImmutableList.set(ImmutableList.java:528) ~[guava-32.1.2-jre.jar:?]
        at org.apache.doris.catalog.Env.renameColumn(Env.java:5015) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.renameColumn(Env.java:5067) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.alter.Alter.processRename(Alter.java:706) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.alter.Alter.processAlterOlapTable(Alter.java:263) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.alter.Alter.processAlterTable(Alter.java:463) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.alterTable(Env.java:4572) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:190) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:3024) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:1050) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:627) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.queryRetry(StmtExecutor.java:545) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:535) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:371) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:235) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:260) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:288) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:342) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### What You Expected?

rename normally

### How to Reproduce?

1. create table
```
CREATE TABLE test_rename_column_with_format_v2 (
            `id` int(11) NULL,
            `name` varchar(255) NULL,
            `score` int(11) NULL,
            index index_name (name) using inverted
        ) ENGINE=OLAP
        DUPLICATE KEY(`id`)
        COMMENT 'OLAP'
        DISTRIBUTED BY HASH(`id`) BUCKETS 1
        PROPERTIES (
            "replication_allocation" = "tag.location.default: 1",
            "inverted_index_storage_format" = "V2",
            "disable_auto_compaction" = "true"
        );
```
2. alter
```
ALTER TABLE test_rename_column_with_format_v2 RENAME COLUMN name name_new; 
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Copy columns and properties to make them mutable.

close #38078

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
add a test case

**Review by morrySnow — DISMISSED** [review]

**Review by starocean999 — DISMISSED** [review]

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run external

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p1

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p1

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run exterrnal

**Comment by qidaye** [comment]
run external

**Comment by qidaye** [comment]
run external

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
