### PR TITLE
[Improvement](coldheat) add statement to show objects which use storage policy

### PR DESCRIPTION
**Pull request by Yulei-Yang**
```
mysql> show storage policy using for test_policy;  
+-------------+----------+---------------------------------+-----------------+
| PolicyName  | Database | Table                           | Partitions      |
+-------------+----------+---------------------------------+-----------------+
| test_policy | db1      | target_test_1                   | ALL             | 
| test_policy | db1      | cooldown_test                   | ALL             |
| test_policy | db1      | partition_test_2                | p201701         |
| test_policy | db1      | partition_with_storage_policy_1 | p201701         | 
| test_policy | db1      | partition_test_1                | p201701,p201702 |
| test_policy | db2      | db2_test_1                      | ALL             |
+-------------+----------+---------------------------------+-----------------+                                            
6 rows in set (0.02 sec)

mysql> show storage policy using;
+-----------------------+-----------------------------------------+----------------------------------------+-----------------+
| PolicyName            | Database                                | Table                                  | Partitions      |
+-----------------------+-----------------------------------------+----------------------------------------+-----------------+
| test_storage_policy   | regression_test_cold_heat_separation_p2 | table_with_storage_policy_1            | ALL             |
| test_storage_policy   | regression_test_cold_heat_separation_p2 | partition_with_multiple_storage_policy | p201701         |
| test_storage_policy_2 | regression_test_cold_heat_separation_p2 | partition_with_multiple_storage_policy | p201702         |
| test_storage_policy_2 | regression_test_cold_heat_separation_p2 | table_with_storage_policy_2            | ALL             |
| test_policy           | db1                                     | target_test_1                          | ALL             |
| test_policy           | db1                                     | cooldown_test                          | ALL             |
| test_policy           | db1                                     | partition_test_2                       | p201701         |
| test_policy           | db1                                     | partition_with_storage_policy_1        | p201701         |
| test_policy           | db1                                     | partition_test_1                       | p201701,p201702 |
| test_policy           | db2                                     | db2_test_1                             | ALL             |
+-----------------------+-----------------------------------------+----------------------------------------+-----------------+
10 rows in set (0.01 sec)
```

docs: https://github.com/apache/doris-website/pull/701

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run performance

**Comment by Yulei-Yang** [comment]
run performance

**Comment by Yulei-Yang** [comment]
run buildall

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
replace screenshot with text for search engine and git commit message friendly

**Comment by Yulei-Yang** [comment]
> replace screenshot with text for search engine and git commit message friendly

done

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
