### PR TITLE
[Bug][DynamicPartition]Fix bug that Modify a dynamic partition property in a non-dynamic partition table will throw a Exception

### PR DESCRIPTION
**Pull request by WingsGo**

### CODE REVIEW

**Comment by WingsGo** [comment]
Ref #4126

**Review by morningman — COMMENTED** [review]
Could you add a UT for this?

**Comment by WingsGo** [comment]
> Could you add a UT for this?

@morningman OK, done~

**Comment by WingsGo** [comment]
Hi, @morningman , I think the PR should included in 0.13-branch, can you review it? thx~~

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
> Hi, @morningman , I think the PR should included in 0.13-branch, can you review it? thx~~

OK

**Pull request merged**
