### PR TITLE
[improvement] TOperationStatus determines that a null pointer is redundant.

### PR DESCRIPTION
**Pull request by zzzzzzzs**
# Proposed changes

TOperationStatus determines that a null pointer is redundant. If tOperationStatus is a null pointer, then tOperationStatus.getMessage() will have a null pointer exception.

## Problem summary

change BrokerUtil.java and BrokerReader.java

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzzzzzs** [comment]
run buildall

**Comment by morningman** [comment]
NullPointerException is not a good exception, better to avoid it.

**Comment by zzzzzzzs** [comment]
> NullPointerException is not a good exception, better to avoid it.

If tOperationStatus is null, it will enter the conditional branch. If it enters the conditional branch, the subsequent tOperationStatus.getMessage() method will throw a NullPointerException.

**Comment by morningman** [comment]
> > NullPointerException is not a good exception, better to avoid it.
> 
> If tOperationStatus is null, it will enter the conditional branch. If it enters the conditional branch, the subsequent tOperationStatus.getMessage() method will throw a NullPointerException.

What I mean is, after your modification, if `tOperationStatus` is null, it may throw NPE. But it is not a good idea to throw NPE.

**Comment by zzzzzzzs** [comment]
> 



> > > NullPointerException is not a good exception, better to avoid it.
> > 
> > 
> > If tOperationStatus is null, it will enter the conditional branch. If it enters the conditional branch, the subsequent tOperationStatus.getMessage() method will throw a NullPointerException.
> 
> What I mean is, after your modification, if `tOperationStatus` is null, it may throw NPE. But it is not a good idea to throw NPE.

I think we should separately check if tOperationStatus is null. What do you think?

**Comment by morningman** [comment]
> > 
> 
> > > > NullPointerException is not a good exception, better to avoid it.
> > > 
> > > 
> > > If tOperationStatus is null, it will enter the conditional branch. If it enters the conditional branch, the subsequent tOperationStatus.getMessage() method will throw a NullPointerException.
> > 
> > 
> > What I mean is, after your modification, if `tOperationStatus` is null, it may throw NPE. But it is not a good idea to throw NPE.
> 
> I think we should separately check if `tOperationStatus` is null. What do you think?

looks good to me

**Comment by zzzzzzzs** [comment]
> > > 
> > 
> > 
> > > > > NullPointerException is not a good exception, better to avoid it.
> > > > 
> > > > 
> > > > If tOperationStatus is null, it will enter the conditional branch. If it enters the conditional branch, the subsequent tOperationStatus.getMessage() method will throw a NullPointerException.
> > > 
> > > 
> > > What I mean is, after your modification, if `tOperationStatus` is null, it may throw NPE. But it is not a good idea to throw NPE.
> > 
> > 
> > I think we should separately check if `tOperationStatus` is null. What do you think?
> 
> looks good to me

PTAL

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
