### PR TITLE
test benchmark pipeline

### PR DESCRIPTION
**Pull request by hello-stephen**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
test comment

**Comment by hello-stephen** [comment]
test comment

**Comment by yiguolei** [comment]
Me too

**Comment by yiguolei** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/clickbench_pr_29133.html

**Comment by hello-stephen** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/clickbench_pr_29133.html

**Comment by hello-stephen** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/clickbench_pr_29133.html

**Comment by hello-stephen** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/clickbench_pr_29174.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
total run time:    30.2s
load time:           520s
storage size:      17123069872 Bytes
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/clickbench_pr_29174.html

**Comment by hello-stephen** [comment]
TeamCity

**Comment by hello-stephen** [comment]
TeamCity

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 total run time: 30.2 s 
 load time: 123 s 
 storage size: 112211221122 Bytes 
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/

**Comment by hello-stephen** [comment]
$comment_body

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 update update

**Pull request closed without merging**
