### PR TITLE
[opt](load) use notify to replace polling for FlushToken

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

For FlushToken，use notify to replace polling to reduce sleep wait time.

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by wangbo — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
