### PR TITLE
[fix](test)Fix index_compaction unstable cases (#29499)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

pick from master: #29499 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run compile

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run compile

**Comment by qidaye** [comment]
run compile

**Pull request merged**
