### PR TITLE
[Opt](parquet/orc-reader) Opt get dict ids in _rewrite_dict_predicates().

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Opt] (parquet/orc-reader) Opt get dict ids in _rewrite_dict_predicates().

The original implementation needed to obtain the dict code through dict value when generating dictionary filter conditions. In order to obtain the dict code, a `dict_value_to_code` hash map needs to be constructed. We found that when the amount of data is large, it is time-consuming to construct the `dict_value_to_code` hash map, and the current implementation will also construct it when there is no filter condition. Because the dict code is the position of the dictionary element, this PR records the position when filtering the dict value, so as to directly obtain the dict code.

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run beut

**Review by morningman — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
