### PR TITLE
[Feature] support spark connector sink stream data to doris

### PR DESCRIPTION
**Pull request by chovy-3012**
## Proposed changes
1. support spark conncetor writing stream data to doris
2. refactor dataframe sink code . writing params be configured  in class "org.apache.doris.spark.cfg.SparkSettings" instead of "org.apache.doris.spark.sql.DorisWriterOption" , and some other static constant

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [x] Code refactor (Modify the code structure, format the code, etc...)
- [x] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — COMMENTED** [review]
Please provide instructions for use and update spark connector related documents at the same time

**Comment by chovy-3012** [comment]
> Please provide instructions for use and update spark connector related documents at the same time

hi, I added both batch/stream writing instructions in doc , pls review.

**Review by hf200012 — COMMENTED** [review]
In order to make it more convenient for users to use, can you consider implementing a
```
CREATE TABLE myUserTable (
user_id STRING,
user_name STRING
uv BIGINT,
pv BIGINT
) WITH (
'connector' ='doris',
'fe.host' ='ip:port',
'username' ='users',
'password' ='password',
'tableName' ='table1'
);
```
Then pass
```
insert into myUserTable select * from <spark sql table>
```
This can refer to the implementation of Flink connector
This can be put into the next stage of iteration

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
