### PR TITLE
[brach-2.0](pick#26245)use 2 phase agg above union all

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by xiaokang** [comment]
https://github.com/apache/doris/pull/26664

**Comment by englefly** [comment]
run buildall

**Comment by xiaokang** [comment]
#26245

**Pull request merged**
