### PR TITLE
[chore](build) Fix compilation errors reported by GCC-13

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

~~Issue Number: close #xxx~~

1. Fix lots of compilation errors reported by GCC-13.
2. Fix the workflow `BE UT (macOS)`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run clickbench

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
