### PR TITLE
[Fix](multi catalog)Support hive default partition.

### PR DESCRIPTION
**Pull request by Jibing-Li**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Hive store all the data without partition columns to a default partition named \_\_HIVE_DEFAULT_PARTITION\_\_.
Doris will fail to get the this partition when the partition column type is INT or something else that \_\_HIVE_DEFAULT_PARTITION\_\_ couldn't convert to. 
This pr is to support hive default partition, set the column value to NULL for the missing partition columns.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please add regression test case

**Comment by Jibing-Li** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.04 seconds
 stream load tsv:          468 seconds loaded 74807831229 Bytes, about 152 MB/s
 stream load json:         37 seconds loaded 2358488459 Bytes, about 60 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          27 seconds loaded 861443392 Bytes, about 30 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230227124233_clickbench_pr_105133.html

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
