### PR TITLE
[fix](auth)fix create table like need create_priv of existed table #37879 #25711

### PR DESCRIPTION
**Pull request by zddr**
pick: https://github.com/apache/doris/pull/37879  https://github.com/apache/doris/pull/25711

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by zddr** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Pull request merged**
