### PR TITLE
[improvement](nereids) Support where, group by, having, order by clause without from clause in query statement

### PR DESCRIPTION
**Pull request by JingDas**
## Proposed changes
Support where, group by, having, order by clause without from clause in query statement.
For example as following:

SELECT 1 AS a, COUNT(*), SUM(2), AVG(1), RANK() OVER() AS w_rank
WHERE 1 = 1
GROUP BY a, w_rank
HAVING COUNT(*) IN (1, 2) AND w_rank = 1
ORDER BY a;

this will return result:

a|count(*)|sum(2)|avg(1)|w_rank|
-+--------+------+------+------+
1|       1|     2|   1.0|     1|

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JingDas** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Comment by seawinde** [comment]
this pr is removed to https://github.com/apache/doris/pull/27006, so close this

**Pull request closed without merging**
