### PR TITLE
[fix](FragmentMgr) Should not use operator[] for _query_ctx_map

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Ref: https://en.cppreference.com/w/cpp/container/unordered_map/operator_at

Returns a reference to the value that is mapped to a key equivalent to key or x respectively, performing an insertion if such key does not already exist.

The original code would make `_query_ctx_map` has key `0-0` and value null-pointer.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run cloud_p1

**Comment by zhiqiang-hhhh** [comment]
image

crash on p0 is not related to this pr, re run

**Comment by zhiqiang-hhhh** [comment]
run p0

**Review by yiguolei — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
