### PR TITLE
[docs](typo) fix faq docs, already support rename column. 

### PR DESCRIPTION
**Pull request by ZhangYu0123**
Already support rename column.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p0

**Review by luzhijing — COMMENTED** [review]
Only properties set “light_schema_change”=“true” can support rename column after version 1.2.0, it's better to  add it.

**Comment by ZhangYu0123** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by ZhangYu0123** [comment]
run p0

**Pull request merged**
