### PR TITLE
[Fix](function) fix coredump because short of check on randoms arguments

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before:
crash or
```sql
mysql [test]>select random(1,array_size(split_by_string(fcst_emp,','))) from test_random;
+---------------------------------------------------------+
| random(1, array_size(split_by_string(`fcst_emp`, ','))) |
+---------------------------------------------------------+
|                                     7471044383762196303 |
+---------------------------------------------------------+
1 row in set (0.05 sec)
```

now:
both for nereids and legacy planner:
```sql
mysql [test]>select random(1,array_size(split_by_string(fcst_emp,','))) from test_random;
ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[INVALID_ARGUMENT]The param of rand function must be literal
```

doc pr: https://github.com/apache/doris-website/pull/992

### CODE REVIEW

**Review by zhiqiang-hhhh — CHANGES_REQUESTED** [review]
The test only guarantee exception is thrown from FE. Modification on BE is not covered, and this is important, since we need to upgrade cluster.

When the pr is picked to 2.1, should add more tests to cover non-nereids planner.

**Comment by zclllyybb** [comment]
> The test only guarantee exception is thrown from FE. Modification on BE is not covered, and this is important, since we need to upgrade cluster.
> 
> When the pr is picked to 2.1, should add more tests to cover non-nereids planner.

实际上，最后面加的那个testcase，就是接收的从BE报的错：
```sql

mysql [test]>set enable_nereids_planner=false;
Query OK, 0 rows affected (0.02 sec)

mysql [test]>select random(1,array_size(split_by_string(fcst_emp,','))) from test_random;
ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[INVALID_ARGUMENT]The param of rand function must be literal
```
剩下的交给升降级测试，回归里只能测到这些了（BE的报错本来就是兜底的，且老优化器的问题主要修复方式是不走老优化器）

**Comment by zhiqiang-hhhh** [comment]
> > The test only guarantee exception is thrown from FE. Modification on BE is not covered, and this is important, since we need to upgrade cluster.
> > When the pr is picked to 2.1, should add more tests to cover non-nereids planner.
> 
> 实际上，最后面加的那个testcase，就是接收的从BE报的错：
> 
> ```sql
> mysql [test]>set enable_nereids_planner=false;
> Query OK, 0 rows affected (0.02 sec)
> 
> mysql [test]>select random(1,array_size(split_by_string(fcst_emp,','))) from test_random;
> ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[INVALID_ARGUMENT]The param of rand function must be literal
> ```
> 
> 剩下的交给升降级测试，回归里只能测到这些了（BE的报错本来就是兜底的，且老优化器的问题主要修复方式是不走老优化器）

master 上还有老优化器么我记得不是删了么已经

**Comment by zclllyybb** [comment]
> > > The test only guarantee exception is thrown from FE. Modification on BE is not covered, and this is important, since we need to upgrade cluster.
> > > When the pr is picked to 2.1, should add more tests to cover non-nereids planner.
> > 
> > 
> > 实际上，最后面加的那个testcase，就是接收的从BE报的错：
> > ```sql
> > mysql [test]>set enable_nereids_planner=false;
> > Query OK, 0 rows affected (0.02 sec)
> > 
> > mysql [test]>select random(1,array_size(split_by_string(fcst_emp,','))) from test_random;
> > ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[INVALID_ARGUMENT]The param of rand function must be literal
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 剩下的交给升降级测试，回归里只能测到这些了（BE的报错本来就是兜底的，且老优化器的问题主要修复方式是不走老优化器）
> 
> master 上还有老优化器么我记得不是删了么已经

还有，不清楚哪个版本删，而且我记得目前还不能直接删来着，有些语句新优化器都没支持上。。

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
