### PR TITLE
[fix](regression-test) Fix scanner profile test failed occasionally

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Collection of profile is async. So wait 5 seconds before get profile.

adaptive_pipeline_task_serial_read_on_limit will fail on multi backends env, since tablets num on each be will not be 10.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by zclllyybb — APPROVED** [review]

**Comment by yiguolei** [comment]
skip buildall

**Comment by yiguolei** [comment]
other pipeline passed, only left performance, skip it

**Comment by yiguolei** [comment]
skip buildall

**Comment by yiguolei** [comment]
skip buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
skip buildall

**Review by hello-stephen — APPROVED** [review]

**Comment by hello-stephen** [comment]
skip buildall

**Pull request merged**
