### PR TITLE
[fix](regression) spare .testfile to make disk checker happy when injecting fault

### PR DESCRIPTION
**Pull request by freemandealer**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
run pipelinex_p0

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
