### PR TITLE
[improvement](statistics)Create or update table stats after alter column stats.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Create or update table stats after alter column stats.
Set flag to disable auto analyze for the table after user inject column stats.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buidall

**Review by morrySnow — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Pull request merged**
