### PR TITLE
[enhance](auth)role/user add comment

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx
doc: https://github.com/apache/doris-website/pull/448

`create user u1 comment "c1";`
`alter user u1 comment "c2";`
`show grants ; `add `Comment`
`create role role1 comment "c3";`
`alter role role1 comment "c4";`
`show roles ;` add `Comment`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zddr** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
