### PR TITLE
[improvement](mtmv) Refactor the plan getting logic when create mtmv,and support to collect view from plan

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes
Refactor some plan getting logic when create materialized view, and support to collect view from plan.
this is the precondition to support create materialized view with view.

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Pull request closed without merging**
