### PR TITLE
[Bug](exchange) fix tablet sink shuffle without project not match the output tuple

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

```
INSERT INTO tbl_4 SELECT k1, k2, k2 FROM tbl_1;

the tbl_1 have k1,k2 columns
the tbl_4 have k1,k2,v columns
if without project expr, will be only two columns not match the output tuple.
```
the co-auther of FE code  from @starocean999

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Review by Gabriel39 — DISMISSED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
