### PR TITLE
[community](tool) add a tool to pick pr from one branch to another

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

A tool to pick pr from one branch to another.

```
usage: tools/pick_pr.sh <branch_from> <branch_to> <git_push_remote> <pr_number>

       branch_from/to  syntax: local_git_remote_name/branch_name  eg: upstream/master upstream/branch-2.0
       git_push_remote syntax: local_git_remote_name              eg: origin your_name
       use 'git remote -v' to get list of local_git_remote_name

       NOTICE: This script depends on github cli tool 'gh', which can be get from https://cli.github.com/
               You need to login using 'gh auth login'. It will ask your github token, which can be generated at https://github.com/settings/tokens
```

The tool will show the commit for the pr and wait user's confirmation. Here is an example.

```
$ sh tools/pick_pr.sh apache/master apache/branch-2.0 origin 29391
step1: git fetch to update local git repos apache and apache

step2: get pr 29391 commit id using gh cli
commit id for 29391 is 'c1ddcc5751f92a32c522aeb86055fe0b23ecbaf9'
commit c1ddcc5751f92a32c522aeb86055fe0b23ecbaf9
Author: Mingyu Chen <[morningman@163.com](mailto:morningman@163.com)>
Date:   Fri Jan 5 00:14:16 2024 +0800

    [opt](config) create custom conf dir if not exists (#29391)

 fe/fe-common/src/main/java/org/apache/doris/common/ConfigBase.java | 1 +
 1 file changed, 1 insertion(+)

step3: create local branch  based on remote branch apache/branch-2.0
switched to new branch 'pick_29391_to_apache_branch-2.0'

step4: will run git cherry-pick c1ddcc5751f92a32c522aeb86055fe0b23ecbaf9 , please confirm y/n: y

auto merged fe/fe-common/src/main/java/org/apache/doris/common/ConfigBase.java
[pick_29391_to_apache_branch-2.0 111c4c49e8] [opt](config) create custom conf dir if not exists (#29391)
 Author: Mingyu Chen <[morningman@163.com](mailto:morningman@163.com)>
 Date: Fri Jan 5 00:14:16 2024 +0800
 1 file changed, 1 insertion(+)

step5: push to your remote repo origin [git@github.com:](mailto:git@github.com:)xiaokang/doris.git
remote: Resolving deltas: 100% (3434/3434), completed with 801 local objects.
remote: 
remote: Create a pull request for 'pick_29391_to_apache_branch-2.0' on GitHub by visiting:
remote:      https://github.com/xiaokang/doris/pull/new/pick_29391_to_apache_branch-2.0
remote: 
To [github.com:](http://github.com/)xiaokang/doris.git
 * [new branch]            pick_29391_to_apache_branch-2.0 -> pick_29391_to_apache_branch-2.0

step6: create pr using gh cli
new pr url: https://github.com/apache/doris/pull/29763

step7: comment 'run buildall' to trigger tests using gh cli
https://github.com/apache/doris/pull/29763#issuecomment-1884091459
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
