### PR TITLE
[Chore](brpc) add gc for abafreelist to avoid eagain and set brpc timeout_ms to 2s

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1. add gc for abafreelist to avoid eagain
```
[CANCELLED]failed to send brpc when exchange, error=Resource temporarily unavailable, error_text=[E11]Resource temporarily unavailable
```
2. set brpc timeout_ms to 2s

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by eleven-f** [comment]
version 2.1.7 error still exists
image

**Comment by zhujian86** [comment]
version 2.1.11 error still exists

**Pull request merged**
