### PR TITLE
[Bug](pipeline) adjust scanner scheduler.submit and _num_scheduling_ctx maintain

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

F0714 09:50:52.553777  9149 task_scheduler.cpp:249] Check failed: !task->is_pending_finish() must not pending close QueryId: 36e0dd2fc7104db2-bc2c1b434b3e9edd
InstanceId: 36e0dd2fc7104db2-bc2c1b434b3e9ef1

num_running_scanners = 0, num_scheduling_ctx = 1 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.86 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.8 seconds inserted 10000000 Rows, about 347K ops/s
 storage size: 17167172021 Bytes

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
