### PR TITLE
[Enhancement] (nereids)implement DropWorkloadPolicyCommand in nereids

### LINKED ISSUE #42622: [Enhancement] (nereids)implement dropDatabase command in nereids
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

DropWorkloadPolicyCommand is available in the legacy planner but needs implementation in Nereids. The syntax is in DorisParser.g4, and DropWorkloadSchedPolicyStmt.java in the legacy planner can be used for reference.

```unsupportedDropStatement : DROP WORKLOAD POLICY (IF EXISTS)? name=identifierOrText```

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #42622 

Related PR: #xxx

Problem Summary:
implement DropWorkloadPolicyCommand in nereids
### Release note

None

### Check List (For Author)

- Test 
    - [X] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Comment by LiBinfeng-01** [comment]
run p0

**Review by LiBinfeng-01 — APPROVED** [review]

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
