### PR TITLE
[fix](analyzer) InferFilterRule bug: equations in on clause of outer/anti join  are not inferable.

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes
`A left join B on A.id=B.id and B.id in (1,2) where a_id<100`
WhereClause triggers InferFilterRule: 
 { `A.id=B.id`,   `B.id in (1,2)` } => `A.id in (1,2)`
inference `A.id in (1,2)`  is incorrect.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
Add some regression test please.

**Comment by starocean999** [comment]
LGTM

**Review by dataroaring — CHANGES_REQUESTED** [review]
We should add a regression test under regression-test.

**Comment by englefly** [comment]
I already add ut to check this incorrectly inference.

**Review by morrySnow — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
