### PR TITLE
[fix](tvf) s3 tvf specify region and s3.region params failed

### LINKED ISSUE #19920: [Bug] s3 tvf specify region params failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master latest

### What's Wrong?

select * from s3(
"uri"="http://{endpoint}/test}test.csv",
"use_path_style"="true",
"s3.access_key"="ak",
"s3.secret_key"="sk",
"s3.region"="region",
"format"="csv"
)

Caused by: java.sql.SQLException: errCode = 2, detailMessage = parse file failed, path = s3://test/test.csv

select * from s3(
"uri"="http://{endpoint}/{bucket}/test.csv",
"use_path_style"="true",
"s3.access_key"="ak",
"s3.secret_key"="sk",
"region"="region",
"format"="csv"
)

errCode = 2, detailMessage = S3TvfBroker list path exception. path=s3://test/test.csv, err: errCode = 2, detailMessage = S3TvfBroker list path failed. path=s3://test/test.csv,msg=errors while get file status Required property 's3.region' when region is not in endpoint.

### What You Expected?

execution success

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lvshaokang**
# Proposed changes

Issue Number: close #19920

## Problem summary

fix s3 tvf specify region and s3.region params failed

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by lvshaokang** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.38 seconds
 stream load tsv:          420 seconds loaded 74807831229 Bytes, about 169 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          80.5 seconds inserted 10000000 Rows, about 124K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230522071840_clickbench_pr_148166.html

**Comment by lvshaokang** [comment]
cc @TangSiyang2001 @Yukang-Lian

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.27 seconds
 stream load tsv:          421 seconds loaded 74807831229 Bytes, about 169 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          78.2 seconds inserted 10000000 Rows, about 127K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230523155907_clickbench_pr_149209.html

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by TangSiyang2001** [comment]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by lvshaokang** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.23 seconds
 stream load tsv:          450 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          76.5 seconds inserted 10000000 Rows, about 130K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230524055225_clickbench_pr_149464.html

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run  buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.37 seconds
 stream load tsv:          455 seconds loaded 74807831229 Bytes, about 156 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          26.0 seconds inserted 10000000 Rows, about 384K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230525015936_clickbench_pr_150041.html

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.53 seconds
 stream load tsv:          443 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.7 seconds inserted 10000000 Rows, about 389K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230525061150_clickbench_pr_150231.html

**Comment by lvshaokang** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.76 seconds
 stream load tsv:          449 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          79.8 seconds inserted 10000000 Rows, about 125K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230525172143_clickbench_pr_150793.html

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run p0

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.7 seconds
 stream load tsv:          443 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.7 seconds inserted 10000000 Rows, about 389K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526132119_clickbench_pr_151343.html

**Comment by lvshaokang** [comment]
run buildall

**Comment by lvshaokang** [comment]
run p0

**Comment by freemandealer** [comment]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
