### PR TITLE
[improvement](doc)statement error in data-model

### PR DESCRIPTION
**Pull request by fuchanghai**
# Proposed changes

this PR close :
- #19739 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by fuchanghai** [comment]
@stalary PTAL

**Review by stalary — COMMENTED** [review]
LGTM

**Comment by stalary** [comment]
run build all

**Review by zy-kkk — APPROVED** [review]

**Comment by stalary** [comment]
run build all

**Comment by zy-kkk** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
