### PR TITLE
[fix](Nereids) array_difference and array_position get wrong result

### PR DESCRIPTION
**Pull request by morrySnow**
## Proposed changes

Issue Number: close #xxx

1. change array_difference signature to let it return same type as arg
2. do not change precision when signature not use wildcard type

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by shuke987 — COMMENTED** [review]
please remove nereids_scalar_fn_Array from https://github.com/apache/doris/blob/5c2fae7ce523e496e9968730e2dc88c792e46926/regression-test/pipeline/p0/conf/regression-conf.groovy#L57C18-L57C41

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162125462 Bytes

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.04 seconds
 stream load tsv:          543 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.7 seconds inserted 10000000 Rows, about 336K ops/s
 storage size: 17162022364 Bytes

**Review by starocean999 — APPROVED** [review]

**Review by Kikyou1997 — APPROVED** [review]

**Pull request merged**
