### PR TITLE
[Improvement](LDAP Auth)Enhance LDAP authentication with a configurable group filter

### PR DESCRIPTION
**Pull request by nsivarajan**
## Proposed changes

This PR enhances LDAP authentication by adding an optional configurable filter for retrieving user groups, primarily to support Open Directory LDAP implementations. If the configurable property is left empty, the existing workflow will remain unchanged.

### CODE REVIEW

**Comment by nsivarajan** [comment]
run buildall

**Comment by nsivarajan** [comment]
run buildall

**Review by zddr — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by nsivarajan** [comment]
@morningman @zddr Please could you assist in merging this PR

**Pull request merged**
