### PR TITLE
[bugfix](core) fmt lost one parameter

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

bug is introduced by https://github.com/apache/doris/pull/40542

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
