### PR TITLE
[Fix](View)Use the element_at function to replace %element_extract% to prevent parsing errors

### PR DESCRIPTION
**Pull request by CalvinKirs**
This is my sql. When I create such a view, it shows that the creation failed. The log is as follows. I observed that when the query statement was generated, `%element_extract%` did not have single quotes, which caused a parsing error, so I used `element_at` for replacement.
```

CREATE TABLE `test1` (

`id` int(11) NULL COMMENT "",
`field1` DATEV2,
  `field2` varchar(1000),
    `field3` varchar(1000),
    `field4` ARRAY<STRING>,
    `field5` ARRAY<STRING>

) ENGINE=OLAP

DUPLICATE KEY(`id`)

COMMENT "OLAP"

DISTRIBUTED BY HASH(`id`) BUCKETS 1

PROPERTIES (

"replication_allocation" = "tag.location.default: 1",

"in_memory" = "false",

"storage_format" = "V2"

);

show tables


CREATE VIEW view_array AS
SELECT id, dm, pn, field3, ms, ek[sm] AS ek
FROM
(
    SELECT
        id, dm, pn, field3, ek, ms, tmp,
        SUM(tmp) OVER (PARTITION BY id, dm, pn, field3 ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS sm
    FROM
    (
        SELECT
            a.id AS id,
            a.field1 AS dm,
            a.field2 AS pn,
            field3,
            field4 AS ek,
            field5 AS ms,
            1 AS tmp
        FROM
        (
            SELECT * FROM test1 LATERAL VIEW explode(field4) test2 AS mension
        ) a
    ) b
) c;

```

```fe.log
2023-08-16 20:08:24,014 INFO (mysql-nio-pool-4|2136) [View.init():171] stmt is SELECT `id` AS `id`, `dm` AS `dm`, `pn` AS `pn`, `brand` AS `brand`, `ms` AS `ms`, %element_extract%(`ek`, `sm`) AS `ek` FROM (SELECT `id` AS `id`, `dm` AS `dm`, `pn` AS `pn`, `brand` AS `brand`, `ek` AS `ek`, `ms` AS `ms`, `tmp` AS `tmp`, sum(`tmp`) OVER (PARTITION BY `id`, `dm`, `pn`, `brand` ORDER BY `id` ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS `sm` FROM (SELECT `a`.`id` AS `id`, `a`.`datamonth` AS `dm`, `a`.`platformname` AS `pn`, `brand` AS `brand`, `evalkeyword` AS `ek`, `mension` AS `ms`, 1 AS `tmp` FROM (SELECT `default_cluster:calvin`.`array_test`.`id` AS `id`, `default_cluster:calvin`.`array_test`.`datamonth` AS `datamonth`, `default_cluster:calvin`.`array_test`.`platformname` AS `platformname`, `default_cluster:calvin`.`array_test`.`brand` AS `brand`, `default_cluster:calvin`.`array_test`.`thrddimension` AS `thrddimension`, `default_cluster:calvin`.`array_test`.`evalkeyword` AS `evalkeyword`, `mension` AS `mension` FROM `default_cluster:calvin`.`array_test` lateral view explode(`default_cluster:calvin`.`array_test`.`thrddimension`) array_test1 as mension) a) b) c
2023-08-16 20:08:24,014 INFO (mysql-nio-pool-4|2136) [View.init():172] exception because: 
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error
	at org.apache.doris.analysis.SqlParser.unrecovered_syntax_error(SqlParser.java:2822) ~[classes/:?]
	at java_cup.runtime.lr_parser.parse(lr_parser.java:619) ~[java-cup-runtime-0.11-a-czt01-cdh.jar:?]
	at org.apache.doris.common.util.SqlParserUtils.getFirstStmt(SqlParserUtils.java:46) ~[classes/:?]
	at org.apache.doris.catalog.View.init(View.java:169) ~[classes/:?]
	at org.apache.doris.catalog.Env.createView(Env.java:4798) ~[classes/:?]
	at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:238) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:2196) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:736) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:448) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:419) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:441) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:589) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:829) ~[classes/:?]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]

```

**Affects version** 2.0 1.2.6

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run clickbench-new (clickbench)

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run External Regression (Doris External Regression)

**Comment by CalvinKirs** [comment]
run clickbench-new (clickbench)

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.67 seconds
 stream load tsv:          539 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17161931569 Bytes

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.96 seconds
 stream load tsv:          535 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162160858 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.16 seconds
 stream load tsv:          538 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17161933541 Bytes

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.91 seconds
 stream load tsv:          544 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162086320 Bytes

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.87 seconds
 stream load tsv:          539 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162164478 Bytes

**Comment by CalvinKirs** [comment]
run FE UT (Doris FE UT)

**Comment by CalvinKirs** [comment]
run P0 Regression (Doris Regression)

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.61 seconds
 stream load tsv:          538 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17162045201 Bytes

**Review by morrySnow — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
