### PR TITLE
[chore](clang-tidy): add bugprone linters

### PR DESCRIPTION
**Pull request by py023**
## Proposed changes

This PR introduces 4 bugprone linter rules to .clang-tidy, these linters found some bugs in #28965. This PR also add some comments to mute false positive reports.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
