### PR TITLE
[improvement](fdb) add a tool which deploys and starts fdb

### PR DESCRIPTION
**Pull request by dataroaring**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Review by yagagagaga — APPROVED** [review]
This script is very convenient.

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — CHANGES_REQUESTED** [review]
too large binary

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — DISMISSED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by gavinchou** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
