### PR TITLE
[fix](regression-test) fix non stable case test_bitmap_index

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Wrong wait getJobState make this case not stable.

**Master && Branch2.0** both have this problem.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
