### PR TITLE
[performance](Planner): optimize getStringValue() in DateLiteral

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

- reduce cost of `getStringValue()` 
- original code don't consider `microsecond` part in `getStringValue()`

run 1000000 times `getStringValue()`
original: 6789ms
now: 2353ms 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
