### PR TITLE
[Fix](binlog) Add more log for ingest_binlog && Fix ingest_binlog not rewrite rowset_meta tablet_uid

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add more log for ingest_binlog && Fix ingest_binlog not rewrite rowset_meta tablet_uid

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by JackDrogon** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
