### PR TITLE
[Fix](regression) Fix flaky test `fault_injection_p0/cloud/test_cloud_mow_stale_resp_load_load_conflict`

### PR DESCRIPTION
**Pull request by bobhan1**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary: `ADMIN SET FRONTEND CONFIG()` will only update the config of the connected FE, which may lead to unexpected result for some cases if the connected FE is not master FE. should use `ADMIN SET FRONTEND CONFIG()` instead.

### Check List (For Author)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [x] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run cloud_p0

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
