### PR TITLE
[enhance](Cloud) Use http action to fetch instance's enable storage vault field instead of using regression's conf

### PR DESCRIPTION
**Pull request by ByteYue**
## Proposed changes

Issue Number: close #xxx

Formerly i tried to use conf to control if the case of storage vault should be skipped or not. It's proved to be error prone and 
is easy to forget set the correct value. So i use the http action to directly fetch the instance's status to do this check.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Review by pingchunzhang — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by platoneko — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
