### PR TITLE
[Bug](broker load) fix hll_hash(null) in broker load report incorrect Exception

### LINKED ISSUE #16294: [Bug](broker load) hll_hash(null) report incorrect exception `label already used`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunck

### What's Wrong?

create a broker load with `set (coln = hll_hash(null))`, an exception reported. It shows `label already used`.

stack:
```
2023-01-31 17:16:18,852 WARN (pending_load_task_scheduler_pool-0|172) [LoadTask.exec():73] LOAD_JOB=10031, error_msg={Unexpected failed to execute load task}
java.lang.NullPointerException: null
	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1192) ~[?:1.8.0_342]
	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1186) ~[?:1.8.0_342]
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376) ~[?:1.8.0_342]
	at java.util.TreeMap.getEntry(TreeMap.java:345) ~[?:1.8.0_342]
	at java.util.TreeMap.containsKey(TreeMap.java:232) ~[?:1.8.0_342]
	at org.apache.doris.analysis.DataDescription.validateHllHash(DataDescription.java:374) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.analysis.DataDescription.validateMappingFunction(DataDescription.java:230) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.Load.initColumns(Load.java:1036) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.Load.initColumns(Load.java:946) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.planner.BrokerScanNode.initColumns(BrokerScanNode.java:271) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.planner.BrokerScanNode.initParams(BrokerScanNode.java:234) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.planner.BrokerScanNode.init(BrokerScanNode.java:179) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.LoadingTaskPlanner.plan(LoadingTaskPlanner.java:127) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.LoadLoadingTask.init(LoadLoadingTask.java:107) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.BrokerLoadJob.createLoadingTask(BrokerLoadJob.java:207) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.BrokerLoadJob.onPendingTaskFinished(BrokerLoadJob.java:166) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.BrokerLoadJob.onTaskFinished(BrokerLoadJob.java:125) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:65) ~[doris-fe.jar:1.0-SNAPSHOT]
	at org.apache.doris.task.MasterTask.run(MasterTask.java:31) ~[doris-fe.jar:1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_342]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
```

### What You Expected?

report ` Column is not in sources, column: null`

### How to Reproduce?

as mentioned above.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Henry2SS**
# Proposed changes

Issue Number: close #16294 

## Problem summary

tested locally. problem is solved.

The main reason is that `columnNameMap` is a TreeMap instance. And an `NullPointerException` will be reported when the key of `TreeMap.contains(key)` is `null`. 

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caiconghui — COMMENTED** [review]
please add ut

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.82 seconds
 load time: 518 seconds
 storage size: 17122749779 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230131130610_clickbench_pr_87932.html

**Comment by Henry2SS** [comment]
> please add ut

done.

**Review by caiconghui — APPROVED** [review]
LGTM

**Pull request merged**
