### PR TITLE
[fix](Nereids) fix some sql cache consistence bug between multiple frontends

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

1. fix some sql cache consistence bug between multiple frontends which introduced by #33262, fix by use row policy as the part of sql cache key. 
2. support dynamic update the num of fe manage sql cache key

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by yiguolei — CHANGES_REQUESTED** [review]
Sync between multi FEs is very difficult.
We could simply using consistency hash like memcache to solve the problem.

**Comment by 924060929** [comment]
> Sync between multi FEs is very difficult. We could simply using consistency hash like memcache to solve the problem.

there hasn't any sync logic in this pr

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
