### PR TITLE
[fix](sys_table) fix potential NPE when query table_properties and partitions sys table

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #xxx

 fix potential NPE when query table_properties and partitions sys table
follow up for #40944

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Vallishp** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
