### PR TITLE
[fix](regression-test) fix multi-thread problem of regression-test

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

use local variable in regression-test to avoid multi-thread problem.

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @shuke987 for the fix.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
