### PR TITLE
[improve](txn-insert) Add txn insert p2 case

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Add a p2 case for txn insert.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add delete and update too. BTW, please add cases for merge on write table specifically in p2, especially there should be a  case enable partial update for insert into select.

**Review by gavinchou — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
