### PR TITLE
[feature](ui) add profile download button in the list page

### PR DESCRIPTION
**Pull request by jeffreys-cat**
## Proposed changes

**add profile download button in the list page**

image

**set sql-statement max width:700**

image

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
