### PR TITLE
[typo](docs) Update compile Dockerfile in developer

### PR DESCRIPTION
**Pull request by FreeOnePlus**
Adjust the default JDK version of the Docker build image from JDK-11 to JDK-1.8.0
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Why downgrade the version of JDK?

**Comment by yiguolei** [comment]
As we disscussed in email and wechat, doris will support jdk 8 as default jdk so I will merge it.

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
