### PR TITLE
[fix](fe) Remove cloudWarmUpJob from DEPRECATED_MODULES_NAMES

### PR DESCRIPTION
**Pull request by w41ter**
It was accidentally introduced in PR #32804.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by gavinchou — DISMISSED** [review]

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
