### PR TITLE
[Fix](single replica load) fix indices_size key not found core

### LINKED ISSUE #20046: [Bug] indices_size key not found cause single_replica_load BE coredump
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

streamload enable single_replica_load，PTabletWriteSlaveRequest_IndexSizeMap key not found, which caused coredump in BE.

    google::protobuf::Map<int64, PTabletWriteSlaveRequest_IndexSizeMap> indices_size =
            request->inverted_indices_size(); 

F0524 21:58:15.057839 1302291 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 1
F0524 21:58:15.057839 1302291 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 1F0524 21:58:15.682101 1302292 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0
F0524 21:58:15.057839 1302291 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 1F0524 21:58:15.682101 1302292 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.073918 1302297 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0
F0524 21:58:15.057839 1302291 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 1F0524 21:58:15.682101 1302292 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.073918 1302297 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.137092 1302295 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0
F0524 21:58:15.057839 1302291 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 1F0524 21:58:15.682101 1302292 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.073918 1302297 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.137092 1302295 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0F0524 21:58:16.141532 1302296 global.cpp:309] /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214 CHECK failed: it != end(): key not found: 0
core:

#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50 ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4216926700 (LWP 1172644))]
(gdb) bt
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1 0x00007f43c4bea859 in __GI_abort () at abort.c:79
#2 0x000055a0f047ccc9 in ?? ()
#3 0x000055a0f04722dd in google::LogMessage::Fail() ()
#4 0x000055a0f0474819 in google::LogMessage::SendToLog() ()
#5 0x000055a0f0471e46 in google::LogMessage::Flush() ()
#6 0x000055a0f0474e89 in google::LogMessageFatal::~LogMessageFatal() ()
#7 0x000055a0f0cb0226 in ?? ()
#8 0x000055a0f0e68545 in google::protobuf::internal::LogMessage::Finish() ()
#9 0x000055a0e9ea10ef in google::protobuf::Map<long, doris::PTabletWriteSlaveRequest_IndexSizeMap>::at<long> (
key=@0x7f4184f3bcc0: 1, this=0x7f42b26ef160)
at /mnt/disk1/chenkaijie/doris/thirdparty/installed/include/google/protobuf/map.h:1214
#10 operator() (__closure=0x7f42b26ef000) at /mnt/disk1/chenkaijie/doris/be/src/service/internal_service.cpp:1315
#11 0x000055a0e92f7250 in std::function<void ()>::operator()() const (this=0x7f421691f728)
at /mnt/disk1/chenkaijie/env/ldb_toolchain/include/c++/11/bits/std_function.h:560
#12 doris::PriorityThreadPool::work_thread (this=<optimized out>, thread_id=<optimized out>)
at /mnt/disk1/chenkaijie/doris/be/src/util/priority_thread_pool.hpp:146
#13 0x000055a0f33db8d0 in std::execute_native_thread_routine (__p=0x7f43981ec3e0)
at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#14 0x00007f43c4f11609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f43c4ce7163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

### What You Expected?

check key is not found

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by airborne12**
# Proposed changes

Issue Number: close #20046

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.05 seconds
 stream load tsv:          445 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.5 seconds inserted 10000000 Rows, about 392K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230525075929_clickbench_pr_150312.html

**Comment by airborne12** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.34 seconds
 stream load tsv:          445 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          82.2 seconds inserted 10000000 Rows, about 121K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230525110151_clickbench_pr_150473.html

**Comment by airborne12** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.42 seconds
 stream load tsv:          448 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          78.4 seconds inserted 10000000 Rows, about 127K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526005316_clickbench_pr_150845.html

**Review by kaijchen — APPROVED** [review]
LGTM, single_replica_load works fine with this patch.

**Comment by airborne12** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.55 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          26.0 seconds inserted 10000000 Rows, about 384K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526140853_clickbench_pr_151396.html

**Comment by airborne12** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.64 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          25.6 seconds inserted 10000000 Rows, about 390K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526183929_clickbench_pr_151677.html

**Review by dataroaring — APPROVED** [review]
lgtm

**Pull request merged**
