### PR TITLE
[fix](multi-catalog)Thrift metastore URI reverse resolution could fail in some environments

### PR DESCRIPTION
**Pull request by tarepanda1024**
## Proposed changes

When custom URI resolver is not specified, the default thrift metastore URI goes through DNS reverse resolution (getCanonicalHostname) which is unlikely to resolve correctly when the HMS is sitting behind LBs and proxies. This is a change in behaviour from hive 2.x branch which isn't required. If reverse resolution is required, custom URI resolver can be implemented.

apache hive have repaired this bug: https://github.com/apache/hive/pull/2933

### CODE REVIEW

**Comment by tarepanda1024** [comment]
run buildall

**Review by dutyu — APPROVED** [review]
LGTM

**Comment by dutyu** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.82 seconds
 stream load tsv:          530 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162198024 Bytes

**Comment by dutyu** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.5 seconds
 stream load tsv:          545 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162095751 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by tarepanda1024** [comment]
Hello, this PR has been marked as Reviewed and approved, when will it be merged into the main branch? 😂 @dutyu @dataroaring  Can you help find someone to merge it into the main branch? 😅

**Review by morningman — APPROVED** [review]

**Comment by tarepanda1024** [comment]
run buildall

**Comment by tarepanda1024** [comment]
run buildall

**Pull request closed without merging**
