### PR TITLE
[doc](fix) a new docs for k8s deploy by operator

### PR DESCRIPTION
**Pull request by catpineapple**
## Proposed changes

Issue Number: close #xxx

a new docs for k8s deploy by operator

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by catpineapple** [comment]
run builall

**Comment by zhangguoqiang666** [comment]
run buildall

**Pull request merged**
