### PR TITLE
[fix](nereids) map literal to double in FilterSelectivityCalculator

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes
1. fix literal to double bug: all literal type implements getDouble() function

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
4. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
5. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
6. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
7. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.66 seconds
 load time: 556 seconds
 storage size: 17154655417 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221028163542_clickbench_pr_35520.html

**Comment by 924060929** [comment]
Literal.getDouble() should supply a default value without throw exception.
```java
public double getDouble() {
    try {
        return Double.parseDouble(getValue().toString());
    } catch (Throwable t) {
        return Double.NaN;
    }
}
```

**Comment by englefly** [comment]
> ```java
> parseDouble
> ```

Good idea.

**Comment by englefly** [comment]
> Literal.getDouble() should supply a default value without throw exception.
> 
> for example:
> 
> ```java
> public double getDouble() {
>     try {
>         return Double.parseDouble(getValue().toString());
>     } catch (Throwable t) {
>         return Double.NaN;
>     }
> }
> ```
> 
> org.apache.commons.lang3.math.NumberUtils is also alternatives
> 
> ```java
> public double getDouble() {
>     return NumberUtils.toDouble(getValue().toString(), Double.NaN);
> }
> ```

Good idea! thx

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
