### PR TITLE
Import new ThreadPool framework

### PR DESCRIPTION
**Pull request by chaoyli**
[gutil] import scoped_refptr smart pointer from KUDU
    scoped_refptr is used to replace std::shared_ptr, is generally faster and smaller.
    advantage
      (1) only requires a single allocation, and ref count is on the same cache line as the object
      (2) the pointer only requires 8 bytes (since the ref count is within the object)
      (3) you can manually increase or decrease reference counts when more control is required
      (4) you can convert from a raw pointer back to a scoped_refptr safely without worrying about double freeing
      (5) since we control the implementation, we can implement features, such as debug builds that capture the stack trace of every referent to help debug leaks.
    disadvantage
      (1) the referred-to object must inherit from RefCounted
      (2) does not support the weak_ptr use cases

### CODE REVIEW

**Review by morningman — CHANGES_REQUESTED** [review]
Missing ISSUE and DESIGN DOC

**Comment by chaoyli** [comment]
#2896

**Comment by chaoyli** [comment]
This patch imports many basis class.
1. scoped_refptr
    scoped_refptr is used to replace std::shared_ptr,  is generally faster and smaller.
    And also we can manually increase or decrease reference counts when more control is required.
2. MonoTime
    The MonoTime represents a particular point in time, relative to some fixed but unspecified reference point.
3. MonoDelta
    The MonoDelta class represents an elapsed duration of time, the delta between two MonoTime instances.

**Comment by chaoyli** [comment]
Thread pool with a variable number of threads.
All tasks submitted directly to the thread pool enter a FIFO queue and are
dispatched to a worker thread when one becomes free. Tasks may also be
submitted via ThreadPoolTokens. The token Wait() and Shutdown() functions
can then be used to block on logical groups of tasks.

A token operates in one of two ExecutionModes, determined at token
construction time:
1. SERIAL: submitted tasks are run one at a time.
2. CONCURRENT: submitted tasks may be run in parallel. This isn't unlike
    tasks submitted without a token, but the logical grouping that tokens
    impart can be useful when a pool is shared by many contexts (e.g. to
    safely shut down one context, to derive context-specific metrics, etc.).

Tasks submitted without a token or via ExecutionMode::CONCURRENT tokens are
processed in FIFO order. On the other hand, ExecutionMode::SERIAL tokens are
processed in a round-robin fashion, one task at a time. This prevents them
from starving one another. However, tokenless (and CONCURRENT token-based)
tasks can starve SERIAL token-based tasks.

```
Usage Example:
std::unique_ptr<ThreadPool> thread_pool;
CHECK_OK(
      ThreadPoolBuilder("my_pool")
            .set_min_threads(0)
            .set_max_threads(5)
            .set_max_queue_size(10)
            .set_idle_timeout(MonoDelta::FromMilliseconds(2000))
            .build(&thread_pool));
     thread_pool->submit(shared_ptr<Runnable>(new Task()));
```

**Comment by chaoyli** [comment]
Thread design point:
1. It is a thin wrapper around pthread that can register itself with the singleton ThreadMgr
(a private class implemented in thread.cpp entirely, which tracks all live threads so
that they may be monitored via the debug webpages). This class has a limited subset of
boost::thread's API. Construction is almost the same, but clients must supply a
category and a name for each thread so that they can be identified in the debug web
UI. Otherwise, join() is the only supported method from boost::thread.
2. Each Thread object knows its operating system thread ID (TID), which can be used to
attach debuggers to specific threads, to retrieve resource-usage statistics from the
operating system, and to assign threads to resource control groups.
3. Threads are shared objects, but in a degenerate way. They may only have
up to two referents: the caller that created the thread (parent), and
the thread itself (child). Moreover, the only two methods to mutate state
(join() and the destructor) are constrained: the child may not join() on
itself, and the destructor is only run when there's one referent left.
These constraints allow us to access thread internals without any locks.

**Comment by lingbin** [comment]
Could you please split this PR into multiple commits?
For example:
1. import some gutil
2. import some util
3. import new thread-pool
4. some refactor on current code

**Pull request closed without merging**
