### PR TITLE
[typo](docs) Add docs of math function

### PR DESCRIPTION
**Pull request by TaoZex**
# Proposed changes

Issue Number: 

## Problem summary

I found that a lot of math function documentation was missing, so I filled it in.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TaoZex** [comment]
Do I need to submit again in doris-website?

**Comment by TaoZex** [comment]
@zy-kkk Could you please help me review these documents?Thanks.

**Review by zy-kkk — CHANGES_REQUESTED** [review]
Thanks for your invitation. Like PR #12713, you will add these document paths to sidebars.json. Another problem is that the documentation in the Doris repository corresponds to the `DEV documentation` on the official website; If you want these documents to display in the `1.1  document`, you need to `Doris-website` submission, please refer to the [Docs Contribute](https://doris.apache.org/community/how-to-contribute/contribute-doc), But you need to verify on `Doris-1.1` that these functions are OK. Finally, the PR title format for the document class is `[typo](docs)`, please change it

**Comment by TaoZex** [comment]
> Thanks for your invitation. Like PR #12713, you will add these document paths to sidebars.json. Another problem is that the documentation in the Doris repository corresponds to the `DEV documentation` on the official website; If you want these documents to display in the `1.1 document`, you need to `Doris-website` submission, please refer to the [Docs Contribute](https://doris.apache.org/community/how-to-contribute/contribute-doc), But you need to verify on `Doris-1.1` that these functions are OK. Finally, the PR title format for the document class is `[typo](docs)`, please change it
I have added these document paths to sidebars.json
In the doris-website repository, I also made a document submission, the link is as follows: https://github.com/apache/doris-website/pull/103
At the same time,I have changed the PR title format.Please review it again, thanks.

**Comment by TaoZex** [comment]
> > Thanks for your invitation. Like PR #12713, you will add these document paths to sidebars.json. Another problem is that the documentation in the Doris repository corresponds to the `DEV documentation` on the official website; If you want these documents to display in the `1.1 document`, you need to `Doris-website` submission, please refer to the [Docs Contribute](https://doris.apache.org/community/how-to-contribute/contribute-doc), But you need to verify on `Doris-1.1` that these functions are OK. Finally, the PR title format for the document class is `[typo](docs)`, please change it
> > I have added these document paths to sidebars.json
> > In the doris-website repository, I also made a document submission, the link is as follows: [apache/doris-website#103](https://github.com/apache/doris-website/pull/103)
> > At the same time,I have changed the PR title format.Please review it again, thanks.

ok

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by TaoZex** [comment]
@zy-kkk In P1 Regression, the details of the error message are as follows:
details
I submitted code to the doris community once before, and the CI pipeline also encountered an error that the Mysql server could not be connected. What does this problem mean? Is it a problem with my code?

**Comment by zy-kkk** [comment]
> @zy-kkk In P1 Regression, the details of the error message are as follows: details I submitted code to the doris community once before, and the CI pipeline also encountered an error that the Mysql server could not be connected. What does this problem mean? Is it a problem with my code?

This doesn't seem to be your problem, you can rebase your branch, or update the branch directly on Github-Web
image

**Comment by TaoZex** [comment]
> > @zy-kkk In P1 Regression, the details of the error message are as follows: details I submitted code to the doris community once before, and the CI pipeline also encountered an error that the Mysql server could not be connected. What does this problem mean? Is it a problem with my code?
> 
> This doesn't seem to be your problem, you can rebase your branch, or update the branch directly on Github-Web image

I've updated the branch directly on Github-Web, and the recommit goes through the CI pipeline. I am curious about the reason why the Mysql connection failed before, so I plan to consult with discuss. May require you to approve again.

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
