### PR TITLE
[fix](ipv6)fix can not resolve host and port

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

for ipv6,address should be `[ip]:port` instead of `ip:port`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Please explain details in PR comment

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM
BTW, we need to find a way to test IPV6 in regression test

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
