### PR TITLE
[minor](docs) update docs for variable sql_select_limit

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run builall

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run buildall

**Pull request merged**
