### PR TITLE
[Fix](JobManager)Release the lock immediately after modifying job metadata to avoid holding the lock for an extended period.

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes

When deleting a job in MV, a DB lock is held. However, due to the larger lock granularity of the Job Manager, this may prevent obtaining the lock. This issue arises because during the creation of a job, immediately scheduled tasks need to perform their initial scheduling and compensate for tasks within the time window. To alleviate this issue, we are attempting to reduce the lock granularity.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by yiguolei** [comment]
run  buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run cloud_p0

**Comment by CalvinKirs** [comment]
run cloud_p0

**Pull request merged**
