### PR TITLE
[fix](memory) arena support memory reuse after clear()

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

In the past, MemPool also used clear() to reuse memory. after replacing it with Arena, the performance of predicate column and agg is low. 

After Arena also support clear(), the performance was the same as MemPool

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — COMMENTED** [review]
recheck all place use area reuse the mem?

**Comment by xinyiZzz** [comment]
> recheck all place use area reuse the mem?

I only found these two places,
In #7820, I deleted some mem_pool.clear(), only these two places are valid

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
> recheck all place use area reuse the mem?

some places arena.reset has also been changed to clear, cc

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 43.11 seconds
 stream load tsv:          466 seconds loaded 74807831229 Bytes, about 153 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          69.2 seconds inserted 10000000 Rows, about 144K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230621135732_clickbench_pr_166285.html

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
