### PR TITLE
[fix](date) return right date value even if out of the range of date dictionary

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

PR(https://github.com/apache/doris/pull/22360) and PR(https://github.com/apache/doris/pull/22384) optimized the performance of date type. However hive supports date out of 1970~2038, leading wrong date value in tpcds benchmark.
How to fix:
1. Increase dictionary range: 1900 ~ 2038
2. The date out of 1900 ~ 2038 is regenerated.

## Performance
Single thread to scan 512000000 rows:
| date range | \<1900 | 1900 ~ 2038 | \> 2038 |
|  ----  | ----  | ---- | ---- |
| previous PR. | - | 11.92s | - |
| this PR. |  37.87s | 12.73s | 40.67s |

## Remaining problems
Date like `0002-11-30` will be generated wrongly.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.89 seconds
 stream load tsv:          552 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162105591 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Review by wsjz — APPROVED** [review]
LGTM

**Pull request merged**
