### PR TITLE
[Fix](cloud) Auto start support `MANUAL_SHUTDOWN` status

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

Issue Number: close #xxx

cloud saas 自动拉起功能，增加用户手动关闭cluster功能

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
update description to english please

**Comment by deardeng** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
