### PR TITLE
[branch-2.0](fe ut) make colcoate test wait time longer (#26999)

### PR DESCRIPTION
**Pull request by yujun777**
pick: #26999

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run arm

**Comment by yujun777** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
