### PR TITLE
[fix](bitmap) fix bitmap iterator comparison error

### LINKED ISSUE #15797: [Bug] inbitmap query result is incorrect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master, 1.2

### What's Wrong?

```
mysql> select * from baseall where k1 in (select to_bitmap(10));
Empty set (0.10 sec)
```

### What You Expected?

```
mysql> select * from baseall where k1 in (select to_bitmap(10));
+------+------+------+------+---------------------+----------+-------+------------+---------------------+-----------+------------+-------+-------------+-----------+
| k0   | k1   | k2   | k3   | k4                  | k5       | k6    | k10        | k11                 | k7        | k8         | k9    | k12         | k13       |
+------+------+------+------+---------------------+----------+-------+------------+---------------------+-----------+------------+-------+-------------+-----------+
|    1 |   10 | 1991 | 5014 | 9223372036854775807 | -258.369 | false | 2015-04-02 | 2013-04-02 15:16:52 | wangynnsf | -123456.54 | 0.235 | string12345 | -11011903 |
+------+------+------+------+---------------------+----------+-------+------------+---------------------+-----------+------------+-------+-------------+-----------+
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #15797

## Problem summary

The problem is caused by the fact that `bitmap.begin() == bitmap.end()` is always true when the bitmap contains a single value.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.15 seconds
 load time: 518 seconds
 storage size: 17122265584 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230110154814_clickbench_pr_77013.html

**Comment by morningman** [comment]
please link to an issue

**Comment by luozenglin** [comment]
> please link to an issue

done

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
