### PR TITLE
[Chore](inverted index) remove useless code of compound filters for inverted index

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Remove useless code from scan operator to scanner for inverted index compound filter

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run cloud_p1

**Review by qidaye — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
