### PR TITLE
[fix](group commit) Fix some wal problems on group commit

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
Fix these problems:
1. Sql Syntax
2. complex type, like array,bitmap
3. there is more than one wal in the same table, the map they shared should be clear before reusing again
4. add a thread pool for replaying wal
5. add find partition function on group commit sink to filter invalid record
6. fix relay wal core problem when doing stream load meet exception 

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
