### PR TITLE
[Chore](inverted index) change Status::EndOfFile to just logging info,remove useless print

### PR DESCRIPTION
**Pull request by airborne12**
# Proposed changes

Issue Number: close #xxx

## Problem summary

We may get message like 'get bkd reader for column c_date failed: END_OF_FILE' in be log, which made people panic.
It just means bkd index is empy which is normal when column is NULL.
So we remove this logging from it.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
