### PR TITLE
[test](migrate) move 2 cases from p2 to p0

### PR DESCRIPTION
**Pull request by zddr**
releated: https://github.com/apache/doris/pull/36787

1. Extend the exploration time of hive docker
2. move case
- test_hive_remove_partition
- test_hive_statistics_from_hms
- test_hive_partition_column_analyze
- test_hive_parquet_alter_column
- test_hive_analyze_db

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run external

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
