### PR TITLE
[fix](case) add order by in test_javaudaf_return_map (#22824)

### PR DESCRIPTION
**Pull request by Mryange**
add order by in test_javaudaf_return_map

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
This PR is not based on the latest branch-2.0, so regression p0 p1 external failed.
but it only modify the case, so I think it can be merged.

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
