### PR TITLE
[typo](doc)Add flink to read the doris table and use doris.filter.query to configure the display

### PR DESCRIPTION
**Pull request by caoliang-web**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caoliang-web** [comment]
run buildall

**Comment by JNSimba** [comment]
please add in faq

**Comment by caoliang-web** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
