### PR TITLE
[fix](compaction) rowid_conversion should ignore deleted row on normal compaction

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
pr https://github.com/apache/doris/pull/22579 should also consider normal compaction scenario

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by hust-hhb** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
