### PR TITLE
[feat](docker)Add a BE ENV item 'SKIP_CHECK_ULIMIT' for Docker to start quickly

### PR DESCRIPTION
**Pull request by FreeOnePlus**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

In the storage_engine.cpp of the BE process, it is mandatory to check that the `ulimit` value must be greater than 60,000. When starting with Docker or Docker-Compose, it is necessary to preemptively change the corresponding value on the host machine. This change is very unfriendly to Docker, as it loses its unique advantage of being able to "build quickly and anywhere," and cannot become a fundamental capability for rapid startup. Therefore, a new environment variable has been added to control whether to skip this check value. The default value is false, which enforces the check of this value. When set to true, it skips the check and starts directly.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [x] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

1. Execute `ulimit -n 50000` to make it less than the BE check value of 60000.
2. Comment out the part that checks the ulimit size in the start_be.sh script.
3. Add the env`export SKIP_CHECK_ULIMIT = true` configuration item.
4. The BE process can start normally.
5. Add the env`export SKIP_CHECK_ULIMIT = false` configuration item.
6. The BE cannot start, indicating a problem with the ulimit value being too small.

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
run buildall

**Comment by FreeOnePlus** [comment]
run buildall

**Review by catpineapple — DISMISSED** [review]

**Comment by FreeOnePlus** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by FreeOnePlus** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by catpineapple — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
