### PR TITLE
[dependenct](fe) Replace jackson-mapper-asl with fastxml-jsckson

### PR DESCRIPTION
**Pull request by CalvinKirs**
`jackson-mapper-asl` is no longer maintained, and the corresponding CVE has not been resolved.

`fastxml.jsckson` is perfectly compatible with `jackson-mapper-asl`, so I made this PR to make a change.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.41 seconds
 stream load tsv:          474 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230303081103_clickbench_pr_107857.html

**Comment by CalvinKirs** [comment]
run p1

**Comment by carlvinhust2012** [comment]
LGTM

**Comment by CalvinKirs** [comment]
run P1

**Comment by CalvinKirs** [comment]
run P1

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
