### PR TITLE
[fix](load) return Status when error in RowsetWriter::build

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Currently `RowsetWriter::build` returns `nullptr` when failure. The cause of the failure is unknown to the caller.
This change proposed to change `RowsetWriter::build` to return `Status` when failure (return OK if success).

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
