### PR TITLE
[opt](index) add more inverted index profile metrics

### PR DESCRIPTION
**Pull request by xiaokang**
add more inverted index query profile:
- InvertedIndexQueryNullBitmapTime
- InvertedIndexSearcherCacheHit
- InvertedIndexSearcherCacheMiss

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
