### PR TITLE
[docker] Add kafka relate case

### PR DESCRIPTION
**Pull request by XuJianxu**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Comment by XuJianxu** [comment]
run external p0

**Comment by XuJianxu** [comment]
run external

**Comment by XuJianxu** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by XuJianxu** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Comment by XuJianxu** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
