### PR TITLE
[improvement](statistics)Drop table stats in unprotectDropTable so that dropDB could call it as well.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Drop table stats in unprotectDropTable so that dropDB could call it as well.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run external

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p1

**Review by morningman — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
