### PR TITLE
[fix](stats) Escape string when insert stats

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]

**Comment by hello-stephen** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run feut

**Pull request merged**
