### PR TITLE
[bump](fe)upgrade dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
upgrade spark to 3.5.1
upgrade avro to 1.11.3
upgrade netty to 4.1.108-final
upgrade gcs-hadoop to hadoop3-2.2.21
upgrade clickhouse to 6.0.0
upgrade grpc to 1.62.2
upgrade checker to 3.42.0
upgrade snappy-java to 1.10.5
upgrade nimbusds to 9.37.3
upgrade hbase to 2.5.8
upgrade jetty to 9.4.54.v20240208
upgrade zookeeper to 3.9.2
upgrade ivy to 2.5.2

remove quartz
remove hbase client

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Pull request merged**
