### PR TITLE
[fix](cloud) To ensure compatibility with the cloud upgrade

### PR DESCRIPTION
**Pull request by deardeng**
Due to the cloud version being significantly outdated, to ensure compatibility with the cloud version, the version value has been lowered to 123

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by deardeng** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
run

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
