### PR TITLE
[fix](segment) add _pk_index_meta's size to Segment::_meta_mem_usage

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

add _pk_index_meta's size to Segment::_meta_mem_usage
to make memory estimation more accurate.

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
