### PR TITLE
[fix](doc) spell errors fixes for debug-point-action

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

spell errors fixes for debug-point-action

### CODE REVIEW

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
There are some conflicts and please rebase it.

**Review by httpshirley — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
