### PR TITLE
[feat](Nereids): eliminate left outer join by unique when comparing mv

### PR DESCRIPTION
**Pull request by keanji-x**
## Proposed changes

eliminate left outer join by distinct when comparing mv

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jackwener — DISMISSED** [review]

**Comment by XieJiann** [comment]
run buildall

**Review by seawinde — APPROVED** [review]

**Review by jackwener — DISMISSED** [review]

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Comment by XieJiann** [comment]
run buildall

**Review by jackwener — DISMISSED** [review]

**Comment by XieJiann** [comment]
run buildall

**Review by jackwener — APPROVED** [review]

**Pull request merged**
