### PR TITLE
[Enhancement](tvf) Backends tvf supports authentication

### LINKED ISSUE #20328: [Enhancement](tvf) tvf supports authentication
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Take backends tvf for example.
For root user:
MySQL [(none)]> select BackendId from backends();
+-----------+
| BackendId  |
+-----------+
|     10003     |
+-----------+

For user without Node privilege and Admin privilege:
MySQL [(none)]> select BackendId from backends();
+-----------+
| BackendId  |
+-----------+
|     10003     |
+-----------+

We expect to authenticate backends tvf like show backends for user without Node privilege and Admin privilege.
MySQL [(none)]> show backends;
ERROR 1227 (42000): errCode = 2, detailMessage = Access denied; you need (at least one of) the ADMIN/OPERATOR privilege(s) for this operation

### Solution

Add authentication for backends tvf.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yongjinhou**
## Proposed changes

Issue Number: close #20328

Add authentication for backends tvf.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run p0

**Review by morningman — DISMISSED** [review]
Please update the backend tvf doc, to add auth part.

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
> Please update the backend tvf doc, to add auth part.

done

**Comment by yongjinhou** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
