### PR TITLE
[minor](fe) convert `MysqlPassword.twoStageHash` Chinese annotations into English

### PR DESCRIPTION
**Pull request by WinkerDu**
## Proposed changes

Issue Number: close #xxx

Convert `MysqlPassword.twoStageHash` annotations from Chinese into English

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
cc @morningman @chenlinzhong @luozenglin Please take a review, thx

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by zxealous — APPROVED** [review]
LGTM

**Pull request merged**
