### PR TITLE
[Enhancement](group commit) optimize pre allocated calculation

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

For group commit, the data flow is

stream pipe -> group commit sink node -> block load queue -> group commit scan node -> tablet channel
|\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_|  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  |\_\_\_\_\_\_\_\_\_\_\_________________________|
                     outside load  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;                                memory queue              &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;                                 inside load

When group commit is set to async mode, it writes to the Write-Ahead Log (WAL). Specifically, once the group commit sink node writes data into the queue, the WAL is immediately persisted to disk. The 'pre allocated' variable tracks the size of all data in memory during the load process. As data is written to the WAL and persisted, 'pre allocated' should be reduced accordingly. Prior to this PR, the reduction of the 'pre allocated' variable was done only after the import was complete. This approach resulted in a portion of the data, already written to the WAL, still being counted in the 'pre allocated' total, leading to inaccuracies in WAL space calculation. This PR addresses the issue by moving the reduction of the 'pre allocated' variable to immediately after the completion of the group commit sink node operation. This PR  helps to avoid the aforementioned inaccuracies to a certain extent.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Comment by gavinchou** [comment]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
