### PR TITLE
[test](auto partition)increase max_auto_partition_num configure value of auto partition

### PR DESCRIPTION
**Pull request by zfr9527**
…configure value

increase max_auto_partition_num configure value of auto partition 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Comment by zfr9527** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Pull request merged**
