### PR TITLE
[feature](AuditLog) add scanRows scanBytes in auditlog

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

The AuditLog is a somewhat neglected feature, as it has historically seen little usage or configuration. Here, we've added statistics for scanRows and scanBytes and added support for pipelines.

PS: Why not use "profile"?
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run clickbench

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — COMMENTED** [review]
if query has limit，maybe child do not eos. how collect the statistics?

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
