### PR TITLE
[fix](fe-log) add position info in async mode

### PR DESCRIPTION
**Pull request by morningman**
followup #37793
NORMAL:  sync flush + with location
ASYNC(default): async flush + with location
BRIEF: async flush + without location

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

**Comment by caiconghui** [comment]
this config is used to improve log4j performance, so I suggest that to make best performance for brief mode without location  and async flush, and the default config is async which is with location but async flush

**Comment by caiconghui** [comment]
so we need to modify illustration for this config

**Review by zclllyybb — APPROVED** [review]

**Review by caiconghui — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
run buildall

**Comment by morningman** [comment]
run performance

**Pull request merged**
