### PR TITLE
[Fix](Http-API)Check and replace user sensitive characters

### PR DESCRIPTION
**Pull request by CalvinKirs**
if we allowed insert arbitrary data into a log file, the integrity of the chain of events being recorded can be compromised.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.08 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17168663163 Bytes

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by morningman — COMMENTED** [review]
LGTM

**Review by smallhibiscus — APPROVED** [review]

**Pull request merged**
