### PR TITLE
[fix](show-table-status) fix hive view NPE and external meta cache refresh issue

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Fix bug that when there are Hive views, `show table status` will throw NPE
    Should skip Hive view when iterating tables for `show tables status` operation.
2. The table's `getRowCount()` method will try to visit all partitions from cache, which may invalid all previous cache entries.
    when doing `show table status`, do not get partitions from cache.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.63 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17166676523 Bytes

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
