### PR TITLE
[fix](mysql) fix mysql channel infinite blocking

### LINKED ISSUE #28807: [Bug] MySQL channel infinite blocking
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2

### What's Wrong?

image
The thread is infinitely blocked in the "Channels. writeBlocking" method.
Thread resources will never be released.

### What You Expected?

Remove unreasonable infinite blocking

### How to Reproduce?

1. submit a big query
2. send "kill <id>" command to kill the previous query
3. probably reproduce this case

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fornaix**
## Proposed changes

Issue Number: close #28807

## Further comments

Call the Channels blocking method with timeout instead.

Using session variables net_write_timeout and net_read_timeout as the timeout parameter.

### CODE REVIEW

**Comment by yiguolei** [comment]
@fornaix  Hi hi， could you please describe the problem?
Because I meet this problem very frequently "The last packet successfully received from the server was 1,401,847 milliseconds ago. The last packet sent successfully to the server was 1,401,848 milliseconds ago.
"

Does it relate with this PR?

**Comment by fornaix** [comment]
@yiguolei  hi, sure. I found this problem after killing a running query. The query is aborted and there are no running instances in be. But the mysql thread that receives the query is stuck there forever.

>  I meet this problem very frequently

Is this problem also stuck in channel blocking write or read?

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
@fornaix  actually I do not know. because I could not get the jstack.

> I found this problem after killing a running query. The query is aborted and there are no running instances in be. But the mysql thread that receives the query is stuck there forever.

If the query is aborted, and the mysql thread maybe hang in getNext and there is a timeout here. I think I will throw timeout exception.

Could you please explain it more detail?

My wechat number is    monkgrandpa     . Could you please add me, we could talk about it at wechat?

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
@fornaix can you submit a PR to branch-2.0 ?

**Comment by fornaix** [comment]
> @fornaix can you submit a PR to branch-2.0 ?

@xiaokang sure, https://github.com/apache/doris/pull/29374

**Comment by xiaokang** [comment]
> > @fornaix can you submit a PR to branch-2.0 ?
> 
> @xiaokang sure, #29374

tks!

**Pull request merged**
