### PR TITLE
[enhancement](regression-test) add sleep 3s for schema change and rollup

### PR DESCRIPTION
**Pull request by yiguolei**
# Proposed changes

Sometime in regression test, the schema change or rollup finished but it may not be ready, so the regression test is not very stable.

I add sleep 3s after rollup or schema change finished to avoid failure.

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
./run buildall

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
./run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
