### PR TITLE
[chore] rename method name and improve logging and comments

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #xxx
method name, comments and logs improved in be/src folder.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Pull request closed without merging**
