### PR TITLE
[fix](memory) Fix conf `max_sys_mem_available_low_water_mark_bytes`

### PR DESCRIPTION
**Pull request by xinyiZzz**
If users cannot understand the algorithm, it is better not to have it.

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
