### PR TITLE
[Enhancement]Add Field check to avoid create invalid field

### PR DESCRIPTION
**Pull request by WingsGo**
This CL includes:
1. add field check to avoid FE's invalid request cause BE coredump
2. use clang-format to format related code

### CODE REVIEW

**Comment by WingsGo** [comment]
For #3832

**Comment by WingsGo** [comment]
In order to make review easier, I revert some formatted code, after logic is right, I will add it later.

**Comment by kangkaisen** [comment]
@WingsGo Hi, it seems code format code still exist in this PR.

**Comment by WingsGo** [comment]
> @WingsGo Hi, it seems code format code still exist in this PR.

Yes, It's because the code file includes some core function,so I have to revert it one by one, but it's much more less than before~0v0

**Pull request closed without merging**
