### PR TITLE
[Enhancement](group commit) Use async group commit rpc call

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run p1

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by mymeiyi — APPROVED** [review]

**Pull request merged**
