### PR TITLE
[improvement](backend)Optimized error messages for insufficient replication

### LINKED ISSUE #17423: [Enhancement] Single BE / FE default table rep num
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

If I don't have a three cluster deployment, I don't see why I should be required to type **"replication_allocation" = "tag.location.default: 1"** each time I want to create a table. It's cumbersome and I have to code around it. 

I also benefitted from talking directly to a member of the Doris team who so kindly reached out to me on Slack, but a beginner may not be able to understand the message **"
ERROR 1105 (HY000): Unexpected exception: errCode = 2, detailMessage = Failed to execute CTAS Reason: errCode = 2, detailMessage = Failed to find 3 backends for policy: cluster|query|load|schedule|tags|medium: default_cluster|false|false|true|[{"location" : "default"}]|HDD"** or at least the solution should be indicated.

### Solution

Can we create a global to remove it? 

Another solution (buit which then imposes straint on the team to design) would be to make it equivalent to the number of BE, and other replication counts are mandatory.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zy-kkk**
# Proposed changes

Issue Number: close #17423

## Problem summary

In this PR, I optimized the error message for creating insufficient table replications
This is my test
I have 3 Be,, two of them are in the default resource group and one is in the test resource group
image

If I create a  4 replications table, I get the following error

```sql
mysql> CREATE TABLE IF NOT EXISTS `rep` (
    ->     `k`  int
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`k`)
    -> DISTRIBUTED BY HASH(`k`) BUCKETS 8
    -> PROPERTIES (
    ->     "replication_num" = "4"
    -> );
ERROR 1105 (HY000): errCode = 2, detailMessage = replication num should be less than the number of available backends. replication num is 4, available backend num is 3
```

Then I create a table with 3 replications, but I set all three copies of it to be in the default resource group

```sql
mysql> CREATE TABLE IF NOT EXISTS `rep` (
    ->     `k`  int
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`k`)
    -> DISTRIBUTED BY HASH(`k`) BUCKETS 8
    -> PROPERTIES (
    ->     "replication_num" = "3"
    -> );
ERROR 1105 (HY000): errCode = 2, detailMessage = Failed to find enough backend, please check the replication num,replication tag and storage medium.
Create failed replications:
replication tag: {"location" : "default"}, replication num: 3, storage medium: HDD
```

Then I  create a 3 replications table with one replication in the default resource group and two replications in the test resource group

```sql
mysql> CREATE TABLE IF NOT EXISTS `rep` (
    ->     `k`  int
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`k`)
    -> DISTRIBUTED BY HASH(`k`) BUCKETS 8
    -> PROPERTIES (
    ->     "replication_allocation" = "tag.location.test: 2,tag.location.default: 1"
    -> );
ERROR 1105 (HY000): errCode = 2, detailMessage = Failed to find enough backend, please check the replication num,replication tag and storage medium.
Create failed replications:
replication tag: {"location" : "test"}, replication num: 2, storage medium: HDD
```

Then I  create a 3 replications table with one replication in the test resource group and two replications in the default resource group

```sql
mysql> CREATE TABLE IF NOT EXISTS `rep` (
    ->     `k`  int
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(`k`)
    -> DISTRIBUTED BY HASH(`k`) BUCKETS 8
    -> PROPERTIES (
    ->     "replication_allocation" = "tag.location.test: 1,tag.location.default: 2"
    -> );
Query OK, 0 rows affected (0.28 sec)
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.38 seconds
 stream load tsv:          423 seconds loaded 74807831229 Bytes, about 168 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230428113714_clickbench_pr_137124.html

**Comment by morningman** [comment]
Some issues:
1. Better wait #19167 to be merged, or there will be conflict.
2. FE ut failed.
3. How about letting `BeSelectionPolicy` to return error msg, so that where ever we use  `BeSelectionPolicy`, we can get same error msg.

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
