### PR TITLE
[fix](web): field in Controller is singleton, which would introduce thread safe problem, so remove it

### PR DESCRIPTION
**Pull request by xutaoustc**
[fix](web): field in Controller is singleton, which would introduce thread safe problem, so remove it

### CODE REVIEW

**Review by bigben0204 — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run feut

**Comment by yiguolei** [comment]
run buildall

**Review by mrhhsg — APPROVED** [review]
LGTM

**Pull request merged**
