### PR TITLE
[fix](docs) Fix Data type: string length and parameter description

### PR DESCRIPTION
**Pull request by catpineapple**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caiconghui — COMMENTED** [review]
a soft limit of string type length, the hard limit is 2GB - 4, but if too long will cause very low performance, so we set a soft limit, default is 1MB, so the origin content is right?

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
> a soft limit of string type length, the hard limit is 2GB - 4, but if too long will cause very low performance, so we set a soft limit, default is 1MB, so the origin content is right?

Actually, we do not want user to save large string in string column. and it may change to a hard limit in future.
So I think we should not say we support 2GB in document.

**Comment by ChPi** [comment]
@morningman  用户使用Doris作为唯一数仓，会存储比较大的数据，且从0.15版本开始使用。未来不要直接限死，还是大小可配置，文档可以指出数据太大导致的问题，让用户自己根据自己的集群业务情况限制大小

**Comment by morningman** [comment]
> 

实际上目前的string不适合存储大字符串，所以这个可以理解为是当前Doris的功能限制，而不是一个可供用户选择的方案

**Comment by hf200012** [comment]
@catpineapple  
please rebase

**Review by jackwener — APPROVED** [review]
LGTM

**Pull request merged**
