### PR TITLE
[fix](Export) Set the default value of the `data_consistence` property of export to `partition`

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

doc pr: https://github.com/apache/doris-website/pull/482

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run external

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
Please add case for partition consistency

**Review by wuwenchi — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
