### PR TITLE
[fix](meta) Disable infer expr column name when query on old optimizer

### PR DESCRIPTION
**Pull request by JingDas**
## Proposed changes

Disable infer expr column name when query on old optimizer.
This bug is be brought in #24990 

## Further comments
if your query SQL is 
`select id, name, sum(target) FROM db_test.table_test2 group by id, name;`
the result column name when query is as following:
`id|name |sum(cast(target as DOUBLE))|`

when you create view as following:
`CREATE VIEW v1 as select id, name, sum(target) FROM db_test.table_test2 group by id, name;`
then query the view v1, the result is as following:
`id|name |__sum_2|`

### CODE REVIEW

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Comment by JingDas** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
