### PR TITLE
[FIX](serde) fix map/array deserialize string with quote pair

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
fix map/array deserialize string with quote pair
Now we deserialize string item with quote can be  ```"``` and ```'``` which non-pair also can be deserialize success, but it should be pair appear in single string  

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
