### PR TITLE
[vectorized](bug) fix array constructor function change origin column from block

### PR DESCRIPTION
**Pull request by zhangstar333**
**when get a column from block, and calculate result column
don't need to change the origin column, maybe it's still need used.** 

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by HappenLee** [comment]
ADD test for the case

**Comment by morningman** [comment]
please add test case

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
