### PR TITLE
[fix](insert) fix group commit regression test

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
1. For now stream load may be not load with group commit when data is too large, so these cases need to consider these scenario.
2. CHANGE_ORDER is a weight schema change, it will throw an exception to client when schema change is going to be finished, so test case need to consider this scenario too, for now i just skip testing CHANGE_ORDER and i will fix it on next pr.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildal

**Comment by hust-hhb** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
