### PR TITLE
[fix](compress) snappy does not work right

### PR DESCRIPTION
**Pull request by dataroaring**
Snapy does not work right and be crashes, the patch fixes it.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
