### PR TITLE
[fix](function) fix str_to_date with specific format

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

before 
```
mysql>SELECT STR_TO_DATE('2019-12-01', 'yyyy-MM-dd');  
+-----------------------------------------+
| STR_TO_DATE('2019-12-01', 'yyyy-MM-dd') |
+-----------------------------------------+
| NULL                                    |
+-----------------------------------------+       

```
after

```
mysql>SELECT STR_TO_DATE('2019-12-01', 'yyyy-MM-dd');  
+-----------------------------------------+
| STR_TO_DATE('2019-12-01', 'yyyy-MM-dd') |
+-----------------------------------------+
| 2019-12-01                              |
+-----------------------------------------+
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.49 seconds
 stream load tsv:          509 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162282337 Bytes

**Comment by Mryange** [comment]
run arm

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
