### PR TITLE
[refine](pipeline) refine some VDataStreamRecvr code 

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
The memory statistics in VDataStreamRecvr are disorganized.
We will use _mem_tracker to record peak memory usage and manage the logic.
Rename some counter.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
