### PR TITLE
[chore](script) avoid failed while buiding on non-git repository

### PR DESCRIPTION
**Pull request by mrhhsg**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
