### PR TITLE
[refactor](nereids) make forbid_unknown_col_stats check more accurate

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
ignore unknown col stats check if:
 colunm not used in query
 column is Array/Json/Map/Struct type

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by Kikyou1997 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Comment by englefly** [comment]
run buildall

**Pull request merged**
