### PR TITLE
[fix](planner) fix no data issue when use datetimev1/datatimev2 & datev2 as function coalesce's parameter in legacy planner

### PR DESCRIPTION
**Pull request by Yulei-Yang**
How to Reproduce:
**Issue1: use datetimev1 and datev2 as parameters in function coalesce**
```sql
admin set frontend config ("enable_date_conversion"="false");
admin set frontend config ("disable_datev1"="false");
drop table test_cls;
CREATE TABLE `test_cls` (
    `id` int(11) NOT NULL COMMENT '',
    `name` varchar(32) NOT NULL COMMENT '',
    `dt` datetime NOT NULL
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 2
PROPERTIES(
    "replication_allocation" = "tag.location.default: 1"
);
```

sql `SET enable_nereids_planner=false; select dt from test_cls where coalesce (dt, str_to_date(concat('202306', '01'), '%Y%m%d')) >= '2023-06-01';` return no data, which is wrong

when see the excution plan
`SET enable_nereids_planner=false; explain select dt from test_cls where coalesce (dt, str_to_date(concat('202306', '01'), '%Y%m%d')) >= '2023-06-01';`

you can see error predicate:
CAST(coalesce(CAST(`dt` AS BIGINT), 20230601) AS DOUBLE) >= NULL

after fix:
CAST(coalesce(`dt`, '2023-06-01') AS DATETIMEV2(0)) >= '2023-06-01 00:00:00'

**Issue2: use datetimev2 and datev2 as parameters in function coalesce**

```sql
admin set frontend config ("enable_date_conversion"="true");
admin set frontend config ("disable_datev1"="true");
drop table test_cls;
CREATE TABLE `test_cls` (
    `id` int(11) NOT NULL COMMENT '',
    `name` varchar(32) NOT NULL COMMENT '',
    `dt` datetime NOT NULL
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 2
PROPERTIES(
    "replication_allocation" = "tag.location.default: 1"
);
```

sql `SET enable_nereids_planner=false; select dt from test_cls where coalesce (dt, str_to_date(concat('202306', '01'), '%Y%m%d')) >= '2023-06-01';` return no data, which is wrong

when see the excution plan
`SET enable_nereids_planner=false; explain select dt from test_cls where coalesce (dt, str_to_date(concat('202306', '01'), '%Y%m%d')) >= '2023-06-01';`

you can see error predicate:
CAST(coalesce(CAST(`dt` AS BIGINT), 20230601) AS DOUBLE) >= NULL

after fix:
coalesce(`dt`, '2023-06-01') >= '2023-06-01 00:00:00'

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
