### PR TITLE
[fix](arrow-flight)Fix the prompt that be arrow_flight_sql_port is not set

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DongLiang-0** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by yagagagaga — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run beut

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
