### PR TITLE
[coverage](fe)add jacoco coverage option on start_fe.sh

### PR DESCRIPTION
**Pull request by pingchunzhang**
## Proposed changes

Issue Number: close #xxx

add JACOCO_COVERAGE_OPT in start_fe.sh for collect system test coverage
JACOCO_COVERAGE_OPT format can be like 
`-javaagent:/var/local/jacoco/lib/jacocoagent.jar=includes=*,output=file,append=true,destfile=fe_cov.exec`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pingchunzhang** [comment]
run buildall

**Comment by pingchunzhang** [comment]
run buildall

**Comment by pingchunzhang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Pull request merged**
