### PR TITLE
[chore](test) Add info about buildKit required with docker-compose

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
got error when trying to create docker cluster using private image. 
adding more info so that can help others.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed. // no code change. just doc update
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by Vallishp** [comment]
run cloud_p0

**Comment by Vallishp** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
