### PR TITLE
[fix](serde)fix the bug in DataTypeNullableSerDe.deserialize_column_from_fixed_json

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by suxiaogang223 — APPROVED** [review]

**Comment by suxiaogang223** [comment]
+1

**Review by morningman — APPROVED** [review]

**Pull request merged**
