### PR TITLE
[regression-test](fix) Fix the incorrect invocation of Awaitility.await.untilAsserted 

### PR DESCRIPTION
**Pull request by shuke987**
### What problem does this PR solve?

Issue Number: close #xxx
#45591 

Related PR: #xxx
#38836 

Problem Summary:
Awaitility.await.untilAsserted  is used like
```
def booleanClosure = { ->
   ...
   return true or false
}

await().atMost(ofSeconds(5)).untilAsserted(() -> {
    assert booleanClosure()
});
```
"untilAsserted" has a feature that it stops executing the subsequent statements upon encountering the first false assertion. If no assertion is encountered, or all assertions are true, "await" exits. There is an issue with our usage in our test cases.
This pr fix this.

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by shuke987** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by shuke987** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
https://github.com/apache/doris/pull/45761 refactor in this pr

**Pull request closed without merging**
