### PR TITLE
[chore](dependencies)upgrade fe dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
upgrade commons-configuration2 to 2.11.0
upgrade logging-interceptor to 4.12.0
upgrade commons-compress to 1.27.1
upgrade jetty-bom to 9.4.56.v20240826
upgrade azure-sdk to 1.2.27

Iceberg depends on configuration2, and configuration2 relies on a newer version of commons-lang3. However, there were significant breaking changes in commons-lang3, which made it incompatible.https://issues.apache.org/jira/browse/LANG-1705  As a result, I rewrote the clone method.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run  buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
