### PR TITLE
[feature-wip](multi-catalog) refactor catalog interface

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

This CL is a big refactor of catalog and datasource, as follows:
1. Most of the places where `Catalog.getDbXXX` is called are changed to `Catalog.getCurrentInternalCatalog().getDbXXX`.
2. So called `getCurrentInternalCatalog` because we will change DataSource to Catalog after, and change current Catalog class to another name.

The method of getting db will be unified into InternalDataSource.

## Checklist(Required)

1. Does it affect the original behavior: (No)
4. Has unit tests been added: (No Need)
5. Has document been added or modified: (No Need)
6. Does it need to update dependencies: (No)
7. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SaintBacchus** [comment]
LGTM

**Comment by dujl** [comment]
Database db = Catalog.getCurrentCatalog().getDbOrAnalysisException(label.getDbName());
            Database db =
                    Catalog.getCurrentInternalCatalog().getDbOrAnalysisException(label.getDbName());

**Comment by morningman** [comment]
> Why invoke getCurrentInternalCatalog outside the catalog such as in InsertStmt? getCurrentInternalCatalog should be an internal function in catalo. In insertStmt we should get a DatabaseIf or TableIf from catalog and add a datasource checker for check whether is it a supported datasource table.
> 
> disadvantage:
> 
> 1. Catalog.getCurrentInternalCatalog(). getDbOrDdlException will throw an exception even though the db is exist in some external datasource. This will confuses users. Such as in CreateRoutineLoadStmt.java,  When create routineLoad job for an external datasource table, It should throw do not support external datasource table  instead of table not exist.
> 2. catalog api caller such analyzer just want to resolve the db or table identifier instead of perceive the catalog internal interface such getCurrentInternalCatalog.
> 
> Suggestion:
> 
> 1. catalog api caller such analyzer use Catalog. getDbOrDdlException apis to get a DatabaseIf or TableIf object.
> 2. In catalog internal, it can use current datasource or catalog indicator from api parameter to get a Database or table object.
> 3. if we support insert external datasource table in the future,  just remove the datasource checker in InsertStmt.

1. First, I deleted the `getDbXXX` methods from `Catalog.java`, because in essence these `getDb` methods should be the methods of DataSourceMgr. The `Catalog` class will be renamed later, such as `Env` or `DorisRuntime`. It is only responsible for managing all Mgrs, and each Mgr is responsible for its own affairs, such as `DataSourceMgr` is responsible for managing `DataSource` (subsequently renamed `Catalog`) and `getDb`.

2. All are currently modified to `getCurrentInternalCatalog`. Mainly because the function of multi catalog is still under development, and there is currently no context of external catalog, so I first use `InternalCatalog` to ensure that the existing functions are completely unaffected.
All subsequent `Catalog.getCurrentInternalCatalog().getDbxxx` will be uniformly changed to, for example, `Env.getCatalog().getDbxxx()`.
Currently this is only an intermediate state, the purpose is to remove some methods in the Catalog.

3. Whether a function supports the external catalog will be determined later in the analyze phase of Stmt. Then, when the switch catalog is developed, you can obtain the context of the catalog through the context for unified judgment.

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
