### PR TITLE
[Refactor](Nereids) refactor fold constant framework on fe

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
change matching of function by notation to matching by inputs datatype

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run feut

**Comment by LiBinfeng-01** [comment]
run performance

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
