### PR TITLE
[Bug](view) fix AES_ENCRYPT have wrong result on view

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes
```sql
mysql [test_query_qa]>create view test_view as select 1,to_base64(AES_ENCRYPT('doris','doris'));
select * from test_view;
Query OK, 0 rows affected (0.01 sec)

+------+----------------------------------------+
| 1    | to_base64(aes_encrypt('doris', '***')) |
+------+----------------------------------------+
|    1 | wiSYsQpmWIYgTOTZpnT5fg==               |
+------+----------------------------------------+
mysql [test]>select 1,to_base64(AES_ENCRYPT('doris','doris'));
+------+----------------------------------------+
| 1    | to_base64(aes_encrypt('doris', '***')) |
+------+----------------------------------------+
|    1 | 4x0fdjDNBZAJxCD7qm/EHg==               |
+------+----------------------------------------+
1 row in set (0.03 sec)
```
## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.45 seconds
 stream load tsv:          450 seconds loaded 74807831229 Bytes, about 158 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230323012047_clickbench_pr_119048.html

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run feut

**Comment by BiteTheDDDDt** [comment]
run feut

**Comment by BiteTheDDDDt** [comment]
run feut

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by 0xqq** [comment]
doris1.2.4 still wrong

**Pull request merged**
