### PR TITLE
[Fix](Job)Job Task does not display error message

### PR DESCRIPTION
**Pull request by CalvinKirs**
Job log should record exception stack and jobid

### test result
image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run P1

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
