### PR TITLE
[Chore](check) ignore license check on .github

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
ignore license check on .github

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by Thearas — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
