### PR TITLE
[opt](merge-on-write) Reduce the version not continuous logs for merge-on-write table

### PR DESCRIPTION
**Pull request by bobhan1**
branch-2.1-pick: https://github.com/apache/doris/pull/40996
branch-2.0-pick: https://github.com/apache/doris/pull/40997

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
