### PR TITLE
[fix](load) acquire latest token instead of oldest token in TokenManager

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Previously, `TokenManager` always returns the oldest token, which may expire soon.
This PR changes it to return the latest token instead.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by SaintBacchus — APPROVED** [review]
LGTM

**Pull request merged**
