### PR TITLE
[bugfix](k8s)roll back jackson version

### PR DESCRIPTION
**Pull request by zddr**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

when Upgrade the version of jackson,k8s client will failed

java.lang.NoClassDefFoundError: org/yaml/snakeyaml/LoaderOptions
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:191) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:509) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:413) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:386) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.2.jar:2.14.2]
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:47) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:589) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:555) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:277) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:243) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:237) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:11) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:8) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:40) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:151) ~[kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:34) ~[kubernetes-client-5.12.2.jar:?]
	at org.apache.doris.deploy.impl.K8sDeployManager.client(K8sDeployManager.java:381) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.deploy.impl.K8sDeployManager.statefulSet(K8sDeployManager.java:265) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.deploy.impl.K8sDeployManager.getGroupHostInfosByStatefulSet(K8sDeployManager.java:177) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.deploy.impl.K8sDeployManager.getGroupHostInfos(K8sDeployManager.java:167) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.deploy.DeployManager.getHelperNodes(DeployManager.java:294) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.getHelperNodeFromDeployManager(Env.java:1242) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.getHelperNodes(Env.java:1188) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.initialize(Env.java:820) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.PaloFe.start(PaloFe.java:146) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.PaloFe.main(PaloFe.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.LoaderOptions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_342]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_342]
	... 28 more

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by CalvinKirs** [comment]
Thank you.
The reason for this problem is that the version of snake-yaml used by k8s-client is not compatible with our fixed version of snake-yaml.

Thanks for the test code, I'll revisit the changes here later.
For now, repinning the version is the fastest way.

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
