### PR TITLE
[Bug](insert )fix insert wrong data on mv when stmt have multiple values

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
https://github.com/apache/doris/issues/27277
fix insert wrong data on mv when stmt have multiple values

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
