### PR TITLE
[refactor](fe): Remove resource group which is useless

### PR DESCRIPTION
**Pull request by levy5307**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Comment by luozenglin** [comment]
PTAL @morningman

**Review by yiguolei — APPROVED** [review]
lgtm

**Comment by levy5307** [comment]
run buildall

**Comment by levy5307** [comment]
run buildall

**Pull request merged**
