### PR TITLE
[feature](AuditLog) add scanRows scanBytes in auditlog

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

info from profile

sql

```
select count(*) from web_sales;
+----------+
| count(*) |
+----------+
|   719384 |
+----------+
```

profile
```
-  ScanByteRead:  6.56  MB
-  ScanRowsRead:  719.384K  (719384)
```

auditlog
```
State=EOF|ErrorCode=0|ErrorMessage=|Time(ms)=49|ScanBytes=6881280|ScanRows=719384|ReturnRows=1|StmtId=16|QueryId=d93ad95d62484a3f-a81acb47b7835a9c|IsQuery=true|isNereids=true|feIp=127.0.0.1|Stmt=select count(*) from web_sales|CpuTimeMS=49
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Comment by xiaokang** [comment]
#25435

**Pull request closed without merging**
