### PR TITLE
[improve](cloud) support arm compilation in cloud mode

### PR DESCRIPTION
**Pull request by luwei16**
Azure is not supported yet. You need to export DISABLE_BUILD_AZURE=ON && sh build.sh --cloud when compiling.

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
