### PR TITLE
[improvement](nererids) Don't break stats cache load loop when meeting unknown stats 

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

 Analyze may got executed on master, and query may got submitted to follower, throw exception directly would break the loading for other columns.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by englefly** [comment]
why we cannot break the loading if some columns are unknown?

**Review by englefly — DISMISSED** [review]

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Pull request closed without merging**
