### PR TITLE
[tools](ssb and tpch)optimize tools

### PR DESCRIPTION
**Pull request by hello-stephen**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. optimize the scripts in order to make them easier to use.
2. use ShellCheck to format the code.
3. use MYSQL_PWD instead of --password=xxx to suppress warning.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Nice job!

However, I think you should also modify `.github/workflows/shellcheck.yml`. The `ShellCheck` action ignores the files under `tools/ssb-tools` and `tools/tpch-tools` currently.

**Comment by adonis0147** [comment]
Nice job!

However, I think you should also modify `.github/workflows/shellcheck.yml`. The `ShellCheck` action ignores the files under `tools/ssb-tools` and `tools/tpch-tools` currently.

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
@yiguolei there are some unresolved comments. Why did you merge it?

CC @morningman

**Comment by hello-stephen** [comment]
> Nice job!
> 
> However, I think you should also modify `.github/workflows/shellcheck.yml`. The `ShellCheck` action ignores the files under `tools/ssb-tools` and `tools/tpch-tools` currently.

sorry for replying late, I made a new request for compensation.

**Pull request merged**
