### PR TITLE
[feature](binlog) Allow BarrierLog to wrap another binlog

### PR DESCRIPTION
**Pull request by w41ter**
to make it work in the old Doris version without breaking compatibility

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
