### PR TITLE
[improvement](insert) refactor group commit stream load

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Refactor group commit stream load to remove some code.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p1

**Comment by mymeiyi** [comment]
run p1

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p1

**Comment by mymeiyi** [comment]
run p1

**Comment by mymeiyi** [comment]
run p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hust-hhb — APPROVED** [review]
LGTM

**Pull request merged**
