### PR TITLE
[Fix](nereids) fix partition_prune or expression evaluate wrongly

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
introduced by #38025
Or expression evaluate wrongly in #38025. For example, partition column is a, b, predicate is  a=a or b>1 , partition  column range is  min<a<5,  b is infinite. The evaluate result of or expression should be b is infinite(because when a is not null, a=a is true, there is no restrict for b, e.g. a=1, b=0 satisfy a=a or b>1).  #38025 pr has wrongly evaluate result b >1

### CODE REVIEW

**Review by 924060929 — DISMISSED** [review]

**Comment by dataroaring** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run cloud_p0

**Review by starocean999 — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run cloud_p1

**Review by starocean999 — APPROVED** [review]

**Review by xzj7019 — APPROVED** [review]

**Pull request merged**
