### PR TITLE
[fix](compaction) fix the issue of writing segment with 0 rows during compaction

### PR DESCRIPTION
**Pull request by luwei16**
https://github.com/apache/doris/pull/37960 introduced this issue

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
