### PR TITLE
[fix](planner) fix result wrong caused by mixed use multiple columns …

### PR DESCRIPTION
**Pull request by Yulei-Yang**
…with type of datetime/datetimev2/date/datev2 of function coalesce & ifnull

cherry-pick: #36688, #36640, #36583

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run performance

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
