### PR TITLE
[fix](nereids) set proper sort info to scan node to enable TopN-opt

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
