### PR TITLE
[Feature](sink) support parallel result sink

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
support parallel result sink

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
