### PR TITLE
[fix](topn-filter) throw out of bound exception  when union has no child

### PR DESCRIPTION
**Pull request by morrySnow**
introduced by #35405

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run feut

**Pull request merged**
