### PR TITLE
[Fix](information_schema) Schema table varchar len error

### LINKED ISSUE #21156: [Bug] When obtaining table information in information_schema, the length of the varchar field is -1
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0

### What's Wrong?

When obtaining table information in information_schema, the length of the varchar field is -1,
However, according to the description of the data type chapter in the official website, the length of varchar is 1-65533

### What You Expected?

expects correct datatype length

### How to Reproduce?

1. create DataSource connection 
2. exec `show full columns from `information_schema`.`tables``
3. view
image
image

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by stalary**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/21156

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by stalary** [comment]
run p0

**Comment by stalary** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
Please add a regression test case

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
@stalary please rebase master and push again

**Review by morningman — APPROVED** [review]
LGTm

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
