### PR TITLE
[regression](fix) fix  concurrency case bug

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
http://43.132.222.7:8111/buildConfiguration/Doris_External_Regression/541813?buildTab=log&linesState=3553&logView=flowAware&focusLine=16429

need fix

**Review by morningman — APPROVED** [review]
LGTM

**Pull request closed without merging**
