### PR TITLE
[regression](s3load) Add regression testing and modify description text for s3load

### PR DESCRIPTION
**Pull request by Zhiyu-h**
## Proposed changes

Add regression testing and modify description text for s3load

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
related case seems failed

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by zzzzzzzs — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zzzzzzzs** [comment]
LGTM

**Pull request merged**
