### PR TITLE
[regression](kerberos)fix regression pipeline env when write hosts 

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

fix pipeline kerberos access exception:  'No route'

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external p0

**Comment by wsjz** [comment]
run external p0

**Comment by wsjz** [comment]
run external p0

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Pull request merged**
