### PR TITLE
[fix](case) Update analyze_stats.groovy

### PR DESCRIPTION
**Pull request by hello-stephen**
I meet this error: http://43.132.222.7:8111/buildConfiguration/Doris_DorisRegression_P0Regression/239889?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildTestsSection=true

After investigation, It is found that the DB name conflicts when the case is executed concurrently.

So, change the conflicted DB name to a unique one.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
