### PR TITLE
[fix](compatibility) type toSql should return lowercase string

### PR DESCRIPTION
**Pull request by morrySnow**
revert #25951

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run external

**Review by starocean999 — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
