### PR TITLE
[FIX](collectiontype)fix collection type with char which without length

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
fix create complex type like array/map/struct with char which without length

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
Check the testcase for char/varchar w/o length. If there are some missing case, add testcase for it.

**Review by morrySnow — DISMISSED** [review]

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run compile

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p1

**Comment by amorynan** [comment]
run clickbench

**Comment by amorynan** [comment]
run external

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
