### PR TITLE
[fix](build) Missing header files

### PR DESCRIPTION
**Pull request by yongjinhou**
# Proposed changes

Issue Number: close #xxx

## Problem summary

BE lacks header files, causing the compilation to fail.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run buildall

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Comment by yongjinhou** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
