### PR TITLE
[opt](profile) parallel serialize fragment and add detail schedule profile

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Add detail schedule profile

	```
	-  Schedule  Time:  652ms
       -  Fragment  Assign  Time:  57ms
       -  Fragment  Serialize  Time:  70ms
       -  Fragment  RPC  Phase1  Time:  522ms
       -  Fragment  RPC  Phase2  Time:  3ms
       -  Fragment  Compressed  Size:  6.82  MB
       -  Fragment  RPC  Count:  2
   -  Wait  and  Fetch  Result  Time:  N/A
       -  Fetch  Result  Time:  0ms
       -  Write  Result  Time:  0ms
   ```
   
   - Fragment Serialize Time: Time to serialized the fragment thrift
   - Fragment RPC Phase1 Time: Time to send first fragment RPC
   - Fragment RPC Phase1 Time: Time to send second fragment RPC
   - Fragment Compressed Size: Total serialized size for fragment in bytes
   - Fragment RPC Count: Number of RPC

2. Separate the serialization of RPC send step

	In previous, Doris will serialize and send fragment to each BE
	one by one. If fragment is large, it is costy.
	In this PR, I separate these 2 steps by first serializing the
	fragment in parallel, and than send it one by one.
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
