### PR TITLE
[fix](trino-connector) Refactor some code of trino-connector jni reader

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Previously, TrinoConnectorJniScanner converted Trino types to Hive types, and then to Doris types.
In fact, the Hive type can be directly obtained from `columns_types`.
In this way, the step of converting Trino types to Hive types can be deleted.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by hubgeter — APPROVED** [review]
LGTM

**Pull request merged**
