### PR TITLE
[test](tvf) append tvf read hive_text file  regression case.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by hubgeter** [comment]
run buildall

**Review by AshinGau — APPROVED** [review]

**Comment by AshinGau** [comment]
LGTM

**Pull request merged**
