### PR TITLE
[Fix](Variant) create table should not automatically add variant to keys

### PR DESCRIPTION
**Pull request by eldenmoon**
Truncate when meet Variant type

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by xiaokang — COMMENTED** [review]
pls add testcase

**Comment by eldenmoon** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by amorynan — APPROVED** [review]
LGTM

**Pull request merged**
