### PR TITLE
[improvement][manager] Modify the agent startup service and build cluster logic

### PR DESCRIPTION
**Pull request by JNSimba**
# Proposed changes

1. The agent judges that the fe/be/broker has been successfully started, The logic is modified to judge whether the process still exists after 10 seconds of starting.
2. The submitted state is uniformly changed to running at the front end
3. change [build cluster] the logic unified as add fe, add be, add broker

## Problem Summary:

Describe the overview of changes.

## Checklist(Requried)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
PR header should be corrected: [doc](https://doris.apache.org/master/zh-CN/community/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83)

**Comment by JNSimba** [comment]
> PR header should be corrected: [doc](https://doris.apache.org/master/zh-CN/community/commit-format-specification.html#commit-%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83)

thanks，already modified

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by weajun** [comment]
LGTM, I have tested pass in my test environment

**Pull request merged**
