### PR TITLE
[chore](nereids) Added compatibility with mysql alias conflict (#38104)

### PR DESCRIPTION
**Pull request by Toms1999**
cherry pick from #38104

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run P0 Regression

**Comment by Toms1999** [comment]
run buildall

**Comment by Toms1999** [comment]
run buildall

**Pull request merged**
