### PR TITLE
[opt](docker)optimize ES docker compose

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

1. add volume for es logs
2. optimize health check, waiting for es status to be green
3. fix es6 valume path error
4. optimize disk watermark to avoid es disk watermark error
5. fix es6 create index error
6. add custom elasticsearch.yml for es6
7. add log4j2.properties for es6, es7, es8

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
