### PR TITLE
[feature](nereids)print nereids node id in explain

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
this pr helps to link node in nereids plan (explain physical plan) and original plan (explain)
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
runb buildall

**Comment by englefly** [comment]
run pipelinex_p0

**Comment by englefly** [comment]
run pipelinex_p0

**Comment by englefly** [comment]
run pipelinex_p0

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run feut

**Comment by englefly** [comment]
run pipelinex_p0

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
