### PR TITLE
[feature](index) Replace BITMAP INDEX with INVERTED INDEX #30950

### PR DESCRIPTION
**Pull request by xiaokang**
cherry pick from #30950

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]

**Comment by xiaokang** [comment]
run p0

**Comment by xiaokang** [comment]
run p0

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
