### PR TITLE
[fix](restore) work around, ingest binlog after backup/restore which local_tablet.partition_id is not correct, use req.partition_id

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

work around, ingest binlog after backup/restore which local_tablet.partition_id is not correct, use req.partition_id

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by deadlinefen — APPROVED** [review]
LGTM

**Comment by JackDrogon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
