### PR TITLE
[enhancement](memory) Record value of MemTracker reserve memory

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Tracking each MemTracker reserve memory, used to analyze reserve memory usage.
img_v3_02bv_f584fc33-e845-41e0-852b-fb23ec8d9e7g

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
