### PR TITLE
[enhancement] Use '#pragma once' to replace '#ifndef'

### PR DESCRIPTION
**Pull request by xlwh**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: Yes

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zbtzbtzbt** [comment]
thanks your pr!
you only change head files in`be/src/olap`, can you modify in all head files?

**Comment by zbtzbtzbt** [comment]
By using keyword replacement, it's convenient

**Review by yiguolei — APPROVED** [review]
LGTM
This PR only changed #pragma once, I will do fast merge.

**Comment by xlwh** [comment]
> 
Ok,  I will follow up with the next PR, thanks!

**Pull request merged**
