### PR TITLE
[typo](doc)Update run-docker-cluster.md----The hyphen writing is not standardized

### PR DESCRIPTION
**Pull request by TomPkuer**
The hyphen writing is not standardized

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HYBG-1126** [comment]
真细心，牛！

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
There are some conflicts and you should resloved it and rebase the code.

**Comment by TomPkuer** [comment]
> run buildall
what is wrong with this pr？

**Pull request closed without merging**
