### PR TITLE
[fix](memory) Fix thread_context check failed: thread_mem_tracker()->label() == "Orphan"

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

```
F1123 08:04:37.272737 754056 thread_context.h:169] Check failed: thread_mem_tracker()->label() == "Orphan" , attach mem tracker label: Query#Id=2d6d0263f4c84f95-a4c2c96307e78498
*** Check failure stack trace: ***
    @     0x55a03307b4ed  google::LogMessage::Fail()
    @     0x55a03307da29  google::LogMessage::SendToLog()
    @     0x55a03307b056  google::LogMessage::Flush()
    @     0x55a03307e099  google::LogMessageFatal::~LogMessageFatal()
    @     0x55a01013a057  doris::ThreadContext::attach_task()
    @     0x55a0101354d8  doris::AttachTask::AttachTask()
    @     0x55a00fdb9981  doris::PlanFragmentExecutor::~PlanFragmentExecutor()
    @     0x55a00fba309d  doris::FragmentExecState::~FragmentExecState()
    @     0x55a00fba3192  std::_Sp_counted_ptr<>::_M_dispose()
    @     0x55a00ce78412  std::_Sp_counted_base<>::_M_release()
    @     0x55a00ce7814a  std::__shared_count<>::~__shared_count()
    @     0x55a00fbd493b  std::__shared_ptr<>::~__shared_ptr()
    @     0x55a00fb726b5  std::shared_ptr<>::~shared_ptr()
    @     0x55a00fb4ca9b  doris::FragmentMgr::cancel()
    @     0x55a00fdb4e44  doris::ThreadMemTrackerMgr::cancel_fragment()
    @     0x55a01f1ac4d7  Allocator<>::sys_memory_check()
    @     0x55a01f1afaf3  Allocator<>::memory_check()
    @     0x55a01f1b07b1  Allocator<>::alloc_impl()
    @     0x55a01f1b0537  Allocator<>::alloc()
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
