### PR TITLE
[feature](cpu cores)get the cores when running within a cgroup.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

same in https://github.com/duckdb/duckdb/issues/6519

```
#  cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
800000
# cat /sys/fs/cgroup/cpu/cpu.cfs_period_us
100000

pipeline executors_size set |size=8


```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
