### PR TITLE
[fix](compaction) fix duplicate key in agg/mor table caused by ordered data compaction

### PR DESCRIPTION
**Pull request by luwei16**

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by luwei16** [comment]
run buildall

**Comment by zhannngchen** [comment]
we'd better add a case?

**Review by gavinchou — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Comment by luwei16** [comment]
run external

**Comment by luwei16** [comment]
run p0

**Pull request merged**
