### PR TITLE
[enhancement](profile) add read columns to scanner profile

### PR DESCRIPTION
**Pull request by Cai-Yao**
# Proposed changes

Issue Number: close #xxx

## Problem summary

add ReadColumns in profile

eg:
```
mysql> select city, sum(cost) as total_cost from example_tbl group by city;
```
```
VScanner:
-  ReadColumns:  [city,  cost]
-  PerScannerRunningTime:  [92.198us,  ]
-  PerScannerRowsRead:  [6,  ]
-  BlockConvertTime:  0ns
-  BlockFetchTime:  86.382us
-  ReaderInitTime:  0ns
-  RowsDelFiltered:  0
```
## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 37.95 seconds
 load time: 519 seconds
 storage size: 17122121002 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230113113904_clickbench_pr_79709.html

**Review by zbtzbtzbt — COMMENTED** [review]
Extra commas  **( , )** can be deleted together in this pr
such as:
92.198us,
6,  
```
VScanner:
-  ReadColumns:  [city,  cost]
-  PerScannerRunningTime:  [92.198us,  ]
-  PerScannerRowsRead:  [6,  ]
-  BlockConvertTime:  0ns
-  BlockFetchTime:  86.382us
-  ReaderInitTime:  0ns
-  RowsDelFiltered:  0
```

**Comment by Cai-Yao** [comment]
> Extra commas **( , )** can be deleted together in this pr such as: 92.198us, 6,
> 
> ```
> VScanner:
> -  ReadColumns:  [city,  cost]
> -  PerScannerRunningTime:  [92.198us,  ]
> -  PerScannerRowsRead:  [6,  ]
> -  BlockConvertTime:  0ns
> -  BlockFetchTime:  86.382us
> -  ReaderInitTime:  0ns
> -  RowsDelFiltered:  0
> ```

done

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
