### PR TITLE
[typo](doc)add user-defined variables docs

### PR DESCRIPTION
**Pull request by ixzc**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ixzc** [comment]
run buildall

**Review by DongLiang-0 — APPROVED** [review]

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by JNSimba — DISMISSED** [review]
LGTM

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]

**Review by caoliang-web — APPROVED** [review]

**Comment by JNSimba** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
