### PR TITLE
[fix](regression) change reference of s3 in p1 via getS3url

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by cambyzju** [comment]
maybe use `getS3Url()` is better?

you could find many other cases use getS3Url:
`find regression-test/ -name "*.groovy"|xargs grep -i getS3Url`

**Comment by zclllyybb** [comment]
> maybe use `getS3Url()` is better?
> 
> you could find many other cases use getS3Url: `find regression-test/ -name "*.groovy"|xargs grep -i getS3Url`

u r right. fixed. thx

**Comment by zclllyybb** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
