### PR TITLE
[Fix](autoinc) try fix concurrent load problem with auto inc column

### PR DESCRIPTION
**Pull request by bobhan1**
1. increase the value of `AutoIncrementGenerator.BATCH_ID_INTERVAL` to reduce the number of writes to BDBJE. (the default value of `config::auto_inc_prefetch_size_ratio` is 10 and the default value of `AutoIncIDBuffer::_batch_size` is 4064, so mostly the request length is 40960)
2. only allow master fe to offer `getAutoIncrementRange` service
3. write editlog before update `batchEndId` in memory in `getAutoIncrementRange `
4. refactor `AutoIncIDBuffer`

branch-2.1 pick: https://github.com/apache/doris/pull/37027

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zhannngchen — CHANGES_REQUESTED** [review]
pls add description for your patch

**Comment by dataroaring** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run build all

**Comment by bobhan1** [comment]
run build all

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
