### PR TITLE
[opt](nereids) optimize str-like-col range filter estimation

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
we have an order reserved mappping from string to double.
for string column A, we have double values for A.min and A.max.
when estimating A<"abc", A.min/max could be used to judge whether 'abc' is between A.min and A.max, but it cannot be used to do range estimation. suppose "abc" is mapped to double x. if we compute selectivity by formula "sel = (x-A.min)/(A.max-A.min)", we are likely to obtain extreme values.
 
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run p0

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
