### PR TITLE
[opt](hash_join) Merging all build blocks at once will cause performance issue

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

For better performance, blocks should be merged as soon as possible in the sink operator, allowing parallel execution with the upstream pipeline.

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
