### PR TITLE
[branch-2.0](routine-load) routine load date where expression rewrite should change over time

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

#33345

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by cjj2010 — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
