### PR TITLE
[fix](mysql compatibility) add an internal database mysql to improve mysql compatibility

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
## Proposed changes

Add an internal database with name 'mysql' to improve compatibility with mysqldump.

## Further comments

releated issue #22867 

When using mysqldump to dump all databases from mysql, users will add a command line arguements `--all-databases` to avoid adding expatiatory names.

According to source code of mysql dump (version 8.1), target server must have a database with name 'mysql' to make things work if we using `--all-databases`
```cpp
// mysqldump.cc
static int dump_all_databases() {
    ...
    uint db_cnt = 0, cnt = 0
    uint mysql_db_found = 0;
    ...
    if (mysql_query_with_error_report(mysql, &tableres, "SHOW DATABASES"))
    ...
    while ((row = mysql_fetch_row(tableres))) {
        ...
        if (mysql_db_found || (!my_strcasecmp(charset_info, row[0], "mysql"))) {
            if (dump_all_tables_in_db(row[0])) result = 1;
            mysql_db_found = 1;
            /*
                once mysql database is found dump all dbs saved as part
                of database_list
            */
            for (; cnt < db_cnt; cnt++) {
                if (dump_all_tables_in_db(database_list[cnt])) result = 1;
                my_free(database_list[cnt]);
            }
        } else {
            /*
                till mysql database is not found save database names to
                database_list
            */
            database_list[db_cnt] =
                my_strdup(PSI_NOT_INSTRUMENTED, row[0], MYF(MY_WME | MY_ZEROFILL));
            db_cnt++;
        }
    }
    assert(mysql_db_found);
    ...
}
```

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
fixing issue #22867

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.06 seconds
 stream load tsv:          514 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162144520 Bytes

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.83 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162411831 Bytes

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.85 seconds
 stream load tsv:          512 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162335228 Bytes

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.7 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162353140 Bytes

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
