### PR TITLE
[chore](dependencies)upgrade hive catalog to 2.0.0

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Changes
- Version 2.0.0 of the shade package eliminates potential jar conflicts, resolves dependency component issues, and significantly reduces package size.

- Utilize the directly-dependent guava library instead of relying on transitively included libraries.
- [Adapt paimon 0.7.0](https://github.com/apache/doris/pull/33424/commits/8f783d2fb941e851b05226052c2c8e1c7da8fc04)

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by xiaokang** [comment]
@CalvinKirs Do you submit this pr to wrong branch?

**Comment by CalvinKirs** [comment]
> @CalvinKirs Do you submit this pr to wrong branch?↳

No, this is a 2.0 change, but it is still in WIP status.

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
