### PR TITLE
[Feature]Support cancel the timeout ExportJob is still in exporting

### LINKED ISSUE #5777: [Export] The timeout ExportJob  is still in exporting
**Describe the bug**
The timeout ExportJob  is still in exporting

**To Reproduce**

1. show data from table 
image

2. export job
image

3. master  fe.log
fe.log always has follow msg
image

4. org.apache.doris.task.ExportExportingTask#exec
May be the usage of synchronized  in method exec() is incorrect?
but after test
image
image

### PR DESCRIPTION
**Pull request by WindyGao**
## Proposed changes
Cancel the timeout ExportJob is still in exporting

[issue-5777](https://github.com/apache/incubator-doris/issues/5777)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

- [x] I have created an issue on (Fix #5777 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WindyGao** [comment]
1. Recurring problems
See [issue-5777](https://github.com/apache/incubator-doris/issues/5777) step 4

2. Compiling and unit tests with stuck job
image
job 17006 unexpired is stuck at 99% progress 

image
job 17006 expired is canceled by my code

**Comment by WindyGao** [comment]
@EmmyMiao87 hi 
i have built it in docker
use sh build.sh
image

**Comment by morningman** [comment]
> why does TeamCity build failed?...

You need to rebase the master code first.
And as we discussed before, there are some other problems about export feature, I think we can fix them all in one PR.

**Comment by EmmyMiao87** [comment]
Fixed #5777

**Pull request closed without merging**
