### PR TITLE
[fix][build](audit-loader) Fix a build error for AuditLoaderPlugin.

### PR DESCRIPTION
**Pull request by lide-reed**
## Proposed changes

Issue Number: close #xxx

Since AuditEvent.java has been moved to the audit directory, the import here also needs to be modified accordingly.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Comment by lide-reed** [comment]
run buildall

**Comment by lide-reed** [comment]
run buildall

**Comment by lide-reed** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Comment by xy720** [comment]
run buildall

**Pull request merged**
