### PR TITLE
[fix](inverted index) Writing to the inverted index also writes to the file cache.

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. When write_file_cache is true, writing to the inverted index also writes to the file cache.

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
