### PR TITLE
[bug](node) add dependency for set operation node

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
These sinks must be completed one by one in order, eg: child(1) must wait child(0) build finish

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
