### PR TITLE
[Chore](tools): update ssb tools

### PR DESCRIPTION
**Pull request by feifeifeimoon**
## Proposed changes

Modify the behavior of ssb tools to be consistent with tpch tpcds.
image

image

image

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by feifeifeimoon** [comment]
run buildall

**Review by xzj7019 — APPROVED** [review]

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
