### PR TITLE
[Enhancement](datetimev2-enhance) support 'microseconds_sub' function for datetimev2

### LINKED ISSUE #17129: [Enhancement] (datetimev2-enhance) support 'microseconds_sub' function for datetimev2
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

As descriptions in #16561 
Now Doris already supports DATETIMEV2 which could have precision up to microseconds. But function `microseconds_sub` is not supported yet.

```
mysql> select microseconds_sub(now(3), 1);
ERROR 1105 (HY000): errCode = 2, detailMessage = Function microseconds_sub is not implemented
```

### Solution

Based on #16967 , implement some extented template function and register it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WinkerDu**
# Proposed changes

Issue Number: close #17129

## Problem summary

Based on #16970 , introduce `microseconds_sub` function for datetimev2

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
run buildall

**Comment by WinkerDu** [comment]
@BiteTheDDDDt Please have a review, thank you :)

**Review by Yukang-Lian — APPROVED** [review]
Good job! LGTM.

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
