### PR TITLE
[Bug](query) fix meet invalid column when direct scan on mow mv

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
fix meet invalid column when direct scan on mow mv
```
2024-06-11 18:01:14,079 [query] |Client=|User=root|Ctl=internal|Db=__internal_schema|State=OK|ErrorCode=0|ErrorMessage=|Time(ms)=3601|ScanBytes=57344|ScanRows=1|ReturnRows=0|StmtId=0|QueryId=67799c8ba77d4ffb-8a80c73b94bb784c|IsQuery=true|isNereids=true|feIp=10.16.10.8|Stmt=SELECT SUBSTRING(CAST(MIN(`mv_(k2 + k3)`) AS STRING), 1, 1024) as min, SUBSTRING(CAST(MAX(`mv_(k2 + k3)`) AS STRING), 1, 1024) as max FROM `regression_test_mv_p0_test_mv_mow`.`u_table` index `k123p`|CpuTimeMS=3544|ShuffleSendBytes=0|ShuffleSendRows=0|SqlHash=null|peakMemoryBytes=168736|SqlDigest=|cloudClusterName=UNKNOWN|TraceId=|WorkloadGroup=normal|FuzzyVariables=|scanBytesFromLocalStorage=0|scanBytesFromRemoteStorage=0
 2024-06-11 18:01:08,291 WARN (Analysis Job Executor-0|521) [Coordinator.getNext():1109] Query 67799c8ba77d4ffb-8a80c73b94bb784c coordinator get next fail, (hk2.dev.selectdb-in.cc)[INTERNAL_ERROR]SegmentIterator meet invalid column, id=1, name=mv_(k2 + k3), need cancel
```

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]
LGTM. Need another review by Nereids team.

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
