### PR TITLE
[bug](compile)fix compile error

### PR DESCRIPTION
**Pull request by LemonLiTree**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
This problem may occur because your version of thirdparty is wrong

**Comment by LemonLiTree** [comment]
> This problem may occur because your version of thirdparty is wrong

but i'm weird: The thirdparty seems to have not been updated ， And this error is only compiled on arm

**Comment by BiteTheDDDDt** [comment]
> > This problem may occur because your version of thirdparty is wrong
> 
> but i'm weird: The thirdparty seems to have not been updated ， And this error is only compiled on arm

1.2 require s2geo v0.9, master require s2geo 1.0, you can check this.

**Comment by LemonLiTree** [comment]
> > > This problem may occur because your version of thirdparty is wrong
> > 
> > 
> > but i'm weird: The thirdparty seems to have not been updated ， And this error is only compiled on arm
> 
> 1.2 require s2geo v0.9, master require s2geo 1.0, you can check this.
yeah，closed

**Pull request closed without merging**
