### PR TITLE
(cloud-merge) Fix create mv failed bacause expr is null

### PR DESCRIPTION
**Pull request by Lchangliang**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Lchangliang** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Lchangliang** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by Lchangliang** [comment]
run p0

**Comment by Lchangliang** [comment]
run buildall

**Comment by Lchangliang** [comment]
run feut

**Comment by Lchangliang** [comment]
run external

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Lchangliang** [comment]
run buildall

**Comment by Lchangliang** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
