### PR TITLE
Add approx count distinct function

### LINKED ISSUE #4220: [FEATURE] Support approx_count_distinct function
We currently have a function called "NDV", but the name of this function is not easy to understand, and we cannot literally understand what the function does. 
So we should add a common alias "approx_count_distinct" to "NDV"

### PR DESCRIPTION
**Pull request by HangyuanLiu**
FIX #4220 
This PR not modify logical, only add a alias to ndv

### CODE REVIEW

**Comment by kangkaisen** [comment]
@HangyuanLiu Hi, you should also add a doc for this function.

**Review by kangkaisen — APPROVED** [review]
+1

**Review by morningman — CHANGES_REQUESTED** [review]
This PR just add alias for ndv() function.
But why you remove all docs about ndv?

**Review by morningman — APPROVED** [review]
function name `ndv()` is not recommended to be used any more.

**Pull request merged**
