### PR TITLE
[improvement](meta) Switch meta serialization to gson 2

### PR DESCRIPTION
**Pull request by iszhangpch**
## Proposed changes

Issue Number:

Switch meta serialization to gson
Contains the following classes：

BatchAlterJobPersistInfo
BackupJob
~~Repository~~
RestoreJob
~~Database~~
FunctionSearchDesc

### CODE REVIEW

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
