### PR TITLE
[minor](dependencies) Incorporate BOMs for Jetty, gRPC, Netty, and Jackson to enhance dependency management

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes

- Added Jetty BOM for unified versioning of Jetty dependencies
- Integrated gRPC BOM to automate and synchronize gRPC module versions
- Incorporated Netty BOM for consistent Netty library versioning
- Adopted Jackson BOM for centralized management of Jackson components

These modifications improve dependency consistency and facilitate future upgrades.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run external

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run external

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Pull request closed without merging**
