### PR TITLE
[fix](docs)Fix description for error code 1051 #27751

### LINKED ISSUE #27751: [Feature] Adding error code for unknown table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In mysql, code 1146, 1049, 1051 represent  `Table '%s.%s' doesn't exist`, `Unknown database '%s'` and `Message: Unknown table '%s'` respectively. But I cannot find relevent error code in [error table](https://github.com/apache/doris/blob/master/docs/en/docs/admin-manual/maint-monitor/doris-error-code.md). Perhaps adding these error code will improve the user experience.

### Use case

Run
```sql
DESCRIBE test_table -- non-existent table
```
current
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```
expectation
```
ERROR <specialized error code> (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #27751

Update description for error code 1051 
added description and error code 1109 to document

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Vallishp** [comment]
run build all

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
