### PR TITLE
[Bug](compatibility) fix covar_samp function coredump when upgrade

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

in branch-2.1, the function covar_samp mode is PropagateNullable
eg: select covar_samp(non_nullable(x), y) from test_covar_samp;
x, y has nullable, and return is nullable
and now the column of non_nullable(x), y is nullable  should check is nullable alone.

the fixed in branch-21 
https://github.com/apache/doris/pull/39943

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
