### PR TITLE
[Enhancement](broker)Doris support obs broker load

### LINKED ISSUE #12329: [Enhancement] doris support obs broker load
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently doris supports S3. In theory, all cloud storages that support S3 can use doris.
However, due to the encoding problem of some character functions in obs-S3, "*", "=" are unavailable, so we can support OBSStorage on doris instead of relying on S3.

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liujinhui1994**
# Proposed changes

Issue Number: close #12329 

## Problem summary

1. Upgrade fs_broker module hadoop2.7.3->hadoop2.8.3
2. Support obs broker load

org.apache.doris.broker.hdfs.FileSystemManager add getOBSFileSystem method

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [x] Yes
    - [ ] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

> LOAD LABEL test014
(
    DATA INFILE("obs://xxxx/datalake/tmp/doris/data/ds=20220829/*")
    INTO TABLE personas_topic_static_hive_bitmap
    FORMAT AS "parquet"
	  (label_code, label_value, ds, mobile)  
   SET 
   (label_code=label_code, label_value=label_value, ds = str_to_date(`ds`,'%Y%m%d'), mobile = to_bitmap(mobile) )
)
WITH BROKER "broker_name"
    ( 
      "fs.obs.access.key" = "xxxx", 
      "fs.obs.secret.key" = "xxxx",
      "fs.obs.endpoint" =   "xxxx"
    )
PROPERTIES
(
    "timeout"="14400",
    "max_filter_ratio"="0"
);

### CODE REVIEW

**Review by Jibing-Li — DISMISSED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
hi @liujinhui1994 , please rebase master to pass the checks

**Comment by liujinhui1994** [comment]
@morningman ok

**Pull request merged**
