### PR TITLE
[fix](schema-change) Fix schema change run into nullable check specified for MV

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Fix using `!=` to compare ColumnType as reference, introduced by #32810 
Add a minimal verify case.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
2.0 and 2.1 do not have this bug

**Pull request merged**
