### PR TITLE
[branch-2.0](enhancement) insert overwite support expr function

### LINKED ISSUE #29161: insert overwite support expr function
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

 insert overwite support expr function 

insert overwrite table test_partitioned27 partitions("p"= DATE_FORMAT(now(), 'p%Y%m%d'))
select 921 as id,'2023-12-27 00:00:00' as gmt_create ,'a' as column1;

at branch2.0 not support

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mnloveyx**
## Proposed changes

Issue Number: close #29161 

## Further comments

insert overwrite table test_partitioned27 partition("p"= DATE_FORMAT(now(), 'p%Y%m%d'))
select 921 as id,'2023-12-27 00:00:00' as gmt_create ,'a' as column1;

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mnloveyx — COMMENTED** [review]
review

**Comment by xiaokang** [comment]
@mnloveyx new feature support should be added to master instead of 2.0 version.

**Comment by mnloveyx** [comment]
> @mnloveyx new feature support should be added to master instead of 2.0 version.

got it

**Comment by mnloveyx** [comment]
> @mnloveyx new feature support should be added to master instead of 2.0 version.

is not a new feature， is a function enhance actual

**Comment by dataroaring** [comment]
Please add some regression tests, including different types and exprs.

**Pull request closed without merging**
