### PR TITLE
[Chore](function) remove repeat max num

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
remove repeat max num

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
