### PR TITLE
[docs](cache) Refactor query-cache docs

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Refactor query-cache docs

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
