### PR TITLE
[opt](nereids) enable runtime filter use cte as target

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
1. remove some unused maps in RuntimeFilterContext
2. let runtime filter use cte as target

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run performance

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run cloud_p0

**Comment by englefly** [comment]
run fe-ut

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Review by starocean999 — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
