### PR TITLE
[Improve](Job)Support other types of Job query interfaces

### PR DESCRIPTION
**Pull request by CalvinKirs**
- Support MTMV job
- Task info add create time and sql
- Optimize scheduling logic

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
