### PR TITLE
[feature](inverted index) multi_match function add

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. select * from tbl where multi_match(c1, 'c2, c3, c4', 'phrase_prefix', 'xxx');
2. multi_match performs a match_phrase_prefix query on the columns specified in the first and second parameters.  The value to be searched is specified in the fourth parameter.

### CODE REVIEW

**Review by airborne12 — DISMISSED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
