### PR TITLE
[fix](regression) fix unstable insert_p2/txn_insert_with_schema_change and test_group_commit_interval_ms_property

### PR DESCRIPTION
**Pull request by mymeiyi**

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run cloud_p0

**Comment by mymeiyi** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
