### PR TITLE
[Bug](ES): Es object mapping error

### LINKED ISSUE #18379: [Bug] Can not grant ES catalog table to a user
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris version is : 1.2.1, but the master code has the same problem.

### What's Wrong?

mysql> select * from es.default_db.test1;
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: java.lang.NullPointerException

```
{code:java}
2023-04-03 16:10:00,672 WARN (mysql-nio-pool-25|29718) [StmtExecutor.analyze():915] Analyze failed. stmt[677, d16718ccf72b4d6b-b8a4ea81207d215d]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-30.0-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-30.0-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[guava-30.0-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935) ~[guava-30.0-jre.jar:?]
        at org.apache.doris.datasource.ExternalSchemaCache.getSchema(ExternalSchemaCache.java:91) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.external.ExternalTable.getFullSchema(ExternalTable.java:220) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.external.ExternalTable.getBaseSchema(ExternalTable.java:225) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.expandStar(SelectStmt.java:1150) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.expandStar(SelectStmt.java:1119) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.analyze(SelectStmt.java:514) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:989) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:898) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:631) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:449) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:426) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:423) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:567) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:808) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
Caused by: java.lang.NullPointerException
        at org.apache.doris.external.elasticsearch.EsUtil.replaceFieldAlias(EsUtil.java:218) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.external.elasticsearch.EsUtil.genColumnsFromEs(EsUtil.java:211) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.external.elasticsearch.EsUtil.genColumnsFromEs(EsUtil.java:186) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.external.EsExternalTable.initSchema(EsExternalTable.java:84) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.ExternalCatalog.getSchema(ExternalCatalog.java:217) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.ExternalSchemaCache.loadSchema(ExternalSchemaCache.java:81) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.ExternalSchemaCache.access$000(ExternalSchemaCache.java:44) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.ExternalSchemaCache$1.load(ExternalSchemaCache.java:62) ~[doris-fe.jar:1.2-SNAPSHOT] {code}
```

### What You Expected?

grant es table, and query it successfully

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by stalary**
# Proposed changes

Issue Number: close https://github.com/apache/doris/issues/18379

## Problem summary

Es object mapping error

## Checklist(Required)

* [x] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xxiao2018** [comment]
run buildall

**Comment by stalary** [comment]
run buildall

**Comment by stalary** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
