### PR TITLE
[bug](cloud) fix null pointer exception in get partition visible version rpc

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

fix null pointer exception in get partition visible version rpc

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by Yulei-Yang — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run cloud_p1

**Comment by xy720** [comment]
run buildall

**Pull request merged**
