### PR TITLE
[refactor](olap-server) Extract submitted compaction tasks management logic to an encapsulated class

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Split `_tablet_submitted_cumu_compaction`, `_tablet_submitted_base_compaction`, `_tablet_submitted_full_compaction` from `StorageEngine` to an encapsuled class `CompactionSubmitRegistry`, for better code reuse and resource management.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by luwei16 — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
