### PR TITLE
[feature](map) basic functions for map datatype

### PR DESCRIPTION
**Pull request by xiaokang**
# Proposed changes

Issue Number: close #xxx

## Problem summary

basic functions for map datatype:
- MAP<K, V> map(K k1, V v1, ...)
- BIGINT map_size(MAP<K, V> m)
- BOOL map_contains_key(MAP<K, V> m, K k1)
- BOOL map_contains_value(MAP<K, V> m, V v1)
- ARRAY< K> map_keys(MAP<K, V> m)
- ARRAY< V> map_values(MAP<K, V> m)

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run beut

**Comment by xiaokang** [comment]
run buildall

**Review by xy720 — DISMISSED** [review]
lgtm, but need rebase master

**Comment by amorynan** [comment]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by xy720 — DISMISSED** [review]

**Comment by xiaokang** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Pull request merged**
