### PR TITLE
[fix-branch-1.2-lts](TaskWorkerPool) Fix task worker pool and remove unnecessary copy

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

cherry-pick #19822

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Comment by yujun777** [comment]
#19822

**Comment by bobhan1** [comment]
run clickbench

**Pull request merged**
