### PR TITLE
[branch-2.0](tablet invert) fix tablet invert index thread trace

### PR DESCRIPTION
**Pull request by yujun777**
pick code from pr #26563

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run feut

**Comment by xiaokang** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Pull request merged**
