### PR TITLE
[Refactor] Replace '#ifndef' with '#pragma once'

### PR DESCRIPTION
**Pull request by xlwh**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
Is there any way to automatically detect header guard style?

**Comment by xlwh** [comment]
> Is there any way to automatically detect header guard style?

Sorry, I don't have a good way to automatically check.  Do you have any good suggest? thanks!

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by lverson3** [comment]
In file included from /home/htcc/gopr/doris/incubator-doris/be/src/vec/columns/columns_common.cpp:25:
/home/htcc/gopr/doris/incubator-doris/be/src/util/simd/bits.h: In function 'uint32_t doris::simd::bytes32_mask_to_bits32_mask(const uint8_t*)':
/home/htcc/gopr/doris/incubator-doris/be/src/util/simd/bits.h:49:10: error: 'size_t' was not declared in this scope; did you mean 'std::size_t'?
   49 |     for (size_t i = 0; i < 32; ++i) 

编译报错是什么原因导致的呢?辛苦帮忙看下

**Pull request merged**
