### PR TITLE
[fix](block) add block columns size dcheck

### PR DESCRIPTION
**Pull request by nanfeng1999**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run p0

**Comment by nanfeng1999** [comment]
run arm

**Comment by nanfeng1999** [comment]
run arm

**Comment by nanfeng1999** [comment]
run arm

**Comment by nanfeng1999** [comment]
run arm

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
lgtm

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by nanfeng1999** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
