### PR TITLE
[opt](multicast) opt MultiCastDataStreamer when source close

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
When the source is closed, we reduce the initial value of the use count to avoid unnecessary copies.

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run performance

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request closed without merging**
