### PR TITLE
[fix](merge-on-write) fix wrong result when query with prefix key predicate

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

MySQL [regression_test_correctness_p0]> select * from test_select_with_perfix;
+-------+-------+------+----------+---------------------+------+
| c0    | c1    | c2   | c3       | c4                  | c5   |
+-------+-------+------+----------+---------------------+------+
|       | efgh  |    1 | abcdad   | 2023-06-27 00:00:00 |    1 |
|       | mefgh |    1 | abcdad   | 2023-06-27 00:00:00 |    1 |
| abcd  | efgh  |    1 | abcdad   | 2023-06-27 00:00:00 |    1 |
| abcd  | efgh  |    2 | abcdad   | 2023-06-27 00:00:00 |    1 |
| abcd  | efghf |    2 | abcdad   | 2023-06-27 00:00:00 |    1 |
| abcde | ab    |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| abcdf | ab    |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| abcdf | dab   |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| abce  | dab   |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| abce  | ldab  |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| abd   | ldab  |    2 | 2efraeef | 2023-06-27 00:00:00 |    1 |
| def   | hh    |    2 | afad     | 2023-06-27 00:00:00 |    1 |
+-------+-------+------+----------+---------------------+------+
12 rows in set (0.01 sec)

MySQL [regression_test_correctness_p0]> select * from test_select_with_perfix where c0='abc';
Empty set (0.01 sec)

MySQL [regression_test_correctness_p0]> select c0 from test_select_with_perfix where c0='abc';
+-------+
| c0    |
+-------+
| abcd  |
| abcd  |
| abcd  |
| abcde |
| abcdf |
| abcdf |
| abce  |
| abce  |
+-------+

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.47 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162390254 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230712232754_clickbench_pr_177476.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
