### PR TITLE
[Bug] Fix the bug of `nullif` function:

### LINKED ISSUE #5858: [BUG] NULLIF() function result is wrong
**Describe the bug**

case1: doris own value is different
```
     SELECT NULLIF (91, CAST(69 AS DECIMAL) );
     Result: 0

     SELECT NULLIF (91, CAST(69 AS INT) );
     Results: 91
```

case2: different from mysql value
```
     SELECT ALL NULLIF (-98, NULL) AS col0
     Doris result: NULL
     Mysql result: -98
```

Found through the sqllogictest test case.

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes
1. Prevent return NULL call nullif(98, null) in FE
2. Support DecimalV2 of nullif function to get the right result

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5858) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by EmmyMiao87 — COMMENTED** [review]
what if  SELECT ALL NULLIF (-98, NULL) AS col0 ?

**Comment by HappenLee** [comment]
> what if SELECT ALL NULLIF (-98, NULL) AS col0 ?

The right result of nullif(-98, null) is -98. but before fix the bug, the answer is `null`. Because the FE wiil treat all the function not in `non_null_result_with_null_param_functions` alwalys `null` if there params have `null`.

so add the `nullif` function to `non_null_result_with_null_param_functions`  we can get the right answer:`98`

**Comment by EmmyMiao87** [comment]
> non_null_result_with_null_param_functions

Great

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

**Pull request merged**
