### PR TITLE
[log](gc) add log for unused rowsets gc

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

Add logs for unused rowset gc to observe it's schedule easily

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run p0

**Comment by TsukiokaKogane** [comment]
hello, about this mr, do you also encounter that a large number of unused rowsets not gc in doris version 2.0?

**Pull request merged**
