### PR TITLE
[opt](Nereids) do not fallback if nereids failed because timeout

### PR DESCRIPTION
**Pull request by morrySnow**
since legacy planner will cost more time to plan, fallback will be worse than throw exception directly

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p1

**Review by 924060929 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
