### PR TITLE
[fix](nereids)change lag/lead function signature

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes
remove CharType from the signature

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
