### PR TITLE
[Enhancement](inverted index) strictly checkout inverted index properties

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by qidaye — DISMISSED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by xiaokang — COMMENTED** [review]
pls add testcase

**Comment by qidaye** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
