### PR TITLE
[fix](catalog) refactor location path and support default fs

### PR DESCRIPTION
**Pull request by morningman**
`LocationPath` is used for normalizing the path uri of files of external table.
But previouly, we use `LocationPath` every where and it is a very heavy operation.

This PR refactor the logic as follow:
1. The `LocationPath` will once be used once when generating file split, and it will be saved in FileSplit.
2. All following logic will reuse the `LocationPath` in file split.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by wsjz — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
