### PR TITLE
[Fix](load) Fix insert into wrong value

### PR DESCRIPTION
**Pull request by Yukang-Lian**
Problem: When the old optimizer processes an INSERT INTO statement that contains two quotation marks, it results in only one quotation mark being written into the database.

Reason: During syntax parsing, the old optimizer interprets two quotation marks as a single quotation mark.

Solution: Remove the logic that consolidates two quotation marks into one.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by starocean999** [comment]
this pr may break behavior like : 'a''b' -> a'b. Suggest use new optimizer or use 'a''''b' -> a''b instead of 'a\'\'b'

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
