### PR TITLE
[enhancement](cloud) support BE http action: /api/file_cache?op=hash

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Add a http action which can calculate its hash value based on the path you input. It's useful when you debug.

### API
```http
GET /api/file_cache
```

### request parameter

|param|type|desc|require|
|:---|:---|:---|:---|
|op|string|the value must be `hash`, other value you can refer to #37484 |yes|
|value|string|the input you want to calc hash|yes|

### response

if success
|param|type|desc|
|:---|:---|:---|
|hash|string|the hash value of your input|

if fail
|param|type|desc|
|:---|:---|:---|
|status|string|error status|
|msg|string|error message|

#### case 1

```bash
curl  '172.100.0.4:8040/api/file_cache?op=hash&value=0200000000000001bf42c14374fff491ffb7c89a1a65c5bb_0.dat'
```

return
```json
{"hash":"c6a599f453f67f0949f80ad9990fa3dd"}
```

#### case 2

```bash
curl  '172.100.0.4:8040/api/file_cache?op=hash'
```

return
```json
{
    "status": "INVALID_ARGUMENT",
    "msg": "missing parameter: value is required"
}
```

### CODE REVIEW

**Comment by yagagagaga** [comment]
run buildall

**Review by gavinchou — COMMENTED** [review]
Pls add a file cache regression test too.

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
