### PR TITLE
[feature](insert)add hive table sink thrift

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

add hive table sink thrift
add partition type
add new compress type

issue: https://github.com/apache/doris/issues/31442

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
https://github.com/apache/doris/issues/31442

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
