### PR TITLE
[Enhancement](partition) Support use Auto and Dynamic partition at the same time

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

before we forbid it in https://github.com/apache/doris/pull/33736, now it's time to let it go.

now we support:
```sql
mysql> create table auto_dynamic(
    ->             k0 datetime(6) NOT NULL
    ->         )
    ->         auto partition by range (date_trunc(k0, 'year'))
    ->         (
    ->         )
    ->         DISTRIBUTED BY HASH(`k0`) BUCKETS 2
    ->         properties(
    ->             "dynamic_partition.enable" = "true",
    ->             "dynamic_partition.prefix" = "p",
    ->             "dynamic_partition.start" = "-50",
    ->             "dynamic_partition.end" = "0",
    ->             "dynamic_partition.time_unit" = "year",
    ->             "replication_num" = "1"
    ->         );
Query OK, 0 rows affected (0.12 sec)
```

with this, the users could manage their data more flexible

we will refactor the docs of it, and the only recommended way it set end to zero.

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
wait https://github.com/apache/doris/pull/39695 merge firstly

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by yujun777 — APPROVED** [review]
LGTM

**Pull request merged**
