### PR TITLE
add iot-function to doris

### PR DESCRIPTION
**Pull request by wangqiuhao0912**
Create function SQL as follows:

drop FUNCTION udaf_iot_first(BIGINT,DOUBLE);
CREATE AGGREGATE FUNCTION udaf_iot_first(BIGINT,DOUBLE) RETURNS DOUBLE
PROPERTIES (
"init_fn"="_ZN9doris_udf12IotFunctions18init_iot_functionsEPNS_15FunctionContextEPNS_9StringValE",
"update_fn"="_ZN9doris_udf12IotFunctions16iot_first_updateEPNS_15FunctionContextERKNS_9BigIntValERKNS_9DoubleValEPNS_9StringValE",
"merge_fn"="_ZN9doris_udf12IotFunctions15iot_first_mergeEPNS_15FunctionContextERKNS_9StringValEPS3_",
"serialize_fn"="_ZN9doris_udf12IotFunctions9serializeEPNS_15FunctionContextERKNS_9StringValE",
"finalize_fn"="_ZN9doris_udf12IotFunctions8finalizeEPNS_15FunctionContextERKNS_9StringValE",
"object_file"="http://IP/../libudaf_iot_algorithm.so" );

### CODE REVIEW

**Comment by morningman** [comment]
Hi @wangqiuhao0912 ， could you give an example of this function's usage?

**Comment by wangqiuhao0912** [comment]
> Hi @wangqiuhao0912 ， could you give an example of this function's usage?


Hi @morningman ,this is create table sql  and usage:

create table equipment_no_par(equipment varchar(32),
ts bigint,
code1 double)
UNIQUE KEY(`equipment`,`ts`)
DISTRIBUTED BY HASH(equipment) buckets 1;

select equipment,udaf_iot_first(ts,code1) from equipment_no_par group by equipment;

**Comment by morningman** [comment]
> udaf_iot_first

Sorry, I want to know the behavior of this udaf.

**Comment by wangqiuhao0912** [comment]
@morningman 

In fact, the meaning of this function is very simple, that is, to find the code1 corresponding to the smallest timestamp (ts) in this group, which will often be used in IoT data. For example, the two rows of data are as follows:
equipment     ts                code1
equ_a     1640274843000  1.1
equ_a     1640274844000  2.5
Using udaf-iot-first(ts, code1) is 1.1, similar to first_value over(), but it is an aggregation within a group

**Comment by jackwener** [comment]
This PR has not been updated for a long time.

There could be many reasons.

If it's caused by there are no maintainers to push or ignore this PR, I'm sorry.

If you contact maintainer or want to continue this PR, feel free to @me or @other maintainers.

**Pull request closed without merging**
