### PR TITLE
[Fix](load) fix request_slave_tablet_pull_rowset get wrong url in case of ipv6 address

### LINKED ISSUE #19025: [Bug] request_slave_tablet_pull_rowset get wrong url in case of ipv6 address
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2

### What's Wrong?

stream load task in enable_single_replica_load mode formulate wrong url in case of ipv6 address
image

### What You Expected?

get ipv6 address with host address in brackets 

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TsukiokaKogane**
# Proposed changes

Issue Number: close #19025

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TsukiokaKogane** [comment]
run buildall

**Comment by TsukiokaKogane** [comment]
run p0

**Comment by TsukiokaKogane** [comment]
run p0

**Comment by TsukiokaKogane** [comment]
run buildall

**Comment by TsukiokaKogane** [comment]
run p0

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Hi @TsukiokaKogane  please rebase master to pass the checks

**Comment by TsukiokaKogane** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by TsukiokaKogane** [comment]
run buildall

**Comment by TsukiokaKogane** [comment]
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
