### PR TITLE
[fix](schema-change) Fix wrong intput column for cast validity check

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

1. Use column idx of ref block instead of new block to indicate the ref column.
2. Rename some variables to clarify their meanings.
3. Clarify some log msg.
4. Add a minimal case to verify the change.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
