### PR TITLE
[fix](backup) support aws_token for backup/restore on master branch

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

after #15340, support access s3 via temporary security credentials. but someday someone removed token info code for s3 client on be, and this pr fix it.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
sh buildall

**Comment by nextdreamblue** [comment]
sh buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by dataroaring** [comment]
please add a regression test?

**Comment by nextdreamblue** [comment]
> please add a regression test?

it's not easy to add, it need a temporary token and this token will be expired. can not set a token for regression test for a long time.

**Review by morningman — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
