### PR TITLE
[feat](nereids) add nereids profile

### PR DESCRIPTION
**Pull request by mongo360**
pick: [#26935](https://github.com/apache/doris/pull/26935)

add nereids profile for 2.0

### CODE REVIEW

**Review by morrySnow — APPROVED** [review]

**Review by GoGoWen — APPROVED** [review]
LGTM

**Comment by mongo360** [comment]
run buildall

**Comment by mongo360** [comment]
run buildall

**Comment by mongo360** [comment]
run feut

**Pull request merged**
