### PR TITLE
[improve](move-memtable) reuse connection in load_stream_stub

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Reuse connection in `LoadStreamStub::open()` and hopefully fix the "Connection reset by peer" issue under heavy load.

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
