### PR TITLE
Revert "[fix](compaction) fix the longest continuous rowsets cannot be selected when missing rowsets (#38728) (#39262)"

### PR DESCRIPTION
**Pull request by luwei16**
This reverts commit c9949f24e5c15e9529285f0e99b7ffdb1095558b.

This pr may increase the probability of full clone failure, so revert it first.

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run beut

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
