### PR TITLE
[chore](license) fix incomplete license header

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by liutang123 — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run cloudp1

**Comment by yiguolei** [comment]
run cloud_p1

**Comment by yiguolei** [comment]
run buildall

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
