### PR TITLE
[fix](optimizer) join reorder may cause column non-existence problem

### LINKED ISSUE #10674: [Bug] join reorder may cause column non-existence problem
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

summary:
Join reorder will make the dependencies out of order, resulting in non-existent columns in reanalyzing.
for example：
```SQL
select * from t1 inner join t2 on t1.a = t2.b inner join t3 on t3.c = t2.b;
```
The table size relationship is t3>t2>t1,  and the problem that t2.b does not exist will occur in reanalyzing.

The reason is that the dependency check in ReorderTable only needs to satisfy one of the predicates involved regardless of its order, for example, when checking t2, which involves t3.c = t2.b and t1.a = t2.b, the order of [t3,t2] can satisfy t3.c = t2.b, so that the order of [t3,t2,t1] can be checked through

### What You Expected?

fix this

### How to Reproduce?

see https://github.com/apache/doris/pull/10670 testDefaultJoinReorderWithView

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yinzhijian**
# Proposed changes

Issue Number: close #10674

## Problem Summary:

for example:
select * from t1 inner join t2 on t1.a = t2.b inner join t3 on t3.c = t2.b;
If t3 is a large table, it will be placed first after the reorderTable,
and the problem that t2.b does not exist will occur in reanalyzing.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yangzhg — DISMISSED** [review]
LGTM

**Comment by yangzhg** [comment]
you need to create an issue

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
