### PR TITLE
[fix](nereids) Agg on unknown-stats column

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p1

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p1

**Comment by englefly** [comment]
run buildp1

**Comment by englefly** [comment]
run p1

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by xzj7019 — APPROVED** [review]

**Pull request merged**
