### PR TITLE
[fix](test) fix some test cases

### PR DESCRIPTION
**Pull request by morningman**
### What problem does this PR solve?

Problem Summary:

1. add some missing output blocks for `test_audit_log_behavior.out`
2. `call flush_audit_log()` does not support old planner, add check for it. followup #42262

### Check List (For Committer)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [x] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [x] Confirm test cases
- [ ] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
