### PR TITLE
[chore](thrift compatibility) Fix thrift id on master is not compatible with branch-2.1

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Ref https://github.com/apache/doris/pull/39852

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Comment by yiguolei** [comment]
skip buildall

**Pull request merged**
