### PR TITLE
[fix](auth)ldap set passwd need forward to master

### PR DESCRIPTION
**Pull request by zddr**
ldap set passwd need forward to master

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by zddr** [comment]
run feut

**Pull request merged**
