### PR TITLE
[Refactor](meta) Delete useless classes and write methods

### PR DESCRIPTION
**Pull request by iszhangpch**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by iszhangpch** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Comment by iszhangpch** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by w41ter — APPROVED** [review]

**Pull request merged**
