### PR TITLE
[chore][fe] Get meta returns dropped partitions in binlog manager

### PR DESCRIPTION
**Pull request by w41ter**
The CCR syncer needs to know the distribution of tables, partitions, indexes, and replicas when synchronizing binlogs. If a partition is deleted before the binlog synchronization is complete, the CCR syncer cannot continue synchronizing. This PR will record the deleted partitions and include them in the get meta response, allowing the CCR syncer to filter out the binlogs that belong to these partitions.

The CCR syncer part PR is selectdb/ccr-syncer#117.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
