### PR TITLE
[feature](doris compose) Add create cloud cluster

### PR DESCRIPTION
**Pull request by yujun777**
1. Add create cloud cluster. The simplest way to create a cloud cluster
```
python docker/runtime/doris-compose/doris-compose.py up  <your-cluster-name> <your-doris-image>  --cloud
```
It then create 1 fdb, 1 ms, 1 recycler,  3 fe,   3 be.

2. Add increment add node to existing cloud cluster.

3. Add command for generate regression-conf-custom.groovy for regression test.

4. Regression test can create cloud docker cluster.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
