### PR TITLE
[fix](MTMV) Disable partition specification temporarily

### LINKED ISSUE #20773: [Bug] create mtmv with partition error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

描述
CREATE TABLE user_p
(
    k1 TINYINT NOT NULL,
    k3 INT
)
PARTITION BY LIST(`k1`)
(
    PARTITION `p_1` VALUES IN ("1"),
    PARTITION `p_2` VALUES IN ("2"),
    PARTITION `p_3` VALUES IN ("3")
)
DISTRIBUTED BY HASH(k1) BUCKETS 6
PROPERTIES (
    "replication_num" = "1"
);

insert into user_p values(1,1);
insert into user_p values(2,2);

CREATE MATERIALIZED VIEW mv_p BUILD IMMEDIATE REFRESH COMPLETE START WITH "2023-05-16 21:33:00" NEXT 1 MINUTE 
PARTITION BY (k1)
DISTRIBUTED BY HASH(k1) 
BUCKETS 6 
PROPERTIES (
    "replication_num" = "1"
)
as select k1,k3 from user_p; 

image

### What You Expected?

normal

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #20773 

The syntax for supporting partition updates in the future has not been researched yet, and there are issues with partition syntax. Therefore, the partition syntax has been temporarily removed in the current version and will be added after future research

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run feut

**Comment by zddr** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Review by SaintBacchus — COMMENTED** [review]
LGTM

**Review by SaintBacchus — APPROVED** [review]

**Pull request merged**
