### PR TITLE
[case]Load data with load_parallelism=any > 1 and stream load with compress type

### PR DESCRIPTION
**Pull request by Zhiyu-h**
## Proposed changes

Issue Number: close #xxx

## Further comments

Load data with load_parallelism=any > 1 and stream load with compress type

### CODE REVIEW

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
