### PR TITLE
[Fix](Job)Fixed the problem of not deleting JOB during DROP JOB metadata playback

### PR DESCRIPTION
**Pull request by CalvinKirs**
### Description
When we perform the DROP operation, the task is deleted from the memory, but when we restart, the metadata is played back and no remove operation is performed.

## Proposed changes
Keep the STOP state and implement the DROP interface separately. When Dropping, first change the job to the STOP state (some tasks in the queue still hold job object references. When these tasks start to execute, you need to check the job status to determine whether it is needed. execute) and then delete it.

- Fixed the problem of not deleting JOB during DROP JOB metadata playback

- DROP JOB adds IF EXISTS syntax
- Fix unstable UT as it could be affected by the current time

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
Only the method names of some metadata have been modified. No other behavior changes

**Review by morningman — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
