### PR TITLE
[Improvement](inverted index) lazy init inverted index file reader

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

We call InvertedIndexFileReader::init in segment_iterator init_inverted_index_iterators now, which cause searcher cache miss.
So we lazy init when we open specific index.

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Pull request merged**
