### PR TITLE
[enhance](catalog)Allow parallel running of insert overwrite on the external table

### PR DESCRIPTION
**Pull request by zddr**
pre pr: https://github.com/apache/doris/pull/40558

Allow parallel running of insert overwrite on the external table

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
