### PR TITLE
[fix](Nereids) column pruning should prune map in cte consumer

### PR DESCRIPTION
**Pull request by morrySnow**
we save bimap in cte consumer to get the maping between producer and consumer.
the consumer's output is decided by the map in it.
so, cte consumer should be output prunable, and should remove useless entry from map when do column pruning

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run cloud_p1

**Review by 924060929 — APPROVED** [review]

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run cloud_p1

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
