### PR TITLE
[fix](test) fix some tests in external p0 (#36127)

### PR DESCRIPTION
**Pull request by morningman**
Also move the analysis exception of "Not support insert with partition spec in hive catalog."
from create sink phase to bind sink phase.
So that when `set enable_fallback_to_original_planner=false;`, the return error will be correct.

branch-2.1: #36127 #36262 #36284

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run feut

**Review by AshinGau — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
