### PR TITLE
[minor] add disable swap command

### PR DESCRIPTION
**Pull request by xiedeyantu**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiedeyantu** [comment]
@xiaokang Hi, Do we need this pr?

**Comment by xiaokang** [comment]
@xiedeyantu Yes, can you submit a pr for branch-2.0

**Comment by xiaokang** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiedeyantu** [comment]
@xiaokang Hi, do we need to merge to master?

**Comment by xiedeyantu** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request closed without merging**
