### PR TITLE
[fix](csv reader) fix core dump when parsing csv with enclose

### PR DESCRIPTION
**Pull request by sollhui**
### What problem does this PR solve?

Problem Summary:
Core dump when load csv file to Doris:
```
==878493==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fe0fda1c800 at pc 0x559d3db60c48 bp 0x7fde739b2b20 sp 0x7fde739b22d8
READ of size 6 at 0x7fe0fda1c800 thread T545 (_scanner_scan)
    #0 0x559d3db60c47 in memmem (/mnt/disk1/laihui/doris/output/be/lib/doris_be+0x61eefc47) (BuildId: 5f823a8a2b6a81c7)
    #1 0x559d6d02ea60 in unsigned char const* doris::EncloseCsvLineReaderContext::look_for_column_sep_pos<false>(unsigned char const*, unsigned long, char const*, unsigned long) /mnt/disk1/laihui/doris/be/src/vec/exec/format/file_reader/
new_plain_text_line_reader.cpp:111:33
    #2 0x559d6d01f21e in doris::EncloseCsvLineReaderContext::_on_match_enclose(unsigned char const*, unsigned long&) /mnt/disk1/laihui/doris/be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp:177:13
    #3 0x559d6d01c7aa in doris::EncloseCsvLineReaderContext::read_line_impl(unsigned char const*, unsigned long) /mnt/disk1/laihui/doris/be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp:68:13
    #4 0x559d6cf9e616 in doris::BaseTextLineReaderContext<doris::EncloseCsvLineReaderContext>::read_line(unsigned char const*, unsigned long) /mnt/disk1/laihui/doris/be/src/vec/exec/format/file_reader/new_plain_text_line_reader.h:77:41
    #5 0x559d6d0258a3 in doris::NewPlainTextLineReader::read_line(unsigned char const**, unsigned long*, bool*, doris::io::IOContext const*) /mnt/disk1/laihui/doris/be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp:335:48
    #6 0x559d6cf5fc8c in doris::vectorized::CsvReader::get_next_block(doris::vectorized::Block*, unsigned long*, bool*) /mnt/disk1/laihui/doris/be/src/vec/exec/format/csv/csv_reader.cpp:538:13
    #7 0x559d90f388bb in doris::vectorized::VFileScanner::_get_block_wrapped(doris::RuntimeState*, doris::vectorized::Block*, bool*) /mnt/disk1/laihui/doris/be/src/vec/exec/scan/vfile_scanner.cpp:306:13
    #8 0x559d90f37222 in doris::vectorized::VFileScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) /mnt/disk1/laihui/doris/be/src/vec/exec/scan/vfile_scanner.cpp:248:17
```

```
const uint8_t* delim_pos = find_col_sep_func(curr_start, curr_len, _column_sep.c_str(), _column_sep_len);
```
curr_len should len - _idx rather than _column_sep_len.
### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by sollhui** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
