### PR TITLE
[Regresstion](external)open case test_doris_jdbc_catalog

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

open case test_doris_jdbc_catalog

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run p0

**Review by pingchunzhang — APPROVED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Pull request merged**
