### PR TITLE
[fix](restore) Reset next version for remote table when restore

### PR DESCRIPTION
**Pull request by smallx**
We should reset next version to visible version + 1 for all partitions of remote table, when restoring table that do not exist locally.

在高并发insert场景，CCR源端表的next version可能比visible version大比较多，目标集群restore全量快照后，切换到增量binlog后，commit事务时使用的version（来自next version）就可能比当前visible version大比较多。

此时，对于MoW表，就会出现publish version不连续，增量binlog一直无法publish的问题。事务状态会一直是`COMMITTED`，并伴随类似ErrMsg `wait for publishing partition 15027 version 1037597. self version: 1037627. table 15025`。

### CODE REVIEW

**Comment by smallx** [comment]
@w41ter please help to review, thank you.

**Review by w41ter — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
