### PR TITLE
[Chore](vectorized) remove all isVectorized

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes

isVectorized is always true now

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
@yiguolei  @Gabriel39  p0 is passed, please take a look again

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
