### PR TITLE
[fix](test)Fix index_compaction unstable cases

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run pipelinex_p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run  p0

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
