### PR TITLE
[Bug](Func) Fix negative number in bitmap return error result

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by zxealous** [comment]
cherry-pick #31563 to branch 2.0

**Review by zxealous — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
#31563

**Pull request merged**
