### PR TITLE
[Fix](Planner) fix cast from decimal to boolean

### LINKED ISSUE #17700: [Bug] Cannot use `between and` in boolean column and doris throws Unexpected exception
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Apache Doris 1.2.2 RELEASE

### What's Wrong?

I'm trying to add Apache Doris support to SQLancer, this may be a bug found by @[SQLancer](https://github.com/sqlancer/sqlancer).

1. CREATE DATABASE and INSERT VALUES
`CREATE TABLE t0(c0 BOOLEAN NOT NULL) DUPLICATE KEY(c0) DISTRIBUTED BY HASH (c0) PROPERTIES ("replication_num" = "1");`
image

2. `select (t0.c0 BETWEEN 0.44 AND 1) from t0;` 
Execute this SQL, then Doris throws Unexpected exception
image

### What You Expected?

Maybe it should be like the following, where boolean is used as 1 or 0 in `between and`.

image

If the boolean columns not support`between and` , an SQL syntax error should be given instead of an exception

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
# Proposed changes

Issue Number: close #17700

## Problem summary

change Planner doing rewrite select list expression, which wants to cast decimal to boolean. Disable this cast and it work normally.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
Please add a regression case.

**Comment by LiBinfeng-01** [comment]
> Please add a regression case.

no problem

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
> Please add a regression case.

done

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.88 seconds
 stream load tsv:          433 seconds loaded 74807831229 Bytes, about 164 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          60 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230512102157_clickbench_pr_142843.html

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
