### PR TITLE
[fix](cloud-schema-change) Exclude merged dropped columns from projection columns

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

schema change in cloud mode used to merge dropped columns from delete predicates to projection columns when reading data from base tablet, resulted in failure when reading rowsets after columns dropped.

### CODE REVIEW

**Review by gavinchou — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run performance

**Comment by TangSiyang2001** [comment]
run buildall

**Review by luwei16 — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
