### PR TITLE
[fix](index compaction) fix fd leak and mem leak while index compaction (#41915)

### PR DESCRIPTION
**Pull request by cambyzju**
pick #41915 to branch-2.1

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run P0 Regression

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
