### PR TITLE
[fix](spill) fix memory orphan check failure of partitioned hash join

### PR DESCRIPTION
**Pull request by jacktengg**
Also add fault injection regression test cases for spill.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run cloud_p1

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
