### PR TITLE
[Bug](function) fix rpad function return error result

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

have test buffer with reserve and resize function
fmt::memory_buffer is dynamic contains not the standard contains in STL
it's should call resize function to get more memory,
specially when realloc and grow more memory

Snipaste_2024-09-27_14-52-48

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
