### PR TITLE
[test](external)move hive cases from p2 to p0

### PR DESCRIPTION
**Pull request by zy-kkk**
test_hive_same_db_table_name
test_hive_special_char_partition
test_complex_types
test_wide_table

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
