### PR TITLE
[fix](move-memtable) fix potential duplicate of TabletStream profile

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Profile is created in `TabletStream` constructor.
If something goes wrong in `init`, tablet_stream is not added into the map.
Causing potential duplicate of TabletStream profile.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
