### PR TITLE
upgrade thirdparty libs

### LINKED ISSUE #6706: [Feature] Upgrade thirdparty version
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Some third-party library versions have not been updated for a long time, and there are performance and functional issues.
 * arrow 0.15 version has serious performance problems [ARROW-7059](https://issues.apache.org/jira/browse/ARROW-7059)
 * thrift 0.9  will cause parquet export bool type incorrectly
 * after upgrade thrift we could remove some boost with stl

So I will update
 * arrow 0.15 ->5.0
 * thrift 0.9->0.13
 * others accroding to [arrow dependencies](https://github.com/apache/arrow/blob/apache-arrow-5.0.0/cpp/thirdparty/versions.txt)

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yangzhg**
- libevent -> 2.1.12
- OpenSSL 1.0.2k -> 1.1.1l
- thrift 0.9.3 -> 0.13.0
- protobuf 3.5.1 -> 3.14.0
- gflags 2.2.0 -> 2.2.2
- glog 0.3.3 -> 0.4.0
- googletest 1.8.0 -> 1.10.0
- snappy 1.1.7 -> 1.1.8
- gperftools 2.7 -> 2.9.1
- lz4 1.7.5 -> 1.9.3
- curl 7.54.1 -> 7.79.0
- re2 2017-05-01 -> 2021-02-02
- zstd 1.3.7 -> 1.5.0
- brotli 1.0.7 -> 1.0.9
- flatbuffers 1.10.0 -> 2.0.0
- apache-arrow 0.15.1 -> 5.0.0
- CRoaring 0.2.60 -> 0.3.4
- orc 1.5.8 -> 1.6.6
- libdivide 4.0.0 -> 5.0
- brpc 0.97 -> 1.0.0-rc02
- librdkafka 1.7.0 -> 1.8.0

after this pr compile doris should use build-env:1.4.0

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [x] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6706) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yangzhg** [comment]
this pr has been passed local test http://ci.palo.com:8111/buildConfiguration/IncubatorDoris_LocalTest/19751

**Review by morningman — COMMENTED** [review]
Please also upgrade librdkafka to 1.7.0 to fix the bug describe in 
https://github.com/edenhill/librdkafka/issues/3295

**Comment by yangzhg** [comment]
> Please also upgrade librdkafka to 1.7.0 to fix the bug describe in [edenhill/librdkafka#3295](https://github.com/edenhill/librdkafka/issues/3295)

DONE

**Review by morningman — APPROVED** [review]
LGTM

**Comment by tinkerrrr** [comment]
@morningman After this pr, can Doris 0.15  be compatible with previous version like 0.14? Since so many thirdparty libs are upgraded...

**Pull request merged**
