### PR TITLE
[Improvement](join) support single column nullable join hash table context

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
support single column nullable join hash table context
QQ_1729828619996

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by Gabriel39 — DISMISSED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
