### PR TITLE
[fix](compile)compile failed after merge #11117 #10479 and #11162

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

#11117 and #10479 changed interface. #11162 use old interface. All of them passed all checked.
But after merged all of them, compile failed.

## Checklist(Required)

1. Type of your changes:
    - [ ] Improvement
    - [x] Fix
    - [ ] Feature-WIP
    - [ ] Feature
    - [ ] Doc
    - [ ] Refator
    - [ ] Others: 
2. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
I will merge this pr as fast as possible because master build fail now.

**Pull request merged**
