### PR TITLE
[improvement](functions) avoid copying of block in create_block_with_nested_columns

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

The performance cost of copying blocks is not negligible, so unnecessary copying should be avoided.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run p1

**Comment by mrhhsg** [comment]
run p0

**Comment by mrhhsg** [comment]
run buildp0

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
