### PR TITLE
[enhancement](delete-handler) split Deletehandler#commitJob and add preconditions to intercept NPE

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feet

**Comment by TangSiyang2001** [comment]
run p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run p1

**Pull request merged**
