### PR TITLE
[Optimize](functions)Optimize function call for const columns.

### PR DESCRIPTION
**Pull request by zclllyybb**
# Problem summary

Introduced new methods to avoid expanding const column in some functions.

## Performance Improvement
before:
```
mysql [tpch]>Select substring(c_name, 5, 10), substring(c_address, 10, 15), substring(c_comment, 50, 75) from customer;
......
15000000 rows in set (18.30 sec)
```
after:
```
mysql [tpch]>Select substring(c_name, 5, 10), substring(c_address, 10, 15), substring(c_comment, 50, 75) from customer;
......
15000000 rows in set (15.92 sec)
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
Good code! LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
