### PR TITLE
[deps](brpc) Upgrade Brpc to 1.2.0 fix `_dl_sym undefined reference` on new verison of glibc

### PR DESCRIPTION
**Pull request by yangzhg**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Upgrade Brpc to 1.2.0 fix `_dl_sym undefined reference` on new verison of glibc
patch `patches/brpc-1.1.0.patch` and `patches/brpc-1.1.0-_dl_sym.patch` alread contiained in brpc 1.2.0 release
We use the 1.2 version directly is better

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x]No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [x] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
greate

**Comment by hello-stephen** [comment]
hi,
In the prior pr about _dl_sym problem, I tested update brpc to 1.2.0, but compiled failed, the error info looks like brpc-1.2.0 rely on a newer version of glog, I am not very sure about it, anyway not work.
maybe need further work on it?

**Comment by jacktengg** [comment]
Build thirdparty failed:
```
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:170: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:173: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:177: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:180: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:183: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/logging.cc:186: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/mnt/disk/tengjianping/doris-test/thirdparty/installed/lib/libglog.a(libglog_la-vlog_is_on.o): In function `__static_initialization_and_destruction_0':
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/vlog_is_on.cc:52: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/vlog_is_on.cc:55: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/mnt/disk/tengjianping/doris-test/thirdparty/installed/lib/libglog.a(libglog_la-utilities.o): In function `__static_initialization_and_destruction_0':
/mnt/disk/tengjianping/doris-test/thirdparty/src/glog-0.4.0/src/utilities.cc:75: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
collect2: error: ld returned 1 exit status
[333/334] Building CXX object tools/rpc_view/CMakeFiles/rpc_view.dir/rpc_view.cpp.o
ninja: build stopped: subcommand failed.
```

**Pull request merged**
