### PR TITLE
[fix](restore) Reset the db name of the materialized index stmt

### PR DESCRIPTION
**Pull request by w41ter**

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by swjtu-zhanglei — APPROVED** [review]
LGTM

**Pull request merged**
