### PR TITLE
[fix](cloud) Fix missing table ids in TxnRunningPB

### PR DESCRIPTION
**Pull request by platoneko**
## Proposed changes

Fix missing table ids in `TxnRunningPB` in `MetaServiceImpl::precommit_txn`.
The table ids in `TxnRunningPB` will be used to check for running doris transactions. If they are missing, it will cause `check_conflict_txn` to assume that transactions below the watermark have already completed. Then, result in a gap between the alter version obtained by the schema change job (which is used to decide the version range of history data to convert) and the version committed by new doris transcations during schema change job.

### CODE REVIEW

**Review by w41ter — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
