### PR TITLE
[fix](ui): 1. fix component/table can not change pageSize

### PR DESCRIPTION
**Pull request by htyoung**
fix(ui): 1. fix component/table can not change pageSize,affect system/query profile/session page etc.
2. add antd Table Component missing rowKey property to fit react specification
2. fix system/query profile/session/configuration page maybe lead memory leak when switch these pages fast
3.other grammar fix to fit typescript and react specification

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ - ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ - ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ - ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ - ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ - ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by htyoung** [comment]
image

**Comment by htyoung** [comment]
> 

it mainly fix the pageSize can't be changed

**Review by jeffreys-cat — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
