### PR TITLE
[enhance](mtmv)Prohibit creating materialized views in external catalogs

### PR DESCRIPTION
**Pull request by zddr**
Prohibit creating materialized views in external catalogs

### CODE REVIEW

**Comment by feifeifeimoon** [comment]
run beut

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
