### PR TITLE
[pick](nestedtype)support nested type with agg replace_if_not_null

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
backport: https://github.com/apache/doris/pull/38304
Issue Number: close #xxx

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p0

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Pull request merged**
