### PR TITLE
[cases](nested-types)run master cases for nested types

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
this pr wanna to check nested types behavior is same with master
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by hello-stephen** [comment]
run p0

**Comment by hello-stephen** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Pull request closed without merging**
