### PR TITLE
[Feature](iceberg-writer) Implements iceberg sink basic functionality for inserting into table.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

#31442

[Feature] (iceberg-writer) Implements iceberg sink basic functionality for inserting into table. 

Currently only insert into and CTAS are supported. Among them, insert into supports unpartitioned tables and partitioned tables, but partitioned tables only support identity transform partitioned tables.

### Future work:
- Complete partitioned table transform functionality.
- Sorting function.
- Insert overwrite function.
- More features like update, delete and merge.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run compile

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
