### PR TITLE
[feature](workloadgroup)Add workload condition query used memory

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
Add workload condition query used memory, we can kill queries based on memory usage.

1  create a policy which can kill query used memory exceeds 100M.
```
create workload policy memory_used_policy conditions(query_be_memory_bytes > 104857600) actions(cancel_query);
```

2 submit a query.
```
mysql [hits]>insert into hits2 select * from hits;
ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[INTERNAL_ERROR]query 81c39e2b3ecf461c-bc78ad6d9b6173d2 cancelled by workload policy memory_used_policy, id:29028
```

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Comment by yiguolei** [comment]
the metric name should be consistent with other metrics in be, for example:
be_scan_rows，The number of rows scanned by an SQL within a single BE process, and if there are multiple concurrency, it is the cumulative value of multiple concurrency.
be_scan_bytes，The number of bytes scanned by an SQL within a single BE process, and if there are multiple concurrency, it is the cumulative value of multiple concurrency.
query_time，The running time of an SQL on a single BE process, measured in milliseconds.

So that I think the name should be be_memory_used_bytes,

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
