### PR TITLE
[regression-test](feature) add skip non-concurrent test functions

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by shuke987** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Comment by hello-stephen** [comment]
skip buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
