### PR TITLE
[performance](move-memtable) enable stream write to socket in background bthread

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Enable stream write to socket in background bthread, which can approximately a few percent contributes to load performance.

Testing 100G insert into B select * from A: **8 min 0.893 sec -> 7 min 49.969 sec**

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
