### PR TITLE
[bug](metrics) fix be metric doris_be_process_thread_num is zero

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

Issue Number: close #xxx

introdued by #26013

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caiconghui — APPROVED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Review by GoGoWen — APPROVED** [review]
LGTM

**Comment by DarvenDuan** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run beut

**Review by GoGoWen — APPROVED** [review]
LGTM

**Review by GoGoWen — APPROVED** [review]
LGTM

**Pull request merged**
