### PR TITLE
[fix](clone) Fix engine_clone file exist

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Fix engine_clone file exist

* not use RETURN_IF_ERROR directly, because defer(!status.ok()) remove linked files
* if to binlog exist, compare md5sum

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Comment by JackDrogon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
