### PR TITLE
[regression-test](parquet) add some parquet cases with tvf

### PR DESCRIPTION
**Pull request by suxiaogang223**
Add some parquet file as tvf case

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run external

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Review by zgxme — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
