### PR TITLE
[fix](create table) Add hit err msg when create table all be on same …

### PR DESCRIPTION
**Pull request by deardeng**
…host

## Proposed changes

Issue Number: close #xxx

当所有be都部署在同一个机器上，而allow_replica_on_same_host=false（默认）时候，建表报错提示不明显，增加提示信息

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by Yukang-Lian** [comment]
run cloud_p1

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
