### PR TITLE
[doc](catalog) update and improve doc of multi catalog

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Update the document of multi catalog feature.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
LGTM

**Review by AshinGau — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by wsjz** [comment]
LGTM

**Review by wsjz — APPROVED** [review]
LGTM

**Review by wsjz — APPROVED** [review]

**Review by wsjz — APPROVED** [review]

**Pull request merged**
