### PR TITLE
[docker](hive) sync for hive initializing

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes

Add healthy checking for hive2 and hive3

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
