### PR TITLE
[doc](fix) Improve the document example of alter table replace

### PR DESCRIPTION
**Pull request by catpineapple**
## Proposed changes

Issue Number: close #xxx

Improve the document example of alter table replace
The old doc example was wrong

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by catpineapple** [comment]
run buildall

**Comment by catpineapple** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by catpineapple** [comment]
run buildall

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
