### PR TITLE
[opt](catalog) cache the converted properties

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

convert properties may be a heavy operation, so we cache the result.

```
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:480)
        - waiting to lock <0x00000005e99cca00> (a sun.misc.URLClassPath)
        at sun.misc.URLClassPath.findResource(URLClassPath.java:225)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:577)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:575)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findResource(URLClassLoader.java:574)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1089)
        at org.apache.hadoop.conf.Configuration.getResource(Configuration.java:2839)
        at org.apache.hadoop.conf.Configuration.getStreamReader(Configuration.java:3113)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3072)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3045)
        at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2923)
        - locked <0x000000065cfe78a8> (a org.apache.hadoop.hive.conf.HiveConf)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2905)
        - locked <0x000000065cfe78a8> (a org.apache.hadoop.hive.conf.HiveConf)
        at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2968)
        at org.apache.hadoop.hive.conf.HiveConf.getProperties(HiveConf.java:5134)
        at org.apache.hadoop.hive.conf.HiveConf.getAllProperties(HiveConf.java:5130)
        at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5147)
        at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5102)
        at org.apache.doris.datasource.property.PropertyConverter.getPropertiesFromDLFConf(PropertyConverter.java:377)
        at org.apache.doris.datasource.property.PropertyConverter.convertToDLFProperties(PropertyConverter.java:365)
        at org.apache.doris.datasource.property.PropertyConverter.convertToMetaProperties(PropertyConverter.java:89)
        at org.apache.doris.datasource.ExternalCatalog.getProperties(ExternalCatalog.java:407)
        at org.apache.doris.datasource.hive.HiveMetaStoreCache.getFileCache(HiveMetaStoreCache.java:378)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
