### PR TITLE
[enhancement](threadname) change thread name, whose length is restricted to 15 characters on linux platform

### LINKED ISSUE #32321: [Enhancement] task worker pool name should be distinguished in top -H
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When a be is running, we can distinguish the thread name of taskworkerpool. The default name is too long.

be/src/agent/task_worker_pool.cpp

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caizj**
The distinguished thread name can be useful for debugging

## Proposed changes
This is the summary of pstack thread name output:
WechatIMG238
WechatIMG239

WP stands for WorkThreadPool, implemented in work_thread_pool.hpp
TP stands for ThreadPool, implemented in threadpool.h
BTS stands for BlockedTaskScheduler, implemented in task_scheduler.h

Issue Number: close #32321

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run builddall

**Comment by caizj** [comment]
run builddall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by caizj** [comment]
run external

**Comment by caizj** [comment]
run p0

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run p0

**Comment by caizj** [comment]
run p0

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run p0

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Pull request closed without merging**
