### PR TITLE
[fix](auto-partition) Fix auto partition load failure in multi replica

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

One sender may incremental_open `tablets_channel` many times. but only close one time. so don't count num_senders duplicated for one sender instance.

### CODE REVIEW

**Comment by zclllyybb** [comment]
run compile

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
test in https://github.com/apache/doris/pull/36353 with memtable on sink node off.
the result of 4BE will release soon.

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
