### PR TITLE
[Bug](materialized-view)  fix some bugs on create mv with percentile_approx 

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1. percentile_approx have wrong symbol
2. fnCall.getParams() get obsolete childrens

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
