### PR TITLE
[improvement](doris compose) make lock file all users can read and write

### PR DESCRIPTION
**Pull request by yujun777**
Fix other user create cluster fail because no permission to the lock file.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run cloud_p0

**Comment by yujun777** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
