### PR TITLE
[fix](docker) Add docker ignore files and change docker default sourc…

### PR DESCRIPTION
**Pull request by deardeng**
…e to ali

## Proposed changes

1. Prevent consuming a large amount of disk capacity when build docker image
2. Accelerate domestic machine download docker dependency

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
