### PR TITLE
[Chore](build) add -Wconversion and remove some unused code

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
add -Wconversion and remove some unused code
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Comment by AcKing-Sam** [comment]
@BiteTheDDDDt  
Hi, when I compiled the BE using command `./build.sh --be`, there's an error:
```shell
doris/be/src/util/mem_info.cpp:517:38: 
error: implicit conversion turns floating-point number into integer: 'double' to 'int64_t' (aka 'long long') [-Werror,-Wfloat-conversion]
    _s_soft_mem_limit = _s_mem_limit * config::soft_mem_limit_frac;
                      ~ ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
And I noticed that the related code has been changed here. Could you please give me some hints? Thanks a lot!

**Pull request merged**
