### PR TITLE
[docs](fix) Update docs sidebar of 2.0 Version

### PR DESCRIPTION
**Pull request by KassieZ**
## Proposed changes

https://ask.selectdb.com/questions/D1r2/doris-docs-chu-xian-le-zhong-fu-de-sql-mode-biao-ti

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KassieZ** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run buildall

**Pull request merged**
