### PR TITLE
[opt](nereids) add project under aggregate to enable extract common sub expression

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
project aggregate function parameters, and then apply common_sub_expression opt by CommonSubExpressionOpt post processor.
example:
agg( sum(A+B), avg(A+B))
   +--->Scan(T)
=>
agg(sum(x) , avg(x))
   +---> project (A+B as x)
               +--->Scan(T)

tpcds  64 changed
TPCDS 1T， 3BE
before： 6050 ms
after： 6075 ms

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run cloud_p0

**Comment by englefly** [comment]
run cloud_p0

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
