### PR TITLE
[Improve](complex-type)improve array/map/struct creating and function with decimalv3

### PR DESCRIPTION
**Pull request by amorynan**
# Proposed changes

improve array/map/struct creating with decimalv3 and array/struct function with decimalv3

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p1

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
