### PR TITLE
[fix](thirdparty) change boost thirdparty url to offical archives.boost.io

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

Issue Number: close #xxx

The old url https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz is sometimes not available.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
master pr: #29401

**Comment by adonis0147** [comment]
Hi @xiaokang , it seems that the URL is available.

**Comment by xiaokang** [comment]
> Hi @xiaokang , it seems that the URL is available.

It's really strange. I tried it now and it works, but it does not work this morning. Maybe the official url is more stable.

Mzg69VqkH3

**Review by adonis0147 — APPROVED** [review]

**Comment by xiaokang** [comment]
#29401

**Pull request merged**
