### PR TITLE
[chore] Fix memory problems in agg_test.cpp.

### LINKED ISSUE #8018: [Bug] Memory problems in agg_test.cpp.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

There are two memory problems in `agg_test.cpp`.

1. mismatched-new-delete
2. memory leak

### What You Expected?

Fix those memory problems.

### How to Reproduce?

Compile and run agg_test.cpp.

`./run-be-ut.sh --run agg_test`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #8018 .

## Problem Summary:

Please refer to #8018 .

## Checklist(Required)

1. Does it affect the original behavior: No.
2. Has unit tests been added: No Need.
3. Has document been added or modified: No Need.
4. Does it need to update dependencies: No.
5. Are there any changes that cannot be rolled back: No.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
A simpler solution is just add delete at end of function.
```cpp
    if (place != nullptr) {
        delete[] place;
    }
```

**Comment by adonis0147** [comment]
@BiteTheDDDDt Yes, but I want to follow the principle of RAII in modern C++ to avoid call `delete` explicitly.
I will use another simple way to do it.

**Comment by BiteTheDDDDt** [comment]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
hi @adonis0147 , please rebase the master to resolve the conflict

**Comment by adonis0147** [comment]
@morningman I have rebased the master branch.

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
