### PR TITLE
[doc](optimizer) Rewrite docs of statistics according to the current master

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

1. Remove verbsoe sample, stale grammar, deleted function
2. And add some use advices

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
update english doc

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
> update english doc

done

**Review by englefly — DISMISSED** [review]

**Comment by Kikyou1997** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
