### PR TITLE
[fix](meta)Fix  error code for unknown table #27751

### LINKED ISSUE #27751: [Feature] Adding error code for unknown table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

In mysql, code 1146, 1049, 1051 represent  `Table '%s.%s' doesn't exist`, `Unknown database '%s'` and `Message: Unknown table '%s'` respectively. But I cannot find relevent error code in [error table](https://github.com/apache/doris/blob/master/docs/en/docs/admin-manual/maint-monitor/doris-error-code.md). Perhaps adding these error code will improve the user experience.

### Use case

Run
```sql
DESCRIBE test_table -- non-existent table
```
current
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```
expectation
```
ERROR <specialized error code> (HY000): errCode = 2, detailMessage = Unknown table 'test_table'
```

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
This fix will improve the error code for unknown table
exception cases.

## Proposed changes

Issue Number: close #27751

Unknown table exception always return 1105 Other errors.
After code analysis Doris already has a error code 1051 and 1109 for unknown table exceptions.
Change according for all table related sql commands.

Only drop command is returning 1109 which is current code behaviour.
without this fix drop command also return 1105 Other errors.
I looked up 1109 error code also suitable if message has unknown table table_name in schema/db.
This fix need docs changes will raise another PR for it.
## Further comments
image

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run build all

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Pull request merged**
