### PR TITLE
[fix](memory) no switch bthread context in UBSAN compile

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Issue Number: close #xxx

When UBSAN is compiled, all memory will be tracked to the orphan (unknown) mem tracker, and the bthread context and mem tracker will no longer be switched. 

The supplementary fixes are as follows: #20999

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Pull request merged**
