### PR TITLE
[fix](txn insert) Fix txn insert commit failed when schema change

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

session1:
```
  1. begin a transaction insert
  2. do some inserts
```

session2:
```
  3. do schema change
```

session1:
```
  4. do some inserts
  5. commit
```

when commit, we get:
```
[ANALYSIS_ERROR]TStatus: errCode = 2, detailMessage = Failed to commit txn 3, cause tablet 10106 succ replica num 0 < load required replica num 1. table 10099, partition: [ id=10098, commit version 2, visible version 2 ], this tablet detail: 1 replicas write data failed: { [replicaId=10107, backendId=10002, backendAlive=true, version=1, state=ALTER] }; 

        0#  doris::Status doris::Status::Error<true>(int, std::basic_string_view<char, std::char_traits<char> >) at /mnt/disk2/meiyi/clion_workspace/doris_master2/be/src/common/status.h:401
        1#  doris::Status doris::Status::create<true>(doris::TStatus const&) at /mnt/disk2/meiyi/clion_workspace/doris_master2/be/src/common/status.h:357
        2#  doris::StreamLoadExecutor::commit_txn(doris::StreamLoadContext*) at /mnt/disk2/meiyi/clion_workspace/doris_master2/be/src/runtime/stream_load/stream_load_executor.cpp:347
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run external

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
