### PR TITLE
[improvement](regression) add custom_env.sh from regression pipeline

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

This file will be used when compiling Doris in regression pipeline.
And we can modify it to control the compile behavior.

I add `BUILD_FS_BENCHMARK=ON`, so that it will build fs_benchmark_tool.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by shuke987 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
