### PR TITLE
[enhancement](util) print if using nereids planner when be coredump #31981

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

pick https://github.com/apache/doris/pull/31752
pick https://github.com/apache/doris/pull/31981

```
*** Query id: 77433c763b14535-be989f185c71e240 ***
*** is nereids: 0 ***
*** tablet id: 0 ***
*** Aborted at 1728464190 (unix time) try "date -d @1728464190" if you are using GNU date ***
*** Current BE git commitID: eaaf726019 ***
*** SIGABRT unknown detail explain (@0x47000060661) received by PID 394849 (TID 395426 OR 0x7ff4a5f36700) from PID 394849; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/yanxuecheng/branch-2.0/doris/be/src/common/signal_handler.h:421
 1# 0x00007FF6CED47B50 in /lib64/libc.so.6
 2# gsignal in /lib64/libc.so.6



*** Query id: 1b3633126e640e0-b1f06a5bb6c0b1cc ***
*** is nereids: 1 ***
*** tablet id: 0 ***
*** Aborted at 1728464469 (unix time) try "date -d @1728464469" if you are using GNU date ***
*** Current BE git commitID: eaaf726019 ***
*** SIGABRT unknown detail explain (@0x4700006f5b8) received by PID 456120 (TID 456600 OR 0x7f72da8df700) from PID 456120; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/yanxuecheng/branch-2.0/doris/be/src/common/signal_handler.h:421
 1# 0x00007F745021BB50 in /lib64/libc.so.6
```

Issue Number: close #xxx

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
