### PR TITLE
[typo](docs)Delete unsupported sql statements in GROUP_CONCAT()

### PR DESCRIPTION
**Pull request by echo-hhj**
## Proposed changes

I deleted the case in GROUP_CONCAT () and modified the corresponding English and Chinese documents

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
why remove it? It is supported, are you having any issues？

**Comment by guardcrystal** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        There is already another email account that is receiving doris emails.
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1968749040
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        07/3/2023 19:02
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Huang ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [apache/doris] [typo](docs)Delete unsupported sql statements in GROUP_CONCAT() (PR #21455)
        
      
    
  
  
why remove it? It is supported, are you having any issues？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by guardcrystal** [comment]
> why remove it? It is supported, are you having any issues？

Sorry for the reply error, test this sql execution failed in 126rc version

**Comment by guardcrystal** [comment]
> why remove it? It is supported, are you having any issues？

截屏2023-07-03 16 19 59

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM, this support removed on #17237

**Review by zy-kkk — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
