### PR TITLE
[refactor](type) change some type inheritance relationship and remove useless interface

### PR DESCRIPTION
**Pull request by morrySnow**
1. let AggStateType extends Type
2. remove useless interface isFixedLengthType and supportsTablePartitioning
3. let MapType implement interface isSupported
4. let VariantType extends ScalarType

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by eldenmoon — DISMISSED** [review]
LGTM

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
