### PR TITLE
[opt](arena) lazy memory allocation in arena

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Arena should not allocate memory in this constructor.

After this pr merged, we shuold revert https://github.com/apache/doris/pull/36299

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run external

**Review by jacktengg — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
revert related: https://github.com/apache/doris/pull/36979

**Pull request merged**
