### PR TITLE
[Fix](RoutineLoad)Query the transaction status NPE when the task has not yet started scheduling

### PR DESCRIPTION
**Pull request by CalvinKirs**
### error log

When the task has not yet started scheduling, there is no transaction status at this time. Therefore the query will cause an NPE exception
```
show routine load task where JobName="npe"
```
```
2023-10-07 13:52:16,883 WARN (mysql-nio-pool-3|1310) [StmtExecutor.executeByLegacy():807] execute Exception. stmt[1368, fc075cfd62aa4459-a8014ca6b5f574fa]
java.lang.NullPointerException: null
	at org.apache.doris.load.routineload.RoutineLoadJob.lambda$getTasksShowInfo$6(RoutineLoadJob.java:1452) ~[classes/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_362]
	at org.apache.doris.load.routineload.RoutineLoadJob.getTasksShowInfo(RoutineLoadJob.java:1450) ~[classes/:?]
	at org.apache.doris.qe.ShowExecutor.handleShowRoutineLoadTask(ShowExecutor.java:1605) ~[classes/:?]
	at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:316) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:2208) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:775) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:468) ~[classes/:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:438) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:353) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:501) ~[classes/:?]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:752) ~[classes/:?]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]

```
### Changes
When the task has not yet started scheduling, that is, when txn_id is -1, the transaction status is set to null

### Test

image

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
Run P0

**Comment by CalvinKirs** [comment]
run p0

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
