### PR TITLE
[feature](cmd) add UNSET_VARIABLE statement to  set back variables

### LINKED ISSUE #20643: [Enhancement] set back all session variables to default value
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

we will set some global variables for test or sometimes
after test, we want to recovery all variables to default value
but it is not easy to do this, because we should check all variables manually

### Solution

provide new statement
```
UNSET [SESSION] VARIABLE ${variable_name};
UNSET [SESSION] VARIABLE ALL;
```
to set variable to default value.

forthemore, we could reorder weather a variable is default value. If it does,
we could update it to new default value when the default value changed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Implement issue Number: close #20643
furthermore, implement global scope.
```sql
UNSET [SESSION|GLOBAL] VARIABLE ${variable_name};
UNSET [SESSION|GLOBAL] VARIABLE ALL;
```

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Review by nextdreamblue — APPROVED** [review]

**Comment by nextdreamblue** [comment]
LGTM

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Pull request merged**
