### PR TITLE
[refactor](functioncontext) remove duplicate type definition in function context

### PR DESCRIPTION
**Pull request by yiguolei**
# Proposed changes
1. remove duplicate type definition in function context
2. remove unused method in function context
3. not need stale state in vexpr context because vexpr is stateless and function context saves state and they are cloned.
4. remove useless slot_size in all tuple or slot descriptor.
5. remove doris_udf namespace, it is useless.
6. remove some unused macro definitions.
7. init v_conjuncts in vscanner, not need write the same code in every scanner.
8. using unique ptr to manage function context since it could only belong to a single expr context.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
./run buildall

**Comment by yiguolei** [comment]
./run buildall

**Comment by yiguolei** [comment]
./run p0

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.82 seconds
 stream load tsv:          473 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          75 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230305110734_clickbench_pr_108736.html

**Comment by yiguolei** [comment]
./run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
