### PR TITLE
[fix](mtmv)ignore MTMV when backup and restore

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

This is a temporary solution. In order to avoid affecting the existing backup function, the backup MTMV will be allowed after detailed design

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
Please update doc of ba

**Comment by zddr** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zddr** [comment]
run cloud_p1

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
