### PR TITLE
[branch-2.1](memory) Pick query memory tracker value is equal to 0 and exception handle

### PR DESCRIPTION
**Pull request by xinyiZzz**
pick
https://github.com/apache/doris/pull/39536
https://github.com/apache/doris/pull/39913
https://github.com/apache/doris/pull/39964
https://github.com/apache/doris/pull/40020
https://github.com/apache/doris/pull/38960
https://github.com/apache/doris/pull/40092

#33396
#33933
#34901
#33841
#35014
#39908
#40043
#28002
#40016
#40439

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Pull request closed without merging**
