### PR TITLE
(#4564)fix ssd config usage bug

### LINKED ISSUE #4564: [BUG] SSD config format BUG
**Describe the bug**
Be's comment indicates there is two ways to config a SSD disk
format 1:   /home/disk1/palo.HDD,50
format 2:   /home/disk1/palo,medium:ssd,capacity:50

But When I config ssd using format 1,error happends
```
W0909 14:02:46.196918 197741 options.cpp:65] path can not be canonicalized. may be not exist. path=/data13/olap.SSD
W0909 14:02:46.197008 197741 options.cpp:142] failed to parse store path /data13/olap.SSD,2048, res=-203
```
It's obviously that the ```storage medium suffix```  can't be regard as a real path.

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

Fix #4564

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by morningman** [comment]
Hi @wangbo , I can not reproduce this bug in my env. What is the Doris version you used?

**Comment by wangbo** [comment]
@morningman 
I reproduce this using the latest master code;
commit:065b97
be.conf:  storage_root_path = /data1/olap/doris/storage.HDD,50
 ```/data1/olap/doris/storage``` is the real path exists.

And the error log print as below:
```
W0919 14:20:09.434904 31844 options.cpp:65] path can not be canonicalized. may be not exist. path=/data1/olap/doris/storage.HDD
W0919 14:20:09.434979 31844 options.cpp:142] failed to parse store path /data1/olap/doris/storage.HDD,50, res=-203
W0919 14:20:09.434986 31844 options.cpp:147] fail to parse storage_root_path config. value=[/data1/olap/doris/storage.HDD,50]
F0919 14:20:09.434994 31844 doris_main.cpp:143] parse config storage path failed, path=/data1/olap/doris/storage.HDD,50

```

**Comment by morningman** [comment]
> @morningman
> I reproduce this using the latest master code;
> commit:065b97
> be.conf: storage_root_path = /data1/olap/doris/storage.HDD,50
> `/data1/olap/doris/storage` is the real path exists.
> 
> And the error log print as below:
> 
> ```
> W0919 14:20:09.434904 31844 options.cpp:65] path can not be canonicalized. may be not exist. path=/data1/olap/doris/storage.HDD
> W0919 14:20:09.434979 31844 options.cpp:142] failed to parse store path /data1/olap/doris/storage.HDD,50, res=-203
> W0919 14:20:09.434986 31844 options.cpp:147] fail to parse storage_root_path config. value=[/data1/olap/doris/storage.HDD,50]
> F0919 14:20:09.434994 31844 doris_main.cpp:143] parse config storage path failed, path=/data1/olap/doris/storage.HDD,50
> ```

Do we support this?
If the storage path in conf is `/data1/olap/doris/storage.HDD,50`, the real dir must be `storage.HDD`, not `storage`.

**Comment by wangbo** [comment]
@morningman 
>>If the storage path in conf is /data1/olap/doris/storage.HDD,50, the real dir must be storage.HDD, not storage.
I configurate be.conf as you said and it works.
I misunderstand it.

**Pull request closed without merging**
