### PR TITLE
Support hive external table on Ali oss.

### PR DESCRIPTION
**Pull request by Jibing-Li**
# Proposed changes

Provide support for hive external table on Ali oss. Create table:
```
CREATE TABLE `test` (   `k1` integer NOT NULL,   `k2` integer NOT NULL,   `k3` integer ) 
engine=hive properties 
("database"="default", 
"table"="test2", 
"hive.metastore.uris"="thrift://host:port"
"AWS_ACCESS_KEY" = "YOUR_ALI_ACCESS_KEY",
"AWS_SECRET_KEY" = "YOUR_ALI_SECRET_KEY",
"AWS_ENDPOINT" = "YOUR_ALI_ENDPOINT",
"AWS_REGION" = "YOUR_ALI_REGION");
```
select result:
```
MySQL [test]> select * from test;
+------+------+------+
| k1   | k2   | k3   |
+------+------+------+
|    1 |    2 |    3 |
+------+------+------+
1 row in set (0.55 sec)
```

## Problem summary
Fe doesn't support hive external table on oss. While querying for this kind of tables, we get
```Not supported storage type: oss```

## Checklist(Required)

1. Does it affect the original behavior: No
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:No need
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified: No need
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies: No
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back: No
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by 1018ji** [comment]
oss 不是支持 s3 协议，不可以直接用吗

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Jibing-Li** [comment]
> oss 不是支持 s3 协议，不可以直接用吗

是支持的，但fe端hadoop文件系统api不支持oss://开头的路径，需要替换成s3://

**Comment by yiguolei** [comment]
> oss 不是支持 s3 协议，不可以直接用吗

有一部分人想用  oss:// 这样啊

**Pull request merged**
