### PR TITLE
[fix](build index)Remove index_meta in tablet schema when the index is dropped.

### LINKED ISSUE #37645: [Bug] when dropping indexes, there is lots of NOT_FOUND files logs
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
W20240710 22:01:53.956023 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017629d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956068 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762ad94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956108 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762bd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956147 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762cd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956187 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762dd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956228 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762ed94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956269 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001762fd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956308 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017630d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956353 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017631d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956454 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017636d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956584 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001763dd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956629 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001763ed94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956668 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001763fd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956708 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017640d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956749 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017641d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956789 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017642d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956840 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017643d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.956880 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017644d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957037 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001764cd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957082 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001764dd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957126 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001764ed94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957170 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/020000000001764fd94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957209 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017650d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957250 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017651d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957293 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017652d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957334 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017653d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957376 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017654d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957419 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017655d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
W20240710 22:01:53.957463 293460 file_system.cpp:68] [NOT_FOUND]failed to get file size /mnt/disk2/VEC_ASAN/doris.HDD/data/151/3817653/376199432/0200000000017656d94444e49d698ded9b7e4159f4c5f498_0_3817636.idx
```

### What You Expected?

No NOT_FOUND logs

### How to Reproduce?

1. create table 
```sql
CREATE TABLE t1
(
    k1 int ,
    k2 string,
    k3 char(50),
    k4 varchar(200),
    k5 int,
    index index_int (k1) using inverted,
    index index_str_k2 (k2) using inverted properties("parser"="english","ignore_above"="257"),
    index index_str_k4 (k4) using inverted,
    index index_k5 (k5) using inverted
)
DISTRIBUTED BY RANDOM BUCKETS 1
PROPERTIES("replication_num" = "1","inverted_index_storage_format"="v1");
```
2. insert data
```
insert into t1 values(1, "json love anny", "json", "anny",1);
```
3. drop index
```
drop index index_int on t1;
drop index index_k5 on t1;
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #37645

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
