### PR TITLE
[fix](load)Fix wrong default value for char and varchar of reading json data

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

Issue Number: close #xxx

If a column is defined as: `col VARCHAR/CHAR NULL` and no default value. Then we load json data which misses column `col`, the result queried is not correct:
+------+
| col      |
+------+
|            |
+------+
But expect:
+------+
| col      |
+------+
| NULL  |
+------+

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.41 seconds
 stream load tsv:          511 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17165995286 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
