### PR TITLE
[bugfix](external) Prevent multiple `fs` from being generated

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

If the user has already registered, there is no need to register again, otherwise `fs` will generate multiple instances.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
