### PR TITLE
Update flink-doris-connector.md

### PR DESCRIPTION
**Pull request by cjj2010**
Add String type correspondence between Doris and Flink

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cjj2010** [comment]
@jackwener I have improved the document and helped to review it. Thank you very much

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
Need to update english doc too

**Comment by cjj2010** [comment]
> Need to update english doc too

ok Now modified

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
