### PR TITLE
[opt](function)Some geo functions incorrectly used get.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
```

mysql [test]>select count(st_distance_sphere(db, db, db, db)) from double_ranges;
+-------------------------------------------+
| count(st_distance_sphere(db, db, db, db)) |
+-------------------------------------------+
|                                         0 |
+-------------------------------------------+
1 row in set (1.25 sec)

mysql [test]>select count(st_distance_sphere(db, db, db, db)) from double_ranges;
+-------------------------------------------+
| count(st_distance_sphere(db, db, db, db)) |
+-------------------------------------------+
|                                         0 |
+-------------------------------------------+
1 row in set (0.33 sec)
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Pull request merged**
