### PR TITLE
[improvement](iceberg)]support doris's char/varchar to iceberg's string

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Support doris's `char`/`varchar` to iceberg's `string`.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run p0

**Comment by wuwenchi** [comment]
run external

**Comment by wuwenchi** [comment]
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by wsjz — APPROVED** [review]
LGTM

**Pull request merged**
