### PR TITLE
[fix](functions) fix least/greatest function coredump bug

### LINKED ISSUE #19378: [Bug] [daily] select greatest() caused be core
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master: doris-0.0.0-trunk-32273a7

### What's Wrong?

image

select greatest(1.1, 1.2, 1.3, 1.4, 1.5, k9) from baseall order by k1;

be.out:
start time: Mon May  8 10:54:26 CST 2023
F0508 11:54:25.791194 106592 column_decimal.cpp:274] Parameters start = 0, length = 15 are out of bound in ColumnDecimal<T>::insert_range_from method (data.size() = 1)
*** Check failure stack trace: ***
    @     0x556056d24dad  google::LogMessage::Fail()
    @     0x556056d272e9  google::LogMessage::SendToLog()
    @     0x556056d24916  google::LogMessage::Flush()
    @     0x556056d27959  google::LogMessageFatal::~LogMessageFatal()
    @     0x5560523bb03a  doris::vectorized::ColumnDecimal<>::insert_range_from()
    @     0x556055f52b13  doris::vectorized::CompareMultiImpl<>::execute()
    @     0x556055f552b8  doris::vectorized::FunctionMultiSameArgs<>::execute_impl()
    @     0x55605411d73c  doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns()
    @     0x55605411c230  doris::vectorized::PreparedFunctionImpl::default_implementation_for_nulls()
    @     0x55605411d3d5  doris::vectorized::PreparedFunctionImpl::execute()
    @     0x5560524951b4  doris::vectorized::IFunctionBase::execute()
    @     0x5560535e7af9  doris::vectorized::VectorizedFnCall::execute()
    @     0x5560535eb9c0  doris::vectorized::VExprContext::execute()
    @     0x5560535ecdbc  doris::vectorized::VExprContext::get_output_block_after_execute_exprs()
    @     0x5560500df47f  doris::vectorized::VMysqlResultWriter<>::append_block()
    @     0x556055fb33fa  doris::vectorized::VResultSink::send()
    @     0x55604ffbf99f  doris::PlanFragmentExecutor::open_vectorized_internal()
    @     0x55604ffc0077  doris::PlanFragmentExecutor::open()
    @     0x55604ff94a69  doris::FragmentExecState::execute()
    @     0x55604ff977e7  doris::FragmentMgr::_exec_actual()
    @     0x55604ff97e5d  _ZNSt17_Function_handlerIFvvEZN5doris11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_12RuntimeStateEPNS1_6StatusEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x5560501d56e5  doris::ThreadPool::dispatch_thread()
    @     0x5560501ccbcf  doris::Thread::supervise_thread()
    @     0x7fccf5986851  start_thread
    @     0x7fccf545067d  clone
    @              (nil)  (unknown)
*** Query id: 9b5060c1111144c2-a439b681ec6460b2 ***
*** Aborted at 1683518065 (unix time) try "date -d @1683518065" if you are using GNU date ***
*** Current BE git commitID: 32273a7 ***
*** SIGABRT unknown detail explain (@0x1f500019e3e) received by PID 106046 (TID 106592 OR 0x7fcb89df8700) from PID 106046; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/doris-release/be/src/common/signal_handler.h:412
 1# 0x00007FCCF598E500 in /lib64/libpthread.so.0
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x0000556056D2F799 in /be/lib/doris_be
 5# 0x0000556056D24DAD in /be/lib/doris_be
 6# google::LogMessage::SendToLog() in doris_be
 7# google::LogMessage::Flush() in /be/lib/doris_be
 8# google::LogMessageFatal::~LogMessageFatal() in /be/lib/doris_be
 9# doris::vectorized::ColumnDecimal<doris::vectorized::Decimal<__int128> >::insert_range_from(doris::vectorized::IColumn const&, unsigned long, unsigned long) at /root/doris-release/be/src/vec/columns/column_decimal.cpp:274
10# doris::vectorized::CompareMultiImpl<doris::vectorized::GreaterOp, doris::vectorized::GreastName>::execute(doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long) at /root/doris-release/be/src/vec/functions/least_greast.cpp:94
11# doris::vectorized::FunctionMultiSameArgs<doris::vectorized::CompareMultiImpl<doris::vectorized::GreaterOp, doris::vectorized::GreastName> >::execute_impl(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) at /root/doris-release/be/src/vec/functions/function_multi_same_args.h:53
12# doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /root/doris-release/be/src/vec/functions/function.cpp:263
13# doris::vectorized::PreparedFunctionImpl::default_implementation_for_nulls(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool, bool*) at /root/doris-release/be/src/vec/functions/function.cpp:240
14# doris::vectorized::PreparedFunctionImpl::execute(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /root/doris-release/be/src/vec/functions/function.cpp:285
15# doris::vectorized::IFunctionBase::execute(doris::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /root/doris-release/be/src/vec/functions/function.h:170
16# doris::vectorized::VectorizedFnCall::execute(doris::vectorized::VExprContext*, doris::vectorized::Block*, int*) at /root/doris-release/be/src/vec/exprs/vectorized_fn_call.cpp:133
17# doris::vectorized::VExprContext::execute(doris::vectorized::Block*, int*) at /root/doris-release/be/src/vec/exprs/vexpr_context.cpp:56
18# doris::vectorized::VExprContext::get_output_block_after_execute_exprs(std::vector<doris::vectorized::VExprContext*, std::allocator<doris::vectorized::VExprContext*> > const&, doris::vectorized::Block const&, doris::vectorized::Block*) at /root/doris-release/be/src/vec/exprs/vexpr_context.cpp:137
19# doris::vectorized::VMysqlResultWriter<false>::append_block(doris::vectorized::Block&) at /root/doris-release/be/src/vec/sink/vmysql_result_writer.cpp:592
20# doris::vectorized::VResultSink::send(doris::RuntimeState*, doris::vectorized::Block*, bool) at /root/doris-release/be/src/vec/sink/vresult_sink.cpp:106
21# doris::PlanFragmentExecutor::open_vectorized_internal() at /root/doris-release/be/src/runtime/plan_fragment_executor.cpp:321
22# doris::PlanFragmentExecutor::open() at /root/doris-release/be/src/runtime/plan_fragment_executor.cpp:263
23# doris::FragmentExecState::execute() at /root/doris-release/be/src/runtime/fragment_mgr.cpp:264
24# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::RuntimeState*, doris::Status*)> const&) at /root/doris-release/be/src/runtime/fragment_mgr.cpp:534
25# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291
26# doris::ThreadPool::dispatch_thread() at /root/doris-release/be/src/util/threadpool.cpp:539
27# doris::Thread::supervise_thread(void*) at /root/doris-release/be/src/util/thread.cpp:466
28# start_thread in /lib64/libpthread.so.0
29# clone in /lib64/libc.so.6

### What You Expected?

query ok

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #19378

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
