### PR TITLE
[fix](truncate) fix tablet invert index leaky

### PR DESCRIPTION
**Pull request by yujun777**
FIX:
1. fix tablet invert index leaky due to truncate fail;
2. fix NPE due to partitions has changed during truncating;

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
