### PR TITLE
[chore](backup) Fix the db name of the restored view

### PR DESCRIPTION
**Pull request by w41ter**
Previously, during restore, the database name in the CREATE VIEW statement was not modified, causing the restored view to be unviewable with the SHOW VIEW command. This PR retains the original cluster's database name in the BackupMeta and manually replaces it with the new cluster's database name in the CREATE VIEW statement during restore.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
please add a regression test case.

**Review by gavinchou — DISMISSED** [review]

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
