### PR TITLE
[fix](tablet scheduler) fix decommission sched exception

### PR DESCRIPTION
**Pull request by yujun777**
BUG:  when there exists running txns,   decommission replica will throw a sched failed exception and enter waiting for decommission status. But pr #30117 changes this behaviour,  it  cause throw a sched unrecovrable exception, then decommission replica will fail immediately.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
本地编译是可以的， 流水线上编译似乎又抽风了

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
