### PR TITLE
[fix](restore) restore failed between force_replication_allocation clusters

### PR DESCRIPTION
**Pull request by cambyzju**
Reproduce steps:
1. If we set `force_olap_table_replication_allocation = tag.location.zone2:1` in cluster A, and we backup tables as SNAPSHOT_A
2. in cluster B, we do not set force_olap_table_replication_allocation, and we try to restore SNAPSHOT_A with property: `reserve_replica = true`, then we got error, cannot find Backend with tag zone2.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run external_regression

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run feut

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
