### PR TITLE
[fix](log) PipelineFragmentContext has already been destoried in try_close_task before logging it

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buidlall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
