### PR TITLE
[typo](doc)fix typo in readme

### PR DESCRIPTION
**Pull request by niebayes**
# Proposed changes

Issue Number: No

## Problem summary

fix a typo by replacing miliseconds with milliseconds.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
modify pr title

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
