### PR TITLE
[fix](parquet) fix time zone error(isAdjustedToUTC=true) in parquet reader

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Revert #33217 and add some fix for regression test.
The modification of PR(#33217) is wrong, which introduce some issues about the time zone(https://github.com/apache/hudi/issues/11003).
If isAdjustedToUTC = false, the reader should display the same value no mater what local time zone is. For example:
When stored as `1970-01-03 12:00:00`,
If isAdjustedToUTC = true, UTC8 should read as `1970-01-03 20:00:00`, UTC6 should read as `1970-01-03 18:00:00`
If isAdjustedToUTC = false, UTC8 and UTC6 should read as `1970-01-03 12:00:00`, which is the same as `1970-01-03 12:00:00` in UTC0

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
