### PR TITLE
[fix] fix dereference to nullptr in Tablet::calc_delete_bitmap

### PR DESCRIPTION
**Pull request by zhengshengjun**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhengshengjun** [comment]
*** Query id: 0-0 ***
*** Aborted at 1671959691 (unix time) try "date -d @1671959691" if you are using GNU date ***
*** Current BE git commitID: 2b61c39 ***
*** SIGSEGV address not mapped to object (@0x18) received by PID 1682989 (TID 0x7f82b1bfb700) from PID 24; stack trace: ***
0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at ../src/common/signal_handler.h:420
1# 0x00007F846C128060 in /lib/x86_64-linux-gnu/libc.so.6
2# doris::Tablet::calc_delete_bitmap(doris::RowsetId, std::vector<std::shared_ptrdoris::segment_v2::Segment, std::allocator<std::shared_ptrdoris::segment_v2::Segment > > const&, std::unordered_set<doris::RowsetId, doris::HashOfRowsetId, std::equal_todoris::RowsetId, std::allocatordoris::RowsetId > const*, std::shared_ptrdoris::DeleteBitmap, long, bool) at ../src/olap/tablet.cpp:2049
3# doris::Tablet::update_delete_bitmap_without_lock(std::shared_ptrdoris::Rowset const&) at /usr/local/include/c++/11.3.0/bits/shared_ptr.h:122
4# doris::Tablet::revise_tablet_meta(std::vector<std::shared_ptrdoris::RowsetMeta, std::allocator<std::shared_ptrdoris::RowsetMeta > > const&, std::vector<doris::Version, std::allocatordoris::Version > const&) at ../src/olap/tablet.cpp:212
5# doris::EngineCloneTask::_finish_full_clone(doris::Tablet*, doris::TabletMeta*) at ../src/olap/task/engine_clone_task.cpp:654
6# doris::EngineCloneTask::_finish_clone(doris::Tablet*, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, long, bool) at ../src/olap/task/engine_clone_task.cpp:521
7# doris::EngineCloneTask::_do_clone() at ../src/olap/task/engine_clone_task.cpp:117
8# doris::EngineCloneTask::execute() at ../src/olap/task/engine_clone_task.cpp:69
9# doris::StorageEngine::execute_task(doris::EngineTask*) at ../src/olap/storage_engine.cpp:1025
10# doris::TaskWorkerPool::_clone_worker_thread_callback() at ../src/agent/task_worker_pool.cpp:917

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.81 seconds
 load time: 641 seconds
 storage size: 17123372435 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221226142026_clickbench_pr_69001.html

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
