### PR TITLE
[fix](statistics) correct update rows when doing multi-table load

### PR DESCRIPTION
**Pull request by freemandealer**
rows of only one table is updated correctly, need to merge all table commit infos.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a case.

**Comment by freemandealer** [comment]
> Please add a case.

here it is: statistics/test_update_rows_and_partition_first_load.groovy

**Pull request merged**
