### PR TITLE
[fix](timezone) fix timezone parse when there is no tzfile

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

When there's no tzfile:
before:
```SQL
mysql [test]>select convert_tz('2020-12-12 12:00:00', 'Asia/Shanghai', 'America/Los_angeles');
+--------------------------------------------------------------------------------------------------+
| convert_tz(cast('2020-12-12 12:00:00' as DATETIMEV2(0)), 'Asia/Shanghai', 'America/Los_angeles') |
+--------------------------------------------------------------------------------------------------+
| NULL                                                                                             |
+--------------------------------------------------------------------------------------------------+
1 row in set (0.03 sec)
```
after：
```SQL
mysql [test]>select convert_tz('2020-12-12 12:00:00', 'Asia/Shanghai', 'America/Los_angeles');
+--------------------------------------------------------------------------------------------------+
| convert_tz(cast('2020-12-12 12:00:00' as DATETIMEV2(0)), 'Asia/Shanghai', 'America/Los_angeles') |
+--------------------------------------------------------------------------------------------------+
| 2020-12-11 20:00:00                                                                              |
+--------------------------------------------------------------------------------------------------+
1 row in set (0.03 sec)
```

It tested in docker.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
@jacktengg PTAL

**Review by jacktengg — APPROVED** [review]
LGTM

**Review by HappenLee — CHANGES_REQUESTED** [review]
ADD a UT or regression test

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
