### PR TITLE
[Fix](outfile) FE check the hdfs URI of outfile

### PR DESCRIPTION
**Pull request by BePPPower**
1. Previously, if the root path of the HDFS URI started with two slashes, the outfile would be successfully exported without errors, but the exported path would not be the expected path.
Currently, we will delete repeated '/' which specified by users in FE.

2. move the test case for outfile HDFS from p2 to p0.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Comment by BePPPower** [comment]
run cloud_p0 cloud_p1

**Pull request merged**
