### PR TITLE
[feature](array-type) Create table with nested array type.

### LINKED ISSUE #8002: [Feature] [array-type] Create table with nested array type.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

This issue is a sub task of #7570 .

Array type declaration doesn't support nested array type (eg: Array<Array\<int\>>) when create table.

### Use case

```shell
mysql> create table array_type_table(k1 INT, k2 Array<Array<int>>) duplicate key (k1)
    -> distributed by hash(k1) buckets 1 properties('replication_num' = '1');
```

### Related issues

#7570

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

Issue Number: close #8002 .

## Problem Summary:

Please refer to #8002 .

## Checklist(Required)

1. Does it affect the original behavior: No.
2. Has unit tests been added: Yes.
3. Has document been added or modified: No Need.
4. Does it need to update dependencies: No.
5. Are there any changes that cannot be rolled back: No.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Doris-Extras** [comment]
mysql> create table array_type_table(k1 INT, k2 Array<Array<int>>) duplicate key (k1)
    -> distributed by hash(k1) buckets 1 properties('replication_num' = '1');

why not use create table array_type_table(k1 INT, k2 Array<int>) ?

**Comment by adonis0147** [comment]
`Array<int>` is an array with one dimension.
`Array<Array<int>>` is an array with two dimension.

**Comment by yiguolei** [comment]
> `Array<int>` is an array with one dimension. `Array<Array<int>>` is an array with two dimensions.
> 
> Like multi-dimensional arrays in [ClickHouse](https://clickhouse.com/docs/en/sql-reference/data-types/array/#array-size).

I see. Great.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
