### PR TITLE
[fix](es catalog) fix issue with select and insert from es catalog core

### LINKED ISSUE #24315: [Bug] select/insert into select es catalog core
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

select core:

```
doris_be: /mnt/disk2/luen/develop/workspace/incubator-doris/thirdparty/installed/include/rapidjson/document.h:1818: int64_t rapidjson::GenericValue<rapidjson::UTF8<>>::GetInt64() const [Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `data_.f.flags & kInt64Flag' failed.
*** Query id: 97ba2e48df8247a4-a1951925d36f11f2 ***
*** Aborted at 1694597597 (unix time) try "date -d @1694597597" if you are using GNU date ***
*** Current BE git commitID: a538b4922c ***
*** SIGABRT unknown detail explain (@0x4210019795b) received by PID 1669467 (TID 1670128 OR 0x7fad593f4700) from PID 1669467; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/common/signal_handler.h:413
 1# 0x00007FAEC30E2B50 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# __GI_abort in /lib64/libc.so.6
 4# _nl_load_domain.cold.0 in /lib64/libc.so.6
 5# 0x00007FAEC30DB426 in /lib64/libc.so.6
 6# rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GetInt64() const in /mnt/disk2/luen/mydoris/be/lib/doris_be
 7# doris::Status doris::insert_int_value<long>(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&, doris::PrimitiveType, doris::vectorized::IColumn*, bool, bool) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/exec/es/es_scroll_parser.cpp:350
 8# doris::ScrollParser::fill_columns(doris::TupleDescriptor const*, std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&, bool*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/exec/es/es_scroll_parser.cpp:535
 9# doris::vectorized::NewEsScanner::_get_next(std::vector<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>, std::allocator<COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn> > >&) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/exec/scan/new_es_scanner.cpp:191
10# doris::vectorized::NewEsScanner::_get_block_impl(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/exec/scan/new_es_scanner.cpp:145
11# doris::vectorized::VScanner::get_block(doris::RuntimeState*, doris::vectorized::Block*, bool*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/exec/scan/vscanner.cpp:98
12# doris::vectorized::ScannerScheduler::_scanner_scan(doris::vectorized::ScannerScheduler*, doris::vectorized::ScannerContext*, std::shared_ptr<doris::vectorized::VScanner>) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/exec/scan/scanner_scheduler.cpp:407
13# doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}::operator()() const at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/exec/scan/scanner_scheduler.cpp:254
14# void std::__invoke_impl<void, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}&>(std::__invoke_other, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
15# std::enable_if<is_invocable_r_v<void, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}&>, void>::type std::__invoke_r<void, doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}&>(doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
16# std::_Function_handler<void (), doris::vectorized::ScannerScheduler::_schedule_scanners(doris::vectorized::ScannerContext*)::$_1::operator()() const::{lambda()#4}>::_M_invoke(std::_Any_data const&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
17# std::function<void ()>::operator()() const at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
18# doris::FunctionRunnable::run() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/threadpool.cpp:48
19# doris::ThreadPool::dispatch_thread() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/threadpool.cpp:533
20# void std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(std::__invoke_memfun_deref, void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
21# std::__invoke_result<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>::type std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
22# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:420
23# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:503
24# void std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
25# std::enable_if<is_invocable_r_v<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
26# std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
27# std::function<void ()>::operator()() const at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
28# doris::Thread::supervise_thread(void*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/thread.cpp:465
29# start_thread in /lib64/libpthread.so.0
30# __clone in /lib64/libc.so.6
```

insert into select core 
```
F20230913 12:06:15.653185 2923605 column_impl.h:67] Size of selector: 1, is larger than size of column:0
*** Check failure stack trace: ***
    @     0x55f283e81076  google::LogMessage::SendToLog()
    @     0x55f283e7d640  google::LogMessage::Flush()
    @     0x55f283e818b9  google::LogMessageFatal::~LogMessageFatal()
    @     0x55f27ca7674e  doris::vectorized::IColumn::append_data_by_selector_impl<>()
    @     0x55f27ca74f95  doris::vectorized::ColumnNullable::append_data_by_selector()
    @     0x55f27cbe7ed7  doris::vectorized::Block::append_block_by_selector()
    @     0x55f283859181  doris::stream_load::VNodeChannel::add_block()
    @     0x55f283862b91  doris::stream_load::VOlapTableSink::send()
    @     0x55f277d6f520  doris::PlanFragmentExecutor::open_vectorized_internal()
    @     0x55f277d6e952  doris::PlanFragmentExecutor::open()
    @     0x55f277d708b2  doris::PlanFragmentExecutor::execute()
    @     0x55f277c58e48  doris::FragmentMgr::_exec_actual()
    @     0x55f277c64a42  doris::FragmentMgr::exec_plan_fragment()::$_0::operator()()
    @     0x55f277c649e5  std::__invoke_impl<>()
    @     0x55f277c649a5  _ZSt10__invoke_rIvRZN5doris11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_12RuntimeStateEPNS0_6StatusEEEE3$_0JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESH_E4typeEOSI_
DpOSJ_
    @     0x55f277c647cd  std::_Function_handler<>::_M_invoke()
    @     0x55f276d46d65  std::function<>::operator()()
    @     0x55f2780c0ba9  doris::FunctionRunnable::run()
    @     0x55f2780b8f87  doris::ThreadPool::dispatch_thread()
    @     0x55f2780c7769  std::__invoke_impl<>()
    @     0x55f2780c76ad  std::__invoke<>()
    @     0x55f2780c767d  _ZNSt5_BindIFMN5doris10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x55f2780c7636  std::_Bind<>::operator()<>()
    @     0x55f2780c7605  std::__invoke_impl<>()
    @     0x55f2780c75c5  _ZSt10__invoke_rIvRSt5_BindIFMN5doris10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @     0x55f2780c73dd  std::_Function_handler<>::_M_invoke()
    @     0x55f276d46d65  std::function<>::operator()()
    @     0x55f2780a6bd5  doris::Thread::supervise_thread()
    @     0x7f987c3c21ca  start_thread
    @     0x7f987cdb1e73  __GI___clone
    @              (nil)  (unknown)
*** Query id: f3fb4909a75b4701-a101af90be279408 ***
*** Aborted at 1694577975 (unix time) try "date -d @1694577975" if you are using GNU date ***
*** Current BE git commitID: a538b4922c ***
*** SIGABRT unknown detail explain (@0x421002c9a32) received by PID 2923058 (TID 2923605 OR 0x7f977217d700) from PID 2923058; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/common/signal_handler.h:413
 1# 0x00007F987CDC6B50 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# __GI_abort in /lib64/libc.so.6
 4# 0x000055F283E8B88D in /mnt/disk2/luen/mydoris/be/lib/doris_be
 5# 0x000055F283E7DB9A in /mnt/disk2/luen/mydoris/be/lib/doris_be
 6# google::LogMessage::SendToLog() in /mnt/disk2/luen/mydoris/be/lib/doris_be
 7# google::LogMessage::Flush() in /mnt/disk2/luen/mydoris/be/lib/doris_be
 8# google::LogMessageFatal::~LogMessageFatal() in /mnt/disk2/luen/mydoris/be/lib/doris_be
 9# void doris::vectorized::IColumn::append_data_by_selector_impl<doris::vectorized::ColumnNullable>(COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&, doris::vectorized::PODArray<unsigned long, 4096ul, Allocator<f
alse, false, false>, 15ul, 16ul> const&) const in /mnt/disk2/luen/mydoris/be/lib/doris_be
10# doris::vectorized::ColumnNullable::append_data_by_selector(COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&, doris::vectorized::PODArray<unsigned long, 4096ul, Allocator<false, false, false>, 15ul, 16ul> const
&) const at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/columns/column_nullable.h:249
11# doris::vectorized::Block::append_block_by_selector(doris::vectorized::MutableBlock*, doris::vectorized::PODArray<unsigned long, 4096ul, Allocator<false, false, false>, 15ul, 16ul> const&) const at /mnt/disk2/luen/develop/workspace/inc
12# doris::stream_load::VNodeChannel::add_block(doris::vectorized::Block*, std::pair<std::unique_ptr<doris::vectorized::PODArray<unsigned long, 4096ul, Allocator<false, false, false>, 15ul, 16ul>, std::default_delete<doris::vectorized::PO
DArray<unsigned long, 4096ul, Allocator<false, false, false>, 15ul, 16ul> > >, std::vector<long, std::allocator<long> > > const*, bool) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/sink/vtablet_sink.cpp:660
13# doris::stream_load::VOlapTableSink::send(doris::RuntimeState*, doris::vectorized::Block*, bool) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/vec/sink/vtablet_sink.cpp:1388
14# doris::PlanFragmentExecutor::open_vectorized_internal() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:335
15# doris::PlanFragmentExecutor::open() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:277
16# doris::PlanFragmentExecutor::execute() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/runtime/plan_fragment_executor.cpp:410
17# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::PlanFragmentExecutor>, std::function<void (doris::RuntimeState*, doris::Status*)> const&) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/runtime/fragment_mgr.cpp:337
18# doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0::operator()() const at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/runt
ime/fragment_mgr.cpp:646
19# void std::__invoke_impl<void, doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0&>(std::__invoke_other, doris::FragmentMgr::exec_plan_f
ragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/inv
oke.h:61
20# std::enable_if<is_invocable_r_v<void, doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0&>, void>::type std::__invoke_r<void, doris::Fr
agmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0&>(doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<voi
d (doris::RuntimeState*, doris::Status*)> const&)::$_0&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
21# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::RuntimeState*, doris::Status*)> const&)::$_0>::_M_invoke(std::_Any_data const&) at /mnt/disk2/lue
n/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
22# std::function<void ()>::operator()() const at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
23# doris::FunctionRunnable::run() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/threadpool.cpp:48
24# doris::ThreadPool::dispatch_thread() at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/threadpool.cpp:533
25# void std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(std::__invoke_memfun_deref, void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-l
inux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
26# std::__invoke_result<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>::type std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /mnt/disk2/luen/develop/tools/l
db_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
27# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/
11/functional:420
28# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:503
29# void std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../l
ib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
30# std::enable_if<is_invocable_r_v<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::_Bind<void (doris::ThreadPoo
l::*(doris::ThreadPool*))()>&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
31# std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c+
+/11/bits/std_function.h:291
32# std::function<void ()>::operator()() const at /mnt/disk2/luen/develop/tools/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
33# doris::Thread::supervise_thread(void*) at /mnt/disk2/luen/develop/workspace/incubator-doris/be/src/util/thread.cpp:465
34# start_thread in /lib64/libpthread.so.0
35# __clone in /lib64/libc.so.6
```

### What You Expected?

query normally.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #24315 

The root cause of this issue is that Elasticsearch's long type allows inserting floats and strings. Doris did not handle these cases when doing type conversion. The current strategy is to take the integer before the decimal point if a float or string is found.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run beut

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
