### PR TITLE
[Enhancement](http)Add http authentication to all API interfaces under be 8040.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes
Add http authentication to all API interfaces under be 8040
The `enable_all_http_auth parameter` in be.conf can control the switch.

Issue Number: close #xxx

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
