### PR TITLE
[bug](json)Fix some problems of json function on Nereids

### PR DESCRIPTION
**Pull request by LemonLiTree**
1. Fix some problems of json_length and json_contains function on Nereids
2. fix wrong result of json_contains function
3. Regression test jsonb_p0 to enable Nereids

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
