### PR TITLE
[Bug](mark-join)fix mark join report error when probe block have column do not output

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
mysql> SELECT  pk AS C1   FROM table_1000_undef_undef2 AS T1 WHERE `col_bigint_undef_signed` NOT IN (SELECT  `col_bigint_undef_signed2` AS C2   FROM  table_1000_undef_undef2 AS T2  ) OR `col_bigint_undef_signed2` <> 9 ;ERROR 1105 (HY000): errCode = 2, detailMessage = (127.0.0.1)[CANCELLED][INTERNAL_ERROR]input block not contain slot column , column_id=3, block=pk Nullable(Int32) Nullable(size = 95, Int32(size = 95), UInt8(size = 95)),col_bigint_undef_signed2 Nullable(Int64) Nullable(size = 95, Int64(size = 95), UInt8(size = 95)),[Anonymous Column] Nullable(UInt8) Nullable(size = 95, UInt8(size = 95), UInt8(size = 95))
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
