### PR TITLE
[fix](group commit) Group commit support sequence column for unique t…

### PR DESCRIPTION
**Pull request by mymeiyi**
…able

## Proposed changes

As the title, fix write sequence and delete sign column for unique table with group commit load, and add some regressions.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run  buildall

**Comment by mymeiyi** [comment]
run pipelinex_p0

**Comment by mymeiyi** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
