### PR TITLE
[cherry-pick](branch-3.0) Pick "[Enhancement](MS) Add fix tablet data size api for meta service (#41782)"

### PR DESCRIPTION
**Pull request by Yukang-Lian**
Pick #41782

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run cloud_p0

**Comment by Yukang-Lian** [comment]
run external

**Comment by Yukang-Lian** [comment]
run external

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
