### PR TITLE
[regression](cluster key) move cluster key case to a new directory

### PR DESCRIPTION
**Pull request by mymeiyi**
move cluster key case from `unique_with_mow_p0` directory to `unique_with_mow_c_p0` directory, because we will add more case like `unique_with_mow_p0`, now the directory is nested and confusing.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
