### PR TITLE
[improvement](jdbc catalog) Optimize JDBC driver property settings

### PR DESCRIPTION
**Pull request by zy-kkk**
Abstract JDBC Driver property settings into methods for easier management

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
