### PR TITLE
[Fix](bitshuffle)Enable avx512 support in bitshuffle for performance boost

### LINKED ISSUE #24145: [Bug] avx512 is misjudge and cause be coredump
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

BE coredump in `CPU().has_avx512()` branch in `bitshuffle_wrapper.cpp`. There is no avx512 feature in cpuinfo but `CPU().has_avx512()` is true.

- coredump stack
image

- cat /proc/cpuinfo

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz
stepping	: 7
cpu MHz		: 2800.044
cache size	: 22528 KB
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch arat xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 invpcid rtm
bogomips	: 5600.08
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:
```

### What You Expected?

If there is no avx512 feature in cpuinfo, `CPU().has_avx512()` should be false and be should not core.

### How to Reproduce?

_No response_

### Anything Else?

avx512 optimization is introduced by https://github.com/apache/doris/pull/15972 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HackToday**
## Proposed changes

Issue Number: close #24145

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HackToday** [comment]
@xiaokang Could you review it or some else?

**Comment by yiguolei** [comment]
could you please add some performance test result in the PR description?

**Comment by HackToday** [comment]
@yiguolei  Thanks for your comment. The PR was reverted before, the performance details info could be found here:
https://github.com/apache/doris/pull/15972

>>As AVX512 is available in most modern processors, it is good to use them if have performance boost.
In latest bitshuffle, AVX512 have been added. We could make it integrated in doris for AVX512 case.
Tested with master branch, queries(SSB query q1.1.sql~q4.3.sql total 13 queries) can be boost from 1.4%~3.2%. (use run-ssb-queries.sh 5 times, each time with 100 iterations.)

Please let me know if other questions.  Thanks

**Comment by JNSimba** [comment]
run buildall

**Pull request closed without merging**
