### PR TITLE
[fix](tablet report) fix fe can not update replica's status with be's report

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #xxx

FE should update its replica's version and health status(is bad or not),  if its state is fall behind BE.

For example,  if BE take away the disk or disk is not available now,  then BE will report lost replica and FE will mark this replica as bad.  

Next BE reinstall the disk and disk is now available, then it will report its replica is ok,  then FE should mark this replica as good. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
