### PR TITLE
[chore](regression-test) Move cloud new tablet compaction test suites from p0 to p1

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title, to reduce cloud_p0 time consumption

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
