### PR TITLE
[enchement](mc)mc catalog append netowrk config

### PR DESCRIPTION
**Pull request by hubgeter**
### What problem does this PR solve?

Since there may be some network problems when accessing maxcompute, in order to provide a better user experience, we introduce some parameters to help users better adapt to the network.

You can add these parameters when creating a catalog:
`mc.connect_timeout` :  Connection timeout, default is 10s.
`mc.read_timeout` : Read timeout,default is 120s.
`mc.retry_count` : Number of retries after failure,default is 4.

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

MaxCompute catalog add three parameters : `mc.connect_timeout` , `mc.read_timeout`,`mc.retry_count`  help users better adapt to the network between MaxCompute and Doris.

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [ ] No.
    - [x] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
