### PR TITLE
[Bug](load) fix crash when be exit

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes
NewLoadStreamMgr relies on metric, and when it is destroyed, it will involve metric destroyed.Now, the deconstruction order is: metric->NewLoadStreamMgr->env.When program exit, it will core dump because of metric had been destroyed while NewLoadStreamMgr destroyed.
Therefore, we should destroy NewLoadStreamMgr before metric, and destroy NewLoadStreamMgr in env destroy method.
the deconstruction order is change:NewLoadStreamMgr->metric->NewLoadStreamMgr->env.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run p0

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
