### PR TITLE
[prune](partition)support prune partition when is auto partition with function call

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
 now create table use auto create partition:
 AUTO PARTITION BY RANGE date_trunc(event_day, 'day')
 so the value of event_day will be insert into partition of date_trunc(event_day, 'day'),
 eg: select * from partition_range where date_trunc(event_day,"day")= "2023-08-07 11:00:00";
 we can prune some partitions by invoke function of date_trunc("2023-08-07 11:00:00","day" );

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
