### PR TITLE
[Feature](datatype) add be ut codes for IPv4/v6

### LINKED ISSUE #21370: [Feature](datatype) Add  IPv4/v6 data type for doris
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Now We do not support  IPv4/v6 data type for doris witch is common  data type in database
So it's the time to support it ! We have some basic funnctions for data type to check the data type is supported completly

- [ ] support CURD 
- [ ] support StreamLoad
- [ ] support Serde functions 
- [ ] support (implicit/explicit) cast functions 
- [ ] specific functions for itself data type (u can reference clickhouse or mysql)
        eg: IPv4ToIPv6(xxx) 

- [ ] make a Performance Test result with clickhouse or ElasticSearch in load this data type

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sjyango**
## Proposed changes

Issue Number: close #21370

Add unit test codes for IP types. Based on pr [24965](https://github.com/apache/doris/pull/24965)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run PipelineX

**Comment by sjyango** [comment]
run p0 PipelineX

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run p0

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run p0

**Review by amorynan — APPROVED** [review]
LGTM

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
