### PR TITLE
[improvement](mow) Add profile for delete_bitmap get_agg function

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
now profile could be
I20240412 11:08:51.078223 2771963 plan_fragment_executor.cpp:640] Fragment xxxx:(Active: 12s048ms, non-child: 0.85%)
   - DorisBeVersion: 7206fa868e
   - BlocksProduced: 40
   - FragmentCpuTime: 867.503ms
   - RowsProduced: 99.89K
  VOlapTableSink:(Active: 11s946ms, non-child: 98.33%)
     - xxx
    VNewOlapScanNode(stress_source(stress_source)) (id=0):(Active: 99.112ms, non-child: 0.82%)
       - xxx
      VScanner:
         -xxx
         - DeleteBitmapGetAggTime: 6.957ms
         - xxx
        SegmentIterator:
           - xxx
<unnamed>:
   - xxx
  LoadChannel load_id=xxx:
     - xxx
    TabletsChannel (xxx):
       - xxx
      RowsetBuilder 512174:
         - xxx
      DeltaWriter 512174:
         - xxx
        MemTableWriter 512174:
           -xxx
      PeakMemoryUsage:
         - xxx

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
