### PR TITLE
[test](doc) add job-scheduler example in doris's doc to regression test

### PR DESCRIPTION
**Pull request by yagagagaga**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run cloud_p0

**Comment by yagagagaga** [comment]
run p0

**Comment by yagagagaga** [comment]
run external

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run external

**Comment by yagagagaga** [comment]
run external

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
