### PR TITLE
[Fix](flexible partial update) Report error when multi segments are generated in one flexible partial update load

### PR DESCRIPTION
**Pull request by bobhan1**
In flexible partial update, when there are more than one segment in one load, we need to do alignment process for same keys between segments. Considering that this situation is rare, we temporally report an error in this situation and will implement it later.

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run cloud_p0

**Pull request merged**
