### PR TITLE
[Improve](fe)Use commons-lang3 uniformly and refactor PatternGenerator#generateTypePattern

### PR DESCRIPTION
**Pull request by CalvinKirs**
# Proposed changes

Issue Number: close #xxx

## Problem summary
`commons-lang `(1and2) is no longer maintained since 2011, and the official recommendation is `commons-lang3`, which can be smoothly upgraded to be compatible with `commons-lang`.
We use both dependencies in `fe`, which can be completely unified.

 `PatternGenerator#generateTypePattern `has many meaningless loops, and IntegerRange is introduced for, which is unnecessary. So I refactored it.

## Describe your changes.

- Use commons-lang3 uniformly
- Add the check that prohibits commons-lang in checkstyle 
- Refactor PatternGenerator#generateTypePattern to reduce meaningless method loops
## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
todo add UT

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
The multiple loop in the PatternGenerator#generateTypePattern is for readability, this function will invoke in the compile time so is not the hot point.

Maybe we should use `java.util.stream.IntStream.range()` to replace it

**Comment by CalvinKirs** [comment]
> The multiple loop in the PatternGenerator#generateTypePattern is for readability, this function will invoke in the compile time so is not the hot point.↳
I know, I just replace `IntegerRange`,but even with the current approach, I don't think it has increased the complexity of the code. right?
> 
> Maybe we should use `java.util.stream.IntStream.rangeClosed()` to replace the `IntRange`↳

**Comment by 924060929** [comment]
> I know, I just replace `IntegerRange`,but even with the current approach, I don't think it has increased the complexity of the code. right?

ok

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
