### PR TITLE
[Improvement](scan) Refine ignoring data distribution without join

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by zhangstar333 — DISMISSED** [review]

**Comment by Gabriel39** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
