### PR TITLE
[test](regression-test) use unified trigger_and_wait_compaction method

### LINKED ISSUE #45591: [Bug] Incorrect usage of Awaitility.await() in test case
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

after #38836 

### What's Wrong?

In groovy, await is used with assert and without return. e.g.
```
def counter = 0;

for (int i = 1; i < 20; i++) {
    Awaitility.await().untilAsserted(() -> {
        ++counter
        println "${i}"
        if (counter > 10) {
            assert true
        } else {
            assert false
        }
    });
}
```
works fine but 
```
def counter = 0;

for (int i = 1; i < 20; i++) {
    Awaitility.await().untilAsserted(() -> {
        ++counter
        println "${i}"
        if (counter > 10) {
            return true
        } else {
            return false
        }
    });
}
```
will result await quit whenever return value is true or false

### What You Expected?

just as mentioned

### How to Reproduce?

just as mentioned

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by py023**
### What problem does this PR solve?

Issue Number: close #45591
Related PR: #38836

Problem Summary: Previously many regression cases use their own private functions to trigger compaction, results in a bunch of error-prone copy-pasted code. This PR introduces a unified method to trigger and wait compaction finished. Hopefully new cases won't need to write their own compaction method in the future.

Unsolved problem: Several cases(~20) have more dedicated actions to check compaction result, I didn't modify those cases in this PR, to avoid unexpected case behavior change. It's better to handle those cases in another PR, as it takes more times and this PR is already a huge change set.

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run p0
run cloud_p0

**Comment by py023** [comment]
run p0
run cloud_p0

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run p0
run cloud_p0

**Comment by hello-stephen** [comment]
run p0

**Comment by hello-stephen** [comment]
run cloud_p0

**Comment by py023** [comment]
run cloud_p0

**Comment by py023** [comment]
run p0

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run p0

**Comment by py023** [comment]
run buildall

**Comment by py023** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by py023** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
