### PR TITLE
[test](regression) add cases about datev1/datatimev1

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

* All cases' results are tested and passed with datetime/date v2
* Cases about:
    1.  Calculation ( +, -
    2. Kinds of predicates(<, >, =, <>, in, not in, is null, is not null)
    3. Load test(from csv and select into)
    4. Runtime filter
    5. Delete conditions
    6. Key columns(agg/duplicate/uniq model, distributed/partition, bitmap index...)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
