### PR TITLE
Remove redundant com.baidu:jprotobuf

### LINKED ISSUE #3318: Remove redundant com.baidu:jprotobuf
Before, in our cluster, we update fe by only updating the palo-fe.jar.
Now, we update fe by updating the all `lib` folder.
But, after update the whole `lib` folder, `NoClassDefFoundError` occurs:
```
2020-04-13 15:20:26,063 WARN 186 [BackendServiceProxy.execPlanFragmentAsync():112] Execute plan fragment catch a exception, addres
s=10.16.126.9:8060
java.lang.NoClassDefFoundError: Could not initialize class com.baidu.bjf.remoting.protobuf.code.CodedConstant
        at com.baidu.bjf.remoting.protobuf.code.TemplateCodeGenerator.initEncodeMethodTemplateVariable(TemplateCodeGenerator.java:
156) ~[jprotobuf-2.2.11-jar-with-dependencies.jar:?]
        at com.baidu.bjf.remoting.protobuf.code.TemplateCodeGenerator.getCode(TemplateCodeGenerator.java:120) ~[jprotobuf-2.2.11-j
ar-with-dependencies.jar:?]
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.doCreate(ProtobufProxy.java:354) ~[jprotobuf-2.2.11-jar-with-dependencies
.jar:?]
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:274) ~[jprotobuf-2.2.11-jar-with-dependencies.j
ar:?]
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:255) ~[jprotobuf-2.2.11-jar-with-dependencies.j
ar:?]
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:234) ~[jprotobuf-2.2.11-jar-with-dependencies.j
ar:?]
        at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:193) ~[jprotobuf-2.2.11-jar-with-dependencies.j
ar:?]
        at com.baidu.jprotobuf.pbrpc.client.PojoRpcMethodInfo.<init>(PojoRpcMethodInfo.java:55) ~[jprotobuf-rpc-core-3.5.21.jar:?]
        at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.proxy(ProtobufRpcProxy.java:289) ~[jprotobuf-rpc-core-3.5.21.jar:?]
        at org.apache.doris.rpc.BackendServiceProxy.getProxy(BackendServiceProxy.java:83) ~[palo-fe.jar:?]
        at org.apache.doris.rpc.BackendServiceProxy.execPlanFragmentAsync(BackendServiceProxy.java:94) [palo-fe.jar:?]
        at org.apache.doris.qe.Coordinator$BackendExecState.execRemoteFragmentAsync(Coordinator.java:1374) [palo-fe.jar:?]
        at org.apache.doris.qe.Coordinator.exec(Coordinator.java:463) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.handleInsertStmt(StmtExecutor.java:608) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:254) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:368) [palo-fe.jar:?]
        at org.apache.doris.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:544) [palo-fe.jar:?]
        at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1633) [palo-fe.jar:?]
        at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1618) [palo-fe.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
```

Strangely, this only appears on 0.11, not 0.12.
I found that the pom of the fe has two versions of `com.baidu:jprotobuf`.
One is `com.baidu:jprotobuf:jar:jar-with-dependencies:2.2.11` and the other is ` com.baidu:jprotobuf:jar:1.11.9` introduced by `com.baidu:jprotobuf-rpc-core:3.5.21`.
The dependency like follows:
```
+- com.baidu:jprotobuf:jar:jar-with-dependencies:2.2.11:compile
 +- com.baidu:jprotobuf-rpc-core:jar:3.5.21:compile
 |  +- com.baidu:jprotobuf:jar:1.11.9:compile
 |     \- commons-io:commons-io:jar:2.6:compile
```
After I remove the `com.baidu:jprotobuf:1.11.9`, `NoClassDefFoundError` disappeared.
So, can we remove the `com.baidu:jprotobuf:jar:1.11.9` and remain `com.baidu:jprotobuf:jar:jar-with-dependencies:2.2.11`?

### PR DESCRIPTION
**Pull request by liutang123**
For #3318 

* exclude jprotobuf from jprotobuf-rpc-core
* add commons-io used in fe.

### CODE REVIEW

**Comment by liutang123** [comment]
At 2020-04-15 17:00, we add this patch to our 0.12 cluster for test.

**Comment by morningman** [comment]
Are you sure this will not cause some other problem?
In our environment, we upgrade many clusters by replace the entire `fe/lib` directory, but none of
them encounter this problem.

**Comment by liutang123** [comment]
> Are you sure this will not cause some other problem?
> In our environment, we upgrade many clusters by replace the entire `fe/lib` directory, but none of
> them encounter this problem.

I am not sure, and this only appears in our 0.11 cluster.
We are testing this PR in our 0.12 cluster.

**Comment by imay** [comment]
@liutang123 
What's your test result? Does it work fine after applying your PR?

**Comment by liutang123** [comment]
> @liutang123
> What's your test result? Does it work fine after applying your PR?

My test is covered by other people, I will online it today again.
I will give a test result next week.

**Comment by imay** [comment]
> And I think this is stable for merge.

OK, Could you please rebase master to make regress run again?

**Review by imay — APPROVED** [review]
LGTM

**Review by kangkaisen — APPROVED** [review]
+1， LGTM

**Pull request merged**
