### PR TITLE
[enhancement](stats) Forbid unknown stats check for internal_column

### PR DESCRIPTION
**Pull request by Kikyou1997**
## Proposed changes

Ignore internal columns when enable new optimizer and forbid unknown stats

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Comment by Kikyou1997** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
