### PR TITLE
[chore](cmake) Split thirdparty into cmake/thirdparty.cmake

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Split thirdparty into cmake/thirdparty.cmake

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by ByteYue — APPROVED** [review]

**Comment by ByteYue** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.06 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162204686 Bytes

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by JackDrogon** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.9 seconds
 stream load tsv:          520 seconds loaded 74807831229 Bytes, about 137 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.6 seconds inserted 10000000 Rows, about 337K ops/s
 storage size: 17162205135 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
