### PR TITLE
[Fix](hive-writer) Fix partition column orders issue when the partition fields inserted into the target table are inconsistent with the field order of the query source table and the schema field order of the query source table.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

#31442

Fix partition column orders issue when the partition fields inserted into the target table are inconsistent with the field order of the query source table and the schema field order of the query source table.

Please look at `regression-test/suites/external_table_p0/hive/ddl/test_hive_write_type.groovy` in the PR.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
