### PR TITLE
[Feature] Add time_round builtin functions

### PR DESCRIPTION
**Pull request by ccoffline**
## Proposed changes

#4619 
Add time_round functions that provides `time_floor` & `time_ceil` at each time unit.

Fix two related bugs.
- #4618 
- Fix `struct TimeInterval` to use `int64_t` instead of `int32_t`, in case when the second diff overflow

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If this change need a document change, I have updated the document
- [x] Any dependent changes have been merged

## Further comments

This change didn't match the style as `TIMESTAMPDIFF`, which has some syntactic sugar on the time units in FE. I'm not much familiar with this implementation, so I'm going to figure it out and make up for the documentation then.

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Thanks for you PR.
Could you please add document for this new function?
under `sql-reference/sql-functions/date-time-functions/`

**Comment by ccoffline** [comment]
> Could you please add document for this new function?
> under `sql-reference/sql-functions/date-time-functions/`

Like I said, `TIMESTAMPDIFF` implementation in FE has some syntactic sugar on the time units, which combines all the functions into one. This makes the docs looks much prettier.

These function set has (#4619)

> `7(year, month, week, day, hour, minute, second) * 2(floor, ceil) * 4([timestamp], [ts, period], [ts, origin], [ts, period, origin])` = 56 functions. 

I'll try to make the docs looks simple.

**Comment by ccoffline** [comment]
@morningman docs added

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
