### PR TITLE
[fix](docker)Docker be register bug and add fe new interface recovery

### PR DESCRIPTION
**Pull request by FreeOnePlus**
## Proposed changes
fix be register bug：
before：
image
alter：
image

add fe new Interface —— recovery

docker run -itd  --name=fe-01  --env RECOVERY=true  -p 8031:8030  -p 9031:9030  -v /data/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta  -v /data/fe-01/log:/opt/apache-doris/fe/log  --network=doris-network  --ip=172.20.80.2    apache/doris:2.1.4-fe

image

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by FreeOnePlus** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
