### PR TITLE
[enhancement](audit) hide password and other sensitive information in log and audit log

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Review by Yulei-Yang — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
run clickbench

**Pull request merged**
