### PR TITLE
[enhance](auth)show privileges

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

```
mysql> show privileges;
+--------------------+-------------------------------------------------------+---------------------------------------------------+
| Privilege          | Context                                               | Comment                                           |
+--------------------+-------------------------------------------------------+---------------------------------------------------+
| Node_priv          | GLOBAL                                                | Privilege for cluster node operations             |
| Admin_priv         | GLOBAL                                                | Privilege for admin user                          |
| Grant_priv         | GLOBAL,CATALOG,DATABASE,TABLE,RESOURCE,WORKLOAD GROUP | Privilege for granting privilege                  |
| Select_priv        | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for select data in tables               |
| Load_priv          | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for loading data into tables            |
| Alter_priv         | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for alter catalog, database or table    |
| Create_priv        | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for creating catalog, database or table |
| Drop_priv          | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for dropping catalog, database or table |
| Usage_priv         | RESOURCE,WORKLOAD GROUP                               | Privilege for using resource or workloadGroup     |
| Cluster_usage_priv | RESOURCE                                              | Privilege for using cluster                       |
| Stage_usage_priv   | RESOURCE                                              | Privilege for using stage                         |
| Show_view_priv     | GLOBAL,CATALOG,DATABASE,TABLE                         | Privilege for show create view                    |
+--------------------+-------------------------------------------------------+---------------------------------------------------+
12 rows in set (0.06 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run feut

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
