### PR TITLE
[Fix](Typo) fix some typo

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Comment by GoGoWen** [comment]
run buildall

**Comment by GoGoWen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request closed without merging**
