### PR TITLE
[fix](decimal) change log fatal to log warning to avoid code dump on decimal type

### PR DESCRIPTION
**Pull request by liaoxin01**
# Proposed changes

Issue Number: close #xxx

## Problem summary

cherry-pick from: #14150

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
buildall

**Comment by yiguolei** [comment]
I think we should use log fatal here, because it will return a wrong result when decimal overflow. If user is using insert into select to do ETL jobs, then data is wrong.

**Review by dataroaring — CHANGES_REQUESTED** [review]
add a config to enable LOG(FATAL) and FATAL by default.

**Pull request closed without merging**
