### PR TITLE
[opt](partial update) Extract some common logic in partial update

### PR DESCRIPTION
**Pull request by bobhan1**

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM，nice work, plz add some description for this PR

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Pull request merged**
