### PR TITLE
[Bugfix](Mtmv)Fix mtmv meta load failed

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem summary
MTMV meta load fail since meta was public to the CI System
```
2023-04-12 20:11:46,606 WARN (main|1) [DorisFE.start():188]
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:107) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.loadImage(Env.java:1680) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.initialize(Env.java:858) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.start(DorisFE.java:146) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.DorisFE.main(DorisFE.java:73) ~[doris-fe.jar:1.2-SNAPSHOT]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:104) ~[doris-fe.jar:1.2-SNAPSHOT]
	... 4 more
Caused by: java.lang.NegativeArraySizeException: -1
	at org.apache.doris.common.io.Text.readString(Text.java:414) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.mtmv.MTMVJobManager.read(MTMVJobManager.java:537) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.loadMTMVJobManager(Env.java:1950) ~[doris-fe.jar:1.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.doris.persist.meta.MetaReader.read(MetaReader.java:104) ~[doris-fe.jar:1.2-SNAPSHOT]
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
