### PR TITLE
[bugfix](clickhouse) fix datetime convert error.

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #xxx

https://github.com/apache/doris/discussions/26049

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
@zy-kkk PTAL

**Review by zy-kkk — CHANGES_REQUESTED** [review]
1. **Use of Existing Methods**: We have an existing method `DecimalDigits` that's specifically designed to extract precision from these types. It's generally more efficient and less error-prone than parsing the string manually. I would recommend leveraging this method for consistency and reliability.

2. **Exception Handling**: The current approach to handling the `NumberFormatException` assumes that any failure to parse the scale is due to a timezone being provided. This might not always be the case, and such an assumption could lead to incorrect type creation.

3. **Testing**: The PR currently lacks tests that cover the new logic paths. It's crucial to have tests in place to ensure that the new code works as expected and doesn't inadvertently break existing functionality.

Here's a rough sketch of how we could use the `DecimalDigits` method to simplify the parsing:

```java
        if (ckType.startsWith("DateTime")) {
            int scale = fieldSchema.getDecimalDigits();
            if (scale > JDBC_DATETIME_SCALE) {
                scale = JDBC_DATETIME_SCALE;
            }
            return ScalarType.createDatetimeV2Type(scale);
        }
```

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by liugddx** [comment]
image

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
