### PR TITLE
[fix](build index)Fix build index failed on renamed column (#42882)(#43246)(#43336)

### PR DESCRIPTION
**Pull request by qidaye**
bp #42882 #43246 #43336
We pick these PRs together because they all fix one problem and if not do so, the regression test won't be passed.

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Pull request merged**
