### PR TITLE
[fix](planner) fix unrequired slot bug when join node introduced by #25204

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

fix bug introduced by #25204

fix issue #35009

before fix, join node will retain some slots, which are not materialized and unrequired. 
join node need remove these slots and not make them be output slots.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
