### PR TITLE
[Bug](materialized-view) fix core dump on create materialized view when diffrent mv column have same reference base column

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
fix core dump on create materialized view when diffrent mv column have same reference base column
```cpp
*** SIGSEGV invalid permissions for mapped object (@0x7f8343550000) received by PID 74569 (TID 75284 OR 0x7f84e4fe1640) from PID 1129644032; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/src/doris/be/src/common/signal_handler.h:413
 1# os::Linux::chained_handler(int, siginfo*, void*) in /opt/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /opt/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /opt/jdk1.8.0_351/jre/lib/amd64/server/libjvm.so
 4# 0x00007F90F3149A60 in /lib64/libc.so.6
 5# doris::vectorized::AggregateFunctionsSingleValue<doris::vectorized::AggregateFunctionMaxData<doris::vectorized::SingleValueDataDecimal<doris::vectorized::Decimal<long> > > >::add(char*, doris::vectorized::IColumn const**, unsigned long, doris::vectorized::Arena*) const at /root/src/doris/be/src/vec/aggregate_functions/aggregate_function_min_max.h:532
 6# doris::MultiBlockMerger::merge(std::vector<std::unique_ptr<doris::vectorized::Block, std::default_delete<doris::vectorized::Block> >, std::allocator<std::unique_ptr<doris::vectorized::Block, std::default_delete<doris::vectorized::Block> > > > const&, doris::RowsetWriter*, unsigned long*) at /root/src/doris/be/src/olap/schema_change.cpp:150
 7# doris::VSchemaChangeWithSorting::_internal_sorting(std::vector<std::unique_ptr<doris::vectorized::Block, std::default_delete<doris::vectorized::Block> >, std::allocator<std::unique_ptr<doris::vectorized::Block, std::default_delete<doris::vectorized::Block> > > > const&, doris::Version const&, long, std::shared_ptr<doris::Tablet>, doris::RowsetTypePB, doris::SegmentsOverlapPB, std::shared_ptr<doris::Rowset>*) at /root/src/doris/be/src/olap/schema_change.cpp:612
 8# doris::VSchemaChangeWithSorting::_inner_process(std::shared_ptr<doris::RowsetReader>, doris::RowsetWriter*, std::shared_ptr<doris::Tablet>, std::shared_ptr<doris::TabletSchema>)::$_1::operator()() const at /root/src/doris/be/src/olap/schema_change.cpp:535
 9# doris::VSchemaChangeWithSorting::_inner_process(std::shared_ptr<doris::RowsetReader>, doris::RowsetWriter*, std::shared_ptr<doris::Tablet>, std::shared_ptr<doris::TabletSchema>) at /root/src/doris/be/src/olap/schema_change.cpp:579
10# doris::SchemaChange::process(std::shared_ptr<doris::RowsetReader>, doris::RowsetWriter*, std::shared_ptr<doris::Tablet>, std::shared_ptr<doris::Tablet>, std::shared_ptr<doris::TabletSchema>) at /root/src/doris/be/src/olap/schema_change.h:121
11# doris::SchemaChangeHandler::_convert_historical_rowsets(doris::SchemaChangeHandler::SchemaChangeParams const&) at /root/src/doris/be/src/olap/schema_change.cpp:1120
12# doris::SchemaChangeHandler::_do_process_alter_tablet_v2(doris::TAlterTabletReqV2 const&) in /opt/doris/be/lib/doris_be
13# doris::SchemaChangeHandler::process_alter_tablet_v2(doris::TAlterTabletReqV2 const&) at /root/src/doris/be/src/olap/schema_change.cpp:665
14# doris::EngineAlterTabletTask::execute() at /root/src/doris/be/src/olap/task/engine_alter_tablet_task.cpp:51
15# doris::StorageEngine::execute_task(doris::EngineTask*) at /root/src/doris/be/src/olap/storage_engine.cpp:1082
16# doris::AlterTableTaskPool::_alter_tablet(doris::TAgentTaskRequest const&, long, doris::TTaskType::type, doris::TFinishTaskRequest*) at /root/src/doris/be/src/agent/task_worker_pool.cpp:1726
17# doris::AlterTableTaskPool::_alter_tablet_worker_thread_callback() at /root/src/doris/be/src/agent/task_worker_pool.cpp:1692
18# doris::ThreadPool::dispatch_thread() in /opt/doris/be/lib/doris_be
19# doris::Thread::supervise_thread(void*) at /root/src/doris/be/src/util/thread.cpp:466
20# start_thread in /lib64/libpthread.so.0
21# clone in /lib64/libc.so.6
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.7 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17161942276 Bytes

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.89 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162241446 Bytes

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.83 seconds
 stream load tsv:          559 seconds loaded 74807831229 Bytes, about 127 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17161862846 Bytes

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.08 seconds
 stream load tsv:          538 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17161942214 Bytes

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run external

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
