### PR TITLE
[bugfix](index) Fix build index limitations

### PR DESCRIPTION
**Pull request by xiaokang**
## Proposed changes

Issue Number: close #xxx

1. skip existed index on column with different id on build index
2. allow build index for CANCELED or FINISHED state

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
