### PR TITLE
[fix](memory) Disable Jemalloc Hook

### PR DESCRIPTION
**Pull request by xinyiZzz**
### What problem does this PR solve?

fix:
```
*** Aborted at 1733734087 (unix time) try "date -d @1733734087" if you are using GNU date ***
*** Current BE git commitID: 43f06a5e26 ***
*** SIGSEGV address not mapped to object (@0x0) received by PID 1671420 (TID 1671420 OR 0x7f4f35f74ac0) from PID 0; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/doris_release/doris/be/src/common/signal_handler.h:421
 1# PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0] in /usr/local/jdk-17.0.2/lib/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/local/jdk-17.0.2/lib/server/libjvm.so
 3# 0x00007F4F34340400 in /lib64/libc.so.6
 4# je_arena_dalloc_promoted at ../src/arena.c:1277
 5# je_free_default at ../src/jemalloc.c:3014
 6# __pthread_create_2_1 in /lib64/libpthread.so.0
 7# os::create_thread(Thread*, os::ThreadType, unsigned long) in /usr/local/jdk-17.0.2/lib/server/libjvm.so
 8# JVM_StartThread in /usr/local/jdk-17.0.2/lib/server/libjvm.so
 9# 0x00007F4F0A96C918
```

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by coldWeather66260** [comment]
Building failed on my mac, it said can't find `mallctl` symbol. Because jemalloc's default prefix on macOS is "je_",  not "".
[from doc:](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md)
```
By default, the prefix is "", except on OS X, where it is "je_". On OS X, jemalloc overlays the default malloc zone, but makes no attempt to actually replace the "malloc", "calloc", etc. symbols.
```

**Comment by xinyiZzz** [comment]
> Building failed on my mac, it said can't find `mallctl` symbol. Because jemalloc's default prefix on macOS is "je_", not "". [from doc:](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md)
> 
> ```
> By default, the prefix is "", except on OS X, where it is "je_". On OS X, jemalloc overlays the default malloc zone, but makes no attempt to actually replace the "malloc", "calloc", etc. symbols.
> ```

Hi, @coldWeather66260, I forgot to check Mac compilation.

I reverted this PR https://github.com/apache/doris/pull/45534, you can try `USE_JEMALLOC=OFF ./build.sh --be` to compile on Mac

**Pull request merged**
