### PR TITLE
[refactor](catalog) move some package related to catalog

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Move some package and files related to multi-catalog.
No logic is changed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
