### PR TITLE
[fix](array-type) bugfix for array column with delete condition

### LINKED ISSUE #13360: [Bug] Array column with delete condition
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

latest-master

### What's Wrong?

BE crashed

### What You Expected?

fix

### How to Reproduce?

1. create table
```
CREATE TABLE `tbl` (
  `id` int(11) NULL,
  `c_array` array<int(11)> NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 2",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```
2. insert data
`insert into tbl values(1, NULL),(2,[12,3]),(3,[]),(4,NULL),(5,NULL);`

3. delete some rows
`delete from tbl  where c_array is null;`

4. select all rows, then BE crashed.
`select * from tbl;`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
# Proposed changes

Issue Number: close #13360

## Problem summary

fix for SQL with array column:
`delete from tbl  where c_array is null;`

more info please refer to https://github.com/apache/doris/issues/13360

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221015064013_clickbench_pr_29630.html

**Review by xy720 — DISMISSED** [review]
LGTM

**Comment by cambyzju** [comment]
> TeamCity pipeline, clickbench performance test result: the sum of best hot time: 40.02 seconds load time: 579 seconds storage size: 17154768600 Bytes https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020045618_clickbench_pr_31546.html
,
It seems this pr should not make performance degradation, only add some logic for ARRAY case and use UNLIKELY.

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 41.51 seconds
 load time: 586 seconds
 storage size: 17154768693 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221020201710_clickbench_pr_31932.html

**Pull request merged**
