### PR TITLE
[Log](load) change VLOG to INFO when write replica failing

### PR DESCRIPTION
**Pull request by sollhui**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by freemandealer** [comment]
run p0

**Comment by freemandealer** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by CalvinKirs — COMMENTED** [review]
trigger

**Pull request merged**
