### PR TITLE
[chore](fe) Fix typos in comments

### PR DESCRIPTION
**Pull request by tudouzhao**
## Proposed changes

Issue Number: no
correct some note errors

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luozenglin — APPROVED** [review]
LGTM

**Comment by tudouzhao** [comment]
run build all

**Comment by tudouzhao** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.42 seconds
 stream load tsv:          546 seconds loaded 74807831229 Bytes, about 130 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17161977787 Bytes

**Pull request merged**
