### PR TITLE
[session](cases)update session var for ENABLE_COMMON_EXPR_PUSHDOWN_FOR_INVERTED_INDEX with true

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
@amorynan  notice that test_index_no_need_read_data failed

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by amorynan** [comment]
run p0 10

**Comment by amorynan** [comment]
run p0

**Comment by hello-stephen** [comment]
run p0 10

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run external

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
