### PR TITLE
[test](migrate) move 3 cases from p2 to p0

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

- test_hive_schema_change
- test_hive_star_qualifier
- test_multi_langs

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external p0

**Comment by wsjz** [comment]
run external p0

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run external

**Review by Jibing-Li — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
