### PR TITLE
[Improve](load)Solve the problem of RoutineLoadTaskScheduler idling when there is no data

### PR DESCRIPTION
**Pull request by CalvinKirs**
Since the polling interval is 0, the CPU will be polled all the time when there is no data

Before and after comparison test, the CPU usage time is reduced by 2000 times

## Proposed changes

Issue Number: close #xxx

Set polling interval to 1 ms

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
