### PR TITLE
[fix](fqdn) Add UnknownHostException handle logic in FQDNManager to avoid that active ip could be incorrectly assigned to dead be or dead fe

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #xxx
1. if be is dead and be ip not changed by FQDNManager，A situation may occur that after a while the old ip is used by other new alive pod，this may cause two be share same ip which is unexpected.
2. when enable_fqdn is false, user can still set hostname in be when add backend  

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.6 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230311141626_clickbench_pr_112772.html

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by caiconghui** [comment]
run buildall

**Review by weizuo93 — APPROVED** [review]

**Pull request merged**
