### PR TITLE
[Ehancement](planner) Rewrite implicit cast to the predicates

### PR DESCRIPTION
**Pull request by Kikyou1997**
# Proposed changes

Issue Number: noinssue

## Problem Summary:

 During the analysis of BinaryPredicate, it will generate a CastExpr implicitly if the slot is in the below case:
  SELECT * FROM t1 WHERE t1.col1 = '1';
 col1 is integer column.
 
This will prevent the binary predicate from pushing down to OlapScan which would impact the performance.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — COMMENTED** [review]
please rebase to newest master

**Comment by Kikyou1997** [comment]
> please rebase to newest master

done

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
@EmmyMiao87 PTAL

**Comment by Kikyou1997** [comment]
@EmmyMiao87

**Review by morningman — APPROVED** [review]

**Pull request merged**
