### PR TITLE
[refactor] add reference path for source file from impala

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

According to the requirements of the APLv2, the referenced code needs to be marked with the path of the source code.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yangzhg — DISMISSED** [review]
LGTM

**Comment by Gabriel39** [comment]
`org.apache.doris.udf.JMXJsonUtil.java` and `org.apache.doris.monitor.jvm.JvmPauseMonitor` are also copied from Impala (branch-4.0 I guess)

**Review by EmmyMiao87 — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
> `org.apache.doris.udf.JMXJsonUtil` and `org.apache.doris.monitor.jvm.JvmPauseMonitor` are also copied from Impala (branch-4.0 I guess)

done

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
