### PR TITLE
[test](Nereids) turn on all test in scalar function w

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. turn on all test case in scalar function W except width_bucket(fix be bug in next PR)
2. turn off all test case for group_concat(distinct order by)
3. fix return nullable in TimestampArithmetic

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.52 seconds
 stream load tsv:          477 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230303043315_clickbench_pr_107753.html

**Comment by morrySnow** [comment]
run buildall

**Review by englefly — DISMISSED** [review]

**Review by jackwener — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
