### PR TITLE
[chore](build) Porting to Clang-16

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

~~Issue Number: close #xxx~~

## Problem summary

This PR ports the codebase to Clang-16.

Upgrade some third-party libraries:
1. Apache BRPC: 1.2.0 -> 1.4.0  (Some bugs are fixed and all patches for 1.2.0 can be removed.)
2. Boost: 1.73.0 -> 1.81.0  (Porting to Clang-16)
3. libclucene: 2.4.6 -> 2.4.8  (Porting to Clang-16)

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run p0

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
