### PR TITLE
[test](config) change desired_max_waiting_jobs in regression pipeline

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
