### PR TITLE
[fix](fe ut) fix unstable SystemInfoServiceTest

### PR DESCRIPTION
**Pull request by yujun777**
For a random alg,   (max -min) < 5%  is too unstable.  Make this diff bigger,  change it to 30%.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
