### PR TITLE
[improve](move-memtable) reduce default load stream per node to 2 for stream load

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

The previous default value `20` is too large, reduce it to `2`.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
