### PR TITLE
[Chore][Compile] fix compile fail on clang

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Comment by platoneko** [comment]
Due to the update in cast_to_string, P0 regression will fail when table has BIGINT field. A solution is:
截屏2022-07-17 下午6 31 15

**Comment by BiteTheDDDDt** [comment]
fixed on https://github.com/apache/doris/pull/10913

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
