### PR TITLE
[log](s3) print detailed error message when failed to access object storage

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Print detailed error message when failed to access object storage.

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
