### PR TITLE
[Bug](udtf) fix udtf core dump use as normal function

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

```
1. select my_udtf(1) will be coredump as it's can't execute like a normal function, must use with lateral view2. 
2. when drop a UDTF function, it's should remove two function, another is utdf_outer function.
```

udtf not in 2.1， not  need pick
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
