### PR TITLE
[minor](doc) update the doc for docker env and custom_lib dir

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

1. Update the doc for `apache/doris:build-env-for-2.0`
2. Update the doc for `custom_dir`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
