### PR TITLE
[pick](nereids) fix bug in case-when/if stats estimation (pick30265)

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
pick #30265 

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by hello-stephen** [comment]
run performance

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Pull request merged**
