### PR TITLE
[chore](third-party) Bump the version of hyperscan

### LINKED ISSUE #292: Build Error with 5.4.0
The latest release dos not longer build in my debian packaging environment:
I am building with default flags in Debian Testing.

Here is a snipped of the errors that occur a lot during build:

```
/home/user/tmp/hyperscan-5.4.0/src/hwlm/hwlm.c:136: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(stream.c.o): in function `roseCountingMiracleScan':
/home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:68: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(stream.c.o): in function `roseCountingMiracleScanShufti':
/home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:118: undefined reference to `avx2_memcpy'
/usr/bin/ld: /home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:118: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(stream.c.o): in function `roseCountingMiracleScan':
/home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:68: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(program_runtime.c.o): in function `roseCountingMiracleScan':
/home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:68: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(program_runtime.c.o):/home/user/tmp/hyperscan-5.4.0/src/rose/counting_miracle.h:118: more undefined references to `avx2_memcpy' follow
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `print_database_string':
/home/user/tmp/hyperscan-5.4.0/src/database.c:405: undefined reference to `avx2_snprintf'
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `hs_serialize_database':
/home/user/tmp/hyperscan-5.4.0/src/database.c:86: undefined reference to `avx2_memset'
/usr/bin/ld: /home/user/tmp/hyperscan-5.4.0/src/database.c:105: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `hs_deserialize_database_at':
/home/user/tmp/hyperscan-5.4.0/src/database.c:227: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `db_copy_bytecode':
/home/user/tmp/hyperscan-5.4.0/src/database.c:196: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `hs_deserialize_database':
/home/user/tmp/hyperscan-5.4.0/src/database.c:275: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(database.c.o): in function `db_copy_bytecode':
/home/user/tmp/hyperscan-5.4.0/src/database.c:196: undefined reference to `avx2_memcpy'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:956: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough16_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:968: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1073: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `core2_nfaExecGough16_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1075: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.a(mpv.c.o): in function `nfaExecMpv_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/mpv.c:886: undefined reference to `core2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:956: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough16_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:968: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1073: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `corei7_nfaExecGough16_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1075: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.a(mpv.c.o): in function `nfaExecMpv_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/mpv.c:886: undefined reference to `corei7_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:956: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough16_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:968: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `nfaExecGough8_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1073: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(gough.c.o): in function `avx2_nfaExecGough16_queueInitState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/gough.c:1075: undefined reference to `avx2_memset'
/usr/bin/ld: ../lib/libhs.a(mpv.c.o): in function `nfaExecMpv_initCompressedState':
/home/user/tmp/hyperscan-5.4.0/src/nfa/mpv.c:886: undefined reference to `avx2_memset'
collect2: error: ld returned 1 exit status

```

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

~~Issue Number: close #xxx~~

The latest version fixed [hyperscan#292](https://github.com/intel/hyperscan/issues/292)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run p0

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
