### PR TITLE
[feature](binlog) Add ingest_binlog/http_get_snapshot limit download speed && Add async ingest_binlog

### PR DESCRIPTION
**Pull request by JackDrogon**
## Proposed changes

Add ingest_binlog/http_get_snapshot limit download speed && Add async ingest_binlog

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Comment by JackDrogon** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
