### PR TITLE
[fix](case) include some case and adjust expect result

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run compile

**Comment by hello-stephen** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
