### PR TITLE
[Enhancement] add more metrics #11214

### LINKED ISSUE #11214: [Enhancement] add more metrics
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

There are dozens of Doris metrics are used in Meituan alone but can be open-sourced.

### Solution

* transaction metrics(count, latency, publish)
* query rpc metrics(count, latency, size, drill down to each BE)
* query metrics(drill down to each DB)
* thrift rpc metrics(drill down to each BE)
One concern is that when there are too many DB/BE, there may be a huge cost on these metrics. We may add switch configs on these metrics.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ccoffline**
# Proposed changes

Issue Number: close #11214

## Problem summary

* Add `AutoMappedMetric` to measure dynamic object.
* Add query instance and rpc metrics
* Add thrift rpc metrics
* Add txn metrics
* Reorganize metrics init routine.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

### CODE REVIEW

**Comment by morningman** [comment]
Please update the document:
```
docs/zh-CN/docs/admin-manual/maint-monitor/monitor-metrics/metrics.md
```

**Comment by ccoffline** [comment]
> Please update the document:

done

**Review by morningman — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
