### PR TITLE
[Improve](Schema Change) avoid printing stack trace when check __DORIS_ROW_STORE_COL__

### PR DESCRIPTION
**Pull request by eldenmoon**
This may result misunderstanding

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by lxr599 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
@eldenmoon pls add a testcase

**Comment by eldenmoon** [comment]
> @eldenmoon pls add a testcase

it' an optimize for log, no need for a test

**Pull request merged**
