### PR TITLE
[Feature] Support fe login using sql tools when no be is available.

### PR DESCRIPTION
**Pull request by arthur-zhang**
When no backend(be) available, eg first time before setup or all be is down, we cannot login to fe using most sql tools, eg datagrip, querious.

This is because these tools call `select version()` or  `select @@version_comment …` right after login, when there is no backend available, the login will fail.

I make this pr to support login when no be available, so we can add backend or modify some configuaration using GUI sql tools, especially the first setup time.

This pr is working at precondition that，sql tools only query very simple information that fe can handle, there is no need to send the request to be.

So I check the query type and BE status, if we can handle the query and no BE is available, we will intercept and process in fe.

some screenshots

Jietu20210703-175414

Jietu20210703-175451

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by morningman** [comment]
Thanks for your PR. This is indeed a problem.
But I think it could be better to handle this situation in `StmtExecutor.handleQueryStmt()`.
Because here we have analyzed the statement, and all constant exprs has been calculated, so that we can simple check
if there is no table ref in statement and all select items are constant literal, and there is no alive backend, then return the result by FE.
This can cover more situation than only handle `select version()` and `select @@variables`;

**Comment by arthur-zhang** [comment]
> Thanks for your PR. This is indeed a problem.
> But I think it could be better to handle this situation in `StmtExecutor.handleQueryStmt()`.
> Because here we have analyzed the statement, and all constant exprs has been calculated, so that we can simple check
> if there is no table ref in statement and all select items are constant literal, and there is no alive backend, then return the result by FE.
> This can cover more situation than only handle `select version()` and `select @@variables`;

Good suggestion，I will move the code to `handleQueryStmt` and make it more general

**Comment by arthur-zhang** [comment]
when this pr is working, constant exprs will be handled in fe when no be is available. eg

```
select version()
select now()
SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
```

the following GUI sql tools will work without be.

- DataGrip
- SQLPro
- Navicat for MySQL
- Querious

and can handle those query that is constant at 

some initial sql to use 
datagrip :
```
SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
```

querious:
```
select @@version_comment limit 1
```

**Comment by arthur-zhang** [comment]
all done

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
