### PR TITLE
[bugfix](testcase)add java error log output

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

In the testcase pipeline, this spark-connector case has a 4% chance of error, but since there is no error log, the cause of the error cannot be located. 
Therefore, an error log is added to facilitate problem location later.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Review by morningman — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
