### PR TITLE
[Fix](multi-catalog) Fix hadoop short circuit reading can not enabled in some environments.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Fix hadoop short circuit reading can not enabled in some environments.
- Revert #21430 because it will cause performance degradation issue.
- Add `$HADOOP_CONF_DIR` to `$CLASSPATH`.
- Remove empty `hdfs-site.xml`. Because in some environments it will cause hadoop short circuit reading can not enabled.
- Copy the hadoop common native libs(which is copied from https://github.com/apache/doris-thirdparty/pull/98
) and add it to `LD_LIBRARY_PATH`. Because in some environments `LD_LIBRARY_PATH` doesn't contain hadoop common native libs, which will cause hadoop short circuit reading can not enabled.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Modify document to explain the logic

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
> Modify document to explain the logic



> Modify document to explain the logic

ok

**Comment by kaka11chen** [comment]
> Modify document to explain the logic

ok

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wsjz — APPROVED** [review]
LGTM

**Pull request merged**
