### PR TITLE
[feature](Nereids): Pushdown TopN through Union

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

```
topn
-> Union All 
  -> child plan1
  -> child plan2
  -> child plan3

rewritten to

topn
-> Union All 
 -> topn
  -> child plan1
 -> topn
  -> child plan2
 -> topn
  -> child plan3
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by keanji-x — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
