### PR TITLE
[chore](workflow) 2/2, auto trigger "License Check" and "BE Code Formatter" instead…

### PR DESCRIPTION
**Pull request by hello-stephen**
… of after approval

refer to: https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by shuke987 — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
