### PR TITLE
[UnitTest] Refactor BE unit test script

### LINKED ISSUE #4265: [UnitTest] Refactor the BE unit test script
**Is your feature request related to a problem? Please describe.**

The script that currently runs BE unit test `run-ut.sh` is inconvenient to use,
and the developer must separately declare the unit test that needs to be run in the script.
And the script does not produce a single test result report.

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Refactor the `run-ut.sh`

1. Rename run-ut.sh to run-be-ut.sh
2. Find all test files from build dir instead of declaring separately in the script
3. Add gtest output to collect the result of unit test.
4. Support `run-be-ut.sh --run test1` to run the specified test.

Also comment out some unit test which are not running anymore.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

- [x] I have create an issue on (Fix #4265), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes

### CODE REVIEW

**Comment by WingsGo** [comment]
Hi, @morningman Can we support run specify UT like sh run-be-test.sh --run xxx_test?

**Comment by morningman** [comment]
> Hi, @morningman Can we support run specify UT like sh run-be-test.sh --run xxx_test?

Ok, I will add it

**Review by yangzhg — APPROVED** [review]
LGTM

**Review by yangzhg — COMMENTED** [review]
I suggest the default operation of `run-be-ut.sh` is build and run all test  instead of only build

**Comment by morningman** [comment]
> est instead of only build

I'm not sure changing the default behavior is ok. This script has same behavior like `run-fe-ut.sh`

**Pull request merged**
