### PR TITLE
[FIX](complex-type) fix agg table with complex type with replace state

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
when we use replace agg state which we only supported in complex type, fix be not implement replace_column_data with agg value to iterator . so we will got a be core below this
```
F20230924 10:40:22.801700 1080720 column_array.h:234] replace_column_data_default not implemented
*** Check failure stack trace: ***
    @     0x564542ab01e6  google::LogMessage::SendToLog()
    @     0x564542aac7b0  google::LogMessage::Flush()
    @     0x564542ab0a29  google::LogMessageFatal::~LogMessageFatal()
    @     0x56452f2d911a  doris::vectorized::ColumnArray::replace_column_data_default()
    @     0x56452f41fc76  doris::vectorized::ColumnNullable::replace_column_data()
    @     0x5645416c26b3  doris::vectorized::VerticalBlockReader::_copy_agg_data()
    @     0x5645416c1725  doris::vectorized::VerticalBlockReader::_update_agg_data()
    @     0x5645416c15f6  doris::vectorized::VerticalBlockReader::_append_agg_data()
    @     0x5645416c0b27  doris::vectorized::VerticalBlockReader::_agg_key_next_block()
    @     0x564520b3dce7  doris::vectorized::VerticalBlockReader::next_block_with_aggregation()
    @     0x564520b2d28b  doris::Merger::vertical_compact_one_group()
    @     0x564520b3054a  doris::Merger::vertical_merge_rowsets()
    @     0x564520b4e5e9  doris::Compaction::do_compaction_impl()
    @     0x564520b4c03f  doris::Compaction::do_compaction()
    @     0x564520ce7947  doris::CumulativeCompaction::execute_compact_impl()
    @     0x564520b4b77b  doris::Compaction::execute_compact()
    @     0x564520de8bd5  doris::Tablet::execute_compaction()
    @     0x564520851d76  doris::StorageEngine::_submit_compaction_task()::$_0::operator()()
    @     0x564520851bf5  std::__invoke_impl<>()
    @     0x564520851b95  _ZSt10__invoke_rIvRZN5doris13StorageEngine23_submit_compaction_taskESt10shared_ptrINS0_6TabletEENS0_14CompactionTypeEbE3$_0JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES9_E4typeEOSA_DpOSB_
    @     0x5645208519ad  std::_Function_handler<>::_M_invoke()
    @     0x56451ea937a3  std::function<>::operator()()
    @     0x564521e63279  doris::FunctionRunnable::run()
    @     0x564521e4f01e  doris::ThreadPool::dispatch_thread()
    @     0x564521e759f4  std::__invoke_impl<>()
    @     0x564521e758cd  std::__invoke<>()
    @     0x564521e75855  _ZNSt5_BindIFMN5doris10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x564521e756fe  std::_Bind<>::operator()<>()
    @     0x564521e75615  std::__invoke_impl<>()
    @     0x564521e755b5  _ZSt10__invoke_rIvRSt5_BindIFMN5doris10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @     0x564521e752dd  std::_Function_handler<>::_M_invoke()
    @     0x56451ea937a3  std::function<>::operator()()
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run p1

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
