### PR TITLE
[Chore](arm) Support auto-SIMD on arm and refactor compilation docs

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by zclllyybb** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
