### PR TITLE
[opt](nereids) modify cbo statistics in filter and scan

### PR DESCRIPTION
**Pull request by yx-keith**
## Proposed changes

Issue Number: (https://github.com/apache/doris/issues/34946)

The entire discussion process can be referred to this issue：https://github.com/apache/doris/issues/34946

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
hi keith,
do you notice that in JoinEstimation, if child.rowCount is 0, estimator regard the input row count as 1.
please refer to:
https://github.com/apache/doris/blob/f53cf052d84335c09b2680259b1366343fc90c9a/fe/fe-core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java#L198

**Comment by yx-keith** [comment]
> hi keith, do you notice that in JoinEstimation, if child.rowCount is 0, estimator regard the input row count as 1. please refer to:
> 
> https://github.com/apache/doris/blob/f53cf052d84335c09b2680259b1366343fc90c9a/fe/fe-core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java#L198

>hi minghong, in JoinEstimation,  outputRowCount of joinNode is calculated as 1, this will cause the result of Join to be considered as only one row of data in the plan, and be distributed using broadcast
core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java#L144

**Review by englefly — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by yx-keith** [comment]
run p0

**Comment by yx-keith** [comment]
run p0

**Comment by yx-keith** [comment]
run p0

**Pull request closed without merging**
