### PR TITLE
[fix](partial update) Fix session variable `enable_unique_key_partial_update` will affect the behavior of insert statement when the target table is not unique table

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes
1. the session variable `enable_unique_key_partial_update` should be ignored if the target table is not unique table.
2. check the partial update constraints in the following order:
- if the target table is a merge-on-read table, report "Partial update is only allowed on unique table with merge-on-write enabled."
- if the users don't specify the columns, report "You must explicitly specify the columns to be updated when updating partial columns using the INSERT statement."
- if there exist key column that doesn't be contained in the specified columns, report "Partial update should include all key columns, missing: xxx"
3. fix some bugs.
## Further comments
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run clickbench

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
