### PR TITLE
[fix](LOG)change printStackTracker to LOG 

### PR DESCRIPTION
**Pull request by vinlee19**
## Proposed changes

Issue Number: close #xxx

issue: Delivering code in production with debug features activated is security-sensitive.  
reason:
> Throwable.printStackTrace(...) prints a Throwable and its stack trace to System.Err (by default) which is not easily parseable and can expose sensitive information.

solution:
> Thus,Loggers should be used (instead of printStackTrace) to print throwables

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
We can add restrictions to checkstyle to prohibit the use of this method

**Comment by vinlee19** [comment]
run buildall

**Review by liugddx — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
