### PR TITLE
[regression](baidu-case)merge baidu-case from master

### PR DESCRIPTION
**Pull request by zgxme**
## Proposed changes
run baidu-case regression on the branch2.0

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]

**Comment by zgxme** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
