### PR TITLE
[enhancement](merge-on-write) refine tablet meta_lock usage and add some trace log

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

1. change to read lock while `save_meta()`, in the method `_delete_stale_rowset_by_version`.
2. make TRACE_TABLET_LOCK_THRESHOLD shorter
3. print detailed trace if update_delete_bitmap takes too long time
4. return on `_load_rowset_segments()` error status
5. print detailed trace if save_meta too slow

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run p0

**Review by dataroaring — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
