### PR TITLE
[enhancement](log) add config for storage to reduce stacktrace log on fe

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

Issue Number: close #xxx

in some cases, for example, repo use aws_token and token is expired. if RepositoryMgr exec repo ping, will get a lot of stacktrace info in fe.log. 

add a fe config print_error_no_stacktrace, user can print error no stacktrace, only exception message.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Review by xy720 — DISMISSED** [review]
LGTM

**Review by lide-reed — DISMISSED** [review]
LGTM

**Review by JackDrogon — CHANGES_REQUESTED** [review]
not a good idea

**Comment by JackDrogon** [comment]
If you want to address privacy issues, please do so in the case itself. Directly disabling the printing of exceptions won't solve it, such as direct fields in the log containing. And printing exceptions is a valid debugging tool

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run beut

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run clickbench-new

**Comment by hello-stephen** [comment]
run feut

**Comment by hello-stephen** [comment]
run clickbench

**Comment by hello-stephen** [comment]
run beut

**Comment by nextdreamblue** [comment]
run feut

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Pull request closed without merging**
