### PR TITLE
[chore](ci) fix case and script about cloud_p0

### PR DESCRIPTION
**Pull request by hello-stephen**
1. fix case map_uniq_with_local_tvf in cloud_p0
2. enable broker load test in p1
3. fix case fail of test_s3_load_parallelism
4. fix coredump collect in cloud_p0

### CODE REVIEW

**Comment by hello-stephen** [comment]
run compile

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
