### PR TITLE
[Fix](flexible partial update) Don't set default value for `TOlapTableIndexSchema.unique_key_update_mode`

### PR DESCRIPTION
**Pull request by bobhan1**
### What problem does this PR solve?

Problem Summary:

If we explicitly set default value for field `unique_key_update_mode` in `.thirft` file, `__isset.unique_key_update_mode` will always be `true`. So `OlapTableSchemaParam::init_unique_key_update_mode` will fail to set `_unique_key_update_mode` correctly if it receive a request from old version FE.

### Check List (For Committer)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [x] Other reason : has been tested in rolling upgrade env

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [ ] Confirm test cases
- [x] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Comment by zhannngchen** [comment]
If there is no test, plz explain why in your PR description.

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]

**Pull request merged**
