### PR TITLE
[chore](regression test) mv test_report_version_missing to p1

### PR DESCRIPTION
**Pull request by yujun777**

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by hello-stephen — CHANGES_REQUESTED** [review]

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run cloud_p0

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Pull request merged**
