### PR TITLE
[feature](agg) add aggregation function 'bitmap_agg'

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

This function can be used to replace `bitmap_union(to_bitmap(expr))`， because bitmap_union(to_bitmap(expr)) need create many  many small bitmaps firstly and then merge them into a single bitmap. 
bitmap_agg will convert the column value into a bitmap directly. Its performance is better than bitmap_union(to_bitmap(expr)) . In our test , there is about 30% improvement.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
