### PR TITLE
[fix](scanner) Check query status when iterating through rowsets and segments

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
To avoid scanner can not exit when doing large IO.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run cloud p0

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
