### PR TITLE
[Doris On ES] [Bug-Fix] Fix lte and gte error expression

### PR DESCRIPTION
**Pull request by wuyunfeng**

### CODE REVIEW

**Comment by wuyunfeng** [comment]
ISSUE： https://github.com/apache/incubator-doris/issues/2852

**Comment by kangkaisen** [comment]
es_query_builder_test also need update?

**Comment by wuyunfeng** [comment]
@kangkaisen  Thanks.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
