### PR TITLE
[test](inverted index) TopN Optimization Test for Composite Key.

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. Prevent incorrect use of composite keys in TopN optimization, which could lead to performance degradation.

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
