### PR TITLE
[fix](Nereids): remove `DataV2Type` in ConvertTz SIGNATURES

### PR DESCRIPTION
**Pull request by jackwener**
# Proposed changes

we shouldn't add `DateV2` in `SIGNATURES`, because when meet `DateV2`, it will cast to `DateTimeV2Type` implicitly.

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.13 seconds
 load time: 507 seconds
 storage size: 17122819584 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230128142720_clickbench_pr_85741.html

**Comment by BiteTheDDDDt** [comment]
On the one hand, you should make sure that the signature in nereids is consistent with the signature in doris_builtins_functions.py. On the other hand, whether a function like DayCeil should remove the datev2 type signature, I'm not sure.

**Review by BiteTheDDDDt — CHANGES_REQUESTED** [review]
Still need to investigate, this pr needs to wait for a while

**Comment by BiteTheDDDDt** [comment]
In my opinion, `convert_tz` does not need `datev2` as an input parameter, but `day_ceil` accepts datev2 is reasonable. You can remove them all temporarily, and we will investigate what is wrong with the implementation of `day_ceil` in `be` later.

For this pr, I think you'd better make some changes in `doris_builtins_functions.py` to ensure that the function signatures of nereids and old planner are consistent.

**Comment by Gabriel39** [comment]
Agree with @BiteTheDDDDt . Functions like `DayCeil ` still need to accept datev2 as argument instead of datetimev2.

**Review by BiteTheDDDDt — APPROVED** [review]
lgtm

**Pull request merged**
