### PR TITLE
[regression-test] add list partition case and multi partition keys case

### PR DESCRIPTION
**Pull request by zhangy5**
## Proposed changes

add partition table case:
1. add list partition p0 case
2. add multi partition keys p0 case

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangy5** [comment]
run buildall

**Comment by zhangy5** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Pull request merged**
