### PR TITLE
[feature](doris compose) support multiple disk types and other improvement

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

support multiple disk types

show cluster owner;

add usage example;

CREATE time convert to local timezone;

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
update hint

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
