### PR TITLE
[fix](config) increase JVM memory of BE

### PR DESCRIPTION
**Pull request by BePPPower**
Because `test_trino_hive_tpch_sf1_parquet` case may cause BE JVM OOM, we increase JVM memory of BE.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
change `JAVA_OPTS` for jdk8 too

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by suxiaogang223 — APPROVED** [review]

**Pull request merged**
