### PR TITLE
[improvement](storage) Add more detailed timer on SegmentIter in profile

### PR DESCRIPTION
**Pull request by zenoyang**
# Proposed changes

- Fix some profile indicators of vectorized query were not counted: ScanTime, VectorPredEvalTime
- Add some metrics for analyzing storage layer performance consumption: LazyReadTime, PredColumnReadTime, ShortPredEvalTime, OutputColumnTime

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wangbo** [comment]
1 Timer itself has an overhead, I don't think we need so many Timer by default and collect it in Prod Env.
We can use GenericTimer when we meet obvious performance bottleneck in Prod Env or Test Env.
We'd better not add more timer than before.
So I suggest you just add ```ShortPredEvalTime```  or using ```PredEvalTime``` to cover short and vec evaluation

2 ```GeneralDebugTimer```  is open by default currently, I think we can disable it by default.

**Comment by zenoyang** [comment]
> 1 Timer itself has an overhead, I don't think we need so many Timer by default and collect it in Prod Env. We can use GenericTimer when we meet obvious performance bottleneck in Prod Env or Test Env. We'd better not add more timer than before. So I suggest you just add `ShortPredEvalTime` or using `PredEvalTime` to cover short and vec evaluation. For other Timer, you can disable it by default or using `GeneralDebugTimer` instead. Explaining how to Timer `SegmentIter` is helpful.
> 
> 2 `GeneralDebugTimer` is open by default currently, I think we can disable it by default.

I think there is a scenario that needs to be considered. For example, a certain sql query of a user in an online environment is slow. If the profile is relatively detailed, we can directly use the online environment to analyze the profile through the profile to quickly locate the bottleneck. Instead of adding relevant profile indicators by changing the code, then compiling, deploying, and analyzing the problem.
Of course, the timer itself has an overhead, so there needs to be a trade-off. ReadColumn is a very time consuming operation (shown below), please confirm whether it is necessary?

```
- BlockLoadTime: 8s695ms
- PredColumnReadTime: 2s536ms
- LazyReadTime: 5s422ms
- ShortPredEvalTime: 433.292ms
```

I will delete other new timers and turn off GeneralDebugTimer by default.

**Comment by wangbo** [comment]
The purpose of this PR to help locate and analyze the query bottleneck is good.
I will do some code refactor to make lazy materialization easier to understand.
So this PR can be merged first.
Performance test would be will be included in my next PR.

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by zenoyang** [comment]
> The purpose of this PR to help locate and analyze the query bottleneck is good. I will do some code refactor to make lazy materialization easier to understand. So this PR can be merged first. Performance test would be will be included in my next PR.

ok, thanks

**Pull request merged**
