### PR TITLE
[refactor](Nereids): unify all `replaceNamedExpressions`

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

Use a unified function `replaceNamedExpressions ` instead of implementing it yourself repeatedly.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run p0

**Comment by jackwener** [comment]
run p0

**Comment by jackwener** [comment]
run p0

**Review by keanji-x — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
