### PR TITLE
Allow user to ignore the broken disk

### PR DESCRIPTION
**Pull request by kangkaisen**
For https://github.com/apache/incubator-doris/issues/2754

### CODE REVIEW

**Review by imay — DISMISSED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
`check_dir_existed()` does not defined?

**Comment by kangkaisen** [comment]
> `check_dir_existed()` does not defined?

`check_dir_existed` is defined in `be/src/olap/utils.cpp`

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
