### PR TITLE
[fix](case) Update regression-conf.groovy

### PR DESCRIPTION
**Pull request by hello-stephen**
ds_rf95ds_rf16 -> ds_rf95,ds_rf16
and disable case test_sql_block_rule

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
