### PR TITLE
[Fix](metahelper)Filename regex validation only checks if the filename is valid.

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
The file name may also be VERSION. Considering the code maintainability, we will only check whether the file name is legal.

### CODE REVIEW

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run cloud_p0

**Pull request merged**
