### PR TITLE
[Enhancement](table) add information_schema.parameters table

### LINKED ISSUE #19626: [Enhancement] adding information_schema.parameters table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

可参考：

https://dev.mysql.com/doc/refman/8.0/en/information-schema-parameters-table.html

这只是一个虚拟表，用于兼容mysql，不需要存储实际信息。

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zhiyu-h**
# Proposed changes

Issue Number: close #19626

## Problem summary

This is a Virtual Table to be compatible with MySQL's INFORMATION_ SCHEMA PARAMETRS.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Yukang-Lian — COMMENTED** [review]
plz add some regression tests.

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Please add regression test for this table

**Review by morningman — DISMISSED** [review]
LGTM

**Pull request closed without merging**
