### PR TITLE
[branch-2.0](schema change) opt cooldown data schema change

### PR DESCRIPTION
**Pull request by DarvenDuan**
## Proposed changes

This PR solves 3 problems of schema change for cooldown data:

1. Schema change will build a new tablet for base tablet, and all replicas do this separately, so the cooldown data SC writes all replicas to the remote storage, But the cooldown rowsets just need one master replica to cooldown, the other replicas follow the master. To optimize this issue, Doris can just write the new rowsets to the local storage, and the tablet will cooldown this rowsets automatically for just one mater replica.

3. In schema change job and rollup job, FE generates createReplicaTask, which specifies the storage policy of the tablets to create, table's storage policy may be empty if we just set the partitions' storage policy, so we use partition's storage policy instead of table.

5. checks the target tablets in the loop of data conversion, and terminates the data conversion thread if the tablet is been dropped.

### CODE REVIEW

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run p0

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run feut

**Review by GoGoWen — APPROVED** [review]
LGTM

**Pull request merged**
