### PR TITLE
[fix](s3) fix invalid s3 properties checking logic

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes
Introduced from #35515

1. Fix invalid `to_int()` method logic
2. Remove unnecessary properties when creating s3 resource
    Before, after recreating s3 resource, there will be some extra properties being added to the resource properties,
    such as AWS_ACCESS_KEY, but this keys are only for s3 client on BE side, don' t needed when ping s3.
    But it will add some invalid properties such as `AWS_TOKEN=null`

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by kaka11chen — DISMISSED** [review]
LGTM

**Review by platoneko — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by platoneko — APPROVED** [review]

**Pull request merged**
