### PR TITLE
[typo](doc) Fixed some description of date_format function documentation

### PR DESCRIPTION
**Pull request by bingquanzhao**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bingquanzhao** [comment]
> Please modify the title format, refer to https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification

done

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
