### PR TITLE
[test](inverted index)Add cases for inverted index format v2

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

1. Add exception when trying to change index storage format
2. Add test cases for index format v2
    - test_add_build_index_with_format_v2
    - test_create_table_with_format_v2
    - test_cumulative_compaction_with_format_v2
    - test_drop_column_with_format_v2
    - test_drop_index_with_format_v2
    - test_index_change_format
    - test_mor_table_with_format_v2
    - test_mow_table_with_format_v2
    - test_recover_with_format_v2
    - test_rename_column_with_format_v2
    - test_single_replica_compaction_with_format_v2
3. There is a test case `test_rename_column_with_format_v2` for #38079

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run performance

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run p0

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
