### PR TITLE
[fix](load) check return value of TabletManager::get_tablet

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
