### PR TITLE
[fix](move-memtable) all sinks wait stream close for load timeout

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Reverts commit ae0220217ba4f3492f6a594a6a0131c768fc3c99.
Also set stream close wait to load timeout.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
