### PR TITLE
[fix](regression test) fix test_abort_txn_by_fe

### PR DESCRIPTION
**Pull request by yujun777**
1. fix regression test test_abort_txn_by_fe;

2. delete duplicated suites which just diff ClusterOptions.cloudMode = true/false,  no needn't.  ClusterOptions.cloudMode = null always support both mode;

3. improvement:  when run a docker suite with ClusterOptions.cloudMode == null,   if there's no an external doris cluster,  it will run both in cloud and not_cloud mode;

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run cloud_p0

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
