### PR TITLE
[fix](functions) fix be crash for function random_bytes and mark_first/last_n

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

fix crash when:
`random_bytes` gets negative input
`mark_first/last_n` gets negative 2nd arg input.

and make `mark_first/last_n` support literal only for 2nd arg

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by mrhhsg — DISMISSED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by mrhhsg — APPROVED** [review]
LGTM

**Pull request merged**
