### PR TITLE
[Update](inverted index) set default inverted index storage format to v2

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

This pull request changes the default storage format for inverted indexes to V2. The V2 format enhances efficiency by merging all index files within a single segment into one file. This update aims to reduce IO cost when writing inverted index files, especially for cloud mode.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
run p0

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
