### PR TITLE
[fix](inverted index)Support rename column with inverted index (#38079)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

backport #38079

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run feut

**Comment by qidaye** [comment]
run p0

**Comment by qidaye** [comment]
run p0

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
