### PR TITLE
[test](regression) add cases for partial update with sequence_type

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Add cases: stream load partial update with sequence_type

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
This PR is after #22250

**Comment by dataroaring** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
