### PR TITLE
[fix](decimalv2) fix decimalv2 agg errors (#29246)

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Pick from #29246

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Comment by jacktengg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Comment by jacktengg** [comment]
run clickbench

**Comment by jacktengg** [comment]
run clickbench

**Pull request merged**
