### PR TITLE
[opt](ES catalog) Add 3 connect attempts per node

### PR DESCRIPTION
**Pull request by qidaye**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
run pipelinex_p0

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
