### PR TITLE
[refactor](jdbc catalog) split jdbc executor for different data sources (step-1)

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #xxx

In order to better manage the data reading and writing of each Jdbc data source, I split the current JdbcExecutor according to the data source. This is the first step to split the MySQLJdbcExecutor. When all subsequent data sources are split, I Unnecessary methods in BaseJdbcExecutor will be removed

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Comment by liugddx** [comment]
Are you planning to split the task and then distribute it to different be for reading?

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]

**Pull request merged**
