### PR TITLE
[fix](resize)fix array/map resize impl missing data resize

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
backport: https://github.com/apache/doris/pull/41595
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by xiaokang — COMMENTED** [review]
pick unit test

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
> pick unit test

rewrite a new test for resize

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
