### PR TITLE
[enhancement](rewrite) add OrToIn rule && fix expr clone problems

### LINKED ISSUE #12871: [Enhancement](rewrite) support Or to In rule
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

support Or to In rewrite rule :

for example, sql `select * from test_tbl where a = 1 or a = 2 or a in (3, 4)` should rewrite to `select * from test_tbl where a in (1,2,3,4)`

### Solution

support Or to In rewrite rule :

for example, sql `select * from test_tbl where a = 1 or a = 2 or a in (3, 4)` should rewrite to `select * from test_tbl where a in (1,2,3,4)`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Henry2SS**
# Proposed changes

Issue Number: close #12871

## Problem summary

1. support Or to In rewrite rule
2. fix Expr clone problems. It should create a new object, or it will always be shallow-copy.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
3. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Henry2SS** [comment]
tested locally.

**Comment by Henry2SS** [comment]
1. fe unit-tests passed locally.
2. compiled and manually tested function passed 

test results:

image

image

**Review by caiconghui — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.37 seconds
 load time: 433 seconds
 storage size: 17123356915 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221212101237_clickbench_pr_62009.html

**Review by caiconghui — APPROVED** [review]
LGTM

**Comment by wangshuo128** [comment]
It seems this PR introduced unstable test, please see http://43.132.222.7:8111/viewLog.html?buildId=69682&buildTypeId=Doris_Doris_FeUt
cc @caiconghui @morrySnow

**Pull request merged**
