### PR TITLE
[docs](stats) add sidebars for stats docs

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

add sidebars for new docs in pr: https://github.com/apache/doris/pull/27176 https://github.com/apache/doris/pull/27461

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run extensions

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
