### PR TITLE
[fix](dynamic partition) partition create failed after alter distributed column

### LINKED ISSUE #10811: [Enhancement] should allow adding partitions when distribution columns' comment had been modified
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

For now, when distribution columns' comment had been modified, dynamic partition will not be allowed to add a new partition.

In fact, only `name` and `type` of `Column` are necessary to be checked.

### Solution

modify the logic of checking

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/10811 https://github.com/apache/doris/issues/20405

This pr fix following two problems:

**Problem1**: Alter column comment make add dynamic partition failed inside issue [#10811](https://github.com/apache/doris/issues/10811)
1. create table with dynamic partition policy;
2. restart FE;
3. alter distribution column comment;
4. alter dynamic_partition.end to trigger add new partition by dynamic partition scheduler;
5. Then we got the error log, and the new partition create failed.
`dynamic add partition failed: errCode = 2, detailMessage =      Cannot assign hash distribution with different distribution cols. default is: [`id` int(11) NULL COMMENT 'new_comment_of_id'], db: default_cluster:example_db, table: test_2`

**Problem2**: rename distributed column, make old partition insert failed. inside https://github.com/apache/doris/issues/20405

**The key point of the reproduce steps is `restart FE`.**

It seems all versions will be affected, include master and lts-1.1 and so on.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run p0

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by yangzhg — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
