### PR TITLE
[Fix](Nereids) fix date and date time arithmatic (#40745)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
cherry-pick:#40745
fix date and time arithmatic of: hours_add, minutes_add, seconds_add, to_days

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
