### PR TITLE
[chore](test) add log to find bug of unstable test

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

1. add log to find bug of unstable test
2. support profile action to fetch profile

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Comment by 924060929** [comment]
run external_p0

**Comment by 924060929** [comment]
run external

**Pull request merged**
