### PR TITLE
[fix](agg) windown_funnel compatibility issue with multi backends

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

In a multi backends environment, compatibility issues may arise if the configurations of the BE instances are inconsistent.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
