### PR TITLE
[bugfix][be][cppcheck] Possible NULL pointer access (#31025)

### LINKED ISSUE #31025: [Bug] (be) Possible access of NULL pointer (null_map) at vorc_reader.cpp
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

doris/be/src/vec/exec/format/orc/vorc_reader.cpp:2173:27: error: Null pointer dereference: null_map [ctunullpointer]
    auto* null_map_data = null_map->data();
doris/be/src/vec/exec/format/orc/vorc_reader.cpp:2173:27: note: Dereferencing argument null_map that is null

Cppcheck report NULL pointer access in vorc_reader

### What You Expected?

Pointer access should be done after validating pointer for NULL check

### How to Reproduce?

cppcheck on be code. and search error 

vallish@Vallishs-MacBook-Air workspace % cat te.txt| grep ctunullpointer
doris/be/src/vec/exec/format/orc/vorc_reader.cpp:2173:27: error: Null pointer dereference: null_map [ctunullpointer]
vallish@Vallishs-MacBook-Air workspace % 

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #31025

Move the code scope after null pointer check.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
