### PR TITLE
[Enhancement](FE) use customized grpc threadpool to get better metric for grpc from FE to BE

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes
Previously in Doris FE, there is no specific thread pool for grpc-client-channel, by default the underlying netty logic would use one [dynamic unbounded cache threadpool](https://groups.google.com/g/grpc-io/c/LrnAbWFozb0). The workload for this grpc threadpool is unseen.
Use ThreadpoolMgr to create one customized threadpool to get Prometheus-compatible metric data.
Issue Number: close #xxx

## Problem summary

Describe your changes.
Use ThreadpoolMgr to create one customized threadpool for grpc's NettyChannel instead of the default threadpool of grpc.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xxiao2018** [comment]
The previous default pool num is 2 * core num.
But you change it to 8 as default, which may be less than previous value?

**Comment by morningman** [comment]
The previous default pool num is 2 * core num.
But you change it to 8 as default, which may be less than previous value?

**Comment by ByteYue** [comment]
> The previous default pool num is 2 * core num. But you change it to 8 as default, which may be less than previous value?

Yes...  It's a little bit confusing me to choose which num to use as the default size. Any advice?😂

**Comment by morningman** [comment]
> > The previous default pool num is 2 * core num. But you change it to 8 as default, which may be less than previous value?
> 
> Yes... It's a little bit confusing me to choose which num to use as the default size. Any advice?😂

My point is, does increase this pool size really solve the problem?
Because you set a smaller default pool size, so I think you have tested it and resolve the problem?

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.23 seconds
 load time: 496 seconds
 storage size: 17180563873 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221113084705_clickbench_pr_45065.html

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Comment by ByteYue** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
