### PR TITLE
[enhancement] Refactor to improve the usability of MemTracker (step2)

### LINKED ISSUE #10741: [Enhancement] Refactor to improve the usability of MemTracker
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

The new MemTracker is difficult to use, mainly reflected in:
1. There are too many macros related to MemTracker.
Mainly, `SCOPED_SWITCH_xxx_TRACKER` related macros for switching TLS trackers are various and depend on each other, which is difficult to use.

2. Creating a new MemTracker is error-prone.
Because the hierarchical relationship between MemTrackers needs to be considered to avoid statistical errors affecting the accuracy of the overall statistics;

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinyiZzz**
# Proposed changes

Issue Number: close #10741

## Problem Summary:

continue #10743

### Main impact
Consuming `MemTracker` will not consume its parent synchronously, which means that `MemTracker` statistics errors will not affect the overall memory statistics of Query or Process.

Parent only used to print tree-like statistics, usually you don't need to set parent, so feel free to use `MemTracker` to count the memory you are interested in~ : )

### Other
1. Create `MemTracker`. Previously, `MemTracker::create_tracker` returned a `std::shared_ptr`, now we directly `new MemTracker()`. It is usually recommended to use `std::unique_ptr` to ensure the same life cycle as the class.

2. When a new thread is added to execute Query, add the macro `SCOPED_ATTACH_TASK` to bind the query mem tracker to ensure that the query memory can be recorded accurately.

3. When adding a new Brpc service, add the macro `SCOPED_SWITCH_BTHREAD_TLS` to ensure that the memory can be counted correctly in Bthread.

4. In addition to consuming MemTracker manually with `consume()/release()`, you can also put into `SCOPED_CONSUME_MEM_TRACKER`, which will automatically track all memory usage of the code segment where it is located.

5. Move `MemTracker` related files from `/runtime` to `/runtime/memory/`

6. Better pages, control the level of display through `?upper_level=6`
image

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
This PR need fast merge because it modified memtracker and too many files. It will not affect logic.

**Comment by BiteTheDDDDt** [comment]
This pr change the config of regression test

**Comment by xinyiZzz** [comment]
> This pr change the config of regression test

fix in https://github.com/apache/doris/pull/11125

**Pull request merged**
