### PR TITLE
[opt](test) set longer timeout for hive query cache test case

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Sometimes the first run of query may be longer then former given threshold, which case test fail.
Also add a new session variable `test_query_cache_hit`

So that we can use it to test if cache is hit in regression test

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
