### PR TITLE
[feature](doris compose) enable fe jvm debug port

### PR DESCRIPTION
**Pull request by yujun777**
1.  fe use 5005 as jvm debug port,  user can run `docker ps | grep  <fe-node-name>` to find out the port on host machine;
2.  extends get-cloud-ini command to print more info

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Pull request merged**
