### PR TITLE
[feat](nereids)Compressed materialize for aggregate and sort

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
if A is a short string column (len<4)
1.  'select A from T group by A' => 'select decodeAsChar(encode_as_int(A)) from T group by encode_as_int(A)'
2.  'select * from T order by A' => 'select * from T order by encode_as_int(A)'

for other sizes, short string will be wrapped by encode_as_smallint/encode_as_bigint/encode_as_largeInt

session variable ENABLE_COMPRESS_MATERIALIZE is used to swith on/off this optimization

Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run feut

**Comment by englefly** [comment]
run  buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
