### PR TITLE
[test]add check for query release when p0 finish

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by wangbo** [comment]
run compile

**Comment by wangbo** [comment]
run p0

**Comment by wangbo** [comment]
run compile

**Comment by wangbo** [comment]
run p0

**Comment by wangbo** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by shuke987 — APPROVED** [review]
LGTM

**Pull request merged**
