### PR TITLE
[Opt](Iceberg) Simplify the code of getting time travel snapshotId

### PR DESCRIPTION
**Pull request by zhangbutao**
## Proposed changes
Optimize the code of getting snapshotId.
We can use the Apache Iceberg funtion to get time travel snapshotId. 

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangbutao** [comment]
run buildall

**Comment by zhangbutao** [comment]
@morningman Could you please take a look? Thx.

**Comment by zhangbutao** [comment]
Gentle ping :)

**Review by morningman — APPROVED** [review]
LGTM
@wuwenchi PTAL

**Comment by wuwenchi** [comment]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by zhangbutao** [comment]
@morningman Thanks for review! Can we merge this change?

**Comment by zhangbutao** [comment]
Ping 😃 @morningman

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
