### PR TITLE
[fix][bug] FE web exists insecure cookie setting

### LINKED ISSUE #30180: [Bug] FE web insecure cookie setting
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

FE web exists insecure cookie setting param

### What You Expected?

FE web exists insecure cookie setting param, need to optimize

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LuGuangming**
## Proposed changes

Issue Number: close #30180

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LuGuangming** [comment]
run buildall

**Comment by zclllyybb** [comment]
is there same problem in master branch?

**Comment by LuGuangming** [comment]
> is there same problem in master branch?
Yes, master has been fix merged

**Comment by zclllyybb** [comment]
> > is there same problem in master branch?
> Yes, master has been fix merged

So it's better to have a link to master's fix patch in the pr's description

**Pull request merged**
