### PR TITLE
[fix](test) do not throw exception when a stream load consums more time

### PR DESCRIPTION
**Pull request by dataroaring**
than expected

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
