### PR TITLE
[bug](function) fix first/last value return error with ignore null

### PR DESCRIPTION
**Pull request by zhangstar333**
### What problem does this PR solve?

Problem Summary:
needs another prs of FE: https://github.com/apache/doris/pull/45065 https://github.com/apache/doris/pull/45264

1. the first value even if have set value, should not return directly, need check it whether need arg_ignore_null, as maybe it's NULL 

2. the last_value if need arg_ignore_null and not set value, should find in while loop, if find could return directly, not find check iff has any value before

### Release note

fix first_value/last_value return error with ignore null param is true

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zclllyybb** [comment]
maybe this PR need a release note

**Comment by zhangstar333** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]

**Comment by zhangstar333** [comment]
need this PR merge first: https://github.com/apache/doris/pull/45065

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
