### PR TITLE
[fix](fe) Key column varchar length change should't light schema change

### LINKED ISSUE #28226: [Bug] (dynamic partition) Cannot assign hash distribution with different distribution col
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

current master 
ddb6eb5ad7df74d3037d7514d5cf8b8f663b3e3b

### What's Wrong?

2023-12-11 11:14:10,376 WARN (DynamicPartitionScheduler|60) [DynamicPartitionScheduler.recordCreatePartitionFailedMsg():581] dynamic add partition failed: errCode = 2, detailMessage = Cannot assign hash distribution with different distribution cols. new is: [`dt` DATETIMEV2(0) NOT NULL COMMENT '分区日期', `watts_range` VARCHAR(30) NULL] default is: [`dt` DATETIMEV2(0) NOT NULL COMMENT '分区日期', `watts_range` VARCHAR(30) NULL], db: default_cluster:db1, table: t7

### What You Expected?

dynamic parition scheduler  work well and can create next partition successfully

### How to Reproduce?

CREATE TABLE t7
(
    dt datetime NOT NULL COMMENT '分区日期',
    citycode SMALLINT,
    watts_range VARCHAR(20),
    pv BIGINT SUM DEFAULT '0'
)
AGGREGATE KEY(dt, citycode, watts_range)
PARTITION BY RANGE(dt)()
DISTRIBUTED BY HASH(dt, watts_range) BUCKETS 1
PROPERTIES (
    "dynamic_partition.enable"="true",
    "dynamic_partition.end"="3",
    "dynamic_partition.buckets"="1",
    "dynamic_partition.start"="-3",
    "dynamic_partition.prefix"="p",
    "dynamic_partition.time_unit"="HOUR",
    "dynamic_partition.create_history_partition"="true",
    "dynamic_partition.replication_allocation" = "tag.location.default: 1"
);

alter table t7  modify column watts_range varchar(30)
(The column `watts_range` is distribute column)

wait at most 1hour , the fe.warn will print the warn message

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
## Proposed changes

Issue Number: close #28226 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by w41ter — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
