### PR TITLE
[Enhancement] (nereids)implement adminDiagnoseTabletCommand in nereids

### LINKED ISSUE #42848: [Enhancement] (nereids)implement adminDiagnoseTabletCommand in nereids
adminDiagnoseTablet command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following adminDiagnoseTablet command in nereids:
unsupportedadminDiagnoseTabletStatement
``` ADMIN DIAGNOSE TABLET tabletId=INTEGER_VALUE                                  ```

### PR DESCRIPTION
**Pull request by msridhar78**
### What problem does this PR solve?

Issue Number: close #42848 

Related PR: #xxx

Problem Summary:

[Enhancement] (nereids)implement adminDiagnoseTabletCommand in nereids

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by msridhar78** [comment]
run buildall

**Review by Vallishp — APPROVED** [review]
LGTM

**Comment by msridhar78** [comment]
run buildall

**Comment by msridhar78** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
