### PR TITLE
[Bug](brpc) fix sync_filter_size/apply_filterv2 has wrong closure

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
1. fix sync_filter_size/apply_filterv2 has wrong closure
2. avoid to use thread local storage of iobuf

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Pull request merged**
