### PR TITLE
[docker](container)create data path after rm residual data avoiding docker start fail

### PR DESCRIPTION
**Pull request by pingchunzhang**
## Proposed changes

Issue Number: close #xxx

exchange excution order avoiding docker container start fail

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pingchunzhang** [comment]
run buildall

**Comment by pingchunzhang** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zgxme — APPROVED** [review]
LGTM

**Pull request merged**
