### PR TITLE
[Bug](runtime-filter) fix runtime filter not register on vdata_gen_scan_node

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
fix runtime filter not register on vdata_gen_scan_node

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run p0

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
