### PR TITLE
[feature](TVF) support path partition keys for external file TVF

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

For partition columns from file path, e.g. /path/to/columnName=columnValue, support them in external file TVF.

Usage:

TVF(..., path_partition_keys="k1,k2,k3");

The corresponding keys will be split by "," and parsed as partition keys from path.

## Further comments

Tests and docs will be added later.

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run feet

**Comment by TangSiyang2001** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
