### PR TITLE
[fix](storage-vectorized) fix VMergeIterator core dump

### LINKED ISSUE #9563: [Bug] vectorization storage layer core dump on VMergeIterator
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master/dev-1.0.1

### What's Wrong?

0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/code/incubator-doris/be/src/common/signal_handler.h:407
 1# 0x00007F1A4770A400 in /lib64/libc.so.6
 2# doris::vectorized::VMergeIteratorContext::copy_row(doris::vectorized::Block*) at /root/code/incubator-doris/be/src/vec/olap/vgeneric_iterators.cpp:199
 3# doris::vectorized::VMergeIterator::next_batch(doris::vectorized::Block*) at /root/code/incubator-doris/be/src/vec/olap/vgeneric_iterators.cpp:346
 4# doris::BetaRowsetReader::next_block(doris::vectorized::Block*) at /root/code/incubator-doris/be/src/olap/rowset/beta_rowset_reader.cpp:194
 5# doris::vectorized::VCollectIterator::Level0Iterator::_refresh_current_row() at /root/code/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:200
 6# doris::vectorized::VCollectIterator::Level0Iterator::init() at /root/code/incubator-doris/be/src/vec/olap/vcollect_iterator.cpp:185
 7# doris::vectorized::VCollectIterator::build_heap(std::vector<[std::shared_ptr<doris::RowsetReader](std::shared_ptr%3Cdoris::RowsetReader)>, std::allocator<[std::shared_ptr<doris::RowsetReader](std::shared_ptr%3Cdoris::RowsetReader)> > >&) at /root/code/incubator-doris/be/src/vec/ola
p/vcollect_iterator.cpp:58
 8# doris::vectorized::BlockReader::_init_collect_iter(doris::TabletReader::ReaderParams const&, std::vector<[std::shared_ptr<doris::RowsetReader](std::shared_ptr%3Cdoris::RowsetReader)>, std::allocator<[std::shared_ptr<doris::RowsetReader](std::shared_ptr%3Cdoris::RowsetReader)> > >*)
 at /root/code/incubator-doris/be/src/vec/olap/block_reader.cpp:68
 9# doris::vectorized::BlockReader::init(doris::TabletReader::ReaderParams const&) at /root/code/incubator-doris/be/src/vec/olap/block_reader.cpp:144
10# doris::OlapScanner::open() at /root/code/incubator-doris/be/src/exec/olap_scanner.cpp:135
11# doris::vectorized::VOlapScanNode::scanner_thread(doris::vectorized::VOlapScanner*) at /root/code/incubator-doris/be/src/vec/exec/volap_scan_node.cpp:155
12# void std::__invoke_impl<void, void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapScanNode*&, doris::vectorized::VOlapScanner*&>(std::__invoke_memfun
_deref, void (doris::vectorized::VOlapScanNode::*&)(doris::vectorized::VOlapScanner*), doris::vectorized::VOlapScanNode*&, doris::vectorized::VOlapScanner*&) at /var/local/ldb-toolchain/include/c++/11/bit
s/invoke.h:74

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaoxin01**
# Proposed changes

Issue Number: close #9563 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — COMMENTED** [review]
whats the difference? please add some comment to explain why use num columnids not columns.size.

**Comment by liaoxin01** [comment]
> whats the difference? please add some comment to explain why use num columnids not columns.size.

@yiguolei num_column_ids indicates the number of columns actually queried. columns.size indicates the size of the schema.  so the num_column_ids is not greater than columns.size. 
And In block_reset, using num_column_ids to create block.

```
    Status block_reset() {
        if (!_block) {
            const Schema& schema = _iter->schema();
            const auto& column_ids = schema.column_ids();
            for (size_t i = 0; i < schema.num_column_ids(); ++i) {
                auto column_desc = schema.column(column_ids[i]);
                auto data_type = Schema::get_data_type_ptr(*column_desc);
                if (data_type == nullptr) {
                    return Status::RuntimeError("invalid data type");
                }
                auto column = data_type->create_column();
                column->reserve(_block_row_max);
                _block.insert(
                        ColumnWithTypeAndName(std::move(column), data_type, column_desc->name()));
            }
        } else {
            _block.clear_column_data();
        }
        return Status::OK();
    }
```

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
Please add regression test for this pr.

**Comment by wangbo** [comment]
Can you make a test for delete predicate for this pr?
When delete predicate exits, delete columnid may append to the end for return column schema, this means the storage layer schema may differ from query layer schema.
While in this pr, src block stands for query layer schema, but we use _iter->schema().num_column_ids()(storage layer schema) to read src block schema, this may has problem when delete condition exists.

**Pull request merged**
