### PR TITLE
[Enhancement](Load) stream tvf support csv header

### LINKED ISSUE #23678: [Enhancement] Improve the functionality of http_stream tvf
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

We still need to do the following functions now
1. Support file import in CSV header format
2. Support for importing JSON file format
3. Support for two phase commit
4. If the above functions are complete, it is necessary to convert the original stream_load format into http_stream mode for import

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zzzzzzzs**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/23678

## Further comments

stream tvf support csv header
csv_with_names
```
id,name,age
1,alice,18
2,bob,20
3,jack,24
4,jackson,19
5,liming,18
6,luffy,20
7,zoro,22
8,sanzi,26
9,wusuopu,21
10,nami,18
```
csv_with_names_and_types
```
id,name,age
INT,STRING,INT
1,alice,18
2,bob,20
3,jack,24
4,jackson,19
5,liming,18
6,luffy,20
7,zoro,22
8,sanzi,26
9,wusuopu,21
10,nami,18
```
example:
```
curl -v --location-trusted -u root: -H "sql: insert into test.t1(id, name, age) select cast(id as INT) as id, name, age from http_stream(\"format\" = \"csv_with_names\", \"column_separator\" = \",\")" -T csv_with_names.txt http://127.0.0.1:8030/api/_http_stream
```

```
curl -v --location-trusted -u root: -H "sql: insert into test.t1(id, name, age) select cast(id as INT) as id, name, age from http_stream(\"format\" = \"csv_with_names_and_types\", \"column_separator\" = \",\")" -T csv_with_names_and_types.txt http://127.0.0.1:8030/api/_http_stream
```

### CODE REVIEW

**Comment by zzzzzzzs** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.2 seconds
 stream load tsv:          530 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17162152881 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
