### PR TITLE
[fix](delta-writer) fix total received rows in delta writer incorrect

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title. `total received rows` in memtable writer was not passed to delta writer.

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
