### PR TITLE
[enhancement](style): polish the `checkstyle`

### PR DESCRIPTION
**Pull request by jackwener**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

- cancel the auto-align in Javadoc

```java
@ param1       desc
@ paramExample desc
``` 

- polish doc for checkstyle

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (yes)
4. Does it need to update dependencies: (no)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Hi @jackwener , would you like to translate the notes in English and use them in snapshot (idea-checkstyle-plugin.png)?

**Comment by jackwener** [comment]
> Hi @jackwener , would you like to translate the notes in English and use them in snapshot (idea-checkstyle-plugin.png)?

I think it's unnecessary, because English doc is exist.

image

**Comment by adonis0147** [comment]
Ok, you didn't use the snapshot in the English docs.

**Comment by adonis0147** [comment]
LGTM

**Review by morrySnow — DISMISSED** [review]
LGTM

**Review by morningman — COMMENTED** [review]
Better to use English in image.

**Comment by jackwener** [comment]
> Better to use English in image.

fixed

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
