### PR TITLE
[enhance](mtmv)mtmv query sql expand star

### PR DESCRIPTION
**Pull request by zddr**
before: SELECT * from user

now: SELECT `internal`.`zd`.`user`.`k1`, `internal`.`zd`.`user`.`k2` from `internal`.`zd`.`user`

Therefore, there is no need for EnvInfo to store catalog and db information when creating materialized views

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run performance

**Review by seawinde — APPROVED** [review]

**Review by morrySnow — DISMISSED** [review]

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by seawinde — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
