### PR TITLE
[feature](docker suite) Docker suite use independent executor

### PR DESCRIPTION
**Pull request by yujun777**
If many docker suites run parallel,  the docker containers take a lot memory,  so use independent executor for them to control the memory usage.

Use options  or config  dockerSuiteParallel  to set the docker suite parallel,  default is 1.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run cloud_p0

**Pull request merged**
