### PR TITLE
[fix](move-memtable) fallback if partial update

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Partial update is not supported by move-memtable, fallback when partial update.
Also, there is 1 reversed filter missing in #25684.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
