### PR TITLE
[fix](httpapi) restore compaction/run_status api can show be's overall compaction status and refactor code

### PR DESCRIPTION
**Pull request by Yulei-Yang**
bp #35278

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xiaokang — CHANGES_REQUESTED** [review]
please add testcase

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run p0

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
> please add testcase

done, can you pls review again/

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
