### PR TITLE
[fix](multicatalog) fix no data error when read hive table on cosn

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #32779

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run buildall

**Review by lide-reed — DISMISSED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xy720 — DISMISSED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run external

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by xy720 — APPROVED** [review]

**Pull request merged**
