### PR TITLE
[fix](segcompaction) enable segcompaction by default

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

PR #28901 has been merged, so we enable segment compaction by default.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run pipeline_p0

**Comment by liaoxin01** [comment]
run pipelinex_p0

**Comment by liaoxin01** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by liaoxin01** [comment]
run pipelinex_p0

**Comment by liaoxin01** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
