### PR TITLE
[fix](compatibility) add some keywords #29251

### PR DESCRIPTION
**Pull request by nextdreamblue**
## Proposed changes

cherry-pick from #29251

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
