### PR TITLE
[test](nereids)add regression case: disable join reorder if there are invalid stats

### PR DESCRIPTION
**Pull request by englefly**
### What problem does this PR solve?
add test case for pr #41790.
this case is blocked by #43279

Issue Number: close #xxx

Related PR: #41790  #43279

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Review by zfr9527 — APPROVED** [review]
LGTM

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by Jibing-Li — APPROVED** [review]

**Review by zfr9527 — APPROVED** [review]
LGTM

**Pull request merged**
