### PR TITLE
[Improve](config)del array config for create inverted index

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
delete useless config : enable_create_inverted_index_for_array

Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
