### PR TITLE
[feature](expr) Support kill query by query_id

### PR DESCRIPTION
**Pull request by nanfeng1999**
## Proposed changes

Issue Number: open #28517

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
LGTM, please update the kill doc

**Comment by nanfeng1999** [comment]
> LGTM, please update the kill doc

done

**Comment by nanfeng1999** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run buildall

**Comment by nanfeng1999** [comment]
run pipelinex_p0

**Review by kaka11chen — APPROVED** [review]
LGTM.

**Pull request merged**
