### PR TITLE
[Improve](Transaction)Commit operation adds mandatory verification.

### PR DESCRIPTION
**Pull request by CalvinKirs**
When committing and publish, commitInfo can’t be empty, otherwise PUBLISH will succeed but visibleVersion is not updated (due to lack of CommitInfo).
https://github.com/apache/doris/blob/0ff3073fc4166ccc8ba4bb6f06c0904b88766577/fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java#L544-L657

https://github.com/apache/doris/blob/0ff3073fc4166ccc8ba4bb6f06c0904b88766577/fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java#L1550
## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

Add pre-check，Avoid situations where PUBLISH succeeds but the data is not visible, causing ambiguity.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
TODO test empty file load

**Comment by CalvinKirs** [comment]
When the load file is empty, the `commitInfos` is empty..Closed

**Pull request closed without merging**
