### PR TITLE
[fix](move-memtable) lock when send data in load stream stub

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Add a lock to ensure message order when send data in load stream stub.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run feut

**Comment by kaijchen** [comment]
run beut

**Comment by kaijchen** [comment]
run clickbench

**Review by sollhui — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
