### PR TITLE
  [Function](cbrt)Add cbrt function for doris

### LINKED ISSUE #12429: [Feature] The cbrt function support like hive.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Need cbrt function support, this function returns the cube root of a double value.

### Use case

When we enter a double value,this function returns the cube root of a double value.

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TaoZex**
# Proposed changes

Issue Number: close #12429

## Problem summary

Add cbrt function for doris,this function returns the cube root of a double value.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
Can you also implement this function in a vectorization engine?

**Comment by TaoZex** [comment]
> Can you also implement this function in a vectorization engine?
The code in the picture implements cbrt function in a vectorization engine. I refer to the vectorization of sqrt function.
cbrt

**Comment by BiteTheDDDDt** [comment]
> > Can you also implement this function in a vectorization engine?
> > The code in the picture implements cbrt function in a vectorization engine. I refer to the vectorization of sqrt function.Do I need to add any other code？
> 
> cbrt

Sorry, I missed it.

**Review by BiteTheDDDDt — CHANGES_REQUESTED** [review]
Need to add documentation for this function

**Comment by TaoZex** [comment]
> Need to add documentation for this function

I have completed the documentation of this function, and found that many mathe functions documentation is missing, I will complete it next.

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
