### PR TITLE
[bugfix]thread pool resource leak

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

1. When the thread pool is not needed, you need to manually close the thread pool.
2. Before rolling back, we need to abort the existing task.
3. Add some exception information

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
