### PR TITLE
[Fix](format) compatible run_clang_format format string with python2/3.6/higher

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Pull request merged**
