### PR TITLE
[feat](fe) Show db total size and recycle bin size with `ShowDataStmt`

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
## Proposed changes
In previous, show data stmt without use database will throw analyze exception.
After the pr show data stmt without use database will print all db size statistic
```
mysql> show data;
+-------+--------------------+-------+------------+-------------+-------------------+
| DbId  | DbName             | Size  | RemoteSize | RecycleSize | RecycleRemoteSize |
+-------+--------------------+-------+------------+-------------+-------------------+
| 21009 | db1                | 0     | 0          | 714         | 0                 |
| 0     | information_schema | 0     | 0          | 0           | 0                 |
| 1     | mysql              | 0     | 0          | 0           | 0                 |
| 10002 | __internal_schema  | 20105 | 0          | 0           | 0                 |
| Total | NULL               | 20105 | 0          | 714         | 0                 |
+-------+--------------------+-------+------------+-------------+-------------------+
5 rows in set (0.00 sec)
```
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by gavinchou** [comment]
Pls add a regression test

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by mymeiyi — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
