### PR TITLE
[Improvement](set) enable admin_set_frontend_config can apply to all fe

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes
Currently, admin_set_frontend_config only apply to the connected fe, now enable it can be apply to all fe
image
image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Pull request merged**
