### PR TITLE
[chore](branch-1.2) remove unnecessary deserialize in tablet sink

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by lide-reed** [comment]
https://github.com/apache/doris/pull/23531/files

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by lide-reed** [comment]
F0309 21:30:43.347543 892102 vtablet_sink.cpp:305] Check failed: block.rows() == tmp_block.rows()
*** Check failure stack trace: ***
    @     0x5561452dd54d  google::LogMessage::Fail()
    @     0x5561452dfa89  google::LogMessage::SendToLog()
    @     0x5561452dd0b6  google::LogMessage::Flush()
    @     0x5561452e00f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x556144c71eeb  doris::stream_load::VNodeChannel::try_send_block()
    @     0x55614010d625  doris::ThreadPool::dispatch_thread()
    @     0x556140102a7f  doris::Thread::supervise_thread()
    @     0x7fc0e6d0fea5  start_thread
    @     0x7fc0e70229fd  __clone
    @              (nil)  (unknown)
*** Query id: f8cb1c18a2e44351-850456f175c6328b ***
*** Aborted at 1709991047 (unix time) try "date -d @1709991047" if you are using GNU date ***
*** Current BE git commitID: e21e1ca ***
*** SIGABRT unkown detail explain (@0x3e8000d9b63) received by PID 891747 (TID 0x7fc064240700) from PID 891747; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /data/doris-1.x/be/src/common/signal_handler.h:420
 1# 0x00007FC0E6F5A400 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x00005561452E7F39 in /usr/local/service/doris/lib/be/doris_be
 5# 0x00005561452DD54D in /usr/local/service/doris/lib/be/doris_be
 6# google::LogMessage::SendToLog() in /usr/local/service/doris/lib/be/doris_be
 7# google::LogMessage::Flush() in /usr/local/service/doris/lib/be/doris_be
 8# google::LogMessageFatal::~LogMessageFatal() in /usr/local/service/doris/lib/be/doris_be
 9# doris::stream_load::VNodeChannel::try_send_block(doris::RuntimeState*) at /data/doris-1.x/be/src/vec/sink/vtablet_sink.cpp:354
10# doris::ThreadPool::dispatch_thread() at /data/doris-1.x/be/src/util/threadpool.cpp:543
11# doris::Thread::supervise_thread(void*) at /data/doris-1.x/be/src/util/thread.cpp:455
12# start_thread in /lib64/libpthread.so.0
13# __clone in /lib64/libc.so.6

**Pull request merged**
