### PR TITLE
[Fix] Change open tablet log level

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Now, during the open tablet operation, logs will be printed, and a large number of logs will be generated under high-frequency import. It is necessary to reduce the log level.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run be-ut

**Comment by HHoflittlefish777** [comment]
run beut

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run p0

**Review by freemandealer — APPROVED** [review]
LGTM

**Pull request merged**
