### PR TITLE
[optimization](agg) add more type in agg percentile

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
Add more supported types to reduce the cost of cast.

```
+-------+----------+------+-------+---------+-------+
| Field | Type     | Null | Key   | Default | Extra |
+-------+----------+------+-------+---------+-------+
| id    | INT      | Yes  | true  | NULL    |       |
| k1    | LARGEINT | Yes  | true  | NULL    |       |
| k2    | BIGINT   | Yes  | true  | NULL    |       |
| k3    | INT      | Yes  | false | NULL    | NONE  |
| k4    | SMALLINT | Yes  | false | NULL    | NONE  |
| k5    | TINYINT  | Yes  | false | NULL    | NONE  |
+-------+----------+------+-------+---------+-------+
```

before
```
output: partial_percentile(CAST(k1[#1] AS BIGINT), 0.5)[#6], partial_percentile(k2[#2], 0.5)[#7], partial_percentile(CAST(k3[#3] AS BIGINT), 0.5)[#8], partial_percentile(CAST(k4[#4] AS BIGINT), 0.5)[#9], partial_percentile(CAST(k5[#5] AS BIGINT), 0.5)[#10]  

mysql [ssb_sf100]>Select percentile(LO_SHIPPRIORITY,0.5) from lineorder_flat;
+------------------------------------------------------------------+
| percentile(cast(LO_SHIPPRIORITY as BIGINT), cast(0.5 as DOUBLE)) |
+------------------------------------------------------------------+
|                                                                0 |
+------------------------------------------------------------------+
1 row in set (12.41 sec)
```
now

```
output: partial_percentile(k1[#1], 0.5)[#6], partial_percentile(k2[#2], 0.5)[#7], partial_percentile(k3[#3], 0.5)[#8], partial_percentile(k4[#4], 0.5)[#9], partial_percentile(k5[#5], 0.5)


mysql [ssb_sf100]>Select percentile(LO_SHIPPRIORITY,0.5) from lineorder_flat;
+--------------------------------------------------+
| percentile(LO_SHIPPRIORITY, cast(0.5 as DOUBLE)) |
+--------------------------------------------------+
|                                                0 |
+--------------------------------------------------+
1 row in set (6.21 sec)

mysql [ssb_sf100]>Select percentile(cast(LO_SHIPPRIORITY as bigint),0.5) from lineorder_flat;
+------------------------------------------------------------------+
| percentile(cast(LO_SHIPPRIORITY as BIGINT), cast(0.5 as DOUBLE)) |
+------------------------------------------------------------------+
|                                                                0 |
+------------------------------------------------------------------+
1 row in set (12.41 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
