### PR TITLE
[fix](doc) Updated Analyze syntax as per code

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

Updated the Anlyze page syntax as per code

changes refered from :#18880   #20264 #23978

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by Jibing-Li — COMMENTED** [review]
These functions are either not supported yet or deprecated, so we don't need to update the doc right now.

**Review by Jibing-Li — CHANGES_REQUESTED** [review]
These functions are either not supported yet or deprecated, so we don't need to update the doc right now.

**Comment by Nitin-Kashyap** [comment]
> These functions are either not supported yet or deprecated, so we don't need to update the doc right now.

agreed, closing this PR

**Pull request closed without merging**
