### PR TITLE
[improve](move-memtable) log rpc failures in stream file writer

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Followup #29257

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
