### PR TITLE
[typo](doc) fix misconfiguration in example

### PR DESCRIPTION
**Pull request by hechao-ustc**
## Proposed changes

Issue Number: close #xxx

I found some configuration in the example that was inconsistent with the context, and fixed.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — APPROVED** [review]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
