### PR TITLE
[fix](regression-test) move some case in test_query_sys_tables to p2

### PR DESCRIPTION
**Pull request by Cai-Yao**
# Proposed changes

Issue Number: close #xxx

## Problem summary

move the case `test a large amount of data` in test_query_sys_tables to p2.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Cai-Yao** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by Cai-Yao** [comment]
build p0

**Comment by Cai-Yao** [comment]
run p0

**Pull request merged**
