### PR TITLE
[fix](profile) The PID_DIR variable in the Doris stop script does not follow the conf file

### PR DESCRIPTION
**Pull request by timyuer**
## Proposed changes

Issue: #20784

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by timyuer** [comment]
run buildall

**Comment by timyuer** [comment]
run p0

**Comment by timyuer** [comment]
@morningman Could you please review it.

**Review by yiguolei — APPROVED** [review]
lgtm

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
