### PR TITLE
[enhancement](oom) add exception in olap data convertor when memory is not enough to prevent oom

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
