### PR TITLE
[opt](cache) More metrics for lru cache

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Metrics to detect cache stampede

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
ubsan fail is not related to this pr.

image

**Review by yiguolei — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
