### PR TITLE
[Enhance](regression)docker hive s3 file address is determined based on the configuration

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

docker hive s3 file address is determined based on the configuration custom_settings.env

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by pingchunzhang — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
