### PR TITLE
[opt](function) opt nullif function by nullif(null,x) = null

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

https://dbfiddle.uk/Ud5Ng3Ui

nullif(null,x) = null
after
```

mysql [test10]>select count(nullif(null,number)) from numbers("number" = "800000000");
+-----------------------------+
| count(nullif(NULL, number)) |
+-----------------------------+
|                           0 |
+-----------------------------+
1 row in set (2.18 sec)

```
now
```
mysql [test10]>select count(nullif(null,number)) from numbers("number" = "800000000");
+-----------------------------+
| count(nullif(NULL, number)) |
+-----------------------------+
|                           0 |
+-----------------------------+
1 row in set (0.86 sec)
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by superdiaodiao — COMMENTED** [review]
`bool use_default_implementation_for_nulls() const override { return false; }`

What if we change the `false` to `true`? Would it be better?

**Comment by Mryange** [comment]
> `bool use_default_implementation_for_nulls() const override { return false; }`
> 
> What if we change the `false` to `true`? Would it be better?

if use_default_implementation_for_nulls = true 
 nullif(3,null) = null 
but 
nullif(3,null) = 3

**Comment by superdiaodiao** [comment]
> > `bool use_default_implementation_for_nulls() const override { return false; }`
> > What if we change the `false` to `true`? Would it be better?
> 
> if use_default_implementation_for_nulls = true nullif(3,null) = null but nullif(3,null) = 3

OK, get.

**Comment by Mryange** [comment]
run buildall

**Pull request closed without merging**
