### PR TITLE
[fix](ui)(fe-system) fix fe System Info query error when the fe serve…

### PR DESCRIPTION
**Pull request by Larborator**
# Proposed changes

Issue Number: #20072

## Problem summary

Describe your changes.
1. Fix duplicate '/' in front-end request URI.
2. When the FileSystemSeparator is '\\', replace '\\' as '/'

## Checklist(Required)

* [x] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Review by jeffreys-cat — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.61 seconds
 stream load tsv:          439 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          78.7 seconds inserted 10000000 Rows, about 127K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526024939_clickbench_pr_150938.html

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
