### PR TITLE
[fix](cloud)(review) map end check added (#33612)

### LINKED ISSUE #33612: [Bug]  iterator need to be validate after find of map
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Based on the bug https://github.com/apache/doris/pull/32489 , reviewed master code.

After iterator returned by using find must be validated with map.end() before use.
 CloudTxnDeleteBitmapCache::remove_expired_tablet_txn_info
           auto txn_iter = _txn_map.find(iter->second);
        if (iter->first == txn_iter->second.txn_expiration) {

### What You Expected?

code should not have a access of iterator without checking map.end()

### How to Reproduce?

_No response_

### Anything Else?

fixed similar problems.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #33612

add validation for iterator

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Review by platoneko — APPROVED** [review]

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
