### PR TITLE
[opt](Nereids) add where Null rule to create empty relation as where false (#38135)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
cherry-pick: #38135 

explain shape plan select * from table2 where Null; explain shape plan select * from table2 where false; in this case, null literal can be regard as same as false literal

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Pull request merged**
