### PR TITLE
[Improve](complex-type) Support Count(complexType)

### PR DESCRIPTION
**Pull request by amorynan**
# Proposed changes

Support count function can use on ARRAY, MAP, STRUCT

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run buildall

**Review by xy720 — COMMENTED** [review]
please add some test cases

**Comment by amorynan** [comment]
> please add some test cases

DONE!

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
buildall

**Comment by amorynan** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run beut

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
