### PR TITLE
[Feature](profile) Add a new rest api to query instance host and ip information for query profile action in branch master

### LINKED ISSUE #18668: [Feature] Add a new rest api to query instance host and ip information for query profile action in branch master
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently the api `GET /rest/v2/manager/query/profile/fragments/{query_id}` can only get these information:
```json
{
    "msg": "success",
    "code": 0,
    "data": [
        {
            "fragment_id": "",
            "time": "",
            "instance_id": {
                "": ""
            }
        }
    ],
    "count": 0
}
```
I need to query instance ip and port information like sql:
```sql
mysql> SHOW QUERY PROFILE "/5dcfbc1054a74e8c-ad482d77a5170465/0";
+-----------------------------------+----------------+------------+
| Instances                         | Host           | ActiveTime |
+-----------------------------------+----------------+------------+
| 5dcfbc1054a74e8c-ad482d77a5170466 | 127.0.0.1:9060 | 11.69ms    |
+-----------------------------------+----------------+------------+
1 row in set (0.01 sec)
```
So adding a new api to query instance host ip and port is necessary.

### Use case

The feature is used for querying host ip and port scenario.

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by bigben0204**
# Proposed changes

Issue Number: close #18668

## Problem summary

Query instance host ip and port

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [X] Has document been added or modified
* [ ] Does it need to update dependencies
* [X] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Review by stalary — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.84 seconds
 stream load tsv:          422 seconds loaded 74807831229 Bytes, about 169 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230516022113_clickbench_pr_144154.html

**Comment by morningman** [comment]
run buildall

**Pull request merged**
