### PR TITLE
[bugfix](es catalog) add constant_keyword wildcard data type

### LINKED ISSUE #30732: [Bug] ES外表目前不能支持wildcard类型字段识别.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris2.0.4

### What's Wrong?

使用以下语句创建的es外表
`
CREATE EXTERNAL TABLE TEST_OS_ES
ENGINE=ELASTICSEARCH
PROPERTIES (
"hosts" = "http://192.168.1.100:9200",
"index" = "test_index",
"enable_keyword_sniff" = "true"
);
`
当字段含有wildcard时查询报错，需要手工指定类型，否则查询报错：

[HY000][1105] errCode = 2, detailMessage = Unsupported type 'UNSUPPORTED_TYPE' in '`test_filed`'.

### What You Expected?

可以正确识别Wildcard类型的字段

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #30732 

https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#constant-keyword-field-type
https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#wildcard-field-type

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — COMMENTED** [review]
Add some test cases

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
> Add some test cases

Done.

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by qidaye** [comment]
@liugddx Please resolve the conflicts.

**Comment by liugddx** [comment]
> @liugddx Please resolve the conflicts.

Done.

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
