### PR TITLE
[Fix](multi-catalog) optimize hashcode for PartitionKey.

### PR DESCRIPTION
**Pull request by dutyu**
## Proposed changes

2551687760879_ pic

1. optimize hashcode logic for PartitionKey to make hashcodes more scattering (try to avoid the above problem)
2. fix hashcode logic for DateLiteral which violates the principle between `hashCode()` and `equals()`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dutyu** [comment]
run buildall

**Comment by dutyu** [comment]
run buildall

**Comment by dutyu** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Pull request merged**
