### PR TITLE
[docs](website) fix a typo in docs tittle

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Review by luozenglin — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Pull request merged**
