### PR TITLE
[chore](third-party) Fix compilation errors while building brpc

### LINKED ISSUE #23340: [Bug] Failed to build BRPC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```shell
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xae): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x12c): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x199): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x209): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x234): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x391): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x437): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x4a0): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x503): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x568): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x5cd): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x727): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x7c5): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0x957): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xae6): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xb84): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xbf1): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xd42): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xed3): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-logging.o):(.text.startup+0xf71): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-vlog_is_on.o):(.text.startup+0x68): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-vlog_is_on.o):(.text.startup+0x1c0): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/Programs/palo_workspace/baidu/bdg/doris/core/thirdparty/installed/lib64/libglog.a(libglog_la-utilities.o):(.text.startup+0x79): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
```

### What You Expected?

Build BRPC successfully.

### How to Reproduce?

```shell
cd thirdparty
./build-thirdparty.sh --clean
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Issue Number: close #23340

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.33 seconds
 stream load tsv:          539 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161974635 Bytes

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
