### PR TITLE
[fix](case) adjust ak sk for multi cloud test case

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run external

**Review by wuwenchi — COMMENTED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
