### PR TITLE
[fix](Nereids) fix bug of dry run query with sql cache

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

1. dry run query should not use sql cache
2. fix test sql cache in cloud mode
3. enable cache OneRowRelation and EmptyRelation in frontend to skip parse sql

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by 924060929** [comment]
run fe ut

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
