### PR TITLE
[fix](java-udf)Fix cannot download pentaho-aggdesigner-algorithm jar in java udf and format it

### PR DESCRIPTION
**Pull request by DongLiang-0**
# Proposed changes

Issue Number: close #xxx

## Problem summary
The hive-exec version of 2.3.5 is too old, so some dependencies cannot be downloaded.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by DongLiang-0** [comment]
run buildall

**Comment by yiguolei** [comment]
why upgrade the hive version? currently, is it compatible with version 2.x and 1.x?

**Comment by DongLiang-0** [comment]
> why upgrade the hive version? currently, is it compatible with version 2.x and 1.x?

Because `hive-exec 2.X` depends on `org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde` , and this `jhyde` dependency can no longer be downloaded in the central warehouse. I have tested the `java-udf`use `hive-exec 3.1.3`, and it can be queried normally.

**Comment by DongLiang-0** [comment]
> why upgrade the hive version? currently, is it compatible with version 2.x and 1.x?

Thanks for your suggestion, now I exclude the jar package of `org.pentaho`

**Comment by DongLiang-0** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by DongLiang-0** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
