### PR TITLE
[fix](hive)fix hive catalog miss partition that have special characters.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes
Previously, when processing partition values, Hive catalog parsed them in the URL format. However, this is different from the encoding method of Hive, which results in missing some partitions with special characters when reading the partition table. 
This PR is to fix this problem.
Ref: common/src/java/org/apache/hadoop/hive/common/FileUtils.java:`makePartName(List<String> partCols, List<String> vals,String defaultStr)`

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by suxiaogang223 — APPROVED** [review]

**Pull request merged**
