### PR TITLE
[bug](prepared statement) fix bug and add some cases for in list prepared statement

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

```
CREATE TABLE `tbl_prepared_stmt` (
  `k1` INT NULL,
  `k2` DECIMAL(27, 9) NULL,
  `k3` VARCHAR(30) NULL,
  `k4` VARCHAR(30) NULL,
  `k5` DATE NULL,
  `k6` DATETIME NULL,
  `k7` FLOAT NULL,
  `k8` DATE NULL,
  `k9` ARRAY<DATETIME> NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`)
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
);

set experimental_enable_nereids_planner = false;

prepare stmt1 from select * from tbl_prepared_stmt WHERE `k1` IN (?, ?, ?) order by 1;

execute stmt1 using ('1231', '1232', '1233');


java.lang.ClassCastException: class org.apache.doris.analysis.CastExpr cannot be cast to class org.apache.doris.analysis.LiteralExpr (org.apache.d
oris.analysis.CastExpr and org.apache.doris.analysis.LiteralExpr are in unnamed module of loader 'app')
        at org.apache.doris.rewrite.RewriteInPredicateRule.apply(RewriteInPredicateRule.java:101) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.rewrite.ExprRewriter.applyRuleBottomUp(ExprRewriter.java:257) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.rewrite.ExprRewriter.applyRule(ExprRewriter.java:244) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.rewrite.ExprRewriter.applyRuleRepeatedly(ExprRewriter.java:234) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.rewrite.ExprRewriter.rewrite(ExprRewriter.java:166) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.rewriteExprs(SelectStmt.java:1895) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:1449) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:1301) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:933) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:621) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:539) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.handleExecute(MysqlConnectProcessor.java:137) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.handleExecute(MysqlConnectProcessor.java:231) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:288) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:339) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run p0

**Review by cambyzju — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]

**Pull request merged**
