### PR TITLE
[test](serialisation) Serialise some cases and enable str_to_date tests

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

1. enable the cases about str_to_date, which have been muted because some parallel config influence.
2. serialise some cases which called `admin set config`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run p0 10

**Comment by zclllyybb** [comment]
run p0 10

**Comment by zclllyybb** [comment]
run p0 10

**Comment by zclllyybb** [comment]
run p0 10

**Comment by zclllyybb** [comment]
run p0 10

**Review by BiteTheDDDDt — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
