### PR TITLE
[feature](load) support single-stream-multi-table load (BE part)

### PR DESCRIPTION
**Pull request by freemandealer**
# Proposed changes

Issue Number: close #xxx

## Motivation
The current routine load process for synchronizing large-scale data from a variety of sources to Doris is inefficient and resource-intensive. Creating individual import tasks for each of the 10,000 tables puts significant pressure on task management and transaction commits. Additionally, maintaining 10,000 Kafka topics for each table adds complexity for users. To address these issues, a solution is needed that allows multiple tables' data to be transmitted through a single topic and distributed to multiple target tables.

## Design overview
**How we do data-driven planning?**

Instead of planning the import tasks before receiving the data, the new approach collects the data first and then determines the number of tables involved in each batch. This ensures that unnecessary planning for inactive tables is avoided, preventing wasted resources.

image

**How we execute plans?**

After FE reponsing with plans for this batch of unplanned table, we execute the plan. In the future, the execution will be performed by pipeline engine (which is not current available for load).

**How it ends?**

When all plans for this routine load task finishing executing, we commit txn for all tables. We use only one txn with a list of tables which are added dynamically. If one plan failed, we fail all of them belonging to this task.

## thread model
note: streamload is not covered in this PR and will be published later in seperate one.

image

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run buildall

**Comment by freemandealer** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
