### PR TITLE
[branch-2.0](feature)(tvf)(jni-avro)jni-avro scanner add complex data types

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes
master PR: https://github.com/apache/doris/pull/26236

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
