### PR TITLE
[fix](nereids) fix months_add/ months_sub/ years_add/years_sub compute wrong result because SimplifyArithmeticComparisonRule

### PR DESCRIPTION
**Pull request by 924060929**
### What problem does this PR solve?

fix months_add/ months_sub/ years_add/years_sub compute wrong result because SimplifyArithmeticComparisonRule
introduced by #25180

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by 924060929** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by morrySnow — DISMISSED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
