### PR TITLE
[pick-1.2][fix](mysql) fix mysql channel infinite blocking

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

cherry-pick to 1.2:
https://github.com/apache/doris/pull/28808
https://github.com/apache/doris/pull/32545

issue:
https://github.com/apache/doris/issues/28807
https://github.com/apache/doris/issues/32539

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]

**Review by lide-reed — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
run feut

**Comment by cambyzju** [comment]
run ut

**Pull request merged**
