### PR TITLE
[fix](mtmv)fix thread local reference to checkpoint's Env, causing Env to be unable to be reclaimed, resulting in excessive memory usage by FE

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

when replay `addTaskResult` log,will create one `ConnectContext`,and set Env.getCurrentEnv,then store this ctx in `ConnectContext.threadLocalInfo`,`threadLocalInfo` is `static`,so this ctx can not be recycling，`Env` of replay thread also can not be recycling

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
