### PR TITLE
[branch-2.0-fix](partial update) only report error when in strict mode partial update when finding missing rowsets during flushing memtable

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

fix https://github.com/apache/doris/pull/28679
pick from master: https://github.com/apache/doris/pull/28764
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run clickbench

**Pull request merged**
