### PR TITLE
[fix](spark-load)fix-Unique-key-with-MOR-by-sparkload for branch2.0

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

mirror #26383

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
run p1

**Comment by xiaokang** [comment]
run buildall

**Pull request merged**
