### PR TITLE
[feature](cmd) add UNSET_VARIABLE statement to set back variables

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

bp #27552

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run external

**Comment by Yulei-Yang** [comment]
run feut

**Comment by Yulei-Yang** [comment]
run buildall

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
