### PR TITLE
[Chore](materialized-view) forbiden create mv with some constant expr and curdate()

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

forbiden create mv with some constant expr and curdate()
```sql
create materialized view const_1 as select k1,curdate() from d_table;
create materialized view const_2 as select k1,curdate()+k1 from d_table;
create materialized view const_3 as select k1,abs(1+1) from d_table;
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.59 seconds
 stream load tsv:          439 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230327111153_clickbench_pr_121300.html

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
