### PR TITLE
[fix] (recover) fix can not recover a BE's tablet after deleting its data directory  manual (#20273)

### LINKED ISSUE #20273: [Bug] Fail to recover a tablet if delete its directory manual
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.4

### What's Wrong?

If delete a tablet's directory manual, it can not reocver its data.  

And if run a query on this tablet,  the command will fail.

### What You Expected?

The tablet can auto recover its data,   run query sql on it no more fail.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

Issue Number: close #20273

<--Describe your changes.-->

When report a tablet's info to the FE,  mark it as no used if missing its data directory.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
Maybe it should remove the arg 'enable_path_check'  in function 'build_tablet_report_info'?

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
Heartbeat is too frequently for io.s

**Comment by yujun777** [comment]
> Heartbeat is too frequently for io.s

@dataroaring The report  hearbeat is 1min.  Maybe we can change check directory  exists period to 1h ? Cause most  of the time the directory should exists.

A test on checking 100,0000 directory is exists, total cost time is 30+ seconds.  It will  expand the heartbeat interval.

Is it better to change  the check directory period to 1h and  amortize the time cost ?

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
