### PR TITLE
[fix](regression) fix arm p0 and p0 memlimit error

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes

1. fix arm p0
fix date type error

2.  p0 memlimit error
(1) limit cache mem usage
(2) add mem_limit to 43%

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by xinyiZzz** [comment]
p0 machine environment has not been modified, mem limit error failed, it should be a commit that caused the query memory usage to increase.

We should locate this commit and confirm whether it is reasonable.

**Comment by xinyiZzz** [comment]
Of course, currently modifying be conf mem limit can avoid block p0

**Comment by ZhangYu0123** [comment]
> p0 machine environment has not been modified, mem limit error failed, it should be a commit that caused the query memory usage to increase.
> 
> We should locate this commit and confirm whether it is reasonable.

I had test history commit submit by reset --hard, It also had the memlimit error.  So i think it probability  p0 machine environment problem.

**Comment by ZhangYu0123** [comment]
> One machine in our workflow may run three tests at the same time, so 43% may have problems

Is the teamcity test script change or can we reduce the test parallel？ I test history commit 2 weeks  ago but also has memlimit error.

**Pull request closed without merging**
