### PR TITLE
[Fix](orc-reader) Fix `Wrong data type for column` error when column order in hive table is not same in orc file schema.

### PR DESCRIPTION
**Pull request by kaka11chen**
### Issue
`Wrong data type for column` error when column order in hive table is not same in orc file schema.

The root cause is in order to handle the following case:

The table in orc format of Hive 1.x may encounter system column names such as `_col0`, `_col1`, `_col2`... in the underlying orc file schema, which need to use the column names in the hive table for mapping.

### Solution
Currently fix this issue by handling the following case by specifying hive version to 1.x.x in the hive catalog configuration.

```sql
CREATE CATALOG hive PROPERTIES (
    'hive.version' = '1.x.x'
);
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]
LGTM.
Is it possible that Hive 2.x and hive 1.x tables are in the same catalog?

**Comment by morningman** [comment]
> LGTM. Is it possible that Hive 2.x and hive 1.x tables are in the same catalog?

Don't think so

**Pull request merged**
