### PR TITLE
[compatibility](MySQL) update charset to utf8mb4, collation to utf8mb4_0900_bin

### PR DESCRIPTION
**Pull request by morrySnow**
## Proposed changes

Doris's behaviour is more like utf8mb4 and utf8mb4_0900_bin than utf8 and utf8_general_ci

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
