### PR TITLE
[improve](group commit) Add a swicth to wait internal group commit lo…

### PR DESCRIPTION
**Pull request by mymeiyi**
…ad finish

## Proposed changes

The group commit is returned once WAL is written, and does not wait the internal group commit finish.
This PR add a switch to make the group commit wait the internal load finish and then return.
The switch is not used for users, we will enable this switch globally in our daily tests to check if the group commit work well for all cases.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hust-hhb — APPROVED** [review]
LGTM

**Pull request merged**
