### PR TITLE
[Chore](Fe)Upgrade dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes

upgrade spring-boot to 2.7.18
upgrade zookeeper to 3.9.2
upgrade jetty to 9.4.55.v20240627
upgrade ivy to 2.5.2
upgrade icu4j to 75.1
upgrade ini4j to 0.5.4

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run cloud_p0

**Comment by CalvinKirs** [comment]
run external

**Comment by CalvinKirs** [comment]
run cloud_p0

**Comment by CalvinKirs** [comment]
run cloud_p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
