### PR TITLE
[enhancement](array-function) `array_position`,`array_contains`,`coun…

### PR DESCRIPTION
**Pull request by eldenmoon**
…tequal` which in `FunctionArrayIndex` handle target NULL

in the previous, the result is:
```
mysql> select array_position([1, null], null);
+--------------------------------------+
| array_position(ARRAY(1, NULL), NULL) |
+--------------------------------------+
|                                 NULL |
+--------------------------------------+
1 row in set (0.02 sec)
```

but after this commit, the result become:
```
mysql> select array_position([1, null], null);
+--------------------------------------+
| array_position(ARRAY(1, NULL), NULL) |
+--------------------------------------+
|                                    2 |
+--------------------------------------+
1 row in set (0.02 sec)
```

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
The behavior follows ClickHouse as well Starrocks

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.48 seconds
 load time: 448 seconds
 storage size: 17172871749 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221124154443_clickbench_pr_52539.html

**Comment by cambyzju** [comment]
> 

actually array functions follows hive/spark as design, in spark:
`pyspark.sql.functions.array_position: Returns null if either of the arguments are null.`

**Comment by eldenmoon** [comment]
@cambyzju I could provide anthother function to follow the behavior of ClickHouse? I think user may need the behavior

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
> @cambyzju I could provide anthother function to follow the behavior of ClickHouse? I think user may need the behavior

I think the way is better. the spark and hive do the right way. `null do not equal null` in SQL.  the clickhouse logic is werid and not right

**Pull request merged**
