### PR TITLE
[enhancement](UDF) The user defined functions support global ('show functions'/'show create') operation

### PR DESCRIPTION
**Pull request by lexluo09**
# Proposed changes

The global udf support ('show functions'/'show create') operation, to show the details of the global udf.

## Problem summary

Solution
1、 add the global keyword.

SHOW [GLOBAL] [FULL] [BUILTIN] FUNCTIONS [IN|FROM db] [LIKE 'function_pattern']

SHOW CREATE GLOBAL FUNCTION function_name(arg_type [, ...]);

2、show the details of the  global udf.

image

image

image

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by lexluo09** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by lexluo09** [comment]
run buildall

**Comment by lexluo09** [comment]
run buildall

**Comment by lexluo09** [comment]
run p0

**Comment by lexluo09** [comment]
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Comment by lexluo09** [comment]
run buildall

**Pull request merged**
