### PR TITLE
[regression](multi-catalog) add aliyun dlf hive on oss and huawei obs test case

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

 add aliyun dlf hive on oss and huawei obs test case
 now obs cases have some problem, will not fix this at this PR, just add comment.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
wait for passing obs test

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Pull request merged**
