### PR TITLE
[fix](partial-update) transient rowset writer should not trigger segcompaction when build rowset

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

Fix core
```
(gdb) bt
#0  0x0000556ab7d8a099 in std::__shared_ptr<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2>::get (this=0x68)
    at /mnt/disk2/zhangchen/env/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1291
#1  std::__shared_ptr_access<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get (this=0x68)
    at /mnt/disk2/zhangchen/env/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:990
#2  std::__shared_ptr_access<doris::RowsetMeta, (__gnu_cxx::_Lock_policy)2, false, false>::operator-> (this=0x68)
    at /mnt/disk2/zhangchen/env/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:984
#3  doris::Rowset::merge_rowset_meta (this=0x7f31ec3a3de0, other=<error reading variable: Cannot access memory at address 0x70>) at /mnt/disk2/zhangchen/doris-dev/be/src/olap/rowset/rowset.cpp:85
#4  0x0000556ab803f2bd in doris::TxnManager::publish_txn (this=0x7f32fa9f7b40, meta=0x7f32fd871a60, partition_id=14635, transaction_id=55775, tablet_id=14664, schema_hash=650230612, tablet_uid=..., version=...,
    stats=0x7f32fbe54738) at /mnt/disk2/zhangchen/doris-dev/be/src/olap/txn_manager.cpp:390
#5  0x0000556ab803e284 in doris::TxnManager::publish_txn (this=0x68, partition_id=1, tablet=..., transaction_id=0, version=..., stats=0x7f32fbe54738) at /mnt/disk2/zhangchen/doris-dev/be/src/olap/txn_manager.cpp:174
#6  0x0000556ab802be93 in doris::TabletPublishTxnTask::handle (this=0x7f32fbe546d0) at /mnt/disk2/zhangchen/doris-dev/be/src/olap/task/engine_publish_version_task.cpp:262
#7  0x0000556ab82a957f in doris::ThreadPool::dispatch_thread (this=0x7f32f98b8400) at /mnt/disk2/zhangchen/doris-dev/be/src/util/threadpool.cpp:531
#8  0x0000556ab82a06cc in std::function<void ()>::operator()() const (this=0x7f31ec3a3de0)
    at /mnt/disk2/zhangchen/env/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
#9  doris::Thread::supervise_thread (arg=0x7f330d24e600) at /mnt/disk2/zhangchen/doris-dev/be/src/util/thread.cpp:465
#10 0x00007f332753eea5 in __pthread_mutex_unlock_full (mutex=0x7f31ec3a3de0, decr=104) at pthread_mutex_unlock.c:101
#11 0x0000000000000000 in ?? () 
```
segcompaction failure caused the rowset build failed, then we got an nullptr, which caused the program coredump

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.63 seconds
 stream load tsv:          504 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         26 seconds loaded 2358488459 Bytes, about 86 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162230637 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230712155233_clickbench_pr_176993.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.24 seconds
 stream load tsv:          452 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          26.0 seconds inserted 10000000 Rows, about 384K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230712075540_clickbench_pr_177005.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
