### PR TITLE
[fix](multi-catalog)fix max compute null parts table read

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

fix max compute null parts table read
if no any data in a part, we should make mc jni scanner return 0 rows

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
