### PR TITLE
[opt](catalog) use table in db object return get db

### PR DESCRIPTION
**Pull request by zy-kkk**
### What problem does this PR solve?

This pull request includes several changes across multiple files to improve logging, add missing logic, and correct SQL syntax. The most important changes include adding logging for synchronization actions, setting the database if missing, and correcting SQL syntax for MySQL queries.

#### Logging Improvements:
* [`fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java`](diffhunk://#diff-50477c5ff1b42452704e942fe5fc738563dc64182690f378925fbc2401be5d48R749): Added logging for synchronized databases during refresh and create actions in the `replayInitCatalog` method. [[1]](diffhunk://#diff-50477c5ff1b42452704e942fe5fc738563dc64182690f378925fbc2401be5d48R749) [[2]](diffhunk://#diff-50477c5ff1b42452704e942fe5fc738563dc64182690f378925fbc2401be5d48R758-R759)
* [`fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java`](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R214-R220): Added logging for synchronized tables during refresh and create actions in the `replayInitDb` method. [[1]](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R214-R220) [[2]](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R229-R235)

#### Logic Enhancements:
* [`fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java`](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R214-R220): Added logic to set the database for tables if it is missing in the `replayInitDb` method. [[1]](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R214-R220) [[2]](diffhunk://#diff-7b2044ac22da12680de78fbe8fface00accf1f915f74473696a78d8ad1e780c6R229-R235)

#### SQL Syntax Correction:
* [`fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java`](diffhunk://#diff-1dc9bf9b52cfa9a96fd6aaed8060578b07dc9ecdefbaa9f3a2c69f9e69e63ce3L54-R54): Corrected SQL syntax by adding backticks around the `rows` alias in the `MYSQL_ROW_COUNT_SQL` query.

#### Test Data Adjustments:
* [`regression-test/data/external_table_p0/hive/test_hive_use_meta_cache.out`](diffhunk://#diff-995a65142428f1d804967ee6169b21e5409187a5f5e139d6d413a994bd8944c7R37-R38): Added missing test cases for Hive meta cache. [[1]](diffhunk://#diff-995a65142428f1d804967ee6169b21e5409187a5f5e139d6d413a994bd8944c7R37-R38) [[2]](diffhunk://#diff-995a65142428f1d804967ee6169b21e5409187a5f5e139d6d413a994bd8944c7R128-R129)

#### Test Suite Modifications:
* [`regression-test/suites/external_table_p0/hive/test_hive_parquet.groovy`](diffhunk://#diff-e16bd2abd096731e6e3c735e31d39210a256a9a2a63a736355877b5e7f441c83L189-R190): Modified the test suite to switch catalogs correctly before using the default database.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by hubgeter — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
