### PR TITLE
[fix](auth)Fix some issues with incorrect permission verification

### PR DESCRIPTION
**Pull request by zddr**
- `show columns` do not have permission to check
- `show sync job`do not have permission to check
- `Show data from db.table` should be the permission to determine the table, not the admin permission
- users with grant permission should not see all processes through 'SHOW PROCESS LIST'
- `show tablet storage format`fix permission error prompt

cases will be added uniformly in other PRs

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
should we add some cases?

**Comment by zddr** [comment]
cases will be added uniformly in other PRs

**Review by morrySnow — APPROVED** [review]

**Comment by zddr** [comment]
run buildall

**Comment by morrySnow** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
