### PR TITLE
[Enhancement](metric) add current edit log metric

### LINKED ISSUE #15656: [Enhancement] add metrics related edit log
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

If image fails to be generated, the edit log becomes larger and larger. We need to add related monitoring item for timely handling，However, there is no metrics related current edit log's size and number in Doris.

### Solution

Add current edit log metrics for Doris to monitor it.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yongjinhou**
# Proposed changes

Issue Number: close #15656

## Problem summary

add current edit log metrics for doris.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
Don't review for now, there may be some problems, I am checking.

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.91 seconds
 load time: 478 seconds
 storage size: 17122667255 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230105155617_clickbench_pr_74373.html

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
