### PR TITLE
[enhance](2pc) enhance abort transaction performance for flink job with 2pc

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

1, disable logging when hold write lock
2, enable timeout  time  configable

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Comment by GoGoWen** [comment]
run buildall

**Review by CalvinKirs — COMMENTED** [review]
Consider reducing the lock granularity instead of disabling logging directly. Effective day-to-day retention is important

**Comment by GoGoWen** [comment]
> Consider reducing the lock granularity instead of disabling logging directly. Effective day-to-day retention is important
Yes,  this pr is not try to disable logging directly,  it just move the logging outside the write lock.

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.48 seconds
 stream load tsv:          529 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162120134 Bytes

**Pull request closed without merging**
