### PR TITLE
[feat](mtmv)Unified external table interface supporting partition refresh and partition pruning

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

- Add `MvccTable` to represent a table that supports querying specified version data
- Add the `MvccSnapshot` interface to store snapshot information of mvcc at a certain moment in time
- Add the `MvccSnapshot` parameter to the method of the `MTMVRelatedTableIf `interface to retrieve data of a specified version
- Partition pruning related methods combined with the `MvccSnapshot` parameter are used to obtain partition information for a specified version
- Load the snapshot information of mvccTable at the beginning of the query plan and store it in StatementContext

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
Unified external table interface supporting partition refresh and partition pruning
### Release note

Unified external table interface supporting partition refresh and partition pruning

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [x] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run external

**Comment by zddr** [comment]
run cloud_p0

**Comment by morrySnow** [comment]
run cloud_p0

**Review by morrySnow — DISMISSED** [review]

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
