### PR TITLE
[Enhancement] Add E as default value function for doris

### LINKED ISSUE #34228: [Enhancement] Add some default value function for doris
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

1. localtime, localtimestamp
2. now
3. bitmap_empty
4. hll_empty
5. e
6. pi
7. uuid_numeric
8. random

### Solution

Reference #34211 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Vallishp**
## Proposed changes

Issue Number: close #34228

add e as default value

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
LGTM

**Review by Nitin-Kashyap — APPROVED** [review]

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
