### PR TITLE
[fix](streamload) fix http_stream retry mechanism

### PR DESCRIPTION
**Pull request by zzzzzzzs**
## Proposed changes

Issue Number: close #xxx

## Further comments
1. For the original global variable need_schema, the Doris retry mechanism cannot be guaranteed, so the method of using local variables is used
2. Removed useless code

### CODE REVIEW

**Comment by zzzzzzzs** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by zzzzzzzs** [comment]
run buildall

**Comment by zzzzzzzs** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by zzzzzzzs** [comment]
run buildall

**Comment by zzzzzzzs** [comment]
run p0

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
