### PR TITLE
[fix](memory) Fix task repeat attach task DCHECK failed

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

EngineChecksumTask repeats attach task

```
Check failed: thread_mem_tracker()->label() == "Orphan" , attach mem tracker label: EngineChecksumTask#tabletId=10162
*** Check failure stack trace: ***
    @     0x560c4647daad  google::LogMessage::Fail()
    @     0x560c4647ffe9  google::LogMessage::SendToLog()
    @     0x560c4647d616  google::LogMessage::Flush()
    @     0x560c46480659  google::LogMessageFatal::~LogMessageFatal()
    @     0x560c20f6d257  doris::ThreadContext::attach_task()
    @     0x560c20f68019  doris::AttachTask::AttachTask()
    @     0x560c206473b9  doris::EngineChecksumTask::execute()
    @     0x560c1dfaf7c5  doris::Compaction::do_compaction()
    @     0x560c203c60c2  doris::CumulativeCompaction::execute_compact_impl()
    @     0x560c1dfaef7d  doris::Compaction::execute_compact()
    @     0x560c202c5a5a  doris::Tablet::execute_compaction()
    @     0x560c1dd7c4b0  doris::StorageEngine::_submit_compaction_task()::$_0::operator()()
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Comment by yiguolei** [comment]
run p0

**Comment by yiguolei** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
