### PR TITLE
[fix](outfile) fix jsonb boolean outfile

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
this pr: https://github.com/apache/doris/pull/38683 omit some outfile to be fixed
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
