### PR TITLE
[Bug](ODBC) fix vectorized null value error report in odbc scan node

### LINKED ISSUE #11419: [Bug] (odbc vectorized) select null from a not null column do not get the right error report
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
mysql> select * from b_mysql;
ERROR 1105 (HY000): errCode = 2, detailMessage = Fail to convert odbc value:'false' to INT on column:`k6`
```

### What You Expected?

```
mysql> select * from b_mysql;                                                                                                                    ERROR 1105 (HY000): errCode = 2, detailMessage = nonnull column contains nullptr. table=`baseall`, column=k6
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #11419

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by BiteTheDDDDt — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
need fix ut

**Review by yiguolei — DISMISSED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
