### PR TITLE
[fix](tools) tpcds-tools: report benchmark result before cleanup

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
cleanup may failed, and blocks printing hot/cold run summary
Issue Number: close #xxx

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Review by hello-stephen — DISMISSED** [review]
LGTM

**Review by feifeifeimoon — APPROVED** [review]

**Review by starocean999 — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run performance

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
