### PR TITLE
[refactor](agg_state) refactor agg_state type to support fixed length object type

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
before the agg_state type only support with datatype string,
But with some agg functions, eg: avg,sum,mix... 
those functions need serialize type is fixed length object type

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by zhangstar333** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
