### PR TITLE
[refine](pipeline) Remove condition_variable from MultiCastDataStreamer.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

 We should ensure that no blocking operations occur in the current pipeline execution.

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
