### PR TITLE
[fix](Nereids) adjust min/max stats for cast function if types are comparable

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
estimate column stats for "cast(col, XXXType)"

-----cast-est------
query4  41169 40335   40267   40267
query58 463     361     401     361
Total cold run time: 41632 ms
Total hot run time: 40628 ms

----master------
query4  40624   40180   40299   40180
query58 487     389     420     389
Total cold run time: 41111 ms
Total hot run time: 40569 ms

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run feut

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by jackwener — APPROVED** [review]

**Pull request merged**
