### PR TITLE
[Scanner](revert) revert the scanner change by apache#35604

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Fix:http://43.132.222.7:8111/buildConfiguration/Doris_DorisPerformance_Performance/439819?buildTab=log&linesState=37791&logView=flowAware&focusLine=39230

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Comment by HappenLee** [comment]
run performance

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
