### PR TITLE
[bugfix](hms)add default value check for hms catalog with dlf

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

1. `dlf` is not supported default values, so throw an exception.
2. The database name needs to be case-insensitive and consistent with hive
3. Improve error message prompt information

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run compile

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
