### PR TITLE
[fix](multi-catalog) fix iceberg defalut credentials proviers

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

Use "fs.s3a.aws.credentials.provider" first if it is in catalog properties， or use "s3.credentials.provider".
And the default credentials list is AWS_CREDENTIALS_PROVIDERS = Arrays.asList(
            DataLakeAWSCredentialsProvider.class.getName(),
            TemporaryAWSCredentialsProvider.class.getName(),
            SimpleAWSCredentialsProvider.class.getName(),
            EnvironmentVariableCredentialsProvider.class.getName(),
            SystemPropertiesCredentialsProvider.class.getName(),
            ProfileCredentialsProvider.class.getName(),
            InstanceProfileCredentialsProvider.class.getName(),
            WebIdentityTokenCredentialsProvider.class.getName(),
            IAMInstanceCredentialsProvider.class.getName());

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
