### PR TITLE
[refactor](load) remove FlushContext from SegmentWriter

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Pull request merged**
