### PR TITLE
[fix](mtmv) Fix rewrite by materialized view fail when query hive table

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes

mv def is 
```sql
            select l_orderkey, l_partkey, o_custkey, l_shipdate, o_orderdate 
            from ${hive_catalog_name}.${hive_database}.${hive_table} 
            left join ${internal_catalog}.${olap_db}.${olap_table} on l_orderkey = o_orderkey 
```
if we query the sql as following, it will rewrite fail by mv, the fail info is `mv can not offer any partition for query`
```sql
            select l_orderkey, l_partkey, o_custkey, l_shipdate, o_orderdate 
            from ${hive_catalog_name}.${hive_database}.${hive_table} 
            left join ${internal_catalog}.${olap_db}.${olap_table} on l_orderkey = o_orderkey 
```
This pr fix this problem. it would be rewritten by mv successfully.

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by zfr9527 — APPROVED** [review]
LGTM

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
