### PR TITLE
[feat](mtmv) compute agg expressions tree cost

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

suppose we have MV: select abs(v) from T;
query: select sum(abs(v)) from T

this pr add expression tree cost into Agg's cost in order to make the cost of the plan using MTMV lower.

Issue Number: close #xxx

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
