### PR TITLE
[fix](multi-catalog)fix mc decimal type parse, fix wrong obj location

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

1. mc decimal type need parse correctly by arrow vector method
2. fix wrong obj location if use oss,obs,cosn

Will add test case in another PR

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Comment by wsjz** [comment]
run p0

**Comment by wsjz** [comment]
run p0

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]

**Pull request merged**
