### PR TITLE
[fix](statistics) fix missing scanBytes and scanRows in query statist…

### PR DESCRIPTION
**Pull request by dutyu**
…ics when enable_vectorized_engine=true.

# Proposed changes

Issue Number: close #xxx

## Problem summary

When set enable_vectorized_engine = true, sometimes scanBytes and scanRows is missing in audit log.

image

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.47 seconds
 load time: 510 seconds
 storage size: 17123356162 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221202033711_clickbench_pr_56557.html

**Comment by dutyu** [comment]
> why the cputimeMS is not added in the method?
> 
> `statistics->add_cpu_ms(_scan_cpu_timer->value() / NANOS_PER_MILLIS);`

It will not work if just add this line at method `collect_query_statistics`, maybe we also need to do some job at `scanner_scheduler.cpp` to update `_scan_cpu_timer`, but i'm not familiar with c++, so i just fix these two fields first. You can submit a new pr to fix this problem.

**Comment by dinggege1024** [comment]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
