### PR TITLE
[fix](log4j) fix audit_log_roll_num not work for fe audit log file

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Pull request merged**
