### PR TITLE
[chore](multi catalog) Print serde properties when show create hive-external-table

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

before:

```
CREATE TABLE `test`(
  `id` int,
  `name` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://HDFS1012837/usr/hive/warehouse/test.db/test'
TBLPROPERTIES (
  ...
)
```

after:

```
CREATE TABLE `test`(
  `id` int,
  `name` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = ',',
  'field.delim' = ',')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://HDFS1012837/usr/hive/warehouse/test.db/test'
TBLPROPERTIES (
  ...
)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run cloud_p1

**Review by cambyzju — DISMISSED** [review]
LGTM

**Review by morningman — COMMENTED** [review]
Please add UT or test case

**Comment by xy720** [comment]
run buildall

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
