### PR TITLE
[Regression](planner) Add tpcds plan check in regression test

### PR DESCRIPTION
**Pull request by Kikyou1997**
# Proposed changes

Issue Number: noissue

## Problem summary

1. upgrade script to make its usage more general
2. add TPC-DS regression test suite

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
3. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
5. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
6. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
@morrySnow @dataroaring

**Comment by hello-stephen** [comment]
LGTM

**Review by yiguolei — CHANGES_REQUESTED** [review]
wait for runtime filter to merge

**Review by dataroaring — DISMISSED** [review]
LGTM

**Pull request closed without merging**
