### PR TITLE
[fix](ctas) fix NPE when ctas with old planner and varchar issue

### PR DESCRIPTION
**Pull request by morningman**
Fix 2 bugs:
1. 
introduced from #35489
When the target table is unpartitioned with text type column from external table,
NPE will be thrown.
Only happen when using old planner.
The new planner works well.

2.
If first column is varchar type, the new planner will change it to string type
and then failed because first column can not be string type.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by BePPPower — APPROVED** [review]
LGTM

**Comment by BePPPower** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by morrySnow — APPROVED** [review]

**Review by BePPPower — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Pull request merged**
