### PR TITLE
[fix](clean trash) Add clean trash regression case

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by dataroaring — CHANGES_REQUESTED** [review]
The case is not stable, because it is possible that there is another thread dropping a table. So the case should be marked noncocurrent, and we also should check trash usage is greater than 0 before clean.

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
