### PR TITLE
[Bug](udf) forbid varchar type and convert to use string type in java-udf

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
Two point have change:
1.  forbid create udf function use varchar type, could use string type.2. 
2. in order to the compatibly of old version, convert varchar to string type to execute udf function.

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p0

**Review by Mryange — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
