### PR TITLE
[Fix](array-function) fix `array_distinct` null values

### PR DESCRIPTION
**Pull request by eldenmoon**
in the previous the result is:
```
mysql> select array_distinct([1,1,3,3,null, null, null]);
+-----------------------------------------------------+
| array_distinct(ARRAY(1, 1, 3, 3, NULL, NULL, NULL)) |
+-----------------------------------------------------+
| [1, 3, NULL, NULL, NULL]                            |
+-----------------------------------------------------+
1 row in set (0.00 sec)
```

after this fix, the result becomes:
```
mysql> select array_distinct([1,1,3,3,null, null, null]);
+-----------------------------------------------------+
| array_distinct(ARRAY(1, 1, 3, 3, NULL, NULL, NULL)) |
+-----------------------------------------------------+
| [1, 3, NULL]                                        |
+-----------------------------------------------------+
1 row in set (0.00 sec)
```

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by carlvinhust2012** [comment]
Does this changed behavior follow the spark or starrocks?

**Comment by eldenmoon** [comment]
@carlvinhust2012 I don't know spark, but starocks behavior mathes the fixed one, I tested on ClickHouse, the duplicated nulls is also removed from results, this is more matched with user's intuition

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.94 seconds
 load time: 443 seconds
 storage size: 17171844166 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221124081216_clickbench_pr_52036.html

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by cambyzju** [comment]
> @carlvinhust2012 I don't know spark, but starocks behavior mathes the fixed one, I tested on ClickHouse, the duplicated nulls is also removed from results, this is more matched with user's intuition
> 
> https://docs.starrocks.io/en-us/2.4/sql-reference/sql-functions/array-functions/array_distinct

I tested this case on spark, it will remove duplicate nulls.

**Pull request merged**
