### PR TITLE
[BugFix](MTMV)Set enable_mtmv_scheduler_framework master only to avoid regression fail

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Set enable_mtmv_scheduler_framework master only to avoid regression fail

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run arm

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run buildall

**Comment by SaintBacchus** [comment]
run p0

**Comment by SaintBacchus** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
