### PR TITLE
[cherry-pick](branch-2.1) pick hive text write from master

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
pick prs:
https://github.com/apache/doris/pull/38549
https://github.com/apache/doris/pull/40183
https://github.com/apache/doris/pull/40315

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run p0

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by suxiaogang223** [comment]
run p0

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
