### PR TITLE
[chore](thirdparty) Fix link errors of librdkafka

### PR DESCRIPTION
**Pull request by amosbird**
Exclude coverage symbol from librdkafka's version script generator to avoid compatibility issues with recent linkers such as lld-17.

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run p0

**Pull request merged**
