### PR TITLE
[fix](hive) report error with escape char and null format

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes

Because be did not process escape char and null format when reading the hive text table, an error was reported when fe found that this value was not the default value.

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildalll

**Comment by suxiaogang223** [comment]
run buildalll

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
