### PR TITLE
[fix](docs) add enable_single_replica_load on be config doc

### PR DESCRIPTION
**Pull request by LemonLiTree**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LemonLiTree** [comment]
runbuild all

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by LemonLiTree** [comment]
runbuild all

**Comment by LemonLiTree** [comment]
run buildall

**Pull request merged**
