### PR TITLE
[Fix](compile) Fix clang-18 and libc++ compile problems

### PR DESCRIPTION
**Pull request by biohazard4321**
## Proposed changes

Issue Number: close #xxx

Fix clang-18 and libc++ compile problems

unique() of shared_ptr is deprecated in clang-18, it's not a strict implementation, can use use_count() instead.
And fixed some other compie errors in both using clang-18 and libc++.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by gavinchou** [comment]
LGTM

**Comment by biohazard4321** [comment]
please approval

**Comment by biohazard4321** [comment]
run buildall

**Comment by biohazard4321** [comment]
run buildall

**Comment by biohazard4321** [comment]
run buildall

**Comment by biohazard4321** [comment]
run p0

**Comment by biohazard4321** [comment]
run cloud_p0

**Comment by biohazard4321** [comment]
run arm

**Comment by biohazard4321** [comment]
run p0

**Comment by biohazard4321** [comment]
run cloud_p0

**Comment by biohazard4321** [comment]
run cloud_p0

**Review by gavinchou — CHANGES_REQUESTED** [review]
Please rebase doris master before proceeding.
The file s3_rate_limiter.cpp seems not correct.

**Comment by biohazard4321** [comment]
run buildall

**Comment by biohazard4321** [comment]
run external

**Comment by biohazard4321** [comment]
run arm

**Comment by biohazard4321** [comment]
run arm

**Comment by biohazard4321** [comment]
run arm

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by platoneko — APPROVED** [review]

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
