### PR TITLE
[chore](version) Show binary version in metrics: fe be ms

### PR DESCRIPTION
**Pull request by yagagagaga**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

pick from https://github.com/selectdb/selectdb-core/commit/1985902d

before
```
root@af0e5d234e63:~# curl 127.0.0.1:8030/metrics | grep doris_fe_version

root@af0e5d234e63:~# curl 127.0.0.1:8060/brpc_metrics | grep doris_be_version

root@af0e5d234e63:~#  curl 127.0.0.1:5000/brpc_metrics | grep doris_cloud_version

```

after
```
[root@dbb7fecb3b61 output]# curl 127.0.0.1:8030/metrics | grep doris_fe_version
# TYPE doris_fe_version gauge
doris_fe_version 30004


[root@dbb7fecb3b61 output]# curl 127.0.0.1:8060/brpc_metrics | grep doris_be_version
# TYPE doris_be_version gauge
doris_be_version 30004

[root@dbb7fecb3b61 output]# curl 127.0.0.1:5000/brpc_metrics | grep doris_cloud_version
# TYPE doris_cloud_version gauge
doris_cloud_version 30004
```

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [x] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. add a number as hotfix version

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by yagagagaga** [comment]
run buildall

**Comment by yagagagaga** [comment]
run buildall

**Review by gavinchou — COMMENTED** [review]
LGTM, better add a regression test

**Review by gavinchou — APPROVED** [review]

**Comment by yagagagaga** [comment]
> LGTM, better add a regression test

OK, I will post another PR to add a regression test

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
