### PR TITLE
[opt](partial update) Forbid partial update on merge-on-write table with sync mv

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

doc: https://github.com/apache/doris-website/pull/1103

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run feut

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
