### PR TITLE
[case](mtmv)fix test_base_mtmv failed

### PR DESCRIPTION
**Pull request by zddr**
```
errCode = 2, detailMessage = Table[t_test_base_mtmv_user]'s state(SCHEMA_CHANGE) is not NORMAL. Do not allow doing ALTER ops
```

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Comment by zddr** [comment]
run p0

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
