### PR TITLE
[refactor](variant) refactor sub path push down on variant type

### PR DESCRIPTION
**Pull request by morrySnow**
intro a new rule VARIANT_SUB_PATH_PRUNING to prune variant sub path.

for example, variant slot v in table t has two sub path: 'c1' and 'c2', after this rule, select v['c1'] from t will only scan one sub path 'c1' of v to reduce scan time.

This rule accomplishes all the work using two components. The Collector traverses from the top down, collecting all the element_at functions on the variant types, and recording the required path from the original variant slot to the current element_at. The Replacer traverses from the bottom up, generating the slots for the required sub path on scan, union, and cte consumer. Then, it replaces the element_at with the corresponding slot.

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by 924060929 — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run performance

**Review by starocean999 — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
