### PR TITLE
[improve](dependency)Upgrade dependency version

### PR DESCRIPTION
**Pull request by CalvinKirs**
exclude old netty version
upgrade spring-boot version to 2.7.13
used ojdbc8 replace ojdbc6
upgrade jackson version to 2.15.2
upgrade fabric8 version to 6.7.2

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall (memory limit)

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 43.98 seconds
 stream load tsv:          448 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 insert into select:          69.7 seconds inserted 10000000 Rows, about 143K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230703080805_clickbench_pr_171296.html

**Comment by CalvinKirs** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
@zddr Hi, i modify fabric8 dependency, pls take a look

**Comment by CalvinKirs** [comment]
> @zddr Hi, i modify fabric8 dependency, pls take a look↳

This is exactly the same as the jackson version that our project depends on.

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
