### PR TITLE
[fix](mow) Fix missing mow flag when streamload commit txn from BE introduced by #36237

### PR DESCRIPTION
**Pull request by gavinchou**
Fix incomplete optimization introduced by #36237
[Opt](streamload) Commit txn on BE coordinator in cloud mode to avoid RPC and lock overhead (#36237)

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
