### PR TITLE
[fix](meta) update killed query state

### LINKED ISSUE #25916: [Bug] Killed query state shows as Finished not Cancelled
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.2+

### What's Wrong?

Rest interface shows Killed Query state as finished, instead of Cancelled.

### What You Expected?

Cancelled query should list as Cancelled and not finished

### How to Reproduce?

Execute a long running query.

from another session kill this query
and then check its status.

GET http://localhost:8088/api/query_detail
select * from queries();

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
issue: #25916

Updated the killed query state as Cancelled instead of Finished when killed

## Proposed changes

Issue Number: close #25916

### CODE REVIEW

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run builaall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
