### PR TITLE
[opt](s3filewriter) Optimize exception handling when put object

### PR DESCRIPTION
**Pull request by gavinchou**
we should not continue to put object if state is not satisfied.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buidall

**Comment by dataroaring** [comment]
run buildall

**Comment by gavinchou** [comment]
run

**Comment by gavinchou** [comment]
run buildall

**Review by swjtu-zhanglei — APPROVED** [review]

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
