### PR TITLE
[fix](arm) fix arm compilation

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

1. fix some not standard usages
2. remove an useless cmake flag

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by zclllyybb** [comment]
run arm

**Review by Mryange — APPROVED** [review]

**Comment by zclllyybb** [comment]
run arm

**Comment by zclllyybb** [comment]
run arm

**Comment by zclllyybb** [comment]
run arm

**Pull request merged**
