### PR TITLE
[Enchancement](column) make create_always_true_column return column const

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
make create_always_true_column return column const

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
