### PR TITLE
[enhancement](regression-test) upgrade groovy to 4.x and enable run test by jdk17/21

### PR DESCRIPTION
**Pull request by 924060929**
## Proposed changes

upgrade groovy to 4.x and enable run test by jdk17 / 21

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Comment by 924060929** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Review by feiniaofeiafei — APPROVED** [review]

**Pull request merged**
