### PR TITLE
[branch-2.1](mtmv) Support read sync materialized view in async materialized view

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes

pick #37396

### CODE REVIEW

**Comment by liutang123** [comment]
run buildall

**Comment by liutang123** [comment]
run p0

**Comment by liutang123** [comment]
run p0

**Comment by hello-stephen** [comment]
run buildall

**Comment by liutang123** [comment]
run p0

**Comment by liutang123** [comment]
run feut

**Comment by liutang123** [comment]
run beut

**Comment by liutang123** [comment]
run buildall

**Pull request merged**
