### PR TITLE
[fix](nereids) do not push RF into nested cte

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
1. When optimizer pushes runtime filters into nested cte, the target slots are not correctly mapped to base table. This simple fix is when we detect such cases, we apply the runtime filter on cte, not inside cte.
2. add a new feature for regression case. this pr introduces a new function "multi_sql('query1; query2;...')" to execute a batch of sql statements. 
 

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]

**Review by xzj7019 — APPROVED** [review]

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
