### PR TITLE
[test](ut) added UT cases for show create materialized view

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes
added UT case for show create materialized view

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
image
unused import

**Review by yiguolei — DISMISSED** [review]

**Comment by Nitin-Kashyap** [comment]
run buildall

**Review by Vallishp — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
