### PR TITLE
[fix](stop)fix missing notify_all() after the stop

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
https://github.com/apache/doris/pull/27653

**Review by Gabriel39 — APPROVED** [review]

**Comment by Mryange** [comment]
run p0

**Pull request merged**
