### PR TITLE
[fix](partial update) report error directly if missing rowsets during doing alignment when flushing memtable due to compaction

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes
related pr: https://github.com/apache/doris/pull/28062, https://github.com/apache/doris/pull/28674
report error directly if we find that situation in https://github.com/apache/doris/pull/28062 happens

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
