### PR TITLE
[fix](tvf) fix 'frontends()' inconsistent with return 'show proc /fro…

### PR DESCRIPTION
**Pull request by deardeng**
…ntends'

## Proposed changes

fix `select * from frontends()` inconsistent with return `show proc '/frontends'\G`
image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
