### PR TITLE
[feat](stats) Support preheating for stats

### PR DESCRIPTION
**Pull request by Kikyou1997**
# Proposed changes

Load the most recently used stats as FE booted.

StatsCacheLoader will record the column(tblid-idxid-colname) it loaded to a map. This PR add a shutdown hook to FE so that we could write the records in map to the metadata.

When booting, Stats of columns that recorded previously would be loaded by a single thread.

NOTE

This PR add new operation type of log, so the metadata is not backforward compatitable, once user or dev run their FE on the code of this version they cannot rollback to previous FE version.

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Kikyou1997** [comment]
run buildall

**Comment by englefly** [comment]
if there is no history information, can we load some stats on FE startup?

**Comment by Kikyou1997** [comment]
> if there is no history information, can we load some stats on FE startup?

No

**Comment by morrySnow** [comment]
i think just load top k newest column statistics is good enough, log the cache status is not necessary

**Comment by morrySnow** [comment]
and we should load the statistics info after analyze job success immediately

**Comment by Kikyou1997** [comment]
> and we should load the statistics info after analyze job success immediately

This logic already exists currently.

**Comment by englefly** [comment]
> 

if there is no history information, could you just load `k` stats?

**Pull request closed without merging**
