### PR TITLE
[regression-test] add p0/p1 case about partition table

### PR DESCRIPTION
**Pull request by zhangy5**
## Proposed changes

add partition table case:
1. different column types as partition key (p0)
2. create partition table error msg (p0)
3. add/drop partition (p1)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangy5** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by adonis0147 — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
