### PR TITLE
[Enhancement] (nereids)implement alterRoleCommand in nereids

### LINKED ISSUE #42799: [Enhancement] (nereids)implement alterRoleCommand in nereids
alterRole command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following alterRole command in nereids:
unsupportedalterRoleStatement
``` ALTER ROLE role=identifier commentSpec                                        ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

Issue Number: close #42799 

Related PR: #xxx

Problem Summary:

### Check List (For Committer)

- Test 

    - [*] Regression test // done
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?

    - [ ] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]
LGTM

**Review by LiBinfeng-01 — APPROVED** [review]

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
