### PR TITLE
[refactor](mysql result format) use new serde framework to tuple convert

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
use new serde framework to tuple convert

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by amorynan — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
等待2.0的编译镜像更新后合入到2.0分支

**Pull request merged**
