### PR TITLE
[fix](pipelinex) fix fragment instance progress reports

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Fix progress in `show load` not 100% when load finished.

PipelineX has deprecated `fragmentInstanceId` in `TReportExecStatusParams`.
The `finishedScanNums` should be reported with distinct `fragmentInstanceId` to prevent being overwritten.

Before

```
| 38024 | lineitem_dup_1_replication_s3_2 | FINISHED | 30.00% (3/10)     | BROKER | ...
```

After

```
| 39025 | lineitem_dup_1_replication_s3_3 | FINISHED | 100.00% (10/10)   | BROKER | ...
```

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
