### PR TITLE
[fix](spill) disable partitioned agg when group by limit opt is set

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

Disable partitioned agg when group by limit opt is set(#29641)

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
