### PR TITLE
[bugfix](iceberg)revert count(*) directly returned by fe

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

related #34928

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Comment by wuwenchi** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Review by CalvinKirs — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
