### PR TITLE
[feat](Nereids) support set var in hint when parse sql

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
set var hint need to be enable to use before analyze, so it need to be set when parsing sql
now it would set twice when parse and begin of analyze

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run compile

**Comment by LiBinfeng-01** [comment]
run cloud_p0

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run p0

**Pull request merged**
