### PR TITLE
[feature](runtime filter) New session variable runtime_filter_wait_infinitely

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
New session variable: `runtime_filter_wait_infinitely`. If `set runtime_filter_wait_infinitely = true`, consumer of rf will wait on receiving until query is timeout.

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
