### PR TITLE
[fix](group commit) Fix some group commit problems

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

Fix some group commit problems found by https://github.com/apache/doris/pull/26856, includes:
* does not support partial update, empty values(), special sql mode
* stream load group commit does not support two phase commit, set temp partitons

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run clickbench

**Comment by mymeiyi** [comment]
run pipelinex_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
