### PR TITLE
[Fix](function)fix datatime-diff function's overflow

### PR DESCRIPTION
**Pull request by zclllyybb**
# Proposed changes

before:
```
mysql [(none)]>SELECT seconds_diff('3000-01-01 00:00:00', '1000-01-01 00:00:00');
+------------------------------------------------------------+
| seconds_diff('1000-01-01 00:00:00', '3000-01-01 00:00:00') |
+------------------------------------------------------------+
|                                                -1310605440 |
+------------------------------------------------------------+
```
after:
```
mysql [(none)]>SELECT seconds_diff('3000-01-01 00:00:00', '1000-01-01 00:00:00');
+------------------------------------------------------------+
| seconds_diff('1000-01-01 00:00:00', '3000-01-01 00:00:00') |
+------------------------------------------------------------+
|                                                63113904000 |
+------------------------------------------------------------+
```

## Problem Summary

fixed wrong calculate results caused by incorrect datatype usage in datatime-diff functions which lead to signed integer overflow.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Have unit tests been added
* [ ] Has the document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.01 seconds
 stream load tsv:          473 seconds loaded 74807831229 Bytes, about 150 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          27 seconds loaded 861443392 Bytes, about 30 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230221084944_clickbench_pr_100910.html

**Comment by zclllyybb** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
