### PR TITLE
[Chore](docs)Add SSL Faq

### PR DESCRIPTION
**Pull request by irenesrl**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by irenesrl** [comment]
run buildall

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
