### PR TITLE
[fix](subquery) fix bug of using constexpr and some agg func(like count,max) as subquery's output

### LINKED ISSUE #16481: [Bug] 开启向量化后每次执行查询时 be 都会挂
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.5，1.2.1

### What's Wrong?

1.1.5:
在开启向量化后，查询表后会出错，并且必定会有1个 be 会挂掉
关闭向量化后，查询能正常

1.2.1
是否开启向量化，都显示错误结果，查询结果为 0 

### What You Expected?

可以实现正常查询

### How to Reproduce?
`CREATE TABLE `A` (
    `user_id` int NULL
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 3
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
);
CREATE TABLE `B` (
    `user_id` int NULL
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 3
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
);
CREATE TABLE `C` (
    `user_id` int NULL
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 3
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
);
CREATE TABLE `D` (
    `user_id` int NULL
) ENGINE=OLAP
DUPLICATE KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 3
PROPERTIES (
"replication_allocation" = "tag.location.default: 3",
"in_memory" = "false",
"storage_format" = "V2"
);

WITH `W1` AS (
    SELECT t.user_id
    FROM A t
             JOIN B u
                  ON u.user_id = t.user_id
),
     `W2` AS (
         SELECT t.user_id
         FROM `C` t
                  JOIN B u
                       ON u.user_id = t.user_id
         GROUP BY t.user_id
     ),
     `W3` AS (
         SELECT t.user_id
         FROM D t
                  JOIN B u
                       ON u.user_id = t.user_id
         GROUP BY t.user_id
     )
SELECT COUNT(`dataset_30`.`reg_user_cnt`) AS `u_18efaea722a8747c_2`
FROM (
         SELECT t1.reg_user_cnt, t2.commit_case_user_cnt, t3.watch_live_course_and_commit_case_user_cnt
         FROM (
                  SELECT COUNT(user_id) AS reg_user_cnt, '1' AS flag
                  FROM W1
              ) t1
                  JOIN (
             SELECT COUNT(user_id) AS commit_case_user_cnt, '1' AS flag
             FROM W2
         ) t2
                       ON t2.flag = t1.flag
                  JOIN (
             SELECT COUNT(t1.user_id) AS watch_live_course_and_commit_case_user_cnt, '1' AS flag
             FROM W2 t1
                      JOIN W3 t2
                           ON t2.user_id = t1.user_id
         ) t3
                       ON t3.flag = t1.flag
     ) `dataset_30`
    LIMIT 1000;

`

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
…tput

Signed-off-by: nextdreamblue <zxw520blue1@163.com>

# Proposed changes

Issue Number: close #16481 #16534

## Problem summary

pr:#16556，just fix some bug about count()，if select like this:
```
select  max(user_id) from(  select max(user_id), 100 as user_id FROM A  )t;
```
will get wrong resout.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
please add regression test case

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.77 seconds
 stream load tsv:          478 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         37 seconds loaded 2358488459 Bytes, about 60 MB/s
 stream load orc:          68 seconds loaded 1101869774 Bytes, about 15 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230209163734_clickbench_pr_93379.html

**Comment by morningman** [comment]
please add test case

**Comment by nextdreamblue** [comment]
> please add test case

done

**Comment by nextdreamblue** [comment]
> please add regression test case

done

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
