### PR TITLE
[regression] update test framework and fix cases

### PR DESCRIPTION
**Pull request by hello-stephen**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

modify regression test framework in order to support cases from ssb_sf1 tpcds_sf1 tpch_sf1, which I will do in next pr.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Have you tested that how long it takes to run? with 16c 64g single node BE?

**Review by dataroaring — CHANGES_REQUESTED** [review]
You'd better split changes to framework and cases, then if there are problems like cases take a long time, we can revert case without any influence, changes to framework is not easy to revert.  How can developers run cases locally?

**Comment by hello-stephen** [comment]
this pr meets the bug https://github.com/apache/doris/issues/10766 too, maybe need to rebase master when the bug fixed

**Comment by hello-stephen** [comment]
> 
regression test exclude suite test_create_table_with_bloom_filter temporarily

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]

**Pull request merged**
