### PR TITLE
[fix](function)adjust aggregate function's nullable property

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes

in this PR have change some age function nullable property.
aggregate functions can be divided into 3 types by their nullable properties:
- AlwaysNullable
- AlwaysNotNullable
- NullableAggregateFunction

this PR code of FE part from https://github.com/apache/doris/pull/37215, the author is @starocean999

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
