### PR TITLE
[fix](fe) `PrintGCTimeStamps` is not applicable in jdk9+

### PR DESCRIPTION
**Pull request by swjtu-zhanglei**
* we met error when starting fe in openjdk11 """ using java version 11 -Djavax.security.auth.useSubjectCredsOnly=false -Xss4m -Xmx8192m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Dlog4j2.formatMsgNoLookups=true Unrecognized VM option 'PrintGCDateStamps' Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit. """
  * refer to https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-9569449C-525F-4474-972C-4C1F63D5C357
  * the problem is introduced by https://github.com/apache/doris/pull/28263

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SWJTU-ZhangLei** [comment]
#28263

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by SWJTU-ZhangLei** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
