### PR TITLE
[bugfix](txn) return when txn state is null when doing abort txn

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes

follower #17893
When doing broker load, if we encountered one error before the txn starts, then there would be one abort txn rpc. Unfortunately, there is no txn state for the corresponding txn, so the following procedure would throw NPE when accessing the null state.
This pr makes it just return if there is no corresponding txn state.
## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by ByteYue** [comment]
run buildadd

**Comment by ByteYue** [comment]
run buildadd

**Comment by waywtdcc** [comment]
Is there any issue to record this error?

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
