### PR TITLE
[fix](group commit) group commit show error url

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes
 
`insert into` in group commit should show error url if some rows are invalid.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run cloud_p1

**Comment by mymeiyi** [comment]
run p1

**Comment by mymeiyi** [comment]
run external

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
