### PR TITLE
[regression] Add tpch sf1 test under unique table with zstd.

### PR DESCRIPTION
**Pull request by smallhibiscus**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Add tpch sf1 test under unique table with zstd.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Review by yiguolei — CHANGES_REQUESTED** [review]
Have you verified the result and the performance of this test?

**Comment by yiguolei** [comment]
@hello-stephen could you please review this pr?

**Comment by smallhibiscus** [comment]
> Have you verified the result and the performance of this test?

I have verified that it can be passed, and I need @hello-stephen  help and review it again

**Pull request closed without merging**
