### PR TITLE
[chore](routine-load) make routine_load_consumer_pool_size can update using HTTP API

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Make routine_load_consumer_pool_size can update using HTTP API.

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
