### PR TITLE
[opt](Nereids) improve Shape check cases

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
1. fix parallel instance num when running shape check
2. stop auto analyze when running shape check
3. verify column stats during shape check

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
