### PR TITLE
[improvement](tablet report) tablet report increase report version

### PR DESCRIPTION
**Pull request by yujun777**
when be report tablet,  update its report version,  then if fe is handling a stale report, it can quickly discard it.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run beut

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run beut

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run beut

**Comment by yujun777** [comment]
run beut

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run cloud_p0

**Comment by yujun777** [comment]
run p0

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run feut

**Comment by yujun777** [comment]
run beut

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run beut

**Pull request merged**
