### PR TITLE
[chore](conf) Specify UTF8 as the default charset.

### PR DESCRIPTION
**Pull request by yagagagaga**
According the [JEP 400](https://openjdk.org/jeps/400), UTF-8 was be used as the default charset of the JavaSE 18. But when you use the version below 18, the default charset depends on your locale. Usually, it can work well in many sence, but Apache Doris only supports UTF-8 as its charset, which may occur some decoding incorrectly.

So it is necessary to set UTF8 as the default JDK charset.

### CODE REVIEW

**Comment by yagagagaga** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by yagagagaga** [comment]
run cloud_p0

**Comment by yagagagaga** [comment]
run cloud_p1

**Comment by yagagagaga** [comment]
run external

**Comment by yagagagaga** [comment]
run external

**Comment by yagagagaga** [comment]
run external

**Pull request merged**
