### PR TITLE
[bugfox](es-catalog)fix exception when querying ES table

### LINKED ISSUE #26786: [Bug] Exception when querying ES table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

catalog statement

```
CREATE CATALOG es_48 PROPERTIES (
"type"="es",
"hosts"="http://localhost:9200/",
"nodes_discovery"="false"
);
```

java.lang.NumberFormatException: For input string: "9200/"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_351]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_351]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_351]

### What You Expected?

Get results normally

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #26786

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM, but please add UT

**Comment by liugddx** [comment]
> LGTM, but please add UT

Done. PTAL

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run p0

**Comment by liugddx** [comment]
run feut

**Comment by liugddx** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
