### PR TITLE
[improvement](statistics)Support get oracle jdbc row count.

### PR DESCRIPTION
**Pull request by Jibing-Li**
### What problem does this PR solve?

Support get oracle jdbc row count from oracle statistics if exists.

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [x] Confirm the release note
- [x] Confirm test cases
- [x] Confirm document
- [x] Add branch pick label

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run compile

**Review by morrySnow — APPROVED** [review]

**Review by morningman — APPROVED** [review]

**Pull request merged**
