### PR TITLE
[Fix](regression) Fix flaky case `test_schema_change_unique_mow`

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

branch-2.1-pick: https://github.com/apache/doris/pull/39213

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run cloud_p0

**Comment by bobhan1** [comment]
run cloud_p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by sollhui — APPROVED** [review]
LGTM

**Pull request merged**
