### PR TITLE
[Test](regression-test): do not use path style to access s3

### PR DESCRIPTION
**Pull request by Thearas**
## Proposed changes

CP from #35666 and #35725.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xiaokang** [comment]
@Thearas There are some  p0 and external testcases failed. Can you check and fix them?

**Comment by Thearas** [comment]
@xiaokang OK, I will fix it when I get time.

**Comment by Thearas** [comment]
run buildall

**Comment by Thearas** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by Thearas** [comment]
run buildall

**Pull request merged**
