### PR TITLE
[Bug](MTMV) fix waitingMTMVTaskFinished failed at test_mtmv_ssb_ddl

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

fix waitingMTMVTaskFinished failed at test_mtmv_ssb_ddl

```groovy
Exception in mtmv_p0/ssb/test_mtmv_ssb_ddl.groovy(line 33):

    }
    
    def ssb_mtmvs = ["ssb_flat", "ssb_q11", "ssb_q12", "ssb_q13", "ssb_q21", "ssb_q22", "ssb_q23",
                     "ssb_q31", "ssb_q32", "ssb_q33", "ssb_q34", "ssb_q31", "ssb_q42", "ssb_q43"]

    for (String mvName in ssb_mtmvs) {
        sql "drop MATERIALIZED VIEW IF EXISTS ${mvName}"
        println "run mtmv ddl: ${mvName}"
        sql new File("""${context.file.parent}/ddl/${mvName}_create.sql""").text
        waitingMTMVTaskFinished(mvName)
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^
    }
}

Exception:
org.junit.ComparisonFailure: expected:<[SUCCESS]> but was:<[PENDING]>
  at org.junit.Assert.assertEquals(Assert.java:117)
  at org.junit.Assert.assertEquals(Assert.java:146)
```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by SaintBacchus** [comment]
LGTM

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
