### PR TITLE
[enhance](Cooldown) add SessionVariable for enableCooldownReplicaAffinity

### PR DESCRIPTION
**Pull request by cjj2010**
add SessionVariable for enableCooldownReplicaAffinity, Configure document [link](https://github.com/apache/doris-website/pull/1157)
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
Submission error, transfer to another PR https://github.com/apache/doris/pull/41741

**Pull request closed without merging**
