### PR TITLE
[Fix](Error) fix some typo error in code

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

changes:
1,  change havingClauseAfterAnaylzed->havingClauseAfterAnalyzed
2, it it -> it is
3, a item -> an item
4, a extra -> an extra

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Comment by morningman** [comment]
Please describe more

**Comment by GoGoWen** [comment]
> Please describe more

Done

**Comment by GoGoWen** [comment]
run buildall

**Comment by GoGoWen** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
