### PR TITLE
[Test](regression) CCR syncer thrift interface regression test

### PR DESCRIPTION
**Pull request by deadlinefen**
CCR syncer thrift interface regression test

### CODE REVIEW

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Pull request closed without merging**
