### PR TITLE
[improve](stack_trace) avoid print stack trace in group commit

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

as the title

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run build_all

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run p0

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
