### PR TITLE
[fix](doc) remove the description of the removed config serialize_batch

### PR DESCRIPTION
**Pull request by gnehil**
Remove the description of the BE configuration 'serialize_batch' which has been removed

## Proposed changes

Issue Number: close #xxx

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JNSimba — DISMISSED** [review]
LGTM

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
Please rebase the code.

**Comment by gnehil** [comment]
> Please rebase the code.

done

**Comment by luzhijing** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
