### PR TITLE
[improvement](function) switch inet(6)_aton alias origin function

### PR DESCRIPTION
**Pull request by superdiaodiao**
## Proposed changes

Issue Number: close #xxx

Functions related:
- inet_aton
- inet6_aton
- is_ipv4_compat
- is_ipv4_mapped

Before this PR,  **inet(6)_aton** is an alias of **ipv4(6)_string_to_num** like Clickhouse, which will throw an **exception** while handling an **invalid IP address** input.
image

However, in MySQL, inet(6)_aton prefers to ignore the exception and return **NULL**. What's more, two functions, is_ipv4_compat and is_ipv4_mapped in MySQL both nest inet6_aton and return NULL as well.
image

In this PR, after Doris Community's discussion, in order to be more compatible with Clickhouse and MySQL, we switch inet(6)_aton alias origin function **from ipv4(6)_string_to_num to ipv4(6)_string_to_num_or_null**, so that these 4 functions will return NULL with the **invalid IP address** input.
image

Meanwhile, If users still want to have an **exception** while handling the **invalid IP address** input, we suggest  **directly using ipv4(6)_string_to_num**.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by superdiaodiao** [comment]
run buildall

**Comment by superdiaodiao** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
