### PR TITLE
[test](catalog) add upgrade test cases for external catalog

### PR DESCRIPTION
**Pull request by morningman**
1. create hive/iceberg/paimon/jdbc catalog
2. do some queries or ddl, dml after upgrade

- Change `regression-test/README.md` to English

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
