### PR TITLE
(cloud-merge)  Supports online capacity expansion and contraction

### PR DESCRIPTION
**Pull request by Lchangliang**
1. Support to reset capacity online via BE HTTP requet
2. Support to analyze cache conf when only get path_name `file_cache_path=[{"path":"xxxx"}]`, we can only specify the path for a file cache instance from now on, if we don't care about the detailed capacity limit

```
# clear file cache
curl ip:http_port/api/file_cache?op=clear
# reset capacity of a certain instance of file cache
curl ip:http_port/api/file_cache?op=reset&capacity=${capacity}&path=${cache_path} 

curl 127.0.0.1:8060/api/file_cache?op=clear
curl 127.0.0.1:8060/api/file_cache?op=reset&capacity=102400000&path=/user/file_cache
```

### CODE REVIEW

**Comment by Lchangliang** [comment]
run buildall

**Comment by Lchangliang** [comment]
run buildall

**Comment by Lchangliang** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by Lchangliang** [comment]
run cloud_p0

**Comment by Lchangliang** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
