### PR TITLE
[Improve](stats)Use Log4j class library instead of Quartz

### PR DESCRIPTION
**Pull request by CalvinKirs**
Quartz new version not support java 8

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run External Regression (Doris External Regression)

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by CalvinKirs** [comment]
https://github.com/apache/doris/pull/22095 subtask

**Pull request merged**
