### PR TITLE
[improvement](fe) skip attach profile during send fragment

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

Sometime attach profile may cost a lot of time in large machine with many instances.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
