### PR TITLE
(#5151) An already merged rowset should skip window check

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes

An already merged rowset should skip window check
see #5151
## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on (Fix #ISSUE), and have described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caiconghui — APPROVED** [review]
LGTM

**Comment by kangkaisen** [comment]
> It seems that rowset [304123-304140] is missed.
But the truth is [304122-304140] is already merged and its create time is updated when merge finished.
So its create time is even later than [304141-304141].

>But the truth is [304122-304140] is already merged and its create time is updated when merge finished.

I think the `create time` should be immutable, why we need to update `create time when merge finished.?

**Comment by morningman** [comment]
> > It seems that rowset [304123-304140] is missed.
> > But the truth is [304122-304140] is already merged and its create time is updated when merge finished.
> > So its create time is even later than [304141-304141].
> 
> > But the truth is [304122-304140] is already merged and its create time is updated when merge finished.
> 
> I think the `create time` should be immutable, why we need to update `create time when merge finished.?

The `create_time` is not modified.
It just because the rowset with higher version may be created before the rowset will lower version.

For example:

[0-10], [10-15], [16-16]

the create time of [10-15] may be later then [16-16], because the compaction of [10-15] is later than the creation of [16-16]

**Comment by kangkaisen** [comment]
@morningman I  see, thank you.

**Pull request merged**
