### PR TITLE
[fix](function) Fix to_bitmap int parameter causing BE crash

### PR DESCRIPTION
**Pull request by zenoyang**
## Proposed changes

Issue Number: close #xxx
fix #21236 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zenoyang** [comment]
run buildall

**Comment by zenoyang** [comment]
run buildall

**Comment by zenoyang** [comment]
run clickbench

**Comment by BiteTheDDDDt** [comment]
The storage layer of doris does not support nullable bitmap columns, so our bitmap should never be null. If there is something inconsistent with the document, we'd better modify the document instead of modifying the behavior

**Pull request closed without merging**
