### PR TITLE
[Feature](multi-catalog) Add memory tracker for orc reader/writer and arrow parquet writer。

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Feature] (multi-catalog) Add memory tracker for orc reader/writer and arrow parquet writer。

## Future work

- Since the parquet reader is written by ourself and does not use the arrow third-party library, some memory usage needs to be added to the memory track.
- Added read and write operator-level memory tracker to the profile.

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
