### PR TITLE
[fix](cooldown) Fix potential data loss when clone task's dst tablet is cooldown replica

### PR DESCRIPTION
**Pull request by platoneko**
# Proposed changes

Issue Number: close #xxx

## Problem summary

If this replica is cooldown replica, MUST generate a new `cooldown_meta_id` to avoid use `cooldown_meta_id` generated in old cooldown term which may lead to such situation:
Replica A is cooldown replica, cooldown_meta_id=2,
Replica B: cooldown_replica=A, cooldown_meta_id=1
Replica A: full clone Replica B, cooldown_meta_id=1, but remote cooldown_meta is still with cooldown_meta_id=2
After tablet report. FE finds all replicas' cooldowned data is consistent(cooldown_meta_id=1)
Replica A: confirm_unused_remote_files, delete some cooldowned data of cooldown_meta_id=2
Replica B: follow_cooldown_data, cooldown_meta_id=2, data lost

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by platoneko** [comment]
run beut

**Comment by platoneko** [comment]
run feut

**Comment by platoneko** [comment]
run p0

**Comment by platoneko** [comment]
run clickbench

**Comment by dataroaring** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.72 seconds
 stream load tsv:          453 seconds loaded 74807831229 Bytes, about 157 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230319041654_clickbench_pr_116579.html

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by platoneko** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.98 seconds
 stream load tsv:          552 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162195977 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Pull request merged**
