### PR TITLE
[Fix](auto-partition) fix auto partition load lost data in multi sender

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

Before if we have multi sender but some of their sink node have no data of some specific partition, then this sink won't know it has to close it. So tablets channel won't be closed correctly. 
Now change close time needed count to same with open in tablets channel.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zclllyybb** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request closed without merging**
