### PR TITLE
[improve](metrics)Display garbage collector type

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #xxx

image

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run p0

**Comment by liugddx** [comment]
run pipelinex_p0

**Comment by liugddx** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by SWJTU-ZhangLei** [comment]
Can you add a regression case ?

**Comment by liugddx** [comment]
> Can you add a regression case ?

Done. thanks for your reminder.

**Comment by SWJTU-ZhangLei** [comment]
> > Can you add a regression case ?
> 
> Done. thanks for your reminder.

Hi, thanks for your contribution,  ut and regression test is both necessary,  maybe you can refer test_fe_metrics.groovy  to add a regression test

**Comment by liugddx** [comment]
> > > Can you add a regression case ?
> > 
> > 
> > Done. thanks for your reminder.
> 
> Hi, thanks for your contribution, ut and regression test is both necessary, maybe you can refer test_fe_metrics.groovy to add a regression test for covering json and promethes api

Done. thank you for your review

**Comment by liugddx** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
