### PR TITLE
[fix](round) fix round decimal128 overflow

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Issue Number: close #https://github.com/apache/doris/issues/37143

### CODE REVIEW

**Comment by cambyzju** [comment]
rund buildall

**Comment by cambyzju** [comment]
run buildall

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
image
Failed on known problem.

**Review by jacktengg — APPROVED** [review]

**Comment by cambyzju** [comment]
run p0

**Review by yiguolei — APPROVED** [review]

**Comment by cambyzju** [comment]
> @cambyzju Will it synchronize to 2.0.13 and 2.1.5

yes，will backport to 2.0.14 & 2.1.5

**Pull request merged**
