### PR TITLE
[upgrade](thirdparty) upgrade librdkafka from 1.8.2 to 2.0.2

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Some error happen when using routine load
```
[INTERNAL_ERROR]Message at offset XXX might be too large to fetch, try increasing receive.message.max.bytes
```
Refer to https://github.com/confluentinc/librdkafka/issues/2993, we should upgrade librdkafka version to avoid this bug.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Pull request merged**
