### PR TITLE
[test](ut) added UT cases for show backend stmt

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
## Proposed changes

Added UT case for Show Backends Stmt

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
