### PR TITLE
[Enhancement](audit log) Add print audit log sesssion variable

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

For the `insert into` statements during group commit load via JDBC. Printing audit logs can severely impact performance. Therefore, we have introduced a session variable to control whether to print audit logs. It is recommended to turn off audit logs only during group commit load via JDBC.

`enable_prepared_stmt_audit_log=false`

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by mymeiyi — APPROVED** [review]

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
