### PR TITLE
[Fix](paritial update) Fix the case of partial update failing in cloud mode

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Problem: The `test_new_partial_update` case fails to run in cloud mode, but it passes in local mode. 

Reason: In PR #35917, we introduced a new table attribute `enable_mow_light_delete`. When executing schema changes with `alter table set xxx` statements, the local and cloud modes process the logic differently. The cloud mode has its unique processing logic, which was not addressed in the mentioned PR, leading to failures in the cloud environment.

Solution: To resolve the issue, we need to complete the missing schema change logic for the cloud mode. Once this is implemented, the problem should be resolved.

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by zhannngchen** [comment]
remember to update documents in repo:doris-websit

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run performance

**Comment by Yukang-Lian** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Pull request merged**
