### PR TITLE
[improvement][fix](catalog) check required properties when creating catalog and fix jdbc catalog issue

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. Check required properties when creating catalog.

To avoid some strange error when missing required properties

This PR add checks for:
1. hms catalog: check the validation of dfs.ha properties
2. jdbc catalog: check jdbc_url, driver_url, driver_class is set.

2. Fix NPE when init MasterCatalogExecutor
   The MasterCatalogExecutor may be called by FrontendServiceImpl from BE, which does not have ConnectionContext.

3. Add more jdbc url param to resolve Chinese issue

    add `useUnicode=true&characterEncoding=utf-8` by default in jdbc catalog when connecting to MySQL

5. Update FAQ doc of catalog

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.9 seconds
 stream load tsv:          480 seconds loaded 74807831229 Bytes, about 148 MB/s
 stream load json:         39 seconds loaded 2358488459 Bytes, about 57 MB/s
 stream load orc:          68 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          28 seconds loaded 861443392 Bytes, about 29 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230228013314_clickbench_pr_105256.html

**Comment by morningman** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
