### PR TITLE
[feature](streamload) support HTTP request with chunked transfer

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

When I set Transfer-Encoding: chunked in HTTP header and use streamload, it can not work well. Therefore, the goal of this PR is to enable streamload to support chunked transfer in HTTP.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
add a regression test.

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
