### PR TITLE
[fix](function) function DATE_FORMAT get wrong result

### LINKED ISSUE #31524: [Bug] function DATE_FORMAT get wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.5 && master

### What's Wrong?

case:
SELECT DATE_FORMAT('1999-01-01', '%X %V')

wrong result:
```
MySQL [test]> SELECT DATE_FORMAT('1999-01-01', '%X %V');
+-----------------------------------------------------------+
| date_format(cast('1999-01-01' as DATETIMEV2(0)), '%X %V') |
+-----------------------------------------------------------+
| 1999 01                                                   |
+-----------------------------------------------------------+
1 row in set (0.012 sec)
```

mysql right result:
```
mysql> SELECT DATE_FORMAT('1999-01-01', '%X %V');
+------------------------------------+
| DATE_FORMAT('1999-01-01', '%X %V') |
+------------------------------------+
| 1998 52                            |
+------------------------------------+
1 row in set (0.00 sec)
```

### What You Expected?

result same as mysql

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by felixwluo**
## Proposed changes

Issue Number: close #31524

## Further comments
Let the query go be the correct result.
before:
图片

now:
图片

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by felixwluo** [comment]
run buildall

**Review by yiguolei — COMMENTED** [review]
Please  add a regression test to make sure the result is right and stable.

**Comment by morrySnow** [comment]
replace snapshot with text for search engine and git commit message friendly

**Comment by felixwluo** [comment]
run buildall

**Review by zclllyybb — CHANGES_REQUESTED** [review]
Don't drop to BE. should keep it right with https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-format and same logic with BE which in `vdatetime_value.cpp:to_format_string()`

**Pull request closed without merging**
