### PR TITLE
[fix] Implementing match_phrase_edge without index query method (#41658)

### PR DESCRIPTION
**Pull request by zzzxl1993**
https://github.com/apache/doris/pull/41658

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
