### PR TITLE
[fix](multi-catalog)fix paimon meta properties convert

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

1. set default region to 'us-east-1' if no any region can be read
2. add meta properties convert to paimon
3. recognize ip endpoint, and return null for getRegionOfEndpoint method
4. add ut case for meta properties convert

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run feut

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
