### PR TITLE
[fix](cloud) abortTransaction does not handle response code

### PR DESCRIPTION
**Pull request by mymeiyi**

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
