### PR TITLE
[feature-wip](arrow-flight)(step6) Support regression test

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Design Documentation Linked to https://github.com/apache/doris/issues/25514

Regression test add a new group: arrow_flight_sql,
- `./run-regression-test.sh -g arrow_flight_sql` to run regression-test, can use `jdbc:arrow-flight-sql` to run all Suites whose group contains arrow_flight_sql.
- `./run-regression-test.sh -g p0,arrow_flight_sql` to run regression-test, can use `jdbc:arrow-flight-sql` to run all Suites whose group contains arrow_flight_sql, and use `jdbc:mysql` to run other Suites whose group contains p0 but does not contain arrow_flight_sql.

Requires attention, the formats of `jdbc:arrow-flight-sql` and `jdbc:mysql` and `mysql client` query results are different, for example:
- Datatime field type: `jdbc:mysql` returns `2010-01-02T05:09:06`, mysql client returns `2010-01-02 05:09:06`, `jdbc:arrow-flight-sql` also returns `2010-01-02 05:09 :06`.
- Array and Map field types: `jdbc:mysql` returns `["ab", "efg", null]`, `{"f1": 1, "f2": "a"}`, `jdbc:arrow-flight-sql` returns `["ab ","efg",null]`, `{"f1":1,"f2":"a"}`, which is missing spaces.
- Float field type: `jdbc:mysql` and mysql client returns `6.333`, `jdbc:arrow-flight-sql` returns `6.333000183105469`, in query_p0/subquery/test_subquery.groovy.
- If the query result is empty, `jdbc:arrow-flight-sql` returns empty and `jdbc:mysql` returns `\N`. 
- use database; and query should be divided into two SQL executions as much as possible. otherwise the results may not be as expected. For example: USE information_schema; select cast ("0.0101031417" as datetime)  The result is 2000-01-01 03:14:1 (constant fold), select cast ("0.0101031417" as datetime) The result is null (no constant fold), 

In addition, doris `jdbc:arrow-flight-sql` still has unfinished parts, such as:
- Unsupported data type: Decimal256. `INVALID_ARGUMENT: [INTERNAL_ERROR]Fail to convert block data to arrow data, error: [E3] write_column_to_arrow with type Decimal256`
- Unsupported null value of map key. `INVALID_ARGUMENT: [INTERNAL_ERROR]Fail to convert block data to arrow data, error: [E33] Can not write null value of map key to arrow.`
- Unsupported data type: ARRAY<MAP<TEXT,TEXT>>
- `jdbc:arrow-flight-sql` not support connecting to specify DB name, such as`jdbc:arrow-flight-sql://127.0.0.1:9090/{db_name}", In order to be compatible with `regression-test`, `use db_name` is added before all SQLs when `jdbc:arrow-flight-sql` runs regression test.
- `select timediff("2010-01-01 01:00:00", "2010-01-02 01:00:00");`, error `java.lang.NumberFormatException: For input string: "-24:00:00"`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Pull request merged**
