### PR TITLE
[docker](hudi) add hudi docker compose

### PR DESCRIPTION
**Pull request by hechao-ustc**
# Proposed changes

Issue Number: close #xxx

#### 1.Prerequisites
/etc/hosts : The docker compose references many services running in container by the hostname. You had better add the following settings to /etc/hosts

> 127.0.0.1 adhoc-1
127.0.0.1 adhoc-2
127.0.0.1 namenode
127.0.0.1 datanode1
127.0.0.1 hiveserver
127.0.0.1 hivemetastore
127.0.0.1 sparkmaster

#### 2.start docker compose
You can run `${DORIS_HONE}/docker/thirdparties/run-thirdparties-docker.sh -c hudi` to start the hudi container.

> cd doris
./docker/thirdparties/run-thirdparties-docker.sh -c hudi 
...
[+] Running 11/10
 ✔ Container adhoc-1                    Removed                                                                                                                                  10.3s 
 ✔ Container datanode1                  Removed                                                                                                                                  10.4s 
 ✔ Container spark-worker-1             Removed                                                                                                                                   0.0s 
 ✔ Container adhoc-2                    Removed                                                                                                                                  10.3s 
 ✔ Container sparkmaster                Removed                                                                                                                                  10.3s 
 ✔ Container historyserver              Removed                                                                                                                                  10.3s 
 ✔ Container hiveserver                 Removed                                                                                                                                  10.2s 
 ✔ Container hivemetastore              Removed                                                                                                                                   0.6s 
 ✔ Container namenode                   Removed                                                                                                                                  10.3s 
 ✔ Container hive-metastore-postgresql  Removed                                                                                                                                   0.2s 
 ✔ Network hudi_doris--hudi            Removed                                                                                                                                   0.0s 
[+] Running 11/11
 ✔ Network hudi_doris--hudi            Created                                                                                                                                   0.0s 
 ✔ Container hive-metastore-postgresql  Started                                                                                                                                   1.2s 
 ✔ Container namenode                   Started                                                                                                                                   1.3s 
 ✔ Container hivemetastore              Started                                                                                                                                   1.7s 
 ✔ Container historyserver              Started                                                                                                                                   1.8s 
 ✔ Container datanode1                  Started                                                                                                                                   2.3s 
 ✔ Container hiveserver                 Started                                                                                                                                   2.2s 
 ✔ Container sparkmaster                Started                                                                                                                                   2.6s 
 ✔ Container spark-worker-1             Started                                                                                                                                   3.3s 
 ✔ Container adhoc-1                    Started                                                                                                                                   3.5s 
 ✔ Container adhoc-2                    Started                                                                                                                                   3.5s 
...

At this point, the Docker cluster will be up and running. The demo cluster brings up the following services

> HDFS Services (NameNode, DataNode)
> Spark Master and Worker
> Hive Services (Metastore, HiveServer2 along with PostgresDB)
> Adhoc containers to run Hudi/Hive CLI commands

During container startup, `/scripts/setup_demo_container_adhoc_2.sh` will use `/scripts/jar/hoodie-hive-sync-bundle.jar` for hudi data synchronization, which will synchronize data on hdfs to hive with hudi format.

You can also refer to https://hudi.apache.org/docs/quick-start-guide in container  `adhoc-1` to create and write hudi table use spark-sql.

#### 3.Using Doris' catalog
After the container starts, you can create a hudi catalog in doris：
`CREATE CATALOG hudi PROPERTIES (
          'type'='hms',
          'hive.metastore.uris' = 'thrift://localhost:9083',
          'hadoop.username' = 'hive'
);`
then you can query the hudi table.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Hi @hechao-ustc , thanks for you contribution.
There are some issues:

1. Please add more details about how to run this docker in your PR comment, such as how to start container, how to connect to hudi using Doris' catalog feature.
2. Describe the pre-installed data set you uploaded to the hudi container.
3. It is not a good idea to upload large file, such as bundle jar file or data file in github repo. Maybe you can pack them in a zip file and give it to me, I can help you to put it some where for easy downloading

**Comment by hechao-ustc** [comment]
> Hi @hechao-ustc , thanks for you contribution. There are some issues:
> 
> 1. Please add more details about how to run this docker in your PR comment, such as how to start container, how to connect to hudi using Doris' catalog feature.
> 2. Describe the pre-installed data set you uploaded to the hudi container.
> 3. It is not a good idea to upload large file, such as bundle jar file or data file in github repo. Maybe you can pack them in a zip file and give it to me, I can help you to put it some where for easy downloading

Thanks for your comment, I will modify it

**Comment by hechao-ustc** [comment]
> Hi @hechao-ustc , thanks for you contribution. There are some issues:
> 
> 3. It is not a good idea to upload large file, such as bundle jar file or data file in github repo. Maybe you can pack them in a zip file and give it to me, I can help you to put it some where for easy downloading

Hi  @morningman , How can I send you the zip file.

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Pull request merged**
