### PR TITLE
[fix](p2)Fix analyze hive partition column p2 case after row count change.

### PR DESCRIPTION
**Pull request by Jibing-Li**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run pipelinex_p0

**Comment by Jibing-Li** [comment]
run p0

**Comment by Jibing-Li** [comment]
run p0

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
