### PR TITLE
[test] add cast array regression test

### PR DESCRIPTION
**Pull request by yinzhijian**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

add P0 test for #9995
1. cast scalar type(except varchar) to array is not allowed
2. cast array to scalar type is not allowed

## Checklist(Required)

1. Does it affect the original behavior: (No)
3. Has unit tests been added: (Yes)
4. Has document been added or modified: (No Need)
5. Does it need to update dependencies: (No)
6. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
LGTM

**Comment by morningman** [comment]
please rebase to pass the BE ut

**Comment by yinzhijian** [comment]
> please rebase to pass the BE ut

done

**Comment by cambyzju** [comment]
LGTM

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
