### PR TITLE
[optimize](cooldown)If cooldowned_rowsets is empty, there is no need to follow the logic of traversing the files

### PR DESCRIPTION
**Pull request by xingyingone**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
run  buildall

**Review by alexxing662 — APPROVED** [review]
LGTM

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]
LGTM

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run  buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
