### PR TITLE
[refactor](statistics) refactor the related code of analysis info.

### PR DESCRIPTION
**Pull request by weizhengte**
# Proposed changes

No functional changes. this pr add Analysis-related information(AnalysisInfo), including subclasses `AnalysisJobInfo` and `AnalysisTaskInfo`. `AnalysisJobInfo` describes the basic job information, automatic collection, periodic analysis will read this information to trigger the system analysis tasks; `AnalysisTaskInfo` is the specific task execution information.

1. Refactor the related code of AnalysisTaskInfo and add AnalysisJobInfo.
2. Change the col_partitions field to partitions, which stores a mapping from column names to partitions when storing JobInfo and comma-separated partitions when storing TaskInfo.
3. Set some fields can be nullable, more semantically for analysis info.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run feut

**Comment by weizhengte** [comment]
run feut

**Comment by weizhengte** [comment]
run clickbench

**Comment by Kikyou1997** [comment]
I've told you many and many times that DO NOT mix the pipeline fix to a big PR like this....

**Review by Kikyou1997 — CHANGES_REQUESTED** [review]
Since related tests is unstable and has been commented , I think this refactor severely lack tests and shouldn'd be merged

**Comment by weizhengte** [comment]
> I've told you many and many times that DO NOT mix the pipeline fix to a big PR like this....

I did modify unstable p0 in the last PR and also in this PR. This is because I thought that the last pr had solved the problem of p0 instability, and then I was told that it was still unstable when I submitted this pr, so I temporarily commented out this (this pr before the comment p0 is normal success)...

Ok, this really unreasonable (modify the operation of unstable p0 in the feature pr), and I have added a new related p0 pr#19799.

**Comment by weizhengte** [comment]
> Since related tests is unstable and has been commented , I think this refactor severely lack tests and shouldn'd be merged

Of course, this is no problem, I will submit the new pr sorting out the relevant p0 first, and then merge this pr

**Comment by weizhengte** [comment]
> Since related tests is unstable and has been commented , I think this refactor severely lack tests and shouldn'd be merged

Ok, I 'll add related p0 tests before merge

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
> > I've told you many and many times that DO NOT mix the pipeline fix to a big PR like this....
> 
> I did modify unstable p0 in the last PR and also in this PR. This is because I thought that the last pr had solved the problem of p0 instability, and then I was told that it was still unstable when I submitted this pr, so I temporarily commented out this (this pr before the comment p0 is normal success)...
> 
> Ok, this unreasonable (modify the operation of unstable p0 in the feature pr), and I have added a new related p0 pr #19799.

p0 already added, see #19901

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run p0

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Pull request closed without merging**
