### PR TITLE
[chore](remove code) Remove dragonbox related

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
dragonbox is no longer needed for float pointer number serialization. and related session variables is removed

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run cloud_p0

**Comment by zhiqiang-hhhh** [comment]
run cloud_p1

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Review by mrhhsg — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]

**Comment by yiguolei** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
