### PR TITLE
[refactor](nereids) remove old analyzer in StmtExecutionAction

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by morrySnow — COMMENTED** [review]
add some test

**Comment by starocean999** [comment]
run buildall

**Comment by morrySnow** [comment]
run external

**Review by morrySnow — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
