### PR TITLE
[fix](json) fix parsing fails when json key string is empty.

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

This is a very subtle bug that can only be reproduced in a non-AVX2 environment.
```
// USE_AVX2 = false
mysql [(none)]>mysql [(none)]>select cast('{"":1, " ":"v1"}' as json);
+----------------------------------+
| cast('{"":1, " ":"v1"}' as JSON) |
+----------------------------------+
| NULL                             |
+----------------------------------+

//USE_AVX2 = true
mysql [(none)]>select cast('{"":1, " ":"v1"}' as json);
+----------------------------------+
| cast('{"":1, " ":"v1"}' as JSON) |
+----------------------------------+
| {"":1," ":"v1"}                  |
+----------------------------------+
```

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by zclllyybb — COMMENTED** [review]
add comment

**Comment by Mryange** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
