### PR TITLE
[security](log) Don't print password in BaseController

### PR DESCRIPTION
**Pull request by hezhangjian**
## Problem summary
Fix security problem.

## Checklist(Required)

* [x] Does it affect the original behavior
* [x] Has unit tests been added
* [x] Has document been added or modified
* [x] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by Shoothzj** [comment]
@morningman Can this PR being merged? Thanks.

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by Shoothzj** [comment]
@morningman Can this PR being merged? Thanks.

**Comment by Shoothzj** [comment]
ping,  Can this PR being merged? Thanks.

**Comment by LemonLiTree** [comment]
please rebase

**Comment by httpshirley** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by Shoothzj** [comment]
run buildall

**Comment by luzhijing** [comment]
P0 Regression build failed, Please rebase the code.

**Comment by Shoothzj** [comment]
@luzhijing Done. I have been rebased many times. which commit I must include?

**Comment by Shoothzj** [comment]
run buildall

**Pull request merged**
