### PR TITLE
[typo](doc)update config

### PR DESCRIPTION
**Pull request by caoliang-web**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caoliang-web** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by DongLiang-0 — APPROVED** [review]

**Review by CalvinKirs — COMMENTED** [review]
trigger ci

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
