### PR TITLE
[fix](statistics)Fix column cached stats size bug.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Fix column cached stats average size calculate bug. Average size is double type, when calculating, it is calculated by totalSize/rowCount. We need to cast totalSize to double, otherwise the result is not accurate, only keep the integer part.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by keanji-x — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run performance

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
