### PR TITLE
[fix](datatype) fix bugs for IPv4/v6 datatype and add some basic regression test cases

### PR DESCRIPTION
**Pull request by sjyango**
## Proposed changes

- support `runtime predicate` for ip datatype in order to execute limit and offset in sort sql.
- support `min` and `max` agg functions for ip datatype in order to execute aggregation.
- modify the sorting algorithm for IPv6 types in order to conform to human reading habits.
- add some basic regression test cases including `order by`, `join`, `group by` etc.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Comment by sjyango** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
