### PR TITLE
[fix](mtmv)Fix slot desc wrong in query rewrite by materialized view when query is complex

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes
If query is very complex such as it has multi union and each union has join subquery.
In this scane, query rewrite by materialized view is sucessful but exec may fail with the reason  
`couldn't resolve slot descriptor 239, desc: tuples:`

this is brought by https://github.com/apache/doris/pull/33362

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — COMMENTED** [review]
add case

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run performance

**Review by keanji-x — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
