### PR TITLE
[Enhancement](compaction) Do not set failure time when cumulative compaction dealing with delete rowset

### PR DESCRIPTION
**Pull request by Yukang-Lian**
### What problem does this PR solve?

Problem Summary:

Before this PR, in cases where there is an alternating distribution of data rowset -> delete rowset -> data rowset -> delete rowset, cumulative compaction would only move the cumulative point forward to allow base compaction to handle the delete rowset. Cumulative compaction itself would not process the data and would return be marked as failure. This would cause the compaction submission task process to pause for 5 seconds, impacting efficiency. 

This PR modifies the return status to OK for such cases, which improves the efficiency of the compaction submission task.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by Yukang-Lian** [comment]
run beut

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Review by luwei16 — COMMENTED** [review]
Continuous deletes (without inserts) will cause a 5-second interval for tablet compaction?

**Review by luwei16 — APPROVED** [review]

**Review by luwei16 — COMMENTED** [review]
Use error codes to distinguish failure, no suite version, and delete.

**Pull request merged**
