### PR TITLE
[fix](clone) Fix clone and alter tablet use same tablet path #34889

### PR DESCRIPTION
**Pull request by deardeng**
cherry pick from #34889

### CODE REVIEW

**Comment by deardeng** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Comment by yujun777** [comment]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Pull request merged**
