### PR TITLE
[Fix](inverted index) fix empty array index writer bug

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

> ERROR 1105 (HY000) at line 2: errCode = 2, detailMessage = (172.30.0.88)[CANCELLED][INTERNAL_ERROR]failed to initialize storage reader. tablet=19538088.469892275.52f8f52df572453e-a81173716e4750d0, res=[E-6002]CLuceneError occured: MultiSegmentReader::getIndexVersion index open failed., backend=172.30.0.88
> 0. be/src/common/stack_trace.cpp:302: StackTrace::tryCapture() @ 0x000000000bb10f07 in be/lib/doris_be
> 1. be/src/common/stack_trace.h:0: doris::get_stack_trace[abi:cxx11]() @ 0x000000000bb0f38a in be/lib/doris_be
> 2. /home/ubuntu/ldb16/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:187: doris::Status doris::Status::Error<true>(int, std::basic_string_view<char, std::char_traits<char> >) @ 0x000000000afb06bb in be/lib /doris_be

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by qidaye** [comment]
It's better to provide the bug stacktrace .

**Pull request merged**
