### PR TITLE
[typo](docs) update document syntax and add links to referenced articles

### PR DESCRIPTION
**Pull request by vinlee19**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by vinlee19** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by liujiwen-up — APPROVED** [review]

**Pull request merged**
