### PR TITLE
[feature](Nereids) support set and use statement syntax only

### PR DESCRIPTION
**Pull request by morrySnow**
This PR:
1. add a new Command type: UnsupportedCommand to handle the statement only support parse but could not execute.
2. support syntax about set and use
3. add keyword VAULT to follow legacy planner

TODO
1. support all statment syntax in Nereids

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Review by 924060929 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
