### PR TITLE
[test](regression) add flink sync db case

### PR DESCRIPTION
**Pull request by JNSimba**
## Problem summary

add flink sync db case
1. Mock cdc sync data write
2. Contains multi-table import, adding and subtracting columns

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run p0

**Comment by JNSimba** [comment]
run p0

**Review by caoliang-web — APPROVED** [review]

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
