### PR TITLE
[fix](insert) improve group_commit related tests

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

1. Check if the group_commit related tests is executed by group commit or not.
2. Make the commit interval configurable: `group_commit_interval_seconds`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run p0

**Comment by mymeiyi** [comment]
run compile p0

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by hust-hhb** [comment]
LGTM

**Review by hust-hhb — APPROVED** [review]
LGTM

**Pull request merged**
