### PR TITLE
[improvement](external catalog)Optimize the process of refreshing catalog for 2.1 (#39205)

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

bp: #39205

When the catalog attributes have not changed, refreshing the catalog only requires processing the cache, without rebuilding the entire catalog.

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run feut

**Pull request merged**
