### PR TITLE
[typo](docs)Changes to expressions

### PR DESCRIPTION
**Pull request by echo-hhj**
Changed the evaluation expression.

### CODE REVIEW

**Review by liujiwen-up — APPROVED** [review]

**Comment by echo-hhj** [comment]
run buildall

**Review by catpineapple — APPROVED** [review]

**Comment by echo-hhj** [comment]
run buildall

**Comment by echo-hhj** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Comment by echo-hhj** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
