### PR TITLE
[community](collaborator) add collaborator wm1581066 for issue and pr label

### PR DESCRIPTION
**Pull request by xiaokang**
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xiaokang** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
