### PR TITLE
[Enhance](regression)enhance jdbc case to adapt to use case concurrency

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

Issue Number: close #xxx

enhance jdbc case to adapt to use case concurrency

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zhangguoqiang666 — COMMENTED** [review]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
