### PR TITLE
[fix](vectorization) fix gcc compile failed

### PR DESCRIPTION
**Pull request by caizj**
issue: https://github.com/apache/doris/issues/31993

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caizj** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by HappenLee** [comment]
LGTM

**Comment by caizj** [comment]
run cloud_p1

**Review by adonis0147 — APPROVED** [review]

**Comment by caizj** [comment]
run buildall

**Comment by caizj** [comment]
run buildall

**Pull request closed without merging**
