### PR TITLE
[improvement](test)Set compile required and add clickbench,arm to buildall

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
# Proposed changes

## Problem summary

Describe your changes.

## Checklist(Required)

* [ no] Does it affect the original behavior
* [ no] Has unit tests been added
* [ no] Has document been added or modified
* [ no] Does it need to update dependencies
* [ yes] Is this PR support rollback (If NO, please explain WHY)

## Further comments

1. when pr comment contains run buildall,  trigger  clickbench and arm pipeline at the sametime
2.set compile pipeline required, when merge to master it will be checked

### CODE REVIEW

**Comment by ZhangGuoqiang666** [comment]
please run buildall for this change

**Comment by morningman** [comment]
run buildall

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Comment by ZhangGuoqiang666** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by ZhangGuoqiang666** [comment]
run clickbench

**Pull request merged**
