### PR TITLE
[test](executor) Open Workload group switch in PR pipeline

### PR DESCRIPTION
**Pull request by wangbo**
Open Workload group switch in PR pipeline

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
