### PR TITLE
[fix](inverted index) add in list to fast execute logic after hit index

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

https://github.com/apache/doris/pull/35344
https://github.com/apache/doris/pull/36085

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Review by xiaokang — CHANGES_REQUESTED** [review]
please add testcase

**Comment by zzzxl1993** [comment]
run p0

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run p1

**Comment by zzzxl1993** [comment]
run compile

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]

**Pull request merged**
