### PR TITLE
[fix](planner)implicit cast should use type member variable instead of targetTypeDef

### PR DESCRIPTION
**Pull request by starocean999**
## Proposed changes

for implicit cast, only type member variable is set and targetTypeDef is null. So we should not access targetTypeDef member if it's an implicit cast

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by starocean999** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by starocean999** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
