### PR TITLE
[Opt](func) opt the percentile func performance

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Before：
```
select app_name ,PERCENTILE(duration, 0.5), count() from test group by 1;
+---------------+-------------------------------------------+----------+
| app_name      | percentile(duration, cast(0.5 as DOUBLE)) | count(*) |
+---------------+-------------------------------------------+----------+
| ddd   |                       -2453840367977893.5 |  3562878 |
| bbb |                        2927619961908628.5 |  3561875 |
| NULL          |                   -1.3121945030076114e+16 |   375247 |
+---------------+-------------------------------------------+----------+
3 rows in set (10.75 sec)
```

After：
```
select app_name ,PERCENTILE(duration, 0.5), count() from test group by 1;
+---------------+-------------------------------------------+----------+
| app_name      | percentile(duration, cast(0.5 as DOUBLE)) | count(*) |
+---------------+-------------------------------------------+----------+
| ddd   |                       -2453840367977893.5 |  3562878 |
| bbb |                        2927619961908628.5 |  3561875 |
| NULL          |                   -1.3121945030076114e+16 |   375247 |
+---------------+-------------------------------------------+----------+
3 rows in set (0.75 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Pull request merged**
