### PR TITLE
[regression-test](load) add streamload default value test

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

add streamload default value test:
DEFAULT "XX"
DEFAULT CURRENT_TIMESTAMP

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run clickbench

**Comment by freemandealer** [comment]
run p1

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Pull request merged**
