### PR TITLE
[Feature](nereids) Support Mark join

### LINKED ISSUE #14314: [Feature] (Nereids) mark join for subquery in disjunctions
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

we need to support filter like that
```sql
a.c1 IN (SELECT c1 FROM b) OR a.c2 > 5
```

https://emmymiao87.github.io/jekyll/update/2021/07/25/Mark-Join.html

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #16572: [Enhancement](Nereids) type coercion on subquery when bind
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

currently, we do typecoercion twice. First one in bind stage, second one after subquery unnest.
The reason is we cannot do type coersion on SubqueryExpr and reserve it when it convert to apply and join.

### Solution

do typecoercion on subqueryExpr when binding and remove the second type coercion.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhengshiJ**
# Proposed changes

Issue Number: close #16572 , close #14314

## Problem summary

1.The new optimizer supports the combination of subquery and disjunction.In the way of MarkJoin, it behaves the same as the old optimizer. For design details see:https://emmymiao87.github.io/jekyll/update/2021/07/25/Mark-Join.html.
2.Implicit type conversion is performed when conjects are generated after subquery parsing
3.Convert the unnesting of scalarSubquery in filter from filter+join to join + Conjuncts.
eg:
unCorrelator
`EXPLAIN logical plan SELECT * FROM sub_query_correlated_subquery1 WHERE k1 > (SELECT AVG(k1) FROM sub_query_correlated_subquery3);`
before
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LogicalProject ( projects=[k1#0, k2#1], excepts=[], canEliminate=true )                                                                                                                                                                          |
| +--LogicalFilter ( predicates=(cast(k1#0 as DOUBLE) > AVG(k1)#7))                                                                                                                                                                                |
| +--LogicalJoin ( type=CROSS_JOIN, markJoinSlotReference=Optional.empty, hashJoinConjuncts=[], otherJoinConjuncts=[] )                                                                                                                            |
|    |--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery1, output=[k1#0, k2#1], indexName=sub_query_correlated_subquery1, selectedIndexId=29014, preAgg=ON )                            |
|    +--LogicalAssertNumRows ( assertNumRowsElement=AssertNumRowsElement ( desiredNumOfRows=1, assertion=EQ ) )                                                                                                                                    |
|       +--LogicalAggregate ( groupByExpr=[], outputExpr=[avg(k1#2) AS `AVG(k1)`#7], hasRepeat=false )                                                                                                                                             |
|          +--LogicalProject ( projects=[k1#2], excepts=[], canEliminate=true )                                                                                                                                                                    |
|             +--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery3, output=[k1#2, k2#3, k3#4, v1#5, v2#6], indexName=sub_query_correlated_subquery3, selectedIndexId=29024, preAgg=ON ) |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
after
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LogicalProject ( projects=[k1#0, k2#1], excepts=[], canEliminate=true )                                                                                                                                                                          |
| +--LogicalJoin ( type=CROSS_JOIN, markJoinSlotReference=Optional.empty, hashJoinConjuncts=[], otherJoinConjuncts=[(cast(k1#0 as DOUBLE) > AVG(k1)#7)] )                                                                                          |
|    |--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery1, output=[k1#0, k2#1], indexName=sub_query_correlated_subquery1, selectedIndexId=29014, preAgg=ON )                            |
|    +--LogicalAssertNumRows ( assertNumRowsElement=AssertNumRowsElement ( desiredNumOfRows=1, assertion=EQ ) )                                                                                                                                    |
|       +--LogicalAggregate ( groupByExpr=[], outputExpr=[avg(k1#2) AS `AVG(k1)`#7], hasRepeat=false )                                                                                                                                             |
|          +--LogicalProject ( projects=[k1#2], excepts=[], canEliminate=true )                                                                                                                                                                    |
|             +--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery3, output=[k1#2, k2#3, k3#4, v1#5, v2#6], indexName=sub_query_correlated_subquery3, selectedIndexId=29024, preAgg=ON ) |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Correlator
`EXPLAIN logical plan SELECT * FROM sub_query_correlated_subquery1 WHERE k1 > (SELECT AVG(k1) FROM sub_query_correlated_subquery3 and sub_query_correlated_subquery1.k1 = sub_query_correlated_subquery3.k1);`
before
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LogicalProject ( projects=[k1#0, k2#1], excepts=[], canEliminate=true )                                                                                                                                                                          |
| +--LogicalFilter ( predicates=(cast(k1#0 as DOUBLE) > AVG(k1)#7))                                                                                                                                                                                |
| +--LogicalJoin ( type=LEFT_OUTER_JOIN, markJoinSlotReference=Optional.empty, hashJoinConjuncts=[], otherJoinConjuncts=[] )                                                                                                                        |
|    |--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery1, output=[k1#0, k2#1], indexName=sub_query_correlated_subquery1, selectedIndexId=29014, preAgg=ON )                            |
|    +--LogicalAssertNumRows ( assertNumRowsElement=AssertNumRowsElement ( desiredNumOfRows=1, assertion=EQ ) )                                                                                                                                    |
|       +--LogicalAggregate ( groupByExpr=[], outputExpr=[avg(k1#2) AS `AVG(k1)`#7], hasRepeat=false )                                                                                                                                             |
|          +--LogicalProject ( projects=[k1#2], excepts=[], canEliminate=true )                                                                                                                                                                    |
|             +--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery3, output=[k1#2, k2#3, k3#4, v1#5, v2#6], indexName=sub_query_correlated_subquery3, selectedIndexId=29024, preAgg=ON ) |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
after
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LogicalProject ( projects=[k1#0, k2#1], excepts=[], canEliminate=true )                                                                                                                                                                          |
| +--LogicalJoin ( type=LEFT_SEMI_JOIN, markJoinSlotReference=Optional.empty, hashJoinConjuncts=[], otherJoinConjuncts=[(cast(k1#0 as DOUBLE) > AVG(k1)#7)] )                                                                                      |
|    |--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery1, output=[k1#0, k2#1], indexName=sub_query_correlated_subquery1, selectedIndexId=29014, preAgg=ON )                            |
|    +--LogicalAssertNumRows ( assertNumRowsElement=AssertNumRowsElement ( desiredNumOfRows=1, assertion=EQ ) )                                                                                                                                    |
|       +--LogicalAggregate ( groupByExpr=[], outputExpr=[avg(k1#2) AS `AVG(k1)`#7], hasRepeat=false )                                                                                                                                             |
|          +--LogicalProject ( projects=[k1#2], excepts=[], canEliminate=true )                                                                                                                                                                    |
|             +--LogicalOlapScan ( qualified=default_cluster:regression_test_nereids_syntax_p0.sub_query_correlated_subquery3, output=[k1#2, k2#3, k3#4, v1#5, v2#6], indexName=sub_query_correlated_subquery3, selectedIndexId=29024, preAgg=ON ) |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```


## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run nereids_p0

**Comment by zhengshiJ** [comment]
run p0
run nereids_p0

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run p0

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run p0

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run buildall

**Comment by zhengshiJ** [comment]
run p0

**Comment by zhengshiJ** [comment]
run p0

**Comment by zhengshiJ** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
