### PR TITLE
Support for AuthSwitchRequest In HandShakePacket to better support MySQL 8.0 clients

### LINKED ISSUE #5384: [Proposal] Support for AuthSwitchRequest In HandShakePacket to better support MySQL 8.0 clients
**Is your feature request related to a problem? Please describe.**

Connecting with a MySQL Client after the version of 8.0.4 to Doris could results in an error.
This is because Doris doesn't support the AuthSwitchRequest packets.

MySQL 8.0.4 client to Drois:
```
Drois  ->: Authentication Plugin: mysql_native_password
Client <-: Client Auth Plugin: caching_sha2_password
Doris  ->: MySQL Error 2012 (HY000): Password check failed.
```

MySQL 8.0.4 client to MySQL 5.x:
```
Mysql ->: Authentication Plugin: mysql_native_password
Client <-: Client Auth Plugin: caching_sha2_password
Mysql ->: Auth Switch Request: Auth Method Name: mysql_native_password
Client <-:  Auth Switch Response
Mysql ->:OK
```

**Describe the solution you'd like**

Support Auth Switch Request in Doris

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

RT

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #5384 ) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If these changes need document changes, I have updated the document
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by yangzhg — DISMISSED** [review]
LGTM

**Review by morningman — APPROVED** [review]
+1

**Comment by EmmyMiao87** [comment]
Due to the upgrade of the mysql protocol, if the user uses the 5.1 version of the client, it will lose the connection with the Mysql server during the query problem.
It can be seen from the warning log of fe that there are similar
```
2021-03-19 15:32:56,508 WARN (doris-mysql-nio-pool-486|1023) [MysqlChannel.fetchOnePacket():154] receive packet sequence id[0] want to get[3]
2021-03-19 15:32:56,508 WARN (doris-mysql-nio-pool-486|1023) [AcceptListener.lambda$handleEvent$1():83] connect processor exception because
java.io.IOException: Bad packet sequence.
        at org.apache.doris.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:155) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.MysqlProto.negotiate(MysqlProto.java:209) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:63) ~[palo-fe.jar:3.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

The solution is: 
Upgrade mysql client to 5.7.
Here is the installation package： https://cloud.baidu.com/doc/PALO/s/qkizg0xdw

**Comment by KeithTt** [comment]
which version contains this pr? I do not find this pr number in the release notes..

**Pull request merged**
