### PR TITLE
Support schema keyword to be compatible with the mysql syntax

### PR DESCRIPTION
**Pull request by caiconghui**

### CODE REVIEW

**Comment by caiconghui** [comment]
for #3115

**Review by morningman — DISMISSED** [review]
LGTM, but could you add a unit test for this syntax? You can just add it in QueryPlanTest.java, by creating a database using this new syntax.

**Comment by caiconghui** [comment]
> LGTM, but could you add a unit test for this syntax? You can just add it in QueryPlanTest.java, by creating a database using this new syntax.

OK

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
