### PR TITLE
[refactor](reader) refactor broker_file_reader to get _client in the constructor

### PR DESCRIPTION
**Pull request by luozenglin**
# Proposed changes

Issue Number: close #xxx

related pr: #15874

## Problem summary

In #15874, @HappenLee's comment is valid. There is no problem getting the client in the constructor and the logic is much clearer. 

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.74 seconds
 load time: 500 seconds
 storage size: 17122133646 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230117164027_clickbench_pr_82594.html

**Comment by luozenglin** [comment]
@HappenLee cc

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by TangSiyang2001** [comment]
The connection held in broker reader will be null after reopen the connection to the broker failed.

**Pull request merged**
