### PR TITLE
[opt](Nereids) use enable_nereids_dml to control ctas and create table

### PR DESCRIPTION
**Pull request by morrySnow**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Comment by morrySnow** [comment]
run p1

**Comment by morrySnow** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
