### PR TITLE
[branch-1.2-lts](memtable) change memtable flush error code

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
BE UT failed

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
@morningman The clang ut is error, is this in line with expectations？

**Pull request merged**
