### PR TITLE
[Chore](build) ignore compile warning on orc && fix invalid command curdate on conf

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

1. ignore compile warning on orc
2. fix invalid command curdate on conf
图片

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run p0

**Review by adonis0147 — APPROVED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
run arm

**Pull request merged**
