### PR TITLE
[Bug] [Memtracker] DCHECK failed in vetorized exec engine fold constant execute

### LINKED ISSUE #9353: [Bug] [Memtracker] DCHECK failed in vetorized exec engine fold constant execute
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

DCHECK faild in fold const expr. call memtracker before init operation cause nullptr of memtracker

### What You Expected?

DCHECK pass

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HappenLee**
# Proposed changes

Issue Number: close #9353

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (Yes)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
The tag should be dev/backlog, because the mem tracker related pr is not in dev/1.01.

**Comment by xinyiZzz** [comment]
Is this the newly added vectorized UT? @HappenLee

**Comment by HappenLee** [comment]
> Is this the newly added vectorized UT? @HappenLee

yes, now run-regression will core，if open fold constant expr. not only vectorized

**Comment by xinyiZzz** [comment]
> > Is this the newly added vectorized UT? @HappenLee
> 
> yes, now run-regression will core，if open fold constant expr. not only vectorized

OK,
I don't have open fold constant expr, I will test more.

**Pull request merged**
