### PR TITLE
[fix](case) ensure jar downloaded

### PR DESCRIPTION
**Pull request by hello-stephen**
1. ensure jar downloaded
2. use different user name to avoid conflict

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run p0

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
