### PR TITLE
[fix](broker load) sync the workflow of BrokerScanner to other Scanner to avoid oom

### LINKED ISSUE #9185: [Bug] load orc format bitmap by broker load will exhaust memory
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15

### What's Wrong?

Load bitmap from orc format data source by brokerload. The memory will increase slowly. Maybe 10 bytes every bitmap record.

### What You Expected?

The memory don't increase continuously.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SleepyBear96**
# Proposed changes

Issue Number: close #9185 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Hi @SleepyBear96 Please also create an issue to describe the problem you solved.

**Comment by SleepyBear96** [comment]
> Hi @SleepyBear96 Please also create an issue to describe the problem you solved.

Done.

**Review by HappenLee — COMMENTED** [review]
If both of all child scanner have same method， you better impl the funciton in `BaseScanner`

**Comment by SleepyBear96** [comment]
> If both of all child scanner have same method， you better impl the funciton in `BaseScanner`

Done.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
