### PR TITLE
[fix](DOE)es catalog not working with pipeline,datetimev2, array and esquery

### LINKED ISSUE #21853: [Bug] 'Unsupported exec type in pipeline: ES_HTTP_SCAN_NODE' when query es catalog
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris version is 2.0-beta. When I use master (2023-07-16), this bug still exists. 

### What's Wrong?

When I query es catalog, doris will return the following error: 'Unsupported exec type in pipeline: ES_HTTP_SCAN_NODE'.

If add ES_HTTP_SCAN_NODE in be/src/pipeline/pipeline_fragment_context.cpp:_build_pipelines, then query es catalog's test1 table, Doris will return the following error:
1. select  test7 from test1;   ->  Expected value of type: DATETIMEV2; but found type: Number; Document slice is : 1659931810000
3. select c_keyword from test1; -> UNAVAILABLE: Network closed for unknown reason. (BE crash)

### What You Expected?

return normally

### How to Reproduce?

1. use doris docker command to start es:  ``` cd doris/docker/thirdparties; sh run-thirdparties-docker.sh -c es ```
2. ``` CREATE CATALOG es PROPERTIES ( "type"="es", "hosts"="http://127.0.0.1:29200"); ```
3. ``` switch es; show tables; select  test7 from test1; ```
4. ``` select  test8 from test1; ```
5. ``` select c_keyword from test1; ```

### Anything Else?

Other relate issue is : #21847

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

Issue Number: close #21853
1. fix es catalog is not working with pipeline
2. fix datetime convert bugs
3. fix doc_value_fields not working with Doris Array.
4. fix esquery function not working

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.02 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17169069615 Bytes

**Comment by qidaye** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.2 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17162334816 Bytes

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
