### PR TITLE
[enhancement](Nereids)support max function

### PR DESCRIPTION
**Pull request by xiaojunjie**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. add max function

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [X] No
    - [ ] I don't know
2. Has unit tests been added:
    - [X] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [X] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [X] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [X] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — COMMENTED** [review]
please add a regression test to make sure this function could work correctly

**Comment by yinzhijian** [comment]
LGTM

**Review by yinzhijian — DISMISSED** [review]

**Review by yinzhijian — DISMISSED** [review]
LGTM

**Review by 924060929 — DISMISSED** [review]
LGTM

**Review by yinzhijian — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
