### PR TITLE
[fix]Replace the failed Spark Doris connector link

### LINKED ISSUE #27679: [Bug] Spark doris connector link failure
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

image

### What You Expected?

link to https://doris.apache.org/zh-CN/docs/ecosystem/spark-doris-connector

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cjj2010**
Replace the failed Spark Doris connector link

## Proposed changes

Issue Number: close #27679

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cjj2010** [comment]
Fixed document error link, could you please review it @morningman

**Comment by LemonLiTree** [comment]
run buildall

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Comment by cjj2010** [comment]
If you have time, please agree to this PR. Thank you @JNSimba

**Pull request closed without merging**
