### PR TITLE
[typo](doc)code comment fix

### PR DESCRIPTION
**Pull request by mongo360**
# Proposed changes
fix wrong code commend 
Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ no ] Does it affect the original behavior
* [ no ] Has unit tests been added
* [ yes ] Has document been added or modified
* [ no ] Does it need to update dependencies
* [ yes ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by jackwener — APPROVED** [review]

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Pull request merged**
