### PR TITLE
[fix](Nereids) set operation children output order not same

### PR DESCRIPTION
**Pull request by morrySnow**
we generate project for all set operation's children to ensure the order of all children are not changed. However, some rules, such as PushDownProjectThroughLimit could remove these projects involuntarily. When it happen, the column order maybe wrong and lead to BE core dump. This PR use a new variable in SetOperation to save the output order of children of set operation. Then the children's output order could be changed and never affect to SetOperation at all.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by jackwener — APPROVED** [review]

**Pull request merged**
