### PR TITLE
[Fix](regression-test) Fix `test_group_commit_stream_load_with_nonexist_db_and_table` regression test case

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run p0

**Comment by Yukang-Lian** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
