### PR TITLE
[Fix](regression) fix wrong regression result

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by shuke987** [comment]
run compile

**Comment by yiguolei** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run compile

**Comment by shuke987** [comment]
run compile

**Review by shuke987 — APPROVED** [review]

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
