### PR TITLE
[fix](ddl) check view name by table name regex when create

### LINKED ISSUE #13242: [Bug] create view need check table by table name regex
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master-63903136c492733449030ba222ce36ade152f2e8

### What's Wrong?

When create view, it can create name like '111mv1', but return error when create table or MATERIALIZED VIEW.

MySQL [test]> CREATE VIEW 111mv1 AS SELECT aaa,sum(abc) as abc FROM testmv;
Query OK, 0 rows affected (4.25 sec)

MySQL [test]> show tables;
+--------------------+
| Tables_in_test     |
+--------------------+
| 111mv1             |
| testmv             |
+--------------------+

MySQL [test]> CREATE MATERIALIZED VIEW 11111mv1 AS SELECT aaa,sum(abc) as abc FROM testmv;
ERROR 1103 (42000): errCode = 2, detailMessage = Incorrect table name '11111mv1'. Table name regex is '^[a-zA-Z][a-zA-Z0-9_]*$'

### What You Expected?

check view name when create

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
Signed-off-by: nextdreamblue <zxw520blue1@163.com>

# Proposed changes

Issue Number: close #13242

## Problem summary

add check view name by table name regex when create.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Please add some unit test

**Comment by nextdreamblue** [comment]
> Please add some unit test

add unit test done, please review again

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
