### PR TITLE
[Fix](compile) fix lost header on arm platform

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run arm

**Comment by zclllyybb** [comment]
run arm

**Comment by hello-stephen** [comment]
run arm

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by hello-stephen — APPROVED** [review]

**Pull request merged**
