### PR TITLE
[typo][doc]modify tablet_repair_and_balance incorrect parameter description.

### PR DESCRIPTION
**Pull request by ixzc**
…iptions.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ixzc** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
