### PR TITLE
[fix](FileCache) the logic of selecting the cache path is reversed

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Bug was introduced by https://github.com/apache/doris/pull/23881/files
The logic of selecting the cache path is reversed, and `BE` will be crashed when enable file cache.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — COMMENTED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]

**Pull request merged**
