### PR TITLE
[improvement](start script) start script can not set http proxy

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

be clone snapshot using http,  if set http proxy, then be clone snapshot will failed.  so the start script forbit set env http proxy.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
