### PR TITLE
[feature](CANCEL-ALTER-SYSTEM)decommission backend by ids

### LINKED ISSUE #23636: [Feature] drop or decommission backend by ids
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

when we need dropping backends,  we should use sql like 
`ALTER SYSTEM DECOMMISSION BACKEND "host:heartbeat_port"[,"host:heartbeat_port"...];
`
this sql means we should copy ip and port.
so can we drop backend by backend id?
Actually, when backend is registered by cluster, may dropping or decommisioning by id may be a good choice.

### Use case

enhancement, not problem.

### Related issues

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #23636 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
@zy-kkk PTAL

**Comment by liugddx** [comment]
@morningman PTAL

**Review by morningman — COMMENTED** [review]
Need to add UT for this case.
You can refer to `TabletRepairAndBalanceTest` to create a mocked backends cluster in FE UT framework

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]

**Comment by morningman** [comment]
run clickbench

**Comment by liugddx** [comment]
run clickbench

**Comment by liugddx** [comment]
run clickbench

**Pull request merged**
