### PR TITLE
[docs](help) remove sql manual

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

The document has been moved to doris-website repo last week.
And we are planning to move the sql-manual docs too.

But sql-manual docs is used for `help` operation, that is, when you execute `help` in mysql client.
It will show the docs of corresponding command.

In this PR, I temporarily remove the build of help-resource.zip, so that the help command can not be used.
After this, the `sql-manual` doc will be moved to `doris-website`.
We will find a way to enable `help` command again.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by KassieZ — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
