### PR TITLE
[fix](partial update) fix data correctness risk when load delete sign data into a table with sequence col

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

In the current implementation of partial column update, in order to improve the efficiency of the load job, for rows
 with delete sign, will automatically ignore the missing columns of the data complement, but when the table has sequence columns, the sequence columns are required to complement.
If a row is written with a delete sign, but the sequence columns are not filled in, the merge-on-read policy compaction will result in incorrect data.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
