### PR TITLE
[chore](cloud) Add ClearFileCacheAction to cloud http service

### PR DESCRIPTION
**Pull request by gavinchou**

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by ByteYue — APPROVED** [review]

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
close because already merged.

**Pull request closed without merging**
