### PR TITLE
[Feautre]add backend_memory_tracker table

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
Add a schema table ```backend_memory_tracker```,  we can get be memtracker details in FE.
```
mysql [information_schema]>select * from backend_memory_tracker;
+-------+------------+--------------------------------------------+-------------------+--------------+----------------+--------------+
| BE_ID | TYPE       | LABEL                                      | PARENT_LABEL      | MEMORY_LIMIT | CURRENT_MEMORY | PEAK_MEMORY  |
+-------+------------+--------------------------------------------+-------------------+--------------+----------------+--------------+
| 10005 | overview   | other                                      |                   |           -1 |              0 |            0 |
| 10005 | overview   | schema_change                              |                   |           -1 |              0 |            0 |
| 10005 | overview   | compaction                                 |                   |           -1 |      146462182 |    288876074 |
| 10005 | overview   | load                                       |                   |           -1 |              0 |  18522354386 |
| 10005 | overview   | query                                      |                   |           -1 |              0 |          128 |
| 10005 | overview   | global                                     |                   |           -1 |       18870394 |    297218169 |
| 10005 | overview   | tc/jemalloc cache                          |                   |           -1 |      950230480 |           -1 |
| 10005 | overview   | sum of all trackers                        |                   |           -1 |     1115563056 |           -1 |
| 10005 | overview   | process resident memory                    |                   | 363173039308 |     1509163008 |  25309491200 |
| 10005 | overview   | reserved memory                            |                   |           -1 |              0 |           -1 |
| 10005 | overview   | process virtual memory                     |                   |           -1 |   117395546112 | 117395546112 |
| 10005 | global     | Orphan                                     |                   |           -1 |          -1255 |            0 |
| 10005 | global     | DetailsTrackerSet                          |                   |           -1 |              0 |            0 |
| 10005 | global     | SegCompaction                              |                   |           -1 |              0 |    314912230 |
| 10005 | global     | PointQueryExecutor                         |                   |           -1 |              0 |            0 |
| 10005 | global     | BlockCompression                           |                   |           -1 |       14418184 |     14680336 |
| 10005 | global     | RowIdStorageReader                         |                   |           -1 |              0 |            0 |
| 10005 | global     | SubcolumnsTree                             |                   |           -1 |              0 |            0 |
| 10005 | global     | S3FileBuffer                               |                   |           -1 |              0 |            0 |
| 10005 | global     | DataPageCache[size](AllocByAllocator)      |                   |           -1 |              0 |            0 |
| 10005 | global     | IndexPageCache[size](AllocByAllocator)     |                   |           -1 |        4453465 |      4453465 |
| 10005 | global     | PKIndexPageCache[size](AllocByAllocator)   |                   |           -1 |              0 |            0 |
| 10005 | compaction | CumulativeCompaction:43034                 |                   |           -1 |              0 |            0 |
| 10005 | compaction | CumulativeCompaction:43038                 |                   |           -1 |              0 |            0 |
| 10005 | compaction | CumulativeCompaction:43064                 |                   |           -1 |      146462182 |    146591820 |
| 10005 | query      | Query#Id=d37540ad6764418b-8e134434fc096fa9 |                   |   2147483648 |              0 |            0 |
| 10005 | load       | MemTableTrackerSet                         |                   |           -1 |              0 |            0 |
| 10005 | compaction | CumulativeCompaction:43042                 |                   |           -1 |              0 |            0 |
| 10005 | other      | SnapshotManager                            |                   |           -1 |              0 |            0 |
| 10005 | global     | PageNoCache                                | DetailsTrackerSet |           -1 |        3278649 |    583658776 |
| 10005 | global     | IOBufBlockMemory                           | DetailsTrackerSet |           -1 |       11427840 |     27688960 |
| 10005 | global     | SegmentCache[size]                         | DetailsTrackerSet |           -1 |      294995027 |    294995027 |
| 10005 | global     | SchemaCache[number]                        | DetailsTrackerSet |           -1 |         171560 |       171560 |
| 10005 | global     | AllMemTableMemory                          | DetailsTrackerSet |           -1 |              0 |   4437646971 |
| 10005 | global     | TabletSchemaCache[number]                  | DetailsTrackerSet |           -1 |          21225 |        21225 |
| 10005 | global     | TabletMeta(experimental)                   | DetailsTrackerSet |           -1 |         223344 |       235376 |
| 10005 | global     | CreateTabletRRIdxCache[number]             | DetailsTrackerSet |           -1 |            106 |          212 |
+-------+------------+--------------------------------------------+-------------------+--------------+----------------+--------------+
37 rows in set (0.02 sec)

```

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by Vallishp — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Comment by wangbo** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request closed without merging**
