### PR TITLE
[opt](paimon) support mapping Paimon column type "Row" to Doris type "Struct"

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
Followup: https://github.com/apache/doris/pull/25364
support mapping Paimon column type "Row" to Doris type "Struct"
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Please update document and test case

**Comment by suxiaogang223** [comment]
update doc https://github.com/apache/doris-website/pull/577

**Comment by suxiaogang223** [comment]
run buildall

**Review by AshinGau — DISMISSED** [review]

**Comment by suxiaogang223** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
