### PR TITLE
[enhancement](load) make default load mem limit configurable

### PR DESCRIPTION
**Pull request by Henry2SS**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [x] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by caiconghui — DISMISSED** [review]
LGTM

**Review by morningman — CHANGES_REQUESTED** [review]
We already had a `load_mem_limit` session variable for this purpose.
I think we should use that instead of adding a new config.

**Comment by Henry2SS** [comment]
> We already had a `load_mem_limit` session variable for this purpose. I think we should use that instead of adding a new config.

the defaut value of `load_mem_limit` is `0`. And it means there is no limit. And it is mainly for `INSERT INTO` operations.
it is okay to set it to `2G` by default?

**Comment by xinyiZzz** [comment]
`runtime_state.cpp` the code below should be removed and replaced with `_query_options.load_mem_limit`.
```
int64_t RuntimeState::get_load_mem_limit() {
    if (_query_options.__isset.load_mem_limit && _query_options.load_mem_limit > 0) {
        return _query_options.load_mem_limit;
    } else {
        return _query_mem_tracker->limit();
    }
}
```

**Comment by xinyiZzz** [comment]
> `runtime_state.cpp` the code below should be removed and replaced with `_query_options.load_mem_limit`.
> 
> ```
> int64_t RuntimeState::get_load_mem_limit() {
>     if (_query_options.__isset.load_mem_limit && _query_options.load_mem_limit > 0) {
>         return _query_options.load_mem_limit;
>     } else {
>         return _query_mem_tracker->limit();
>     }
> }
> ```

To ensure compatibility during the upgrade process, cannot be removed now
Consider recording a TODO in `runtime_state.cpp`, the code is abandoned, it can be deleted after v1.3

**Comment by Henry2SS** [comment]
> > `runtime_state.cpp` the code below should be removed and replaced with `_query_options.load_mem_limit`.
> > ```
> > int64_t RuntimeState::get_load_mem_limit() {
> >     if (_query_options.__isset.load_mem_limit && _query_options.load_mem_limit > 0) {
> >         return _query_options.load_mem_limit;
> >     } else {
> >         return _query_mem_tracker->limit();
> >     }
> > }
> > ```
> 
> To ensure compatibility during the upgrade process, cannot be removed now Consider recording a TODO in `runtime_state.cpp`, the code is abandoned, it can be deleted after v1.3

OK. Thx for your advice.

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Review by caiconghui — DISMISSED** [review]
LGTM

**Review by caiconghui — APPROVED** [review]

**Review by caiconghui — APPROVED** [review]

**Review by caiconghui — DISMISSED** [review]
LGTM

**Review by morningman — COMMENTED** [review]
LGTM, but please add some document for this config

**Comment by Henry2SS** [comment]
> LGTM, but please add some document for this config

Done.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
