### PR TITLE
[fix](function) fix ipv4 funcs get failed error, improve an ipv6 func and exception message

### PR DESCRIPTION
**Pull request by superdiaodiao**
## Proposed changes

Issue Number: close #xxx

Function related:
- **ipv4_string_to_num**
- **ipv4_string_to_num_or_default**
- **ipv6_string_to_num**

**1. Fix**
In the past, when ipv4_string_to_num or ipv4_string_to_num_or_default handled with the **NULL** input, we got this error:
image

In this PR, we fix it, which is making ipv4_string_to_num throw an **exception** and ipv4_string_to_num_or_default return **0**.
image

**2. Improve**
make ipv6_string_to_num function part more reasonable while handling with **NULL** and let exception message more concrete by changing "Invalid IPv6 value" to "**Null Input, you may consider convert it to a valid default value like '::' first**"
image

**3. Other**
make IPExceptionMode more specific, separate different IP func registration part to be more readable

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by superdiaodiao** [comment]
run buildall

**Comment by superdiaodiao** [comment]
run buildall

**Comment by superdiaodiao** [comment]
run buildall

**Comment by superdiaodiao** [comment]
run p0

**Comment by superdiaodiao** [comment]
run pipelinex_p0

**Comment by superdiaodiao** [comment]
run buildall

**Comment by superdiaodiao** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
