### PR TITLE
[improvement](flink-connector) DataSourceFunction read doris supports parallel

### PR DESCRIPTION
**Pull request by JNSimba**
## Proposed changes

The previous DataSourceFunction inherited from RichSourceFunction. As a result, no matter how much the parallelism of flink is set, the parallelism of DataSourceFunction is only 1.
Now modify it to **RichParallelSourceFunction**.

And when flink has multiple degrees of parallelism, assign the doris data to each parallelism.
For example, read dorisPartitions.size = 10, flink.parallelism = 4
The task is split as follows:
task0: dorisPartitions[0],[4],[8]
task1: dorisPartitions[1],[5],[9]
task2: dorisPartitions[2],[6]
task3: dorisPartitions[3],[7]

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [x] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by hf200012 — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
> LGTM

Hi @hf200012 , I have talked to @JNSimba in private that this PR need further modification.
Because currently implementation will lead to duplicate data processing and some other problem.

**Comment by JNSimba** [comment]
Optimized task allocation algorithm

**Comment by hf200012** [comment]
> > LGTM
> 
> Hi @hf200012 , I have talked to @JNSimba in private that this PR need further modification. Because currently implementation will lead to duplicate data processing and some other problem.

OK，@JNSimba and I are communicating

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
