### PR TITLE
[fix](HardwareInfo) fix fe hardware info query error when the fe server run in Windows 11. (#20186)

### LINKED ISSUE #20186: [Bug] Failed to get hardware info when the FE server after an update to Windows 11.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

When I upgraded the operating system to Windows 11, the fe server in Windows 11 reported an error about Hardware Info.

mmexport1685366262895

### What You Expected?

Get the right hardware info.

### How to Reproduce?

Run fe server in Windows 11.

### Anything Else?

I have searched in stackoverflow and the issue can be fixed by upgraded the version of JNI.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Larborator**
## Proposed changes

Issue Number: close #20186

<--Describe your changes.-->

## Problem summary
Failed to get hardware info when the FE server after an update to Windows 11.

Describe your changes.
Upgrade jna and jna-platform version to 5.13.0.

## Checklist(Required)

* [x] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

### CODE REVIEW

**Comment by stalary** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.34 seconds
 stream load tsv:          495 seconds loaded 74807831229 Bytes, about 144 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161374812 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.63 seconds
 stream load tsv:          495 seconds loaded 74807831229 Bytes, about 144 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162170514 Bytes

**Comment by Larborator** [comment]
run buildall

**Pull request closed without merging**
