### PR TITLE
[Enhancement](Backup) support show create repository

### PR DESCRIPTION
**Pull request by GoGoWen**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

support show create repository stmt.

SQL example: show create repository for repo_name
Result:
MySQL [(none)]> show create repository for doris_backup_backup_cluster_bt1;
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RepoName                        | CreateStmt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| doris_backup_backup_cluster_bt1 | create read only repository doris_backup_backup_cluster_bt1 with broker broker_name on location "hdfs://ns1017/user/jd_ad/ads_report/narwal_backup/backup_cluster" properties ("password" = "XXXX","dfs.client.failover.proxy.provider" = "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider","dfs.ha.namenodes.ns1017" = "nn1,nn2","dfs.namenode.rpc-address.ns1017.nn2" = "XXXXXX:8020","dfs.nameservices" = "ns1017","dfs.namenode.rpc-address.ns1017.nn1" = "XXXXX:8020","username" = "XXXX") |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Checklist(Required)

* [N ] Does it affect the original behavior
* [ N] Has unit tests been added
* [N ] Has document been added or modified
* [N ] Does it need to update dependencies
* [Y] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
Need to use `PrintableMap` to print properties, to hide sensitive properties.

**Comment by GoGoWen** [comment]
> Need to use `PrintableMap` to print properties, to hide sensitive properties.

Done

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.54 seconds
 stream load tsv:          427 seconds loaded 74807831229 Bytes, about 167 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230410045843_clickbench_pr_126765.html

**Pull request merged**
