### PR TITLE
[improve](function) add error msg if exceeded maximum default value in repeat function

### PR DESCRIPTION
**Pull request by zhangstar333**
add some error msg from repeat function, so the user could know the count is greater than default value.
```
mysql [test_query_qa]>set repeat_max_num = 5;
Query OK, 0 rows affected (0.01 sec)

mysql [test_query_qa]>select repeat(k6,10) from baseall where k1 = 1;
ERROR 1105 (HY000): errCode = 2, detailMessage = (10.16.10.8)[CANCELLED]The second parameter of repeat function exceeded maximum default value, default_value is 5, and now input is 10 . you could try change default value greater than value by: set repeat_max_num = 20.
```

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
