### PR TITLE
[docs](typo) Correct the wrong default value of DECIMAL type displayed in the Help CREATE TABLE

### PR DESCRIPTION
**Pull request by ChaseHuangxu**
# Proposed changes

Issue Number: None

## Problem summary

Correct the wrong default value of DECIMAL type displayed in the Help CREATE TABLE

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments
Just the documentation changes

### CODE REVIEW

**Review by Yukang-Lian — APPROVED** [review]
Good job! LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by luzhijing** [comment]
run P0

**Pull request merged**
