### PR TITLE
[chroe](ci) add script for create_issue_comment

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Review by pingchunzhang — COMMENTED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by pingchunzhang — COMMENTED** [review]
LGTM

**Review by pingchunzhang — APPROVED** [review]
LGTM

**Pull request merged**
