### PR TITLE
[improvement](statistics)Make partition batch size configurable and limit total rows to scan in partition analyze.

### PR DESCRIPTION
**Pull request by Jibing-Li**
1. Make the number of partitions to collect in one batch configurable
2. Add a limit to the total row count while doing partition analyzing in one batch.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run feut

**Comment by Jibing-Li** [comment]
run performance

**Review by morningman — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
