### PR TITLE
[tpch](nereids) estimate cost with unknown column stats

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes

make nereids generate more reasonable plans with table row count, but without column stats.
tpch sf100 test(q5 and q7 oom without stats)
image

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Review by Kikyou1997 — APPROVED** [review]

**Review by Kikyou1997 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
