### PR TITLE
[fix](delete) fix incorrect tablet schema of delete predicate rowset (#29536)

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

pick from #29536 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by liaoxin01** [comment]
run clickbench

**Comment by liaoxin01** [comment]
run p1

**Pull request merged**
