### PR TITLE
[enhancement](err-msg) Add detailed column and schema info when failed to create a column iterator

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

As title.

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run feut

**Comment by TangSiyang2001** [comment]
run cloudut

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
