### PR TITLE
[Doc] correct format errors in English doc

### PR DESCRIPTION
**Pull request by Sunt-ing**
## Proposed changes
Some formate errors in English doc.
They are very straightforward and should not break any existing build.

### CODE REVIEW

**Comment by Sunt-ing** [comment]
@EmmyMiao87 Hi, hope you have a fantastic Spring Festival! This PR has been created for a long time. It's merely for the doc part and won't break any existing build. Believe me, it will make the English doc better! Could you please review it after have a nice lunch or dinner and temporally have nothing to do? I will appreciate that!

**Comment by EmmyMiao87** [comment]
Happy Ox New Year ~.
I have seen PR and there is no problem. 
But you need to rebase the master code to resolve the conflict firstly.

**Comment by Sunt-ing** [comment]
OK, thanks! I will do that.

**Comment by Sunt-ing** [comment]
It seems that I have finished the work. @EmmyMiao87

**Comment by Sunt-ing** [comment]
@EmmyMiao87 Could you review this PR again? Thanks!!

**Review by EmmyMiao87 — COMMENTED** [review]
LGTM

**Comment by EmmyMiao87** [comment]
Done

**Comment by Sunt-ing** [comment]
Thanks!!!

**Review by EmmyMiao87 — APPROVED** [review]
LGTM

**Pull request merged**
