### PR TITLE
[Feat](fe) Support compress file for tvf hdfs() and s3()

### LINKED ISSUE #19477: [Feature] support compress file for tvf hdfs() and s3()
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Related discussion: https://github.com/apache/doris/discussions/18140

We can support it by add a new properties for tvf , like :

```
select * from hdfs("uri" = "xxx", ..., "compress_type" = "lz4", ...)
```

User can:
1. Specify compression explicitly by setting `"compression" = "xxx"`.
2. Doris can infer the compression type by the suffix of file name, eg, file1.gz

Currently, we only support reading compress file in csv format, and on BE side, we already support.
All need to do is to analyze the "compress_type" on FE side and pass it to BE.

Related class:
```
PropertyAnalyzer.analyzeCompressionType()
```
You can also refer to this PR: https://github.com/apache/doris/pull/19387/files

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by reswqa**
# Proposed changes

Issue Number: close #19477.

## Problem summary

We can support this by add a new properties for tvf, like :

`select * from hdfs("uri" = "xxx", ..., "compress_type" = "lz4", ...)`

User can:

Specify compression explicitly by setting `"compression" = "xxx"`.
Doris can infer the compression type by the suffix of file name(e.g. `file1.gz`)
Currently, we only support reading compress file in `csv` format, and on BE side, we already support.
All need to do is to analyze the `"compress_type"` on FE side and pass it to BE.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by reswqa** [comment]
run buildall

**Comment by reswqa** [comment]
Thanks @morningman for the quick review! I have addressed your comment and introduce some regression test case about reading compressed `csv` file located in `hdfs`. Please take a look in your free time, thx~

**Comment by reswqa** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
LGTM, please modify the document:

```
https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/table-functions/s3/
https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/table-functions/hdfs/
```
both Chinese and English

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Pull request merged**
