### PR TITLE
[fix](hive) support hive3 timestamp with local time zone

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Hive 3.1 adds a new data type: TIMESTAMP WITH LOCAL TIME ZONE.

Example:

```
beeline> create table x(t timestamp, tltz timestamp with local time zone);
OK

beeline> desc x;
+-----------+---------------------------------------------------+----------+
| col_name  |                     data_type                     | comment  |
+-----------+---------------------------------------------------+----------+
| t         | timestamp                                         |          |
| tltz      | timestamp with local time zone('Asia/Shanghai')  |          |
+-----------+---------------------------------------------------+----------+
```

Doris does not support timestamp with tz, simply map it to Datatime column.
User should notice that and convert timezone by self

### CODE REVIEW

**Review by wuwenchi — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Pull request closed without merging**
