### PR TITLE
 [Bug][Vectorized] core dump on ST_AsText

### LINKED ISSUE #8869: [Bug][Vectorized] core dump on `ST_AsText`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
SELECT ST_AsText(ST_Point(123.12345678901234567890,89.1234567890));
```
```cpp
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/common/signal_handler.h:420
 1# 0x000000318AE32920 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x0000000004C5ECF9 in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
 5# 0x0000000004C5430D at src/logging.cc:1650
 6# google::LogMessage::SendToLog() at src/logging.cc:1607
 7# google::LogMessage::Flush() at src/logging.cc:1477
 8# google::LogMessageFatal::~LogMessageFatal() at src/logging.cc:2227
 9# doris::vectorized::ColumnNullable::ColumnNullable(COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&&, COW<doris::vectorized::IColumn>::mutable_ptr<doris::vectorized::IColumn>&&) in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
10# doris::vectorized::StPoint::execute(doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/functions_geo.cpp:38
11# doris::vectorized::GeoFunction<doris::vectorized::StPoint, doris::vectorized::DataTypeString>::execute_impl(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/functions_geo.h:45
12# doris::vectorized::DefaultExecutable::execute_impl(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/function.h:444
13# doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
14# doris::vectorized::PreparedFunctionImpl::default_implementation_for_constant_arguments(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool, bool*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:184
15# doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:237
16# doris::vectorized::PreparedFunctionImpl::execute(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:272
17# doris::vectorized::IFunctionBase::execute(doris_udf::FunctionContext*, doris::vectorized::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/functions/function.h:142
18# doris::vectorized::VectorizedFnCall::execute(doris::vectorized::VExprContext*, doris::vectorized::Block*, int*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/exprs/vectorized_fn_call.cpp:96
19# doris::vectorized::VExpr::get_const_col(doris::vectorized::VExprContext*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/exprs/vexpr.cpp:311
20# doris::vectorized::VExpr::init_function_context(doris::vectorized::VExprContext*, doris_udf::FunctionContext::FunctionStateScope, std::shared_ptr<doris::vectorized::IFunctionBase> const&) in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
21# doris::vectorized::VectorizedFnCall::open(doris::RuntimeState*, doris::vectorized::VExprContext*, doris_udf::FunctionContext::FunctionStateScope) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/exprs/vectorized_fn_call.cpp:73
22# doris::vectorized::VExprContext::open(doris::RuntimeState*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/exprs/vexpr_context.cpp:58
23# doris::FoldConstantExecutor::fold_constant_vexpr(doris::TFoldConstantParams const&, doris::PConstantExprResult*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/runtime/fold_constant_executor.cpp:121
24# doris::PInternalServiceImpl<doris::PBackendService>::_fold_constant_expr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, doris::PConstantExprResult*) in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
25# doris::PInternalServiceImpl<doris::PBackendService>::fold_constant_expr(google::protobuf::RpcController*, doris::PConstantExprRequest const*, doris::PConstantExprResult*, google::protobuf::Closure*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/service/internal_service.cpp:397
26# brpc::policy::ProcessHttpRequest(brpc::InputMessageBase*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/thirdparty/src/incubator-brpc-1.0.0/src/brpc/policy/http_rpc_protocol.cpp:1499
27# brpc::ProcessInputMessage(void*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/thirdparty/src/incubator-brpc-1.0.0/src/brpc/input_messenger.cpp:137
28# brpc::InputMessenger::OnNewMessages(brpc::Socket*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/thirdparty/src/incubator-brpc-1.0.0/src/brpc/input_messenger.cpp:335
29# brpc::Socket::ProcessEvent(void*) at /home/disk2/pxl/dev/baidu/bdg/doris/core/thirdparty/src/incubator-brpc-1.0.0/src/brpc/socket.cpp:1020
30# bthread::TaskGroup::task_runner(long) at /home/disk2/pxl/dev/baidu/bdg/doris/core/thirdparty/src/incubator-brpc-1.0.0/src/bthread/task_group.cpp:301
31# bthread_make_fcontext in /home/disk2/pxl/dev/baidu/bdg/doris/core/output/be/lib/palo_be
```

### What You Expected?

fix it

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
fix geo

# Proposed changes

Issue Number: close #8869

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — CHANGES_REQUESTED** [review]
We should add case for this fix.

**Review by HappenLee — COMMENTED** [review]
use `remove_nullable` function to do thing like this

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
@morningman  Hi, I fix the conflict.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
