### PR TITLE
[Chore](rollup) check duplicate column name when create table with rollup

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
check duplicate column name when create table with rollup
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by starocean999 — APPROVED** [review]

**Review by morrySnow — DISMISSED** [review]

**Review by starocean999 — CHANGES_REQUESTED** [review]
better to do the validation in nereids planner. You can check the rollups in CreateTableInfo.validate method

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
