### PR TITLE
[Fix](beut) Fix TestDeleteConditionHandler beut

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

introduced in https://github.com/apache/doris/pull/37834

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by bobhan1** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
