### PR TITLE
[fix](replace_column_data)fix replace_column_data semantic 

### PR DESCRIPTION
**Pull request by amorynan**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:
replace_column_data is only for column which is not variable_length column like column_vector...
 set is_variable_length = true such as column_string|array|map|struct 
should not impl this function, when in agg situation for replace_if_not_null : we should use ```insert_from```!
### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by xiaokang** [comment]
do not do it in branch-2.0

**Pull request closed without merging**
