### PR TITLE
[improvement](stream load) support hll_from_base64 for stream load column mapping

### LINKED ISSUE #35922: [Enhancement] Support stream load to use hll_from_base64 function when doing column mapping
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When executing stream load and specifying hll_from_base64 function to map data to HLL type, the following exception message is returned:
> HIL column must use hll _hash function, like xxx=hll_hash (xxx) or xxx=hll_empty(), see more in null

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gnehil**
## Proposed changes

Issue Number: close #35922

### CODE REVIEW

**Review by dataroaring — CHANGES_REQUESTED** [review]
please add a regression case for http load and streamload.

**Comment by gnehil** [comment]
> please add a regression case for http load and streamload.

Regression test added, please review.

**Comment by liaoxin01** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by gnehil** [comment]
runbuild all

**Comment by superdiaodiao** [comment]
run buildall

**Comment by gnehil** [comment]
run buildall

**Comment by gnehil** [comment]
run buildall

**Comment by gnehil** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
