### PR TITLE
[opt](profile) set datalake profile level as 1

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Follow https://github.com/apache/doris/pull/25491, only the profile marked as 1 will be shown in simplified profile.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
