### PR TITLE
[fix](cluster key) Fix cluster key compaction and forbid cluster key in cloud mode

### PR DESCRIPTION
**Pull request by mymeiyi**
1. fix test_compaction_uniq_cluster_keys_with_delete
2. add more compaction case for cluster key like other mow cases
3. forbid cluster key in cloud mode

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
