### PR TITLE
[Docs](Catalog) Optimize the documentation catalog and add the Join Our Community Documentation

### PR DESCRIPTION
**Pull request by KassieZ**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by KassieZ** [comment]
run buildall

**Comment by luzhijing** [comment]
run buildall

**Review by zy-kkk — DISMISSED** [review]

**Review by luzhijing — DISMISSED** [review]
LGTM

**Review by zy-kkk — DISMISSED** [review]

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Pull request closed without merging**
