### PR TITLE
[Fix](Nereids) fix leading with different be instance number (#36613)

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
cherry-pick: #36613
Problem:
When use different be number to test leading explain shape plan, physical distribute plan would differ due to different be numbers
Solved:
Disable physical distribute node showing in fix leading cases

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by hello-stephen** [comment]
http://43.132.222.7:8111/buildConfiguration/Doris_DorisRegression_P0Regression/456864?buildTab=tests&name=fix&expandedTest=build%3A%28id%3A456864%29%2Cid%3A2000001806
流水线上这个case没过

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by morrySnow** [comment]
run external

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Pull request merged**
