### PR TITLE
[Enhance](regression)enhance docker network by add docker network subnet

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

enhance docker network by add docker network subnet

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
https://github.com/apache/doris/pull/26862

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by pingchunzhang — APPROVED** [review]

**Pull request merged**
