### PR TITLE
[fix](auth)fix some tvf not check auth

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

Problem Summary:

fix some tvf not check auth

- backends() support check auth 
- frontends() support check auth 
- frontends_disks() support check auth 

### Release note

Change the privilege required for TVF backends, frontends and frontends_disks. Before, no privilege required for them. from now on, ADMIN_PRIV or NODE_PRIV is required.

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [x] Yes. 

- Does this need documentation?
    - [ ] No.
    - [x] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Thearas** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run performance

**Review by morrySnow — APPROVED** [review]

**Review by zfr9527 — APPROVED** [review]
LGTM

**Pull request merged**
