### PR TITLE
[debug](Variant) sanitize variant type and column in `find_and_set_le…

### PR DESCRIPTION
**Pull request by eldenmoon**
…ave_value`

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
