### PR TITLE
[Fix](planner)fix conjunct planned on exchange node

### PR DESCRIPTION
**Pull request by sohardforaname**
# Proposed changes

Issue Number: close #xxx

## Problem summary

sql like: 
select k5, k6, SUM(k3) AS k3 
from ( 
    select
        k5,
        date_format(k6, '%Y-%m-%d') as k6,
        count(distinct k3) as k3 
    from t 
    group by k5, k6
) AS temp where 1=1
group by k5, k6;

will throw exception since conjuncts planned on exchange node, because exchange node cannot handle conjuncts, now we skip exchange node when planning conjuncts, which fixes the bug. 
notice: the bug occurs iff the conjunct is always true like 1=1 above.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by sohardforaname** [comment]
run buildall

**Comment by sohardforaname** [comment]
run p0

**Comment by englefly** [comment]
add some explanation in problem summary
1. the root cause is exchange node is not able to filter data
2. remove the `1=1` in view, it is not the conjunct mentioned in this pr
3. change the `1=1` to a more general equal.

**Comment by sohardforaname** [comment]
> add some explanation in problem summary
> 
> 1. the root cause is exchange node is not able to filter data
> 2. remove the `1=1` in view, it is not the conjunct mentioned in this pr
> 3. change the `1=1` to a more general equal.

done

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
