### PR TITLE
[Feature-WIP](inverted index) Add boolean query functionality

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

1. BooleanQuery usage:
      BooleanQuery::Builder builder;
      builder.set_op(OperatorType::OP_AND);
      builder.add(term_query);
      builder.add(term_query);
      builder.add(term_query);
      auto boolean_query = builder.build();

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
