### PR TITLE
[fix](profile) Fix content missing of brokerload profile

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
Broker load does not set enable_profile for its load task, makes profile empty.

BTW: profile of broker load can not be fetch during task executing, since it only register profile after load job is finished.

before:
image

after:
image

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
