### PR TITLE
[fix](group commit)Fix the issue of duplicate addition of wal path when encouter exception

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
wal path has been created at the beginning, so no need to call add_wal_path to create it again when encouter exception.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by hust-hhb** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by hust-hhb** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
