### PR TITLE
[fix](sequence-column) Fix sequence_col column used default expr insert failed

### LINKED ISSUE #18911: [Bug] 指定sequence_col的类型为时间的默认值是CURRENT_TIMESTAMP，insert 失败
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2/master

### What's Wrong?

sequence列使用CURRENT_TIMESTAMP在fe没做处理，导致insert失败。
CREATE TABLE `order_info` (
`project_id` BIGINT NOT NULL ,
`consume_date` DATETIMEV2 NOT NULL,
`order_id` BIGINT NOT NULL ,
`combo_extend` JSONB DEFAULT NULL,
`age` INT ,
`name` varchar(20),
`write_time` DATETIME DEFAULT CURRENT_TIMESTAMP
) UNIQUE KEY(`project_id`, `consume_date`,`order_id`)
DISTRIBUTED BY HASH(`project_id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"enable_unique_key_merge_on_write" = "true",
"function_column.sequence_col" = 'write_time'
);

INSERT INTO
test.order_info_4 (
order_id,
project_id,
consume_date,
age,
name
)
VALUES
(
1231234356,
370040365,
'2023-01-12',
NULL,
NULL
);
image

### What You Expected?

intert成功

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lvshaokang**
# Proposed changes

Issue Number: close #18911 

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
please add a regression test.

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.3 seconds
 stream load tsv:          429 seconds loaded 74807831229 Bytes, about 166 MB/s
 stream load json:         23 seconds loaded 2358488459 Bytes, about 97 MB/s
 stream load orc:          59 seconds loaded 1101869774 Bytes, about 17 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230423093318_clickbench_pr_133309.html

**Comment by lvshaokang** [comment]
run buildall

**Comment by lvshaokang** [comment]
run p0

**Comment by lvshaokang** [comment]
run buildall

**Comment by zclllyybb** [comment]
please rebase after https://github.com/apache/doris/pull/19216 . thank you

**Comment by lvshaokang** [comment]
> we will fix the p0 regression soonly

@zclllyybb Ok, if already fix the p0 regression, could you call me? I will re-run it. Thanks!

**Comment by zclllyybb** [comment]
Ooops... Sorry, I made a mistake and wrongly thought it was because of a series of known issues with the pipeline. But actually it's not. The actual reason for P0 failure is that your changes make there an inequality of `block`'s and output descriptor's column number, in `VOlapTableSink::_validate_data` 😄

**Comment by lvshaokang** [comment]
> Ooops... Sorry, I made a mistake and wrongly thought it was because of a series of known issues with the pipeline. But actually it's not. The actual reason for P0 failure is that your changes make there an inequality of `block`'s and output descriptor's column number, in `VOlapTableSink::_validate_data` 😄

@zclllyybb Could you offer a more detailed logs for me, i would like to known the exception column order is? Btw, I have tested the above error case with locally `run-regression-test.sh` and no error was reported.

**Comment by lvshaokang** [comment]
run buildall

**Comment by lvshaokang** [comment]
run buildall

**Comment by lvshaokang** [comment]
run buildall

**Comment by lvshaokang** [comment]
run clickbench

**Comment by lvshaokang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
