### PR TITLE
[feature](nereids) add expression transformation rule simplify_conditional_function

### PR DESCRIPTION
**Pull request by feiniaofeiafei**
```sql
coalesce(null,null,expr,...) => coalesce(expr,...)
coalesce(expr1(not null able ), expr2, ...., expr_n) => expr1
coalesce(null,null) => null
coalesce(expr1) => expr1
nvl(null,R) => R
nvl(L(not-nullable ),R) => L
nullif(null, R) => Null
nullif(L, null) => Null
```

### CODE REVIEW

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run cloud_p0

**Comment by feiniaofeiafei** [comment]
run external

**Comment by feiniaofeiafei** [comment]
run cloud_p1

**Review by 924060929 — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run p0

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run buildall

**Comment by feiniaofeiafei** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
