### PR TITLE
[fix](testcases) Fix some unstable testcases.

### PR DESCRIPTION
**Pull request by zclllyybb**
# Proposed changes

Issue Number: close DORIS-4566, DORIS-4570

## Problem summary

1. case of `test_string_concat_extremely_long_string` will exceed our test limit. Move it to p2 so that it will be tested only in SelectDB test environment.
2. Because we need to keep consistent with MySQL & avoid overflow. the `q67` must keep its behavior like now. When we fully apply nereids & decimalV3 then, it will be fixed automatically.
3. In the parallel test, although all query stats were cleaned, the cases run in parallel will affect this. So we need to use a unique table for `query_stats_test`
4. `test_query_sys_tables` didn't deal with some unstable situations. fixed it.
5. temporarily disable unstable case `analyze_test` case for p0.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Comment by zclllyybb** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
