### PR TITLE
[fix](Row store) get the correct value of row_store_page_size after FE restarts

### PR DESCRIPTION
**Pull request by lxr599**
## Proposed changes

pick #38236

### CODE REVIEW

**Comment by lxr599** [comment]
run buildall

**Comment by lxr599** [comment]
run buildall

**Comment by lxr599** [comment]
run buildall

**Comment by lxr599** [comment]
run compile

**Comment by lxr599** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
