### PR TITLE
[chore](routine load)  make error msg clear if routine load name illegal

### PR DESCRIPTION
**Pull request by sollhui**
Make error msg clear if routine load name illegal(such as job name is too long).

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
