### PR TITLE
[bug](Fe) fix potential deadlock in show proc statement

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

version: 1.2|2.0|2.1

We have encountered Fe hang and the number connections reach limits.
Unfortunately, I restarted FE without Jstack the Fe process.

But I found a lot of logs like:

```
2024-05-11 14:09:32,533 WARN (thrift-server-pool-424042|4684871) [ReportHandler.putToQueue():190] the report queue size exceeds the limit: 100.
 current: 101
2024-05-11 14:09:32,545 WARN (thrift-server-pool-392529|4367180) [ReportHandler.putToQueue():190] the report queue size exceeds the limit: 100.
 current: 101
2024-05-11 14:09:32,663 WARN (thrift-server-pool-421895|4663462) [ReportHandler.putToQueue():190] the report queue size exceeds the limit: 100.
 current: 101
2024-05-11 14:09:32,816 WARN (thrift-server-pool-379243|4167917) [ReportHandler.putToQueue():190] the report queue size exceeds the limit: 100.
 current: 101
2024-05-11 14:09:33,531 WARN (thrift-server-pool-420797|4652941) [ReportHandler.putToQueue():190] the report queue size exceeds the limit: 100.
 current: 101
```

The tablet report task is hang:

```
2024-05-11 14:07:57,671 INFO (Thread-57|105) [ReportHandler.tabletReport():250] backend[10009] reports 28982 tablet(s). repor
t version: 17094493386232
2024-05-11 14:24:15,323 INFO (Thread-57|105) [TabletInvertedIndex.tabletReport():308] finished to do tablet diff with backend[10009].
sync: 0. metaDel: 7. foundInMeta: 28953. migration: 0. found invalid transactions 0. found republish transactions 0. tabletInMemorySync:
0. need recovery: 0. cost: 66 ms
```

And the dynamic partition scheduler seems also hang:

image

I found a similar issue, as issue #11319 saying, we should avoid using common global `ForkJoinPool` to execute parallelStream tasks and prevent Fe deadlocks from occurring.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by lide-reed** [comment]
It's said that java.util.concurrent.ForkJoinPool may degrade performance. Please confirm whether the changes here involve high-frequency operations.

**Comment by xy720** [comment]
> It's said that java.util.concurrent.ForkJoinPool may degrade performance. Please confirm whether the changes here involve high-frequency operations.
> https://stackoverflow.com/questions/20288379/analysis-performance-of-forkjoinpool

As we discussed, the pr will not affect performance. No longer use the global only thread pool here, but instead use its own thread pool separately.

**Review by lide-reed — APPROVED** [review]
LGTM

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
