### PR TITLE
[fix](column-id) fix null conn ctx  in column id flusher and parser for `database` field in  corresponding show stmt

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

introduce: #23616

1. In column id flush daemon thread, conn ctx is null, fix the NPE caused by fetching the timeout from conn ctx in underlying `AlterLightSchemaChangeHelper`.
2. Fix the SHOW CONVERT_LIGHT_SCHEMA_CHANGE_PROCESS stmt with  database clause grammar.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run p0

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by kaijchen — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
