### PR TITLE
[refactor](planner) Separate the planning process for the legacy planner and Nereids

### LINKED ISSUE #15392: add a complete framework to support Command

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #15392

1. separate the planning process for legacy planner and Nereids in StmtExecutor
2. add forward to master logic to Nereids
3. refactor Command process for Nereids, add run interface to Command
4. internal query could run on Nereids as normal query
5. fix CreatePolicyCommand syntax, let it exactlly same with legacy planner
6. let Nereids session variables forward to master

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.2 seconds
 stream load tsv:          477 seconds loaded 74807831229 Bytes, about 149 MB/s
 stream load json:         24 seconds loaded 2358488459 Bytes, about 93 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230322180336_clickbench_pr_118830.html

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run clickbench p0 beut

**Comment by morrySnow** [comment]
run compile

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run clickbench

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
