### PR TITLE
[Enhancement] support different python version in build-support scripts

### PR DESCRIPTION
**Pull request by carlvinhust2012**
# Proposed changes
1. support different python version in build-support scripts which is more convenient for us.
Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
Python 2 is EOF. Is it necessary to support it?

Furthermore, the modification looks verbose. You can use a variable to indicate python with different versions.

```shell
PYTHON='python3'

"${PYTHON}" ...
```

**Comment by carlvinhust2012** [comment]
> Python 2 is EOF. Is it necessary to support it?
> 
> Furthermore, the modification looks verbose. You can use a variable to indicate python with different versions.
> 
> ```shell
> PYTHON='python3'
> 
> "${PYTHON}" ...
> ```

yes, this is a good idea. I have test the way like "python${VERSION} parameter-list" yestoday.

**Comment by morningman** [comment]
Hi @carlvinhust2012 , please rebase the fix the BE ut. some commit has been reverted to fix that bug.

**Comment by carlvinhust2012** [comment]
> Hi @carlvinhust2012 , please rebase the fix the BE ut. some commit has been reverted to fix that bug.

ok，I will rebase later.

**Review by dataroaring — APPROVED** [review]

**Pull request merged**
