### PR TITLE
[bugfix](iceberg)Restrictions on creating a database

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

1. Restrictions on creating a database. 
Currently, only attributes of the `hms` type of database can be added.
Like:
```
create database db properties ('a'='b');
```
2. Unify the catalog name of iceberg and doris to be the same.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
