### PR TITLE
[fix](bitmap) incorrect result of operator ==

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

If both the right and left Roaring64Map contain only one empty map, the operator ‘==’ should return true but currently returns false.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Pull request closed without merging**
