### PR TITLE
[improvement](inverted index)Remove searcher bitmap timer to improve query speed

### PR DESCRIPTION
**Pull request by qidaye**
# Proposed changes

Timer becomes a bottleneck when the query hit volume is very high.

Test result:

 sql | TIMER Added | TIMER Removed | Hits
 -- | -- | -- | --
select count() from hits where PageCharset match_any 'windows'; | 1.23s | 0.60s | 60715906
select count() from hits_one_bucket2 where agent match_any 'windows'; | 4.27s | 1.95s | 41142388
select count() from hits_one_bucket2 where agent match_any 'Windows Chrome'; | 7.00s | 2.06s | 45256626
select count() from hits_one_bucket2 where agent match_all 'Windows Chrome'; | 7.74s | 2.79s | 41142388

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
LGTM

**Comment by qidaye** [comment]
run buildall

**Review by Tanya-W — COMMENTED** [review]
LGTM

**Review by morningman — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.04 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         38 seconds loaded 2358488459 Bytes, about 59 MB/s
 stream load orc:          67 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          27 seconds loaded 861443392 Bytes, about 30 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230306050022_clickbench_pr_109023.html

**Comment by qidaye** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
