### PR TITLE
[fix](statistics)Fix empty table keep auto analyze bug.

### PR DESCRIPTION
**Pull request by Jibing-Li**
1. Fix empty table keep auto analyze bug, reset new partition flag no matter row count is 0 or not.
2. Use report row count == -1 to check table is empty or not.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run feut

**Comment by Jibing-Li** [comment]
run buildall

**Review by zfr9527 — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
