### PR TITLE
[enhancement](test) unique model by modify a key type from SMALLINT to other type 

### PR DESCRIPTION
**Pull request by cjj2010**
…MALLINT to other type

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cjj2010** [comment]
run buildall

**Comment by cjj2010** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run feut

**Comment by yiguolei** [comment]
run beut

**Comment by cjj2010** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by cjj2010** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
