### PR TITLE
[conf](mysql) opt mysql network timeout to 600s

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes
Now `netWriteTimeout` and `netReadTimeout` only used in `MysqlChannel`, from pr: https://github.com/apache/doris/pull/28808

First of all, mysql client may be in different location as FE, the network maybe slow, not like FE and BE always have a fast network.
Secondly,  the max packet size is 16MB in Mysql Protocol, not very small.

So we should enlarge this timeout.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
issue: 
https://github.com/apache/doris/issues/28807
https://github.com/apache/doris/issues/32539

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run external

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
