### PR TITLE
[Test](regression) CCR syncer thrift interface regression test

### PR DESCRIPTION
**Pull request by deadlinefen**
[Test](regression) CCR syncer thrift interface regression test

### CODE REVIEW

**Comment by deadlinefen** [comment]
run p0

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run P0

**Comment by deadlinefen** [comment]
run P0

**Comment by deadlinefen** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Comment by deadlinefen** [comment]
run buildall

**Pull request closed without merging**
