### PR TITLE
[dependency](fe)Upgrade dependency library

### PR DESCRIPTION
**Pull request by CalvinKirs**
Upgrade netty to 4.1.104.final
Upgrade grpc to 1.60.1
Upgrade check-freamework to 3.42.0
Upgrade snappy-java to 1.1.10.5
Upgrade avro to 1.11.3
Upgrade aws-java -sdk to 1.12.625
Binding zookeeper version to 3.9.1
Binding jetty-version  to 9.4.53.v20231009

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by hf200012 — APPROVED** [review]
LGTM

**Pull request merged**
