### PR TITLE
[fix](docs) fix stream load docs

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

The example under `enable_profile` is actually for `two_phase_commit`.

Also fix indentation using spaces instead of tabs.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run external

**Pull request merged**
