### PR TITLE
[improve](load) don't limit ADD_SEGMENT running count in load stream

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Don't limit ADD_SEGMENT running count in load stream like APPEND_DATA.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by sollhui — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
