### PR TITLE
[Improvement](column) reduce cache miss for data copy

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

query:
select  count(*) from (
    select /*+SET_VAR(disable_join_reorder=true)*/distinct c_last_name, c_first_name, d_date
    from store_sales
         join
         date_dim
         on store_sales.ss_sold_date_sk = date_dim.d_date_sk
         join[shuffle]
         customer
         on store_sales.ss_customer_sk = customer.c_customer_sk
         where d_month_seq between 1183 and 1183 + 11
  intersect
    select /*+SET_VAR(disable_join_reorder=true)*/distinct c_last_name, c_first_name, d_date
    from catalog_sales
         join
         date_dim on catalog_sales.cs_sold_date_sk = date_dim.d_date_sk
         join[shuffle]
         customer on catalog_sales.cs_bill_customer_sk = customer.c_customer_sk
         where d_month_seq between 1183 and 1183 + 11
  intersect
    select /*+SET_VAR(disable_join_reorder=true)*/distinct c_last_name, c_first_name, d_date
    from web_sales
         join
         date_dim on web_sales.ws_sold_date_sk = date_dim.d_date_sk
         join[shuffle]
         customer on web_sales.ws_bill_customer_sk = customer.c_customer_sk
         where d_month_seq between 1183 and 1183 + 11
) hot_cust
limit 100;

2.2s->1.9s

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by Gabriel39** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
