### PR TITLE
[Performance](sink) opt mysql result writer

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

1kw double data

Before： 1.8s
After：1.6s

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
