### PR TITLE
[fix](load) fix broker load progress due to retry

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Currently, when retrying a broker load, it will use a different `load_id` with the same `job_id`.
The `total_scan_nums` in progress is accumulated by `job_id`.
This will cause the `total_scan_nums` progress to be multiple of the actual scan nums.

For example, suppose a 10 instance broker load gets retried:

```
initial (0/10) 0% -> retry (0/20) 0% -> finish (10/20) 50%
```

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
