### PR TITLE
[fix](statistics)Fix alter column stats bug.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Encode the min and max value with base64 encoder while inject the column stats.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by Kikyou1997 — APPROVED** [review]

**Review by englefly — DISMISSED** [review]

**Comment by Jibing-Li** [comment]
run buildall

**Review by englefly — APPROVED** [review]

**Pull request merged**
