### PR TITLE
[fix](regression-test) fix the comparison errors caused by inconsistent accuracy

### PR DESCRIPTION
**Pull request by AshinGau**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

Keep the scale of low precision data to resolve the comparison errors caused by inconsistent accuracy:
```
Check tag 'q09' failed, line 3, DECIMAL result mismatch.
Expect cell is: 0.0395
But real is: 0.039535109
```

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by BiteTheDDDDt** [comment]
Will this cause the bug to be covered up? The decimal type doesn't seem to have precision errors

**Comment by AshinGau** [comment]
> > Will this cause the bug to be covered up? The decimal type doesn't seem to have precision errors
> 
> Maybe we should change this back after the decimal v3 is completed. Because currently, the decimal type doesn't return real precision.

This fix was introduced for two reasons:
1. The previous fix judges whether two numbers(float & double) are equal by the threshold of relative change. However, this is a fixed value, which may not solve the accuracy problem with larger error, so the rounding method may be better.
2. Other correctness regression tests(tpch 100/1000) are prepared to be added, but the correct result sets come from other frameworks(Trino/Spark). Different frameworks cannot guarantee consistent behavior of decimal.

**Comment by BiteTheDDDDt** [comment]
> > > Will this cause the bug to be covered up? The decimal type doesn't seem to have precision errors
> > 
> > 
> > Maybe we should change this back after the decimal v3 is completed. Because currently, the decimal type doesn't return real precision.
> 
> This fix was introduced for two reasons:
> 
>     1. The previous fix judges whether two numbers(float & double) are equal by the threshold of relative change. However, this is a fixed value, which may not solve the accuracy problem with larger error, so the rounding method may be better.
> 
>     2. Other correctness regression tests(tpch 100/1000) are prepared to be added, but the correct result sets come from other frameworks(Trino/Spark). Different frameworks cannot guarantee consistent behavior of decimal.

OK.
BTW, maybe we should make some modifications to these result sets from other frameworks as appropriate.

**Pull request merged**
