### PR TITLE
[feat](nereids) count prefix index in CBO

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
1. if prefix index is choosen, lower the filter cost in CBO
2. for join cost: if left.rowcount==right.rowcount, we will choose the wider (stats.getWidthInJoinCluster()) child as left child, since we prefer left deep tree.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run performance

**Review by starocean999 — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
