### PR TITLE
[Opt](heartbeat) improve the tolerance of the cluster to occasional heartbeat failures

### PR DESCRIPTION
**Pull request by liaoxin01**
To improve the tolerance of the cluster to occasional heartbeat failures，change max_backend_heartbeat_failure_tolerance_count from 1 to 3.

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Review by gavinchou — APPROVED** [review]

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
