### PR TITLE
[Enhancement] Change Create Resource Group Grammar

### LINKED ISSUE #20170: [Enhancement] Change Create Resource Group Grammar
### Problem
Currently Doris has both ```Resource Group``` and ```Resource```,  the name is quite similar, but they are quite diffrent things.
So we want to change ```Resource Group```  to ```WorkLoad Group```.

```
CREATE WORKLOAD GROUP [IF NOT EXISTS] "group_name"
PROPERTIES (
    property_list
);
```

```
ALTER WORKLOAD GROUP "group_name"
PROPERTIES (
    property_list
);
```

```
DROP WORKLOAD GROUP if exists  "group_name";
```

```
SHOW WORKLOAD GROUPS;
```
Previous PR is #18184
### Description

_No response_

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liutang123**
## Proposed changes

Issue Number: close #20170

<--Describe your changes.-->

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by liutang123** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
