### PR TITLE
[fix](mtmv)fix mtmv deadlock issue

### PR DESCRIPTION
**Pull request by zddr**
### What problem does this PR solve?

- table1 is olapTable
- mv1 is MTMV create by table1
- mv2 is MTMV create by table1

reason:
- mtmv-task-thread-1: refresh mv1,  blocked write lock :mv1
- show partitions: hold read lock: mv1 ,block read lock: table1
- insert into table1: block write lock: table1
- mtmv-task-thread-2: refresh mv2, hold read lock: table1, blocked read lock :mv1

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

show partitions: not hold readLock of olapTable and MTMV at same time
getAndCopyPartitionItems: set max wait time

### Check List (For Author)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

- Behavior changed:

    - [x] No.
    - [ ] Yes. 

- Does this need documentation?

    - [x] No.
    - [ ] Yes. 

- Release note

    
    
    fix mtmv deadlock issue

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Review by 924060929 — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
