### PR TITLE
[enhencement](hive-catalog) add `hive.recursive_directories_table` and `hive.ignore_absent_partitions` configs for HiveCatalog

### PR DESCRIPTION
**Pull request by BePPPower**
Add 2 configs for Hive Catalog:

1. `hive.recursive_directories_table`: Enable reading data from subdirectories of table or partition locations. If disabled, subdirectories are ignored. Default value is `false`.

2. `hive.ignore_absent_partitions`: Ignore partitions when the file system location does not exist rather than failing the query. This skips data that may be expected to be part of the table. Default value is `true`.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
