### PR TITLE
[Fix](ScannerScheduler) fix dead lock when shutdown group_local_scan_thread_pool

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

1. `_group_local_scan_thread_pool->shutdown();` is called before `_task_group_local_scan_queue->close();`. This could cause problems as threads in the thread pool might still be trying to fetch tasks from the queue. When you shut down the thread pool, these threads might get interrupted while there are still unprocessed tasks in the queue. To avoid this, we should first close the queue and then shut down the thread pool. This way, threads in the thread pool will not try to fetch new tasks after the queue is closed, but instead finish their current tasks and then exit.

2. `_scheduler_pool->wait();` and `_local_scan_thread_pool->join();` are called, but for the other thread pools (`_remote_scan_thread_pool`, `_limited_scan_thread_pool`, `_group_local_scan_thread_pool`), no corresponding `wait` or `join` methods are called. This could result in threads in these thread pools still running after the `ScannerScheduler` object has been destroyed, which could lead to undefined behavior. We should ensure that all threads have exited before destroying the `ScannerScheduler` object.

This PR first closes the task queue, then shuts down all the thread pools, and finally waits for all threads in the thread pools to exit. This ensures that all tasks are properly handled, all threads are properly exited, and avoids resource leaks and undefined behavior.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new mechine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 55.77 seconds
 stream load tsv:          517 seconds loaded 74807831229 Bytes, about 137 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          88.9 seconds inserted 10000000 Rows, about 112K ops/s
 storage size: 17168079879 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706104842_clickbench_pr_173169.html

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 50.62 seconds
 stream load tsv:          464 seconds loaded 74807831229 Bytes, about 153 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          57 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          29 seconds loaded 861443392 Bytes, about 28 MB/s
 insert into select:          68.3 seconds inserted 10000000 Rows, about 146K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230706025734_clickbench_pr_173258.html

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
