### PR TITLE
fix show grants throw NullPointerException

### LINKED ISSUE #22940: [Bug] show grants throw NullPointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

show priv information for a non-existent user throws an exception
```
mysql>  show grants for 'search';
ERROR 1105 (HY000): NullPointerException, msg: java.lang.NullPointerException: null
```

### What You Expected?

```
mysql> show grants for search;
+------------------------------+----------+-------+-------------+--------------+---------------+------------+----------+---------------+--------------------+
| UserIdentity                 | Password | Roles | GlobalPrivs | CatalogPrivs | DatabasePrivs | TablePrivs | ColPrivs | ResourcePrivs | WorkloadGroupPrivs |
+------------------------------+----------+-------+-------------+--------------+---------------+------------+----------+---------------+--------------------+
| 'default_cluster:search'@'%' | NULL     | NULL  | NULL        | NULL         | NULL          | NULL       | NULL     | NULL          | NULL               |
+------------------------------+----------+-------+-------------+--------------+---------------+------------+----------+---------------+--------------------+
```

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luozenglin**
## Proposed changes

Issue Number: close #22940

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luozenglin** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.86 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17162317920 Bytes

**Review by morningman — COMMENTED** [review]
Please add regression test to cover this case

**Comment by luozenglin** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.21 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          97.0 seconds inserted 10000000 Rows, about 103K ops/s
 storage size: 17162096789 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.67 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          99.3 seconds inserted 10000000 Rows, about 100K ops/s
 storage size: 17162297749 Bytes

**Comment by luozenglin** [comment]
> Please add regression test to cover this case

done

**Comment by luozenglin** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.5 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          98.9 seconds inserted 10000000 Rows, about 101K ops/s
 storage size: 17161954130 Bytes

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
