### PR TITLE
[Enhancement](multi-catalog) Add some checks for ShowPartitionsStmt.

### PR DESCRIPTION
**Pull request by dutyu**
## Proposed changes

1.  Add some validations for ShowPartitionsStmt with hive tables
2. Make the behavior consistently with hive, like follows:
hms

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dutyu** [comment]
run buildall

**Comment by dutyu** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Pull request merged**
