### PR TITLE
[Enhance][WIP]add more info when kafka routine load error

### PR DESCRIPTION
**Pull request by sollhui**
# Proposed changes

Issue Number: close #xxx

## Problem summary
At present, when Doris Routine Load stops one instance of Kafka in the multi replica service composed of three nodes, the job will be paused，expect
1. Stopping one or two copies of three copies does not affect writing
2. To complete the automatic recovery task after restarting the Kafka replica

more information needs to be provided by be which can help fe deal with it.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
I'm not sure if this message is a standard one. Could you  get the specific status code? Sorry I'm not familiar with the interaction here so wanted to ask

**Comment by HHoflittlefish777** [comment]
> I'm not sure if this message is a standard one. Could you get the specific status code? Sorry I'm not familiar with the interaction here so wanted to ask

I think it is not a standard one, using enum as status code would be work?

**Comment by morningman** [comment]
Have you try this FE config? `max_tolerable_backend_down_num`

**Comment by morningman** [comment]
> > Have you try this FE config? `max_tolerable_backend_down_num`
> 
> @morningman the purpose of this pr not tolerable backend, but tolerable kafka in the case of three replicates, the primary node goes down

Sorry for the late reply.
I see you only set an error_msg in your PR, I didn't get your point about how to address your issue by only setting an error msg?

**Pull request closed without merging**
