### PR TITLE
[Chore](clang-tidy) remove misc-unused-parameters check

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

remove misc-unused-parameters check

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by luozenglin** [comment]
Why remove this check?

**Comment by BiteTheDDDDt** [comment]
> Why remove this check?

For some abstract methods, we tend not to annotate useless parameters

**Comment by luozenglin** [comment]
> > Why remove this check?
> 
> For some abstract methods, we tend not to annotate useless parameters

Is it possible to remove the parameter name and keep the parameter type in this case?

**Comment by BiteTheDDDDt** [comment]
> 

Yes, but I prefer clang-tidy do not produce a warning on here.

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
