### PR TITLE
[fix](partial update) fix a mem leak issue

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

we should avoid to use raw pointer

### CODE REVIEW

**Comment by zhannngchen** [comment]
run build all

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Review by hust-hhb — APPROVED** [review]
LGTM

**Pull request merged**
