### PR TITLE
[Bug](Variables) Fix bug that execute showVariablesStmt with where expression return empty resultset

### LINKED ISSUE #8093: [Bug]  Execute showVariablesStmt with where expression return empty resultset
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

MySQL [(none)]> show variables where Variable_name = "wait_timeout";
Empty set (0.01 sec)

### What You Expected?

MySQL [(none)]> show variables where Variable_name = "wait_timeout";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.02 sec)

### How to Reproduce?

execute showVariablesStmt with where expression

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
# Proposed changes

Issue Number: close #8093 

## Problem Summary:
This Bug is introduced by PR #7936 , which change key type of connectionMap from Long to Integer, which cause connectionMap could not find connectContext by connectionId 

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
Why change connection id from long to int?

**Comment by caiconghui** [comment]
> Why change connection id from long to int?

the original type of connection id in connect context in  is  int,

**Comment by caiconghui** [comment]
> Why change connection id from long to int?

The value range of connection id is from int_min to int_max, I think it is enough, so I don't change the connection id type in connection context

**Comment by yiguolei** [comment]
LGTM

**Review by weizuo93 — APPROVED** [review]
LGTM

**Pull request merged**
