### PR TITLE
[fix](arrow-flight) BE upgrade arrow to 15.0.2

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

arrow 13.0.0 -> 15.0.2

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Comment by xinyiZzz** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
