### PR TITLE
[refactor](status) refactor querycontext and runtime state status

### PR DESCRIPTION
**Pull request by yiguolei**
## Proposed changes

1. remove is_cancelled from runtimestate and querycontext. 
2. Put is_cancelled and status to atomicstatus.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by mrhhsg — APPROVED** [review]
LGTM

**Review by zhiqiang-hhhh — APPROVED** [review]

**Review by jacktengg — APPROVED** [review]

**Pull request merged**
