### PR TITLE
[fix](routine-load) fix timeout backoff can not work

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

fix https://github.com/apache/doris/pull/32227

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by XuJianxu — APPROVED** [review]
LGTM

**Pull request merged**
