### PR TITLE
remove redundant this

### PR DESCRIPTION
**Pull request by 1000xCoder**
## Proposed changes

Removing redundant this, since it is required mostly in constructor.

Issue Number: #9775 

## Problem Summary:

Before pr:

```
public AlterHandler getSchemaChangeHandler() {
        return this.schemaChangeHandler;
}
```
After pr:

```
public AlterHandler getSchemaChangeHandler() {
        return schemaChangeHandler;
}
```

## Checklist(Required)

Does it affect the original behavior: No
Has unit tests been added: No
Has document been added or modified: No Need
Does it need to update dependencies: No
Are there any changes that cannot be rolled back: No
Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jackwener — APPROVED** [review]
LGTM

**Comment by jackwener** [comment]
cc @yiguolei

**Comment by jackwener** [comment]
cc @hf200012 ,PTAL

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by Vikasss7663** [comment]
Hi @jackwener 
This is to thank you, I have successfully done my first open source contribution, the way you help me means a lot.

The thing I have did, I swear I could do 2 years ago as well but I was scared of open source contribution and it takes almost 2 years for that first contribution because of my fear, but now I think I should give it a try at-least.

Again Thank you ...

**Pull request merged**
