### PR TITLE
[fix](core) fix multi_search_all_positions cause coredump when column nullable

### LINKED ISSUE #19103: [Bug] multi_search_all_positions cause coredump when column nullable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
*** SIGSEGV invalid permissions for mapped object (@0x7f99a6097000) received by PID 911033 (TID 0x7f99451b2700) from PID 18446744072200220672; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /data/doris-1.x/be/src/common/signal_handler.h:420
 1# os::Linux::chained_handler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /usr/local/jdk/jre/lib/amd64/server/libjvm.so
 4# 0x00007F9A11947400 in /lib64/libc.so.6
 5# doris::vectorized::VMysqlResultWriter::_add_one_cell(COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn> const&, unsigned long, std::shared_ptr<doris::vectorized::IDataType const> const&, doris::MysqlRowBuffer&, int) at /data/doris-1.x/be/src/vec/sink/vmysql_result_writer.cpp:321
 6# doris::Status doris::vectorized::VMysqlResultWriter::_add_one_column<(doris::PrimitiveType)17, false>(COW<doris::vectorized::IColumn>::immutable_ptr<doris::vectorized::IColumn> const&, std::unique_ptr<doris::TFetchDataResult, std::default_delete<doris::TFetchDataResult> >&, std::shared_ptr<doris::vectorized::IDataType const> const&, int) at /data/doris-1.x/be/src/vec/sink/vmysql_result_writer.cpp:180
 7# doris::vectorized::VMysqlResultWriter::append_block(doris::vectorized::Block&) at /data/doris-1.x/be/src/vec/sink/vmysql_result_writer.cpp:667
 8# doris::vectorized::VResultSink::send(doris::RuntimeState*, doris::vectorized::Block*) at /data/doris-1.x/be/src/vec/sink/vresult_sink.cpp:96
 9# doris::PlanFragmentExecutor::open_vectorized_internal() at /data/doris-1.x/be/src/runtime/plan_fragment_executor.cpp:320
10# doris::PlanFragmentExecutor::open() at /data/doris-1.x/be/src/runtime/plan_fragment_executor.cpp:259
11# doris::FragmentExecState::execute() at /data/doris-1.x/be/src/runtime/fragment_mgr.cpp:261
12# doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) at /data/doris-1.x/be/src/runtime/fragment_mgr.cpp:508
13# std::_Function_handler<void (), doris::FragmentMgr::exec_plan_fragment(doris::TExecPlanFragmentParams const&, std::function<void (doris::PlanFragmentExecutor*)>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291
14# doris::ThreadPool::dispatch_thread() at /data/doris-1.x/be/src/util/threadpool.cpp:543
15# doris::Thread::supervise_thread(void*) at /data/doris-1.x/be/src/util/thread.cpp:455
16# start_thread in /lib64/libpthread.so.0
17# __clone in /lib64/libc.so.6
```

### What You Expected?

get result 

### How to Reproduce?

CREATE TABLE IF NOT EXISTS strings
            (
                `col1`      INT NOT NULL,
                `content`   TEXT  NULL,
                `mode`      ARRAY<TEXT>  NULL
            ) ENGINE=OLAP
            DUPLICATE KEY(`col1`)
            COMMENT 'OLAP'
            DISTRIBUTED BY HASH(`col1`) BUCKETS 3
            PROPERTIES (
            "replication_allocation" = "tag.location.default: 1",
            "in_memory" = "false",
            "storage_format" = "V2"
            );

            truncate table strings;

            INSERT INTO strings (col1, content, mode) VALUES
            (1, 'Hello, World!', ['hello', 'world'] ),
            (2, 'Hello, World!', ['hello', 'world', 'Hello', '!'] ),
            (3, 'hello, world!', ['Hello', 'world'] ),
            (4, 'hello, world!', ['hello', 'world', 'Hello', '!'] ),
            (5, 'HHHHW!', ['H', 'HHHH', 'HW', 'WH'] ),
            (6, NULL, ['H', 'HHHH', 'HW', 'WH'] ),
            (7, 'HHHHW!', NULL ),
            (8, 'HHHHW!', [NULL, 'HHHH', 'HW', 'WH'] );

select *,multi_search_all_positions(content, ['hello', '!', 'world', 'Hello', 'World']) from strings order by col1;
select *,multi_search_all_positions(content, mode) from strings order by col1;

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nextdreamblue**
# Proposed changes

Issue Number: close #19103

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zclllyybb — DISMISSED** [review]

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run COMPILE

**Comment by nextdreamblue** [comment]
run buildall

**Comment by nextdreamblue** [comment]
run p0

**Comment by nextdreamblue** [comment]
close by https://github.com/apache/doris/pull/19498

**Pull request closed without merging**
