### PR TITLE
[feature](struct-type) support basic struct constructor function

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

ref #16547 

This commit will support struct constructor function.

**need to merge #18392 first.**

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — DISMISSED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
