### PR TITLE
[improve](percentile_approx) use pdqsort to improve percentile_approx function performance

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
could faster about 1s on table rows of count 150000000

Snipaste_2024-08-27_22-16-24

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
