### PR TITLE
[Fix](Variant) implement some interface in ColumnNothing

### PR DESCRIPTION
**Pull request by eldenmoon**
IColumnDummy implementation is not suitable for ColumnNothing in ColumnObject

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]

**Pull request merged**
