### PR TITLE
[feature](nereids) add weekOfYear to support ssb-flat benchmark

### PR DESCRIPTION
**Pull request by englefly**
# Proposed changes
support function `WeekOfYear`
In current implementation, `WeekOfYear` can be used in where clause, but not in select clause.

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
could you add some usage example

**Review by yinzhijian — COMMENTED** [review]
Maybe it would be better to add some regression tests

**Comment by englefly** [comment]
> could you add some usage example
please refer to regression test: test_weekofyear

**Review by 924060929 — DISMISSED** [review]

**Review by yinzhijian — APPROVED** [review]
LGTM

**Review by 924060929 — APPROVED** [review]

**Pull request merged**
