### PR TITLE
[fix](index compaction)Fix core when having multiple dest segments

### PR DESCRIPTION
**Pull request by qidaye**
## Proposed changes

introduced by: #39076

### CODE REVIEW

**Comment by qidaye** [comment]
run buildall

**Comment by qidaye** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
pls paste coredump stack.

**Review by csun5285 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
