### PR TITLE
[fix](FE) fix be coredump when children of FunctionCallExpr is folded

### LINKED ISSUE #16069: [Bug] fix be coredump when children of FunctionCallExpr is folded
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql

CREATE TABLE `a` (
  `k1` int(11) NULL COMMENT "",
  `k2` bitmap BITMAP_UNION NULL COMMENT "",
  `k3` bitmap BITMAP_UNION NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);

CREATE TABLE `b` (
  `k1` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
); 

select  count(distinct case when false then k2 when true then k3 end) as tmp from a where k1 in (select k1 from b group by k1);
ERROR 1105 (HY000): errCode = 2, detailMessage = VSlotRef - invalid slot id 0
```
#### For the selectList rewrite

`count(distinct case when false then k2 when true then k3 end)` rewrite to `count(k3)`

`count(k3)` information:

```java
FunctionCallExpr
- fnParams
  - isDistinct = true
  - exprs
    - CaseExpr
      -  0 = {BoolLiteral@6749} "BoolLiteral false"
         1 = {SlotRef@6750} "SlotRef(k2)"
         2 = {BoolLiteral@6751} "BoolLiteral(true)"
         3 = {SlotRef@6752} "SlotRef(k3)"
- child
  - SlotRef(k3)
```
#### For the Stmt rewrite
It rewrite Selectlist again

use `CountDistinctToBitmapOrHLLRule` rewrite `count(k3)` to `bitmap_union_count`

`bitmap_union_count` information

```java
FunctionCallExpr
- fnParams
  - isDistinct = true
  - exprs
    - CaseExpr
      -  0 = {BoolLiteral@6749} "BoolLiteral false"
         1 = {SlotRef@6750} "SlotRef(k2)"
         2 = {BoolLiteral@6751} "BoolLiteral(true)"
         3 = {SlotRef@6752} "SlotRef(k3)"
- child
  -  0 = {BoolLiteral@6749} "BoolLiteral false"
      1 = {SlotRef@6750} "SlotRef(k2)"
      2 = {BoolLiteral@6751} "BoolLiteral(true)"
      3 = {SlotRef@6752} "SlotRef(k3)"
```
`bitmap_union_count` FunctionCallExpr's child should `k3` instead of `CaseExpr`
and child(1) `SlotRef(k2)` slot id and parent tuple id are last time outdate information.
so Be could coredump.

### What You Expected?

correct

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
# Proposed changes

Issue Number: close #16069

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [x] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.07 seconds
 load time: 496 seconds
 storage size: 17122666964 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230118154234_clickbench_pr_83265.html

**Comment by BiteTheDDDDt** [comment]
Some tests are failing, maybe you should only clone in a specific rewrite rule?

**Comment by qzsee** [comment]
> Some tests are failing, maybe you should only clone in a specific rewrite rule?

It's too tricky to clone in a specific rewrite rules

It also causes some rewrite results to be lost

I'm trying to figure out how to fix it, right.

**Review by morningman — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM

**Pull request merged**
