### PR TITLE
[enhance](mtmv)Disable mtmv list rollup

### PR DESCRIPTION
**Pull request by zddr**
Prohibit creating materialized views on partitions where the base table is a list partition

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run performance

**Comment by zddr** [comment]
run performance

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run cloud_p0

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run cloud_p1

**Comment by zddr** [comment]
run cloud_p1

**Review by morrySnow — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
