### PR TITLE
[Chore](java-udf) add some java-udf function name to asan_suppr

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

```cpp
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55648dcd65ee in malloc (/mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be+0xd0795ee) (BuildId: ef15df7d2d317ee2)
    #1 0x7f4a4fe20f64 in os::malloc(unsigned long, MemoryType, NativeCallStack const&) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x91df64) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #2 0x7f4a4fb16800 in GenericGrowableArray::raw_allocate(int) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x613800) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #3 0x7f4a4fdc956d in MemberNameTable::MemberNameTable(int) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8c656d) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #4 0x7f4a4fb43a8f in InstanceKlass::add_member_name(Handle) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x640a8f) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #5 0x7f4a4fdca9ac in MethodHandles::init_method_MemberName(Handle, CallInfo&) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8c79ac) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #6 0x7f4a4fdd020d in MethodHandles::resolve_MemberName(Handle, KlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8cd20d) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #7 0x7f4a4fdd04c4 in MHN_resolve_Mem (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8cd4c4) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #8 0x7f4a3fec5c33  (<unknown module>)
    #9 0x7f4a3feb60ff  (<unknown module>)
    #10 0x7f4a3feb60ff  (<unknown module>)
    #11 0x7f4a3feb60ff  (<unknown module>)
    #12 0x7f4a3feb60ff  (<unknown module>)
    #13 0x7f4a3feb60ff  (<unknown module>)
    #14 0x7f4a3feb60ff  (<unknown module>)
    #15 0x7f4a3feb60ff  (<unknown module>)
    #16 0x7f4a3feb63b5  (<unknown module>)
    #17 0x7f4a3feb60ff  (<unknown module>)
    #18 0x7f4a3feb60ff  (<unknown module>)
    #19 0x7f4a3feb60ff  (<unknown module>)
    #20 0x7f4a3feb60ff  (<unknown module>)
    #21 0x7f4a3feb60ff  (<unknown module>)
    #22 0x7f4a3feb60ff  (<unknown module>)
    #23 0x7f4a3feb60ff  (<unknown module>)
    #24 0x7f4a3feb60ff  (<unknown module>)
    #25 0x7f4a3feb63b5  (<unknown module>)
    #26 0x7f4a3feae7a6  (<unknown module>)
    #27 0x7f4a4fb94d15 in JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x691d15) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #28 0x7f4a4fb46ad6 in InstanceKlass::call_class_initializer_impl(instanceKlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x643ad6) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #29 0x7f4a4fb490eb in InstanceKlass::initialize_impl(instanceKlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x6460eb) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55648dcd65ee in malloc (/mnt/ssd01/pipline/OpenSourceDoris/clusterEnv/P0/Cluster0/be/lib/doris_be+0xd0795ee) (BuildId: ef15df7d2d317ee2)
    #1 0x7f4a4fe20f64 in os::malloc(unsigned long, MemoryType, NativeCallStack const&) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x91df64) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #2 0x7f4a4fb16800 in GenericGrowableArray::raw_allocate(int) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x613800) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #3 0x7f4a4fdc956d in MemberNameTable::MemberNameTable(int) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8c656d) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #4 0x7f4a4fb43a8f in InstanceKlass::add_member_name(Handle) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x640a8f) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #5 0x7f4a4fdca9ac in MethodHandles::init_method_MemberName(Handle, CallInfo&) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8c79ac) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #6 0x7f4a4fdd020d in MethodHandles::resolve_MemberName(Handle, KlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8cd20d) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #7 0x7f4a4fdd04c4 in MHN_resolve_Mem (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x8cd4c4) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #8 0x7f4a3fec5c33  (<unknown module>)
    #9 0x7f4a3feb60ff  (<unknown module>)
    #10 0x7f4a3feb60ff  (<unknown module>)
    #11 0x7f4a3feb60ff  (<unknown module>)
    #12 0x7f4a3feb60ff  (<unknown module>)
    #13 0x7f4a3feb60ff  (<unknown module>)
    #14 0x7f4a3feb60ff  (<unknown module>)
    #15 0x7f4a3feb60ff  (<unknown module>)
    #16 0x7f4a3feb60ff  (<unknown module>)
    #17 0x7f4a3feb60ff  (<unknown module>)
    #18 0x7f4a3feb60ff  (<unknown module>)
    #19 0x7f4a3feb60ff  (<unknown module>)
    #20 0x7f4a3feb60ff  (<unknown module>)
    #21 0x7f4a3feb60ff  (<unknown module>)
    #22 0x7f4a3feb60ff  (<unknown module>)
    #23 0x7f4a3feb60ff  (<unknown module>)
    #24 0x7f4a3feb60ff  (<unknown module>)
    #25 0x7f4a3feb63b5  (<unknown module>)
    #26 0x7f4a3feae7a6  (<unknown module>)
    #27 0x7f4a4fb94d15 in JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x691d15) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #28 0x7f4a4fb46ad6 in InstanceKlass::call_class_initializer_impl(instanceKlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x643ad6) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)
    #29 0x7f4a4fb490eb in InstanceKlass::initialize_impl(instanceKlassHandle, Thread*) (/usr/local/software/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so+0x6460eb) (BuildId: 78b091327a0bf6d146f8881f285955b4f7f2b712)

SUMMARY: AddressSanitizer: 9238592 byte(s) leaked in 4228 allocation(s).

```

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.47 seconds
 stream load tsv:          443 seconds loaded 74807831229 Bytes, about 161 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          74.8 seconds inserted 10000000 Rows, about 133K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230526081610_clickbench_pr_151131.html

**Comment by BiteTheDDDDt** [comment]
run arm

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
