### PR TITLE
Throw a UserException when miss plugin's md5 file

### PR DESCRIPTION
**Pull request by WingsGo**

### CODE REVIEW

**Comment by WingsGo** [comment]
For #3541

**Review by morningman — COMMENTED** [review]
Actually, we do not require an m5sum when installing plugin from local dir, which is different from http. So, How about just ignore the md5sum if it does not exist?

**Comment by imay** [comment]
> Actually, we do not require an m5sum when installing plugin from local dir, which is different from http. So, How about just ignore the md5sum if it does not exist?

I think we can keep it to avoid install wrong plugin which is not user's intent.

**Review by imay — APPROVED** [review]
LGTM

**Pull request merged**
