### PR TITLE
[fix](fe rest api)api gets execution plan, table name case problem

### PR DESCRIPTION
**Pull request by hf200012**
## Proposed changes
The user has configured the parameter lower_case_table_names, which ignores the case of the table name. When executed on the SQL client, the table name can be queried in both case.
But when using Connector to read doris data, the table names must be in the same case, otherwise an error will be reported.

image

image

connector reading error：
image

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
The current configuration is easily confusing.We need to unify the configuration.

image
image

https://doris.apache.org/docs/dev/lakehouse/multi-catalog/jdbc?_highlight=lower_case_table_names#lowercase-table-name-synchronization

https://doris.apache.org/docs/dev/admin-manual/config/fe-config?_highlight=lower_case_table_names#lower_case_table_names

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
