### PR TITLE
[FIX](func) fix count distinct do not support arr/map/struct

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
with old optimizer:
we would met core when we sql: ``` select count(distinct arr or map or struct) from table```
like this:
```
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
F20231016 17:46:58.601244 3568578 column.h:331] get_max_row_byte_size not supported
*** Check failure stack trace: ***
    @     0x557c8826e206  google::LogMessage::SendToLog()
    @     0x557c8826a7d0  google::LogMessage::Flush()
    @     0x557c8826ea49  google::LogMessageFatal::~LogMessageFatal()
    @     0x557c5f1d88b6  doris::vectorized::IColumn::get_max_row_byte_size()
    @     0x557c6fa60270  doris::vectorized::ColumnNullable::get_max_row_byte_size()
    @     0x557c7984abc3  doris::vectorized::MethodSerialized<>::init_serialized_keys()
    @     0x557c70277e33  doris::vectorized::DistinctAggregationNode::_emplace_into_hash_table_to_distinct()::$_0::operator()<>()
    @     0x557c70277a6d  std::__invoke_impl<>()
    @     0x557c70277a1d  std::__invoke<>()
    @     0x557c7027716d  (unknown)
    @     0x557c7027710a  (unknown)
    @     0x557c70277073  (unknown)
    @     0x557c70276f83  doris::vectorized::DistinctAggregationNode::_emplace_into_hash_table_to_distinct()
    @     0x557c70275b52  doris::vectorized::DistinctAggregationNode::_distinct_pre_agg_with_serialized_key()
    @     0x557c877f0315  doris::pipeline::DistinctStreamingAggSinkOperator::sink()
    @     0x557c8809bb75  doris::pipeline::PipelineTask::execute()
    @     0x557c8823d3af  doris::pipeline::TaskScheduler::_do_work()
    @     0x557c8824c0e9  std::__invoke_impl<>()
    @     0x557c8824bf55  std::__invoke<>()
    @     0x557c8824bec4  _ZNSt5_BindIFMN5doris8pipeline13TaskSchedulerEFvmEPS2_mEE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x557c8824bd2e  std::_Bind<>::operator()<>()
    @     0x557c8824bc45  std::__invoke_impl<>()
    @     0x557c8824bbe5  _ZSt10__invoke_rIvRSt5_BindIFMN5doris8pipeline13TaskSchedulerEFvmEPS3_mEEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESB_E4typeEOSC_DpOSD_
    @     0x557c8824b8dd  std::_Function_handler<>::_M_invoke()
    @     0x557c5ead63e3  std::function<>::operator()()
    @     0x557c61f638e9  doris::FunctionRunnable::run()
    @     0x557c61f4f68e  doris::ThreadPool::dispatch_thread()
    @     0x557c61f760e4  std::__invoke_impl<>()
    @     0x557c61f75fbd  std::__invoke<>()
    @     0x557c61f75f45  _ZNSt5_BindIFMN5doris10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x557c61f75dee  std::_Bind<>::operator()<>()
    @     0x557c61f75d05  std::__invoke_impl<>()

```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run feut

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
