### PR TITLE
[Fix](flexible partial update) Fix auto-increment column value is wrongly updated when it's not specified

### PR DESCRIPTION
**Pull request by bobhan1**

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run cloud_p0

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Pull request closed without merging**
