### PR TITLE
[fix](load) exclude canceled  job when canceling load

### LINKED ISSUE #19215: [Bug] A S3 load job will be submitted successfully with duplicated label of the former failed job, which causes a normal cancel falied
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.


### Version

master

### What's Wrong?

As seen below, load job with the duplicate label will still submitted sucessfully, which cause the later cancel failed.

```
mysql> show load;
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| JobId | Label         | State     | Progress          | Type   | EtlInfo | TaskInfo                                            | ErrorMsg                                                                                                 | CreateTime          | EtlStartTime        | EtlFinishTime       | LoadStartTime       | LoadFinishTime      | URL  | JobDetails                                                                                                                                                                                                                         | TransactionId | ErrorTablets | User | Comment |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| 11001 | lineitem_load | CANCELLED | ETL:N/A; LOAD:N/A | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | type:ETL_RUN_FAIL; msg:errCode = 2, detailMessage = Scan bytes per file scanner exceed limit: 3221225472 | 2023-04-28 20:50:28 | NULL                | NULL                | NULL                | 2023-04-28 20:50:35 | NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":1,"FileSize":7895697364}                                                                                                     | 2             | {}           | root |         |
| 11004 | lineitem_load | CANCELLED | ETL:N/A; LOAD:N/A | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | type:ETL_RUN_FAIL; msg:errCode = 2, detailMessage = Scan bytes per file scanner exceed limit: 5368709120 | 2023-04-28 20:52:49 | NULL                | NULL                | NULL                | 2023-04-28 20:52:54 | NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":1,"FileSize":7895697364}                                                                                                     | 3             | {}           | root |         |
| 11007 | lineitem_load | LOADING   | ETL:100%; LOAD:3% | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | NULL                                                                                                     | 2023-04-28 20:53:22 | 2023-04-28 20:53:23 | 2023-04-28 20:53:23 | 2023-04-28 20:53:23 | NULL                | NULL | {"Unfinished backends":{"1fb727df9d134e05-b2fde24e8a2e1acf":[10011]},"ScannedRows":1682496,"TaskNumber":1,"LoadBytes":305841896,"All backends":{"1fb727df9d134e05-b2fde24e8a2e1acf":[10011]},"FileNumber":1,"FileSize":7895697364} | 4             | {}           | root |         |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
3 rows in set (0.00 sec)

mysql> CANCEL LOAD FROM test WHERE LABEL = "lineitem_load";
ERROR 1105 (HY000): errCode = 2, detailMessage = Cancel load job [11001] fail, label=[lineitem_load] failed msg=errCode = 2, detailMessage = Job could not be cancelled when job is finished or cancelled
``` 

### What You Expected?

No job will be submitted successfully with a duplicated load label.

### How to Reproduce?

Make a S3 load fail, and submit a sucessful job with the same label, it will run normally. Then try to cancel it then failure occurs as shown.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hastyshell**
# Proposed changes

Issue Number: close #19215

## Problem summary

after fix:
```
mysql> show load;
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| JobId | Label         | State     | Progress          | Type   | EtlInfo | TaskInfo                                            | ErrorMsg                                                                                                 | CreateTime          | EtlStartTime        | EtlFinishTime       | LoadStartTime       | LoadFinishTime      | URL  | JobDetails                                                                                                                                                                                                                         | TransactionId | ErrorTablets | User | Comment |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| 11001 | lineitem_load | CANCELLED | ETL:N/A; LOAD:N/A | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | type:ETL_RUN_FAIL; msg:errCode = 2, detailMessage = Scan bytes per file scanner exceed limit: 3221225472 | 2023-05-04 19:19:47 | NULL                | NULL                | NULL                | 2023-05-04 19:19:49 | NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":1,"FileSize":7895697364}                                                                                                     | 1002          | {}           | root |         |
| 11004 | lineitem_load | LOADING   | ETL:100%; LOAD:2% | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | NULL                                                                                                     | 2023-05-04 19:20:52 | 2023-05-04 19:20:53 | 2023-05-04 19:20:53 | 2023-05-04 19:20:53 | NULL                | NULL | {"Unfinished backends":{"3782926ace6f45c5-b199d1091cae9cc8":[10021]},"ScannedRows":1341120,"TaskNumber":1,"LoadBytes":227694824,"All backends":{"3782926ace6f45c5-b199d1091cae9cc8":[10021]},"FileNumber":1,"FileSize":7895697364} | 1003          | {}           | root |         |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+

mysql> CANCEL LOAD FROM test WHERE LABEL="lineitem_load";
Query OK, 0 rows affected (0.01 sec)

mysql> show load;
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| JobId | Label         | State     | Progress          | Type   | EtlInfo | TaskInfo                                            | ErrorMsg                                                                                                 | CreateTime          | EtlStartTime        | EtlFinishTime       | LoadStartTime       | LoadFinishTime      | URL  | JobDetails                                                                                                                                                                                                                         | TransactionId | ErrorTablets | User | Comment |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
| 11001 | lineitem_load | CANCELLED | ETL:N/A; LOAD:N/A | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | type:ETL_RUN_FAIL; msg:errCode = 2, detailMessage = Scan bytes per file scanner exceed limit: 3221225472 | 2023-05-04 19:19:47 | NULL                | NULL                | NULL                | 2023-05-04 19:19:49 | NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"LoadBytes":0,"All backends":{},"FileNumber":1,"FileSize":7895697364}                                                                                                     | 1002          | {}           | root |         |
| 11004 | lineitem_load | CANCELLED | ETL:N/A; LOAD:N/A | BROKER | NULL    | cluster:N/A; timeout(s):14400; max_filter_ratio:0.0 | type:USER_CANCEL; msg:user cancel                                                                        | 2023-05-04 19:20:52 | 2023-05-04 19:20:53 | 2023-05-04 19:20:53 | 2023-05-04 19:20:53 | 2023-05-04 19:22:24 | NULL | {"Unfinished backends":{"3782926ace6f45c5-b199d1091cae9cc8":[10021]},"ScannedRows":2865120,"TaskNumber":1,"LoadBytes":486453189,"All backends":{"3782926ace6f45c5-b199d1091cae9cc8":[10021]},"FileNumber":1,"FileSize":7895697364} | 1003          | {}           | root |         |
+-------+---------------+-----------+-------------------+--------+---------+-----------------------------------------------------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+---------------------+---------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------+------+---------+
```

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by freemandealer** [comment]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
