### PR TITLE
[Fix](multi-catalog) Fix the transaction is not removed in abnormal situations by removing transaction in finally block.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Fix] (multi-catalog) Fix the transaction is not removed in abnormal situations by removing transaction in `finally` block.

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
