### PR TITLE
[cleanup](load) remove unused dynamic schema code

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

support for dynamic schema is removed in #23298, cleanup residue code.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by JackDrogon — COMMENTED** [review]
LGTM

**Pull request merged**
