### PR TITLE
[enhance](mtmv)mtmv date trunc support hour

### PR DESCRIPTION
**Pull request by zddr**
before support:year", "month", "day"

now add:hour

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by seawinde — APPROVED** [review]

**Comment by zddr** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run cloud_p0

**Comment by zddr** [comment]
run cloud_p0

**Pull request merged**
