### PR TITLE
[fix](cloud) cloud group commit should skip repaly wal if label is already used and the txn state is committed or visible

### PR DESCRIPTION
**Pull request by mymeiyi**

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Review by gavinchou — DISMISSED** [review]

**Comment by mymeiyi** [comment]
run cloud_p0

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]

**Pull request merged**
