### PR TITLE
[test](statistics)Add delete test case for statistics.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Add delete test case for statistics.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p0

**Review by morrySnow — APPROVED** [review]

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run p0

**Review by zfr9527 — APPROVED** [review]
LGTM

**Pull request merged**
