### PR TITLE
[FIX](complextype)fix complex type nested version type but not hide version

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx
fix ``` show create table xxx ``` and ``` desc table ``` statement , arr/map/struct not hide the version for date,datetime,decimal version

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Review by morrySnow — DISMISSED** [review]

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]

**Review by morrySnow — DISMISSED** [review]

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
