### PR TITLE
[opt](Nereids) give the easy understand error message when the window func misses the parameters

### PR DESCRIPTION
**Pull request by Reminiscent**
…e window func miss parameters

# Proposed changes
Add the error message when the window func misses the parameters.

## Problem summary
For the new optimizer, if the window func misses the parameter. It will not give an understandable error message. So add the error message.

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — APPROVED** [review]

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.27 seconds
 stream load tsv:          444 seconds loaded 74807831229 Bytes, about 160 MB/s
 stream load json:         22 seconds loaded 2358488459 Bytes, about 102 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          79.4 seconds inserted 10000000 Rows, about 125K ops/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230523130210_clickbench_pr_149048.html

**Comment by Reminiscent** [comment]
run buildp0

**Comment by Reminiscent** [comment]
run p0

**Comment by Reminiscent** [comment]
run p0

**Pull request merged**
