### PR TITLE
[chore](conf)remove unused  doris_max_scan_key_num and max_send_batch_parallelism_per_job conf

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
Use SessionVariable to control it, rather than be conf.

update doc https://github.com/apache/doris-website/pull/1001

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p1

**Comment by Mryange** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by Mryange** [comment]
run cloud_p0

**Review by zclllyybb — APPROVED** [review]
LGTM

**Pull request merged**
