### PR TITLE
[fix](test) load data inpath will remove the data in hdfs

### PR DESCRIPTION
**Pull request by AshinGau**
## Proposed changes

Load data from hdfs in hive will move the source directory into table's location directory, leading the error like `Can not get first file, please check uri` in tvf test.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by AshinGau** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
