### PR TITLE
[Enhancement] (nereids)implement showTableIdCommand in nereids

### LINKED ISSUE #42728: [Enhancement] (nereids)implement showTableIdCommand in nereids
showTableId command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showTableId command in nereids:
unsupportedshowTableIdStatement
``` SHOW TABLE tableId=INTEGER_VALUE                                              ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

implement show table id command in nereids

Issue Number: close #42728 

Related PR: #xxx

Problem Summary:

### Check List (For Committer)

- Test 

    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

mysql> show table 15053;
+----------------------------------------+-----------------------------------+-------+
| DbName                                 | TableName                         | DbId  |
+----------------------------------------+-----------------------------------+-------+
| regression_test_catalog_recycle_bin_p0 | test_truncate_no_partition_backup | 13004 |
+----------------------------------------+-----------------------------------+-------+
1 row in set (0.00 sec)

- Behavior changed:

    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?

    - [ ] No.
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run build all

**Comment by starocean999** [comment]
please add a test case

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run p0

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
