### PR TITLE
[enhancement](log) remove some temp debug log

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
before in this pr https://github.com/apache/doris/pull/25458
wants debug P0 case in TeamCity pipeline, so add some temp debug log, now could remove it.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
