### PR TITLE
[fix](regression) fix unstable test cases and remove redundant cases

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #xxx

## Problem summary

1. aggregate_strategies execution too slow, use smaller table valued function to speed up
2. add a p2 case nereids_syntax_p2/aggregate_strategies to use larger table valued function to ensure correct
3. remove case nereids_syntax_p0/test_join_nereids since it redundant with nereids_p0/join/test_join
4. remove unstable case in query_p0/aggregate/aggregate

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by dataroaring** [comment]
We'd better move larger value case to P2, Because P1 consumes about 40minutes now.

**Comment by morrySnow** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
