### PR TITLE
[test](routine load) fix some unstable routine load cases

### PR DESCRIPTION
**Pull request by sollhui**
Fix some unstable routine load case.

### CODE REVIEW

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by sollhui** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Review by XuJianxu — APPROVED** [review]
LGTM

**Pull request merged**
