### PR TITLE
Doris on es 聚合下推

### PR DESCRIPTION
**Pull request by Userwhite**
## Proposed changes

support pushdown aggregate operator to ES 
https://github.com/apache/incubator-doris/issues/6989

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [x] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [x] Compiling and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuyunfeng** [comment]
@Userwhite As discussed in our online meeting，we should move the predicate-transform from BE (backends) to FE (frontends) which would contribute significant  effect  for subsequent planning and extension. We will continue to pay more attention  and participate in this PR

**Comment by Userwhite** [comment]
> 
OK, I know it. I will deal with it recently. Now nothing has done because I am busy in the last and this week😂

**Comment by Userwhite** [comment]
> > 
> 
> 



> @Userwhite As discussed in our online meeting，we should move the predicate-transform from BE (backends) to FE (frontends) which would contribute significant effect for subsequent planning and extension. We will continue to pay more attention and participation in this PR

OK, I know it. I will deal with it recently. Now nothing has done because I am busy in the last and this week😂

**Comment by stalary** [comment]
Recently, I want to do the generate DSL up to FE, and I also want to support aggregation push down. Can we communicate on wechat? my wechat is 17853149599. @Userwhite

**Comment by jackwener** [comment]
This PR has not been updated for a long time.

There could be many reasons.

If it's caused by there are no maintainers to push or ignore this PR, I'm sorry.

If you contact maintainer or want to continue this PR, feel free to @me or @other maintainers.

**Pull request closed without merging**
