### PR TITLE
[Bug](dry-run) make dryrun result set collect multi batch's QueryStatistics

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
 make dryrun result set collect multi batch's QueryStatistics

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
