### PR TITLE
[regression-test][framework] support cases that can only run in non-concurrent-mode.

### PR DESCRIPTION
**Pull request by shuke987**
## Proposed changes
There are test cases that can be only run in non-concurrent-mode, e.g.
1. cases that will modify global variables
2. cases that will add global block rule
run these cases when other cases are finished in regression-test.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by shuke987** [comment]
run p0

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run buildall

**Comment by shuke987** [comment]
run p0

**Comment by shuke987** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
