### PR TITLE
[enhancement](*): ignore with build_*

### PR DESCRIPTION
**Pull request by jackwener**
# Proposed changes

Issue Number: close #xxx

## Problem Summary:

ignore with build_*

## Checklist(Required)

1. Does it affect the original behavior: (No)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
```shell
be/build_Release/
```
Remove `be/build_Release/`
```shell
be/ut_build*/
be/build_*/
```
Better to have a consistent style here.

**Comment by BiteTheDDDDt** [comment]
LGTM

**Comment by jackwener** [comment]
> ```shell
> be/build_Release/
> ```
> 
> Remove `be/build_Release/`
> 
> ```shell
> be/ut_build*/
> be/build_*/
> ```
> 
> Better to have a consistent style here.

Fixed

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
