### PR TITLE
[opt](Nereids) support drop statement syntax in Nereids

### PR DESCRIPTION
**Pull request by morrySnow**

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run cloud_p1

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Pull request merged**
