### PR TITLE
[opt](memory) `max_sys_mem_available_low_water_mark_bytes`default value modified to 6.4G

### PR DESCRIPTION
**Pull request by xinyiZzz**
// The maximum low water mark of the system `/proc/meminfo/MemAvailable`, Unit byte, default 6.4G,
// actual low water mark=min(6.4G, MemTotal * 10%), avoid wasting too much memory on machines
// with large memory larger than 64G.
// Turn up max. On machines with more than 64G memory, more memory buffers will be reserved for Full GC.
// Turn down max. will use as much memory as possible.

### CODE REVIEW

**Comment by xinyiZzz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by xinyiZzz** [comment]
run buildall

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
