### PR TITLE
[test](hive) run suite cases both in hive2 and hive3

### PR DESCRIPTION
**Pull request by suxiaogang223**
## Proposed changes
Followup: https://github.com/apache/doris/pull/33115
There are hive2 and hive3 dockers in regress-test, so the the original test cases need to be tested in hive2 and hive3 environments.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
doc change https://github.com/apache/doris-website/pull/577

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by suxiaogang223** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
