### PR TITLE
[fix](ci) setup JDK 17 in Code Check CI

### PR DESCRIPTION
**Pull request by Selflocking**
## Proposed changes

Issue Number: close #xxx

Fix Code Check CI
see: 
- https://lists.apache.org/list?dev@doris.apache.org:lte=1M:JDK_17
- https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks

I have tested it in my repo:
https://github.com/Selflocking/doris/actions/runs/8206035510/job/22444233830?pr=2

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Selflocking** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by Selflocking** [comment]
@Yukang-Lian This PR has been open for many days, could you help review it? thanks🥹

**Comment by Yukang-Lian** [comment]
> @Yukang-Lian This PR has been open for many days, could you help review it? thanks🥹

OK

**Comment by Yukang-Lian** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
@Selflocking  Every time you merge master into your PR, you need to comment 'run buildall' and wait check pass. Actually, if there is no conflict between master and your PR, you do NOT need to merge it.

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
https://github.com/apache/doris/pull/32161 after this comment, we do not check java version on clang-tidy prepare

**Comment by Selflocking** [comment]
> #32161 after this comment, we do not check java version on clang-tidy prepare

so should i close this pr?

**Pull request closed without merging**
