### PR TITLE
[fix](merge-cloud) Set visible version for OlapScanNode at the plan phase

### PR DESCRIPTION
**Pull request by w41ter**
## Proposed changes

Issue Number: close #xxx

This PR fixes the spark read with an incorrect partition version in the cloud mode

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — CHANGES_REQUESTED** [review]
cloud_p0 failed a lot.

**Review by gavinchou — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
