### PR TITLE
[Compile] Update Repository for java-cup and cup-maven-plugin

### PR DESCRIPTION
**Pull request by coalchan**
## Proposed changes

cloudera repository has been moved to https://repository.cloudera.com/artifactory/[xxx], like https://repository.cloudera.com/artifactory/public

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Comment by gowuliao** [comment]
sed -i "s#\(https://repository.cloudera.com\)[^<]*#\1/artifactory/libs-release-local#g" fe/pom.xml

**Comment by Ling2099** [comment]
在编译 apache/doris:build-env-for-1.1.0 时，fe/pom.xml 中的内容已经是 `<id>cloudera-public</id>` 与 `<url>https://repository.cloudera.com/artifactory/public/</url>` 了，为什么还是会出现 Plugin net.sourceforge.czt.dev:cup-maven-plugin:1.6-cdh or one of its dependencies could not be resolved: Failed to read... 错误呢？

**Comment by xuchen-plus** [comment]
The url `https://repository.cloudera.com/artifactory/public/` for this plugin seems outdated again. I found it here: https://repository.cloudera.com/#browse/search=keyword%3Dnet.sourceforge.czt.dev%3Acup-maven-plugin:NX.coreui.model.Component-1
Download all files and put them under local maven repo dir and the compilation of FE succeeds.

**Comment by issue-K** [comment]
Can we fix this? It's not working

**Pull request merged**
