### PR TITLE
[fix](Nereids) Fixed a bug where the execution plan was incorrect after ddl

### PR DESCRIPTION
**Pull request by xingyingone**
[fix](Nereids) Fixed a bug where the execution plan was incorrect after ddl

## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/29987

master PR: https://github.com/apache/doris/pull/30107

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
https://github.com/apache/doris/pull/30107

**Comment by xingyingone** [comment]
run  buildall

**Comment by xingyingone** [comment]
run  buildall

**Comment by xingyingone** [comment]
run buildall

**Comment by xingyingone** [comment]
run P0 Regression (ARM pipeline)

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
