### PR TITLE
[FIX](serde)fix datetimev2 serde parse from string with scale

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
This pr should be merge to branch-2.0

**Pull request merged**
