### PR TITLE
[fix](function)return NULL rather than 'null' if path not found

### PR DESCRIPTION
**Pull request by Yulei-Yang**
cherry-pick #25880
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run feut

**Comment by xiaokang** [comment]
@Yulei-Yang  feut and p0 failed case should be fixed

**Comment by Yulei-Yang** [comment]
run feut

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
> @Yulei-Yang feut and p0 failed case should be fixed

morningman said he will handle it

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
