### PR TITLE
[Chore](inverted index) remove useless code in scan operator for normalize compound and match predicate

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes
Remove unused code in scan operator for normalizing compound and match predicate

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run cloudp0

**Comment by airborne12** [comment]
run cloud_p0

**Review by eldenmoon — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Pull request merged**
