### PR TITLE
[regression-test](flink-connector) add flink connector data type case

### PR DESCRIPTION
**Pull request by JNSimba**
## Proposed changes

Add cases about data types in flink connector

### CODE REVIEW

**Comment by 924060929** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Comment by JNSimba** [comment]
run buildall

**Review by CalvinKirs — APPROVED** [review]

**Review by caoliang-web — APPROVED** [review]
LGTM

**Pull request merged**
