### PR TITLE
[fix](ip-search)fix ip search with inverted index

### PR DESCRIPTION
**Pull request by amorynan**
### What problem does this PR solve?
this pr is to solve is_ip_address_in_range with invalid param 
Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [x] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
May be some UT tests needed.

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
