### PR TITLE
[Chore](case) remove max in num check case

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
remove max in num check case

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zhangstar333 — DISMISSED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
