### PR TITLE
[refactor](mysql result format) use new serde framework to tuple conv…

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
pick [#25006](https://github.com/apache/doris/pull/25006)

### CODE REVIEW

**Comment by zhiqiang-hhhh** [comment]
@xiaokang @yiguolei

**Comment by xiaokang** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Pull request merged**
