### PR TITLE
[fix](lock): do not use instance lock to protect static data

### PR DESCRIPTION
**Pull request by xutaoustc**
[fix](lock): do not use instance lock to protect static data

### CODE REVIEW

**Comment by yiguolei** [comment]
run buildall

**Comment by xutaoustc** [comment]
run buildall

**Comment by xutaoustc** [comment]
run buildall

**Comment by xutaoustc** [comment]
run p0

**Comment by yiguolei** [comment]
run buildall

**Comment by xutaoustc** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
