### PR TITLE
[fix](multi-catalog)fix hive catalog docs, obs impl, dlf properties

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

1. fix hive catalog docs 
2. fix dlf properties
3. fix obs impl

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by luzhijing — DISMISSED** [review]
LGTM

**Comment by luzhijing** [comment]
run buildall

**Comment by luzhijing** [comment]
run p0

**Review by morningman — CHANGES_REQUESTED** [review]
Do not merge, the bug in code also need to fix

**Comment by wsjz** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
