### PR TITLE
[fix](regression) Add regression for group commit executed on observe…

### PR DESCRIPTION
**Pull request by mymeiyi**
…r fe

## Proposed changes

The related PR is https://github.com/apache/doris/pull/26589

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
