### PR TITLE
[feature](extension) support beats output to doris

### PR DESCRIPTION
**Pull request by hailin0**
# Proposed changes

Issue Number: close #xxx

## Problem summary

This is an output implementation of [elastic beats](https://github.com/elastic/beats) for support [Filebeat](https://github.com/elastic/beats/tree/master/filebeat), [Metricbeat](https://github.com/elastic/beats/tree/master/metricbeat), [Packetbeat](https://github.com/elastic/beats/tree/master/packetbeat), [Winlogbeat](https://github.com/elastic/beats/tree/master/winlogbeat), [Auditbeat](https://github.com/elastic/beats/tree/master/auditbeat), [Heartbeat](https://github.com/elastic/beats/tree/master/heartbeat) to [Apache Doris](https://github.com/apache/doris).

This module is used to output data to Doris for elastic beats, use the HTTP protocol to interact with the Doris FE Http interface, and import data through Doris's stream load.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [x] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Hi @hailin0 Thanks for your contribution.
There are some issues:
1. We prefer using 4 spaces instead tab for intent, could you please change it?
2. How to run `extension/beats/doris/doris_integration_test.go`? Please give an example so that I can add it to regression test.
3. `extension/beats/go.mod ` missing license header, please add it.

**Comment by CalvinKirs** [comment]
> > Hi @hailin0 Thanks for your contribution. There are some issues:↳
> > 
> > 1. We prefer using 4 spaces instead tab for intent, could you please change it?
> > 2. How to run `extension/beats/doris/doris_integration_test.go`? Please give an example so that I can add it to regression test.
> > 3. `extension/beats/go.mod ` missing license header, please add it.
you should update this file https://github.com/apache/doris/blob/master/.licenserc.yaml#L6, 
Then we will skip the checking of these two files.
> 
> I see logstash plugin, how does he do the test↳
> 
> https://github.com/apache/doris/tree/master/extension/logstash

**Review by morningman — DISMISSED** [review]
hi @hailin0 
Could you give a brief command line to run `extension/beats/doris/doris_integration_test.go`, suppose that there 
is already Doris cluster?

I will add this to the regression test later. And this PR LTGM

**Comment by morningman** [comment]
run  buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
