### PR TITLE
[bugfix](hive/iceberg)align with Hive insert overwrite table functionality

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

When execute: `insert overwrite table tb1 select * from tb2` and `tb2` is an empty table:
1. if `tb1` is a partition table, there will be nothing to do.
2. if `tb1` is a unpartition table, the data in the table will be cleared.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run feut

**Review by morningman — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
