### PR TITLE
[typo](doc) add limitation description for inverted index

### PR DESCRIPTION
**Pull request by gnehil**
## Proposed changes

add limitation description for inverted index for different data model.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by caoliang-web — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by CalvinKirs — COMMENTED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Review by CalvinKirs — COMMENTED** [review]
LGTM

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
TEST

**Review by CalvinKirs — APPROVED** [review]

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
TEST

**Review by CalvinKirs — APPROVED** [review]

**Review by CalvinKirs — COMMENTED** [review]
well done

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
