### PR TITLE
[fix](invert index) fix clucene compiler warning

### PR DESCRIPTION
**Pull request by zzzxl1993**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zzzxl1993** [comment]
run buildall

**Comment by zzzxl1993** [comment]
run beut

**Comment by zzzxl1993** [comment]
run beut

**Comment by zzzxl1993** [comment]
run beut

**Comment by zzzxl1993** [comment]
run buildall

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run p0

**Comment by zzzxl1993** [comment]
run p1

**Comment by zzzxl1993** [comment]
run p0

**Pull request merged**
