### PR TITLE
[function](round) fix decimal scale for scale not specified

### PR DESCRIPTION
**Pull request by maochongxin**
before:
```
MySQL [test]> select round(col1) from tbl;
+---------------+
| round(`col1`) |
+---------------+
|      16000000 |
+---------------+
1 row in set (0.30 sec)
```

```
-- !select --
16000   1600000 1600000

-- !select --
16000   1600000 1600000

-- !select --
17000   1700000 1700000

-- !select --
16000   1600000 1600000

-- !select --
16.030  16.03000        16.03000

-- !select --
16.020  16.02000        16.02000

-- !select --
16.030  16.03000        16.03000

-- !select --
16.020  16.02000        16.02000

-- !select --
16.020  16.02000        16.02000
```

now:
```
MySQL [test]> select round(col1) from tbl;
+---------------+
| round(`col1`) |
+---------------+
|     16.000000 |
+---------------+
1 row in set (0.06 sec)
```

```
-- !select --
16.000  16.00000        16.00000

-- !select --
16.000  16.00000        16.00000

-- !select --
17.000  17.00000        17.00000

-- !select --
16.000  16.00000        16.00000

-- !select --
16.030  16.03000        16.03000

-- !select --
16.020  16.02000        16.02000

-- !select --
16.030  16.03000        16.03000

-- !select --
16.020  16.02000        16.02000

-- !select --
16.020  16.02000        16.02000
```

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.8 seconds
 load time: 631 seconds
 storage size: 17123579763 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221230160959_clickbench_pr_72097.html

**Comment by Gabriel39** [comment]
Hi @maochongxin , I have some questions for this PR. Could you add my WeChat account? My ID is HongKanStation

**Comment by Gabriel39** [comment]
Pls add regression cases

**Comment by maochongxin** [comment]
> Pls add regression cases

done

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Pull request merged**
