### PR TITLE
[regression] Add a case to check if light_schema_change=true when creating table

### PR DESCRIPTION
**Pull request by Lchangliang**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Checking master and 2.0 that if light_schema_change=true when creating table.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Lchangliang** [comment]
run buildall

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by Lchangliang** [comment]
run p0

**Comment by Lchangliang** [comment]
run buildall

**Comment by Lchangliang** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
