### PR TITLE
[chore](multi catalog) Improve network interface detection in Hive container script

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

Improved the network interface detection logic in the run container script to better support systems with multiple network interfaces (such as eth0, eth1, etc.). 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Review by lide-reed — DISMISSED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Review by cambyzju — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
