### PR TITLE
[Fix](Json type) forbit schema change adding JSON columns with none n…

### PR DESCRIPTION
**Pull request by eldenmoon**
…ull default value

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by eldenmoon** [comment]
run buildall

**Comment by eldenmoon** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
