### PR TITLE
[regressiontest](statistics) Comment stats unstable cases

### PR DESCRIPTION
**Pull request by weizhengte**
# Proposed changes

When p0 executes `delete from`, it will be unstable, wait for the repair and reopen related cases. 

P1 is still in effect.

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Comment by weizhengte** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Comment by weizhengte** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
