### PR TITLE
[fix](test) fix unstable pk uk case

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Variables should use `def` to define local variables in groovy.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run buildall

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
