### PR TITLE
[branch-2.0](multi catalog) Print serde properties when show create hive-external-table

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

Issue Number: close #xxx

cherry-pick: #34966

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run fe_ut

**Comment by xy720** [comment]
run feut

**Review by cambyzju — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run p0

**Comment by xy720** [comment]
run feut

**Comment by xy720** [comment]
run fe_ut

**Review by lide-reed — APPROVED** [review]
LGTM

**Pull request merged**
