### PR TITLE
[fix](pipelineX) _local_channel_dependency is null in non pipelineX

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

odd pr test https://github.com/apache/doris/pull/32055

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by zhiqiang-hhhh — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by wangbo — APPROVED** [review]
LGTM

**Pull request merged**
