### PR TITLE
Revert "[Enhancement](Nereids)enable nereids DML by default. (#21539)"

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

This reverts #21539 (commit f668b3965effbd5df4902f20b496cb6b6642414c).

Because it's blocking P0 regression test.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 53.94 seconds
 stream load tsv:          544 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17169966318 Bytes

**Review by morrySnow — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
