### PR TITLE
[fix](script)  do not prepare lakesoul data when --stop

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

Issue Number: close #xxx

It should not run the command to prepare lakesoul data when --stop

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by hello-stephen** [comment]
run external

**Review by englefly — APPROVED** [review]

**Pull request merged**
