### PR TITLE
[feature](restore) Support clean_tables/clean_partitions properties for restore job

### PR DESCRIPTION
**Pull request by w41ter**
The restore will keep the existing tables/partitions in which the restore target is not contained, this PR adds a property clean_restore to indicate that the restore job needs to recycle those tables/partitions

The CCR part PR is: selectdb/ccr-syncer#128.
The website PR is: apache/doris-website#999

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by xy720 — COMMENTED** [review]
Hi, can you update the docs about these two properties?

**Comment by w41ter** [comment]
> Hi, can you update the docs about these two properties?

updated

**Review by xy720 — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
