### PR TITLE
[fix](funcs) map struct construct funcs

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
we should not change the column which is passed from a block when we execute a function , because this block may be used in other expression or other exec node
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
