### PR TITLE
[Enhancement](function)make SUBSTRING_INDEX function DEPEND_ON_ARGUMENT

### PR DESCRIPTION
**Pull request by koarz**
## Proposed changes

Issue Number:  #27435 

make function SUBSTRING_INDEX DEPEND_ON_ARGUMENT

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by koarz** [comment]
run p0

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by koarz** [comment]
run buildall

**Comment by koarz** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
