### PR TITLE
[fix](planner)Fix missing kw for workload

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
1 add usage docment for Workload Group query queue;
2 Fix missing KW for ```workload```, this may cause create workload group failed.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
