### PR TITLE
Masking glibc symbols for better portability

### PR DESCRIPTION
**Pull request by amosbird**
## Proposed changes

In ClickHouse we have glibc symbols masked to backport down towards CentOS 5 (glibc 2.5). It's quite useful for creating portable executables. I'd love to have this capability shipped into Doris :)

This PR contains glibc related symbols extracted from https://github.com/bminor/musl/commit/593caa456309714402ca4cb77c3770f4c24da9da . It's been verified in ClickHouse and works perfectly. I've also shipped https://github.com/skywind3000/FastMemcpy together to have a hosted memcpy implementation. Otherwise it requires glibc@2.14 which is not available on most CentOS 6 machines.

Btw, I've also disabled libssh2 and nghttp2 when building libcurl. It somehow introduces weird dependency issues on my dev machine (gentoo). Please verify if they are indeed necessary.

After this PR, palo_be only requires glibc 2.10. Related license files are attached too.

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Doris's issues](https://github.com/apache/incubator-doris/issues), and have described the bug/feature there in detail
- [X] Commit messages in my PR start with the related issues ID, like "#4071 Add pull request template to doris project"
- [X] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I have updated the document
- [X] Any dependent changes have been merged

### CODE REVIEW

**Comment by morningman** [comment]
Good work!
I am not familiar with this part of the logic, but I read some of the cited articles you gave.
I have some questions:

1. What is difference between `src/glibc-compatibility/FastMemcpy.h` and `src/FastMemcpy/FastMemcpy.h`?
2. Does it compatible with ARM?

**Comment by amosbird** [comment]
> What is difference between src/glibc-compatibility/FastMemcpy.h and src/FastMemcpy/FastMemcpy.h?

Oops, those are redundant. I'll get rid of the FastMemcpy folder.

> Does it compatible with ARM?

Not yet in this PR, but it's doable. I've done ARM-compatible stuff for ClickHouse. I'll send another PR if this one gets accepted :)

**Comment by morningman** [comment]
> Not yet in this PR, but it's doable. I've done ARM-compatible stuff for ClickHouse. I'll send another PR if this one gets accepted :)

Thanks!
But we are going the release version 0.13, I think its better to merge this PR after we create 0.13 branch.
It will be soon.

**Comment by amosbird** [comment]
> But we are going the release version 0.13 ...
Great!

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
