### PR TITLE
[fix](debug point) fix gcc compile

### PR DESCRIPTION
**Pull request by yujun777**
performance pipeline enable missing-field-initializers warning,  it cause compile fail:

```
13:27:42   /root/doris/be/src/util/debug_points.h: In member function 'void doris::DebugPoints::add_with_params(const std::string&, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)':
13:27:42   /root/doris/be/src/util/debug_points.h:159:79: error: missing initializer for member 'doris::DebugPoint::handler' [-Werror=missing-field-initializers]
13:27:42     159 |         add(name, std::shared_ptr<DebugPoint>(new DebugPoint {.params = params}));
13:27:42         |                                                                               ^
13:27:42   /root/doris/be/src/util/debug_points.h: In member function 'void doris::DebugPoints::add_with_handler(const std::string&, std::any)':
13:27:42   /root/doris/be/src/util/debug_points.h:167:81: error: missing initializer for member 'doris::DebugPoint::params' [-Werror=missing-field-initializers]
13:27:42     167 |         add(name, std::shared_ptr<DebugPoint>(new DebugPoint {.handler = handler}));
13:27:42         |                                                                                 ^
13:27:42   cc1plus: all warnings being treated as errors
13:27:43   [572/1346] Building CXX object src/http/CMakeFiles/Webserver.dir/action/stream_load.cpp.o
```

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run beut

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run cloud_p1

**Comment by yujun777** [comment]
run p1

**Review by w41ter — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
