### PR TITLE
[opt](merge-on-write) eliminate reading the old values of non-key columns for delete stmt in publish phase

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

https://github.com/apache/doris/pull/22270 should also do in pulish phase

branch-2.1-pick: https://github.com/apache/doris/pull/39074

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
