### PR TITLE
[refactor](Nereids) let type coercion same with legacy planner

### LINKED ISSUE #16714: let Nereids's type coercion exactly same with legacy planner

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

Issue Number: close #16714 

- change for Nereids
1. add a variable length parameter to the ctor of Count for a good error reporting of Count(a, b)
2. refactor StringRegexPredicate, let it inherit from ScalarFunction
3. remove useless class TypeCollection
4. use catalog.Type.Collection to check expression arguments type
5. change type coercion for TimestampArithmetic, divide, integral divide, comparison predicate, case when and in predicate. Let them same as legacy planner.

- change for legacy planner
1. change the common type of floating and Decimal from Decimal to Double

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morrySnow** [comment]
run p0 feut

**Comment by morrySnow** [comment]
run p0 feut

**Comment by morrySnow** [comment]
run p0 feut

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run p0 feut

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run compile

**Comment by morrySnow** [comment]
run feut beut clickbench

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run buildall

**Review by jackwener — APPROVED** [review]

**Pull request merged**
