### PR TITLE
[fix](be) doris_be compile failed

### LINKED ISSUE #20931: [Bug] Compile be failed with undefined reference on master branch.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev-master

### What's Wrong?

link doris_be failed with the following error.

```
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:56: error: undefined reference to 'doris::GeoPoint::GeoPoint()'                                                                                                                                                            
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:59: error: undefined reference to 'doris::GeoPoint::from_coord(double, double)'                                                                                                                                            
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:67: error: undefined reference to 'doris::GeoShape::encode_to(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'                                                                           
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:73: error: undefined reference to 'doris::GeoPoint::~GeoPoint()'                                                                                                                                                           
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:73: error: undefined reference to 'doris::GeoPoint::~GeoPoint()'                                                                                                                                                           
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:130: error: undefined reference to 'doris::GeoPoint::GeoPoint()'                                                                                                                                                           
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:133: error: undefined reference to 'doris::GeoShape::decode_from(void const*, unsigned long)'                                                                                                                              
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:139: error: undefined reference to 'doris::GeoPoint::x() const'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:145: error: undefined reference to 'doris::GeoPoint::~GeoPoint()'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:145: error: undefined reference to 'doris::GeoPoint::~GeoPoint()'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:162: error: undefined reference to 'doris::GeoPoint::GeoPoint()'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:165: error: undefined reference to 'doris::GeoShape::decode_from(void const*, unsigned long)'                                                                                                                             
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:171: error: undefined reference to 'doris::GeoPoint::y() const'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:199: error: undefined reference to 'doris::GeoPoint::ComputeDistance(double, double, double, double, double*)'                                                                                                            
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:233: error: undefined reference to 'doris::GeoPoint::ComputeAngleSphere(double, double, double, double, double*)'                                                                                                         
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:262: error: undefined reference to 'doris::GeoPoint::GeoPoint()'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:268: error: undefined reference to 'doris::GeoShape::decode_from(void const*, unsigned long)'                                                                                                                             
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:275: error: undefined reference to 'doris::GeoShape::decode_from(void const*, unsigned long)'                                                                                                                             
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:288: error: undefined reference to 'doris::GeoPoint::ComputeAngle(doris::GeoPoint*, doris::GeoPoint*, doris::GeoPoint*, double*)'                                                                                         
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:331: error: undefined reference to 'doris::GeoPoint::ComputeAzimuth(doris::GeoPoint*, doris::GeoPoint*, double*)'                                                                                                         
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:358: error: undefined reference to 'doris::GeoShape::from_encoded(void const*, unsigned long)'                                                                                                                            
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:365: error: undefined reference to 'doris::GeoShape::ComputeArea(doris::GeoShape*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'                                             
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:393: error: undefined reference to 'doris::GeoShape::from_encoded(void const*, unsigned long)'                                                                                                                            
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:400: error: undefined reference to 'doris::GeoShape::ComputeArea(doris::GeoShape*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'                                             
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:430: error: undefined reference to 'doris::GeoCircle::GeoCircle()'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:437: error: undefined reference to 'doris::GeoCircle::init(double, double, double)'
/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:443: error: undefined reference to 'doris::GeoShape::encode_to(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'                                                                         /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:448: error: undefined reference to 'doris::GeoCircle::~GeoCircle()'/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:448: error: undefined reference to 'doris::GeoCircle::~GeoCircle()'/opt/doris/2x/be/src/vec/functions/functions_geo.cpp:480: error: undefined reference to 'doris::GeoShape::from_encoded(void const*, unsigned long)'                                                                                                                            /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:649: error: undefined reference to 'doris::GeoShape::from_encoded(void const*, unsigned long)'                                                                                                                            /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:655: error: undefined reference to 'doris::GeoShape::as_binary[abi:cxx11](doris::GeoShape*)'                                                                                                                              /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:610: error: undefined reference to 'doris::GeoShape::from_wkb(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:616: error: undefined reference to 'doris::GeoShape::encode_to(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'                                                                         /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:610: error: undefined reference to 'doris::GeoShape::from_wkb(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:616: error: undefined reference to 'doris::GeoShape::encode_to(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'                                                                         /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:559: error: undefined reference to 'doris::GeoShape::from_wkt(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:559: error: undefined reference to 'doris::GeoShape::from_wkt(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:559: error: undefined reference to 'doris::GeoShape::from_wkt(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        /opt/doris/2x/be/src/vec/functions/functions_geo.cpp:559: error: undefined reference to 'doris::GeoShape::from_wkt(char const*, unsigned long, doris::GeoParseStatus*)'                                                                                                        collect2: error: ld returned 1 exit statusmake[2]: *** [src/service/CMakeFiles/doris_be.dir/build.make:244: src/service/doris_be] Error 1make[1]: *** [CMakeFiles/Makefile2:2248: src/service/CMakeFiles/doris_be.dir/all] Error 2make: *** [Makefile:156: all] Error 2
```

### What You Expected?

build success.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gohalo**
## Proposed changes

Issue Number: close #20931

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Comment by gohalo** [comment]
have no idea how to fix this complie failed problem

image

**Comment by gohalo** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.82 seconds
 stream load tsv:          508 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17167876250 Bytes

**Comment by gohalo** [comment]
run buildall

**Comment by gohalo** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.22 seconds
 stream load tsv:          513 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162387069 Bytes

**Comment by LemonLiTree** [comment]
Where did you compile and report the error? I have always had no problem compiling on mac and linux

**Comment by gohalo** [comment]
> Where did you compile and report the error? I have always had no problem compiling on mac and linux

image

**Comment by LemonLiTree** [comment]
> > Where did you compile and report the error? I have always had no problem compiling on mac and linux
> 
> image
> 
> still have the errors now...

add my wechat : LQF1296996755

**Review by LemonLiTree — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.84 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17162042221 Bytes

**Comment by LemonLiTree** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run  buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 48.62 seconds
 stream load tsv:          536 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17161960520 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
