### PR TITLE
[fix](cluster key) fix bug if be enable enable_rowid_conversion_correctness_check

### PR DESCRIPTION
**Pull request by mymeiyi**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

fix:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
*** Query id: 0-0 ***
*** is nereids: 0 ***
*** tablet id: 1980528 ***
*** Aborted at 1733280745 (unix time) try "date -d @1733280745" if you are using GNU date ***
*** Current BE git commitID: 009e5a82c4 ***
*** SIGABRT unknown detail explain (@0x4290022570e) received by PID 2250510 (TID 2251330 OR 0x7f21b45dd700) from PID 2250510; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/meiyi/clion_workspace/doris/be/src/common/signal_handler.h:421
 1# 0x00007F24197AFB50 in /lib64/libc.so.6
 2# gsignal in /lib64/libc.so.6
 3# __GI_abort in /lib64/libc.so.6
 4# __gnu_cxx::__verbose_terminate_handler() [clone .cold] at ../../../../libstdc++-v3/libsupc++/vterminate.cc:75
 5# __cxxabiv1::__terminate(void (*)()) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
 6# 0x0000564E1F9917D1 in /mnt/disk2/meiyi/deployment/doris/output/be/lib/doris_be
 7# 0x0000564E1F991924 in /mnt/disk2/meiyi/deployment/doris/output/be/lib/doris_be
 8# std::__throw_system_error(int) at ../../../../../libstdc++-v3/src/c++11/system_error.cc:338
 9# std::__shared_mutex_pthread::lock_shared() at /mnt/disk2/meiyi/soft/ldb_toolchain_2/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/shared_mutex:232
10# std::shared_mutex::lock_shared() at /mnt/disk2/meiyi/soft/ldb_toolchain_2/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/shared_mutex:426
11# std::shared_lock<std::shared_mutex>::shared_lock(std::shared_mutex&) at /mnt/disk2/meiyi/soft/ldb_toolchain_2/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/shared_mutex:727
12# doris::BaseTablet::tablet_schema() const at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/base_tablet.h:91
13# doris::BaseTablet::check_rowid_conversion(std::shared_ptr<doris::Rowset>, std::map<std::shared_ptr<doris::Rowset>, std::__cxx11::list<std::pair<doris::RowLocation, doris::RowLocation>, std::allocator<std::pair<doris::RowLocation, doris::RowLocation> > >, std::less<std::shared_ptr<doris::Rowset> >, std::allocator<std::pair<std::shared_ptr<doris::Rowset> const, std::__cxx11::list<std::pair<doris::RowLocation, doris::RowLocation>, std::allocator<std::pair<doris::RowLocation, doris::RowLocation> > > > > > const&) at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/base_tablet.cpp:1607
14# doris::CompactionMixin::modify_rowsets() at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/compaction.cpp:1087
15# doris::CompactionMixin::execute_compact_impl(long) at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/compaction.cpp:472
16# doris::CompactionMixin::execute_compact() at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/compaction.cpp:425
17# doris::CumulativeCompaction::execute_compact() at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/cumulative_compaction.cpp:111
18# doris::Tablet::execute_compaction(doris::CompactionMixin&)::$_0::operator()() const at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/tablet.cpp:1850
19# doris::Tablet::execute_compaction(doris::CompactionMixin&) at /mnt/disk2/meiyi/clion_workspace/doris/be/src/olap/tablet.cpp:1850
```

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by zhannngchen** [comment]
please explain how this PR solve the core, the code change is not seem very intuitive

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
