### PR TITLE
[Test](hive-writer) Adjust test_hive_write_partitions regression test to resolve special characters issue with git on windows.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Test] (hive-writer) Adjust test_hive_write_partitions regression test to resolve special characters issue with git on windows.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run external

**Comment by kaka11chen** [comment]
run external

**Comment by kaka11chen** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Pull request merged**
