### PR TITLE
[enhancement](node) add filter in partition sort node in BE

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
add filter in partition sort node in BE

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — COMMENTED** [review]
better add a case to reach the code

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run p1

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
