### PR TITLE
[improvement](doc) Supplementary Bulk Deletion Notes

### PR DESCRIPTION
**Pull request by ya-dao**
# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [x] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

* 按照批量删除文档前文的介绍, 用户可能会开启`show_hidden_columns`的session variable来查看表是否支持批量删除. 
* 后续按示例进行DELETE/MERGE的导入作业后, 如果在同一个session中执行`select count(*) from xxx`语句时, 可能会发现结果与预期不一致
* 无法快速联想到是因为之前开启的session variable导致被删除的语句也被查出来了.

### CODE REVIEW

**Comment by luzhijing** [comment]
Hello, please use English in community and supplement the corresponding English documents.

**Comment by dataroaring** [comment]
You'd better write title and commit message in english.

**Comment by ya-dao** [comment]
sorry, I forgot to reply this after committing, I committed the english doc, if there still something need to do please level a comment for me.

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
> sorry, I forgot to reply this after committing, I committed the english doc, if there still something need to do please level a comment for me.

Welcome to Apache Doris Community and look forward to your joining!

**Comment by ya-dao** [comment]
Does the PR flow finished?

**Comment by luzhijing** [comment]
run buildall

**Comment by ya-dao** [comment]
> run buildall

Means just wait for end of the check list run, it will close automatically? I checked other closed PR, it seems that no more command can execute by committer.

**Comment by luzhijing** [comment]
run P0

**Comment by luzhijing** [comment]
> > run buildall
> 
> Means just wait for end of the check list run, it will close automatically? I checked other closed PR, it seems that no more command can execute by committer.

Yes, if the checklist is not finished, you can start it with the command `run buildall`

**Pull request merged**
