### PR TITLE
[Enhancement](compaction) stop tablet compaction when table dropped

### LINKED ISSUE #18446: [Enhancement] (compaction) stop tablet compaction when table truncated
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

When truncate table, tablet in be will still do compaction as current tablet in be has no information about table status in fe.
So, we have to build a relation in be tablet and fe table truncate status.

### Solution

add a tablet status and make fe and be related when truncate table

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gitccl**
# Proposed changes

Issue Number: close #18446

## Problem summary

When table was dropped without FORCE, tablet in be will still do compaction as current tablet in be has no information about table status in fe. 

To solve this problem, we add a field `is_dropped` to both fe and be 's TabletMeta to indicate whether the tablet is dropped, and tablet with `is_dropped=true` will not be compacted.
When a table was dropped, the `is_dropped` in fe's TabletMeta will be set to true. When be reports tablet to fe, fe will compare be's `is_dropped` with its own. If it is different, fe will send an UPDATE_TABLET_META_INFO AgentTask to be to change be's `is_dropped`.

The recover process is similar to the above.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by gitccl** [comment]
run buildall

**Comment by gitccl** [comment]
run buildall

**Comment by yixiutt** [comment]
LGTM

**Review by yixiutt — APPROVED** [review]

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by gitccl** [comment]
@zhannngchen Hi, can this pr be merged?

**Pull request merged**
