### PR TITLE
[feature](csv)Supports reading CSV data using LF and CRLF as line separators.

### PR DESCRIPTION
**Pull request by hubgeter**
## Proposed changes

Supports reading CSV data using LF and CRLF as line separators.

csv file:
```
1,abc
2,def\r
3,qwe
4,hello\r
```
if you  `set keep_carriage_return = false`
you will get : 
```mysql
1   abc
2   def 
3   qwe
4   hello 
```
Here, both \r\n and \n are used as delimiters.

if you  `set keep_carriage_return = true`
you will get : 
```mysql
1   abc
2   def\r
3   qwe
4   hello\r 
```
Here only \n is used as a delimiter.

## warning
It should be noted that `set keep_carriage_return = true` is valid for tvf, but not for stream load/mysql load. This means that when you perform stream load/mysql load, crlf and lf will be automatically used as delimiters, even if you `set keep_carriage_return = true`. 

Issue Number: close #xxx

### CODE REVIEW

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run buildall

**Comment by hubgeter** [comment]
run p0

**Comment by hubgeter** [comment]
run buildall

**Comment by morningman** [comment]
run p0

**Comment by morningman** [comment]
run p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by suxiaogang223 — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Pull request merged**
