### PR TITLE
[fix](java-udf)Fix need to restart BE after replacing the jar package in java-udf

### PR DESCRIPTION
**Pull request by DongLiang-0**
## Proposed changes
Since the Nereids optimizer does not process the functionId, when creating a function, replacing the new jar package requires restarting be.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
java-udaf need add func id also in nereids.

**Comment by DongLiang-0** [comment]
> java-udaf need add func id also in nereids.

Of course, I've added

**Comment by DongLiang-0** [comment]
run buildall

**Review by zhangstar333 — APPROVED** [review]

**Review by sohardforaname — APPROVED** [review]

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by DongLiang-0** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
