### PR TITLE
[fix](load)Support load json data with default value

### LINKED ISSUE #19741: [Feature] support real default value for json stream load
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

```
#表结构
 CREATE TABLE `ods_t_test` (
 `id` bigint(30) NOT NULL,
 `order_code` varchar(30) DEFAULT NULL COMMENT '',
 `create_time` datetimev2(3) DEFAULT CURRENT_TIMESTAMP
) ENGINE=OLAP
UNIQUE KEY(`id`, `order_code`)
DISTRIBUTED BY HASH(`order_code`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);


##数据格式
{"id":"23","order_code":"23123"}


##导入
导入
curl --location-trusted -u root -T test.json -H "label:1245" -H "format:json" http://10.16.10.14:8234/api/test/ods_t_test/_stream_load
```

描述 ： create_time没有设置正确的default值，正常应该是当前时间 ，insert 是没有问题的.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarvenDuan**
# Proposed changes

Issue Number: close #19741

## Problem summary

If a column has been defined as :`key INT NULL DEFALT '100'`, when loading json data which lacks column `key`, the default value of `key` is not `100` but `NULL`.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [X] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [X] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eldenmoon** [comment]
run buildall

**Comment by DarvenDuan** [comment]
run buildall

**Comment by DarvenDuan** [comment]
> run buildall

It seems that P0 is not stable 😄

**Comment by DarvenDuan** [comment]
run P0

**Comment by DarvenDuan** [comment]
run buildall

**Comment by eldenmoon** [comment]
you should format your code `./build-support/clang-format.sh`

**Comment by DarvenDuan** [comment]
run buildall

**Review by eldenmoon — APPROVED** [review]
LGTM

**Pull request merged**
