### PR TITLE
[fix](merge-on-write) incorrect result caused by key range filter with pk

### PR DESCRIPTION
**Pull request by liaoxin01**
## Proposed changes

Issue Number: close #xxx

case：
create table test_unique_key_range_tbl (
    k1 date not null,
    k2 bigint not null,
    v1 int null,
    v2 int not null
) UNIQUE KEY(`k1`, `k2`)
DISTRIBUTED BY HASH(`k2`) BUCKETS 30
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "enable_unique_key_merge_on_write" = "true"
);
 insert into test_unique_key_range_tbl values ( '2024-02-18' ,  9019386549208004184 ,    -10 ,      5 ),
            ( '2024-02-18' ,  9208781524087970597 ,      0 ,      5 );
 select k1, v1, v2 from test_unique_key_range_tbl where k1 = '2024-02-18' order by 1, 2, 3;
+------------+------+------+
| k1         | v1   | v2   |
+------------+------+------+
| 2024-02-18 |  -10 |    5 |
+------------+------+------+
1 row in set (0.14 sec)

MySQL [test]> select k1,k2, v1, v2 from test_unique_key_range_tbl where k1 = '2024-02-18' order by 1, 2, 3;
+------------+---------------------+------+------+
| k1         | k2                  | v1   | v2   |
+------------+---------------------+------+------+
| 2024-02-18 | 9019386549208004184 |  -10 |    5 |
| 2024-02-18 | 9208781524087970597 |    0 |    5 |
+------------+---------------------+------+------+

which introduce by：#21770

solution: 
when filed is null，we encode a value greater than the KEY_NORMAL_MARKER by 1. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liaoxin01** [comment]
run buildall

**Comment by liaoxin01** [comment]
run p0

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
