### PR TITLE
[Bug](array-type) Fix array product calculate decimal type return wrong result

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

```
before:
mysql> select array_product([1.12, 3.45, 4.23]);
+----------------------------------------+
| array_product(ARRAY(1.12, 3.45, 4.23)) |
+----------------------------------------+
|         -6763245964154109952.000000000 |
+----------------------------------------+
1 row in set (0.02 sec)

after:
mysql> select array_product([1.12, 3.45, 4.23]);
+-----------------------------------------+
| array_product(ARRAY(1.12, 3.45, 4.23)) |
+-----------------------------------------+
|                            16.344720000 |
+-----------------------------------------+
1 row in set (0.02 sec)
```

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by cambyzju — DISMISSED** [review]
LGTM

**Comment by xy720** [comment]
rebase master

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.47 seconds
 load time: 568 seconds
 storage size: 17154644077 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221031141110_clickbench_pr_36615.html

**Review by cambyzju — APPROVED** [review]
LGTM

**Pull request merged**
