### PR TITLE
[Bug][Vectorized] fix core dump with HLL and some refactor of Decompressor

### LINKED ISSUE #8667: [Bug][Vectorized] core dump with HLL
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
#0  0x000000318ae328a5 in raise () from /lib64/libc.so.6
#1  0x000000318ae34085 in abort () from /lib64/libc.so.6
#2  0x0000000004c430f9 in google::DumpStackTraceAndExit () at src/utilities.cc:160
#3  0x0000000004c3870d in google::LogMessage::Fail() () at src/logging.cc:1650
#4  0x0000000004c3ac49 in google::LogMessage::SendToLog (this=0x7f57e2e11a08) at src/logging.cc:1607
#5  0x0000000004c38276 in google::LogMessage::Flush (this=0x7f57e2e11a08) at src/logging.cc:1476
#6  0x0000000004c3b2b9 in google::LogMessageFatal::~LogMessageFatal() () at src/logging.cc:2226
#7  0x00000000036f0cae in doris::vectorized::DataTypeFactory::create_data_type(doris::PColumnMeta const&) ()
    at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/data_types/data_type_factory.cpp:249
#8  0x00000000036de49f in doris::vectorized::Block::Block(doris::PBlock const&) ()
    at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/core/block.cpp:89
#9  0x00000000047faa71 in doris::vectorized::VDataStreamRecvr::SenderQueue::add_block(doris::PBlock const&, int, long, google::protobuf::Closure**) () at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/runtime/vdata_stream_recvr.cpp:124
#10 0x00000000047fe959 in doris::vectorized::VDataStreamMgr::transmit_block(doris::PTransmitDataParams const*, google::protobuf::Closure**) () at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/vec/runtime/vdata_stream_mgr.cpp:119
#11 0x0000000003214106 in doris::PInternalServiceImpl<doris::PBackendService>::transmit_block(google::protobuf::RpcController*, doris::PTransmitDataParams const*, doris::PTransmitDataResult*, google::protobuf::Closure*) ()
    at /home/disk2/pxl/dev/baidu/bdg/doris/core/be/src/service/internal_service.cpp:436
#12 0x0000000004e6265d in brpc::policy::ProcessRpcRequest (msg_base=0x10168080)
    at /home/disk2/pxl/dev/ldb_toolchain/include/c++/11/bits/unique_ptr.h:442
```

### What You Expected?

fix

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #8667

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
Could you write a test in regression-test?

**Review by dataroaring — CHANGES_REQUESTED** [review]
You'd better put case like https://github.com/apache/incubator-doris/pull/8681.

**Review by morningman — DISMISSED** [review]
LGTM
cc @dataroaring

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
