### PR TITLE
[fix](sql-block-rule) fix block rule missing issue after replay

### PR DESCRIPTION
**Pull request by morningman**
Intro from #30784

the `sqlBlockRulesSplit` field in `CommonUserProperties` is missing after
read metadata from image.

After changing meta serde to Gson, some "after work" should be done
by implementing `GsonPostProcessable` interface.

Also change 2 things:
1. Shorten the serde name of some fields.
2. When setting sql block rules for user, no longer check if the rule exist.
    Just like grant/revoke, when grant/revoke, we don't check if db or table exists.
    Decouple these 2 logics to make code simple.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
