### PR TITLE
[feature](agg) add the aggregation function 'mag_agg'

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

New aggregation function: map_agg.

This function requires two arguments: a key and a value, which are used to build a map.

```sql
select map_agg(column1, column2) from t group by column3;
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.43 seconds
 stream load tsv:          510 seconds loaded 74807831229 Bytes, about 139 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17162546629 Bytes

**Review by zclllyybb — COMMENTED** [review]
need some regression-test?

**Comment by mrhhsg** [comment]
> need some regression-test?

Yes, already added.

**Comment by mrhhsg** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 44.98 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161631307 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by jacktengg — APPROVED** [review]
LGTM

**Comment by StarkLiuyin** [comment]
LGTM

**Pull request merged**
