### PR TITLE
[Enhancement] (nereids)implement showPrivilegesCommand in nereids

### LINKED ISSUE #42769: [Enhancement] (nereids)implement showPrivilegesCommand in nereids
showPrivileges command is supported in legacy planner but not in nereids(new doris fe planner). you need implement the following showPrivileges command in nereids:
unsupportedshowPrivilegesStatement
``` SHOW PRIVILEGES                                                               ```

### PR DESCRIPTION
**Pull request by Vallishp**
### What problem does this PR solve?

 showPrivilegesCommand in nereids

Issue Number: close #42769 

Related PR: #xxx

Problem Summary:

### Check List (For Committer)

- Test 

    - [ ] Regression test already covered
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No colde files have been changed.
        - [ ] Other reason 

test_show_privileges cover this case.
2024-11-01 15:56:37.330 INFO [script-thread-6] (SuiteContext.groovy:100) - packageName: account_p0/test_show_privileges.groovy
2024-11-01 15:56:37.330 INFO [script-thread-6] (SuiteContext.groovy:111) - scriptFileName: test_show_privileges.groovy
2024-11-01 15:56:37.331 INFO [script-thread-6] (SuiteContext.groovy:95) - flowName: account_p0.test_show_privileges.test_show_privileges, flowId: account_p0/test_show_privileges.groovy#test_show_privileges
2024-11-01 15:56:37.346 INFO [suite-thread-1] (ScriptContext.groovy:100) - Run test_show_privileges in /root/doris/workspace/doris/regression-test/suites/account_p0/test_show_privileges.groovy
2024-11-01 15:56:37.352 INFO [suite-thread-1] (Config.groovy:969) - Try to create db, sql: CREATE DATABASE IF NOT EXISTS regression_test_account_p0
2024-11-01 15:56:37.374 INFO [suite-thread-1] (Config.groovy:1022) - connect to jdbc:mysql://127.0.0.1:9030/regression_test_account_p0?useLocalSessionState=true&allowLoadLocalInfile=true&verifyServerCertificate=false&useSSL=true&requireSSL=false&enabledTLSProtocols=TLSv1.2&connectTimeout=5000&socketTimeout=1800000
2024-11-01 15:56:37.399 INFO [suite-thread-1] (Suite.groovy:384) - Execute sql: show privileges
2024-11-01 15:58:03.912 INFO [suite-thread-1] (ScriptContext.groovy:120) - Run test_show_privileges in /root/doris/workspace/doris/regression-test/suites/account_p0/test_show_privileges.groovy succeed

- Behavior changed:

    - [ ] No. NO change
    - [ ] Yes. 

- Does this need documentation?

    - [ ] No. 
    - [ ] Yes. 

- Release note

    
    
    None

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by Vallishp** [comment]
run buildall

**Comment by starocean999** [comment]
please resolve conflict

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — DISMISSED** [review]
LGTM

**Review by LiBinfeng-01 — APPROVED** [review]

**Comment by Vallishp** [comment]
run buildall

**Comment by Vallishp** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
