### PR TITLE
[refactor](cluster)(step-1) remove cluster related stmt

### PR DESCRIPTION
**Pull request by morningman**
# Proposed changes

Issue Number: #19897

## Problem summary

Cluster is deprecated since 0.14. It is time to remove it.
This is the step 1: 
1. remove related stmt:
    - create
    - drop
    - alter
    - link
    - migration
 
2. No need to init default cluster when starting a new Doris cluster.
3. The information schema db's id is always 0.

I have tested the metadata upgrade from 1.2, which is compatible.
The "cluster" module in metadata image file is no longer saved,
so the new version of image file can not be read by old FE.
When reading the old image file, the "cluster" module will be ignored and skipped.

### TODO
1. Remove `default_cluster` prefix for db and user.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.23 seconds
 stream load tsv:          421 seconds loaded 74807831229 Bytes, about 169 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          58 seconds loaded 1101869774 Bytes, about 18 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230507021935_clickbench_pr_139665.html

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
