### PR TITLE
[chore](fe)correct some doc errors

### PR DESCRIPTION
**Pull request by tudouzhao**
## Proposed changes

Issue Number: close #xxx

Editlog roll at a threshold of 5w instead of 10w.
refer to Config.java

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by nimuyuhan — APPROVED** [review]
LGMT

**Comment by tudouzhao** [comment]
run buildall

**Review by vinlee19 — APPROVED** [review]
LGTM

**Review by luozenglin — DISMISSED** [review]
LGTM

**Comment by tudouzhao** [comment]
run buildall

**Comment by tudouzhao** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.8 seconds
 stream load tsv:          535 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          28.7 seconds inserted 10000000 Rows, about 348K ops/s
 storage size: 17162064113 Bytes

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request closed without merging**
