### PR TITLE
[fix](inverted index) Clear the index cache corresponding to the tabl…

### PR DESCRIPTION
**Pull request by zzzxl1993**
…e after deleting the table.

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Review by qidaye — APPROVED** [review]
LGTM

**Comment by zzzxl1993** [comment]
run buildall

**Review by qidaye — APPROVED** [review]

**Review by airborne12 — APPROVED** [review]
LGTM

**Pull request merged**
