### PR TITLE
[Fix] Fix typos in class name

### PR DESCRIPTION
**Pull request by wangbo**
## Proposed changes
1 Fix typos in class name.
2 use correct return Status.

### CODE REVIEW

**Comment by wangbo** [comment]
run buildall

**Review by BiteTheDDDDt — DISMISSED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Comment by wangbo** [comment]
run buildall

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
