### PR TITLE
[fix](tablet clone) clone add replica prefer choose the same medium

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

when chose a be for adding the new cloning replica,  if there are the same medium,  always chosen them. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by wm1581066** [comment]
any test cases?

**Review by dataroaring — DISMISSED** [review]

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
> any test cases?

add a fe ut

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
