### PR TITLE
[fix](clone) Fix the skipped link file due to the stale value

### PR DESCRIPTION
**Pull request by w41ter**
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

The clone task will compare the differences and similarities between local and downloaded files. If the md5sum of two binlog files is the same, it will set `skip_link_file` to skip the linking of that file. However, `skip_link_file` isn't reset on time. As a result, subsequent files will all be skipped because `skip_link_file` has been set, which leads to the problem that for some rowsets, the meta exists while the segment file doesn't.

The error msg:

```
[NOT_FOUND]failed to get file size /mnt/disk3/VEC_ASAN2/doris.HDD/data/900/13372467/1624966973/02000000002e1250744766e3a98c0e213d847daea65158a9_0.dat
```

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
