### PR TITLE
[fix](dynamic_partition) fix dead lock when modify dynamic partition property for olap table

### LINKED ISSUE #20387: [Bug] concurrent alter dynamic_partition.end make FE deadlock
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?
**Reproduce steps:**
1. create 3 test tables inside the same database
```
CREATE TABLE IF NOT EXISTS t1
        ( k1 date NOT NULL, k2 varchar(20) NOT NULL, k3 int sum NOT NULL )
        AGGREGATE KEY(k1,k2)
        PARTITION BY RANGE(k1) ( )
        DISTRIBUTED BY HASH(k1) BUCKETS 1
        PROPERTIES (
            "dynamic_partition.enable"="true",
            "dynamic_partition.end"="3",
            "dynamic_partition.buckets"="1",
            "dynamic_partition.start"="-3",
            "dynamic_partition.prefix"="p",
            "dynamic_partition.time_unit"="DAY",
            "dynamic_partition.create_history_partition"="true",
            "dynamic_partition.replication_allocation" = "tag.location.default: 1");
```

2. alter dynamic_partition.end for different tables at the same time. for example:
```
mysql -h127.0.0.1 -uroot -P9030 example_db -e "alter table t1 set('dynamic_partition.end'='9')" &
mysql -h127.0.0.1 -uroot -P9030 example_db -e "alter table t2 set('dynamic_partition.end'='9')" &
mysql -h127.0.0.1 -uroot -P9030 example_db -e "alter table t3 set('dynamic_partition.end'='9')" &
```

3. Then we could found mysql client will never return, and the fe.warn.log found following logs:
`2023-06-02 20:42:55,730 WARN (tablet stat mgr|32) [Table.tryWriteLock():183] Failed to try table t3's write lock. timeout 3000 MILLISECONDS. Current owner: Thread[mysql-nio-pool-4,5,main]`

**The jstack like:**
```
Found one Java-level deadlock:
=============================
"mysql-nio-pool-13":
  waiting for ownable synchronizer 0x0000000725d04fd8, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
  which is held by "mysql-nio-pool-10"
"mysql-nio-pool-10":
  waiting for ownable synchronizer 0x0000000725b55830, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
  which is held by "mysql-nio-pool-13"

Java stack information for the threads listed above:
===================================================
"mysql-nio-pool-13":
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x0000000725d04fd8> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
    at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
    at org.apache.doris.catalog.Table.readLock(Table.java:145)
    at org.apache.doris.catalog.Database.getReplicaCountWithLock(Database.java:304)
    at org.apache.doris.catalog.Database.getReplicaQuotaLeftWithLock(Database.java:318)
    at org.apache.doris.datasource.InternalCatalog.addPartition(InternalCatalog.java:1460)
    at org.apache.doris.catalog.Env.addPartition(Env.java:2762)
    at org.apache.doris.clone.DynamicPartitionScheduler.executeDynamicPartition(DynamicPartitionScheduler.java:568)
    at org.apache.doris.clone.DynamicPartitionScheduler.executeDynamicPartitionFirstTime(DynamicPartitionScheduler.java:105)
    at org.apache.doris.common.util.DynamicPartitionUtil.registerOrRemoveDynamicPartitionTable(DynamicPartitionUtil.java:482)
    at org.apache.doris.catalog.Env.modifyTableDynamicPartition(Env.java:4341)
    at org.apache.doris.alter.SchemaChangeHandler.process(SchemaChangeHandler.java:1833)
    at org.apache.doris.alter.Alter.processAlterOlapTable(Alter.java:230)
    at org.apache.doris.alter.Alter.processAlterTable(Alter.java:474)
    at org.apache.doris.catalog.Env.alterTable(Env.java:3820)
    at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:162)
    at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:2127)
    at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:724)
    at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:437)
    at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:408)
    at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:432)
    at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:579)
    at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:817)
    at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52)
    at org.apache.doris.mysql.ReadListener$$Lambda$819/659638132.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
"mysql-nio-pool-10":
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x0000000725b55830> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
    at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
    at org.apache.doris.catalog.Table.readLock(Table.java:145)
    at org.apache.doris.catalog.Database.getReplicaCountWithLock(Database.java:304)
    at org.apache.doris.catalog.Database.getReplicaQuotaLeftWithLock(Database.java:318)
    at org.apache.doris.datasource.InternalCatalog.addPartition(InternalCatalog.java:1460)
    at org.apache.doris.catalog.Env.addPartition(Env.java:2762)
    at org.apache.doris.clone.DynamicPartitionScheduler.executeDynamicPartition(DynamicPartitionScheduler.java:568)
    at org.apache.doris.clone.DynamicPartitionScheduler.executeDynamicPartitionFirstTime(DynamicPartitionScheduler.java:105)
    at org.apache.doris.common.util.DynamicPartitionUtil.registerOrRemoveDynamicPartitionTable(DynamicPartitionUtil.java:482)
    at org.apache.doris.catalog.Env.modifyTableDynamicPartition(Env.java:4341)
    at org.apache.doris.alter.SchemaChangeHandler.process(SchemaChangeHandler.java:1833)
    at org.apache.doris.alter.Alter.processAlterOlapTable(Alter.java:230)
    at org.apache.doris.alter.Alter.processAlterTable(Alter.java:474)
    at org.apache.doris.catalog.Env.alterTable(Env.java:3820)
    at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:162)
    at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:2127)
    at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:724)
    at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:437)
    at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:408)
    at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:432)
    at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:579)
    at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:817)
    at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52)
    at org.apache.doris.mysql.ReadListener$$Lambda$819/659638132.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**The reason maybe:**
1. inside function `SchemaChangeHandler.process`, we add write lock of one OLAP table;
2. inside function `Database.getReplicaCountWithLock`, we add read lock one by one for all tables inside this db;

So the deadlock is each thread owner the write lock, and try to get another table's read lock. For example:
```
         Thead1                                             Thead2
Step1: add Table1 Write Lock 
Step2:                                                Add Table2 Write Lock
Step3: try Add Table2 Read Lock
Step4:                                                try Add Table1 Read Lock
```

### What You Expected?

fix

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes

Issue Number: close #20387 

we should keep the right sequence for obtaining meta lock , to escape dead lock

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
cc @morningman @HappenLee @wangbo @cambyzju

**Review by morningman — DISMISSED** [review]
LGTm

**Comment by morningman** [comment]
This change will cause the `alter table dynamic partition` op not taking effect immediately.
But it looks good to me

**Comment by caiconghui** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
