### PR TITLE
[Enhance](catalog)add table cache in paimon jni

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

- fix get old schema after refresh paimon table
- add table cache in paimon jni

first query
```
Total:  10s375ms
OpenScannerTime:  3s623ms
```
second query
```
Total:  5s644ms
OpenScannerTime:  533.520ms
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
