### PR TITLE
[Debug](float) Add clang debug tune float accuracy

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

Add clang debug tune float accuracy

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
