### PR TITLE
[improve](execution) replace the LOG(FATAL) to throw Exception in query execute layer

### PR DESCRIPTION
**Pull request by zhangstar333**
As the LOG(FATAL) will cause BE core dump, so change it to throw exception in Execute Engine Layer.

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
