### PR TITLE
[feature](statistics)Support get row count for JDBC external table.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Support get row count for JDBC external table by executing select count(1) from table.
Return -1 when external table row count is unknown.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
