### PR TITLE
[minor](fe) optimize some log info and imports issue

### PR DESCRIPTION
**Pull request by morningman**
1. When setting `cluster_id`, give some detail instruction
2. Disallow `org.apache.hadoop.util.Lists`
3. fix when enable `bdbje_debug_mode`, NPE will be thrown when starting FE

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM.

**Pull request merged**
