### PR TITLE
[opt](Nereids) forbid one step topn with distribute as child

### PR DESCRIPTION
**Pull request by morrySnow**

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Comment by englefly** [comment]
how about forbid one phase sort in LogicalTopNToPhysicalTopN?

**Review by englefly — APPROVED** [review]

**Pull request merged**
