### PR TITLE
[fix](Nereids) cast to boolean wrong when constant folding by be

### PR DESCRIPTION
**Pull request by morrySnow**
not add case because be return wrong answer for this

select cast(2.0 as boolean); -- should return 1 not 2

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run p0

**Comment by morrySnow** [comment]
run performance

**Comment by morrySnow** [comment]
run cloud_p0

**Review by starocean999 — APPROVED** [review]

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
