### PR TITLE
[Improvement](function) opt for case when

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
## Proposed changes
```sql
mysql [tpch]>SELECT count( CASE WHEN l_commitdate = '1992-01-31' THEN '01' ELSE '' END) FROM lineitem;
+----------------------------------------------------------------------+
| count(CASE WHEN (l_commitdate = '1992-01-31') THEN '01' ELSE '' END) |
+----------------------------------------------------------------------+
|                                                            600037902 |
+----------------------------------------------------------------------+
1 row in set (9.05 sec)

mysql [tpch]>SELECT count( CASE WHEN l_commitdate = '1992-01-31' THEN '01' ELSE '' END) FROM lineitem;
+----------------------------------------------------------------------+
| count(CASE WHEN (l_commitdate = '1992-01-31') THEN '01' ELSE '' END) |
+----------------------------------------------------------------------+
|                                                            600037902 |
+----------------------------------------------------------------------+
1 row in set (3.76 sec)
```
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.76 seconds
 stream load tsv:          541 seconds loaded 74807831229 Bytes, about 131 MB/s
 stream load json:         21 seconds loaded 2358488459 Bytes, about 107 MB/s
 stream load orc:          66 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.3 seconds inserted 10000000 Rows, about 341K ops/s
 storage size: 17161985818 Bytes

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run ckbench

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run ckbench

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by zhangstar333 — APPROVED** [review]

**Pull request merged**
