### PR TITLE
[fix](cast) fix wrong result while cast string to float

### LINKED ISSUE #31518: [Bug] cast string to float get wrong result
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.5 && master

### What's Wrong?

case:
select cast("123.123" as float);

wrong result on 2.0.5 && master:
```
MySQL [(none)]> select cast("123.123" as float);
+--------------------------+
| cast('123.123' as FLOAT) |
+--------------------------+
|       123.12300109863281 |
+--------------------------+
1 row in set (0.010 sec)
```

right result:
```
MySQL [(none)]> select cast("123.123" as float);
+--------------------------+
| CAST('123.123' AS FLOAT) |
+--------------------------+
|                  123.123 |
+--------------------------+
1 row in set (0.051 sec)
```

### What You Expected?

work well

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cambyzju**
## Proposed changes

Issue Number: close https://github.com/apache/doris/issues/31518

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — DISMISSED** [review]

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by starocean999 — DISMISSED** [review]

**Comment by cambyzju** [comment]
run buildall

**Comment by cambyzju** [comment]
update regression test

**Review by xy720 — APPROVED** [review]
LGTM

**Pull request merged**
