### PR TITLE
[docs](function) add a series of date function documents

### PR DESCRIPTION
**Pull request by luozenglin**
add docs for `hours_add`, `hours_sub`, `minutes_add`, `minutes_sub`, `seconds_add`, `seconds_sub`, `years_sub`, `years_add`, `months_add`, `months_sub`, `days_add`, `days_add`, `weeks_add`, `weeks_sub` functions.

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zy-kkk — CHANGES_REQUESTED** [review]
I think if you add new function documents, you need to add the path of these documents according to the title of the file in `sidebars.json`, so that they can be displayed on the official website.

**Comment by luozenglin** [comment]
> I think if you add new function documents, you need to add the path of these documents according to the title of the file in `sidebars.json`, so that they can be displayed on the official website.

done. Thank you for reminding me.

**Review by zy-kkk — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
