### PR TITLE
[fix](catalog)Use hive-catalog-shade to solve thrift version compatibility issues

### PR DESCRIPTION
**Pull request by CalvinKirs**
`Hive 3` uses the `thrift-0.9.3` package, and `Doris` uses the `thrift-0.16.0` package. These two packages are not compatible, so we use the `hive-sahde` package to manage hive dependencies in a unified way. This jar package renames the `thrift` class , so the problem of conflict can be resolved.

## Checklist(Required)

* [x] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [x] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run P0

**Comment by CalvinKirs** [comment]
run P0 Regression

**Comment by CalvinKirs** [comment]
run COMPILE

**Comment by CalvinKirs** [comment]
run compile

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run compile

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run p0

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
