### PR TITLE
[fix](compile) fix be unused variable error when make

### PR DESCRIPTION
**Pull request by felixwluo**
## Proposed changes

Issue Number: close #xxx

image
Error when compiling master

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by felixwluo** [comment]
run buildall

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTm

**Pull request merged**
