### PR TITLE
[Fix](function) fix function `retention` lost `ARRAY`'s element type …

### LINKED ISSUE #14537: [Bug] (function) using `retention` may throw Unsupported type 'ARRAY<NULL_TYPE>'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Table is 
```
CREATE TABLE `login_event` (
`day` date NULL,
`user_id` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`day`, `user_id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`user_id`) BUCKETS 16
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2",
"disable_auto_compaction" = "false"
);
```

```
 SELECT SUM(cast(a.r[1] as int)) as active_user_num_7day FROM ( SELECT user_id, retention( day = '2022-11-01', day = '2022-11-02', day = '2022-11-04', day = '2022-11-07') as r FROM login_event WHERE (day >= '2022-11-01') AND (day <= '2022-11-21') GROUP BY user_id ) a;

**ERROR 1105 (HY000): errCode = 2, detailMessage = Unsupported type 'ARRAY<NULL_TYPE>' in '`a`.`r`'.**
```

### What You Expected?

no error

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eldenmoon**
…in `Builtin function` retType

# Proposed changes

Issue Number: close #14537

## Problem summary

```
SELECT SUM(cast(a.r[1] as int)) as active_user_num_7day FROM ( SELECT user_id, retention( day = '2022-11-01', day = '2022-11-02', day = '2022-11-04', day = '2022-11-07') as r FROM login_event WHERE (day >= '2022-11-01') AND (day <= '2022-11-21') GROUP BY user_id ) a;

**ERROR 1105 (HY000): errCode = 2, detailMessage = Unsupported type 'ARRAY<NULL_TYPE>' in '`a`.`r`'.**
```

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — CHANGES_REQUESTED** [review]
Please add a regression test.

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.34 seconds
 load time: 446 seconds
 storage size: 17172757420 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221124050106_clickbench_pr_51907.html

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
Minor fix merge it quickly.

**Pull request merged**
