### PR TITLE
[fix](show_variables) fix default value for special variables

### PR DESCRIPTION
**Pull request by Yulei-Yang**
Before:
image

After:
image

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Comment by Yulei-Yang** [comment]
run p0

**Review by xy720 — APPROVED** [review]
LGTM

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Pull request merged**
