### PR TITLE
[case](regression) Load json data with enable_simdjson_reader=false #…

### PR DESCRIPTION
**Pull request by HowardQin**
Set enable_simdjson_reader=false
and test some json data load，
at last restore enable_simdjson_reader to default value

### CODE REVIEW

**Comment by HowardQin** [comment]
run buildall

**Comment by xiaokang** [comment]
Thanks @HowardQin , #26601 has been picked by @hello-stephen in #27158 with your contribution mentioned.

**Comment by yiguolei** [comment]
So I will close this PR

**Comment by HowardQin** [comment]
OK

**Pull request closed without merging**
