### PR TITLE
[enhancement](explain) compress descriptor table explain string

### PR DESCRIPTION
**Pull request by morrySnow**
# Proposed changes

1. compress slot descriptor explain string to one row
2. remove unmaterialized tuple descriptor and slot descriptor

before this PR descriptor table explain string is like this:
```
TupleDescriptor{id=0, tbl=lineitem, byteSize=176, materialized=true}
  SlotDescriptor{id=0, col=l_shipdate, type=DATEV2}
    parent=0
    materialized=true
    byteSize=4
    byteOffset=0
    nullIndicatorByte=0
    nullIndicatorBit=-1
    nullable=false
    slotIdx=0

  SlotDescriptor{id=1, col=l_orderkey, type=BIGINT}
    parent=0
    materialized=true
    byteSize=8
    byteOffset=24
    nullIndicatorByte=0
    nullIndicatorBit=-1
    nullable=false
    slotIdx=6

  SlotDescriptor{id=2, col=l_linenumber, type=INT}
    parent=0
    materialized=true
    byteSize=4
    byteOffset=4
    nullIndicatorByte=0
    nullIndicatorBit=-1
    nullable=false
    slotIdx=1

  SlotDescriptor{id=3, col=l_partkey, type=INT}
    parent=0
    materialized=true
    byteSize=4
    byteOffset=8
    nullIndicatorByte=0
    nullIndicatorBit=-1
    nullable=false
    slotIdx=2
```

after this PR descriptor table explain string is like this:
```
TupleDescriptor{id=2, tbl=lineitem}
  SlotDescriptor{id=1, col=l_extendedprice, type=DECIMAL(15,2), nullable=false}
  SlotDescriptor{id=2, col=l_discount, type=DECIMAL(15,2), nullable=false}
  SlotDescriptor{id=5, col=l_partkey, type=INT, nullable=false}
  SlotDescriptor{id=7, col=l_suppkey, type=INT, nullable=false}
  SlotDescriptor{id=8, col=l_orderkey, type=BIGINT, nullable=false}
```

## Problem summary

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 36.56 seconds
 load time: 478 seconds
 storage size: 17179877071 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221110074907_clickbench_pr_43238.html

**Comment by cambyzju** [comment]
Could you give both string before and after change? Now the description seems only include the string before change?

**Comment by morrySnow** [comment]
> Could you give both string before and after change? Now the description seems only include the string before change?

add it

**Review by morningman — APPROVED** [review]
lgtm

**Pull request merged**
