### PR TITLE
[Opt](flexible partial update) let `SegmentWriter` do not support flexible partial update

### PR DESCRIPTION
**Pull request by bobhan1**
Considering that `SegmentWriter` will be removed in the near future, we stop to support flexible partial update on `SegmentWriter` to reduce maintenance costs

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run external

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
