### PR TITLE
[fix](cloud) Fix wrong error msg when not in cloud mode

### PR DESCRIPTION
**Pull request by zclllyybb**
## Proposed changes

Issue Number: close #xxx

fix:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: class org.apache.doris.system.SystemInfoService cannot be cast to class org.apache.doris.cloud.system.CloudSystemInfoService (org.apache.doris.system.SystemInfoService and org.apache.doris.cloud.system.CloudSystemInfoService are in unnamed module of loader 'app')
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zclllyybb** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by wangbo — DISMISSED** [review]
LGTM

**Review by gavinchou — APPROVED** [review]

**Comment by deardeng** [comment]
OlapScanNode.java 同样有一处漏了这个判断，方便的话可以帮一起修下

**Comment by zclllyybb** [comment]
> OlapScanNode.java 同样有一处漏了这个判断，方便的话可以帮一起修下

done

**Comment by zclllyybb** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
