### PR TITLE
[bugfix](jdbc catalog)fix catalog connections not released 

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close 

refer to https://github.com/alibaba/druid/wiki/%E8%BF%9E%E6%8E%A5%E6%B3%84%E6%BC%8F%E7%9B%91%E6%B5%8B

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
run buildall

**Comment by liugddx** [comment]
#27263

**Review by morningman — COMMENTED** [review]
Why adding this, this may impact the performance

**Comment by liugddx** [comment]
> Why adding this, this may impact the performance

Yes, a user wants to set up this test, so the connection pool configuration needs to be provided to the user, should we put the connection pool configuration into the catalog properties?

**Comment by liugddx** [comment]
#28300

**Pull request closed without merging**
