### PR TITLE
[fix](Nereids): NullSafeEqual should be in HashJoinCondition

### PR DESCRIPTION
**Pull request by jackwener**
## Proposed changes

Originally, we just put `EqualTo` in `HashJoinCondition`, we also need to allow `NullSafeEqual`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by XieJiann** [comment]
Maybe some test to check correctness is necessary

**Review by keanji-x — APPROVED** [review]

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by jackwener** [comment]
run buildall

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
