### PR TITLE
[fix](compatibility) type toSql should return lowercase string (#38012)

### PR DESCRIPTION
**Pull request by morrySnow**
pick from master #38012

revert #25951

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run beut

**Pull request merged**
