### PR TITLE
[fix](bitmap) fix wrong result of bitmap intersect functions

### LINKED ISSUE #22476: [Bug] (query) select count 和 intersect_count一起查询有bug，返回结果0
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

branch-1.2-lts

### What's Wrong?

CREATE TABLE test1 (
dt1 date NOT NULL,
dt2 date NOT NULL ,
id varchar(256) NULL,
type smallint(6) MAX NULL,
id_bitmap bitmap BITMAP_UNION NULL
) ENGINE=OLAP
AGGREGATE KEY(dt1, dt2, id)
PARTITION BY RANGE(dt1)
(PARTITION p20230725 VALUES [('2023-07-25'), ('2023-07-26')))
DISTRIBUTED BY HASH(dt1, dt2) BUCKETS 15;

insert into test1
select
str_to_date('2023-07-25','%Y-%m-%d') as dt1,
str_to_date('2023-07-25','%Y-%m-%d') as dt2,
'aaaaaaaaaa' as id,
1 as type,
BITMAP_HASH64('aaaaaaaaaa') as id_bitmap

select count(distinct if(type=1, id,null)) as count1,
intersect_count(id_bitmap, type, 1) as count2_bitmap from test1;

+--------+---------------+
| count1 | count2_bitmap |
+--------+---------------+
|      1 |             0 |
+--------+---------------+
1 row in set (0.02 sec)

### What You Expected?

return result both 1

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jacktengg**
## Proposed changes

Issue Number: close #22476

Agg result of bitmap `intersect_count`, `orthogonal_bitmap_intersect` and `orthogonal_bitmap_intersect_count` should set `first_init` to false after merging.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jacktengg** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.38 seconds
 stream load tsv:          516 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         30 seconds loaded 2358488459 Bytes, about 74 MB/s
 stream load orc:          70 seconds loaded 1101869774 Bytes, about 15 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162066981 Bytes

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by jacktengg** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by caiconghui — APPROVED** [review]
LGTM

**Pull request merged**
