### PR TITLE
[case](regression) test invalid jsonpaths

### PR DESCRIPTION
**Pull request by HowardQin**
streamload json file with invalid jsonpaths property

### CODE REVIEW

**Comment by HowardQin** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by HowardQin** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
