### PR TITLE
[enhancement](merge-on-write) update publish/streamload/compaction co…

### PR DESCRIPTION
**Pull request by zhannngchen**
…nfigs for MoW table

## Proposed changes

Issue Number: close #xxx

update configs to reduce possibility of publish timeout

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
