### PR TITLE
[fix](auth)Fix no priv to insert to mysql catalog

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

fix user can not insert to mysql catalog even if he has load permission

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
Need to modify for Nereids too

**Review by morningman — APPROVED** [review]
LGTM

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
