### PR TITLE
[fix](array) fix add_array_null_value for inverted index_builder 

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
in index_builder.cpp we should also handle function add_array_null which happend in alter statement
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Review by airborne12 — DISMISSED** [review]
LGTM

**Comment by amorynan** [comment]
run cloud_p0

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Review by airborne12 — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run p0

**Pull request merged**
