### PR TITLE
[opt](Nereids) update join stats derive

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes
in hash join condition, some equals are trustable, some are not. 
an equal is trustable if one side is almost unique, like primary key. for such equal condition we could estimate more accurate.
the problem is in rewriten q20, the are 2 equal condition, one is trustable, another is not. But we treat both of them as trustable.

Test result:
on tpch100, from 2.2 sec to 0.44 sec
no impact on tpch other queries
no performance impact on tpcds queries

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by yiguolei** [comment]
wow

**Comment by englefly** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
please add more detail about this PR in commit msg

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
