### PR TITLE
[docs](workload-group) Modify workload group docs

### PR DESCRIPTION
**Pull request by yongjinhou**
## Proposed changes

Issue Number: close #xxx

Modify workload group docs.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yongjinhou** [comment]
run buildall

**Comment by yongjinhou** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
