### PR TITLE
[bugfix](iceberg)Fixed random core with writing iceberg partitioned table

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Use local variables instead of member variables.

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Review by kaka11chen — APPROVED** [review]
LGTM

**Pull request merged**
