### PR TITLE
[fix](mtmv)fix getIdToItem cause ConcurrentModificationException

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

- Under normal circumstances, obtaining and operating the partition data of OLAP requires maintaining a read lock throughout the entire process. However, some operations of MTMV are time-consuming, so the method of copying a partition data is adopted. Only the read lock is maintained when obtaining the partition, and subsequent operations such as traversal use the replicated data
- Add read lock for some read operations of MTMV
## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run feut

**Review by morrySnow — APPROVED** [review]

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
