### PR TITLE
[refactor](mysql compatibility) An abstract class for all databases created for mysql compatibility

### PR DESCRIPTION
**Pull request by zhiqiang-hhhh**
## Proposed changes

Better code structure for mysql compatibility databases.

## Further comments
InfoSchemaDb and MysqlDb will implement MysqlCompatibleDatabase to inherit some general functionality.

### CODE REVIEW

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by yiguolei** [comment]
run buildall

**Review by xinyiZzz — DISMISSED** [review]
LGTM

**Comment by zhiqiang-hhhh** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Pull request merged**
