### PR TITLE
[FIX](regresstest) fix local tvf for doris cluter mode which here may not has fe log in …

### PR DESCRIPTION
**Pull request by amorynan**
…node

## Proposed changes

Issue Number: close #xxx
fix local tvf for doris cluter mode which here may not has fe log in node

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run p0

**Comment by amorynan** [comment]
run buildall

**Review by Xiaoccer — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
