### PR TITLE
[fix](decimalv3) fix result error when cast a round decimalv3 to double

### PR DESCRIPTION
**Pull request by dujl**
## Proposed changes

Issue Number: close #xxx

in round function,  when the src data is decimalv3 and the scale parameter is large than src data's scale, the round result  scale will be set to source data's scale, but it use scale parameter to create the result column.  This will result in the round result is wrong.

```
CREATE TABLE `tb_round_decimal` (
          `id` int NOT NULL COMMENT '',
          `d1` decimalv3(9, 4) NULL COMMENT '',
          `d2` decimalv3(27, 4)  NULL DEFAULT "0" ,
          `d3` decimalv3(38, 4)  NULL
        ) ENGINE=OLAP
        UNIQUE KEY(`id`)
        DISTRIBUTED BY HASH(`id`) BUCKETS 10
        PROPERTIES (
        "replication_allocation" = "tag.location.default: 1"
        ); 


insert into tb_round_decimal values (1, 123.56789, 234.67895, 345.78956); 
insert into tb_round_decimal values (2, 123.56789, 234.67895, 345.78956); 

select cast(round(sum(d1), 6) as double), cast(round(sum(d2), 6) as double), cast(round(sum(d3), 6) as double) from tb_round_decimal ;
```

before:

```
2.471356	  4.693578	6.91579
```

after:
```
247.1356	469.3578	691.579
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Gabriel39 — DISMISSED** [review]
LGTM

**Comment by dujl** [comment]
run buildall

**Comment by dujl** [comment]
run p0

**Comment by dujl** [comment]
run buildall

**Comment by dujl** [comment]
run p0

**Comment by dujl** [comment]
run p0

**Comment by dujl** [comment]
run buildall

**Comment by dujl** [comment]
run p0

**Comment by dujl** [comment]
run p0

**Comment by dujl** [comment]
run buildall

**Comment by dujl** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
