### PR TITLE
[enhancement](schema) Add schema consistency check when add partition

### PR DESCRIPTION
**Pull request by luwei16**
## Proposed changes

Issue Number: close #xxx

When adding partition, add schema consistency check to reduce the possibility of inconsistency between FE and BE schema.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Review by morningman — COMMENTED** [review]
Can it be covered by case?

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by luwei16** [comment]
> Can it be covered by case?

Existing regression cases can partially cover it, but the code with meta_changed = true cannot be covered because this is an abnormal scenario.

**Review by ByteYue — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
