### PR TITLE
[refactor](catalog) set "use_meta_cache" default to true

### PR DESCRIPTION
**Pull request by morningman**
This is PR #33610 introduce a new feature of `use_meta_cache=true`.
Now I will set this property default to true.
For all newly created catalog, is this property is not specified, it will be true.
For all previously created catalog, this property is still false.

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]
LGTM

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Pull request merged**
