### PR TITLE
[fix](regression) fix txn_insert case

### PR DESCRIPTION
**Pull request by mymeiyi**
## Proposed changes

The delete predicate on mow table is implementated in insert, so in txn insert, it is an insert rather than delete operation, the commit order is changed, so the result is changed.

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
