### PR TITLE
[Enhance](regression)Do path creation ahead of time for case test_export_external_table

### PR DESCRIPTION
**Pull request by zhangguoqiang666**
## Proposed changes

Issue Number: close #xxx

Do path creation ahead of time for case test_export_external_table

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by zgxme — APPROVED** [review]

**Review by BePPPower — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
