### PR TITLE
[fix](cooldown)Fix bug for storage policy in dynamic partition

### LINKED ISSUE #17712: [Bug](cooldown)Fix bug for storage policy in dynamic partition
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.3

### What's Wrong?

Fix bug for storage policy in dynamic partition

### What You Expected?

Fix bug for storage policy in dynamic partition

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pengxiangyu**
# Proposed changes

Issue Number: close #17712

## Problem summary

Fix bug for storage policy in dynamic partition, change stroage policy if partition has this property.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pengxiangyu** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 34.12 seconds
 stream load tsv:          472 seconds loaded 74807831229 Bytes, about 151 MB/s
 stream load json:         41 seconds loaded 2358488459 Bytes, about 54 MB/s
 stream load orc:          76 seconds loaded 1101869774 Bytes, about 13 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230310101937_clickbench_pr_112220.html

**Comment by pengxiangyu** [comment]
run compile

**Comment by pengxiangyu** [comment]
run p0

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
