### PR TITLE
[Branch2.0](Export) add show export regression testes

### PR DESCRIPTION
**Pull request by BePPPower**
## Proposed changes

Issue Number: close #xxx

backport: #27140

and fix the revert: #27160

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run buildall

**Comment by hello-stephen** [comment]
please rebase the latest branch-2.0 to trigger p0 correctly

**Comment by BePPPower** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Pull request merged**
