### PR TITLE
[case](paimon/iceberg)move cases from p2 to p0

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

move cases from p2 to p0

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Comment by wuwenchi** [comment]
run feut

**Comment by wuwenchi** [comment]
run buildall

**Comment by morningman** [comment]
run buildall

**Comment by wuwenchi** [comment]
run p0

**Comment by wuwenchi** [comment]
run external

**Review by morningman — APPROVED** [review]
LGTM

**Review by zddr — APPROVED** [review]

**Review by AshinGau — APPROVED** [review]

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
