### PR TITLE
[fix](mtmv) Fix show mtmv statement rise wrong exception for right statement

### LINKED ISSUE #15881: [Bug] Show mtmv statements rise wrong exception
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?
execute sql `show mtmv task from db1 on table1;`

image

### What You Expected?
This is a right statement so it will return right result with no any exceptions

### How to Reproduce?

show mtmv task from db1 on table1;

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SaintBacchus**
# Proposed changes

Issue Number: close #15881

## Problem summary
Wrong exception raise in the right  show mtmv statement.

Describe your changes.

Add a null check in the analyze

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [x] Yes
    - [ ] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.84 seconds
 load time: 491 seconds
 storage size: 17122680832 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230112185421_clickbench_pr_79145.html

**Comment by stalary** [comment]
I don't  understand. What problem is this supposed to solve?

**Comment by SaintBacchus** [comment]
@stalary `show mtmv task from db1 on t1` is a right statement. 
But now it rise exceptions since `mvName.getDb()` is null. 
It should rise exception in this statement `show mtmv task from db1 on db2.t1`

**Review by adonis0147 — APPROVED** [review]
LGTM

**Pull request merged**
