### PR TITLE
[Improvement](regression-test) generate user token by configured user and password rather than hard cord

### PR DESCRIPTION
**Pull request by Yulei-Yang**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yulei-Yang** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Review by yuxuan-luo — APPROVED** [review]
LGTM

**Comment by Yulei-Yang** [comment]
rerun p0

**Comment by Yulei-Yang** [comment]
rerun pipelineX_p0

**Comment by Yulei-Yang** [comment]
run pipelinex_p0

**Comment by shuke987** [comment]
run buildall

**Pull request merged**
