### PR TITLE
[enhancement](compaction) optimize the cpu consumption of the compaction task producer thread

### PR DESCRIPTION
**Pull request by luwei16**

### CODE REVIEW

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by zclllyybb** [comment]
改了config默认值，记得提文档pr

**Comment by luwei16** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run cloud_p0

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by luwei16** [comment]
run cloud_p0

**Review by Yukang-Lian — APPROVED** [review]

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by luwei16** [comment]
run buildall

**Comment by luwei16** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by luwei16** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
