### PR TITLE
[Enhancement][Materialized-View] support unique key materialized view

### LINKED ISSUE #10608: [Enhancement][Materialized-View] support unique key materialized view
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

make `uniq/agg table`  create mv have same `table type` with base table.
forbid `group by` on `agg base table`.

```sql
create table u_table(
	k1 int null,
	k2 int null,
	k3 bigint null,
	k4 bigint null
)
unique key (k1,k2,k3)
distributed BY hash(k1) buckets 3
properties("replication_num" = "1");

create materialized view k123 as select k1,k3,k2,k4 from u_table;

MySQL [test]> desc u_table all;
+-----------+---------------+-------+--------+------+-------+---------+---------+---------+
| IndexName | IndexKeysType | Field | Type   | Null | Key   | Default | Extra   | Visible |
+-----------+---------------+-------+--------+------+-------+---------+---------+---------+
| u_table   | UNIQUE_KEYS   | k1    | INT    | Yes  | true  | NULL    |         | true    |
|           |               | k2    | INT    | Yes  | true  | NULL    |         | true    |
|           |               | k3    | BIGINT | Yes  | true  | NULL    |         | true    |
|           |               | k4    | BIGINT | Yes  | false | NULL    | REPLACE | true    |
|           |               |       |        |      |       |         |         |         |
| k123      | UNIQUE_KEYS   | k1    | INT    | Yes  | true  | NULL    |         | true    |
|           |               | k3    | BIGINT | Yes  | true  | NULL    |         | true    |
|           |               | k2    | INT    | Yes  | true  | NULL    |         | true    |
|           |               | k4    | BIGINT | Yes  | true  | NULL    | REPLACE | true    |
+-----------+---------------+-------+--------+------+-------+---------+---------+---------+
9 rows in set (0.006 sec)
```

```sql
create table a_table(
	k1 int null,
	k2 int null,
	k3 bigint null,
	k4 bigint sum null
)
aggregate key (k1,k2,k3)
distributed BY hash(k1) buckets 3
properties("replication_num" = "1");

create materialized view k123 as select k1,k2,k3,sum(k4) from a_table group by k1,k2,k3; // old usage
create materialized view k123 as select k1,k2,k3,k4 from a_table; // new usage
```

### Solution

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

Issue Number: close #10608

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
Please add some test cases for this.

**Comment by EmmyMiao87** [comment]
Please add unit test ~

**Comment by stalary** [comment]
`regression-test/data/rollup/test_materialized_view.out` seems to be something different?

**Comment by BiteTheDDDDt** [comment]
> 

I modified the test_materialized_view, so the result will change

**Pull request closed without merging**
