### PR TITLE
[config](cloud) Set meta_schema_value_version to 1 by default

### PR DESCRIPTION
**Pull request by gavinchou**
It should be 1 by default to be compatible with existing warehouses and  for better performance.

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
