### PR TITLE
[Enhancement](hive-writer) Write only regular fields to file in the hive-writer.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Issue Number: #31442

[Enhancement] (hive-writer) Write only regular fields to file in the hive-writer.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
