### PR TITLE
[webserver] Introduce mustache to simplify BE's website render

### PR DESCRIPTION
**Pull request by acelyc111**
cpp-mustache is a C++ implementation of a Mustache template engine
with support for RapidJSON, and in order to simplify RapidJSON object
building, we introduce class EasyJson from Apache Kudu.

### CODE REVIEW

**Comment by acelyc111** [comment]
easy_json.{h,.cc} and easy_json-test.cpp are copied from Kudu repository, mustache.{h, cc} are copied from cpp-mustache repository.
Now BE's web site looks like:
image

**Review by morningman — COMMENTED** [review]
Could you help to comment out the `logs/` entry? which is not implemented yet.

**Comment by acelyc111** [comment]
> Could you help to comment out the `logs/` entry? which is not implemented yet.

@morningman I've updated to disable to show it on navigate bar.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
