### PR TITLE
[fix](case)Fix case failure caused by different pipeline configurations

### PR DESCRIPTION
**Pull request by zddr**
- force_olap_table_replication_num will force a change in the number of copies of the table, resulting in a case failure
- other user login to information_schema db, avoiding unauthorized access
cause by：https://github.com/apache/doris/pull/36479

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
