### PR TITLE
[feature](create table) show create table print storage medium

### PR DESCRIPTION
**Pull request by yujun777**
1.  pick: #21757
2. store table's storage medium in TableProperty, it's store as gjson, so upgrade or downgrade are ok.
3. for existing table, its storage medium is null;  for new created table,  if not special storage medium, then it's default_storage_medium;

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
