### PR TITLE
[fix](partial-update) remove unnecessary DECHEK on IndexChannel::num_rows_filtered

### PR DESCRIPTION
**Pull request by hust-hhb**
## Proposed changes
insert into select now will use pipeline mode to load data, which will make numbers of instances to do loading task, one instance corresponds to one vtablet writer, if numbers of tablet is not large, some vtablet writer may do nothing, so DECHEK on IndexChannel::num_rows_filtered should be remove, otherwise partial-update in strict mode will core in this DECHEK.
Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by hust-hhb** [comment]
this pr will make p0 pipeline core, because of dechek on IndexChannel::num_rows_filtered, 
14:50:Ch.787323 4129250 vtablet_writer.h:461] Check failed: !_tablets_filtered_rows.empty(), now we discussing the solution, close it temporarily

**Comment by hust-hhb** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
