### PR TITLE
[Enhance](Routine Load) enhance routine load get topic metadata

### PR DESCRIPTION
**Pull request by GoGoWen**
## Proposed changes

use _k_consumer->metadata(false /* for this topic */, topic, &metadata, 5000); instead of 
_k_consumer->metadata(true /* for this topic */, topic, &metadata, 5000); because _k_consumer->metadata(true ...) will get all topic's metadata, which will cause performance issue.

### CODE REVIEW

**Comment by GoGoWen** [comment]
run buildall

**Comment by GoGoWen** [comment]
run performance

**Comment by GoGoWen** [comment]
run performance

**Comment by GoGoWen** [comment]
run regression

**Comment by dataroaring** [comment]
run buildall

**Review by sollhui — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by GoGoWen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
