### PR TITLE
[fix](planner) throw NPE when insert overwrite partition(*)

### PR DESCRIPTION
**Pull request by morrySnow**

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Review by zclllyybb — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
run performance

**Comment by morrySnow** [comment]
run cloud_p0

**Comment by morrySnow** [comment]
run cloud_p0

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
