### PR TITLE
[Regression](inverted index) fix build index case for wrong debug point

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Fix wrong debug point in test case

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Comment by airborne12** [comment]
run buildall

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by zzzxl1993 — APPROVED** [review]
LGTM

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
