### PR TITLE
[fix](es-catalog) If the returned data is incorrect, it will be directly unified as the index was not found.

### PR DESCRIPTION
**Pull request by liugddx**
## Proposed changes

Issue Number: close #xxx

image

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by airborne12 — APPROVED** [review]
LGTM

**Comment by airborne12** [comment]
run buildall

**Comment by liugddx** [comment]
@qidaye PTAL

**Comment by liugddx** [comment]
@zy-kkk

**Review by qidaye — APPROVED** [review]
LGTM

**Pull request merged**
