### PR TITLE
[opt](delete) Delete job should retry for failure that is not `DELETE_INVALID_XXX`

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

fix https://github.com/apache/doris/pull/37363, delete job should fail and abort for DELETE_INVALID_CONDITION/DELETE_INVALID_PARAMETERS and retry for other failures.

branch-2.1 pick: https://github.com/apache/doris/pull/38032

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run external

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run cloud_p0

**Comment by bobhan1** [comment]
run cloud_p0

**Comment by bobhan1** [comment]
run cloud_p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
