### PR TITLE
[performance](move-memtable) only call _select_streams when necessary

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Only call `_select_streams` when creating delta writer.

Before:
image

After:
image

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by liaoxin01 — DISMISSED** [review]
LGTM

**Comment by liaoxin01** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by liaoxin01 — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
