### PR TITLE
Revert "[enhancement](k8s) Support fqdn mode for fe

### PR DESCRIPTION
**Pull request by yinzhijian**
This reverts #16315 

# Proposed changes

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by yinzhijian** [comment]
run buildall

**Comment by yinzhijian** [comment]
run feut

**Comment by yinzhijian** [comment]
run COMPILE

**Comment by yinzhijian** [comment]
run COMPILE

**Comment by yinzhijian** [comment]
run buildall

**Review by jackwener — DISMISSED** [review]

**Comment by jackwener** [comment]
run buildp0

**Comment by yinzhijian** [comment]
run buildp0

**Comment by yinzhijian** [comment]
run p0

**Comment by yinzhijian** [comment]
run buildall

**Comment by yinzhijian** [comment]
run feut

**Review by jackwener — APPROVED** [review]

**Pull request merged**
