### PR TITLE
[Calcite optimzer] support opertor of scan,  filter,  project of One QueryBlock #4223

### PR DESCRIPTION
**Pull request by wutiangan**
## Proposed changes

the predicate of filter operator only support BinaryPredicate and CompoundPredicate.
for example: set enable_calcite = true; select i from t where j > 1 and (k <= 2 or i = 5)

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update (if none of the other choices apply)
- [] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on #ISSUE, and have described the bug/feature there in detail
- [] Compiling and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] If this change need a document change, I have updated the document
- [] Any dependent changes have been merged

## Further comments
this is the first commit of calcite optimzier

### CODE REVIEW

**Comment by imay** [comment]
Hi @wutiangan 
I think support calcite in Doris is a long-time and very hard work, it will last for a long time.
Can you give more detail design about it before you commit your pull request.
Without more detail design, I don't know what's the CL is doing.

**Review by imay — CHANGES_REQUESTED** [review]
Need more detail design.

**Comment by morningman** [comment]
Hi @imay @wutiangan , I think we can open a branch for this feature, so that we can still do the review without invading the trunk code.

**Comment by imay** [comment]
> Hi @imay @wutiangan , I think we can open a branch for this feature, so that we can still do the review without invading the trunk code.

It looks good to me.

**Pull request closed without merging**
