### PR TITLE
[fix](merge cloud) Fix cloud be set be tag map

### PR DESCRIPTION
**Pull request by yujun777**
1. fix cloud backend use the same tag map;
2. cloud system info service delete static method;
3. regression stream action add 2pc;

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by gavinchou — COMMENTED** [review]
LGTM

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
