### PR TITLE
[Fix](multi-catalog) invalidates the file cache when table is non-par…

### PR DESCRIPTION
**Pull request by dutyu**
…titioned.

# Proposed changes

Invalidate the file cache when refresh a non-partitioned external hive table.

## Problem summary

Reference to `org.apache.doris.planner.external.HiveSplitter`, the file cache of `HiveMetaStoreCache` may be created even the table is a non-partitioned table, so the `RefreshTableStmt` should consider this scene and handle it.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dutyu** [comment]
run buildall

**Comment by dutyu** [comment]
run p0

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.17 seconds
 stream load tsv:          471 seconds loaded 74807831229 Bytes, about 151 MB/s
 stream load json:         26 seconds loaded 2358488459 Bytes, about 86 MB/s
 stream load orc:          75 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230319102626_clickbench_pr_116777.html

**Comment by dutyu** [comment]
run p0

**Comment by dutyu** [comment]
run p0

**Comment by morningman** [comment]
I suggest to use TTL to solve this problem, see #17947

**Comment by dutyu** [comment]
> I suggest to use TTL to solve this problem, see #17947

I think maybe TTL has not much relevance with this problem, this pr just fix the problem that `RrefreshTableStmt` does not invalidate the file cache for an non-partitioned table.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
