### PR TITLE
[Feature](partitions) Support auto partition  FE part

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
this pr have some change need notice:
1. add fe meta VERSION_125 = 1252, so can't back to return lower fe version 
2. change partition name is case sensitive.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run P1

**Comment by zhangstar333** [comment]
run p1

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by Mryange — APPROVED** [review]

**Review by Mryange — APPROVED** [review]
LGTM

**Pull request merged**
