### PR TITLE
[Fix](Job)Replaying logs should not modify the original information of the job

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Proposed changes
```
        JobExecutionConfiguration jobConfig = new JobExecutionConfiguration();
        jobConfig.setExecuteType(JobExecuteType.INSTANT);
        setJobConfig(jobConfig);
```
- Replaying logs should not modify the original information of the job
- Use the new optimizer to check whether the executed statement is legal

### CODE REVIEW

**Review by morningman — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run feut

**Comment by CalvinKirs** [comment]
run buildall

**Comment by hubgeter** [comment]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Review by hubgeter — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
