### PR TITLE
[improve](function) when drop function to remove cache package jar in BE

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
when drop function, use agent task to remove the udf-package jar which cached in BE.

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Pull request closed without merging**
