### PR TITLE
[improvement](routine-load) add routine load rows check

### PR DESCRIPTION
**Pull request by sollhui**
## Proposed changes

During the process of consuming Kafka, there may be a risk of data loss, and data verification needs to be added to investigate the cause of problems when they occur.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Comment by HHoflittlefish777** [comment]
run p1

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by kaijchen — APPROVED** [review]

**Comment by HHoflittlefish777** [comment]
run p0

**Comment by HHoflittlefish777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by HHoflittlefish777** [comment]
run clickbench

**Pull request merged**
