### PR TITLE
[optimize](string) optimize split_by_string and substring_index function 

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes
Use SIMD stringsearcher and SIMD memcmp optimze split_by_string and substring_index function.
- split_by_string function has 32%~540% up
- substring_index function has 22%~46% up

Performance difference depends on the needle size and whether the needle is constant param.  And the longer the needle, the more performance improvement

(1) split_by_string 32%~540% up
| needle | before | after |  up | comment |
|--------|--------| --------|--------|--------|
| needle size 6, constant | 6.6s image | 1.14s image |  540% | use StringSearcher  |
| needle size 6, vector | 6.62s image | 2.94s image | 120% | use SIMD memcmp |
|  needle size 1, constant | 4.08s image | 1.32s image | 200% | use StringSearcher  |
|  needle size 1, vector |  4.14s image | 3.14s image  | 32%  | use SIMD memcmp  |

(2) substring_index  22%~46% up
1. needle vector params are not supported.
2. when needle size 1, memchr is 6% faster than SIMD stringsearcher. 
3. when needle size greater than 1, stringsearcher is better than memmem.

| needle | before | after |  up | comment |
|--------|--------| --------|--------|--------|
| needle size 6, constant | 1.48s image | 1.03s image |  46% |  use StringSearcher  |
|  needle size 2, constant | 1.27s image | 1.03s image | 22% | use StringSearcher  |

Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run arm

**Comment by ZhangYu0123** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
