### PR TITLE
[fix](mtmv)mtmv support default key

### PR DESCRIPTION
**Pull request by zddr**
When no dup key is specified, it is generated by default

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Review by seawinde — APPROVED** [review]

**Pull request merged**
