### PR TITLE
[fix](case) fix txn_insert_inject_case

### PR DESCRIPTION
**Pull request by mymeiyi**

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

**Review by cjj2010 — APPROVED** [review]
LGTM

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run p0

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by zhannngchen — APPROVED** [review]
LGTM

**Pull request merged**
