### PR TITLE
[FE Code Style][sub] Adjust the severity of some check rules

### PR DESCRIPTION
**Pull request by xleoken**
## Problem Summary:

Adjust `RedundantImport`,`UnusedImports`,`EmptyStatement`,`NewlineAtEndOfFile`,`UpperEll`, `AvoidStarImport`, `MissingOverride` rules.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by leo65535** [comment]
cc @morningman, take a review when you're free, thanks.

**Comment by morrySnow** [comment]
Hi, leo65535. Great job. It's nice to see you dealing with the style of the previous code. It is important to point out that once the task start, it is best to deal with all style issues other than JavaDoc-related issues as soon as possible to minimizing the impact on code history.

**Comment by leo65535** [comment]
> Hi, leo65535. Great job. It's nice to see you dealing with the style of the previous code. It is important to point out that once the task start, it is best to deal with all style issues other than JavaDoc-related issues as soon as possible to minimizing the impact on code history.

hi, there are many rules, I think it's better to split them to several steps.

**Review by charlesy6 — APPROVED** [review]

**Review by jackwener — APPROVED** [review]
LGTM😀
cc @morningman

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morrySnow** [comment]
> > Hi, leo65535. Great job. It's nice to see you dealing with the style of the previous code. It is important to point out that once the task start, it is best to deal with all style issues other than JavaDoc-related issues as soon as possible to minimizing the impact on code history.
> 
> Hi @morrySnow, there are many rules, I think it's better to split them to several steps. And, it will be hard to review, please refer to [pull request](https://github.com/apache/incubator-doris/pull/9113), `File changes 1387`.

Yes, `split them to several steps` is necessary. We need to fix all about them asap. The first step from you is very important. After this PR merged, we need to take apart the rest of the rules to avoid two people fixing the same rule.

**Comment by leo65535** [comment]
> > > Hi, leo65535. Great job. It's nice to see you dealing with the style of the previous code. It is important to point out that once the task start, it is best to deal with all style issues other than JavaDoc-related issues as soon as possible to minimizing the impact on code history.
> > 
> > 
> > Hi @morrySnow, there are many rules, I think it's better to split them to several steps. And, it will be hard to review, please refer to [pull request](https://github.com/apache/incubator-doris/pull/9113), `File changes 1387`.
> 
> Yes, `split them to several steps` is necessary. We need to fix all about them asap. The first step from you is very important. After this PR merged, we need to take apart the rest of the rules to avoid two people fixing the same rule.

@morrySnow, thanks for the warning.

**Pull request merged**
