### PR TITLE
[enhancement][regression] remove binary data in regression test output file

### PR DESCRIPTION
**Pull request by zhannngchen**
## Proposed changes

Issue Number: close #xxx

If there are binary outputs in the output file of the regression test, it will be more difficult to deal with conflicts when cherry-picking PRs to other branches, and this PR deletes these binary outputs to make it easier to merge and cherry-pick the code in future.

### CODE REVIEW

**Review by gavinchou — DISMISSED** [review]

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
run buildall

**Comment by zhannngchen** [comment]
reopen

**Comment by zhannngchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by zhannngchen** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
