### PR TITLE
[Fix](MySqlLoad)Fixed the  MySqlLoad will create a new thread every time checkpoint is made

### PR DESCRIPTION
**Pull request by CalvinKirs**
## What Happend
image

**mysql-load-fail-record-cleaner** thread crazy increase

## Proposed changes

MySqlLoad will create a new thread every time checkpoint is made, set it's only daemon thread can be create new thread

## Test

image

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by bobhan1 — APPROVED** [review]

**Pull request merged**
