### PR TITLE
[test](fuzzy) test fuzzy in BE

### PR DESCRIPTION
**Pull request by zhangstar333**
## Proposed changes
1.  remove some not used conf: https://github.com/apache/doris-website/pull/455/files
2. add enable_set_in_bitmap_value/enable_shrink_memory for fuzzy to test.

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Comment by zhangstar333** [comment]
run buildall

**Comment by zhangstar333** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
