### PR TITLE
[regression-test](profile) add regression tests for query profile and insert profile

### PR DESCRIPTION
**Pull request by 1330571**
# Proposed changes

Issue Number: close #16540

## Problem summary
There have been no regression tests for profile 

## Describe your changes.

add 2 regression tests for insert profile and query profile

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — CHANGES_REQUESTED** [review]
please add 'show query profile' stmt.

**Comment by 1330571** [comment]
have added a test for `show query profile` stmt in `test_query_profile`.

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run all

**Review by Yukang-Lian — DISMISSED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by 1330571** [comment]
run buildall

**Comment by 1330571** [comment]
run buildall

**Comment by 1330571** [comment]
run buildall

**Comment by 1330571** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
