### PR TITLE
[Improvement](multi-catalog)support max compute complex type parse

### PR DESCRIPTION
**Pull request by wsjz**
## Proposed changes

support max compute array/map/struct type and add test case

### CODE REVIEW

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run external

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Comment by wsjz** [comment]
run buildall

**Review by morningman — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Comment by wsjz** [comment]
add fix https://github.com/apache/doris/pull/39680

**Pull request merged**
