### PR TITLE
[BugFix](Array)Fix using Array aggregate function caused be coredump

### LINKED ISSUE #10648: [Bug] using Array aggregate function caused be coredump
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```
#0  get_data (this=<optimized out>) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/common/cow.h:190
#1  get_offsets (this=<optimized out>) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/columns/column_array.h:126
#2  execute (array=..., data_type_array=0x7fc8fdc7b630, result=2, block=...) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/array/function_array_aggregation.cpp:154
#3  doris::vectorized::FunctionArrayMapped<doris::vectorized::ArrayAggregateImpl<(doris::vectorized::AggregateOperation)3>, doris::vectorized::NameArrayAverage>::execute_impl (this=<optimized out>, context=<optimized out>, block=..., arguments=..., result=2,
    input_rows_count=1) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/array/function_array_mapped.h:65
#4  0x00007fc8f3a6f4bd in execute_impl (input_rows_count=1, result=2, arguments=..., block=..., context=0x7fc8f8bdf0e8, this=0x7fc8f962a3d0) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/shared_ptr_base.h:1290
#5  doris::vectorized::PreparedFunctionImpl::execute_without_low_cardinality_columns (this=0x7fc8f962a3d0, context=0x7fc8f8bdf0e8, block=..., args=..., result=<optimized out>, input_rows_count=1, dry_run=false)
    at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:253
#6  0x00007fc8f3a70a29 in doris::vectorized::PreparedFunctionImpl::execute (this=<optimized out>, context=<optimized out>, block=..., args=..., result=<optimized out>, input_rows_count=1, dry_run=false)
    at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/functions/function.cpp:274
#7  0x00007fc8f3105d04 in doris::vectorized::IFunctionBase::execute (this=this@entry=0x7fc8fde95280, context=0x7fc8f8bdf0e8, block=..., arguments=..., result=result@entry=2, input_rows_count=1, dry_run=false)
    at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/shared_ptr_base.h:1290
#8  0x00007fc8f33c829b in doris::vectorized::VectorizedFnCall::execute (this=0x7fc8fdc96c00, context=0x7fc8fde946e0, block=0x7fc895366f80, result_column_id=0x7fc8f8bdf140)
    at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/stl_vector.h:1043
#9  0x00007fc8f33cac27 in doris::vectorized::VExprContext::execute (this=0x7fc8fde946e0, block=block@entry=0x7fc895366f80, result_column_id=result_column_id@entry=0x7fc8f8bdf140) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exprs/vexpr_context.cpp:42
#10 0x00007fc8f3097d7f in doris::vectorized::VUnionNode::get_next_const (this=this@entry=0x7fc8f9cf5680, state=state@entry=0x7fc8fde83000, block=block@entry=0x7fc8fde956d0)
    at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/stl_vector.h:1043
#11 0x00007fc8f30985f6 in doris::vectorized::VUnionNode::get_next (this=0x7fc8f9cf5680, state=0x7fc8fde83000, block=0x7fc8fde956d0, eos=0x7fc8fde86149) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/vec/exec/vunion_node.cpp:237
#12 0x00007fc8f25f9e9e in doris::PlanFragmentExecutor::get_vectorized_internal (this=this@entry=0x7fc8fde86070, block=block@entry=0x7fc8953689b8) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/unique_ptr.h:421
#13 0x00007fc8f25fe275 in doris::PlanFragmentExecutor::open_vectorized_internal (this=this@entry=0x7fc8fde86070) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:270
#14 0x00007fc8f26001af in doris::PlanFragmentExecutor::open (this=this@entry=0x7fc8fde86070) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:228
#15 0x00007fc8f25e1fe5 in doris::FragmentExecState::execute (this=0x7fc8fde86000) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/runtime/fragment_mgr.cpp:242
#16 0x00007fc8f25e6a28 in doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x7fc8f9298c40, exec_state=..., cb=...)
    at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/shared_ptr_base.h:1290
#17 0x00007fc8f25f294c in __invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__f=
    @0x7fc8fde95720: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0x7fc8f25e64a0 <doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>, __t=@0x7fc8fde95760: 0x7fc8f9298c40, __f=
    @0x7fc8fde95720: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0x7fc8f25e64a0 <doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>, __t=@0x7fc8fde95760: 0x7fc8f9298c40) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/ext/atomicity.h:109
#18 __invoke_r<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__fn=
    @0x7fc8fde95720: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0x7fc8f25e64a0 <doris::FragmentMgr::_exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:111
#19 __call<void, 0, 1, 2> (__args=<optimized out>, this=0x7fc8fde95720) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/functional:570
#20 operator()<> (this=0x7fc8fde95720) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/functional:629
#21 __invoke_impl<void, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)>&> (__f=...) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:61
#22 __invoke_r<void, std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)>&> (__fn=...) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/invoke.h:111
#23 std::_Function_handler<void (), std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:291
#24 0x00007fc8f288a66d in operator() (this=<optimized out>) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:556
#25 run (this=<optimized out>) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/util/threadpool.cpp:45
#26 doris::ThreadPool::dispatch_thread (this=0x7fc8f93cf200) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/util/threadpool.cpp:540
#27 0x00007fc8f2880d5f in operator() (this=0x7fc8f9620718) at /home/disk4/xuyang/work/baidu/bdg/doris/palo-toolchain/ldb_toolchain/include/c++/11/bits/std_function.h:556
#28 doris::Thread::supervise_thread (arg=0x7fc8f9620700) at /home/disk4/xuyang/work/baidu/bdg/doris/core/be/src/util/thread.cpp:408
#29 0x00007fc8ee1c3aa1 in start_thread () from /lib64/libpthread.so.0
#30 0x00007fc8ee4c1c4d in clone () from /lib64/libc.so.6
```

### What You Expected?

work well

### How to Reproduce?

```
set enable_vectorized_engine=true;
select array_avg([1,2,3]);
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xy720**
# Proposed changes

Issue Number: close #10648

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by qidaye** [comment]
This bug is similar to #10640

**Comment by xy720** [comment]
> This bug is similar to #10640

I think it is not the same bug.
This bug is because the `convert_to_full_column_if_const` function has never been called in advance.

But in #10640, the bug is caused by the memory space return by `convert_to_full_column_if_const` was released in advance.

**Comment by xy720** [comment]
> This bug is similar to #10640

I think it is not the same bug.
This bug is because the `convert_to_full_column_if_const` function has never been called in advance.

But in #10640, the bug is caused by the memory space return by `convert_to_full_column_if_const` was released in advance.

> > This bug is similar to #10640
> 
> I think it is not the same bug. This bug is because the `convert_to_full_column_if_const` function has never been called in advance.
> 
> But in #10640, the bug is caused by the memory space return by `convert_to_full_column_if_const` was released in advance.

Haha, but they do look like same.

**Comment by qidaye** [comment]
> > This bug is similar to #10640
> 
> I think it is not the same bug. This bug is because the `convert_to_full_column_if_const` function has never been called in advance.
> 
> But in #10640, the bug is caused by the memory space return by `convert_to_full_column_if_const` was released in advance.
> 
> > > This bug is similar to #10640
> > 
> > 
> > I think it is not the same bug. This bug is because the `convert_to_full_column_if_const` function has never been called in advance.
> > But in #10640, the bug is caused by the memory space return by `convert_to_full_column_if_const` was released in advance.
> 
> Haha, but they do look like same.

Yes. Not same bug, but similar way to fix.

**Review by adonis0147 — DISMISSED** [review]
LGTM

**Review by xy720 — COMMENTED** [review]
rebase to re-tigger regression test

**Review by yangzhg — APPROVED** [review]
LGTM

**Pull request merged**
