### PR TITLE
[fix](typo) correct the typo

### PR DESCRIPTION
**Pull request by XuJianxu**
## Proposed changes

Issue Number: close #xxx

Correct the type

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by AshinGau — APPROVED** [review]

**Comment by AshinGau** [comment]
LGTM

**Review by hello-stephen — APPROVED** [review]
LGTM

**Review by vinlee19 — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by XuJianxu** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.96 seconds
 stream load tsv:          528 seconds loaded 74807831229 Bytes, about 135 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.6 seconds inserted 10000000 Rows, about 349K ops/s
 storage size: 17162113661 Bytes

**Pull request closed without merging**
