### PR TITLE
[Fix](partial update) Fix wrongly update autoinc column in partial update

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

https://github.com/apache/doris/pull/38229 convert partial update to upsert in some situations. But when the insert stmt has missing autoinc value column, we can't do this transformation, otherwise the value in autoinc column will be wrongly overwritten with newly generated values instead of reading from old rows.

branch-2.1-pick: https://github.com/apache/doris/pull/40073

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Review by cambyzju — DISMISSED** [review]

**Comment by bobhan1** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
