### PR TITLE
[typo](docs) fix docs，characters error

### PR DESCRIPTION
**Pull request by wanghuan2054**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by wanghuan2054** [comment]
> run buildall

Can you help solve this problem ？ ”Run failed: Code Quality Analysis“

**Comment by dataroaring** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]
LGTM

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
