### PR TITLE
[fix](cluster key) support cloud mode

### PR DESCRIPTION
**Pull request by mymeiyi**
cluster key support cloud mode

### CODE REVIEW

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run cloud_p0

**Comment by mymeiyi** [comment]
run feut

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Pull request merged**
