### PR TITLE
[fix](pipeline) fix use error row desc when origin block clear

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes

```
20240326 14:56:31.548905 2901802 block.cpp:703] Check failed: d.column->use_count() == 1 (2 vs. 1)  , [col_int_undef_signed, 1], [col_date_undef_signed_not_null, 2], [col_int_undef_signed, 1], [VectorizedFnCall[ifnull](arguments=col_date_undef_signed_not_null, col_date_undef_signed_not_null,return=DateV2), 2]
*** Check failure stack trace: ***
    @     0x5565ba9e58a6  google::LogMessage::SendToLog()
    @     0x5565ba9e22f0  google::LogMessage::Flush()
    @     0x5565ba9e60e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x5565b1242035  doris::vectorized::Block::clear_column_data()
    @     0x5565aae44b41  doris::ExecNode::clear_origin_block()
    @     0x5565aae3fbca  doris::ExecNode::get_next_after_projects()
    @     0x5565b9e6e058  doris::pipeline::StatefulOperator<>::get_block()
    @     0x5565ba5dbbd4  doris::pipeline::PipelineTask::execute()
```

We should use intermediate_row_desc to clean the origin block because there are differences on the join node.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p0

**Comment by Mryange** [comment]
run buildall

**Review by Gabriel39 — APPROVED** [review]

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
