### PR TITLE
[chore] Add bvar for meta operations of BE

### PR DESCRIPTION
**Pull request by gavinchou**

### CODE REVIEW

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Review by vinlee19 — APPROVED** [review]
LGTM

**Comment by vinlee19** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by gavinchou** [comment]
run buildall

**Comment by gavinchou** [comment]
run buildall

**Pull request merged**
