### PR TITLE
[improvement](nereids) Get partition related table disable nullable field and complete agg matched pattern mv rules.

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes

**Get partition related table disable nullable field** 
If create mv def as following which use table `base_date`,  this will cause a exception with msg `Unable to find a suitable base table for partitioning`, because the  mv partition date field is nullable from the base table def.
>
>           CREATE MATERIALIZED VIEW mv_name
>                    BUILD DEFERRED REFRESH AUTO ON MANUAL
>                   partition by(`date`)
>                    DISTRIBUTED BY RANDOM BUCKETS 2
>                   PROPERTIES ('replication_num' = '1')
>                    AS
>                    SELECT * FROM base_date;

>         CREATE TABLE  base_date(
>          `user_id` LARGEINT NOT NULL COMMENT '\"用户id\"',
>         `date` DATE NULL COMMENT '\"数据灌入日期时间\"',
>          `num` SMALLINT NULL COMMENT '\"数量\"'
>        ) ENGINE=OLAP
>        DUPLICATE KEY(`user_id`, `date`, `num`)
>        COMMENT 'OLAP'
>        PARTITION BY RANGE(`date`)
>        (PARTITION p201701_1000 VALUES [('0000-01-01'), ('2017-02-01')),
>        PARTITION p201702_2000 VALUES [('2017-02-01'), ('2017-03-01')),
>        PARTITION p201703_all VALUES [('2017-03-01'), ('2017-04-01')))
>        DISTRIBUTED BY HASH(`user_id`) BUCKETS 2
>        PROPERTIES ('replication_num' = '1') ;

**Complete agg matched pattern mv rules**
`MaterializedViewFilterAggregateRule`
It supports rewrite by mv when query sql pattern like filter on aggregate.

`MaterializedViewProjectFilterAggregateRule`
It supports rewrite by mv when query sql pattern like  project on filter on aggregate

`MaterializedViewFilterProjectAggregateRule`
It supports rewrite by mv when query sql pattern like filter on project on aggregate

**Modify the regression test to make sure the result is not null, which we can check the data correctness**

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by zddr — APPROVED** [review]

**Review by morrySnow — APPROVED** [review]

**Comment by seawinde** [comment]
run pull_request

**Review by wm1581066 — APPROVED** [review]
LGTM

**Pull request merged**
