### PR TITLE
[fix](global-variable) fix bug that set default value for global variable will cause NullPointerException

### LINKED ISSUE #18002: [Bug] Set default value for global variable will cause NullPointerException
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

dev

### What's Wrong?

`set global var = DEFAULT` will cause NullPointerException:
```
mysql> set global enable_profile = DEFAULT;
ERROR 1105 (HY000): NullPointerException, msg: java.lang.NullPointerException: null
```

Related code: https://github.com/apache/doris/blob/4193884a32ba8d18e2ab9be4fcf2c4f5360b209a/fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java#L266

### What You Expected?

No exception.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gitccl**
# Proposed changes

Issue Number: close #18002

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by gitccl** [comment]
run p1

**Comment by gitccl** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 33.91 seconds
 stream load tsv:          447 seconds loaded 74807831229 Bytes, about 159 MB/s
 stream load json:         25 seconds loaded 2358488459 Bytes, about 89 MB/s
 stream load orc:          73 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230322041447_clickbench_pr_118420.html

**Comment by gitccl** [comment]
run p1

**Review by Yukang-Lian — DISMISSED** [review]
LGTM

**Comment by gitccl** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
