### PR TITLE
[improvement](garbage sweep) garbage sweep sleep for a while to reduce io

### PR DESCRIPTION
**Pull request by yujun777**
## Proposed changes

1.  sleep 1ms after garbage sweep a batch;
2.  not auto clean cache file when staring be;

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.38 seconds
 stream load tsv:          514 seconds loaded 74807831229 Bytes, about 138 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.6 seconds inserted 10000000 Rows, about 337K ops/s
 storage size: 17162073643 Bytes

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by ByteYue — APPROVED** [review]

**Review by Yukang-Lian — APPROVED** [review]
LGTM

**Pull request merged**
