### PR TITLE
[fix](group commit) Pick some group commit pr

### PR DESCRIPTION
**Pull request by mymeiyi**
Pick https://github.com/apache/doris/pull/38292, https://github.com/apache/doris/pull/34021, https://github.com/apache/doris/pull/38228, some modify of https://github.com/apache/doris/pull/37260, some modify of https://github.com/apache/doris/pull/37595

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run buildall

**Comment by mymeiyi** [comment]
run feut

**Comment by mymeiyi** [comment]
run fe_ut

**Pull request merged**
