### PR TITLE
[fix](dynamic) Fix error reporting when dynamic partition properties contain incorrect attributes

### PR DESCRIPTION
**Pull request by Zhiyu-h**
## Proposed changes

Issue Number: close #xxx

Fix error reporting when dynamic partition properties contain incorrect attributes

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Zhiyu-h** [comment]
run buildall

**Review by Hastyshell — APPROVED** [review]
LGTM

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by Hastyshell — APPROVED** [review]
LGTM

**Review by dataroaring — CHANGES_REQUESTED** [review]
What if storage_policy is not empty?

**Comment by dataroaring** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run_buildall

**Comment by Zhiyu-h** [comment]
run_buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by Zhiyu-h** [comment]
run  buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by yiguolei** [comment]
run buildall

**Comment by xiaokang** [comment]
@Zhiyu-h can you submit a pr for branch-2.0

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]
lgtm

**Pull request merged**
