### PR TITLE
[enhance](cooldown) add new cooldown cases

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes

Issue Number: close #xxx
Add new cold heat separation cases.
1. create one table with no partition, using cooldown policy to test if the data is cooldown correctly
2. create one table each tablet with 3 replica using cooldown policy to test if only one replica's data would be uploaded and if all the procedures are handled correctly
3. create table with 2 partition each with different cooldown policy
4. create table to test alter policy
## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ByteYue** [comment]
run buildall

**Comment by dataroaring** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by ByteYue** [comment]
runbuild all

**Comment by ByteYue** [comment]
runbuild all

**Comment by zhangguoqiang666** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
