### PR TITLE
[Fix](upgrade) Fix fields not handled correctly during upgrade and downgrade

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

2.1 version is #36691

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Comment by Yukang-Lian** [comment]
run p0

**Comment by Yukang-Lian** [comment]
run external

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
