### PR TITLE
[Fix](Nereids) fix fold const be return type

### PR DESCRIPTION
**Pull request by LiBinfeng-01**
remove windowframe in window expression to avoid folding constant on be

### CODE REVIEW

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run buildall

**Comment by LiBinfeng-01** [comment]
run p0

**Comment by LiBinfeng-01** [comment]
run p0

**Review by starocean999 — APPROVED** [review]

**Review by englefly — APPROVED** [review]

**Pull request merged**
