### PR TITLE
[Migrate-Test](multi-catalog) Migrate p2 tests from p2 to p0.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

[Migrate-Test] (multi-catalog) Migrate p2 tests from p2 to p0.
- Migrate p2 tests from p2 to p0.
- Set health check of hms docker to 10s(interval) * 120(retries).
- Remove duplicated tables in `create_preinstalled_table.hql` by adding new scripts.

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by BePPPower — APPROVED** [review]

**Pull request merged**
