### PR TITLE
[fix](jdbc scan) Remove the `conjuncts.remove` call in JdbcScan

### PR DESCRIPTION
**Pull request by zy-kkk**
In #37565, due to the change in the calling order of finalize, the final generated Plan will be missing the PREDICATES that have been pushed down in Jdbc. Although this behavior is correct, before perfectly handling the push down of various PREDICATES, we need to keep all conjuncts to ensure that we can still filter data normally when the data returned by Jdbc is a superset.

### CODE REVIEW

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — DISMISSED** [review]
LGTM

**Review by kaka11chen — DISMISSED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Review by wuwenchi — APPROVED** [review]
LGTM

**Review by morningman — APPROVED** [review]

**Pull request merged**
