### PR TITLE
[feature](system) support decommission disk for doris

### PR DESCRIPTION
**Pull request by xy720**
## Proposed changes

This commit add two statements:

1. decommission

```
alter system decommission disk "/home/disk1/palo.HDD" on backend "127.0.0.1:8911";
```

3.cancel decommission

```
cancel decommission disk "/home/disk1/palo.HDD" on backend "127.0.0.1:8911";
```

The logic is same with decommission backend.

We only mark the root path as decommissioned in Fe meta, and let the Fe TabletScheduler do the rest jobs.

**1、For Repair Process:**

1、The tablet on the decommissioned disk will be treated as unstable by TabletChecker.

2、The TabletChecker will add the unstable tablets into queue of TabletScheduler.

3、TabletScheduler will schedule the tablet, and send tasks to Backends to relocate the tablet.

  1)、If there is a new backend without related replica for this tablet

       i. Send replica_missing(for tablet that only have one replica)/replica_relocating task for this tablet,  
          the dest node is the new backend, and create a new replica on the new backend.

       ii. Send redundant task for this tablet, and remove the replica on decommissioned disk.

  2)、 If there is no new backend for this tablet, but it has more than one replica.

       i. Send force_redundant task for this tablet, and remove the replica on decommissioned disk.

       ii. Send replica_missing task for this tablet, the dest node is the same backend, and create a new replica 
          on the same backend on other disk.

  3)、If there is no new backend for this tablet, and this tablet only have one replica.

       i. I haven't figured out how to do for this situation.

4、The tablet is relocated.

**2、For Balance Process:**

We exclude the decommissioned disk from the balance system, so that the decommissioned disk will not be treated as low path and block the balance.

Furthermore, to show the progress of the decommission, TabletNum and SystemDecommission column have been added to the `show proc '/backends/{backendId}'` results.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
run buildall

**Comment by xy720** [comment]
Currently not support for colocate tablet.

**Comment by yongjinhou** [comment]
run p0

**Comment by yongjinhou** [comment]
run p1

**Comment by xy720** [comment]
run build all

**Comment by xy720** [comment]
run buildall

**Review by chenlinzhong — APPROVED** [review]
LGTM

**Comment by xy720** [comment]
run buildall

**Pull request closed without merging**
