### PR TITLE
[bug](json)Fix the problem of be down caused by json path ending with \

### PR DESCRIPTION
**Pull request by LemonLiTree**
## Proposed changes

Issue Number: close #xxx

pict https://github.com/apache/doris/pull/28180 to branch-2.0

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Comment by LemonLiTree** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
