### PR TITLE
[fix](Nereids) fix ShowProcedureStatusCommand sendResultSet

### PR DESCRIPTION
**Pull request by zy-kkk**
## Proposed changes

Issue Number: close #xxx

Show Command should return an empty Set even if the result is empty

Fix compatible problem with mysql workbench

before repair
```
Doris > SHOW PROCEDURE STATUS WHERE Db='test';
Query OK, 0 rows affected (0.00 sec)
```

After repair:
```
Doris > SHOW PROCEDURE STATUS WHERE Db='test';
Empty set (0.11 sec)
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by zy-kkk** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
@Vallishp PTAL

**Review by Vallishp — APPROVED** [review]
LGTM

**Comment by zy-kkk** [comment]
run buildall

**Pull request merged**
