### PR TITLE
[Fix](job)Fix CAS competition failure leading to message publishing failure.

### PR DESCRIPTION
**Pull request by CalvinKirs**
### What problem does this PR solve?

 **tryPublish** returns false in case of CAS competition failure or when the queue is full. Therefore, we need to first check if there is enough capacity and then use the **publish** method for serial publishing.

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason 

- Behavior changed:
    - [ ] No.
    - [ ] Yes. 

- Does this need documentation?
    - [ ] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by CalvinKirs** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
run buildall

**Review by zddr — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
run feut

**Comment by CalvinKirs** [comment]
run buildall

**Comment by CalvinKirs** [comment]
run buildall

**Review by JNSimba — APPROVED** [review]

**Pull request merged**
