### PR TITLE
[bugfix] issue-6390 , wrong result in query view with an added null column

### LINKED ISSUE #6390: [Bug] wrong result in query view with an added null column
**Describe the bug**
Create a view, add an extra column and assign it to null. 
query the view with added column 'is not null' and 'order by'
if 'is not null' and 'order by'  exist at the same time,
**'is not null' will be ignore.**

**To Reproduce**

1. CREATE TABLE test

````` 
CREATE TABLE test
(
    k1 varchar(8) NULL,
    k2 int NULL
)
AGGREGATE KEY(k1,k2)
DISTRIBUTED BY HASH(k1) BUCKETS 5
PROPERTIES("replication_num" = "1");
````` 

2.insert data
````` 
insert into test select 'a' as k1,1 as k2;
insert into test select 'a' as k1,2 as k2;
insert into test select 'b' as k1,3 as k2;
insert into test select 'b' as k1,4 as k2;
`````  

3. create view and and a null column
`````  
create view test_view AS SELECT *,null as add_column  FROM test;

select * from test_view;
+------+------+------------+
| k1   | k2   | add_column |
+------+------+------------+
| a    |    1 | NULL       |
| a    |    2 | NULL       |
| b    |    3 | NULL       |
| b    |    4 | NULL       |
+------+------+------------+
4 rows in set (0.01 sec)
`````  

4. reproduce 
`````  
--【it is right】
select * from test_view where add_column is not null;
Empty set (0.01 sec)

--【after add order by，error！】
select * from test_view where add_column is not null order by k1;
+------+------+------------+
| k1   | k2   | add_column |
+------+------+------------+
| a    |    1 | NULL       |
| a    |    2 | NULL       |
| b    |    4 | NULL       |
| b    |    3 | NULL       |
+------+------+------------+
4 rows in set (0.01 sec)

--【after add order by，error！】
select * from test_view where add_column is not null order by k2;
+------+------+------------+
| k1   | k2   | add_column |
+------+------+------------+
| a    |    1 | NULL       |
| a    |    2 | NULL       |
| b    |    3 | NULL       |
| b    |    4 | NULL       |
+------+------+------------+
4 rows in set (0.01 sec)
--【after add order by，error！】
select * from test_view where add_column is not null order by add_column;
+------+------+------------+
| k1   | k2   | add_column |
+------+------+------------+
| b    |    4 | NULL       |
| a    |    2 | NULL       |
| b    |    3 | NULL       |
| a    |    1 | NULL       |
+------+------+------------+
4 rows in set (0.02 sec)
`````

### PR DESCRIPTION
**Pull request by zbtzbtzbt**
## Proposed changes
Fix fe/fe-core/.../analysis  isNullpredicate.java ,add a getResultValue function to fix issue-6390

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)
- [ ] Optimization. Including functional usability improvements and performance improvements.
- [ ] Dependency. Such as changes related to third-party components.
- [ ] Other.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have created an issue on (Fix #6390 ) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — COMMENTED** [review]
Thanks for your PR. Could you please add unit test for this case?
You can refer to the QueryPlanTest.java.

Although we can not insert real data in unit test, and I think this case can be checked in query plan.

**Comment by zbtzbtzbt** [comment]
hi morningman～ I add some unit test in QueryPlanTest.java. the bug need createView and orderby，so I add a function to create view，use LOG.info show explainString，and use assertTrue to test。

**Comment by zbtzbtzbt** [comment]
@morningman i solve the conflict,please try again.

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
