### PR TITLE
[Fix](multi-catalog)Fix the issue of not initializing the writer caused by refactoring and add hive writing regression tests.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

Issue Number: #31442

- Fix the issue of not initializing the writer caused by refactoring code in #31716.
- Fix reference lifetime issue of `TParquetVersion::type parquet_version` in `VParquetTransformer ` when using temp object.
- Add hive writing regression tests. 

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run buildall

**Comment by kaka11chen** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by wuwenchi — APPROVED** [review]

**Pull request merged**
