### PR TITLE
[fix](scan) _insert_data_normal should catch exception when BlockReader::_unique_key_next_block

### PR DESCRIPTION
**Pull request by xingyingone**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by xingyingone** [comment]
https://github.com/apache/doris/pull/29426

**Comment by xingyingone** [comment]
run  buildall

**Review by yiguolei — APPROVED** [review]

**Comment by yiguolei** [comment]
run buildall

**Comment by xingyingone** [comment]
run  buildall

**Comment by xiaokang** [comment]
run buildall

**Comment by xingyingone** [comment]
run   buildall

**Comment by xingyingone** [comment]
run beut

**Pull request merged**
