### PR TITLE
[feat](binlog) Add replace table binlog

### LINKED ISSUE #43436: [Enhancement] add replace table support for ccr
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Adding support of replace table for ccr.

### Solution

If source table is managed by ccr job, we should issue the sql to downstream.
Otherwise, we should do a fullsync or partial sync.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by w41ter**
### What problem does this PR solve?

Issue Number: close #43436

Related PR: https://github.com/selectdb/ccr-syncer/pull/245

Problem Summary:

### Release note

None

### Check List (For Author)

- Test 
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
        - [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [x] Other reason 

Add cases in ccr-syncer

- Behavior changed:
    - [x] No.
    - [ ] Yes. 

- Does this need documentation?
    - [x] No.
    - [ ] Yes. 

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run feut

**Comment by w41ter** [comment]
run cloudut

**Comment by w41ter** [comment]
run performance

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Comment by w41ter** [comment]
run buildall

**Review by Yukang-Lian — APPROVED** [review]

**Pull request merged**
