### PR TITLE
[regression](s3) add default conf for s3 releated cases

### PR DESCRIPTION
**Pull request by hello-stephen**
## Proposed changes

replace COS with OSS in the TeamCity pipeline to improve stability

### CODE REVIEW

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Comment by hello-stephen** [comment]
run buildall

**Review by shuke987 — APPROVED** [review]
LGTM

**Review by swjtu-zhanglei — APPROVED** [review]

**Review by zhangstar333 — APPROVED** [review]

**Review by Thearas — COMMENTED** [review]
LGTM

**Pull request merged**
