### PR TITLE
[fix](map_agg) lost scale information for decimal type

### LINKED ISSUE #23775: [Bug] Some aggregation functions such as map_agg may drop the decimal point
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

SHA-1: 97eb2b91726ca24622c20c20fb1ab5b9e1c85559

### What's Wrong?

   CREATE TABLE `test_array_agg_decimal` (
        `id` int(11) NOT NULL,
        `label_name` varchar(32) default null,
        `value_field` string default null,
        `age` int(11) default null,
         `o_totalprice` DECIMAL(15, 2) default NULL
    ) ENGINE=OLAP
    DUPLICATE KEY(`id`)
    COMMENT 'OLAP'
    DISTRIBUTED BY HASH(`id`) BUCKETS 1
    PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "storage_format" = "V2",
    "light_schema_change" = "true",
    "disable_auto_compaction" = "false",
    "enable_single_replica_compaction" = "false"
    );
    
        insert into `test_array_agg_decimal` values
(1, "alex",NULL,NULL,NULL),
(1, "LB", "V1_2",1,NULL),
(1, "LC", "V1_3",2,1.11),
(2, "LA", "V2_1",4,1.23),
(2, "LB", "V2_2",5,NULL),
(2, "LC", "V2_3",5,1.21),
(3, "LA", "V3_1",6,1.21),
(3, NULL, NULL,6,1.23),
(3, "LC", "V3_3",NULL,1.24),
(4, "LA", "V4_1",5,1.22),
(4, "LB", "V4_2",6,NULL),
(4, "LC", "V4_3",6,1.22),
(5, "LA", "V5_1",6,NULL),
(5, "LB", "V5_2",5,NULL),
(5, "LC", "V5_3",NULL,NULL),
(7, "", NULL,NULL,NULL),
(8, "", NULL,0,NULL);

mysql>  select id,map_agg(id,o_totalprice) from test_array_agg_decimal group by id;
+------+-------------------------------+
| id   | map_agg(`id`, `o_totalprice`) |
+------+-------------------------------+
|    1 | {1:111}                       |
|    2 | {2:121}                       |
|    3 | {3:124}                       |
|    4 | {4:122}                       |
|    5 | {5:NULL}                      |
|    7 | {7:NULL}                      |
|    8 | {8:NULL}                      |
+------+-------------------------------+
7 rows in set (5.92 sec)

### What You Expected?

Some aggregation functions such as map agg may drop the decimal point

### How to Reproduce?

_No response_

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mrhhsg**
## Proposed changes

FIX: https://github.com/apache/doris/issues/23775

Add also fix the `streaming_agg_serialize_to_column` function.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mrhhsg** [comment]
run buildall

**Comment by mrhhsg** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47.51 seconds
 stream load tsv:          531 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162014488 Bytes

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 47 seconds
 stream load tsv:          532 seconds loaded 74807831229 Bytes, about 134 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.2 seconds inserted 10000000 Rows, about 342K ops/s
 storage size: 17162098783 Bytes

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by xingyingone — APPROVED** [review]
LGTM

**Pull request merged**
