### PR TITLE
[doc](apache-superset)add doc for apache superset compatible

### PR DESCRIPTION
**Pull request by liujiwen-up**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
Is there any requirement for doris version?

**Comment by liujiwen-up** [comment]
> doris版本有要求吗？
Tested 2.0.x, 2.1, master version, all are compatible

**Comment by zy-kkk** [comment]
run buildall

**Review by zy-kkk — APPROVED** [review]

**Review by echo-hhj — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
