### PR TITLE
[opt](inverted index) support the same column create different type index

### PR DESCRIPTION
**Pull request by Tanya-W**
## Proposed changes

support the same column create different type index with different index name.

such like:
- create table with index:
```
CREATE TABLE table1
(
    id INT DEFAULT '10',
    name VARCHAR(32) DEFAULT '',
    INDEX index_1 (name) USING NGRAM_BF PROPERTIES("gram_size"="3", "bf_size"="256") COMMENT 'ngram_bf index',
    INDEX index_2 (name) USING INVERTED PROPERTIES("parser" = "english") COMMENT 'inverted index'
)
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES("replication_num" = "1"); 
```
- alter add index:
```
CREATE INDEX index_1 ON table1(name) USING NGRAM_BF PROPERTIES("gram_size"="3", "bf_size"="256") COMMENT 'ngram_bf index';
CREATE INDEX index_2 ON table1(name) USING INVERTED PROPERTIES("parser" = "english") COMMENT 'inverted index';
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Tanya-W** [comment]
run buildall

**Review by qidaye — DISMISSED** [review]
LGTM

**Comment by Tanya-W** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 52.64 seconds
 stream load tsv:          506 seconds loaded 74807831229 Bytes, about 140 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.5 seconds inserted 10000000 Rows, about 338K ops/s
 storage size: 17160882690 Bytes

**Review by xiaokang — DISMISSED** [review]
LGTM

**Comment by xiaokang** [comment]
add some case for ngram + inverted index

**Comment by Tanya-W** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 51.29 seconds
 stream load tsv:          505 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         19 seconds loaded 2358488459 Bytes, about 118 MB/s
 stream load orc:          65 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.4 seconds inserted 10000000 Rows, about 340K ops/s
 storage size: 17169606415 Bytes

**Comment by Tanya-W** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.43 seconds
 stream load tsv:          504 seconds loaded 74807831229 Bytes, about 141 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          32 seconds loaded 861443392 Bytes, about 25 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17164675764 Bytes

**Review by qidaye — APPROVED** [review]
LGTM

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
