### PR TITLE
[Chore](case) add order by to testIncorrectMVRewriteInSubquery

### PR DESCRIPTION
**Pull request by BiteTheDDDDt**
# Proposed changes

add order by to testIncorrectMVRewriteInSubquery

Exception:
java.lang.IllegalStateException: Check tag 'select_star' failed:
Check tag 'select_star' failed, line 1, INT result mismatch.
Expect cell is: 1
But real is: 2line 1 mismatch
ExpectRow: [2020-01-01, 1, a, 1]
RealRow: [2020-01-01, 1, a, 2]

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dataroaring** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run p0

**Comment by BiteTheDDDDt** [comment]
run buildall

**Comment by BiteTheDDDDt** [comment]
run buildall

**Review by luozenglin — APPROVED** [review]
LGTM

**Pull request merged**
