### PR TITLE
[Fix](inverted index) fix race condition for column reader load inverted index reader

### PR DESCRIPTION
**Pull request by airborne12**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by airborne12** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by eldenmoon — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run performance

**Review by xiaokang — APPROVED** [review]
LGTM

**Pull request merged**
