### PR TITLE
[Optimization](String) Optimize q20 q21 q22 q23 LIKE_SUBSTRING (like '%xxx%') 

### PR DESCRIPTION
**Pull request by ZhangYu0123**
# Proposed changes

Optimize q20, q21, q22, q23 LIKE_SUBSTRING (like '%xxxx%').  Idea is from clickhouse stringsearcher:

1.  Stringsearcher is about 10%~20% faster than volnitsky algorithm when needle size is less than 10 using two chars at beginning search in SIMD .
2. Stringsearcher is faster than volnitsky algorithm, when needle size is less than 21.

**The changes are as follows:**

1.  Using first two chars of needle at beginning search. We can compare two chars of needle and [n:n+17) chars in haystack in SIMD in one loop. Filter efficiency will be higher.
2. When env support SIMD, we use stringsearcher.

**Test result in clickbench:**

1. q20 is about 15% up. 
```
q20: SELECT COUNT(*) FROM hits WHERE URL LIKE '%google%';
```
2.  q21, q22 is about 1%~5% up.  
```
q21: SELECT SearchPhrase, MIN(URL), COUNT(*) AS c FROM hits WHERE URL LIKE '%google%' AND SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;
q22: SELECT SearchPhrase, MIN(URL), MIN(Title), COUNT(*) AS c, COUNT(DISTINCT UserID) FROM hits WHERE Title LIKE '%Google%' AND URL NOT LIKE '%.google.%' AND SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;
```
3.  q23 is about 30%~40% up and not stable.
```
q23: SELECT * FROM hits WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10;
```

-------
after：
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230402003237_clickbench_pr_123705.html
image

https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230402030931_clickbench_pr_123726.html
image

before:
https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230402003741_clickbench_pr_123714.html
image

https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230402063546_clickbench_pr_123743.html
image
Issue Number: close #xxx

## Problem summary

Describe your changes.

## Checklist(Required)

* [ ] Does it affect the original behavior
* [ ] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [ ] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 32.92 seconds
 stream load tsv:          439 seconds loaded 74807831229 Bytes, about 162 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          72 seconds loaded 1101869774 Bytes, about 14 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20230401145609_clickbench_pr_123652.html

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run clickbench

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run buildall

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
