### PR TITLE
[fix](delete) fix potential delete fail after adding columns

### PR DESCRIPTION
**Pull request by Hastyshell**
## Proposed changes

1. Move the column id related checks into delete handler.
2. Use column id radically in delete handler.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by luwei16 — APPROVED** [review]

**Comment by TangSiyang2001** [comment]
run buildall

**Comment by TangSiyang2001** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
