### PR TITLE
[Enhancement](table) adding information_schema.parameters table

### LINKED ISSUE #19626: [Enhancement] adding information_schema.parameters table
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

可参考：

https://dev.mysql.com/doc/refman/8.0/en/information-schema-parameters-table.html

这只是一个虚拟表，用于兼容mysql，不需要存储实际信息。

### Solution

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zhiyu-h**
## Proposed changes

Issue Number: close #19626

this is a virtual table for compatibility information_schema parameters table

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Zhiyu-h** [comment]
run buildall

**Comment by zgxme** [comment]
run buildall

**Comment by Zhiyu-h** [comment]
run P0

**Review by morningman — APPROVED** [review]
LGTM

**Review by AshinGau — APPROVED** [review]

**Pull request merged**
