### PR TITLE
[Fix](auto inc) Fix auto inc db id overflow

### PR DESCRIPTION
**Pull request by Yukang-Lian**
## Proposed changes

Issue Number: close #xxx

db_id, table_id and tablet_id should be int64_t instead of int32_t

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Yukang-Lian** [comment]
run buildall

**Comment by Yukang-Lian** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Comment by Yukang-Lian** [comment]
run performance

**Comment by Yukang-Lian** [comment]
run performance

**Comment by dataroaring** [comment]
run performance

**Pull request merged**
