### PR TITLE
[Fix](regression-test) Fix hive tpcds100 shapes.

### PR DESCRIPTION
**Pull request by kaka11chen**
## Proposed changes

- Fix hive tpcds100 shapes by #25866.
- Add `set enable_pipeline_engine=true.`

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morningman — APPROVED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Comment by zhangguoqiang666** [comment]
run external

**Review by zhangguoqiang666 — APPROVED** [review]
LGTM

**Comment by zhangguoqiang666** [comment]
run external

**Comment by zhangguoqiang666** [comment]
run external

**Comment by kaka11chen** [comment]
Because tpcds100 hive shape has been reverted, we will do this in the future.

**Pull request closed without merging**
