### PR TITLE
[fix] disk_info_mac DiskInfo::get_device_names sort

### PR DESCRIPTION
**Pull request by zjj**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Review by adonis0147 — APPROVED** [review]

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run external

**Comment by adonis0147** [comment]
run p0

**Comment by adonis0147** [comment]
run buildall

**Comment by adonis0147** [comment]
run p1

**Comment by adonis0147** [comment]
run p1

**Comment by adonis0147** [comment]
run cloud_p1

**Review by zxealous — APPROVED** [review]

**Pull request merged**
