### PR TITLE
[fix](fe ut) fix unstable test DecommissionBackendTest

### PR DESCRIPTION
**Pull request by yujun777**
fix unstable test DecommissionBackendTest.testDecommissionBackendWithDropTable by PR #25444
because it increase backend num.  The new create table 'tb1''s tablets maynot create on the decommission backend.

Also fix "alter system add backend",  because it's new create backend's state is alive = false;

## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Review by wm1581066 — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
