### PR TITLE
[Enhancement] Make array type config readable

### PR DESCRIPTION
**Pull request by xinghuayu007**
## Proposed changes

When a config is array type, `admin show frontend config` can not demonstrate the configuration correctly, like pic 1 `audit_log_modules`.
2021-05-10 19-28-16屏幕截图

This PR supports to demonstrate array type config content, like pic 2;
2021-05-10 19-34-15屏幕截图

## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Code refactor (Modify the code structure, format the code, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have created an issue on (Fix #ISSUE) and described the bug/feature there in detail
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If these changes need document changes, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by WindyGao** [comment]
hi
Is there some problems with TeamCity?
I encounter the same failure like follow PR
https://github.com/apache/incubator-doris/pull/5778

**Review by morningman — APPROVED** [review]
LGTM

**Comment by xinghuayu007** [comment]
> hi
> Is there some problems with TeamCity?
> I encounter the same failure like follow PR
> #5778

The test service is not stable, you can contact Doris manager.

**Comment by WindyGao** [comment]
> > hi
> > Is there some problems with TeamCity?
> > I encounter the same failure like follow PR
> > #5778
> 
> The test service is not stable, you can contact Doris manager.

probably rebase the master code can avoid this porblem...

**Comment by morningman** [comment]
The UT is not your problem, it has been fixed.

**Pull request merged**
