### PR TITLE
[fix](OrcReader) fix the issue that orc_reader can not read DECIMAL(0,0) type of orc file

### PR DESCRIPTION
**Pull request by BePPPower**
Because HIVE 0.11 & 0.12 does not support precision and scale for decimal
The decimal type of orc file produced by HIVE 0.11 & 0.12 are DECIMAL(0,0)
We should set a default precision and scale for these orc files.

### CODE REVIEW

**Comment by BePPPower** [comment]
run buildall

**Comment by BePPPower** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by BePPPower** [comment]
run external

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
