### PR TITLE
[BugFix](Concat) output of string concat function exceeds UINT makes crash

### PR DESCRIPTION
**Pull request by ByteYue**
# Proposed changes
The previously logic of concat function assumes all input string could be concat inside INT size buffer, user might accidentally input string parameters which could sum up to exceed the size.
Issue Number: close #xxx

## Problem summary
When input such query below be would coredump.
```
select
  concat(
    cast(substr(
      cast(ref_1.`cp_type` as varchar),
      cast(
        max(
          cast(ref_1.`cp_catalog_page_number` as int)) over (partition by ref_1.`cp_end_date_sk` order by ref_1.`cp_catalog_page_number`) as int),
      cast(ref_1.`cp_end_date_sk` as int)) as varchar),
    cast(substring(
      cast(ref_1.`cp_department` as varchar),
      cast(ref_1.`cp_end_date_sk` as int),
      cast(ref_1.`cp_end_date_sk` as int)) as varchar),
    cast(rpad(
      cast(ref_1.`cp_type` as varchar),
      cast(ref_1.`cp_start_date_sk` as int),
      cast(ref_1.`cp_description` as varchar)) as varchar)) as c1
from
  regression_test_tpcds_sf1_p1.catalog_page as ref_1
```
Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [x] No
    - [ ] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [x] No
    - [ ] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 38.03 seconds
 load time: 577 seconds
 storage size: 17154865250 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221102170638_clickbench_pr_38686.html

**Comment by yiguolei** [comment]
Please add sql based regression test.

**Comment by ByteYue** [comment]
> Please add sql based regression test.

Already added.

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
