### PR TITLE
[refactor](load) expand OlapTableValidator to VOlapTableBlockConvertor

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

Converting input block is closely related to validating input block.
This patch adds input block conversion into OlapTableValidator, and rename it to VOlapTableBlockConvertor.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by freemandealer — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
