### PR TITLE
[Opt](exec) opt the repeat node code

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes
DSQ86

Before ：3.2s
After：2.6s

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by hello-stephen** [comment]
run performance

**Review by wm1581066 — APPROVED** [review]
LGTM

**Review by mrhhsg — APPROVED** [review]
LGTM

**Pull request merged**
