### PR TITLE
[doc](disk)fix disk capacity doc error

### PR DESCRIPTION
**Pull request by zddr**
## Proposed changes

Issue Number: close #xxx

fix disk capacity doc error

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zddr** [comment]
run buildall

**Comment by zddr** [comment]
run p0

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]
LGTM

**Pull request merged**
