### PR TITLE
[Bug] fix using clause npe

### LINKED ISSUE #7953: [Bug] using clause npe
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```sql
create table A
(
    k1 int,
    k2 int,
    v1 int sum
)
DISTRIBUTED BY HASH(k1) BUCKETS 3;

insert into A values(1,3,7);
insert into A values(2,2,8);
insert into A values(3,1,9);

create table B
(
    k1 int,
    k2 int,
    k3 int
)
DISTRIBUTED BY HASH(k1) BUCKETS 3;

insert into B values(1,3,1);
insert into B values(3,1,1);
insert into B values(4,1,1);
insert into B values(5,2,1);

select t1.* from A t1 join B t2 using(k1,k2) where t1.k1 between 1 and 3 and t2.k3 between 1+0 and 3+0;

ERROR 1064 (HY000): errCode = 2, detailMessage = Unexpected exception: null
```
### What You Expected?

no error

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qzsee**
# Proposed changes

Issue Number: close #7953

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No Need)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
HI @qzsee , Could you please add the case you described in #7953 to the QueryPlanTest.java?

**Comment by qzsee** [comment]
> HI @qzsee , Could you please add the case you described in #7953 to the QueryPlanTest.java?

done

**Review by morningman — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
Hi @qzsee , sorry for the late reply.
Please rebase the master to resolve the conflict.

**Comment by morningman** [comment]
hi @qzsee , looks like you did something wrong with the rebase?

**Comment by qzsee** [comment]
> hi @qzsee , looks like you did something wrong with the rebase?

Sorry ，Now is ok

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
