### PR TITLE
[Chore](metrics) remove trace metrics code using runtime profile instand

### PR DESCRIPTION
**Pull request by ZhangYu0123**
## Proposed changes

1. remove trace metrics code  and use runtime profile instand

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ZhangYu0123** [comment]
run buildall

**Comment by ZhangYu0123** [comment]
run p1

**Review by yiguolei — APPROVED** [review]
LGTM

**Comment by yiguolei** [comment]
Great job, thanks for your contribution

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
