### PR TITLE
[opt](merge-on-write) Skip the alignment process of some rowsets in partial update #38487

### PR DESCRIPTION
**Pull request by bobhan1**
## Proposed changes

picks https://github.com/apache/doris/pull/38487

regression cases are commented currently.

### CODE REVIEW

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run buildall

**Comment by bobhan1** [comment]
run p0

**Comment by bobhan1** [comment]
run p1

**Comment by bobhan1** [comment]
run p1

**Comment by zhannngchen** [comment]
run p1

**Comment by bobhan1** [comment]
run buildall

**Pull request merged**
