### PR TITLE
[Improve](table-function) explode json array with json args 

### PR DESCRIPTION
**Pull request by amorynan**
## Proposed changes
backport: https://github.com/apache/doris/pull/37278
https://github.com/apache/doris/pull/39572
Issue Number: close #xxx

### CODE REVIEW

**Comment by amorynan** [comment]
run buildall

**Comment by amorynan** [comment]
run buildall

**Review by xiaokang — APPROVED** [review]
LGTM

**Comment by amorynan** [comment]
run buildall

**Pull request merged**
