### PR TITLE
[fix](Nereids) should push project through limit after eliminate union node

### PR DESCRIPTION
**Pull request by morrySnow**
other wise:

push limit through union could generate plan:

```
limit
+-- union
    |-- limit
    |   +-- empty relation
    +-- limit
        +-- project
```

and then eliminate union will generate plan:

```
+-- limit
    +-  project
        +-- limit
            +-- project
```

it could not be processed by tranlator correctly

## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run buildall

**Comment by morrySnow** [comment]
run feut

**Comment by morrySnow** [comment]
run external

**Comment by morrySnow** [comment]
run buildall

**Review by 924060929 — APPROVED** [review]

**Review by starocean999 — APPROVED** [review]

**Pull request merged**
