### PR TITLE
[pipeline](datagen) Improve datagen operator parallelism

### PR DESCRIPTION
**Pull request by Gabriel39**
## Proposed changes

Now we use ``` DataGenOperator (num_instance=1) -> ResultSinkOperator(num_instance=1) ``` for loading/query tasks.

This PR use a local shuffle to improve its parallelism and the plan is 
``` DataGenOperator (num_instance=1) -> LocalExchangeSink (num_instance=1) -> LocalExchangeSource (num_instance=(cores / 2) -> ResultSinkOperator(num_instance=(cores / 2)) ```

### CODE REVIEW

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Comment by Gabriel39** [comment]
run buildall

**Review by Mryange — APPROVED** [review]

**Review by BiteTheDDDDt — APPROVED** [review]

**Pull request merged**
