### PR TITLE
[fix](tablet io error) fix tablet not increase _io_error_times in some cases.

### PR DESCRIPTION
**Pull request by yujun777**
When read/write a tablet,  if meet io error,  it will increase this tablet's field `_io_error_times`.  And if `_io_error_times` >= config::max_tablet_io_errors,  then be will report this tablet as bad,   then fe can drop it later.

But there are a lot of code that may met an io error!  And they may forget to increase this tablet's  _io_error_times.  
This PR only fix some,  there should be others not fixed.

What's more,   config::max_tablet_io_errors of be.conf  default value is -1.  It means always no set tablet as bad. For an online cluster, it shoud manually set this parameter > 0 in order to make it work.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run beut

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run p0

**Comment by yujun777** [comment]
run cloud_p0

**Review by deardeng — APPROVED** [review]
LGTM

**Pull request merged**
