### PR TITLE
[feature](profile) profilev2 distinguish Sink and Operator in pipelineX

### PR DESCRIPTION
**Pull request by Mryange**
## Proposed changes
```
PLAN  FRAGMENT  2

    PARTITION:  HASH_PARTITIONED:  lo_orderkey

    STREAM  DATA  SINK
        EXCHANGE  ID:  4660
        HASH_PARTITIONED:  d_year,  p_brand


    4657:VAGGREGATE  (update  serialize)
    |    STREAMING
    |    output:  partial_sum(lo_revenue)[#93]
    |    group  by:  d_year,  p_brand
    |    cardinality=300,018,951
    |    Operator:  
    |        Instance  num  :  8
    |        BlocksReturned:  8
    |        CloseTime:  avg  46.763us,  max  56.81us,  min  37.857us
    |        OpenTime:  avg  20.457us,  max  22.247us,  min  18.530us
    |        RowsReturned:  2.24K  (2240)
    |        TotalTime:  avg  365.394us,  max  443.390us,  min  279.527us
    |    Sink:  
    |        Instance  num  :  8
    |        CloseTime:  avg  2.674us,  max  3.274us,  min  2.235us
    |        InputRows:  4.7908M  (4790800)
    |        OpenTime:  avg  76.286us,  max  83.717us,  min  71.846us
    |        TotalTime:  avg  358.77ms,  max  383.583ms,  min  310.991ms
    |    
    4651:VHASH  JOIN
    |    join  op:  INNER  JOIN(BROADCAST)[]
    |    equal  join  conjunct:  lo_orderdate  =  d_datekey
    |    runtime  filters:  RF002[in_or_bloom]  <-  d_datekey(-1/0/2097152)
    |    cardinality=600,037,902
    |    vec  output  tuple  id:  11
    |    vIntermediate  tuple  ids:  10  
    |    hash  output  slot  ids:  4  75  77  
    |    Operator:  
    |        Instance  num  :  8
    |        BlocksReturned:  1.92K  (1920)
    |        CloseTime:  avg  19.204us,  max  25.965us,  min  15.557us
    |        OpenTime:  avg  69.838us,  max  81.579us,  min  63.196us
    |        ProbeRows:  4.7908M  (4790800)
    |        ProjectionTime:  avg  6.317ms,  max  6.959ms,  min  4.891ms
    |        RowsReturned:  4.7908M  (4790800)
    |        TotalTime:  avg  89.640us,  max  98.862us,  min  79.352us
    |    Sink:  
    |        Instance  num  :  8
    |        InputRows:  2.556K  (2556)
    |        OpenTime:  avg  158.922us,  max  187.671us,  min  147.882us
    |        TotalTime:  avg  457.145us,  max  1.584ms,  min  264.362us
    |    
    |----4648:VEXCHANGE
    |              offset:  0
    |              Operator:  
    |                  Instance  num  :  8
    |                  BlocksReturned:  1
    |                  CloseTime:  avg  11.117us,  max  15.272us,  min  8.372us
    |                  OpenTime:  avg  68.936us,  max  79.580us,  min  61.298us
    |                  RowsReturned:  2.556K  (2556)
    |                  TotalTime:  avg  85.606us,  max  125.387us,  min  70.692us
    |              Sink:  
    |                  Instance  num  :  1
    |                  BlocksSent:  1
    |                  CloseTime:  avg  41.152us,  max  41.152us,  min  41.152us
    |                  InputRows:  2.556K  (2556)
    |                  OpenTime:  avg  113.23us,  max  113.23us,  min  113.23us
    |                  TotalTime:  avg  197.68us,  max  197.68us,  min  197.68us
    |        
    4641:VHASH  JOIN
    |    join  op:  INNER  JOIN(BROADCAST)[]
    |    equal  join  conjunct:  lo_suppkey  =  s_suppkey
    |    runtime  filters:  RF001[in_or_bloom]  <-  s_suppkey(-1/0/2097152)
    |    cardinality=600,037,902
    |    vec  output  tuple  id:  9
    |    vIntermediate  tuple  ids:  8  
    |    hash  output  slot  ids:  64  24  59  60  61  62  63  
    |    Operator:  
    |        Instance  num  :  8
    |        BlocksReturned:  1.92K  (1920)
    |        CloseTime:  avg  22.29us,  max  28.617us,  min  16.414us
    |        OpenTime:  avg  52.906us,  max  57.943us,  min  49.619us
    |        ProbeRows:  4.826478M  (4826478)
    |        ProjectionTime:  avg  10.864ms,  max  11.680ms,  min  9.178ms
    |        RowsReturned:  4.7908M  (4790800)
    |        TotalTime:  avg  75.660us,  max  83.522us,  min  66.718us
    |    Sink:  
    |        Instance  num  :  8
    |        InputRows:  40.125K  (40125)
    |        OpenTime:  avg  151.66us,  max  160.933us,  min  141.457us
    |        TotalTime:  avg  2.361ms,  max  17.94ms,  min  215.131us
```

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run feut

**Comment by Mryange** [comment]
run buildall

**Comment by Mryange** [comment]
run p1

**Review by yiguolei — APPROVED** [review]
LGTM

**Review by HappenLee — APPROVED** [review]
LGTM

**Pull request merged**
