### PR TITLE
[improvement](balance) partition rebalance chose disk by rr

### PR DESCRIPTION
**Pull request by yujun777**
Partition rebalance will call function takeAnAvailBalanceSlotFrom to chose disk. But this function prefer to choose the first disk. This PR make this function chose disk by RR.

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Review by deardeng — APPROVED** [review]
LGTM

**Review by dataroaring — DISMISSED** [review]
LGTM

**Comment by yujun777** [comment]
run buildall

**Comment by yujun777** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
