### PR TITLE
[fix](partition) Fix be tablet partition id eq 0 By report tablet

### PR DESCRIPTION
**Pull request by deardeng**
## Proposed changes

Issue Number: close #xxx

修复升级到203之后遇到的be tablet 中 partition id为0

1. 通过be report tablet 汇报到fe的tablet 中partition id 判断是否一致
2. 若不一致产生一个update tablet task，让be修复，并打印相关warning log

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by deardeng** [comment]
3副本，mock了2副本中的tablet partition id 为0，修复后的效果
image
image

**Review by yujun777 — APPROVED** [review]
LGTM

**Review by yujun777 — APPROVED** [review]
LGTM

**Comment by dataroaring** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Comment by deardeng** [comment]
run buildall

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
