### PR TITLE
[fix](nereids) Fix query mv rewrite fail when mv cache build quickly

### PR DESCRIPTION
**Pull request by seawinde**
## Proposed changes

Fix query rewrite fail by mv when mv build interval  is short and cache update quickly.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by seawinde** [comment]
run buildall

**Comment by seawinde** [comment]
run buildall

**Review by morningman — DISMISSED** [review]

**Review by keanji-x — APPROVED** [review]

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — DISMISSED** [review]

**Comment by seawinde** [comment]
run buildall

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
