### PR TITLE
[bugfix](hudi)add timetravel for nereids

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

1. add timetravel for nereids.

```
select * from tb FOR TIME AS OF "2024-07-24 19:58:43";
select * from tb FOR TIME AS OF "20240724195843";
```
2. Add ugi authentication to the thread pool

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by wsjz — APPROVED** [review]
LGTM

**Review by hubgeter — APPROVED** [review]
LGTM

**Pull request merged**
