### PR TITLE
[fix](planner) Fix table sample not take effect

### PR DESCRIPTION
**Pull request by xinyiZzz**
## Proposed changes

Modify `computeSampleTabletIds` location. table sample not take effect because selectedIndexId=-1 in computeSampleTabletIds, the previous run FE UT had special processing, so FE UT did not discover the BUG in time.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by morrySnow — COMMENTED** [review]
add some test case please

**Comment by xinyiZzz** [comment]
run buildall

**Comment by xinyiZzz** [comment]
> add some test case please

table sample not take effect because `selectedIndexId=-1` in `computeSampleTabletIds`, the previous run FE UT had special processing, so FE UT did not discover the BUG in time.
```
if (FeConstants.runningUnitTest && selectedIndexId == -1) {
     selectedIndexId = olapTable.getBaseIndexId();
}
```

**Review by Jibing-Li — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]

**Pull request merged**
