### PR TITLE
[Fix] add hll param for if function

### PR DESCRIPTION
**Pull request by qzsee**
# Proposed changes

Issue Number: close #xxx

## Problem summary

ERROR 1105 (HY000): errCode = 2, detailMessage = No matching function with signature: if(boolean, hll, hll)

Describe your changes.

## Checklist(Required)

1. Does it affect the original behavior: 
    - [x] Yes
    - [ ] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [ ] No
5. Are there any changes that cannot be rolled back:
    - [x] Yes (If Yes, please explain WHY)
    - [ ] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by cambyzju** [comment]
Which SQL print the error message?

**Comment by qzsee** [comment]
> 

SELECT
 hll_union_agg(if(xxx='xxx', xx_id, hll_empty()))
from xxx
where xxx = '2022-08-10'
and xx = '110000'

**Comment by qzsee** [comment]
> Which SQL print the error message?

SELECT
hll_union_agg(if(xxx='xxx', xx_id, hll_empty()))
from xxx
where xxx = '2022-08-10'
and xx = '110000'

**Comment by yiguolei** [comment]
pls add regression test for it

**Comment by qzsee** [comment]
> pls add regression test for it

done

**Review by yiguolei — APPROVED** [review]
LGTM

**Pull request merged**
