### PR TITLE
Use LongAdder or volatile long to replace AtomicLong in some scenarios

### PR DESCRIPTION
**Pull request by caiconghui**
## Proposed changes
This PR is to use LongAdder or volatile long to replace AtomicLong in some scenarios.
In the statistical summation scenario, LongAdder(introduced by jdk1.8) has better performance than AtomicLong in high concurrency update scenario. And if we just want to keep get and set operation for variable to be atomic, just add volatile at the front of the variable is enough, use AtomicLong is a little heavy.
NOTE: LongAdder is usually preferable to AtomicLong when multiple threads update a common sum that is used for purposes such as collecting statistics, not for fine-grained synchronization control, such as auto-incremental ids.
## Types of changes

What types of changes does your code introduce to Doris?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on [#4132 ](https://github.com/apache/incubator-doris/issues/4132), and have described the bug/feature there in detail
- [ ] Commit messages in my PR start with the related issues ID, like "#4071 Add pull request template to doris project"
- [x] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I have updated the document
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by caiconghui** [comment]
for #4132

**Comment by kangkaisen** [comment]
@caiconghui Hi，how many performance improvement this PR will get?

**Comment by caiconghui** [comment]
> @caiconghui Hi，how many performance improvement this PR will get?
@kangkaisen 
for single AtomicLong value and single LongAdder value, i test increment opertion with 30 threads in 2 seconds in my macbook, and I find the Throughput increased by about 60%  when i used LongAdder instead of AtomicLong.

as for volatile long and AtomicLong, the performance is almost same, but if volatile can be enough to ensure thread-safe, then we should take a more lightweight solution.

**Comment by kangkaisen** [comment]
> > @caiconghui Hi，how many performance improvement this PR will get?
> > @kangkaisen
> > for single AtomicLong value and single LongAdder value, i test increment opertion with 30 threads in 2 seconds in my macbook, and I find the Throughput increased by about 60%  when i used LongAdder instead of AtomicLong.
> 
> as for volatile long and AtomicLong, the performance is almost same, but if volatile can be enough to ensure thread-safe, then we should take a more lightweight solution.

OK

**Review by kangkaisen — APPROVED** [review]
+1, LGTM

**Pull request merged**
