### PR TITLE
[fix](reader) fix leak in Level1Iteartor

### PR DESCRIPTION
**Pull request by w41ter**
_merge_next() and _normal_next() leak _cur_child when _cur_child->next() returns failure.

### CODE REVIEW

**Comment by w41ter** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.96 seconds
 stream load tsv:          550 seconds loaded 74807831229 Bytes, about 129 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.0 seconds inserted 10000000 Rows, about 344K ops/s
 storage size: 17162020441 Bytes

**Comment by gavinchou** [comment]
LGTM

**Review by gavinchou — APPROVED** [review]

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by w41ter** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 46.2 seconds
 stream load tsv:          537 seconds loaded 74807831229 Bytes, about 132 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          31 seconds loaded 861443392 Bytes, about 26 MB/s
 insert into select:          29.1 seconds inserted 10000000 Rows, about 343K ops/s
 storage size: 17161988950 Bytes

**Review by morningman — APPROVED** [review]
LGTM

**Pull request merged**
