### PR TITLE
[Fix](profile) clean profile stmt can't clean all fe node profile

### PR DESCRIPTION
**Pull request by qzsee**
## Proposed changes

Issue Number: close #xxx

### CODE REVIEW

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Review by nextdreamblue — APPROVED** [review]
LGTM

**Comment by qzsee** [comment]
run buildall

**Comment by qzsee** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Comment by nextdreamblue** [comment]
LGTM

**Pull request merged**
