### PR TITLE
[regressioncase](nereids)check  stats and log memo for tpcds_sf1_unique_p1/query46

### PR DESCRIPTION
**Pull request by englefly**
## Proposed changes

Issue Number: close #xxx

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run buildall

**Comment by englefly** [comment]
run p1 10

**Comment by englefly** [comment]
run p0

**Comment by englefly** [comment]
run p1

**Comment by englefly** [comment]
run p1

**Review by starocean999 — APPROVED** [review]

**Review by hello-stephen — APPROVED** [review]

**Comment by hello-stephen** [comment]
run feut

**Comment by hello-stephen** [comment]
run beut

**Comment by hello-stephen** [comment]
run clickbench

**Review by LiBinfeng-01 — APPROVED** [review]

**Pull request merged**
