### PR TITLE
[fix](load) fix core in flush_single_memtable when publish_txn

### LINKED ISSUE #20572: [Bug] core in flush_single_memtable when publish_txn
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master (325ddab34e9a26ab32ac5ddcc9db3feaeb9b6e5f)

### What's Wrong?

```
start time: Thu 08 Jun 2023 03:07:45 AM CST
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/ssd01/doris-master/NEREIDS_ASAN/be/lib/hadoop_hdfs/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/ssd01/doris-master/NEREIDS_ASAN/be/lib/java-udf-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
*** Query id: 0-0 ***
*** Aborted at 1686164932 (unix time) try "date -d @1686164932" if you are using GNU date ***
*** Current BE git commitID: 296ca1d9dd ***
*** SIGSEGV address not mapped to object (@0x30) received by PID 2585749 (TID 2587763 OR 0x7f1ac0677700) from PID 48; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/doris_master/doris/be/src/common/signal_handler.h:413
 1# 0x00007F2D806770A7 in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 3# 0x00007F2D8067002C in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
 4# 0x00007F2D9A1630C0 in /lib/x86_64-linux-gnu/libc.so.6
 5# std::_Function_base::_M_empty() const at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:248
 6# std::function<doris::Status (int)>::operator()(int) const at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:558
 7# doris::BetaRowsetWriter::flush_single_memtable(doris::vectorized::Block const*, long*, doris::FlushContext const*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/rowset/beta_rowset_writer.cpp:497
 8# doris::Tablet::calc_delete_bitmap(std::shared_ptr<doris::Rowset>, std::vector<std::shared_ptr<doris::segment_v2::Segment>, std::allocator<std::shared_ptr<doris::segment_v2::Segment> > > const&, std::unordered_set<doris::RowsetId, doris::HashOfRowsetId, std::equal_to<doris::RowsetId>, std::allocator<doris::RowsetId> > const*, std::shared_ptr<doris::DeleteBitmap>, long, doris::RowsetWriter*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/tablet.cpp:2865
 9# doris::Tablet::update_delete_bitmap(std::shared_ptr<doris::Rowset> const&, doris::TabletTxnInfo const*, doris::RowsetWriter*) at /home/zcp/repo_center/doris_master/doris/be/src/olap/tablet.cpp:3102
10# doris::TxnManager::publish_txn(doris::OlapMeta*, long, long, long, int, doris::UniqueId, doris::Version const&) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:371
11# doris::TxnManager::publish_txn(long, std::shared_ptr<doris::Tablet> const&, long, doris::Version const&) at /home/zcp/repo_center/doris_master/doris/be/src/olap/txn_manager.cpp:169
12# doris::TabletPublishTxnTask::handle() at /home/zcp/repo_center/doris_master/doris/be/src/olap/task/engine_publish_version_task.cpp:230
13# doris::EnginePublishVersionTask::finish()::$_0::operator()() const at /home/zcp/repo_center/doris_master/doris/be/src/olap/task/engine_publish_version_task.cpp:166
14# void std::__invoke_impl<void, doris::EnginePublishVersionTask::finish()::$_0&>(std::__invoke_other, doris::EnginePublishVersionTask::finish()::$_0&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
15# std::enable_if<is_invocable_r_v<void, doris::EnginePublishVersionTask::finish()::$_0&>, void>::type std::__invoke_r<void, doris::EnginePublishVersionTask::finish()::$_0&>(doris::EnginePublishVersionTask::finish()::$_0&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
16# std::_Function_handler<void (), doris::EnginePublishVersionTask::finish()::$_0>::_M_invoke(std::_Any_data const&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
17# std::function<void ()>::operator()() const at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
18# doris::FunctionRunnable::run() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:48
19# doris::ThreadPool::dispatch_thread() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:531
20# void std::__invoke_impl<void, void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(std::__invoke_memfun_deref, void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
21# std::__invoke_result<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>::type std::__invoke<void (doris::ThreadPool::*&)(), doris::ThreadPool*&>(void (doris::ThreadPool::*&)(), doris::ThreadPool*&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
22# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:420
23# void std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>::operator()<, void>() at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/functional:503
24# void std::__invoke_impl<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
25# std::enable_if<is_invocable_r_v<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&>(std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()>&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117
26# std::_Function_handler<void (), std::_Bind<void (doris::ThreadPool::*(doris::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
27# std::function<void ()>::operator()() const at /var/local/ldb_toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:560
28# doris::Thread::supervise_thread(void*) at /home/zcp/repo_center/doris_master/doris/be/src/util/thread.cpp:465
29# start_thread at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:478
30# __clone in /lib/x86_64-linux-gnu/libc.so.6 
```

### What You Expected?

should not core

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kaijchen**
## Proposed changes

ctx might be nullptr, which causes the following core

Fix #20572

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by kaijchen** [comment]
run buildall

**Review by zhannngchen — DISMISSED** [review]
LGTM

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by kaijchen** [comment]
run buildall

**Review by zhannngchen — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Pull request merged**
