### PR TITLE
[Refactor](exec) remove the unless file and refactor the agg code

### PR DESCRIPTION
**Pull request by HappenLee**
## Proposed changes

1. delete the file：be/src/vec/utils/count_by_enum_helpers.hpp
2. move code to：be/src/vec/aggregate_functions/aggregate_function_count_by_enum.h

### CODE REVIEW

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Comment by HappenLee** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by Mryange — APPROVED** [review]

**Pull request merged**
