### PR TITLE
[fix](Nereids) fix nullable() of lead/lag

### PR DESCRIPTION
**Pull request by YangShaw**
# Proposed changes

Issue Number: close #xxx

## Problem summary
fix bug when we use NULL as default value for window function lead() and lag().

## Checklist(Required)

* [ ] Does it affect the original behavior
* [x] Has unit tests been added
* [ ] Has document been added or modified
* [ ] Does it need to update dependencies
* [x] Is this PR support rollback (If NO, please explain WHY)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by YangShaw** [comment]
run buildall

**Comment by YangShaw** [comment]
run p0

**Comment by YangShaw** [comment]
run p0

**Comment by YangShaw** [comment]
run p0

**Review by morrySnow — APPROVED** [review]

**Comment by morrySnow** [comment]
run compile

**Pull request merged**
