### PR TITLE
[improvement](statistics)Drop column stats after schema change.

### PR DESCRIPTION
**Pull request by Jibing-Li**
Drop column stats after schema change. So the auto analyze could be triggered and will collect stats under new schema.

### CODE REVIEW

**Comment by Jibing-Li** [comment]
run buildall

**Comment by Jibing-Li** [comment]
run cloud_p0

**Comment by Jibing-Li** [comment]
run cloud_p1

**Review by morningman — APPROVED** [review]
LGTM

**Review by morrySnow — APPROVED** [review]

**Pull request merged**
