### PR TITLE
[opt](coord) use single instance only with small limit

### PR DESCRIPTION
**Pull request by morningman**
## Proposed changes

Followup #31342
When executing simple query like `select * from tbl limit 1`.
Doris will use only one instance for each scan node, to reduce the fan-out of simple queries.
But if the limit number is large, eg, 1 billion, this logic is not suitable.

So I add a new session variable `limit_rows_for_single_instance`, default is 10000.
Only if the limit number is lower than this value, Doris will use one instance for scan node.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Review by HappenLee — DISMISSED** [review]
LGTM

**Review by yiguolei — DISMISSED** [review]
LGTM

**Comment by morningman** [comment]
run buildall

**Review by yiguolei — APPROVED** [review]

**Review by Gabriel39 — APPROVED** [review]

**Pull request merged**
