### PR TITLE
[bugfix](hive)fix testcase for test_hive_write_different_path

### PR DESCRIPTION
**Pull request by wuwenchi**
## Proposed changes

Hive's test environment uses docker, so when using 127.0.0.1, BE will write the file to the docker of its own machine. But if FE and  are not on the same machine, FE cannot read this file because it can only read docker on its own machine. Therefore, the address 127.0.0.1 cannot be used in the test environment.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run buildall

**Comment by wuwenchi** [comment]
run external

**Comment by wuwenchi** [comment]
run buildall

**Review by morningman — APPROVED** [review]
LGTM

**Review by zy-kkk — APPROVED** [review]

**Pull request merged**
